### ISSUE TITLE
Reproduced: Connak message is not properly handled! Subscriptions are lost when QoS 2 is used. 'Connect' event is not called after the reconnect

### ISSUE THREAD

**Issue by ievgennaida** [mqttjs/MQTT.js#1001]
Hello
I have struggled a lot with a client stop receiving messages (lost subscriptions) when connection is lost with the broker but finally I have reproduced it.

**Pre Requirements:** 
1. "mosca": "2.8.3",
2. "mqtt": "3.0.0"
3. At least one **QoS = 2** message should be send before the connection loss with the broker. 

**STR:**
1. Start the broker.
2. Start the client.
3. Send the message QoS 2 
4. Stop the broker and wait 5 sec. 
5. Start the broker.
6. Send the message with any QoS. 
7. See that client has no 'connected' event while broker is reporting that client is connected. 
See that message from the step 6 is not received. P.s. connack message is send by a broker but not handler properly by a mqtt.js. 
  
Code:
```
const { Server } = require("mosca");
let port = 8885;

function initBroker() {
  const settings = {
    port: port
  };

  let broker = new Server(settings);
  // fired when the mqtt server is ready
  broker.on("ready", function() {
    console.log("Broker: Ready");
  });

  // fired when a message is received
  broker.on("published", function(packet, client) {
    //console.log("Published", packet.payload);
  });

  broker.on("clientConnected", function(client) {
    console.log("Broker: client connected: " + client.id);
  });

  broker.on("clientDisconected", function() {
    console.log("Broker: client disconected");
  });

  return broker;
}

broker = initBroker();

const mqtt = require("mqtt");

const senderOptions = {
  host: "mqtt://localhost",
  port: port,
  keepalive: 30,
  clientId: "client"
};

let client = mqtt.connect(
  senderOptions.host + ":" + senderOptions.port,
  senderOptions
);

client.on("reconnect", () => {
  console.log("Client: reconnect");
});

client.on("connect", () => {
  console.log("Client: connect");
  client.subscribe("data", { qos: 2 });
});

client.on("message", async (topic, message) => {
  console.log("Client: message recieved:" + topic + ". " + message);
});

// STR:
// Check that message with QoS 2 is send when server is connected.
setTimeout(() => {
  client.publish("data", "message when connected", { qos: 2 });
}, 1000);

// Simulate lost connection
setTimeout(() => {
   broker.close(() => {
     console.log("Broker: Closed");
   });
}, 5000);

// Start new broker.
setTimeout(() => {
  // Start new broker.
   broker = initBroker();
}, 8000);

// Publish new message. This message is never recieved. 
setTimeout(() => {
  client.publish("data", "message when restarted.");
}, 10000);

```

**Log when initially QoS 1 is sent (Correct behavior)**
```
Broker: Ready
Broker: client connected: client
Client: connect
Client: message recieved:data. message when connected
Broker: Closed
Client: reconnect
Broker: Ready
Client: reconnect
Broker: client connected: client
Client: connect
Client: message recieved:data. message when restarted.
```

**Log when initially  QoS 2 is sent ('connect' event is missing)**
```
Broker: Ready
Broker: client connected: client
Client: connect
Client: message recieved:data. message when connected
Broker: Closed
Client: reconnect
Broker: Ready
Client: reconnect
Broker: client connected: client
```

**Note: see that when QoS 2 is send 'connect' event is missing and all new published messages are missing** 

**Some observations:**
This is happens while store.js is not properly cleaned up when connack message is handled.
1. Store.prototype.del is never called for the QoS 2 while called for QoS 1 
2. When there are qos2 messages in the store 'end' event is never called on a 
client.js  so 'connect' and subscribe does not triggered.
```
`  outStore.on('end', function () {
      var allProcessed = true
      for (var id in that._packetIdsDuringStoreProcessing) {
        if (!that._packetIdsDuringStoreProcessing[id]) {
          allProcessed = false
          break
        }
      }
      if (allProcessed) {
        clearStoreProcessing()
        that.removeListener('close', remove)
        that.emit('connect', packet)
      } else {
        startStreamProcess()
      }
    })
```

@mcollina   Could you please check that?  I would assume that client should handle qos 2 properly even when when mosca does not support it. 

Thanks in advance!

```
{
  "dependencies": {
    "mosca": "2.8.3",
    "mqtt": "3.0.0"
  }
}
```

**Comment by Ridarso** [comment]
hai, @ievgennaida has you solve this problem? I have face same issue like you but I use mosquitto as broker.

**Comment by ievgennaida** [comment]
I use mosquitto broker as well. With the code above issue is always reproducible. As a workaround, I am using QoS1 only. If you will be able to find a better solution, please post it, thanks.
