### ISSUE TITLE
Publish fails silently if payload is too big.

### ISSUE THREAD

**Issue by spydmobile** [mqttjs/MQTT.js#1005]
This code will work:
`mqttClient.publish("intellifire/ember/allfires", JSON.stringify(wildfires.slice(0, 2000)))`
this will fail silently and reconnect:
`mqttClient.publish("intellifire/ember/allfires", JSON.stringify(wildfires.slice(0, 2500)))`

**Comment by RangerMauve** [comment]
Transferring this issue to the main MQTT.js repository since I don't think it's caused by the async layer.

**Comment by spydmobile** [comment]
Hi I am sorry, I do not think this is caused by mqtt.js or the async layer, I went into my broker and configured a larger packet limit and it is now working. So unless you feel there is work to be done about the error, i think this was not really a bug....

**Comment by RangerMauve** [comment]
Sweet, thanks for double checking! Hopefully this issue will help people figure their situation out when this comes up for them. 😁
