### ISSUE TITLE
Can't publish 3000 msg/sec using mqtts

### ISSUE THREAD

**Issue by muhamedcpqd** [mqttjs/MQTT.js#1007]
I was trying to publish 3000 msg/sec with the client using mqtts, but using only the publish function I can only achieve a maximum of 500 msg/sec. I already tried to use setInterval with 3 ms and using a loop of 10 iteration (10 msg in 3 ms in each execution) but it was useless, the mqtt client hanged around 500~600 msg/sec. There is a way to achieve this throughput using the mqtt js lib????

**Comment by jimmiehansson** [comment]
Are you using a specific storage while doing this?

**Comment by muhamedcpqd** [comment]
I already solved the problem.. the service i developed did not correctly consumed the data to send to the mqtt publisher. I will close this issue. Thanks anyway.
