### ISSUE TITLE
Building with Webpack have issues with  #!/usr/bin/env node in mqtt.js

### ISSUE THREAD

**Issue by savnik** [mqttjs/MQTT.js#1008]
When building with webpack on seed.run following webpack error occours:

`Serverless: Bundling with Webpack...
ERROR in /tmp/seed/source/node_modules/async-mqtt/node_modules/mqtt/mqtt.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node`

Following the webpack issue list here is a similar type of issues: https://github.com/webpack/webpack/issues/4603

They add appropriate loaders to to the webpack configuration.
This could probably be resolved within the MQTT package instead of in each project?

**Comment by GauravWable** [comment]
i am also facing error with webpack

`npm ERR! code ELIFECYCLE
npm ERR! errno 3221226505
npm ERR! ble-collect@1.0.0 start: `webpack && qode ./dist/index.js`
npm ERR! Exit status 3221226505
npm ERR!`

**Comment by hieutranagi47** [comment]
I am facing the same problem with #!/usr/bin/env node. I use webpack to build my node cli tool.

**Comment by savnik** [comment]
@hieutranagi47 I did a dirty fix and forked the mqtt lib and removed shebang. 
This fixed the issue for me temporary.
https://www.npmjs.com/package/mqtt-no-shebang

**Comment by hieutranagi47** [comment]
> @hieutranagi47 I did a dirty fix and forked the mqtt lib and removed shebang.
> This fixed the issue for me temporary. In order to use it, i have put it into a package.
> https://www.npmjs.com/package/mqtt-no-shebang

Thank Savnik so much! I'll try it. :)

**Comment by savnik** [comment]
I see there is a fix in place now. I will test it and if all okay, i will deprecate the temporary fix in https://www.npmjs.com/package/mqtt-no-shebang
