### ISSUE TITLE
Mqtt client is connected to cloudmqtt but can't publish and subscribe

### ISSUE THREAD

**Issue by aqieez** [mqttjs/MQTT.js#1009]
const mqtt = require('mqtt');
  const express = require('express');
  const app= express();
 
 var host = 'mqtt://farmer.cloudmqtt.com';
 
 var options = {
     port : 16567,
     clientId: 'mqttjs_' + Math.random().toString(16).substr(2, 8),
     user :'username',
     password: 'Password'
    
 };
 app.listen(3000, () => {
    var client  = mqtt.connect(host, options);
   client.on('connect', function() { 
    console.log("client is connected");
  });
  client.publish('sup','hi there this is client',function(){
    console.log("message published successfully");
  });
 });
I am using node js with mqtt module to connect with my cloudmqtt. when i start my node js server i can see a connection in cloudmqtt i am not getting client.on function running to show me some information if i am connected on not. Also i am not able to publish any message. but in cloudmqtt it's showing that i am connected. Please help

**Comment by jigneshk5** [comment]
Use this project: https://github.com/CloudMQTT/mqtt-sse
as refernce
