### ISSUE TITLE
How to connect using CA signed server certificate

### ISSUE THREAD

**Issue by renerlemes** [mqttjs/MQTT.js#1011]
I need to connecto to my broker with SSL/TLS Version = Auto and SSL/TLS Certificate Type = CA signed server certificate

**Comment by jdiamond** [comment]
From the README:

> In case mqtts (mqtt over tls) is required, the `options` object is
passed through to [`tls.connect()`](http://nodejs.org/api/tls.html#tls_tls_connect_options_callback).

From those docs for `tls.connect()`, click on `tls.createSecureContext()` where it says:

> ...: [`tls.createSecureContext()`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) options that are used if the secureContext option is missing,

Now you can see you need to pass in a `ca` property containing the loaded certificate from your CA.

**Comment by medilies** [comment]
hello guys! this 
> In case mqtts (mqtt over tls) is required, the options object is passed through to tls.connect().
makes me feel like a noob!

I really can't figure out how to use my **ca.crt** to connect to the mosquitto

**Comment by jdiamond** [comment]
Here is a working example:

```
const mqtt = require('mqtt');
const fs = require('fs');

const client = mqtt.connect('mqtts://test.mosquitto.org', {
  ca: fs.readFileSync('mosquitto.org.crt'),
});

client.on('connect', () => {
  console.log('connected');
});
```

You can get mosquitto.org.crt from here: https://test.mosquitto.org/ssl/mosquitto.org.crt

**Comment by medilies** [comment]
hey @jdiamond  in case of a CA generated locally with openSSL will passing it in options.ca be fine ?

**Comment by jdiamond** [comment]
Yeah, doesn't matter who generated it as long as it's in the right format and valid. That's probably how the mosquitto cert was generated.

**Comment by chimiwangchuk** [comment]
is there possibility to do certs based authentication for IOT connection in browser?

**Comment by robertsLando** [comment]
@chimiwangchuk nope, you should use wss

**Comment by chimiwangchuk** [comment]
@robertsLando Thank you much for reply. Is there any specific reasons why it is not allowed from browser?

I tried to overwrite protocol as 'mqtt' or 'mqtts' as well but in browser it takes as 'wss' only

**Comment by robertsLando** [comment]
It's a browser limitation, it's for security reason, browser only accepts the certificates that come with the site not others
