### ISSUE TITLE
Cannot be installed(compiled) with nodejs 12.13.0 on ubuntu 16

### ISSUE THREAD

**Issue by fedulovivan** [mqttjs/MQTT.js#1012]
Trying to install it globally with ```yarn global add mqtt``` and got a bunch of [compilation-errors.txt](https://github.com/mqttjs/MQTT.js/files/3875351/compilation-errors.txt)

FYI with nodejs 10.15.1 everything is ok.

**Comment by diegovasquesmellet** [comment]
Do you have any updates on this?
I'm only able to build MQTT properly when using version 8.9.4.

I tried to build using 10.15.1 and 12.13.1 and both of them fails due to some test issues:

  625 passing (2m)
  3 failing

  1) MqttClient
       connecting
         should connect to the broker:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) MqttClient
       MQTT 5.0
         connecting
           should connect to the broker:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  3) MqttSecureClient
       connecting
         should connect to the broker:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by fedulovivan** [comment]
@mcollina you probably need to run some test mqtt broker to launch tests for this project
