### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by pwlan** [mqttjs/MQTT.js#1013]
Hi,

i have a question. When I import 'mqtt' i get "Invalid or unexpected token". The problem is related to the first line "#!/usr/bin/env node" in mqtt.js. 
What am i doing wrong?

I am using nodejs v13.1.0 on ubuntu.

**Comment by fedulovivan** [comment]
Its and executable js script
so instead of running as ```node mqtt.js``` use ```chmod +X mqtt.js && mqtt.js```

**Comment by pwlan** [comment]
Thank you for the quick response. I seem to have found the problem. It has to do with the node version. It works fine with node v12.
I am integrating mqtt.js as a client within my node server.
```
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://test.mosquitto.org')
....
```
