### ISSUE TITLE
DOMException: "The operation is insecure."

### ISSUE THREAD

**Issue by cory-weiner** [mqttjs/MQTT.js#1014]
I have deployed my VueJS application to netlify. My app works fine on my local machine, and the production deployment works in Chrome, but Firefox gives the following error when you hit 'connect' (which is calling client.connect() from mqtt.js library)

`mqtt.connect(this.host+':'+this.port,{clientId:this.clientId})`

`DOMException: "The operation is insecure."`

You can see a working example here:
https://inspiring-beaver-f90fa7.netlify.com/

**Comment by jimmiehansson** [comment]
I'm unfortunately not able to reproduce this using a Linux Firefox ESR 60.9.X (64-bit) instance. Can you provide further details about the browser you're using and what version/platform its occurring in?

**Comment by cory-weiner** [comment]
Thanks for looking at this. This is actually resolved now. The issue is my production environment was serving over HTTPS and Firefox blocks websocket connections from HTTPS to non encrypted websocket servers (ws instead of wss).

It is working now that I've switched to wss test server.

**Comment by jamieduk** [comment]
how do i setup wws easyily and for free can you help? how did you resolve this or did you have to pay for hosting or something?
