### ISSUE TITLE
Handling reconnection is weird

### ISSUE THREAD

**Issue by david114** [mqttjs/MQTT.js#1015]
Hi,
the on `error` event handles a disconnection from the broker, without actually doing anything.
so i have this code:

```
client.on('error', (err) => { 
  console.log("Connection loss, trying to reconnect");
});
```

as you may see, I'm not doing anything but printing to the console. but the client keeps trying to reconnect every second until I'm reconnected to the broker again (which is exactly what i want)

my problem now is, when I'm deleting this piece of code the client suddenly won't try to reconnect and I'm receiving an error. 

Do I really need to put a` client.on('error', (err) => { });` into my code in order to handle a connection loss?

**Comment by jimmiehansson** [comment]
This would make sense if there is no callback attached to the `error` event previously as yours instead would be the return in that context. Can you provide further details on how you connect the client and where this is occurring?

**Comment by david114** [comment]
My connection code looks like this:

```
const options = {
  host: process.env.HOST,
  port: 8883,
  protocol: 'mqtts',
  rejectUnauthorized: true,
  username: process.env.USERNAME,
  password: process.env.PASSWORD,
};

const client = mqtt.connect(options);

```
It's happening when the client loses conenction to the broker.

**Comment by jimmiehansson** [comment]
Thanks David! Can you run a test on this with the output thrown from the error event. Such as:

```js
client.on('error', (err) => { 
  console.log(err);
});
```

**Comment by david114** [comment]
```
Error: connect ECONNREFUSED XXXXXXX:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: 'XXXXXXXX',
  port: 8883
}
```

**Comment by jimmiehansson** [comment]
I think what is happening here is that the listener for error which controls the stream being used doesn't force a new attempt unless the `error` listener has been emitted to. Whether this is an intended behavior by not destroying the previous stream if necessary or a case where error should be wrapped internally is beyond my knowledge of this library at this point. I'm sure @mcollina could give further insight. A ECONNREFUSED would indicate a broken pipe but this should be handled silently by the client unless the emitted listener is required like you proposed
