### ISSUE TITLE
Connect failed with RN release build

### ISSUE THREAD

**Issue by hungthuanmk** [mqttjs/MQTT.js#1016]
I am building a React Native (v0.61) app with MQTT.js (3.0.0)
Everything works well in Debug.  When I build APK and deploy on my friend's phone (Android 8) it can work normally but on my phone (Android 9) is not.
I have tried some packages but they seem too old and not compatible more.

**Comment by hungthuanmk** [comment]
Ref solved solution:
https://stackoverflow.com/questions/59112767/react-native-mqtt-js-does-not-work-on-android-9

**Comment by hungthuanmk** [comment]
Ref solved solution:
https://stackoverflow.com/questions/59112767/react-native-mqtt-js-does-not-work-on-android-9

**Comment by huuthinh95** [comment]
@hungthuanmk Can you share me a source code that run mqtt.js on react native. I can't use mqtt.js in react native app.

**Comment by robertsLando** [comment]
@hungthuanmk Use latest version 5.2.2
