### ISSUE TITLE
Doesn't seem possible to unsubscribe from events like: connect or offline

### ISSUE THREAD

**Issue by timhoeppner** [mqttjs/MQTT.js#1017]
Using VueJs and subscribing to 'connect' and 'offline' events to monitor broker status. There doesn't seem a way to unsubscribe from these events. Tried using off() but its not defined.

Need to be able to unsubscribe from these events so that I can control subscription to these events on a VueJs component level.

**Comment by jdiamond** [comment]
Use `removeListener` instead of `off`.
