### ISSUE TITLE
Documentation about Reconnection handling 

### ISSUE THREAD

**Issue by fabik111** [mqttjs/MQTT.js#1019]
Hi,
I had added a callback on the `offline` event that, in case is fired, it  will call the `reconnect()` method.   
But I've experienced some re-connection loop after the first offline event, so I've deduced that there is already a re-connection policy.
Can you improve the documentation about `reconnect()` method and default re-connection attempts?

**Comment by PHPJourney** [comment]
Hi, How do you solution this question？
I cannot use reconnect function. It's like not running

**Comment by fabik111** [comment]
Hi,
I don't use reconnect function, I think there is already an auto re-connection policy, so if you lose connectivity automatically it re-establish the connection. My issue is not about a bug but about bad documentation

**Comment by PHPJourney** [comment]
> Hi,
> I don't use reconnect function, I think there is already an auto re-connection policy, so if you lose connectivity automatically it re-establish the connection. My issue is not about a bug but about bad documentation
I'm not see automatically it re-establish the connection work. My app in wi-fi offline state. wait a moment open it. It's can't reconnect.

**Comment by fabik111** [comment]
I'm sorry but I can't help you, also for me this is unknown
