### ISSUE TITLE
Improve mqtt client packet queues

### ISSUE THREAD

**Issue by adamvr** [mqttjs/MQTT.js#102]
They're pretty hacked together now, and the process for adding packets to them is pretty brittle (e.g. `this.inflight.unsuback[this.nextId++] = callback;`).

Also as mentioned by @mcollina in #101, make it so we can store the queues somewhere else than in memory, such as a redis store or a file.

Possibly implemented overridable functions e.g.

    MqttClient.prototype._queuePacket = function(type, packet) {
        // Add to gross memory queues
    });
   
    MqttClient.prototype._nextPacket = function(type) {
        // Read next packet from gross memory queues
    });

    // Later...
    client._queuePacket = function(type, packet) {
        redis.lpush('mqttjs:'+type, packet);
    });

    client._nextPacket = function(type, cb) {
        redis.rpop('mqttjs:'+type, cb);
    });

**Comment by mcollina** [comment]
Done in 1.0.0.
