### ISSUE TITLE
Unable to resolve module `url` from `node_modules/mqtt/lib/connect/index.js

### ISSUE THREAD

**Issue by pavankumarkl** [mqttjs/MQTT.js#1020]
Is this the library issue, do I have to install any other module?

**Comment by pavankumarkl** [comment]
got it, had to change import from 'mqtt/dist/mqtt' instead of ''mqtt'

**Comment by SignDawn** [comment]
It's a way, but it loses the type prompt. Is there a better way?

**Comment by ashiqdey** [comment]
Just use this [package ](https://www.npmjs.com/package/precompiled-mqtt) instead which is build version of mqtt 4.3.7

**Comment by ErickGiffoni** [comment]
> Just use this [package ](https://www.npmjs.com/package/precompiled-mqtt) instead which is build version of mqtt 4.3.7

Didn't work out for me since I'm using typescript and the `precompiled-mqtt` does not have a @types/precompiled-mqtt yet

**Comment by simonmysun** [comment]
solved [here](https://github.com/mqttjs/MQTT.js/issues/1412#issuecomment-1193363330). hope it helps.
