### ISSUE TITLE
Hello, does mqtt.js support custom exchange?Because now the local connection is rabbitmq.I would really appreciate your reply.

### ISSUE THREAD

**Issue by hc-1994** [mqttjs/MQTT.js#1024]

**Comment by jdiamond** [comment]
Exchanges are not part of the MQTT protocol and are specific to RabbitMQ. You can configure the MQTT plugin to use a custom exchange and then all messages received via MQTT will go to that exchange. See [here](https://www.rabbitmq.com/mqtt.html) for more information on configuring the MQTT plugin.
