### ISSUE TITLE
MQTT.js does not accept passwords with special characters 

### ISSUE THREAD

**Issue by AVancans** [mqttjs/MQTT.js#1025]
My mosquito server password contained a character `^` which seemed to be working via command-line interface `mqtt pub -t "test" -u "user" -P "pasSw^rd" -m "Hello"`, however, it did not work from the nodejs script. 

```
mqtt.connect({
    host: '***',
    port: 1883,
    username: 'user',
    password: 'pasSw^rd',
});
```

Would always result in `Error: Connection refused: Not authorized`.

After 4 hours of debugging (and trying out different approaches on how to pass credentials, how to specify host etc) I changed the password to one not containing `^` and it worked.

There seems to be inconsistency - why does the command line and the server accept `^` in the password, but MQTT.js client doesn't?

**Comment by jdiamond** [comment]
This doesn't really make sense since the `mqtt` command-line tool that comes with MQTT.js uses MQTT.js.

I just did a test with the same password and it worked fine.

```
❯ cat make-passwd.sh
#!/bin/sh

printf "pasSw^rd\npasSw^rd\n" | mosquitto_passwd -c mosquitto.passwd user
```

```
❯ cat mosquitto.conf
listener 1883 127.0.0.1
password_file mosquitto.passwd
```

```
❯ cat start-broker.sh
#!/bin/sh

/usr/local/sbin/mosquitto -c mosquitto.conf
```

```
❯ ./start-broker.sh
1577475077: mosquitto version 1.6.8 starting
1577475077: Config loaded from mosquitto.conf.
1577475077: Opening ipv4 listen socket on port 1883.
```

```
❯ cat test.js
#!/usr/bin/env node

const mqtt = require('mqtt');

const client = mqtt.connect('mqtt://127.0.0.1', {
  username: 'user',
  password: 'pasSw^rd'
});

client.on('connect', () => {
  console.log('connected');
});
```

```
❯ ./test.js
connected
^C
```

If you can share minimal steps to reproduce like I did above, please reopen.

**Comment by AVancans** [comment]
@jdiamond, this morning trying to reproduce the issue - everything works fine. Go figure, lol.
Not sure what was the issue - maybe I had to restart my client instance as it was freshly installed environment. Sorry for the false alarm.
