### ISSUE TITLE
cannot connect to 'ws://test.mosquitto.org:8080' but its mqtt port

### ISSUE THREAD

**Issue by tiffanytut0225** [mqttjs/MQTT.js#1027]
below is my client source code within react app
```javascript
options = {
      keepalive: 60,
      reconnectPeriod: 1000,
      connectTimeout: 30 * 1000,
      protocolId: 'MQIsdp',
      protocolVersion: 3,
      path: '/mqtt'
    }
    url = 'ws://test.mosquitto.org:8080/' // replace with 'mqtt://test.mosquitto.org/' is ok to connect
    client = mqtt.connect(url, options)
```
i can not figure it why it is ok to connect mqtt port but not websocket. Should i have other settings for websocket?
the error message is "Connection closed before receiving a handshake response"
thanks!

**Comment by ysfscream** [comment]
@tiffanytut0225 I think you should replace your URL to `ws://test.mosquitto.org:8080/mqtt`

**Comment by tiffanytut0225** [comment]
@ysfscream 
thank you for your reply :)
i had replace my URL, but it still cannot connect.

![image](https://user-images.githubusercontent.com/42331417/74585784-b9d05a00-501b-11ea-95d9-214534c22b36.png)

**Comment by ysfscream** [comment]
@tiffanytut0225 OK. I tested it just now, it seems that it is not connected, it may be a problem with mosquitto.
