### ISSUE TITLE
always disconnect in when connect

### ISSUE THREAD

**Issue by YamiNguyen2609** [mqttjs/MQTT.js#1031]
import mqtt from 'mqtt'
    const client = mqtt.connect('mqtt://XXX.XXX.XXX.XXX', {
        port: 1883,
      })  
      client.on("connect", () => {
        console.log('connected')
      }) <------ not working
      But when I call "close" event is working
      client.on("close", () => {
        console.log('close')
      }) <------ working
I try this #573 but not working with me, please help me

**Comment by manikandasankar** [comment]
Facing same issue.

**Comment by manikandasankar** [comment]
Facing same issue.

**Comment by YamiNguyen2609** [comment]
hi @manikandasankar . I use sp-react-native-mqtt to replace it and It's working with me, try it :D

**Comment by manikandasankar** [comment]
@YamiNguyen2609 **sp-react-native-mqtt** doesn't provide support ssl connection using **ca, cert, key** files.

**Comment by YoDaMa** [comment]
closing since @YamiNguyen2609 has resolved their issue.
