### ISSUE TITLE
Exception "WebSocket is not connected" while end()

### ISSUE THREAD

**Issue by naiyu** [mqttjs/MQTT.js#1032]
I want to close the connection by using the mqtt.Client#unsubscribe() and mqtt.Client#end(), it has close the connection but throws the exception "webSocket is not connected".
it is that something wrong while I close the connection? How to fix it?

**Comment by jdiamond** [comment]
Are you waiting for the unsubscribe() callback before calling end()?

**Comment by liuricong** [comment]
Call end () in the unsubscribe () callback the same error is "closeSocket:fail WebSocket is not connected"

**Comment by YoDaMa** [comment]
Could be related to: https://github.com/websockets/ws/issues/353
