### ISSUE TITLE
The client keeps node alive if end() is called before the connection is established

### ISSUE THREAD

**Issue by kkeri** [mqttjs/MQTT.js#1033]
If I set up an MQTT connection and for some reason, I want to exit the program during startup, calling `client.end()` is not enough to quit the event loop. The process hangs up for some 90 seconds before exiting. Although if I wait a few seconds to allow the connection to be established and only then I call `client.end()`, node exits as expected. Here is a sample that produces the issue.

~~~
const mqtt = require('mqtt')

const client = mqtt.connect('tcp://localhost')

client.on('connect', () => {
  console.log(`connected to broker`)
})

client.on('close', () => {
  console.log(`connection closed`)
})

const delay = 0 // but try 5000 instead

setTimeout(() => client.end(), delay)
~~~

**Comment by jdiamond** [comment]
Thanks for the script to reproduce.

I changed delay to 5000, saw it log the connect message, then the closed message 5 seconds later, and 
 then the process immediately exited.

I'm running Node.js v12.14.0 on macOS. What about you? Also, what broker are you running on localhost? I tested with test.mosquitto.org.

**Comment by jdiamond** [comment]
Based on your edits, can confirm that setting delay to 0 does hang for 90 seconds.

**Comment by kkeri** [comment]
Thanks for the confirmation. Btw. I'm on Windows 10, using node v10.15.1 and mosquitto version 1.5.8.
