### ISSUE TITLE
Is there a way to see the currently subscribed channels?

### ISSUE THREAD

**Issue by DennisOosterling** [mqttjs/MQTT.js#1035]
So basically the question in the title.

Having some issues with the client not unsubscribing on a component unMount function. As a work around I would like to unsubscribe from all unrelevant channels when necessary. Must I keep track of my active subscriptions myself or can I somehow get this information from the client?

**Comment by jdiamond** [comment]
The client keeps a list of topics to resubscribe to when it reconnects in `_resubscribeTopics`, but that's supposed to be a "private" field. I would track it myself.
