### ISSUE TITLE
CDNJS for MQTT.JS

### ISSUE THREAD

**Issue by NervenCid** [mqttjs/MQTT.js#1056]
Hello to all:

I'm new on MQTT and i saw in the documentation that is possible to use it from the browser (but it is neccessary to build it again).

I wonder if it is possible to publish a cdn version of MQTT.JS on CDNJS (https://cdnjs.com/)

Thank you and sorry for my poor english

**Comment by kartben** [comment]
I'm assuming you could simply rely on https://unpkg.com?

Le dim. 23 févr. 2020 à 17:25, NervenCid <notifications@github.com> a
écrit :

**Comment by NervenCid** [comment]
@kartben 

Thank you for your answer, i am not familiar with the tool, but i mean that a CDN could be more easy to use in a frontend.

isn't it?

**Comment by joltmode** [comment]
@NervenCid unpkg.com already is a CDN.

Just use: https://unpkg.com/mqtt/dist/mqtt.min.js

**Comment by kartben** [comment]
@NervenCid please re-open if you have further questions or if we misunderstood your original request!
Thanks --
