### ISSUE TITLE
Browserified version seems to convert some payloads to strings

### ISSUE THREAD

**Issue by Pakkes** [mqttjs/MQTT.js#1064]
Hi,
I'm facing a strange behavior while using the browserified version of the MQTT.js library. 
It seems that some payloads are converted to strings. For example:

- `mqtt.publish("world", "Hello!")` --> The broker gets "Hello!" (please note the 2 0x22 chars " delimiting the message
- If I try to publish a binary content the broker gets the JS representation of the object and not the supposed stream. For example: 
`var msg = msgpack.encode("Hello");`
`mqtt.publish("world", "Hello!");` --> The broker gets `{"type":"Buffer","data":[.....]}`

The broker I use is Aedes.
I've downloaded the ready-to-use version found here [https://unpkg.com/mqtt/dist/mqtt.min.js](url) and the created my version by using browserify: same results...

Is there a parameter I need to use or some guidelines I have to follow in order to obtain the correct payload stream?

Really many thanks in advance for your help. Regards

**Comment by mcollina** [comment]
What's your broker code?

**Comment by Pakkes** [comment]
Hi.
The problem is that not only the broker, but also clients subscribed to topics received the wrong stream.
However ... maybe you've pointed me in the right direction.
My nodeJS broker starts 3 servers

1) server for pure MQTT protocol
2) server for WS protocol
3) server for WSS protocol

Only the trafic on server 1 (mqtt) behaves as expected. Maybe I have to instruct aedes to manage payloads received over WS and WSS protocols by expecting binary buffers and similar?

By the way, this is the main broker code which starts the listener:
```
var aedes = require('aedes')();
var fs = require('fs');
var http = require('http');
var https = require('https');
var net = require('net'); 
var tls = require('tls');
var ws = require('websocket-stream');

var optionsTls = {
    key: fs.readFileSync('.....'),
    cert: fs.readFileSync('......'),
    rejectUnauthorized: true
}

var serverMqtt_tls = tls.createServer(optionsTls, aedes.handle);
serverMqtt_tls.listen(10001, function () {
    console.log('Server TLS listening on port 10001');
})

var httpServer_WS = http.createServer();
ws.createServer({ server: httpServer_WS }, aedes.handle);
httpServer_WS.listen(10004, function () {
    console.log('Websocket server listening on port 10004');
})

var httpsServer_WS_TLS = https.createServer(optionsTls);
ws.createServer({ server: httpsServer_WS_TLS }, aedes.handle);
httpsServer_WS_TLS.listen(10005, function () {
    console.log('Websocket server with TLS listening on port 10005');
})
```

**Comment by Pakkes** [comment]
I really apologize for wasting your precious time with this (supposed) issue. It's not an issue, but a problem caused by me. I finally found the error: I converted every payload with JSON.stringify(payload) before send it !!!! Please remove this entry, since it's not an issue.
