### ISSUE TITLE
Old browsers doesn't work

### ISSUE THREAD

**Issue by Ermak-13** [mqttjs/MQTT.js#1067]
Old browsers doesn't work because result (bundle) js has es6 code. Below, steps for repeating problem. If I use mqtt/dist/mqtt then it works (all is good). 
**Suggest:** set 'main' or 'browser' key as dist/mqtt [in package.json]
**Reason:** mqtt > mqtt-packet > debug [es6]

```
// index.js
var mqtt = require('mqtt');

```
```
// webpack.config.js
const path = require('path');

module.exports = {
  mode: 'production',
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, "dist")
  }
}
```

```
npm i es-check
webpack
npx es-check es5 dist/main.js
```

**RESULT**
ES-Check: there were 1 ES version matching errors.

          ES-Check Error:
          ----
          · erroring file: dist/main.js
          · error: SyntaxError: Unexpected token (2501:25)
          · see the printed err.stack below for context
          ----

**Comment by xty1992a** [comment]
move dist/main.js to you project from node_modules;

via babel covert it to es5
