### ISSUE TITLE
flushVolatile causes an error

### ISSUE THREAD

**Issue by oroszgergely** [mqttjs/MQTT.js#1068]
If the mqtt broker (mosquitto) restarts, then the node client tries to reconnect, but always returns this error.
Anybody knows why this happens?

Reconnect MQTTí
Connecting MQTT
MQTT closed
Subscribed to #
Error: Connection closed
    at /node_modules/mqtt/lib/client.js:105:29
    at Array.forEach (<anonymous>)
    at flushVolatile (/node_modules/mqtt/lib/client.js:103:24)
    at Socket.<anonymous> (/node_modules/mqtt/lib/client.js:304:5)
    at Socket.emit (events.js:311:20)
    at TCP.<anonymous> (net.js:668:12)

here is my config: 
let mqtt_options = {
    clientId: Math.random().toString(36).substring(7),
    port: 1883,
    keepalive: 60,
    debug: true,
    clean: true,
    protocolId: 'MQIsdp',
    protocolVersion: 3,
};

**Comment by JacopoDaeli** [comment]
I've the same issue. Problem is happening with AWS IoT. @oroszgergely have you found out?

**Comment by JacopoDaeli** [comment]
Actually I just figure out mine.
This possibly happens if your client does not have the right to subscribe to the topic.
