### ISSUE TITLE
Is client.on an outdated API? Why not in the document?

### ISSUE THREAD

**Issue by wuyouxin** [mqttjs/MQTT.js#1069]

**Comment by Andreyooo** [comment]
Not sure what you mean. Check example in readme on how it´s used.

**Comment by YoDaMa** [comment]
yeah seems like a strange question... maybe you meant something else? If so, reopen. Otherwise I am closing this.

**Comment by wuyouxin** [comment]
Is 'client.on' an outdated API? Why not in the document?

**Comment by YoDaMa** [comment]
https://github.com/mqttjs/MQTT.js#example
