### ISSUE TITLE
How to differenciate devices/users on mqtt.js?

### ISSUE THREAD

**Issue by NervenCid** [mqttjs/MQTT.js#1072]
Hello:

I'm developing a web app with mqtt protocol using mosquitto and mqtt.js, by my limited understood the pub/sub logic is in the form.

    mosquitto_pub -h <host> -p <port> -t <topic> -m "message"

and

    mosquitto_sub -h <host> -p <port> -t <topic>

.

I read that is possible to put a username and password but if i understand is for the entire broker server, but i need to differentiate each device/user (in the app the user can create/delete multiple unique devices with their own different measures but the topics could be the same between users or devices), and make difficult to a third party to access data via console(only knowing the topic assuming that the topic name could be the same between users/devices), i wonder if it is possible to use tokens, oauth, or something similar on mqtt.js.

Thank you and sorry for the english.

**Comment by jdiamond** [comment]
Mosquitto can control which topics different users can access. Look up the `acl_file` option. Mosquitto also supports plugins that let you do custom authentication, but I've never used that and don't know how it works.

At my work, we use [Aedes](https://github.com/moscajs/aedes) as our broker which is very easy to extend. Devices authenticate with unique usernames and passwords we manage in a database and users authenticate with OAuth tokens in the password field. As far as MQTT.js is concerned, it's just a string in the password field and the broker can verify it however it wants.

**Comment by NervenCid** [comment]
Thank you @jdiamond for your answer.

So Aedes works like a library inside the server or it is a different broker

**Comment by jdiamond** [comment]
I guess I would call it a different broker, but you have to write a Node.js script to run it. See this example: 

https://github.com/moscajs/aedes/blob/master/example.js

To do custom authentication, you would add an "authenticate" handler:

https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-authenticate-client-username-password-callback

**Comment by Andreyooo** [comment]
In mosquitto you can set username/password for many different users. If that`s what you are looking for refer to this [](http://www.steves-internet-guide.com/mqtt-security-mechanisms/)
