### ISSUE TITLE
[bug] Mqttjs v4 client emits error on close

### ISSUE THREAD

**Issue by robertsLando** [mqttjs/MQTT.js#1082]
After updating to v4 now clients gets an error when closing using `end`. Is this expected?

https://github.com/moscajs/aedes/pull/479#event-3284370393

**Comment by YoDaMa** [comment]
@robertsLando v4 does permit new errors to be emitted via the client, but are you saying that the client emits an error every time a call to `end` is made?

**Comment by robertsLando** [comment]
@YoDaMa I have just double checked  the code and I saw that in the failing tests the 'problem' was that broker is closed after the client without waiting the client close callback, so this caused broker to close client stream before it closes successfully and the error is triggered. So  everything is fine here :)
