### ISSUE TITLE
Update documentation for client "reconnectPeriod" option.

### ISSUE THREAD

**Issue by burritoIand** [mqttjs/MQTT.js#1083]
In exploring the use of this library I've been trying to wrap my head around how reconnection works etc.

The documentation in the readme states "milliseconds, interval between two reconnections". Meanwhile I am using mqtt to connect to AWS IoT service and their v2 iot js sdk uses another aws common library called [aws-crt for nodejs](https://github.com/awslabs/aws-crt-nodejs/blob/master/lib/browser/mqtt.ts#L123). In that library you'll notice the default value for `reconnectPeriod` is `0`, whereas the default value in this library is `1000`.

I noticed that when the value is set to `0`, my client will close and then never try to reconnect again. This led me to look at the source code which makes it clear that if the value is 0 then it does not schedule a reconnection.

https://github.com/mqttjs/MQTT.js/blob/d764f02552639e9fed0f2b2039ca86d9941ba0cb/lib/client.js#L940
https://github.com/mqttjs/MQTT.js/blob/d764f02552639e9fed0f2b2039ca86d9941ba0cb/lib/client.js#L904
https://github.com/mqttjs/MQTT.js/blob/d764f02552639e9fed0f2b2039ca86d9941ba0cb/lib/client.js#L651

It's not clear from the documentation that setting `reconnectPeriod: 0` will make the client flush the connection at end and not try to reconnect. Also please correct me if I'm wrong about how that works. If it's true, I feel like the AWS library should also tell users that setting `reconnectPeriod` to 0 means the client will not reconnect upon disconnection.

*Side Note*: I think it'd be very helpful to have a dedicated "Reconnection" section in this documentation towards the top that describes how reconnection works and how to refresh the client option data using transformWsUrl. The transformWsUrl docs are at the bottom and also aren't clear that you _can_ manipulate more than the url in that hook. For instance I needed to update the `options.username` and `options.clientId`.
```
  transformWsUrl(url, options, client) {
    // update client options with latest auth data.
    client.options.username = `${this.prefix}&token=${this.token}`;
    client.options.clientId = `${this.clientId}`;

    return url;
  }

```
related:
https://github.com/mqttjs/MQTT.js/issues/533  - resolved question on updating reconnect data
https://github.com/mqttjs/MQTT.js/issues/602 - questions answered below & will be added to readme reconnection section
https://github.com/mqttjs/MQTT.js/issues/1019 - resolved question on updating reconnect docs
https://github.com/mqttjs/MQTT.js/issues/828 - resolved question on transformWsUrl promise support (does not support)
https://github.com/mqttjs/MQTT.js/issues/761 - resolved question on how to update reconnect options

**Comment by YoDaMa** [comment]
@burritoIand I would not only agree with you I would encourage you to take what has been learned in your sleuthing and add it to the documentation here 😄 I might recommend expanding the API section for the boolean `reconnecting`, as well as adding a separate section between `Debug Logs` and `API`, for `About Reconnecting`

**Comment by burritoIand** [comment]
@YoDaMa haha ok yeah I'll open a pr shortly! Figured I'd open this to kick start it.

**Comment by burritoIand** [comment]
@YoDaMa attempting to add some color to the questions posed in https://github.com/mqttjs/MQTT.js/issues/602:

* `If the first connection attempt does not succeed, will there be a reconnection attempt?` - Yes, if the `close` event is emitted for whatever reason, the client will continuously attempt to reconnect as long as `reconnectPeriod` is > 0 and `reconnectPeriod` < `connectTimeout` (bug https://github.com/mqttjs/MQTT.js/issues/419).

* `If the first connection attempt succeeds and then fail, will there be a reconnection attempt?` - Yes, see above.

* `What are the other events that would happen in each scenario, regarding 'error', 'close', 'offline'` - Reconnection is triggered by a `close` event being emitted. During the reconnection process the `offline` event is emitted, followed by the `reconnect` event, and if a packet fails to send, `error` may be emitted.

* `Is it required to re-subscribe in each 'connect' event?` - All topics will automatically be resubscribed if `client.options.resubscribe` is `true` (default) and `client.options.reconnectPeriod` is greater than `0` (1000ms default).

* `Will a "publish" attempt during a reconnection return an error immediately or be queued?` - TBD

* `Will a "publish" attempt before the first connection succeed?` - Oddly yes (I think), but this may be due to a small bug where the `client.publish()` method only checks that a client isn't disconnecting while not also checking that it's connected (https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L488). 

* `Will the "reconnect" event happen for the first connection attempt?` - Reconnect event does not happen for first connection unless it drops and reconnects.

Also updated above list of related PR's that could be closed by these docs updates..

**Comment by burritoIand** [comment]
feel free to add/edit, then I can add to readme, we can close the other issues and close this :)

**Comment by YoDaMa** [comment]
> Will a "publish" attempt during a reconnection return an error immediately or be queued? - TBD
This seems like a difficult question to answer. Does this mean the client is in the process of reconnecting and emits a publish while recreating the stream? I am unclear on the behaviour this would have.

These are useful FAQs but a bit too niche for the documentation at this point. They can serve as reference for people to look up by existing in the issues though.

**Comment by jdiamond** [comment]
MQTT.js queues packets when not connected which then get flushed when the connection is made. This is even for qos 0 publishes and is separate than the store for qos > 0 publishes. Works with other packet types like subscribe, too.

https://github.com/mqttjs/MQTT.js/blob/28243fc6ec53c2f30efe154ff11fa3d71b30618b/lib/client.js#L227-L228

**Comment by burritoIand** [comment]
@jdiamond ah ok yeah that makes sense.. so any package that's published will end up in the queue if it's not sent immediately..

@YoDaMa ok yeah that makes sense, will close this :)
