### ISSUE TITLE
How to skip the send of puback/pubrec during error

### ISSUE THREAD

**Issue by avwarez** [mqttjs/MQTT.js#1089]
Hi,
 I'm trying to correctly manage Errors in my subscriber's callback, but when I throw a new Error(...) the puback/pubrec is already sent, so the script dies and I have lost the event.
```
client.on('message', function (topic, message) {
   console.log('client.on message')

   var data = message.toString();

   var options = {
      hostname: 'nas',
      port: 9000,
      path: '/',
      method: 'POST',
      headers: {
         'Content-Type': 'application/json',
         'Content-Length': data.length
      }
   }

   var req = httpwrapper.request(options, (res) => {
      res.setEncoding('utf8')

      res.on('data', (chunk) => {
         if (res.statusCode != 200) {
            // throw new Error('res.statusCode=' + res.statusCode)
         }
      })
   })
   req.write(data)
   req.end()
})
```
Looking at the MQTT.js code I found this block, but I cannot understand how "instruct" node to set error=new Error() and force the process flow to enter inside the "if (error)":
```
  debug('_handlePublish: qos %d', qos)
  switch (qos) {
    case 2: {
      options.customHandleAcks(topic, message, packet, function (error, code) {
        if (!(error instanceof Error)) {
          code = error
          error = null
        }
        if (error) { return that.emit('error', error) }
        if (validReasonCodes.indexOf(code) === -1) { return that.emit('error', new Error('Wrong reason code for pubrec')) }
        if (code) {
          that._sendPacket({cmd: 'pubrec', messageId: messageId, reasonCode: code}, done)
        } else {
          that.incomingStore.put(packet, function () {
            that._sendPacket({cmd: 'pubrec', messageId: messageId}, done)
          })
        }
      })
      break
    }
```
I've already tried to set protocolVersion: 5 and define a new customHandleAcks callback inside connection options but I'm new to asynchronous programming, and I don't know how to do that :(

Please help.
Thanks

**Comment by jdiamond** [comment]
MQTT.js and the MQTT protocol itself don't really care if the application encounters an error while processing a message after it has received it. As long as the message was delivered to the application, the ack is sent.

The `customHandleAcks` option lets you choose what reason code to send, but it's not like sending an error will trigger any sort of retries:

> If PUBACK or PUBREC is received containing a Reason Code of 0x80 or greater the corresponding PUBLISH packet is treated as acknowledged, and MUST NOT be retransmitted [MQTT-4.4.0-2].

But if you want to see an example of using that option, check out this test:

https://github.com/mqttjs/MQTT.js/blob/a4d66266802ff16d03eea057d83c626421e04d94/test/client_mqtt5.js#L318-L324

**Comment by avwarez** [comment]
Hi jdiamond
 thanks for the reply
> MQTT.js and the MQTT protocol itself don't really care if the application encounters an error while processing a message after it has received it. As long as the message was delivered to the application, the ack is sent.
You are right, but I'm not agree. A protocol (MQTT) is a set of rules to define a comunication between systems. It doesn't define what you can do or not with the software (MQTT.js) :) and I think this library can do much more. 
> But if you want to see an example of using that option, check out this test:
> 
> https://github.com/mqttjs/MQTT.js/blob/a4d66266802ff16d03eea057d83c626421e04d94/test/client_mqtt5.js#L318-L324
Thank you, it was useful to understand.

For who is interested I found a workaround, maybe it can be merged inside mqtt.js library.
1. changed method's name MqttClient.prototype._handlePublish to MqttClient.prototype._intHandlePublish
2. defined new method by composition:
```
MqttClient.prototype._handlePublish = function (packet, done) {
   this.intHandlePublish(packet, done)
}
```
3. overridden handlePublish inside my script:
```
client._handlePublish = function (packet, done) {

   if (forced) {
      return client._intHandlePublish(packet, done)
   }

   var data = packet.payload.toString();
   var http_options = {
      hostname: 'nas',
      port: 9000,
      path: '/',
      method: 'POST',
      headers: {
         'Content-Type': 'application/json',
         'Content-Length': data.length
      }
   }

   var req = httpwrapper.request(http_options, (res) => {
      res.setEncoding('utf8')

      res.on('data', (chunk) => {
         if (res.statusCode == 200) {
            client._intHandlePublish(packet, done)
         }
      })
   })
   req.write(data)
   req.end()
}
```
It's close to an experiment, but I hope it's useful for someone to play with this fantastic library.

Thanks!

**Comment by jdiamond** [comment]
You can disagree, but if the protocol doesn't define ways to accommodate your use case, it's not the right protocol for the job. MQTT is a pub/sub protocol--not producer/consumer like you are trying to use it. It has no notion of timeouts or dead letter queues and the only way to force the broker to resend a message is for a client to disconnect without sending an ack and reconnect. You would be better off with a protocol like AMQP or using a service like SQS.
