### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by OmgImAlexis** [mqttjs/MQTT.js#1100]
@mcollina any chance on a new release?

**Comment by YoDaMa** [comment]
There was a release made last week?

**Comment by OmgImAlexis** [comment]
I'm not talking a major just minor bump.

Also quite a bit has changed since including my PR which allows me to use this with webpack again. 

https://github.com/mqttjs/MQTT.js/compare/bd4e24a9ec16c31f966801fc7ccc0953236d7830...master

**Comment by YoDaMa** [comment]
there's been a release so closing this issue.
