### ISSUE TITLE
New messages not being published after store messages are processed - possible solution

### ISSUE THREAD

**Issue by gabrielfnogueira** [mqttjs/MQTT.js#1116]
Hi there!

We have an electron app that only publishes QoS 2 messages and I'm using https://github.com/mcollina/mqtt-level-store as persistent store.
Our users reported that a lot of messages are not being published. The internet connection in the warehouse we run the app is not good, so we lose connection quite often. After some investigation, this is what I've found:

- whenever we lose connection, the messages are stored as expected, so after reconnection they are sent;
- however, after the stored messages are sent, all the newer messages are stored immediately. They are only sent after someone restarts the app;
- and then again, after the previously stored messages are sent, the newer messages are immediately stored again.

I've enabled debugging logs and I noticed the log `_storeProcessing enabled`, so I checked the code and I noticed that the flag `_storeProcessing` is still `true` after the store finished processing in both cases (https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L517-L535).

So I've forked this repo, added more logging messages to understand what's happening and this is what I've come up with:

- `_storeProcessing = true` is set in the beginning of `storeDeliver` (https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L1507-L1514);
- if there’s no packet, a listener is set for when it’s readable again, but `_storeProcessing` is never set to `false` again (https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L1518-L1522);
- then, when a new message is published, there's the aforementioned check and the message is stored immediately.

Now, I'm not sure if this is the expected behavior. As a quickfix to our problem, I've added a call to `clearStoreProcessing()` inside the `!packet` check to reset the value of `_storeProcessing`.

https://github.com/gabrielfnogueira/MQTTjs/blob/reset-store-processing/lib/client.js#L1518-L1523

I've been using my fork in the application and in my tests everything's working as (we) expected.

If this is indeed a bug, I'm more than happy to open a Pull Request with my change. If not, I'd like to hear your feedback on it 😄

**Comment by sgiacosa** [comment]
Hello Gabriel, thanks for your solution, I'm having the same problem. I think this is a bug, please, make a PR to solve it.
