### ISSUE TITLE
The unsubscribe method of MQTT.js is not working properly.

### ISSUE THREAD

**Issue by lucaspedro** [mqttjs/MQTT.js#1117]
During the implementation of a code I realized that my topics registered in mqtt.js were not removed from the registry when calling the unsubscribe function.
Thus, in the case of dynamic components that needed to open and close their topics by demand, the code was lost and did not receive the values in a timely manner (when it did).
I did some research and apparently was making the correct use of the function, but the behavior was not ideal, to correct this problem I had to implement my own unsubscribe, I will share it below:

```
/* Clean a list of topics. */
    destroyTopics(topics) {
      topics.map((topic) => {
        this.destroyTopic(topic)
      })
    },
    /* Clean only one topic. */
    destroyTopic(topic) {
      this.$mqtt2.unsubscribe(topic)
      for (const key in this.$mqtt2.messageIdToTopic) {
        for (let i = 0; i < this.$mqtt2.messageIdToTopic[key].length; i++) {
          let elem = this.$mqtt2.messageIdToTopic[key][i]
          if (elem == topic) {
            this.$mqtt2.messageIdToTopic[key].splice(i, 1);
          }
        }
        if (this.$mqtt2.messageIdToTopic[key].length<=0)
          delete this.$mqtt2.messageIdToTopic[key]
      }
    },
```

But I hope that the lib updates and corrects this problem on its own, since the ideal is that this process is carried out by itself.

**Comment by Mailari** [comment]
Even I am faced the same issue while unsubscribing topics during run time

**Comment by hpo14** [comment]
Had same issue, with mqttjs v4.2.4. the callback arg on unsubscribe doesnt raise any error.
So i delete the key after calling unsubscribe.
```
topics = this.$mqtt.messageIdToTopic
topicExits = Object.keys(topics).find(
  k => String(topics[k]) === targetMqttTopic
)
if (topicExits !== undefined) {
  this.$mqtt.unsubscribe(targetMqttTopic)
  delete this.$mqtt.messageIdToTopic[topicExits]
}
```

**Comment by oneEyedSunday** [comment]
Im running into this in a react app, weird that this isnt handled
