### ISSUE TITLE
[Question] publish while not connected

### ISSUE THREAD

**Issue by Woiife** [mqttjs/MQTT.js#1121]
Hello can please someone answer this question (I know if I search and try long enough I fill find it myself).

What is the behavior, when you publish a message while the connection to the broker is offline? Will it be dropped or does it get stored in some buffer (memory overflow?)

Thank you in advance

**Comment by taraskuzyk** [comment]
From experience, the message gets published even if I call **publish** before **on("connect", ...)** listener gets triggered, so it definitely doesn't get dropped and must be stored in some buffer. (on Node 12)

**Comment by Woiife** [comment]
Yes seems the same for me here. But is it then save to just keep it going? I fear a memory overflow if the client is disconnected for to long.

**Comment by seriousme** [comment]
Well that depends on the store you use:
The default store is a ES6 Map, see [lib/store.js](https://github.com/mqttjs/MQTT.js/blob/963e554d3da2e4149c6f99b4fbe3aad6e620b955/lib/store.js).
But you can provide your own store that persists to disk,e.g. see [mqtt.Client](https://github.com/mqttjs/MQTT.js/tree/963e554d3da2e4149c6f99b4fbe3aad6e620b955#mqttclientstreambuilder-options) and [mqtt.Store]( https://github.com/mqttjs/MQTT.js/tree/963e554d3da2e4149c6f99b4fbe3aad6e620b955#store)

**Comment by Woiife** [comment]
I reviewed the code and saw that the messages are stored by there id. This means also messages to the same topic are stored again and again, since the id always changes.
Therefore it is NOT save to just keept it going because you would risk an increase of memory usage. In my wrapperclient I now have an options which dropts the message, if the client is not connected.
Please correct me if I am wrong

**Comment by Woiife** [comment]
I reviewed the code and saw that the messages are stored by there id. This means also messages to the same topic are stored again and again, since the id always changes.
Therefore it is NOT save to just keept it going because you would risk an increase of memory usage. In my wrapperclient I now have an options which dropts the message, if the client is not connected.
Please correct me if I am wrong

**Comment by Woiife** [comment]
I reviewed the code and saw that the messages are stored by there id. This means also messages to the same topic are stored again and again, since the id always changes.
Therefore it is NOT save to just keept it going because you would risk an increase of memory usage. In my wrapperclient I now have an options which dropts the message, if the client is not connected.
Please correct me if I am wrong

**Comment by Woiife** [comment]
I reviewed the code and saw that the messages are stored by there id. This means also messages to the same topic are stored again and again, since the id always changes.
Therefore it is NOT save to just keept it going because you would risk an increase of memory usage. In my wrapperclient I now have an options which dropts the message, if the client is not connected.
Please correct me if I am wrong

**Comment by seriousme** [comment]
It really depends on what you are trying to achieve, e.g.:
- how big are your messages ? (100 bytes, 10MB etc)
- how often do you send messages ? (once a second, once a day, once a month  etc)
- how long do you think you will be offline as a maximum ? (if your node is down for 20 years, does it still matter etc)
- do you need all data or is it enough to only retain the latest data ?
- how much storage do you have ? (memory, disk)

You could write your own Store that does one or more of the following tricks:
- writes messages to disk and reads them back once you get online.
- drops new messages once the store is full (keeping the oldest messages in store)
- removes old messages once the store is full  (keeping the newest messages in store)

The default store implementation will keep everything in the ES6 Map, this will first fill up memory and eventually your swap disk (if present) . Once that is full your device will crash :-(

Kind regards,
Hans

**Comment by Woiife** [comment]
Thank you for the quick response and the clarification. I am fully aware that the conditions will affect all this (size, frequency, etc). The way it is implemented is fine. I just wanted to know what is the behavior in this case which I now know.

I my situation I would like to have the latest message of a topic to be stored. I might start implementing an own store, but for now I just drop the messages before calling "subrcribe" if I am not connected and a certain flag is not set.

Thank you for your help!
