### ISSUE TITLE
Unable to connect over TLS

### ISSUE THREAD

**Issue by PierreLoupG** [mqttjs/MQTT.js#1128]
Hi,
I'm trying to connect to a broker over TLS in react-native. Based on the doc I tried this code:

```js
const options = {
  port: PORT,
  host: HOST,
  protocol: 'mqtts',
  secureProtocol: 'TLS_method',
  username: USERNAME,
  password: PASSWORD,
  ca: CA_FILE
}

const client = mqtt.connect(options);

client.on('error', (error) => {
  console.log("error", error);
});

client.on('connect', () => {
  console.log("connected");
});
```
The options object will be passed through `tls.connect()`, so I specified the certificate file.

The connection doesn't return an error, but the client is not connected.
What did I do wrong?

Thanks in advance for your help

**Comment by jdiamond** [comment]
What is `CA_FILE`? It can't be a path to file--you need to load it yourself and pass in the file's content as a `Buffer` or string.

Try running with env var `DEBUG=mqttjs,mqttjs:*` to see if there is any useful output.

**Comment by PierreLoupG** [comment]
`CA_FILE` is the file content as a string, not the path.

The broker log show:
```
1595238085: OpenSSL Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
1595238085: Socket error on client <unknown>, disconnecting.
```
I checked, and the cafile in the mosquitto.conf is the same one I use.
What could cause this error ?

**Comment by jdiamond** [comment]
I think the certificate in mosquitto.conf and the CA file you use with MQTT.js would only be the same if the certificate was self-signed.

Your error message makes me think mosquitto is expecting a client certificate. Are you setting the require_certificate and cafile options in mosquitto.conf? If so, remove those. You should probably only be setting certfile and keyfile. But if you are trying to use client certificates, you need to also set the cert and key options with MQTT.js.

**Comment by YassineChe** [comment]
How did you solve it ?
