### ISSUE TITLE
TLS connection with brokers using NodeJS default CA

### ISSUE THREAD

**Issue by chainhead** [mqttjs/MQTT.js#1132]
A number of CA are [burnt into NodeJS source code](https://github.com/nodejs/node/blob/v4.2.0/src/node_root_certs.h). Suppose, I have to make a TLS connection to a broker that used one or more of the default CA in NodeJS source. Then, effectively, I have to mention the protocol as `mqtts` _only_ (letting the cipher options to default) when connecting. Is this correct?

Example:

```js
const options = {
  port: PORT,
  host: HOST,
  protocol: 'mqtts'
}

const client = mqtt.connect(options);
```

**Comment by jdiamond** [comment]
Yes. To use MQTT over TLS, you have to set `protocol` like you did or use a URL that starts with "mqtts:".

MQTT.js eventually just calls `tls.connect`, so I would assume those default CAs should be used if you don't set `ca` in the options. I've always used a custom CA so can't say I've seen it work myself.
