### ISSUE TITLE
Bug: Resubscribe with persistent session only working correctly with protocolVersion 5

### ISSUE THREAD

**Issue by Tharit** [mqttjs/MQTT.js#1157]
There is an issue with the automatic resubscription.

If a persistent session is used (```clean: false```) and the session does not exist after a reconnect (```connack.sessionPresent: false```, e.g. because the broker restarted), then NOTHING is resubscribed. 

I think this line here in the _resubscribe function is the problem:

```(this.options.clean || (this.options.protocolVersion === 5 && !connack.sessionPresent))```

Why is this check for protocolVersion 5 there? If I remove it then everything works.

**Comment by YoDaMa** [comment]
@Tharit or @heunghingwan can you provide a code snippet demonstrating the repro, and also debug logs showing the bug? I want to add a test to #1204, plus it doesn't seem correct.
