### ISSUE TITLE
DISCONNET packet is not send

### ISSUE THREAD

**Issue by ysfscream** [mqttjs/MQTT.js#1159]
Sorry there is a problem here.

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718090

Reference 3.1.4 in this MQTT standard document:

> The DISCONNECT Packet is the final Control Packet sent from the Client to the Server. It indicates that the Client is disconnecting cleanly.

I tested and found that no `DISCONNECT Packet` was sent when calling `client.end()`. What should I do? Thanks for your help.

**Comment by jdiamond** [comment]
Please share your test code. Maybe you are exiting the process right after calling `end()` without passing in a callback?

**Comment by ysfscream** [comment]
Hello, thanks for your answer. Let me show you the code of my production environment directly.

```ts
private disconnect(): boolean | void {
    if (!this.client.connected) {
      return false
    }
    this.client.end!(true)
    this.retryTimes = 0
}
```
Just simply call the end method, so all I need is to pass in a callback? Or should the force parameter be removed?

**Comment by YoDaMa** [comment]
you're using the `Force` flag set to `true`, so what you're seeing is expected behavior. If you want to see the disconnect packet before moving on, you will either have to use `async/await`, or callback.

```
this.client.end(false, () => { /* this code will not be executed until the DISCONNECT packet is received. */})

**Comment by ysfscream** [comment]
OK! @jdiamond @YoDaMa Thanks for your patience. I solved this problem 👍
