### ISSUE TITLE
TypeError: net.createConnection is not a function

### ISSUE THREAD

**Issue by anUniqueBoy** [mqttjs/MQTT.js#1163]
vue.esm.js?efeb:628 [Vue warn]: Error in mounted hook: "TypeError: net.createConnection is not a function"

found in

---> <App> at src/App.vue
       <Root>
vue.esm.js?efeb:1896 TypeError: net.createConnection is not a function
    at Object.streamBuilder (tcp.js?c670:18)
    at MqttClient.wrapper [as streamBuilder] (index.js?0a0f:153)
    at MqttClient._setupStream (client.js?24d8:298)
    at new MqttClient (client.js?24d8:277)
    at Function.connect (index.js?0a0f:155)
    at VueComponent.publishmsg (App.vue?26cd:97)
    at VueComponent.mounted (App.vue?26cd:68)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)
    at callHook (vue.esm.js?efeb:4203)
    at Object.insert (vue.esm.js?efeb:3141)
mqtt version 4.2.1
vue2.0

**Comment by anUniqueBoy** [comment]
hello,The above error when i use mqtt in my  vue project，what is the reason

**Comment by anUniqueBoy** [comment]
This problem will not occur after I downgraded the version of mqtt to 4.0.1

**Comment by moliyu** [comment]
> This problem will not occur after I downgraded the version of mqtt to 4.0.1
I have the same problem with you.however, when i use the version 4.1.0 and it work

**Comment by anUniqueBoy** [comment]
Yes, I used 4.2.1 to report an error, so I dropped it directly to 4.0.1

**Comment by anUniqueBoy** [comment]
> > This problem will not occur after I downgraded the version of mqtt to 4.0.1
> > I have the same problem with you.however, when i use the version 4.1.0 and it work

Yes, I used 4.2.1 to report an error, so I dropped it directly to 4.0.1

**Comment by gbaranski** [comment]
try that
https://github.com/mqttjs/MQTT.js/issue_comments/697243565_

**Comment by gbaranski** [comment]
> > > This problem will not occur after I downgraded the version of mqtt to 4.0.1
> > > I have the same problem with you.however, when i use the version 4.1.0 and it work
> 
> Yes, I used 4.2.1 to report an error, so I dropped it directly to 4.0.1

https://github.com/mqttjs/MQTT.js/issues/1160 try this one

**Comment by ysfscream** [comment]
Maybe you should use webscoket instead of TCP?

**Comment by ollolollollooloo** [comment]
this is also happening to me

**Comment by geri777** [comment]
same with version 4.3.6
mqtt.js is included via script tag in my Vue project.

**Comment by mohammadne** [comment]
same in 4.3.6

I have to use `https://unpkg.com/mqtt@4.0.1/dist/mqtt.js` instead of `https://unpkg.com/mqtt/dist/mqtt.js`

**Comment by turbotimon** [comment]
same problem here... why was this closed without fixing it?

**Comment by robertsLando** [comment]
can someone confirm if this still happens with `mqtt@beta` ?

**Comment by turbotimon** [comment]
@robertsLando i tested with `mqtt@beta` and this particular errors does not happen anymore 👍

In my particular case (and mabye it was the case with others also), the **main problem was that i tried to connect over TCP in a browser, but browser only allow WS**. Anyway, would it be a FR to bring a semantic error message when somebody tries to connect with TCP in a browser, e.g. `const url = 'mqtt://broker.emqx.io:1883'` as in [this](https://www.emqx.com/en/blog/mqtt-js-tutorial) example?

**Comment by robertsLando** [comment]
> Anyway, would it be a FR to bring a semantic error message when somebody tries to connect with TCP in a browser, e.g. const url = 'mqtt://broker.emqx.io:1883' as in [this](https://www.emqx.com/en/blog/mqtt-js-tutorial) example?

Yeah an error message should be shown in that case. Would you like to submit a PR?

**Comment by turbotimon** [comment]
Unfortunately i don't have time at the moment... holidays soon!

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
