### ISSUE TITLE
Cannot find module 'safe-buffer'

### ISSUE THREAD

**Issue by tobdub** [mqttjs/MQTT.js#1168]
```
Error: Cannot find module 'safe-buffer'
Require stack:
- /home/node/node_modules/mqtt/lib/connect/ws.js
- /home/node/node_modules/mqtt/lib/connect/index.js
- /home/node/node_modules/mqtt/mqtt.js
```

_safe-buffer_ is listed as a _devDependency_, but seems to be used by _lib/connect/ws.js_

**Comment by YoDaMa** [comment]
this is a bug. There is a PR though to remove this dependency right now: https://github.com/mqttjs/MQTT.js/pull/1167/files

**Comment by tobdub** [comment]
Fixed
