### ISSUE TITLE
Wrong condition in eventListenerSupport detection

### ISSUE THREAD

**Issue by vetinary** [mqttjs/MQTT.js#1175]
Upgraded to **mqtt@4.2.1** and got error **Uncaught TypeError: socket.addEventListener is not a function** in Firefox

In file **dist/mqtt.js** on line **1930** there is a condition `const eventListenerSupport = (typeof socket.addEventListener === 'undefined')` which sets value of `eventListenerSupport` to `true` in case of method `addEventListener` is undefined. 

Changing the condition to `const eventListenerSupport = (typeof socket.addEventListener !== 'undefined')` solves the problem. 
Hope this helpes someone.

AB#8504348

**Comment by YoDaMa** [comment]
Thanks for pointing this out, we'll get it fixed.

**Comment by nosovk** [comment]
@YoDaMa PR above is a solution?
