### ISSUE TITLE
Browserclient close reason?

### ISSUE THREAD

**Issue by ryandegruyter** [mqttjs/MQTT.js#1178]
What is the best way to find out why a browser client closes the connection?

We are experiencing regular client disconnects, sometimes reconnects are successful, sometimes not.

The period between a successful connect and close event vary also, from a few minutes to a few hours.

I noticed the close and disconnect events don't emit any information. So it's difficult to find out the reason.

I check with our network team and they're quit sure the disconnect is coming from the client side.

Does anyone know any way on finding out the reason why the browser client closes the connection?

AB#8572324

**Comment by YoDaMa** [comment]
Hi @ryandegruyter, if you enable logging using the environment variables, you will better be able to understand what's going on. Right now there's no way for me to help you except to say it sounds like an annoying issue.

**Comment by YoDaMa** [comment]
@ryandegruyter ping

**Comment by ryandegruyter** [comment]
Hi @YoDaMa, you may close this for now, DEBUG did not provide any additional information on why connections got closed. But currently we suspect our specific issue is a fault on the server side. Thanks for your reply.
