### ISSUE TITLE
read ECONNRESET at TCP.onStreamRead

### ISSUE THREAD

**Issue by PanzerWafer** [mqttjs/MQTT.js#1179]
Calling  ```client.end()```  generates this error caught by ```client.on('error'), ... )``` : 

```console
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

I'm using **Node v12.19.0**, with **VerneMQ 1.11.0** as MQTT Broker. 

This is a simple code snippet that reproduces that error (the one from the examples, but with error handling):

```js
var mqtt = require('mqtt')
var client = mqtt.connect('mqtt://VernemqBrokerAddress')

client.on('connect', function ( ) {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})

client.on('message', function (topic, message) {
  console.log(message.toString())
  client.end()
})

client.on('error'), function (...args) {
  console.log(args)
}
```

and this is what debug shows with the code snippet (just the output near the error):

``` console
Hello mqtt
  mqttjs:client end :: (mqttjs_aba2800f) +1ms
  mqttjs:client end :: cb? true +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client end :: (mqttjs_aba2800f) :: immediately calling finish +0ms
  mqttjs:client end :: (mqttjs_aba2800f) :: finish :: calling _cleanUp with force false +0ms
  mqttjs:client _cleanUp :: done callback provided for on stream close +1ms
  mqttjs:client _cleanUp :: forced? false +0ms
  mqttjs:client _cleanUp :: (mqttjs_aba2800f) :: call _sendPacket with disconnect packet +0ms
  mqttjs:client _sendPacket :: (mqttjs_aba2800f) ::  start +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'disconnect' } +0ms
  mqttjs:client sendPacket :: emitting `packetsend` +0ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqtt-packet:writeToStream generate called +8ms
  mqtt-packet:writeToStream generate: packet.cmd: disconnect +1ms
  mqtt-packet:writeToStream writeVarByteInt: writing to stream: <Buffer 00> +0ms
  mqttjs:client sendPacket :: writeToStream result true +1ms
  mqttjs:client sendPacket :: invoking cb +0ms
  mqttjs:client _cleanUp :: clearing pingTimer +0ms
  mqttjs:client streamErrorHandler :: error read ECONNRESET +4ms
  mqttjs:client streamErrorHandler :: emitting error +0ms
[
  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:208:20) {
    errno: 'ECONNRESET',
    code: 'ECONNRESET',
    syscall: 'read'
  }
]
  mqttjs:client (mqttjs_aba2800f)stream :: on close +1ms
  mqttjs:client flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function +0ms
  mqttjs:client stream: emit close to MqttClient +0ms
  mqttjs:client close :: connected set to `false` +0ms
  mqttjs:client close :: clearing connackTimer +1ms
  mqttjs:client close :: clearing ping timer +0ms
  mqttjs:client close :: calling _setupReconnect +0ms
  mqttjs:client _setupReconnect :: doing nothing... +0ms
  mqttjs:client end :: finish :: calling process.nextTick on closeStores +0ms
  mqttjs:client end :: closeStores: closing incoming and outgoing stores +0ms
  mqttjs:client end :: closeStores: emitting end +1ms
  mqttjs:client end :: closeStores: invoking callback with args +0ms
  mqttjs:client nop :: undefined +0ms

```  

I also tried to use the public MQTT broker installed on ```test.mosquitto.org``` and the error doesn't appear. 

I'm not sure whose fault is it, if client or server, but the VerneMQ server doesn't raise any error (I've checked in the logs). Is it the server that performs a wrong disconnection generating an error on the client? If yes, should ```mqtt``` package handle that?

Should I do anything about the error on the application level? Like managing it?

AB#8574516

**Comment by YoDaMa** [comment]
this is an interesting error... We added more clarity on the errors popping up in MQTT.js to users so they could deal with for instance connection errors, but this is a side effect. It's not clear if by sending disconnect that is propagated to the broker and so the broker rips out the connection causing the ECONNRESET error to occur. 

A solution might be to ignore errors on disconnect... it would be a tricky solution though. PRs welcome.

**Comment by fpagliughi** [comment]
I hit this issue as well with Node 16 and VerneMQTT 1.12.6.2.  I confirmed that it only happens with a VerneMQ broker - not with Mosquitto or RabbitMQ. I hit up the VerneMQ folks, and they came back with a solution in a few minutes: 
https://github.com/vernemq/vernemq/issues/2092

The TCP linger option for the server needs to be set to a non-zero value. Add this to the server's configuration file, `vernemq.conf`:
```
tcp_listen_options = [{nodelay, true}, {linger, {true, 6}}, {send_timeout, 30000}, {send_timeout_close, true}]
```

That fixed it for me.
