### ISSUE TITLE
server's topicAliasMaximum is not relevant to client's topicAliasMaximum

### ISSUE THREAD

**Issue by heunghingwan** [mqttjs/MQTT.js#1183]
hi,
I think this is a bug, topicAliasMaximum in CONNACK is for client to send to server, it should not overwrite CONNECT options, this will be a problem when reconnect.
https://github.com/mqttjs/MQTT.js/blob/70a247c29e0b05ddd8755e7b9c8c41a4c25b431b/lib/client.js#L1174

AB#8607503

**Comment by YoDaMa** [comment]
please create a PR addressing it if it is a bug.

**Comment by heunghingwan** [comment]
fix by #1301 (#1300 for detail)
