### ISSUE TITLE
TypeError: socketTask.onOpen is not a function

### ISSUE THREAD

**Issue by asagcs** [mqttjs/MQTT.js#1184]
i found it in uniapp with .nvue, can anyone tell me what socketTask.onOpen  does；

version： mqtt 4.1.0

Here is my code:
```
connect: function() {
				var self = this
				self.logs.push('connect')
				var mqtt = require('mqtt/dist/mqtt.js')
				
				var hosts = '',
				
				
					hosts = 'wx://' + this.serve.host + ':' + this.serve.port + this.serve.path

				
				this.client = mqtt.connect(hosts)
				
				
			},
```

AB#8632728

**Comment by YoDaMa** [comment]
it looks like it is in the Alibaba websockets code. I'm not sure the purpose of it.

https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/wx.js#L61
