### ISSUE TITLE
Mosquitto broker connection fails

### ISSUE THREAD

**Issue by kyjak** [mqttjs/MQTT.js#1192]
I have a mosquitto broker running both mqtt and ws protocols.
I can connect successfully from MQTT Explorer and a custom C# client using username and password, so the server side (passwd file, etc.) work.
However, when connecting using this library, i get a connection error of "Error: Connection refused: Not authorized".
When I switch on allow_anonymous and remove the username/pwd, the client connects.

code follows
`const client = mqtt.connect(`ws://hostname.com:8082`, {
  clientId: `server`,
  clean: false,
  username: "xxx",
  password: "xxx"
});
`

AB#8676209

**Comment by YoDaMa** [comment]
make sure you are using the latest, there was a bug in 4.2.2 that was patched this morning with the 4.2.3 release

**Comment by bashman** [comment]
> make sure you are using the latest, there was a bug in 4.2.2 that was patched this morning with the 4.2.3 release


Hi. CDN version is updated?... 

I using: https://unpkg.com/mqtt@4.2.3/dist/mqtt.min.js

I am testin in MQTTX and wss works fine!. 

Here my log:
mqtt.min.js:1 WebSocket connection to 'wss://message.xxx.com:8084/' failed: Error during WebSocket handshake: Unexpected response code: 404
(anonymous) @ mqtt.min.js:1
t.exports @ mqtt.min.js:1
(anonymous) @ mqtt.min.js:1
v._setupStream @ mqtt.min.js:1
v @ mqtt.min.js:1
a @ mqtt.min.js:1
(anonymous) @ 1.html:42
32mqtt.min.js:1 WebSocket connection to 'wss://message.xxx.com:8084/' failed: Error during WebSocket handshake: Unexpected response code: 404
(anonymous) @ mqtt.min.js:1
t.exports @ mqtt.min.js:1
(anonymous) @ mqtt.min.js:1
v._setupStream @ mqtt.min.js:1
v._reconnect @ mqtt.min.js:1
(anonymous) @ mqtt.min.js:1

**Comment by kyjak** [comment]
upgraded to 4.2.3 and the connection works, thank you for the hint, closing item
