### ISSUE TITLE
TypeError [ERR_INVALID_URL] after updating to 4.2.3

### ISSUE THREAD

**Issue by youngcholo** [mqttjs/MQTT.js#1193]
I'm getting this error after updating to 4.2.3

```
TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: [object Object]
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at Object.connect (C:\Program Files (x86)\NLT\bin\node_modules\mqtt\lib\connect\index.js:64:18)
    at Object.connect (C:\Program Files (x86)\NLT\bin\node_modules\async-mqtt\index.js:139:25)
```
```
mqtt: {
    connection: {
      host: {
        doc: "The URL of the mqtt server.",
        format: "mqtt-url",
        default: "tcp://localhost",
        env: "MQTT",
        arg: "mqtt"
      },
      port: {
        doc: "The port to connect to for the mqtt server.",
        format: "port",
        default: 1883,
        env: "MQTT_PORT"
      }
    }
  }
```
const connectionString = url.parse(conf.get("mqtt").connection.host);
connectionString.port = conf.get("mqtt").connection.port;
mqtt.connect(connectionString, { clientId: this._clientId, clean:false })

this was working yesterday with 4.2.1

AB#8679346

**Comment by YoDaMa** [comment]
@youngcholo thanks for filing the issue. What is the connection string you are providing?

**Comment by YoDaMa** [comment]
is there a minimal repro you can provide?

**Comment by yurievangelista** [comment]
Same is happening here with a pre-signed URL string. 
What I've managed to observe is that the opts parameter in the **streamBuilder** function seems to lose the `href` property somewhere along the way, and I'm left with an empty ("/") path.
I'm using the library in a browser, if that's any help.

**Comment by youngcholo** [comment]
Before 4.2.3 and as specified in the docs,  " The URL can also be an object as returned by URL.parse()"
https://repl.it/join/yhjykmju-youngcholo

**Comment by YoDaMa** [comment]
@youngcholo yeah looks like a bug again with the url parsing. Can you incorporate the changes from the PR linked manually and see if they fix things?

**Comment by youngcholo** [comment]
Apologies for the late response. The issue still persists in 4.2.4.
https://repl.it/@youngcholo/mqtttest424

**Comment by YoDaMa** [comment]
I see now. Thanks for the repl. This is an issue with the legacy support of url.parse. Will have to see if the changes should be reversed because I did not anticipate them affecting the API in this way. I do not believe though there is explicit support for url.parse() in the documentation, but since that does provide a change of support unsure if that means it should be a major version bump...

**Comment by youngcholo** [comment]
Thanks for the information @YoDaMa. If we want to connect via tcp instead of passing the urlObj, we can just pass the host and port in the options, right? 

mqtt.connect({ host: urlObj.host, port: urlObj.port, clientId: this._clientId, clean:false })

**Comment by YoDaMa** [comment]
usually when I'm working with a URL for TCP, I will pass the port in during the connection string: 

```js
mqtt.connect('mqtt://test.mosquitto.org:1883')
```
