### ISSUE TITLE
Error on close and error event

### ISSUE THREAD

**Issue by AndreaBaroni92** [mqttjs/MQTT.js#1196]
When i try to connect to an mqtt server that doesn't exist , for example: 
```javascript
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://not.existing.server')

client.on('connect', function () {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})
client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})

client.on('close', function ( ){
    console.log("Error")
})

client.on('error', function (error ){
    console.log("error also there")
})
```
the code above goes into a loop that will emit a close event ( even if the connection hasn’t been successfully established )  and an error event.

AB#8704082

**Comment by YoDaMa** [comment]
So the bug is that you think it should only emit an error event and not a close event?

**Comment by AndreaBaroni92** [comment]
Hi, 
yes, i suppose it should only emit an error event because i'm not able to detect if the connection goes down due to an error ( like ENOTFOUND) or because it has been closed. Also when in the code above i replace 
``
var client  = mqtt.connect('mqtt://not.existing.server')
``
with
``
var client  = mqtt.connect({host:'147.217.75.186',port:1883})  
``
(where the host it's a random ip) only a close event is emitted.
