### ISSUE TITLE
Uncaught TypeError: net.createConnection is not a function

### ISSUE THREAD

**Issue by NicklasPetersen** [mqttjs/MQTT.js#1202]
Hello,

I am trying to use this API, because I have a webpage that I want to continuously subscribe to certain topics. 

I am trying your example from README, however I get the following error:

> Uncaught TypeError: net.createConnection is not a function
    streamBuilder http://127.0.1.1/tpr/bundle.js:11342
    wrapper http://127.0.1.1/tpr/bundle.js:11311
    _setupStream http://127.0.1.1/tpr/bundle.js:9725
    MqttClient http://127.0.1.1/tpr/bundle.js:9704
    connect http://127.0.1.1/tpr/bundle.js:11313
    subscribe http://127.0.1.1/tpr/bundle.js:15321
    onload http://127.0.1.1/tpr/bundle.js:15312
    EventHandlerNonNull*[89]< http://127.0.1.1/tpr/bundle.js:15294
    o http://127.0.1.1/tpr/bundle.js:1
    r http://127.0.1.1/tpr/bundle.js:1
    <anonymous> http://127.0.1.1/tpr/bundle.js:1

My package.json file looks like this:

`{
  "name": "tpr",
  "version": "1.0.0",
  "main": "/public/script.js",
  "scripts": {
    "build": "browserify public/script.js -o bundle.js",
    "watch": "watchify public/script.js -o bundle.js"
  },
  "author": "nip@mail.dk",
  "license": "ISC",
  "devDependencies": {
    "browserify": "^17.0.0",
    "watchify": "^3.11.1"
  },
  "dependencies": {
    "jquery": "^3.5.1",
    "mqtt": "^4.2.4"
  },
  "description": ""
}
`
Why do I get this error message, and how do I fix it?

Have a nice day. 

AB#8738610

**Comment by cameronelliott** [comment]
I think you might be trying non 'ws' 'wss' urls for the broker, just a suspicion.
This got me too.
