### ISSUE TITLE
light version of mqtt.js

### ISSUE THREAD

**Issue by nosovk** [mqttjs/MQTT.js#1208]
currently mqtt.js supports all MQTT protocol versions.
Probably supporting only v5 could improve project maintainability, avoid some hard to debug errors (I never saw protocol version in open issues, most users don't see the difference, also most of all brokers support mqttv5 now), reduce size of bundle?

AB#8781743

**Comment by YoDaMa** [comment]
That’s a good thought but industry wide adoption of MQTTv5 is not there yet. At least for Microsoft many of the Brokers are still v3.1.1... and with no backwards compatibility between the two it’s not smart right now. I would love an industry-wide path to adoption on MQTTv5.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nosovk** [comment]
Understand. Then it could be done, but bit later.
