### ISSUE TITLE
mqtt protocol cannot connect

### ISSUE THREAD

**Issue by ysfscream** [mqttjs/MQTT.js#1210]
The URL of the mqtt protocol cannot be resolved to the host, so it cannot connect to the custom host, only the local.

![image](https://user-images.githubusercontent.com/21299158/98896240-7ab83200-24e3-11eb-8f47-55445df1af0e.png)

Source code is here:

![image](https://user-images.githubusercontent.com/21299158/98897040-6bd27f00-24e5-11eb-9c3b-2e6c43161e9e.png)

**Comment by django-wong** [comment]
Have you noticed this?

> v4.0.0 (Released 04/2020) removes support for all end of life node versions and now supports node v12 and v14. It also adds improvements to debug logging, along with some feature additions.

**Comment by brookswood** [comment]
I am experiencing the same issue, downgrading did the trick as well.  Should we assume this reference error is a result of node v12 support and above?
