### ISSUE TITLE
MQTTjs Socket issues on Firefox.

### ISSUE THREAD

**Issue by HiveTechDev** [mqttjs/MQTT.js#1225]
I've looked, and can't find a duplicate issue. Trying to get a very very basic websocket connection setup for web to connect to test.mosquitto.org.

Code works perfectly fine in chrome. In firefox you get one of two errors, sometimes both:

1) The connection to wss://test.mosquitto.org:8081/ was interrupted while the page was loading.
2) Firefox can’t establish a connection to the server at wss://test.mosquitto.org:8081/.

This was tested on Firefox on Ubuntu 20, Mac and Windows 10. All with the same issue. Full code is attached to try and reproduce:

<html>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>

    <script>

    var clientId = 'mqttjs_' + Math.random().toString(16).substr(2, 8)

    // This sample should be run in tandem with the aedes_server.js file.
    // Simply run it:
    // $ node aedes_server.js
    //
    // Then run this file in a separate console:
    // $ node websocket_sample.js
    //
    var host = 'wss://test.mosquitto.org:8081'

    var options = {
        keepalive: 30,
        clientId: clientId,
        clean: false,
        reconnectPeriod: 1000,
        connectTimeout: 30 * 1000,
        protocol: "wss",
        will: {
            topic: 'WillMsg',
            payload: 'Connection Closed abnormally..!',
            qos: 0,
            retain: false
        },
    }

    console.log('connecting mqtt client : host: ', host, "  :: Options : ", options)
    var client = mqtt.connect(host, options)

    client.on('error', function (err) {
        console.log(err)
        client.end()
    })

    client.on('connect', function () {
        console.log('client connected:' + clientId)
        client.subscribe('topic', { qos: 0 })
        var t=setInterval(() => {
            client.publish('topic', 'TYLER IS ::: wss secure connection demo...! -> ' + Date.now(), { qos: 0, retain: false })
        },1000);
    })

    client.on('message', function (topic, message, packet) {
        console.log('Received Message:= ' + message.toString() + '\nOn topic:= ' + topic)
    })

    client.on('close', function () {
        console.log(clientId + ' disconnected')
    })
    </script>
    <body>

    </body>
</html>

[firefoxMQTT.html.zip](https://github.com/mqttjs/MQTT.js/files/5661537/firefoxMQTT.html.zip)

**Comment by paulober** [comment]
Have the same error. Any solution to this?

**Comment by Gaffen** [comment]
I'm also seeing this

**Comment by jonasgeiler** [comment]
bump
