### ISSUE TITLE
Cannot connect from browser to native MQTT

### ISSUE THREAD

**Issue by PaulCorbeau** [mqttjs/MQTT.js#1229]
Hello, 

I try to access directly a MQTT broker on port 1883, without websocket from a browser.

![image](https://user-images.githubusercontent.com/8874816/102200774-8ec9c780-3ec5-11eb-8370-1e60f76800c1.png)

When I check the object result I can see that the protocol is not changed to mqtt nor tcp : 

![image](https://user-images.githubusercontent.com/8874816/102201339-3e9f3500-3ec6-11eb-90f9-6e1627e48eef.png)

I found that some settings can be change with the option : wsOptions. I tried to create manually the Websocket but it indicates that it accepts only ws or wss.

Am I missing something ? 

thanks

AB#8978851

**Comment by sectokia** [comment]
1883 is for MQTT protocol, which is different to MQTT over Websockets.
Your broken needs to support MQTT over websockets, and this will usually be running on a different port, maybe 80, 8080, 8883 (I don't believe there is a 'default' universally used like 1883 is for MQTT).
