### ISSUE TITLE
Get bytes sent over MQTT socket.

### ISSUE THREAD

**Issue by MiguelTing** [mqttjs/MQTT.js#1230]
Hi,

Is there a way to get the number of bytes sent via the MQTT client including all the encryption overhead of using SSL?
I tried using 

```
client = mqtt.connect(connectionArgs);
console.log(client.stream.bytesRead, client.stream.bytesWritten)
```

But it only gave me 45 and 60 bytes respectively. The data I got from wireshark and enabling  client.stream.enableTrace() is around 9kb which far from 60+45 bytes.

AB#9000267

**Comment by YoDaMa** [comment]
This is a good feature request but it is not technically available now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
