### ISSUE TITLE
Unknown command 'mqtt.js'

### ISSUE THREAD

**Issue by erickcrus** [mqttjs/MQTT.js#1234]
Hello guys, sorry for my poor english, but i'm having a big problem to run the client in my ReactJS application.
With my application running, I installed the mqtt package using: `npm install mqtt --save`.

then I ran the commands: 
`npm install -g webpack`
`cd node_modules/mqtt`
`npm install .`

When I ran the command `webpack mqtt.js --output-library mqtt` , I received a response that said I should install webpack-cli, which I installed using the command `npm install webpack-cli -g`.

When I tried to run `webpack mqtt.js --output-library mqtt` in node_modules/mqtt folder again, I received the following response:
`[webpack-cli] Unknown command 'mqtt.js'`
`[webpack-cli] Run 'webpack --help' to see available commands and options`

my package.json dependencies:
```javascript
...,
"dependencies": {
    ...,
    "jsonschema": "^1.2.6",
    "mosca": "^2.8.3",
    "mqtt": "^4.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "react-websocket": "^2.1.0",
    "save": "^2.4.0",
    "web-vitals": "^0.2.4",
    "websocket": "^1.0.33"
},
...
```

my client App.js code:
```javascript
...
import mqtt from 'mqtt';
var MQTT_TOPIC = "IDNodeMCU";
var MQTT_ADDR = "my_server_ip:port";
var  client  = mqtt.connect(MQTT_ADDR);
client.on('connect', function () {
    console.log('client connected');
    client.subscribe(MQTT_TOPIC);
    client.publish(MQTT_TOPIC, 'Website here!');
});
...
```

I don't get error messages on the console, but the 'connect' event is not triggered, because on the console I don't get `client connected` response.

I know the server is working, as my client at NodeMCU is behaving normally.

AB#9145998

**Comment by bardakcioglu** [comment]
SAME İSSUE

**Comment by erickcrus** [comment]
I found a solution to the problem:
I reconfigured the server, using the mosca package, attaching an node http server:
```javascript
const mosca = require('mosca');
const express = require('express');
const server = require('http').createServer();

// initializes mosca server
const mqttServ = new mosca.Server({});

// attach http to mosca server
mqttServ.attachHttpServer(server);

// debug mosca server
mqttServ.on('ready', () => {
    console.log(mqttServ);
});

const port = 2469;
server.listen(port, (err) => {
    if(err) console.log(err);
    console.log('Server running on  ', port);
});
```

on ReactJS client:
```javascript
import mqtt from 'mqtt';
const client = mqtt.connect('ws://server_ip:port');

export default class App extends React.Component {
    componentDidMount(){
        client.on('connect', function () {
            client.subscribe("test");
            client.publish("test", 'React here!');
        });
    }
    ...
}
```
