### ISSUE TITLE
Format of publishing retained message

### ISSUE THREAD

**Issue by Zeni241** [mqttjs/MQTT.js#1240]
What is the right format for publishing retained message? I tried following formats without success.

```
1.   client.publish('mytopic', 'message', {qos:1, retain:'true'});
2.  client.publish('mytopic', 'message', [qos:1, retain:'true']);

3.  const opt = {
    qos:1,
    retain:'true',
  };
 client.publish('mytopic', 'message', opt);
```

AB#9225606

**Comment by jdiamond** [comment]
options should be an object so kind of like your first and third examples, but retain should be a boolean so you wouldn't use quotes around true.

**Comment by Zeni241** [comment]
I think that first one is working. I had to reload mqtt client (mqtt spy) to see the updated status and it is now showing retained. For Qos its an other story. The client subscription Qos also counts.
