### ISSUE TITLE
MQTT after version 4.2 does not work in react-native

### ISSUE THREAD

**Issue by julianwong94** [mqttjs/MQTT.js#1242]
Mqtt doesn't work in react-native packages after the migration from websocket-stream to ws. The ws import tries to find 'http' which is only available in node and throws an error that the http module is not found. 

I saw that there was a fix for the browser here: https://github.com/mqttjs/MQTT.js/issues/1145. I've tried this library in both a browser app and a react-native app, and I believe the difference is that webpack doesn't throw an error if the unresolved import is not used, while the metro-bundler will throw an error if the dependency is anywhere in the dependency tree.

I looked at the [websocket-stream](https://github.com/maxogden/websocket-stream) package and found that they were able to circumvent ever importing from the 'ws' package by adding this to the package json:

```
"browser": {
    "ws": "./ws-fallback.js",
   // ...rest
  },
```

and this to ws-fallback.js:

```var ws = null

if (typeof WebSocket !== 'undefined') {
  ws = WebSocket
} else if (typeof MozWebSocket !== 'undefined') {
  ws = MozWebSocket
} else if (typeof window !== 'undefined') {
  ws = window.WebSocket || window.MozWebSocket
}

module.exports = ws
```

I can submit a pull request for adding this, but I'm wondering if we can revert the changes from https://github.com/mqttjs/MQTT.js/issues/1145 after adding it.

AB#9242797

**Comment by conkyliu** [comment]
Use the last version, ios and android work normally in RN. https://github.com/conkyliu/MQTT.js
