### ISSUE TITLE
is there an example to connect to AWS IoT?

### ISSUE THREAD

**Issue by ollolollollooloo** [mqttjs/MQTT.js#1245]
AB#9289712

**Comment by ollolollollooloo** [comment]
I have this code in react-native but it doesn't connect

const mqtt = require('mqtt')
// const fs = require('fs')
const path = require('path');
// var RNFS = require('react-native-fs');

// const KEY = fs.readFileSync('%USERPROFILE%\certs\private.pem.key');
// const CERT = fs.readFileSync('%USERPROFILE%\certs\certificate.pem.crt');
// const CAfile = [fs.readFileSync('%USERPROFILE%\certs\root-ca.pem')];
// const KEY = './aws/private.pem.key';
// const CERT = './aws/certificate.pem.crt';
// const CAfile = ['./aws/root-ca.pem'];
// const KEY = RNFS.readFileSync('%USERPROFILE%\certs\private.pem.key');
// const CERT = RNFS.readFileSync('%USERPROFILE%\certs\certificate.pem.crt');
// const CAfile = [RNFS.readFileSync('%USERPROFILE%\certs\root-ca.pem')];
const KEY = path.resolve(__dirname, './certs/private.pem.key');
const CERT = path.resolve(__dirname, './certs/certificate.pem.crt');
const CAfile = path.resolve(__dirname, './certs/root-ca.pem');

const options = {
  host: "xxxx-ats.iot.us-east-2.amazonaws.com",
  port: 8883,
  protocolId: 'MQIsdp',
  ca: CAfile,
  keyPath: KEY,
  certPath: CERT,
  secureProtocol: 'TLSv1_method',
  protocolVersion: 3
};
const client  = mqtt.connect(options)

client.on('connect', function () {
  console.log("publish!!!!")
  client.publish('test', 'Hello mqtt')
  client.subscribe('test', function (err) {
    if (!err) {
      client.publish('test', 'Hello mqtt')
    }
  })
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})

**Comment by julianwong94** [comment]
You should look at this library (which uses mqtt under the hood) https://github.com/aws/aws-iot-device-sdk-js-v2
