### ISSUE TITLE
Receive hex data

### ISSUE THREAD

**Issue by PeHo89** [mqttjs/MQTT.js#1250]
Is there a way to receive hex data with MQTT.js? Ideally as Buffer, etc.? When I publish hex data to a topic where I am subscribing to with MQTT.js, I always receive hex data encoded as text. And I am not able to figure out the used encoding to reverse it manually and use the hex data. I tried 315 different encodings, but none of them resulted in the sent hex data. Is there a way to deal with this?

AB#9332534

**Comment by PeHo89** [comment]
I

**Comment by SirPhemmiey** [comment]
Hi @PeHo89 were you able to solve this?

**Comment by PeHo89** [comment]
Hi @SirPhemmiey yes, I was able to solve it. Not directly with MQTT.js but with NestJS (which uses MQTT.js under the hood). Here I receive a buffer that I can convert to literally anything.
