### ISSUE TITLE
Is there support for client certificates over WSS?

### ISSUE THREAD

**Issue by SystemDisc** [mqttjs/MQTT.js#1260]
Is there support for client certificates over WSS? If not, what would it take to get this feature added? I can try to help

AB#9531294

**Comment by zielu** [comment]
I was struggling with this too, but if you dig into code you will find this bit: https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/ws.js#L8

I managed to get it to work by constructing options like this:
```
