### ISSUE TITLE
React Native Support - How to configure?

### ISSUE THREAD

**Issue by larry-cherry** [mqttjs/MQTT.js#1264]
I have been reading over some of the past issues about getting this library to work with React Native. I would like to use this library because it looks like it is the most supported one out there for javascript. I have not found a guide that can be followed to get this project working on React Native. I have read several posts from this repo linked below that talk about some of the difficulties getting it to work. It does appear that people have gotten this project to work with React Native but I am not sure what their project setup looks like. What I am asking is if it is possible to get this repo working with React Native can there be a README file created that walks through the setup process and possibly common issues that arise? I have listed a few of the issues that mention the setup process below but do not know if any of these are relevant. 

- [React-Native support #573](https://github.com/mqttjs/MQTT.js/issues/573)
- [MQTT after version 4.2 does not work in react-native #1242](https://github.com/mqttjs/MQTT.js/issues/1242)
- [Cannot import in React Native #979](https://github.com/mqttjs/MQTT.js/issues/979)

**Comment by larry-cherry** [comment]
I figured I would post some of my findings on getting this library to work with react native. I found you have to set up the buffer globally in your react native app. I did this in my index.js file. The following comments helped me with that configuration [573#issuecomment-428583410](https://github.com/mqttjs/MQTT.js/issues/573#issuecomment-428583410) and [573#issuecomment-467283871](https://github.com/mqttjs/MQTT.js/issues/573#issuecomment-467283871). You also need a way of passing the appropriate net client to the tcp.js file. The require for net is a little quirky so I modified the streambuilder function in the file MQTT.js/lib/connect/tcp.js to accept an optional argument of the net client. That appeared to fix all the issues that I had. I will post a copy of the updated tcp.js file below. If there is a better way to pass the net client please let me know. 

`
'use strict'
var net = require('net');
var debug = require('debug')('mqttjs:tcp')

function streamBuilder (client, opts, netClient) {
  var port, host
  opts.port = opts.port || 1883
  opts.hostname = opts.hostname || opts.host || 'localhost'

  port = opts.port
  host = opts.hostname

  debug('port %d and host %s', port, host)
  if(!netClient){
    netClient = net;
  }
  return netClient.createConnection(port, host);
}

module.exports = streamBuilder
`

**Comment by inkCrazy** [comment]
+1

**Comment by DannieL8** [comment]
+1

**Comment by inkCrazy** [comment]
我最后使用了paho-mqtt.js，地址：https://www.eclipse.org/paho/files/jsdoc/paho-mqtt.js.html，使用websocket协议，运行完好。

**Comment by conkyliu** [comment]
Use the last version, ios and android work normally in RN. https://github.com/conkyliu/MQTT.js

**Comment by andrewleong** [comment]
+1

**Comment by swkang0513** [comment]
+1
