### ISSUE TITLE
Problem Not Working Connection with Nodejs or Browser

### ISSUE THREAD

**Issue by sergioxdev** [mqttjs/MQTT.js#1265]
I post the code that I am creating,
starting it from the shell with the command: node script.js

result:
lost connection! undefined
connection closed! undefined

```js
'use strict'
var mqtt = require('mqtt')
var url = require('url')
var path = require('path')
var fs = require('fs')
var TRUSTED_CA_LIST = fs.readFileSync(path.join(__dirname, '/ca.cer'))
var endpoint = 'wss://server:port/mqtt'
var parsed = url.parse(endpoint)
var mqttOptions = {
	keepalive: 60,
	reschedulePings: true,
	protocolId: 'MQTT',
	protocolVersion: 5,
	reconnectPeriod: 1000,
	connectTimeout: 10 * 1000,
	clean: true,
	protocol: 'wss',
	clientId: 'example',
	username: 'example',
	password: 'example',
  	ca: TRUSTED_CA_LIST,
  	rejectUnauthorized: true,
	will: {
		topic: 'WillMsg',
		payload: 'Connection Closed abnormally..!',
		qos: 0,
		retain: false
	},
	debug: true,
}
var client = mqtt.connect(parsed, mqttOptions)
client.subscribe('example')

client.on('connect', function () {
  console.log('connected')
})
client.on('error', function (a) {
  console.log('error! ' + a)
})
client.on('offline', function (a) {
  console.log('lost connection! ' + a)
})
client.on('close', function (a) {
  console.log('connection closed! ' + a)
})
client.on('message', function (topic, message) {
  console.log(message.toString())
})
```

-----------------------
same code, starting it from firefox: inserted in a web page

result: it works 

```js
html
head
<script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script> 

script
var TRUSTED_CA_LIST = 'example'

var endpoint = 'wss://server:port/mqtt'

var mqttOptions = {
	keepalive: 60,
	reschedulePings: true,
	protocolId: 'MQTT',
	protocolVersion: 5,
	reconnectPeriod: 1000,
	connectTimeout: 10 * 1000,
	clean: true,
	protocol: 'wss',
	clientId: 'example',
	username: 'example',
	password: 'example',
  	ca: TRUSTED_CA_LIST,
  	rejectUnauthorized: true,
	will: {
		topic: 'WillMsg',
		payload: 'Connection Closed abnormally..!',
		qos: 0,
		retain: false
	},
	debug: true,
}

var client = mqtt.connect(endpoint, mqttOptions)
client.subscribe('example')

client.on('connect', function () {
  console.log('connected')
})

client.on('error', function (a) {
  console.log('error! ' + a)
})

client.on('offline', function (a) {
  console.log('lost connection! ' + a)
})

client.on('close', function (a) {
  console.log('connection closed! ' + a)
})

client.on('message', function (topic, message) {
  console.log(message.toString())
})

/script
/head
body
/body
/html
```

something wrong, suggestions are welcome

**Comment by sergioxdev** [comment]
updates I kept testing:
premise:
- certicates signed by CA authority are used
- I have tested the services on the different ports with other clients and the brocker works fine 

nodejs:
- mqtt > OK
- mqtts > OK
- ws > OK
- WSS > NO - (lost connection! undefined - connection closed! undefined)

firefox:
- mqtt > NO - (error Javascript on -> createConnection(r))
- mqtts > NO - (error Javascript on -> createConnection(r))
- ws > NO - (lost connection! undefined - connection closed! undefined)
- WSS >  OK

**Comment by YoDaMa** [comment]
@sergioxdev so I understand correctly, you are saying that with your snippet of code using WSS, it does not work in NodeJS but it does work when running the code in a Browser environment?

**Comment by sergioxdev** [comment]
> @sergioxdev so I understand correctly, you are saying that with your snippet of code using WSS, it does not work in NodeJS but it does work when running the code in a Browser environment?

@YoDaMa  Yes, right

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

**Comment by robertsLando** [comment]
Feel free to reopen this issue if it happens also with v5
