### ISSUE TITLE
Is it possible to use with Deno?

### ISSUE THREAD

**Issue by al6x** [mqttjs/MQTT.js#1267]

**Comment by josephrocca** [comment]
Relevant: https://github.com/denoland/deno/discussions/10105

**Comment by YoDaMa** [comment]
quoting from the deno discussion: 

> I'm guessing this is because MQTT.js contains a browserified version of Node.js's Buffer, and that package tries to change prototypes using __proto__. This doesn't work because, unlike browsers, Deno doesn't allow __proto__ to be overwritten (relevant issue). One way to fix this (as mentioned here) is to replace all instances of obj.__proto__ = newPrototype with Object.setPrototypeOf(obj, newPrototype).
> 
> But actually, it looks like the latest version of browserify's Buffer uses setPrototypeOf instead of __proto__, so you may just be able to ask the maintainer of https://github.com/mqttjs/MQTT.js to re-browserify the package and publish a new version.

So essentially we should work on re-releasing the browserified package. This should be easy enough. @al6x or @vishnureddy17 do you want to take a stab at it? Just send a PR with the update browserify package.

**Comment by vishnureddy17** [comment]
I should be able to take a stab at it some time mid-week, I'll assign the issue to myself once I get started on it. @al6x , feel free to pick this one up if I haven't started.

**Comment by vishnureddy17** [comment]
Hmm, it actually looks like the most recent version of `browserify` still hasn't updated the dependency on `buffer`. So it wouldn't be a matter of simply re-browserifying.

**Comment by vishnureddy17** [comment]
Gonna close this, as we won't be able to get to Deno support right now given the current situation with Browserify.
