### ISSUE TITLE
[vite] Dep optimization failed with error: Could not load url (imported by node_modules\mqtt\lib\connect\index.js): ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by yaolunmao** [mqttjs/MQTT.js#1270]
`import mqtt from 'mqtt';`

Error report occurred：[vite] Dep optimization failed with error: Could not load url (imported by node_modules\mqtt\lib\connect\index.js): ENOENT: no such file or directory,

I'm the vue3.0 project，How to solve it? Thank you

**Comment by m01i0ng** [comment]
https://github.com/mqttjs/MQTT.js/issues/1269#issuecomment-868932161

**Comment by YoDaMa** [comment]
looks like https://github.com/mqttjs/MQTT.js/issues/1269 answers this, so closing.
