### ISSUE TITLE
how to mock mqtt ?

### ISSUE THREAD

**Issue by sapanavyavahare** [mqttjs/MQTT.js#1277]
Hi team I want to do unit testing on mqtt so I want to mock but how to mock it don't know.

**Comment by dgg** [comment]
Use a mock library to substitute the instance that connect returns and then one can fake the events and their arguments.
Having said so, you are probably better off running an in-memory instance of a broker to run your test (more like integration testing). We use aedes for such purpose

**Comment by YoDaMa** [comment]
closing as this seems to be resolved.
