### ISSUE TITLE
`client.reconnect()` will not proper set `client.disconnecting` to `false`

### ISSUE THREAD

**Issue by yyjdelete** [mqttjs/MQTT.js#1284]
reconnect will set `disconnecting` and `disconnected` to `false`, but it will call end later and reset them to true, even  event `connect` is already fired. And this make later `_checkDisconnecting()` always failed.
https://github.com/mqttjs/MQTT.js/blob/37b12cb94737acddfe0fa016e013516ba3b9a031/lib/client.js#L912-L915
https://github.com/mqttjs/MQTT.js/blob/37b12cb94737acddfe0fa016e013516ba3b9a031/lib/client.js#L855
```js
var client  = mqtt.connect('ws://xxxx/mqtt', {'username':'test'});

    var i = 0;
client.on('connect', function() {
    console.log(client.disconnecting)
    console.log(client.disconnected)
    console.log(client.connected)
    setTimeout(() => client.reconnect(), 1000);
});
```
```
times 0
disconnecting:  false
disconnected:  undefined
connected:  true
---
times 1
disconnecting:  true
disconnected:  true
connected:  false
---
times 2
disconnecting:  false
disconnected:  false
connected:  false
```

2. Another question, `_setupPingTimer()` is skipped when `disconnected` is true, so maybe I can get connection without ping for the second try? I didn't found any other code to set `disconnected` to false, but pingTimer maybe already broken when pingResp  is already false in last connection.
https://github.com/mqttjs/MQTT.js/blob/37b12cb94737acddfe0fa016e013516ba3b9a031/lib/client.js#L1481-L1489

**Comment by rodrigobrochado** [comment]
The `disconnected` property should be already deprecated, following issue #690, but seems to be abandoned. 

BTW, I'm having some instabilities with the client, but I'm testing some boosts on the broker settings to see if it fixes them. While trying to find some solution, I've also take a look on the code and this part took my attention:

https://github.com/mqttjs/MQTT.js/blob/d8be59eba419d65ad2f46734623fd91ec437d6e2/lib/client.js#L1551-L1555

If `disconnected` is deprecated, the condition there should be changed to `!this.connected` and I doubt the goal of the `return` statement, although I didn't reviewed it exhaustively.
Don't know if it helps you @yyjdelete , but just to say that I'm also having issues and have some doubts in client.js

It'll be great if you have some time to comment @mcollina :)

**Comment by YoDaMa** [comment]
@rodrigobrochado I'm working to aggregate all this good feedback so we can make sure it gets addressed in the "vNext" (major version update) of this library. Could you provide a discussion commend here: https://github.com/mqttjs/MQTT.js/discussions/1324, with a summary of what you want done from this issue. It would be helpful.

**Comment by rodrigobrochado** [comment]
Thanks @YoDaMa. I think the huge work you've done in #1318, #1325 and are doing on vNext will probably fix this issue. 

My client was misbehaving and seemed to be related to the broker rejecting packages when it was full. When digging on the client source code, I've come to the  strange behavior of the `disconnected` property, but that was vanished on #1318.
Thanks for your work!

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
