### ISSUE TITLE
default store has clean: true even if I connect with clean: false

### ISSUE THREAD

**Issue by jedwards1211** [mqttjs/MQTT.js#1286]
Shouldn't the default in-memory store inherit the `clean` option from the connection settings?

**Comment by redboltz** [comment]
I have added clean option to the store.
See #706 and #707.
And the comment https://github.com/mqttjs/MQTT.js/pull/707#discussion_r148088223 , 
I think that the current behavior is the original author's policy.
So I chose the way passing clean: false option to both mqtt.Client and Store.

**Comment by jedwards1211** [comment]
Nothing about those threads seems to indicate anyone's opposed to constructing default stores with `clean: false` if the client was constructed with `clean: false` though?

**Comment by redboltz** [comment]
I understand. I think that it is useful that the default store inherit clean options of the client too.

**Comment by redboltz** [comment]
For your information.
I personally passing stores to the client. Both the stores and the client have the same clean flag.
The reason I do that is keeping the session after disconnection **from the client**.
If I understand correctly, after calling client.end() then no operation is permitted such as client.reconnect().
The concept of end() is end, not disconnect.
But end() is the only way to send disconnect packet from the client.
My usecase requires the disconnection from the client side. And later, connect again with the kept session.
So I need to create the new client for the 2nd connection. At that time I pass my store to the client.
So my store need to live after the first connection is end.

But if users only use the clean:false store for reconnection that is caused **by closing from the broker side**, default internal store with inheriting clean flag is useful.

**Comment by jedwards1211** [comment]
If stores had a `clear()` method instead of a clean option, that gets called only when the client makes a connection or disconnection with `clean: true`, it would still work fine for your use case of transferring the store to a new client.

**Comment by YoDaMa** [comment]
@jedwards1211 if the client would control the clean flag, and the client were destroyed, then the clean flag controlling the store would also be lost. Yes? The current configuration maintains the state of the flag on the store, so regardless of the health of the client, the flag is persisted.

**Comment by jedwards1211** [comment]
@YoDaMa If the connection was made with `clean: true` then upon disconnect it will clear the store, and this is all good since the data should be cleared regardless of whether the next connection will be clean or not.

So in the case where a `clean: false` connection ends and data is left in the store:
If the next client is created with `clean: false`, all good to go
If the next client is created with `clean: true`, then it would just clear out the store before connecting

The store only uses the clean flag value when the client closes it, so it doesn't need to persist the flag value.

**Comment by YoDaMa** [comment]
Thanks for this issue @jedwards1211, we should incorporate these store updates into vNext. Please add your comments to the vNext (aka major version update) discussion here: https://github.com/mqttjs/MQTT.js/discussions/1324.

I will be focusing my work on the client, if you offer a PR to change the store currently, that change will likely be incorporated into the Store for vNext.

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
