### ISSUE TITLE
Reconnect fails if reconnect attempts goes beyond count 6

### ISSUE THREAD

**Issue by Prashant459** [mqttjs/MQTT.js#1295]
Procedure to reproduce issue:

1. Connect to MQTT
2. Unplug Ethernet cable and let the router be on. wifi on device should receive becon frame
3. Let the reconnect attempt goes beyond count 6
4. plug in the ethernet cable 

Device fail to reconnect though reconnect attempts continue to occur.

**Comment by yanxiaochong** [comment]
hai, @Prashant459 has you solve this problem? I have face same issue

**Comment by Prashant459** [comment]
It was coding issue at myside. One of the queue in kernel was not getting flushed hence timeout used to occur for me. It was not at all related to MQTT library.

**Comment by yanxiaochong** [comment]
Thanks
