### ISSUE TITLE
Can the MQTT service be shared with Node-Koa

### ISSUE THREAD

**Issue by wjm0913** [mqttjs/MQTT.js#1297]
Hello, I'm a beginner MQTT，Can the MQTT service be shared with Node-Koa，Just like WS

![image](https://user-images.githubusercontent.com/45306520/124106916-4788da00-da97-11eb-891e-83aa1753186e.png)

**Comment by wjm0913** [comment]
@YoDaMa

**Comment by YoDaMa** [comment]
Hey @wjm0913 thanks for creating this question issue. The answer is I don't know. I haven't worked with Node-Koa. If you can share what Node Koa is and what is necessary to share MQTT, I could give a better answer.

**Comment by ChenMatsu** [comment]
> @YoDaMa

Hi, I use mqtt with koa framework. Basically, no matter express or koa, it should work as expected. My setup is to listen to a certain topic using mqtt and send the topic to react app by using Aedes broker which transfer Matt into ws.
