### ISSUE TITLE
WebSocket connection to <AWS IoT Url> failed:

### ISSUE THREAD

**Issue by sean-paterson** [mqttjs/MQTT.js#1302]
I am working with this library for my AWS IoT MQTT topics. However, I've run into an issue when trying to connect to the  presigned-url of the following format:

`wss://<endpoint>.iot.us-west-2.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<credential>%2Fus-west-2%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=<date>&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=<signature>&X-Amz-Security-Token=<security-token>`

 Here is the sample code I've used for this test:
 
```
import * as mqtt from 'mqtt';

try {
  const options: Partial<IClientOptions> = {
    will: {
      topic: 'hello',
      payload: JSON.stringify({ clientId: '1', username: 'sean' }),
      qos: 1,
      retain: true
    },
    port: 443,
    clientId: '1', 
    username: 'sean'
  };
const client = mqtt.connect(
  request.url,
  options);

console.log(client);

client.on('connect', function() {
  client.subscribe('hello', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  });
});

client.on('error', (err) => {
  console.log('error', err);
  client.end()
});

} catch (error) {
  console.log(error);
}
```
 
 Unfortunately, when I boot up my webpage, I am receiving the following repeated error in the Chrome dev tools:

`WebSocket connection to <AWS IoT Url> failed:`

Usually, there is an actual error message displayed after the _'... failed:'_ string. In the code, I am seeing a nop function that is logging the error. Just curious what errors usually cause the nop function to be called and how could I can begin testing why my url is failing to connect?

**Comment by sean-legitscript** [comment]
Any thoughts on this? I also tested the sample test:
```
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://test.mosquitto.org')

client.on('connect', function () {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})
```

Getting the following error:
`stream.js:64 WebSocket connection to 'ws://test.mosquitto.org/' failed: `

**Comment by sean-paterson** [comment]
Any thoughts on this? I also tested the sample test:
```
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://test.mosquitto.org')

client.on('connect', function () {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})
```

Getting the following error:
`stream.js:64 WebSocket connection to 'ws://test.mosquitto.org/' failed: `

**Comment by sean-paterson** [comment]
Any thoughts on this one? I've been spending a few days trying to understand the empty error message but not really getting anywhere. I really want to use this library but this situation is definitely stalling my progress. Is there any documentation I could look over to help me understand the empty error message?

**Comment by sean-paterson** [comment]
Found out that my AWS IoT IAM credentials were invalid so I was unable to properly connect to the cloud. If yall have time, it would be useful if the connect function would notify that this might be the problem. The current functionality of displaying an empty error message made it difficult to actually debug the problem 🤔

**Comment by YoDaMa** [comment]
does this mean you’d like MQTT.js to provide more verbose error logging or that you’d like the AWS broker to provide errors upon authentication failure?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YoDaMa** [comment]
closing, but going to note that there's some good insight here for vNext. 

Better error handling for auth failures (or just guidance on how to use the callbacks to identify auth failures?) 

**Note that sometimes this is simply the broker's fault for not providing an error.** (With that, maybe we should format the error if it's empty to say "No Error Provided by Broker")
