### ISSUE TITLE
Enable mqtts, report an error

### ISSUE THREAD

**Issue by weiliudong** [mqttjs/MQTT.js#1309]
After testing, when the nodejs environment is higher than version 9.0.0,
let options = {
         clientId: username,
         password: password,
         username: username,
         rejectUnauthorized: true,
         key: xxx,
         cert:xxx,
         ca: xxx
     };
Enable mqtts, report an error

**Comment by YoDaMa** [comment]
@weiliudong thanks for contributing an issue. Can you provide further details on what you mean here? I'm sorry but I don't understand exactly how to repro or what the bug is.
