### ISSUE TITLE
On connect event callback ConnackPacket

### ISSUE THREAD

**Issue by ccarcaci** [mqttjs/MQTT.js#1321]
I have this snippet of code:
```
const client = mqtt.connect('mqtt://test.mosquitto.org')
client.on('connect', (packet: mqtt.IConnectPacket) => {
  expect(packet.protocolVersion).toBe(5)
  done()
})
```

The signature of the 'connect' listener is declared as:
https://github.com/mqttjs/MQTT.js/blob/master/types/lib/client.d.ts#L103
Where the `OnConnectCallback` type is:
https://github.com/mqttjs/MQTT.js/blob/master/types/lib/client.d.ts#L69

But when I put a breakpoint on this line:
```
expect(packet.protocolVersion).toBe(5)
``` 

I have a Connack-shaped packet as response (see picture below).
![Screenshot from 2021-08-30 19-08-12](https://user-images.githubusercontent.com/7973726/131377827-04e86178-327a-434d-aeff-4192b35c7116.png)

The Connack packet is aligned with the specs here: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901074

Is it wrong to have the Connect packet into the on connect callback signature?

**Comment by YoDaMa** [comment]
> Is it wrong to have the Connect packet into the on connect callback signature?

I don't fully get this last point. Are you saying "Is it wrong that the code I wrote uses mqtt.IConnectPacket as the type for the packet on the connect callback?"

if so, then yes. It might also be a bug in our typing.

Code is a bit difficult to follow, but see here: https://github.com/mqttjs/MQTT.js/blob/dbdbe454a21df49d1ee7ead8dda3444c50b66065/lib/client.js#L1551

`_onConnect` is called by `handleConnack` so it's passing back an `IConnackPacket`. 

If you wanna make a contribution to fix this, be my guest.

**Comment by ccarcaci** [comment]
> Are you saying "Is it wrong that the code I wrote uses mqtt.IConnectPacket as the type for the packet on the connect callback?"

Yes, exactly, I was expecting, from the signature, to have a Connack packet but I got a Connect one.

> If you wanna make a contribution to fix this, be my guest.

I'll get back with a PR in the next days.

Thank you :)

**Comment by YoDaMa** [comment]
great. I will keep this in mind with the vNext rewrite too (https://github.com/mqttjs/MQTT.js/discussions/1324). Keep an eye on it and if there's a bug popping up there notify me.

**Comment by ccarcaci** [comment]
PR filed.
https://github.com/mqttjs/MQTT.js/pull/1333

**Comment by ccarcaci** [comment]
PR merged!
