### ISSUE TITLE
IClientPublishOptions.payloadFormatIndicator type definition specifies it must be a number, but it only works with a boolean value.

### ISSUE THREAD

**Issue by mg90707** [mqttjs/MQTT.js#1334]
Hello,
according to the typescript definitions in client-options.d.ts IClientPublishOptions.payloadFormatIndicator must be a number. However when passing a number (0 or 1) publishing fails, because in the "mqtt-packet" package the payloadFormatIndicator is checked for a boolean value (false or true) and not a numeric value.

This is the check that fails for a numeric value:
https://github.com/mqttjs/mqtt-packet/blob/23774e79e0ca83a718b95d254414964e7a421b1f/writeToStream.js#L902

According to the docs here `https://github.com/mqttjs/MQTT.js` payloadFormatIndicator should be a boolean. Therefore I guess the typescript defitions should get changed accordingly.

I'm using MQTT.js v4.2.8.

**Comment by YoDaMa** [comment]
@mg90707 thanks for identifying it. please make a PR for the change so we can merge it in and get this updated on the next release :)
