### ISSUE TITLE
Connection to broker failed using Websocket + TLS + Chrome

### ISSUE THREAD

**Issue by demian85** [mqttjs/MQTT.js#1335]
Hey guys. I'm really confused and this is driving me crazy. Please help me out.
I have a Web app using this lib to connect to a custom broker implementation (aedes) using a secure websocket connection.
It has been working forever, up until a few days ago. Now it magically fails ONLY in Chrome an Safari. It works in Firefox!

This is the error I keep getting over and over again. There are no logs on the server-side because it's like the browser closes the connection before it is even established!

![image](https://user-images.githubusercontent.com/470630/136216068-f7995ced-72f6-45a8-a12b-284008fdc7e1.png)

Does anyone have an idea what the hell is going on? Is this something related to the TLS certificates? Those have been renewed a month ago and will expire in 2 months. Double checked. Also, and again, in Firefox it works!

Thanks!

**Comment by demian85** [comment]
This is even weirder than I thought. It works on Chrome + Linux. The problem seems to be Mac + Chrome. Is this for real? What changed in the latest Chrome version that broke everything?

**Comment by demian85** [comment]
Pump! 
I'm still having the same weird issue and I cannot even find anything useful in Google...
Can Websockets be established cross-domain? It always worked like that. Did anything change lately?
It still works on Firefox!

**Comment by demian85** [comment]
Tried changing the domain for an IP, tried changing protocol, ws:// ws://, nothing works! What does this mean? Worst error message ever...
![image](https://user-images.githubusercontent.com/470630/145417412-0ba5a39f-e608-48b8-8fd4-8ba0a3f4a474.png)

**Comment by YoDaMa** [comment]
@demian85 please give a reproducible example and we would be happy to see what your problem is. Right now I cannot follow you.

**Comment by pablogallero** [comment]
Hello, I'm having the same issue. Any idea what can I do?

**Comment by angelofan** [comment]
I'm having the same issue.

**Comment by robertsLando** [comment]
I think this problem only happens when the server certificate isn't trusted for some reason

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

**Comment by jaketakula** [comment]
hey, we are having this issue with mqttjs v4.2.8.
it happens realy but when it happens, the broswer keeps failing to connect.
the place is exactly same at `new WebSocket()`
does nayone can help ? thx a lots.

**Comment by robertsLando** [comment]
@jaketakula Firstly update to latest 5.1.3

**Comment by jaketakula** [comment]
> @jaketakula Firstly update to latest 5.1.3

thx for the quick reply. will give it a try and update it later on.

**Comment by 0viii0viii** [comment]
@jaketakula any update on this issue?

**Comment by robertsLando** [comment]
I sincerly have no clue about this as I'm using WSS with mqttjs in almost all my projects without any issue. If someone can give me some debug logs or else to reproduce the issue I will give them a look. In the meanwhile I close this

**Comment by jaketakula** [comment]
No worries. We can close it. Martha is really nice project. I appreciate
the efforts and time you out on this project that benefits a lots people. I
need to talk to team and create ticket to bump the version. As currently we
are busy with something more important. But I promise this will bump and
will update here. Thank you very much!
