### ISSUE TITLE
@types/ws is missing from dev dependancies

### ISSUE THREAD

**Issue by jdm-hexagon** [mqttjs/MQTT.js#1340]
Not sure if it's omission by design or not, but the type definition for `ClientOptions` in `node_modules/mqtt/types/lib/client-options.d.ts` is missing because `@types/ws` hasn't been added as a dev dependancy, requiring it be added manually to every project that uses `mqtt`.

**Comment by vishnureddy17** [comment]
Looks like this was addressed in #1333.
