### ISSUE TITLE
Connection refused: Bad username or password

### ISSUE THREAD

**Issue by nicoworq** [mqttjs/MQTT.js#1345]
Hi! I'm trying to connect to a Thingstream broker running MQTT 3.1.1, using user and pass. 

```
  var username = "user";
  var pass = "pass";
 
  var client = mqtt.connect('mqtt:mqtt.thingstream.io',
    {   
      username: username,
      password: pass,
    }
  )
```

But I'm getting this error: 

```
Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (\mqttNode\node_modules\mqtt\lib\client.js:1190:15)
    at MqttClient._handlePacket (\mqttNode\node_modules\mqtt\lib\client.js:424:12)
    at work (\mqttNode\node_modules\mqtt\lib\client.js:321:12)
    at Writable.writable._write (\mqttNode\node_modules\mqtt\lib\client.js:335:5)
    at doWrite (\mqttNode\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (\mqttNode\node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at Writable.write (\mqttNode\node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12) {
  code: 4
```

I'm able to connect without problems using mosquitto client.

Any suggestion? Thanks in advance!

**Comment by nicoworq** [comment]
Nop, I'm able to connect without problems using mosquitto client.

**Comment by msalafia** [comment]
Probably because mosquitto_pub and mosquitto_sub bypass authentication on mosquitto. As i remember, there should be a root user called `mosquitto` that is always authorised on the mosquitto tools.

**Comment by odeliat** [comment]
Is there a solution for this issue? I'm getting the same error connecting to RabbitMQ.
I have 2 instances of the server, The first connected successfully but the second got this error.
How can I fix this? 

```ts
const client = mqtt.connect(mqtt://hostname:1883, {
      username: "username",
      password: "password",
    });
```

**Comment by moeiscool** [comment]
i have this same error

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

**Comment by frank-niu-github** [comment]
> MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

I used the version 5.3.5 also have same issue.

**Comment by robertsLando** [comment]
Can you connect using another client with same username/password?

**Comment by frank-niu-github** [comment]
> Can you connect using another client with same username/password?

Yes. I successfully used the MQTTX tool and same username/password to connect to our MQTT server.

My vue3 source code as below:

![image](https://github.com/mqttjs/MQTT.js/assets/96820492/aa16a20d-fbae-4716-969b-387c695aec9f)

**Comment by robertsLando** [comment]
do you have a way to see what's coming to the broker? I would be curious to know what broker receives, I think it could be code/decode issue with the password/username, does they contain some strange char/symbol?

**Comment by frank-niu-github** [comment]
> do you have a way to see what's coming to the broker? I would be curious to know what broker receives, I think it could be code/decode issue with the password/username, does they contain some strange char/symbol?

Hi RobertsLando, Thanks for you reply. Actually the username/password have ‘-’ symbol between the string word. How can I fixed this decode issue?

**Comment by robertsLando** [comment]
Mine was just a supposition, the `-` doesn't have any decode issue. I suggest you to try checking what the broker receives

**Comment by frank-niu-github** [comment]
> Mine was just a supposition, the `-` doesn't have any decode issue. I suggest you to try checking what the broker receives

Thanks for your suggestions. This is my fault. Because our MQTT broker setting the HTTP auth. The backend of the cloud server is responsible for verifying the username/password send by Websocket. Always return bad username/password when there is no response from the backend.

**Comment by robertsLando** [comment]
Closiong this for now as I have a feel that when this happens it's most likely a user issue
