### ISSUE TITLE
Can MQTT.js use System trusted/ browser trusted ROOT CA to establish TLS connections over mqtt/websockets.

### ISSUE THREAD

**Issue by tn185075** [mqttjs/MQTT.js#1349]
This is more of a question.

**Comment by jdiamond** [comment]
When running in a browser, the browser creates the TLS connections and you cannot override the CAs so you can only use what the browser trusts.

When running in Node.js, you can override the default CAs but there is no easy option to just tell it to use the system CAs.

MQTT.js just passes options to the core tls module that comes with Node.js. See the options here: https://nodejs.org/dist/latest-v16.x/docs/api/tls.html#tlscreatesecurecontextoptions

**Comment by tn185075** [comment]
Can MQTT.js use browser trusted CA to establish a secure web socket connection with a MQTT broker?

**Comment by tn185075** [comment]
So extending the node ca cert's can make `mqtt.js` establish secure web socket connection?
