### ISSUE TITLE
Problem to connect to a broker using credentials

### ISSUE THREAD

**Issue by franciscogneto** [mqttjs/MQTT.js#1351]
I cant connect to a mqtt broker in my network, i am trying to connect using the following code:

> let client;
try {
    client = mqtt.connect(`mqtt://${brokerIp}:1883`, {username,password});
} catch (error) {
    console.log(error);
    client = mqtt.connect(`wss://${auxBroker}`);
}

the IP, username and password are correct, but i have this response in my aplication:
![image](https://user-images.githubusercontent.com/37386356/140064443-0d38197f-9dcc-4baa-8b90-0b80d0a05d5a.png)
So as you can see, the first connection isn't working but the second is
**Obs: i am using mqtt cdnjs version: 4.2.8**

**Comment by msalafia** [comment]
I think because you cannot use `mqtt://...` on a browser. You can only using websockets from a browser.

**Comment by franciscogneto** [comment]
To solve this problem i needed to implement websocket in my back end application and connect by websocket
