### ISSUE TITLE
How to remove message event?

### ISSUE THREAD

**Issue by chenzesam** [mqttjs/MQTT.js#1354]
I bind **message** event, and i want to remove it when effect return function, so i wirte code below.
```ts
useEffect(() => {
    const fff: OnMessageCallback = (topic, payloadBuffer) => {
      // do something
    };
    mqtt?.on('message', fff);
    return () => {
      mqtt?.off?.('message', fff);
    };
}, [mqtt]);
```
but i got error: **off is undefined...**
so how can it resolve it?

**Comment by vCloudSail** [comment]
Maybe try this:
`
    mqtt?.on('message', null);
`

**Comment by HiScales** [comment]
sir,what is the final solution？

**Comment by vishnureddy17** [comment]
@HiScales, the client is an EventEmitter, please check the [EventEmitter documentation](https://nodejs.org/api/events.html) for details on this.
