### ISSUE TITLE
creat-react-app@5.0.0 run mqtt fail

### ISSUE THREAD

**Issue by conkyliu** [mqttjs/MQTT.js#1370]
`ERROR in ./node_modules/readable-stream/lib/_stream_readable.js 46:13-37
Module not found: Error: Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/buffer/Buffer'.
 @ ./node_modules/readable-stream/readable-browser.js 1:10-63
 @ ./node_modules/mqtt/lib/client.js 12:15-50
 @ ./node_modules/mqtt/lib/connect/index.js 3:17-37
 @ ./src/App.js 8:0-24 27:17-29
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./node_modules/readable-stream/lib/_stream_writable.js 70:13-37
Module not found: Error: Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/buffer/Buffer'.
 @ ./node_modules/readable-stream/readable-browser.js 4:0-55
 @ ./node_modules/mqtt/lib/client.js 12:15-50
 @ ./node_modules/mqtt/lib/connect/index.js 3:17-37
 @ ./src/App.js 8:0-24 27:17-29
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./node_modules/readable-stream/lib/internal/streams/buffer_list.js 74:15-32
Module not found: Error: Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/buffer/Buffer'.
 @ ./node_modules/readable-stream/lib/_stream_readable.js 72:17-58
 @ ./node_modules/readable-stream/readable-browser.js 1:10-63
 @ ./node_modules/mqtt/lib/client.js 12:15-50
 @ ./node_modules/mqtt/lib/connect/index.js 3:17-37
 @ ./src/App.js 8:0-24 27:17-29
 @ ./src/index.js 7:0-24 11:33-36

ERROR in ./node_modules/string_decoder/node_modules/safe-buffer/index.js 4:13-30
Module not found: Error: Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/buffer/Buffer'.
 @ ./node_modules/string_decoder/lib/string_decoder.js 24:13-42
 @ ./node_modules/readable-stream/lib/_stream_readable.js 163:40-80 325:38-78
 @ ./node_modules/readable-stream/readable-browser.js 1:10-63
 @ ./node_modules/mqtt/lib/client.js 12:15-50
 @ ./node_modules/mqtt/lib/connect/index.js 3:17-37
 @ ./src/App.js 8:0-24 27:17-29
 @ ./src/index.js 7:0-24 11:33-36

`

**Comment by MrSatan** [comment]
same here. webpack 5 has removed support for node buffer.

**Comment by erasabi** [comment]
same. is there any fix or workaround in sight?

**Comment by msalafia** [comment]
Only [https://github.com/mqttjs/MQTT.js/issues/1412#issuecomment-1046369875](this) worked for me. But it's a really raw workaround.
