### ISSUE TITLE
publish() does not always call the callback

### ISSUE THREAD

**Issue by vishnureddy17** [mqttjs/MQTT.js#1372]
In the `publish()` function on `MqttClient`, there is the `publishProc()` function defined inside that does the important bits for `publish()`. `publishProc()` appears to return a boolean indicating success or failure of the operation. However, in the case where `publishProc()` returns false (i.e., when the message ID provider runs out of IDs, causing `_nextId()` to return `null`), the callback passed to `publish()` will never be called. The offending code is below:

https://github.com/mqttjs/MQTT.js/blob/2679952587a0e3e1b5fcbfd6b11fca72c65fba95/lib/client.js#L619-L626

This `proc()` patten is seen elsewhere in the client code, so other cases like this should be investigated if and when this issue gets worked on.

**Comment by YoDaMa** [comment]
@vishnureddy17 do you think this is still an issue?

**Comment by vishnureddy17** [comment]
@YoDaMa yes, but it'd only be an issue if there are 2^16 inflight messages

**Comment by redboltz** [comment]
> @YoDaMa yes, but it'd only be an issue if there are 2^16 inflight messages

I added `UniqueMessageIdProvider()` to solve the issue and it has been merged.
The default behavior is the first messageId (MQTT's Packet Identifier) is randomly choosed.
See
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/default-message-id-provider.js#L16
And then, incremental value is used.
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/default-message-id-provider.js#L27-L32

It could be conflict. If conflict happens, the behavior is undefined.

So I introduced UniqueMessageIdProvider().
https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/README.md

> messageIdProvider: custom messageId provider. when new UniqueMessageIdProvider() is set, then non conflict messageId is provided.

When you set it as the option, the messageId is never coniflct. The allocation algorithm is returing the smallest vacant value.
See https://www.npmjs.com/package/number-allocator

If the messageId rans out, then the message is enqueued. So **the callback is not called immediately**. But if messageId would be reusable by PUBACK, PUBCOMP, SUBACK, or UNSUBACK receiving, then the enqueued message would be processed and **the callback is called**.

UniqueMessageIdProvider() isn't used by default. You need to set it as the option.

**Comment by vishnureddy17** [comment]
> If the messageId rans out, then the message is enqueued. So **the callback is not called immediately**. But if messageId would be reusable by PUBACK, PUBCOMP, SUBACK, or UNSUBACK receiving, then the enqueued message would be processed and **the callback is called**.

From my testing, the callback will NOT be called if using `UniqueMessageIdProvider` and the message Ids run out. Here's a quick experiment I ran to test this:
1. Modify `UniqueMessageIdProvider` code to change 65535 to some low number like 5. This will make it easier to see what happens when message IDs run out. https://github.com/mqttjs/MQTT.js/blob/f04c24bd082aa9f6db2da6da65e40b2e0b692bcc/lib/unique-message-id-provider.js#L14
2. Create new client (tls protocol) with messageIdProvider option set to `new UniqueMessageIdProvider()`
3. Publish 10 messages with QoS 1 quickly

Result: only the 5 of the publishes result in the callback being called.

Expected behavior: Callback gets called 10 times. 5 succeed and the other 5 have an error due to not enough message IDs left.

**Comment by redboltz** [comment]
@vishnureddy17 thank you for additional information.
I reproduced the issue and fixed it by #1372. Please test using it.

The expected behavior is a little different from yours.

After this fix, the expected behavior is as follows:

> If the messageId rans out, then the message is enqueued. So the callback is not called immediately. But if messageId would be reusable by PUBACK, PUBCOMP, SUBACK, or UNSUBACK receiving, then the enqueued message would be processed and the callback is called.

So in your test case, first 5 publishs' callbacks are called *when the packet is sent*. The rest 5 publish's callbacks are called *when the packet is sent* too. But the timing is different. In order to send sixth publish, messageId is needed. So the publish is enqueued until the messageId become reusable. When PUBACK is received, then messageId becomes reusable. Then qneueued sixth publish is processed then callback is called.

Finally, all callbacks are called.

**Comment by vishnureddy17** [comment]
Yep, just tested and seems good to me. Thanks! :)
