### ISSUE TITLE
Remove babel-eslint from dependencies

### ISSUE THREAD

**Issue by cesarfd** [mqttjs/MQTT.js#1382]
For some reason, release 4.3.0 includes `babel-eslint` as a dependency which is supposed to be a dev only package (and it's also deprecated). This makes hundreds of packages being listed without the `"dev"` flag in package-lock.json.

**Comment by YoDaMa** [comment]
should be removed. thanks for the catch.

**Comment by YoDaMa** [comment]
released 4.3.1 as a patch update for this bug. PR: https://github.com/mqttjs/MQTT.js/pull/1383
