### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by NorthernMan54** [mqttjs/MQTT.js#1385]
Over in the Homebridge community we are chasing down an issue that is triggered by having multiple homebridge plugins leveraging MQTT and exposes this issue with the collections package.  https://github.com/montagejs/collections/issues/241

Looking thru the commits for mqtt, #1301  back in the summer exposed the issue.

Leaving this here incase others are experiencing the same issue.

Reported problems

https://github.com/NorthernMan54/homebridge-alexa/issues/481
https://github.com/dgreif/ring/issues/844
https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1240

**Comment by NorthernMan54** [comment]
At the present time we are recommending that the impacted plugins pin the mqtt dependancy to mqtt version 4.2.8 to workaround the issue.

**Comment by YoDaMa** [comment]
can @NorthernMan54 confirm the fix in #1386 fixes the issue the HomeBridge community is seeing?

**Comment by NorthernMan54** [comment]
@YoDaMa I can confirm that collections 5.1.13 and number-allocator 1.0.8 resolves the issue ( just finished testing this )

**Comment by YoDaMa** [comment]
ok, I will release a patch update this morning.

**Comment by YoDaMa** [comment]
released. please validate. https://github.com/mqttjs/MQTT.js/pull/1386/files and https://github.com/mqttjs/MQTT.js/pull/1388 handled this bug.

**Comment by NorthernMan54** [comment]
Removed the workarounds, and updated everything.  And can confirm that issue is resolved.  Tks very much

**Comment by NorthernMan54** [comment]
PS And a big thanks for your support on this issue from the Homebridge community

**Comment by YoDaMa** [comment]
you're welcome :)
