### ISSUE TITLE
When switching the network, mqtt sometimes has the problem that the heartbeat remains, but the push is not received

### ISSUE THREAD

**Issue by kaixinkaixinmeifannao** [mqttjs/MQTT.js#1387]
When switching the network, connect first and then detect the heartbeat. When the heartbeat is disconnected, close the connection, resulting in the absence of the channel and the heartbeat continues
![C763F1D7-6AD4-436c-B055-6B547788BB3B](https://user-images.githubusercontent.com/45986999/147643682-0c4a9c54-8453-4722-b7ff-f8175d31a037.png)

**Comment by YoDaMa** [comment]
Can you provide me with a version of MQTT.js you are using, the platform (Linux? Windows? Mac?), and a code snippet for reproducing. I do not know how to assist you otherwise.
