### ISSUE TITLE
when the password is incorrent,only close event, no error event

### ISSUE THREAD

**Issue by liu-xinhui** [mqttjs/MQTT.js#1406]
```javascript
const mqtt = require("mqtt");
        const client = mqtt.connect("ws://third.elevatorstar.com:7004/mqtt", {
          clientId: this.device.id,
          username: this.device.id,
          password: this.device.secret + "1",
          reconnectPeriod: 0,
        });
        client.on("connect", function() {
          console.log("connect");
        });

        client.on("close", () => {
          console.log("close");
        });

        client.on("error", function(error) {
          console.log(error);
        });
```
The error event no call when password is incorrent

**Comment by liu-xinhui** [comment]
if i enable reconnect,only reconnect and close event. 
When the error event call?

**Comment by liu-xinhui** [comment]
when the password is incorrent, 4.3.4 no error event.but 4.2.1 is no this problem

this is the 4.2.1 error message，4.3.4 no this
```
Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (client.js:1184)
    at MqttClient._handlePacket (client.js:424)
    at work (client.js:321)
    at Writable.writable._write (client.js:335)
    at doWrite (_stream_writable.js:428)
    at writeOrBuffer (_stream_writable.js:417)
    at Writable.write (_stream_writable.js:334)
    at Duplexify.ondata (_stream_readable.js:619)
    at Duplexify.emit (events.js:153)
    at addChunk (_stream_readable.js:291)
```

**Comment by liu-xinhui** [comment]
I have try 4.3.4, 4.3.0, 4.2.8, 4.2.6，4.2.1.
only 4.2.1 has the error msg. This big problem has occured a year ago, but no one find？

**Comment by caoyawu** [comment]
I tested 4.3.4, it's work well  and i got the error message

**Comment by liu-xinhui** [comment]
@caoyawu you can try my server，ws://121.40.115.160:7024/mqtt

**Comment by caoyawu** [comment]
@liu-xinhui I get "Connection refused: Not authorized" for "ws://121.40.115.160:7024/mqtt"

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/153360025-b7ceba63-7027-4cdc-a295-62a845b326a3.png)
![image](https://user-images.githubusercontent.com/7698511/153360035-7b1f0bff-d887-457a-a1a0-c3014ff4b0cf.png)

@caoyawu 
I create a new VUE project to test,not got error also.
I have push to git,you can try my code.
[https://gitee.com/desire/mqtt-test.git](https://gitee.com/desire/mqtt-test.git)

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/153370604-f34ee123-3172-4b06-a6e2-fa87899cde96.png)

http://jsrun.net/Fj9Kp/edit

you can try online,also only close,no error

**Comment by caoyawu** [comment]
![1644485833(1)](https://user-images.githubusercontent.com/5251061/153379594-d0282689-0966-41ba-86b8-522fab2b8ff9.png)

**Comment by liu-xinhui** [comment]
@caoyawu 
It should print error message every time， not sometimes print or sometimes not. 
I have tried reconnect. Fortunately, you can get an error after try many times. 
unfortunately, there are no error after hundreds of times

you can change `https://unpkg.com/mqtt@4.3.5/dist/mqtt.min.js ` to `https://unpkg.com/mqtt@4.2.1/dist/mqtt.min.js`
will always show error msg.

**Comment by YoDaMa** [comment]
@liu-xinhui can you verify that the MQTT spec defines this behavior. I'm wondering if the behavior you expected in 4.2.1 but no longer see in more recent versions was a bug.

**Comment by Karl-Sparticle** [comment]
It happen to me also for 4.3.7.
I have try this version https://unpkg.com/mqtt@4.2.1/dist/mqtt.min.js。There is error event if default options was used.

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists
