### ISSUE TITLE
WebSocket types aren't pulled in by client libraries

### ISSUE THREAD

**Issue by StenAL** [mqttjs/MQTT.js#1408]
Hello!

I have TypeScript project that depends on `mqtt`. If I enable the `strict`  compiler option in my project, it refuses to build because of a implicit-any match in `mqtt`.

This is because [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) is set to `false` by default which means tsc will try to type-check `mqtt` as well. The specific line it fails at is importing a type from `ws` in [types/lib/client-options.d.ts](https://github.com/mqttjs/MQTT.js/blob/master/types/lib/client-options.d.ts#L3):
```
node_modules/mqtt/types/lib/client-options.d.ts:3:31 - error TS7016: Could not find a declaration file for module 'ws'. '/project/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm install @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

3 import { ClientOptions } from 'ws'
                                ~~~~


Found 1 error.
```

This happens because `@types/ws` is declared as a devDependency so it isn't automatically pulled in to my project. To fix this, `mqtt` would either need to move `@types/ws` to dependencies or at least document that I should install it myself (similar to what's done with `@types/node` [here](https://github.com/mqttjs/MQTT.js/blob/main/README.md?plain=1#L799-L800)).

**Comment by YoDaMa** [comment]
yeah the typings story right now isn't great... would welcome a PR to update the documentation. I don't think we should move @types/ws to dependencies. Is it normal to ever put a types dependency as a dependency vs a dev dependency?

**Comment by StenAL** [comment]
In the past the official suggestion used to be just save types in regular dependencies (https://github.com/microsoft/types-publisher/issues/81) but seems like this is no longer the case (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md?plain=1#L32).

An issue with keeping the types in devDependencies is that if my project uses a newer version of `@types/ws` or `@types/node` then the types might be incompatible with types in this repo. However, bundling the types with MQTT does increase bundle size so I don't know...

I'll open a PR to update the docs for now.

**Comment by Kuinox** [comment]
Hello,
importing `@types/ws` when consuming `mqtt` package doesn't work when using yarn 3.  
mqtt.js is importing files from `@types/ws` therefor must declare it as a dependency, not a devDependency.

**Comment by Kuinox** [comment]
@YoDaMa if you didn't noticed my late comment.
