### ISSUE TITLE
can we add 'ETIMEDOUT' to socketErrors so that we can judge whether the broker is available？

### ISSUE THREAD

**Issue by caoyawu** [mqttjs/MQTT.js#1410]
currently，the socketErrors is
`const socketErrors = [
  'ECONNREFUSED',
  'EADDRINUSE',
  'ECONNRESET',
  'ENOTFOUND'
]`

when we are connecting to a unavailable broker, there is no error event and we cann't judge whether the broker is available.
so I suggest add 'ETIMEDOUT' to socketErrors, then we can get error event if broker is unavailable.

**Comment by YoDaMa** [comment]
sure. make a PR. @caoyawu
