### ISSUE TITLE
pubrel is not send out when using QoS2 and publish in client has no callback

### ISSUE THREAD

**Issue by Apollon77** [mqttjs/MQTT.js#1430]
I was debugging an issue where no pubrec was sent  als answer of an pubrec for a QoS2 published message. The reason was basically that my publish method call did not had a callback provided and so it was running in this case https://github.com/mqttjs/MQTT.js/blob/fe7828886bb95358bc892d66309f955ed8ed0b82/lib/client.js#L1587

My understanding was that when using QoS 2 then this publish -> pubrec -> pubrel (and so on...) should be done in any case, so is this intended behaviour that a not provided callback prevents all of this?

**Comment by yangpu** [comment]
Message with qos 2 is not sent anymore after upgrading from v4.3.2 to v4.3.6, and this is a bug or break change?

**Comment by Apollon77** [comment]
@yangpu Did you specified a callback on publish? As described I was able to "fix" it by providing the callback

**Comment by yangpu** [comment]
No callback is provided for publishing message. However, the library should keep the same interface while refactoring under the patch version, or note the break change. Thanks alot.

**Comment by BertKleewein** [comment]
I introduced this bug with #1401. I am investigating.

**Comment by BertKleewein** [comment]
Fixed for next release:  https://github.com/mqttjs/MQTT.js/pull/1443
