### ISSUE TITLE
Vite^2.6.4 + Vue^3.2.16 + TypeScript^4.4.3 Use error reporting

### ISSUE THREAD

**Issue by sunjunjie1314520** [mqttjs/MQTT.js#1448]
1. step
![image](https://user-images.githubusercontent.com/34414647/158141217-9977e8e2-9cca-4cbd-a6f6-cccf6ac5fb59.png)
2. step
![image](https://user-images.githubusercontent.com/34414647/158141397-8554c3d7-e9e7-4a37-ab54-fd0a5eb67f61.png)
3.step
![image](https://user-images.githubusercontent.com/34414647/158141530-8afa0fec-91e7-4bee-8ff1-39f1426e6d10.png)
The console reported an error
What do I need to do

**Comment by nanxfu** [comment]
same as you

**Comment by sunjunjie1314520** [comment]
文件已收到！谢谢！

**Comment by nanxfu** [comment]
I solved this proble with #1269 

- Use ``` import * as mqtt from 'mqtt/dist/mqtt.min';```

- Add ```"skipLibCheck": true ```to your tsconfig.json
- Create a shims-mqtt.d.ts with
```
declare module 'mqtt/dist/mqtt.min' {
  import MQTT from 'mqtt'
  export = MQTT
}
```

**Comment by kkstun** [comment]
Not work  use " "vite": "^2.9.5", "typescript": "^4.6.3", "vue": "^3.2.33""   .  Any better idea?

**Comment by XDEcat-Geek** [comment]
> [我用#1269](https://github.com/mqttjs/MQTT.js/issues/1269)解决了这个问题[](https://github.com/mqttjs/MQTT.js/issues/1269)
> 
> * 利用` import * as mqtt from 'mqtt/dist/mqtt.min';`
> * 添加`"skipLibCheck": true `到您的 tsconfig.json
> * 创建一个 shims-mqtt.d.ts
> 
> ```
> declare module 'mqtt/dist/mqtt.min' {
>   import MQTT from 'mqtt'
>   export = MQTT
> }
> ```

谢谢，我也遇到了同样的问题

**Comment by sunjunjie1314520** [comment]
文件已收到！谢谢！

**Comment by Calerme** [comment]
> I solved this proble with #1269
> 
> * Use ` import * as mqtt from 'mqtt/dist/mqtt.min';`
> * Add `"skipLibCheck": true `to your tsconfig.json
> * Create a shims-mqtt.d.ts with
> 
> ```
> declare module 'mqtt/dist/mqtt.min' {
>   import MQTT from 'mqtt'
>   export = MQTT
> }
> ```

我用上边的代码解决后，又出现了新问题：

![image](https://user-images.githubusercontent.com/12893097/192074664-578989a2-3d39-455c-8250-ece945bf0b78.png)

**Comment by sunjunjie1314520** [comment]
文件已收到！谢谢！

**Comment by Calerme** [comment]
> > I solved this proble with #1269
> > 
> > * Use ` import * as mqtt from 'mqtt/dist/mqtt.min';`
> > * Add `"skipLibCheck": true `to your tsconfig.json
> > * Create a shims-mqtt.d.ts with
> > 
> > ```
> > declare module 'mqtt/dist/mqtt.min' {
> >   import MQTT from 'mqtt'
> >   export = MQTT
> > }
> > ```
> 
> 我用上边的代码解决后，又出现了新问题：
> 
> ![image](https://user-images.githubusercontent.com/12893097/192074664-578989a2-3d39-455c-8250-ece945bf0b78.png)

我又尝试了如下办法解决了这个问题：

1. mqtt 版本降低为 4.0.1
2. 引用改为 `import mqtt from "mqtt/dist/mqtt.min"`;

**Comment by sunjunjie1314520** [comment]
文件已收到！谢谢！

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

**Comment by sunjunjie1314520** [comment]
文件已收到！谢谢！
