### ISSUE TITLE
Problem when storing message published by a topic

### ISSUE THREAD

**Issue by Malo-B** [mqttjs/MQTT.js#1458]
Hello everyone,
I am developing a react app to display some graphs and to display the real time temperature of a room. I use zigbee2mqtt and mosquitto as a broker. I would like to display the real time temperature on the app. In order to do this, I made this program

 
```
var mqtt=require('mqtt');


const connectUrl = 'localhost:9001'
var client = mqtt.connect(connectUrl)


client.on("connect",function(){	
    console.log("connected");
    })
client.on('error', (error) => {
    console.log('Connection failed:', error)
})


var topic = "zigbee2mqtt/sensor_1";
client.subscribe(topic)
client.on('message',function(topic, message, packet){
let msg_sensor_1=message;
	console.log("1st"+ msg_sensor_1);
	
	});

console.log("2nd"+msg_sensor_1);

```

Expectation:
In console : 1st 20°C 2nd 20°C

Reality:
In console : 1st 20°C

 Do you know what I have to change to store the message on my variable ?

It is a program which will run all the time, when a new message is published by a topic I would like to display it in the react app.

Thanks.

Regards

**Comment by Menno00** [comment]
The second console.log is performed only when the program is started while the first is executed each time you receive a message on that topic.
Probably the second also gives you error because the variable is not defined or am I wrong?

**Comment by Malo-B** [comment]
Yes you are right. Do you know a way to extract the variable when I receive a message ?

**Comment by joaopfg** [comment]
@Malo-B Declare it outside the scope of the callback and let just the assignment inside the callback.

**Comment by Malo-B** [comment]
I have already tried it, and I've tried a lot solutions. Maybe with an eventListener ? 
To explain more precisely, I receive a message containing 5 informations (temperature, pressure, battery...) and I want to display the temperature in my home page. I've created a .js file containing the code above, I transform the message to a json and I've made an export var msg_sensor_1 at the end of this file. I've imported this var in my home page. When there is no message published, I display error but when there is a message I display the temperature. 

Thanks for your help !

**Comment by joaopfg** [comment]
@Malo-B If you write it like:

```
var mqtt=require('mqtt');


const connectUrl = 'localhost:9001'
var client = mqtt.connect(connectUrl)


client.on("connect",function(){	
    console.log("connected");
    })
client.on('error', (error) => {
    console.log('Connection failed:', error)
})


var topic = "zigbee2mqtt/sensor_1";
client.subscribe(topic);

let msg_sensor_1;

client.on('message',function(topic, message, packet){
msg_sensor_1=message;
console.log("1st"+ msg_sensor_1);
});

console.log("2nd"+msg_sensor_1);
```

Does it work ?

**Comment by Malo-B** [comment]
No, when the page is loaded, the console display 2ndundefined, then connected. Then when I push the button of my sensor to get the values (or the temperature changes) the console display 1st {temperature…).
I added `export {msg_sensor_1}` at the end. Nothing happened...
Thanks for your help.


![Capture d’écran 2022-03-23 à 17 16 22](https://user-images.githubusercontent.com/76887230/159746122-13bc7f55-5265-4f7b-809e-77e3f08912a2.png)
}

**Comment by Menno00** [comment]
You have undefined because at the beginning msg sensor hasn't got any values and only when you recive a message It changes its value

**Comment by Malo-B** [comment]
Yes I know, I've put a singular value before (36°C) but the value does not change when a new value comes. I made a json.Parse and then msg_sensor_1.temperature to get the right value. 
![Capture d’écran 2022-03-23 à 17 38 40](https://user-images.githubusercontent.com/76887230/159750650-f83701a0-a44a-45bd-a058-40e13fd9c94c.png)
