### ISSUE TITLE
when mqtt server goes offline (host shut off), and comes back online....

### ISSUE THREAD

**Issue by geetee24** [mqttjs/MQTT.js#1466]
when mqtt server goes offline (host shut off), and comes back online....  this library's reconnect handler does not recover and does not reconnect.

Need example showing how to accomplish this

**Comment by doc-han** [comment]
Can you provide a sample of your connection code?
*Note*: when `reconnectPeriod` is set to `0` reconnection is disabled.
[reference](https://github.com/mqttjs/MQTT.js#client)

**Comment by geetee24** [comment]
The code is exactly the same as the example that you provide

**Comment by danbo** [comment]
I think I have the same problem - if server goes away and client keeps trying to publish, 

1. client says error / connection refused
2. Error handler fires - client "ends"
3. client disconnecting error upon upcoming publish events - no recovery when server is back online

```
Error: client disconnecting
    at MqttClient._checkDisconnecting (c:\...\node_modules\mqtt\lib\client.js:577:26)
    at MqttClient.publish (c:\...\node_modules\mqtt\lib\client.js:617:12)
    ...
```

All examples show using client.end() in the error handler. 
```
mqttClient.on('error', function (err) {
    console.log(err);
    client.end();
  });
```

When I remove client.end(), the client library reconnects successfully when the server back and continues to send messages as expected. Other clients listening successfully reconnect on their own and receive messages.

I think it's related to this open issue: #1284 

Also, can someone clarify why/when we would want to call [end()](https://github.com/mqttjs/MQTT.js#end) ?

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
