### ISSUE TITLE
transformWsUrl  not called when connection is closed by Google Iot Core for expired JWT

### ISSUE THREAD

**Issue by Infinitism** [mqttjs/MQTT.js#1473]
Hi, 

I am using mqtt-async and created a client with transformWsUrl defined. This function is never called when the connection is closed with the broker due to expired jwt token. 

The .on('close') callback gets triggered but not the transformWsUrl.

I don't know how to refresh the the jwt token since reconnect() doesn't allow to reconnect with updated connection options.

**Comment by oneEyedSunday** [comment]
hook up to the `reconnect` event, disconnect / end the initial connection.  Then, connect again with fresh credentials
