### ISSUE TITLE
Why does vue fail to use mqtt?

### ISSUE THREAD

**Issue by bbhxwl** [mqttjs/MQTT.js#1490]
![image](https://user-images.githubusercontent.com/26525599/172157790-648d8d74-9a97-4c66-9bc7-582103879a1c.png)

**Comment by nosovk** [comment]
you can use bundled MQTT.js, like one at https://unpkg.com/mqtt/dist/mqtt.min.js
Bundling done via browserify (as far I remember), and all nodejs polyfills will be inside.

Or use another lib https://github.com/mqttjs/MQTT.js/issues/1346, that is browser compatible from start.

Or contribute to mqtt.js (see announcement about v5 in readme)

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
