### ISSUE TITLE
Getting duplicated messages upon more pub/sub

### ISSUE THREAD

**Issue by NayOoLwin5** [mqttjs/MQTT.js#1501]
In my express app, I have a mqtt setup in a function. The pub/sub will run each time I call the api with a new data. The message in on_message callback is getting duplicated with every api call without restarting the server. 
Here is the example - 
```
client  = mqtt.connect("mqtt://broker.hivemq.com",{clientId:"test_id", keepalive: 1000});

client.subscribe('data/test',{qos: 2});
client.publish('data/test', 'tesing1',{qos: 2, retain:false});
 	
 client.on('message', function (topic, message) {
		console.log(message.toString());
});
```
On the first api call - output
```
testing1
```
On the second call - output 
```
testing1
testing1
```
On third - output
```
testing1
testing1
testing1
```
Am I missing something here in my setup? I want only one output with each time it triggers the function.

**Comment by vishnureddy17** [comment]
@NayOoLwin5 Can you clarify which API call you are referring to? Thanks!

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists
