### ISSUE TITLE
Consider exposing Suback packet in Subscribe's completion callback

### ISSUE THREAD

**Issue by bretambrose** [mqttjs/MQTT.js#1510]
Publish and Unsubscribe both use completion callbacks that take the full packet, but Subscribe's callback is the array of granted subscriptions, which keeps the Suback User Properties or Reason String from being exposed to the user.  

I'm not particularly confident that I know what is and isn't a breaking change in Javascript, so I thought I'd wait for some feedback before making a PR along the lines of:

```
export declare type ClientSubscribeCallback = (err: Error, granted: ISubscriptionGrant[]) => void
```
to
```
export declare type ClientSubscribeCallback = (err: Error, granted: ISubscriptionGrant[], packet?: Packet) => void
```

with associated logic update where the Suback is handled:

`callback(err, subs)` to `callback(err, subs, packet)` in subscribe()

**Comment by robertsLando** [comment]
@bretambrose Consider opening a PR to fix this
