### ISSUE TITLE
Inconsistent publish() callback invocations on puback receipt

### ISSUE THREAD

**Issue by bretambrose** [mqttjs/MQTT.js#1511]
This may be intentional but I found it somewhat of a bummer.

If the received puback indicates a failure (by reason code), the user callback will be invoked with the puback packet: https://github.com/mqttjs/MQTT.js/blob/accd78e38aa82c8cc1ea04029e56494276776c87/lib/client.js#L1614

If the received puback indicates a success, the user callback will be invoked with the original publish packet (happens in the store implementation, where the input parameter 'packet' gets aliased/shadowed by a local with the same name): https://github.com/mqttjs/MQTT.js/blob/accd78e38aa82c8cc1ea04029e56494276776c87/lib/store.js#L90-L94

The end result is that there is no way to find out a successful puback's ResponseString and UserProperties (which are probably empty but for completeness sake, it would be nice to have theoretical access).

**Comment by ogis-yamazaki** [comment]
I noticed this problem too.

User callback is executed twice if the received PUBACK indicates failure (by reason code).

invoke callback 1st here. 
https://github.com/mqttjs/MQTT.js/blob/accd78e38aa82c8cc1ea04029e56494276776c87/lib/client.js#L1614

invoke callback 2nd here. 
https://github.com/mqttjs/MQTT.js/blob/accd78e38aa82c8cc1ea04029e56494276776c87/lib/client.js#L1617
https://github.com/mqttjs/MQTT.js/blob/accd78e38aa82c8cc1ea04029e56494276776c87/lib/store.js#L94

**Comment by robertsLando** [comment]
Fixed by #1635
