### ISSUE TITLE
Module parse failed: Unexpected token (120:38) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by wwdDongDong** [mqttjs/MQTT.js#1513]
![image](https://user-images.githubusercontent.com/30905492/179882493-4b7e3dd7-59fb-4a64-9a40-78877bff679c.png)

**Comment by wwdDongDong** [comment]
{
  "name": "topology",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "wwd",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "lint": "eslint --ext .js,.vue src",
    "build": "node build/build.js"
  },
  "dependencies": {
    "@topology/activity-diagram": "^0.3.0",
    "@topology/chart-diagram": "^0.3.0",
    "@topology/class-diagram": "^0.3.0",
    "@topology/core": "^0.5.28",
    "@topology/flow-diagram": "^0.3.0",
    "@topology/layout": "^0.3.0",
    "@topology/sequence-diagram": "^0.3.0",
    "axios": "^0.27.2",
    "element-ui": "^2.15.9",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.2.3",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.14.1",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "sass-loader": "^7.3.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**Comment by shady-xia** [comment]
I have the same problem, Have you solved it?

**Comment by wwdDongDong** [comment]
> I have the same problem, Have you solved it?

我解决了，我安装的相关插件自动安装了4.3.7版本的mqtt，我在node_modules当中删除了mqtt的文件夹，重新安装了mqtt@4.2.7就好了

**Comment by shady-xia** [comment]
谢谢，果然可以了，看了下4.2.7的源码是es5，而4.3.7是es6所以会出问题

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
