### ISSUE TITLE
Error event with Self-Signed certficates

### ISSUE THREAD

**Issue by MHAchristo** [mqttjs/MQTT.js#1514]
I'm getting issues with my Node application connecting to a secured TLS broker, even while passing it our Key, CRT, and Ca files via its env variables.  

```
self signed certificate Error
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```

The connection and communication work outside of the application, so I'm not sure what the issue is with Node being unable to connect to a secure TLS broker.  

I've attempted to set `rejectUnauthorized: false` and `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` as options, without change.

**Comment by zzswang** [comment]
Any update on this?
