### ISSUE TITLE
How to use TLS/SSL two-way authentication connections in browser?

### ISSUE THREAD

**Issue by ysfscream** [mqttjs/MQTT.js#1515]
Hi, guys. I want to use two-way authentication when connecting using WebSocket, but when I use the client certificate, it shows that the connection has failed, so I would like to ask how to use TLS/SSL two-way authentication in the browser?

I am very sorry for the disturbance, I would be very grateful.

Currently, I am configuring the contents of the ca, cert and key files directly into options in the code, but I can't use them, unlike when using TCP connections.

```js
const { host, port, endpoint, ...options } = this.connection
options.rejectUnauthorized = true
options.ca = certs.ca
options.cert = certs.sert
options.key = certs.key
const connectUrl = `wss://${host}:${port}${endpoint}`
this.client = mqtt.connect(connectUrl, options)
```

Because I tested it, it will connect fine if I don't use WebSocket.

The only error message I get is that the connection failed. I think it's an error when creating a new WebSocket client.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/21299158/180713952-d7141733-9272-4a4a-a40d-41349030461c.png">

@YoDaMa

**Comment by MattBrittan** [comment]
"two-way authentication connections in browser" - short answer is "you can't".

Longer answer is that you can use client certificates by setting them up in your OS certificate store (or potentially some kind of smart card). When the browser connects and a client certificate is requested it will attempt to find a certificate in the store (for more info see [here](https://wiki.mozilla.org/PSM:CertPrompt) and [here](https://blog.mozilla.org/security/2021/07/28/making-client-certificates-available-by-default-in-firefox-90/) and [here](https://support.google.com/chrome/a/answer/6080885?hl=en)). So you may, potentially, be able to get this to work by manually adding the certificates to every client (but I suspect that's not a viable solution).

Unfortunately, current browsers (as far as I am aware) do not provide any way for Javascript code to specify a client certificate to be used when establishing a connection. This means there is no way for this library to do so. In the same way you can't specify a CA to use (the browser also controls that).

Note that this is a duplicate of #421 and #741

**Comment by ysfscream** [comment]
@MattBrittan Thank you for your answer! it solved my doubts and I will close this issue

**Comment by afgarcia86** [comment]
Is there no way to send the certs to the backend so that the backend can still do 1 Way TLS Auth?

I would like for the server to reject my connection if I don't send a valid self signed certificate. I found a potential work around by adding a Trusted CA, Cert & Key along with an extra Self Signed Root CA. So that my server can decide if it trusts me or not. It seems to work as expected with the MQTTX tool but if I enable `TLS Verify Client` it rejects the connection and I am pretty sure its because the library is not including the certs I am giving it in the options.

**Comment by MattBrittan** [comment]
@afgarcia86 its kind of possible if you manually load the certs (how you do this would depend on the browser/os). However, its not something javascript (run by the browser) has any control over.

**Comment by afgarcia86** [comment]
@MattBrittan do you have any context you can share that might send me down the right direction? It seems like there is a hack here that might work: https://github.com/mqttjs/MQTT.js/issues/741#issuecomment-351900862

**Comment by MattBrittan** [comment]
@afgarcia86 sorry - it's not something I've tried for some time (realistically this might work for a developer account, but the process is too complicated for most end users). It looks like that "hack" is just making an `https` request prior to making the `wss` request (this may be needed if the browser does not prompt you to load a cert when making the `wss` request`). See something [like this](https://www.ssl.com/how-to/configuring-client-authentication-certificates-in-web-browsers/) for instructions on loading the certs client side. Note that I don't think 1-Way auth is possible (if using TLS the browser will always verify the server cert).
A better approach might be to pass a JWT (or similar) and have the server verify that (how you would do that would vary from broker to broker; with Mosquitto [`mosquitto-go-auth`](https://github.com/iegomez/mosquitto-go-auth?tab=readme-ov-file#jwt) would support this.
