### ISSUE TITLE
use it in webapp and when the webapp not deploy @ 80 or 443 port ,the request url is not correct

### ISSUE THREAD

**Issue by shanjunmei** [mqttjs/MQTT.js#1517]
even i already set correct protocol +host +port ,mqttjs still add currrent web port to the request path
my web app run on 83 port ,websocket run on 9001, final request path look like this 
![image](https://user-images.githubusercontent.com/9591051/182539437-a66a1afb-49a2-4a46-8679-ff7213ade22b.png)

**Comment by doc-han** [comment]
what does your mqtt connect options look like?

**Comment by shanjunmei** [comment]
> 
var opst={"username":"","password":""};
mqtt.connect('ws://host:port' ,opts);

**Comment by doc-han** [comment]
Use this format
```js
mqtt.connect({
	host: "host-here",
	hostname: "host-here",
	protocol: "ws",
	port: 9001,
	username: "username-here",
	password: "password-here",
	clientId: "unique-client-id-here"
})
```

**Comment by shanjunmei** [comment]
> 
![image](https://user-images.githubusercontent.com/9591051/182548438-c811ff00-0c39-49ef-86e8-fd58a9033d5f.png)
According to the way you just provided, this error will occur，still miss some parameter?
![image](https://user-images.githubusercontent.com/9591051/182548304-ddad2563-592e-46ca-985d-22d3c2321cc0.png)

**Comment by shanjunmei** [comment]
> 

Sorry, because the protocol contains colons and slashes, it's ok now

**Comment by doc-han** [comment]
Welcome
