### ISSUE TITLE
Mqtt problem with vite and create react app

### ISSUE THREAD

**Issue by majeeddl** [mqttjs/MQTT.js#1523]
when I create react app with vite , I see this error :  " global is not defined "
when I create app with create react app I see this error : " Buffer is not defined"

After changing 
```javascript 
 import mqtt from 'mqtt' 
``` 
to 
```javascript 
 import mqtt from 'mqtt/dist/mqtt'
``` 
 , I see the error of can not connect to server in console log in browser as following : 

![2022-08-11_23-00-40](https://user-images.githubusercontent.com/472520/184229441-322715d0-16c0-40a4-b441-dd39ba0ae9b7.png)

**Comment by arielquintero** [comment]
amigo pudiste resolverlo, yo tengo el mismo problema

**Comment by robertsLando** [comment]
Could be fixed by https://github.com/mqttjs/MQTT.js/pull/1571

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
