### ISSUE TITLE
TopicAliasMaximum option is referenced incorrectly

### ISSUE THREAD

**Issue by ogis-yamazaki** [mqttjs/MQTT.js#1524]
TopicAliasMaximum should be set in options.properties.

But , the following directly references options. ( ``if (options.topicAliasMaximum > 0) {``)
https://github.com/mqttjs/MQTT.js/blob/aa49aaf9856fe9f433005e850b490a96505add19/lib/client.js#L322-L327

So, even if I set TopicAliasMaximum to the correct position, this does not seem to be valid.

**Comment by redboltz** [comment]
`topicAliasMaximum` is MqttClient's option.
If it is set at the constructor. See README.md

> - topicAliasMaximum: representing the Topic Alias Maximum value indicates the highest value that the Client will accept as a Topic Alias sent by the Server number,

If the `topicAliasMaximum` is set by option, then it is stored as `topicAliasRecv`.

When sending CONNECT packet, the `topicAliasMaximum` property is set using  `topicAliasRecv`.
https://github.com/mqttjs/MQTT.js/blob/aa49aaf9856fe9f433005e850b490a96505add19/lib/client.js#L485-L492

Users don't need to set and shouldn't set TopicAliasMaximum property on CONNECT packet.

**Comment by redboltz** [comment]
> `topicAliasMaximum` is MqttClient's option. If it is set at the constructor. See README.md
> 
> > * topicAliasMaximum: representing the Topic Alias Maximum value indicates the highest value that the Client will accept as a Topic Alias sent by the Server number,
> 
> If the `topicAliasMaximum` is set by option, then it is stored as `topicAliasRecv`.
> 
> When sending CONNECT packet, the `topicAliasMaximum` property is set using `topicAliasRecv`.
> 
> https://github.com/mqttjs/MQTT.js/blob/aa49aaf9856fe9f433005e850b490a96505add19/lib/client.js#L485-L492
> 
> Users don't need to set and shouldn't set TopicAliasMaximum property on CONNECT packet.

Sorry, it's something wrong. I will check the implementation.

**Comment by redboltz** [comment]
I noticed that I forgot updating the document when I introduced TopicAlias functionality. See #1526.

**Comment by robertsLando** [comment]
Fixed by #1519 and #1612
