### ISSUE TITLE
Typescript type is missing (autoUseTopicAlias and autoAssignTopicAlias)

### ISSUE THREAD

**Issue by ogis-yamazaki** [mqttjs/MQTT.js#1525]
The following is a type definition file

https://github.com/mqttjs/MQTT.js/blob/aa49aaf9856fe9f433005e850b490a96505add19/types/lib/client-options.d.ts

The following options seem to be missing.
```ts
        autoUseTopicAlias?: boolean
        autoAssignTopicAlias?: boolean
```

**Comment by robertsLando** [comment]
Fixed by #1519 and #1612
