### ISSUE TITLE
client.end() throwing error vernqmq broker

### ISSUE THREAD

**Issue by syedzahidulla** [mqttjs/MQTT.js#1530]
Iam using verneMQ Broket and its throwign me error on client.end()

error Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

**Comment by leppaott** [comment]
Same here. We're trying to disconnect by calling client.end() without logging the error anymore.
Passing force=true, does remove this.

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists
