### ISSUE TITLE
mqtt 使用babel-polyfill编译报错 

### ISSUE THREAD

**Issue by wwdDongDong** [mqttjs/MQTT.js#1531]
![image](https://user-images.githubusercontent.com/30905492/188412951-be743c27-ae27-4277-be48-a2c47cffd35e.png)
报错的是3297行，报错问题是 
![image](https://user-images.githubusercontent.com/30905492/188413092-a5564a7e-e721-4629-b78e-b2d1d28feda4.png)
将3314行的const修改为var就不报错了，希望可以处理一下
另外虽然不报错了，但是依然会报警告 **"export 'connect' (imported as 'mqtt') was not found in 'mqtt/dist/mqtt.js'**
![image](https://user-images.githubusercontent.com/30905492/188415868-5362de84-745b-4f65-aaa2-3bf298644675.png)
<code>import * as mqtt from "mqtt/dist/mqtt.js";
var MQTT = /** @class */ (function() {
  function MQTT(url, options, topics, cb) {
    this.url = url;
    this.options = options;
    this.topics = topics;
    this.cb = cb;
    this.fns = {};
    this.init();
  }
  MQTT.prototype.init = function() {
    this.client = mqtt.connect(this.url, this.options);
    this.client.on("message", this.cb);
    const _this = this;
    this.client.on("connect", function() {
      console.log("MQTT连接成功" + new Date().toLocaleString());
      if (_this.topics) {
        _this.client.subscribe(_this.topics.split(","), { qos: 2 });
      }
    });
    this.client.on("reconnect", (error) => {
      console.log("MQTT正在重新链接" + error + new Date().toLocaleString());
    });
    this.client.on("error", (error) => {
      console.log("MQTT正在重新链接" + error + new Date().toLocaleString());
    });
  };
  MQTT.prototype.publish = function(topic, message) {
    this.client.publish(topic, message);
  };
  MQTT.prototype.close = function() {
    this.client.end();
  };
  return MQTT;
}());
export { MQTT };
</code>

**Comment by wwdDongDong** [comment]
![Uploading image.png…]()
具体位置如下

**Comment by wwdDongDong** [comment]
编译的具体位置如下
![image](https://user-images.githubusercontent.com/30905492/188419103-aa212432-4749-4deb-a3bd-91295fe024a1.png)

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
