### ISSUE TITLE
[Bug] SubAck does not return reasonCode，but the subscription is successful

### ISSUE THREAD

**Issue by ChunMengLu** [mqttjs/MQTT.js#1532]
mqttx sub but mqtt broker sub ack grantedQosList is empty，mqtt.js sub successful。

mqtt.js sub ack logic seems to be buggy：https://github.com/mqttjs/MQTT.js/blob/main/lib/client.js#L1641

**Comment by robertsLando** [comment]
Duplicate of #1512
