### ISSUE TITLE
publish() fails when given an ArrayBuffer

### ISSUE THREAD

**Issue by transplier** [mqttjs/MQTT.js#1540]
I am connected to a Mosquitto instance via websocket in Firefox. This line works fine and immediately transmits a `hi` to the broker:
```js
mqttClient.publish('example/topic', 'hi')
```
However, when I try to send binary data, it silently drops the message. The connection seems to go dead for an indeterminate amount of time:
```js
const ab = new ArrayBuffer(1);
ab[0] = 36; // Easy to see in MQTT explorer, it's just an ASCII dollar sign.
mqttClient.publish('example/topic', ab) 
```

Sometimes, after a while, I do get a message in the broker - but it appears to be garbage. The length seems correct though the content is not. For example, I've received messages like `0(stud` for some 8-byte messages I've been trying to send, which is the correct message length but definitely not the correct content.

Even more rarely, after several seconds, I get the following uncaught exception:
```Uncaught TypeError: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object```

I'm running the latest minified source from the unpkg linked in the README.

**Comment by RafaelSchridi** [comment]
I also ran into this a while back and subscribed here for changes, I just ended up base64 encoding everything.

**Comment by FurqanAnwar** [comment]
@RafaelSchridi I've used JSON.stringify(new ArrayBuffer) and it worked fine for me.

**Comment by robertsLando** [comment]
Publish only accepts string | Buffer

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists
