### ISSUE TITLE
React Buffer error

### ISSUE THREAD

**Issue by ipewzner** [mqttjs/MQTT.js#1542]
1) If in React you get an error about the Buffer 
try to change the " import mqtt from 'mqtt' " to " import mqtt from 'mqtt/dist/mqtt' "
credit to: https://github.com/mqttjs/MQTT.js/issues/1020#issuecomment-565948999

2) In the example for React is missing some ')}'  4 lines from the bottom.

**Comment by MidnightRising** [comment]
Downgrade your `react-scripts` entry in `package.json` to `4.0.3`. Make the update, delete `package-lock.json` and then run `npm run install`

**Comment by Jiec-er** [comment]
> 1. If in React you get an error about the Buffer
>    try to change the " import mqtt from 'mqtt' " to " import mqtt from 'mqtt/dist/mqtt' "
>    credit to: [Unable to resolve module `url` from `node_modules/mqtt/lib/connect/index.js #1020 (comment)](https://github.com/mqttjs/MQTT.js/issues/1020#issuecomment-565948999)
> 2. In the example for React is missing some ')}'  4 lines from the bottom.

thank you for your help ! before your answer , i get  a white page  when i run my react application, no any error information😥
