### ISSUE TITLE
How to modify payload before republishing a payload when publishing is failed?

### ISSUE THREAD

**Issue by shahidul-brur** [mqttjs/MQTT.js#1554]
Suppose, I am publishing a payload to a mqtt topic. At that moment I am offline or the broker is down, so the publishing is failed. It will be published when I will come back online. 

I want to modify the payload before it is published when I am online. For example: I want to update the timestamp field before it is published, since the time when I tried to publish the payload and when it is actually being published after coming back to online is different. Is it possible? How can I do this?

**Comment by robertsLando** [comment]
You should manually access to outgoing store and edit it
