### ISSUE TITLE
ws is changed to wss

### ISSUE THREAD

**Issue by Vamoss** [mqttjs/MQTT.js#1556]
Hi,

When I have a URL starting with ```ws://``` the browser tries to connect using ```wss://```.
It happens with the latest version, but I notice it has been happening for a while.

No matter if I have the user and password in the URL or not.

Thank you!

**Comment by Vamoss** [comment]
Chrome is causing this issue:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests

I am closing the issue.

**Comment by akmaldira** [comment]
how you solve it?
