### ISSUE TITLE
Potential race condition leading to publish callback not being called for QoS 0

### ISSUE THREAD

**Issue by robinsummerhill** [mqttjs/MQTT.js#1561]
mqtt 4.3.7

We're experiencing infrequent incidents where it appears that the callback supplied to client.publish is not always called when QoS is set to zero.

First, am I right in assuming the callback should *always* be called for qos=0 - either with an error or null indicating success? The documentation would seem to indicate this but is not explicit:
> callback - function (err), fired when the QoS handling completes, or at the next tick if QoS 0. An error occurs if client is disconnecting.

We think that the issue occurs when an unexpected disconnect from the broker happens at exactly the right moment - just before a call to publish but before the disconnect has been picked up by the library.

Looking at the source code, checks are made for the connection state before attempting to publish at client.js#617:
```
 if (this._checkDisconnecting(callback)) {
    return this
  }
```

and client.js#617:
```
if (!this.connected) {
...
}
```

If these checks pass then the packet is written to client.stream and the callback is scheduled to be called on the next `drain` event. (client.js#180):
```
client.stream.once('drain', cb)
```

However, if the disconnect happens after the checks but before actually sending the packet there is a potential race condition where the packet is written but `drain` will never be fired and the callback is not called.

Can you confirm if this is a bug or we are making assumptions about the callback processing that are not valid for qos=0?

**Comment by robertsLando** [comment]
Please consider opening a PR to fix this issue

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
