### ISSUE TITLE
Does MQTT.js work in mobile browsers?

### ISSUE THREAD

**Issue by Duckle29** [mqttjs/MQTT.js#1566]
Hi there.

I have written a small PWA that lets me control some devices over MQTT.
It works great on desktop, both in the browser and as an installed PWA, however when I try it on mobile it doesn't work.

I have tried it on: 

 - Samsung S22 with chrome 108.0.5359.128
 - Old Ipad safari running 12.5.5

In both cases it fails to connect, I see no connection attempts on my broker, and it just continuously cycles the `close` and `reconnect` event

So is this a known limitation of this library?

There seems to be a related but never answered issue here https://github.com/mqttjs/MQTT.js/issues/1220

**Comment by Duckle29** [comment]
You can see my PWA here, it's fairly simple https://github.com/Duckle29/wifir_pwa/blob/main/js/main.js#L134

**Comment by robertsLando** [comment]
It works
