### ISSUE TITLE
The message received by the JS client is out of order after disconnection

### ISSUE THREAD

**Issue by cnvvtn** [mqttjs/MQTT.js#1568]
After repeated testing, 4.3.7 has repeated the bug in both cdn and npm, while 4.1.0 introduced into cdn does not have this phenomenon

#### Repeat the steps for this problem
1. Client A goes offline
2. Client B sends A message to A, such as aa, bb, cc, and dd
3. The client receives the dd, cc, bb, aa message after reconnecting to the client
4. In normal cases, the message that the client reconnects should be aa, bb, cc, dd

That is just the opposite, I think it is the js logic problem, does not conform to the official document said message queue reconnection principle of first in, first out, resulting in the last message is the first to be received

Problem log: Obviously, the operation log has caused the problem, such as in the red box, the last message sent is the first message received back, so I don't think it is the user code logic.
![image](https://user-images.githubusercontent.com/103573590/211765557-b884ad04-cb64-489e-9ced-0034d84993b3.png)

Normal log:
Using the link is pointing to js code: https://cdn.bootcdn.net/ajax/libs/mqtt/4.1.0/mqtt.min.js
The logging should look like this:
![image](https://user-images.githubusercontent.com/103573590/211766178-c7572b6e-0796-44c0-85eb-60b7d209907f.png)

Hope it gets noticed and fixed in the new version! Versions for other languages have not yet been tried.

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
