### ISSUE TITLE
`IS_BROWSER` fails when application is not built/served by Webpack

### ISSUE THREAD

**Issue by fabioimpe** [mqttjs/MQTT.js#1570]
Hi,
I'm facing an issue where in a browser environment MQTT library still try to use `ws` instead of the browser native `WebSocket` for the web socket connection.
After digging in the codebase I found out that the following code to understand if the code is running on `node` or in a browser is NOT taking care of any bundler other than Webpack (for instance I'm on Parcel 2 and is not working):
https://github.com/mqttjs/MQTT.js/blob/b3ce3da84147c86eb176759f53fa929e96de7969/lib/connect/ws.js#L18

In addition to this I don't understand the usage of `process.title` at all, I investigated a bit about this but I wasn't able to find any meaningful documentation or hint of its usage.

I think is worth having a safer way to check whether the code is running on the browser or not.

**Comment by fabioimpe** [comment]
Maybe related issues:
https://github.com/mqttjs/MQTT.js/issues/1233
https://github.com/mqttjs/MQTT.js/issues/1412
https://github.com/mqttjs/MQTT.js/issues/1523
https://github.com/mqttjs/MQTT.js/issues/1441

**Comment by robertsLando** [comment]
Fixed by #1571
