### ISSUE TITLE
How to sent data only when there are changes to the state of the device with mqtt?

### ISSUE THREAD

**Issue by MarwenBenTalebAli** [mqttjs/MQTT.js#1575]
Can I publish mqtt data only when data values change?

I can check every second the state of a device on or off but it doesn't make sense to send the same message every second.

```
const client = mqtt.connect(connectUrl, options);
client.on('connect', () => {
   setInterval(() => {
     const deviceState = getDeviceState(0, 1);
     client.publish('state', deviceState);
   }, 1000);
});
```

**Comment by eye-c** [comment]
that is exactly what I did by memoizing the state and only sending data when there is an inflection. It is great for sending alarms. You should consider using a state library

**Comment by robertsLando** [comment]
Not an mqttjs related question. This is more like a javascript question. Anyway you can use a Proxy: https://dev.to/dailydevtips1/detect-object-changes-with-javascript-proxy-1o5g
