### ISSUE TITLE
When connect() is called, it uses localhost and not the host specified in the options object

### ISSUE THREAD

**Issue by eye-c** [mqttjs/MQTT.js#1579]
Hi, I'm running MQTT.js on my dev machine in a react component and have been connecting to my local mosquitto broker without a problem using **{ host: localhost }**. When I try to connect to my HiveMQ broker I get this error:

**ws.js?725c:109 WebSocket connection to 'ws://localhost:8884/' failed:** 

these are my options passed in to the connect function

```

mqttOptions: {
    "host": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.s1.eu.hivemq.cloud",
    "port": "8884",
    "clientId": "icodegfx",
    "username": "icodegfx",
    "password": "password",
    "protocol": "MQTT"
}

const mqttConnect = (mqttOptions) => {
	console.log(`mqttOptions: ${JSON.stringify(mqttOptions, null, 4)}`)
	setConnectStatus('Connecting')
	setClient(mqtt.connect(mqttOptions))
}


```

I don't understand why the client tries to connect to **ws://localhost**

**Comment by d-00001101** [comment]
When stating the host as the first argument, the connect function prepends ws://localhost to the host name
![MQTTJS ERROR](https://user-images.githubusercontent.com/113072875/219222033-e1fae1c3-9172-458f-9ca9-87a8db708e19.jpg)

**Comment by eye-c** [comment]
When adding the host explicitly as the first argument it prepends **ws//localhost** to the host url
![MQTTJS ERROR](https://user-images.githubusercontent.com/55814315/219222519-cce96d07-1b96-40c9-a770-19eb0ca959d1.jpg)

**Comment by eye-c** [comment]
the options object looks like this in the console.
**mqttOptions: {
    "host": "58xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0c.s1.eu.hivemq.cloud",
    "port": "8883",
    "clientId": "icode-id",
    "username": "icode",
    "password": "password",
    "protocol": "MQTT"
}**

**Comment by Noobmaster69-bug** [comment]
I think you using wrong protocol value, it's should be "wss" or "ws".

**Comment by lufke** [comment]
Try using 127.0.0.1 I triednti connect yo localhost and just problems, but with 127.0.0.1 no problem

**Comment by Adotac** [comment]
same problem here with hivemq, mqtt client just ignores my options which I thought it automatically creates a localhost and I can't see the messages on hivemq webclient.

**Comment by doc-han** [comment]
You should define both `host` and `hostname` with the same host server URL.

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
