### ISSUE TITLE
Create browserMqtt.js on stable release

### ISSUE THREAD

**Issue by gavalierm** [mqttjs/MQTT.js#1583]
When you push out the stable release, you can add browserMqtt.js to the release. So users who wants to use this libray on browser do not have go do browserify stuff.

Make sense?

**Comment by nosovk** [comment]
Just use ESM ready implementation like https://github.com/shanewholloway/js-u8-mqtt if you want to connect to MQTT broker from WEB,

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues

**Comment by nosovk** [comment]
https://bundlephobia.com/package/mqtt@beta seems two times larger than https://bundlephobia.com/package/mqtt@4 :(

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
