### ISSUE TITLE
disconnect event did not being triggered while network being closed

### ISSUE THREAD

**Issue by laxian** [mqttjs/MQTT.js#1584]
## As the title says

this is my test code:

```JavaScript
const mqtt = require('mqtt')

const host = 'broker.emqx.io'
const port = '1883'
const clientId = `S1RRR2232D0003_1`

const connectUrl = `mqtt://${host}:${port}`
const topic = "test-js"

const client = mqtt.connect(connectUrl, {
    clientId,
    clean: true,
    connectTimeout: 5 * 1000,
    reconnectPeriod: 5 * 1000,
    keepalive: 10,
})

client.on('connect', function () {
    client.publish(topic, 'Heartbeat Messages', { qos: 0, retain: false }, function (error) {
        if (error) {
            console.error(error)
        }
        else {
            console.log('Heartbeat Messages Sent.')
        }
    })
})

client.on('disconnect', function (error) {
    if (error) {
        console.error(error)
    }
})

client.on('offline', function (error) {
        console.error(error)
})

```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13779717/224622709-2fea66c1-0b47-47f6-bb4a-7ba00e98b973.png">

Why disconnect and offline events not being triggered?
Thank you!

**Comment by laxian** [comment]
on Ubuntu or Mac
In case I start the test process on WIFI named `ap1`, 
I won't receive `offline` event if I switch WIFI to `ap2` or turn off WIFI, until I reconnect to `ap1`

For comparison, if you use Python paho-mqtt library to switch or close WIFI, you can receive on_ disconnect,
In addition, switching WIFI can correctly reconnect successfully

**Comment by robertsLando** [comment]
@laxian are you able to reproduce the issue with latest version?

**Comment by jzombie** [comment]
> @laxian are you able to reproduce the issue with latest version?

It's been happening to me.  I haven't been getting disconnect events when the socket goes offline in the browser.

**Comment by robertsLando** [comment]
I'm quite sure this is fixed now, be sure to setup the options correctly
