### ISSUE TITLE
Mosquitto endless loop of connected / disconnected after mqtt_reconnect() because of the same client name

### ISSUE THREAD

**Issue by CptHolzschnauz** [mqttjs/MQTT.js#1585]
If you just call the reconnect function without a new client name, it ends in a endless loop of connection/disconnection at least with the Mosquitto broker.

The solution is to provide a new client name, something like

function mqtt_reconnect(err) {
    console.log("Reconnect MQTT");
	// Generate a new user name to prevent the broker from dicconect us directly because the name is already logged in
	var options = {
	clientId: 'MyMQTT_' + Math.random().toString(16).substr(2, 8), 
	port: 1883,
	//username: 'mqtt_user',
	//password: 'mqtt_password',	
	keepalive : 60
};	
    if (err) {console.log(err);}
	client  = mqtt.connect(Broker_URL, options);
};

Maybe that's something for the documentation or a error handler in the lib. The error now is thrown by the tcp socket lib.

**Comment by robertsLando** [comment]
This is not an issue with mqttjs, this is how MQTT protocol works. When a client connects if there is another client with same id already connected that will be force closed in favor of the new one. This must be handled on client side by creating unique clientIds
