### ISSUE TITLE
[Help wanted] - unit test with angular 15

### ISSUE THREAD

**Issue by yvesguilherme** [mqttjs/MQTT.js#1586]
For some weeks I tried to write some tests with jasmine, but I can't get them to get 100% coverage... especially on these lines as per the print screen...

![image](https://user-images.githubusercontent.com/22429592/224726138-049c4a09-4ef1-46da-ab3f-614f4021ffd4.png)

But also always returning the following error: 

![image](https://user-images.githubusercontent.com/22429592/224726385-b60ee2b5-b89e-4ed8-b205-19acc3ab851e.png)

![image](https://user-images.githubusercontent.com/22429592/224726474-17689b3c-3732-4cc6-8136-19e9ddc8e260.png)

Has anyone experienced any of these problems? And of course, if you can help me, I will be grateful... 

hugs...! :)

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
