### ISSUE TITLE
Vite / MQTT : [Quasar] boot error: ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by Asthonishia** [mqttjs/MQTT.js#1587]
Hi,

I'm using Quasar framework V2.
I did a migration from vue2 to 3, from webpack to vite.

Since i use Vite, it is imposible for me to have a functional mqtt client :(.

I always have this error :
`client-entry.js:148 [Quasar] boot error: ReferenceError: Buffer is not defined`
    
`at node_modules/mqtt-packet/constants.js (mqtt.js?v=6ee0c284:11981:38)
    at __require (chunk-OL3AADLO.js?v=6ee0c284:9:50)
    at node_modules/mqtt-packet/parser.js (mqtt.js?v=6ee0c284:12113:21)
    at __require (chunk-OL3AADLO.js?v=6ee0c284:9:50)
    at node_modules/mqtt-packet/mqtt.js (mqtt.js?v=6ee0c284:13732:22)
    at __require (chunk-OL3AADLO.js?v=6ee0c284:9:50)
    at node_modules/mqtt/lib/client.js (mqtt.js?v=6ee0c284:14078:22)
    at __require (chunk-OL3AADLO.js?v=6ee0c284:9:50)
    at node_modules/mqtt/lib/connect/index.js (mqtt.js?v=6ee0c284:16466:22)
    at __require (chunk-OL3AADLO.js?v=6ee0c284:9:50)`

I tried to install buffer/process but i don't really know how i must configure it after.

Any idea ?

**Comment by dokodream** [comment]
Maybe you could try this
```ts
import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'
import {NodeGlobalsPolyfillPlugin} from '@esbuild-plugins/node-globals-polyfill'
import {NodeModulesPolyfillPlugin} from "@esbuild-plugins/node-modules-polyfill";
import path from "path";


// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        vue(),
    ],
    optimizeDeps: {
        esbuildOptions: {
            // Node.js global to browser globalThis
            define: {
                global: 'globalThis'
            },
            // Enable esbuild polyfill plugins
            plugins: [
                NodeGlobalsPolyfillPlugin({
                    process: true,
                    buffer: true
                }),
                NodeModulesPolyfillPlugin()
            ]
        }
    },
    resolve: {
        alias: {
            "@": path.resolve(__dirname, "src")
        }
    }
})

```

**Comment by nosovk** [comment]
We use sveltekit, that also depends on vite. And there were lots of problems with shims and size, that's why we finally moved to https://github.com/shanewholloway/js-u8-mqtt
It does the same, but its size is much less end it's esm friendly.

**Comment by Asthonishia** [comment]
I did a rollback to webpack finally. thank you for the anwsers and the lib. I put it on my fav for future projects :)

**Comment by drogerie21** [comment]
> Maybe you could try this
> 
> ```ts
> import {defineConfig} from 'vite'
> import vue from '@vitejs/plugin-vue'
> import {NodeGlobalsPolyfillPlugin} from '@esbuild-plugins/node-globals-polyfill'
> import {NodeModulesPolyfillPlugin} from "@esbuild-plugins/node-modules-polyfill";
> import path from "path";
> 
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>     plugins: [
>         vue(),
>     ],
>     optimizeDeps: {
>         esbuildOptions: {
>             // Node.js global to browser globalThis
>             define: {
>                 global: 'globalThis'
>             },
>             // Enable esbuild polyfill plugins
>             plugins: [
>                 NodeGlobalsPolyfillPlugin({
>                     process: true,
>                     buffer: true
>                 }),
>                 NodeModulesPolyfillPlugin()
>             ]
>         }
>     },
>     resolve: {
>         alias: {
>             "@": path.resolve(__dirname, "src")
>         }
>     }
> })
> ```

Hi, have the same problem, using quasar and trying to implement a mqtt client.
Can you give some more context to your solution. Where should i place this code-snippet. I´m not able to find the vite config ...
Thanks!

**Comment by nosovk** [comment]
> We use sveltekit, that also depends on vite. And there were lots of problems with shims and size, that's why we finally moved to https://github.com/shanewholloway/js-u8-mqtt It does the same, but its size is much less end it's esm friendly.

solution was to use esm first implementation that does not depend on shims

**Comment by annlumia** [comment]
Try to configure resolve.alias on `quasar.config.js`


```js

...
  extendViteConf(viteConf) {
        viteConf.resolve.alias = {
          ...viteConf.resolve.alias,
          mqtt: 'mqtt/dist/mqtt.js',
        };
    },
...
```

**Comment by robertsLando** [comment]
I have fixed [Browser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
