### ISSUE TITLE
Moquitto broker is active but I keep getting Error: getaddrinfo ENOTFOUND #1279 #1590

### ISSUE THREAD

**Issue by schaefer01** [mqttjs/MQTT.js#1592]
argh, updated but still no joy

% node -v
v19.8.1

% node /usr/local/bin//mqtt sub --protocol ws -t 'hello' -h 'test.mosquitto.org' -v$ mqtt pub -t 'hello' -h
Error: getaddrinfo ENOTFOUND test.mosquitto.org,
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'test.mosquitto.org,'
}

% ping test.mosquitto.org
PING test.mosquitto.org (91.121.93.94): 56 data bytes
64 bytes from 91.121.93.94: icmp_seq=0 ttl=48 time=78.528 ms

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists

**Comment by schaefer01** [comment]
After the issue report, I switched to a different julia package. https://github.com/denglerchr/Mosquitto.jl
