### ISSUE TITLE
Upgrade the version of minimist to solve the security problem

### ISSUE THREAD

**Issue by z0215** [mqttjs/MQTT.js#1593]
minimist has [security issues](https://github.com/minimistjs/minimist#security) before 1.2.6, please upgrade to the latest version to solve the security issues

**Comment by robertsLando** [comment]
PR?

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
