### ISSUE TITLE
How can I send command to connected IoT device?

### ISSUE THREAD

**Issue by jAddict7** [mqttjs/MQTT.js#1598]
Hi, am new to MQTT. Now I am able to receive the data from IoT device but unable to send a command back to the device as like TCP write. Please do guide me on whats the feature in this library to use for sending a command to the IoT device?

**Comment by jsiegenthaler** [comment]
Publish sends a message to a topic

**Comment by jAddict7** [comment]
Hi @jsiegenthaler, I am trying to send like this

`client.subscribe([topic3], () => {
	console.log(`Subscribe to topic '${topic3}'`)

	client.publish(topic3, '<command>', { qos: 0, retain: false }, (error) => {
		if(error){
			console.error(error)
		}
	})
})`

But I am receiving the message in Server and not sending back to IoT device. Whether we need to subscribe to IoT device in any ways and try publishing the message??

**Comment by ldeffenb** [comment]
The IoT device needs to subscribe to whatever command topics it is expected to support.
