### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by liusong1111** [mqttjs/MQTT.js#1604]
Yes I know there is #1294 and #1412 , and I **did** solve my problem following:

https://github.com/mqttjs/MQTT.js/issues/1412#issuecomment-1193363330

But, It's so hard to **import into** browser correctly, either with vallilia js or frameworks like vue3/react, so, please take it serious.

Let's say, I follow vue official first step `npm init vue@latest`, and `npm i mqtt -S`, and, copy-paste mqtt homepage's demo code, after `npm run dev`, open browser, **Buffer is not defined** is welcoming me :(

**Comment by liusong1111** [comment]
+ #1596

**Comment by robertsLando** [comment]
I have fixed [Bropwser](https://github.com/mqttjs/MQTT.js#browser) docs by adding webpack and vite setup. Check them out
