### ISSUE TITLE
MQTT over WebSocket, QoS 0 messages may not get sent before disconnection

### ISSUE THREAD

**Issue by ysfscream** [mqttjs/MQTT.js#1607]
**Describe the bug**
When using MQTT over WebSocket with QoS set to 0, I have encountered a situation where the publish callback is triggered before the message has been successfully sent. This causes the message not to get sent before the connection is ended. This issue occurs intermittently only with WebSocket connections, not with MQTT over TCP connections.

**To Reproduce**
Here is a simple code snippet that reproduces the issue:

```javascript
const client = // initialize MQTT client with WebSocket
client.publish(topic, message, { qos: 0 }, (err, packet) => {
  if (err) {
    console.error('Publish failed:', err)
  } else {
    console.log('Publish succeeded:', packet)
    client.end()
  }
})
```

In the case of a WebSocket connection and QoS 0, the 'Publish succeeded' log may print before the message is actually sent.

**Expected behavior**
The publish callback should not be called until the message is successfully sent, even when using WebSocket and QoS 0. 

**Environment (please complete the following information):**
- OS: macOS
- Node.js version: v16.14.2
- MQTT.js version: 4.3.7

**Additional context**
The issue only occurs intermittently and with WebSocket connections, not other MQTT/TCP of connections.

**Comment by robertsLando** [comment]
Could you submit a PR to fix this issue?

**Comment by robertsLando** [comment]
MQTT [5.0.0 BETA](https://www.npmjs.com/package/mqtt/v/beta) is now available! Try it out and give us [feedback](https://github.com/mqttjs/MQTT.js/issues/1639): `npm i mqtt@beta`. It may fix your issues
