### ISSUE TITLE
native promise/async support

### ISSUE THREAD

**Issue by sibelius** [mqttjs/MQTT.js#1642]
What about adding native support to promise/async?

instead of adding another package https://github.com/mqttjs/async-mqtt

**Comment by robertsLando** [comment]
This is already in my TODO list

**Comment by robertsLando** [comment]
@vishnureddy17 @BertKleewein What's the best approach for this in your opinion? Should I create an alias method foreach publish method like `publishAsync` `subscribeAsync` etc... or should I add an override to actual functions? How would you expect the override to work? 

I was tring this way in `client.publish`: 

```ts
let toReturn: MqttClient | Promise<void> = this

if (typeof callback === 'function') {
	const deferred = new Deferred<void>()
	toReturn = deferred.promise
	callback = deferred.callback
}
```

where `Deferred` is an util class like:

```ts
export class Deferred<T> {
	private readonly _promise: Promise<T>

	private _resolve: (value?: T | PromiseLike<T>) => void

	private _reject: (reason?: any) => void

	constructor() {
		this._promise = new Promise<T>((resolve, reject) => {
			this._resolve = resolve
			this._reject = reject
		})
	}

	get promise(): Promise<T> {
		return this._promise
	}

	get callback(): GenericCallback<T> {
		return (error?: Error, result?: T): void => {
			if (error) {
				this.reject(error)
			} else {
				this.resolve(result)
			}
		}
	}

	resolve = (value?: T | PromiseLike<T>): void => {
		this._resolve(value)
	}

	reject = (reason?: any): void => {
		this._reject(reason)
	}
}
```

First problem with this is that if someone doesn't provide a function the method will always return a promise and that could be not expected, in fact many tests fail with that change. IMO the cleaner approach (at code side) is to create an alias method

**Comment by vishnureddy17** [comment]
> IMO the cleaner approach (at code side) is to create an alias method

I agree.
