### ISSUE TITLE
mqtt 5.0.2 webpack 5 and chrome 53 and lower

### ISSUE THREAD

**Issue by Aliendreamer** [mqttjs/MQTT.js#1663]
I don't think is an issue, of the library, but if you try to use mqtt 5.0.2 with browsers from like 2016 it throws exception in one of the dependencies file.
4.3.7 don't have this issue, we were trying to update our version when we noticed the problem:
mqtt/node_modules/readable-stream/lib/ours/errors.js:314 line -> this is the offending file and line.
Sorry, I thought I made a screenshot but seems I forgot.
I think that probably 99% of the use cases will never hit this issue, but as we are working on older devices like lg from 2018 which has chrome 53, or 2017 which has chrome 38 we caught it.
So I am just opening it as I saw you are gathering feedback for the new version, if someone else hit it, and I notice there is a discussion for removing this library/polyfill at all if I am not mistaken.

**Comment by robertsLando** [comment]
I suggest to upgrade to newer browser versions. Thanks for the feedback anyway. Provide a screenshot or a console log of the error just for reference when possible, thanks
