### ISSUE TITLE
How can I know the connection is kicked by the same clientId ?

### ISSUE THREAD

**Issue by wenlongwanggithub** [mqttjs/MQTT.js#1668]
For example,
I have device A and B.
A connected with server using clientId='111',
and later B connects using the same clientId,
I wanna know A is kicked , so I can show a dialog in app telling user: you're kicked by another device.

**Comment by robertsLando** [comment]
There is no way to know that. Specs only say that the client connection should be closed by the broker as you can see here in aedes: https://github.com/moscajs/aedes/blob/main/aedes.js#L170.
