### ISSUE TITLE
5.0.3 release broken for react native, downgrade to 5.0.2

### ISSUE THREAD

**Issue by grizmio** [mqttjs/MQTT.js#1672]
For those using version 5.0.3 in react native and getting
"Error: ws does not work in the browser. Browser clients must use the native WebSocket object"
just downgrade to 5.0.2 and it will work.
```npm i --save mqtt@5.0.2```

**Comment by robertsLando** [comment]
@grizmio What's the value of `process.title` in react native? I have a feel this is due to this commit: https://github.com/mqttjs/MQTT.js/commit/183b35aa3ed98fbbcbea6805994ef7c3cc8ee616

I can revert part of that to keep the react native compatibility

**Comment by stephanbruny** [comment]
Couldn't the mode (browser or node process) be set by the user?
This way we could set the mode explicitly instead of implicitly by trying to figure out the current process platform

**Comment by robertsLando** [comment]
We could think about adding an env var for that

**Comment by robertsLando** [comment]
@stephanbruny news on this?

**Comment by tanoc** [comment]
I think there is no `title` in `process` in react-native, so `undefined`

**Comment by tanoc** [comment]
Stackoverflow says this: `typeof navigator !== 'undefined' && navigator.product === 'ReactNative'`

**Comment by robertsLando** [comment]
Should react native then use the browser or non browser version?

**Comment by robertsLando** [comment]
@tanoc @grizmio @stephanbruny  I suggest to use:

```ts
import * as mqtt from 'mqtt/dist/mqtt'
```

Let me know id that works

**Comment by robertsLando** [comment]
FYI starting from 5.2.1 you can now import mqtt using:

`import mqtt from 'mqtt'`
