### ISSUE TITLE
MqttClient.reconnecting has no default value

### ISSUE THREAD

**Issue by davdeo** [mqttjs/MQTT.js#1674]
After calling `mqtt.connect(brokerUrl, options)` the returned MqttClient has no default value for reconnecting (it is undefined). 
Is this intentional? If yes why isn't the type something like: `reconnecting: boolean | undefined`?

**Comment by robertsLando** [comment]
could be a type issue, PR?

**Comment by davdeo** [comment]
I guess the problem was that the default value was not set in the constructor.

https://github.com/mqttjs/MQTT.js/pull/1678
