### ISSUE TITLE
MQTT 5 issue

### ISSUE THREAD

**Issue by jsb04** [mqttjs/MQTT.js#1675]
Hi,
I just tried to upgrade to v5 but found I get a runtime error:

process is not defined
ReferenceError: process is not defined
    at ./node_modules/mqtt/build/lib/client.js

I thought this might be because I had to use new MQTTClinet rather than .connect but when I could not find any examples of the constructor arguments:
    constructor(streamBuilder: StreamBuilder, options: IClientOptions);
is new MQTTClient required ?   could you update / provide an example please?
Also, previously I had to patch it as per:  # https://github.com/mqttjs/MQTT.js/issues/1412
eg.   modify webpack.config.js and package.json in node_modules/mqtt
I am no longer applying those changes; not certain if that has any bearing on the above issue but applying the same changes I previously was only results in more compilation errors.

Thanks
Josh

**Comment by jsb04** [comment]
I looked a bit further and I do think the issue probably stems from https://github.com/mqttjs/MQTT.js/issues/1412 - its just that the fix there no longer seems to work for 5.0.3 and it is also annoying that I've been patching this library to make it work.
1.   What would the fix for 5.0.3 be?
2. 2.  Is there a better way than manually patching Matt.js client?

**Comment by dvkam** [comment]
See here: https://github.com/mqttjs/MQTT.js/issues/1667

**Comment by robertsLando** [comment]
Dup of #1667
