### ISSUE TITLE
Two questions on createClient()

### ISSUE THREAD

**Issue by user1020** [mqttjs/MQTT.js#168]
Thanks for writing this interesting module.  I am trying to use it in my project.

The following example works, but I am not sure if I can put a callback function for mqtt.createClient(..)

```
var mqtt = require('mqtt')
client = mqtt.createClient(1883, 'localhost');
client.subscribe('presence');
client.publish('presence', 'Hello mqtt');
client.on('message', function (topic, message) {
  console.log(message);
});
client.end();
```

Another question is, when I change 

```
client = mqtt.createClient(1883, 'localhost');
```

to

```
client = mqtt.connect('mqtt://user:pass@localhost?clientId=123abc');
```

the example stopped working. The client doesn't open TCP connections according to my wireshark.   Wonder why.

Thanks in advance

**Comment by Huang9495** [comment]
Hi @mcollina @user1020  First,I use your code to my test .Unlucky, I have error after I test,I don't know why. Can you help me to resolve the issue. Second, I try a test by another code and takes place the same as error.Can you tell the reason of the issue.
## My operate environment :Ubuntu:14.04 ;Node.js:6.11;MQTT:2.9.1;Mosquitto:1.4.12;

**The error is mqtt.createClient is not a function .**

## The picture is here:
client = mqtt.createClient(1883, 'localhost');
              ^
TypeError: mqtt.createClient is not a function
    at Object.<anonymous> (/home/kris-allen/mqtt/mqtt/MQTT.js/test.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

## The second code is :
var mqtt = require('mqtt');

client = mqtt.createClient(1883, 'localhost');

client.subscribe('datasend')

client.on('datasend',function(client){
console.log('client connected');
});

client.on('message', function (topic, message) {
console.log(message.toString())
})

setInterval(function(){
client.publish('datasend','1');
console.log('datasend');
},2000);

client.end();

**Comment by mcollina** [comment]
`createClient`  has been deprecated long ago. Check the updated example in the README.

**Comment by Huang9495** [comment]
Hi ! @mcollina  Thanks for your help , I am reading README.But I remain have question is why this code is test in my workmate's computer is OK, the environment is similar to me.

**Comment by mcollina** [comment]
very likely he has an older version of MQTT.js

**Comment by Huang9495** [comment]
Hi @mcollina  I have complete my test through you method ,Thank you again your help!

**Comment by Huang9495** [comment]
Hi !@mcollina I have another issue , today ,I do a test that send the data from client to service and send the data from service to client at the same time. The issue is that nothing will occur of client where I send the data and set up to show. But it will occur after I shield the code of send the data from client to service. Can you tell me the reason .Whether the passageway of message only response the one-way rather than two-way?

**Comment by mcollina** [comment]
I did not understand. Can you please make an example?
Il giorno ven 21 lug 2017 alle 14:00 Kril Allen <notifications@github.com>
ha scritto:

**Comment by Huang9495** [comment]
Hi @mcollina 
First example :
## service code
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://localhost:1883')
client.on('connect', function () {
       client.subscribe('datasend1')
       console.log('OK')
client.on('message', function (topic, message) {
       console.log(message.toString())
setInterval(function(){
       client.publish('datasend2','**1**');
       console.log('ohnow');
},4000);
## client code
import paho.mqtt.client as mqtt
import json
import time
data_topic1 = "datasend1"
data_topic2 = "datasend2"
mqtt_srvr = '××××××××××'(I input my IP in fact)
mqtt_srvr_port = 1883
i=1
def mqtt_on_connect(client, userdata,flags, rc):
	print("**34134**")
client.def mqtt_on_message(client, userdata, msg):
        print (str(msg.payload))subscribe(data_topic2)
mqtt_client = mqtt.Client()
mqtt_client.on_connect = mqtt_on_connect
mqtt_client.on_message = mqtt_on_message
mqtt_client.connect(mqtt_srvr, mqtt_srvr_port, 60)
while i<=100:
	mqtt_client.publish(data_topic1,'546')
	i+=1
	print('gogogo')
	time.sleep(2)
mqtt_client.loop_forever()

in this example I can see the "OK"、"546"、"ohnow" on the terminal of service and the "gogogo" without "34134 "and "1" on the terminal of client;
But after I shield the code of send data from client to service, I can see  the "34134" and "1" ;
why?why?why?can you tell me the reason?
And I don't realize the mean of what you say that Il giorno ven 21 lug 2017 alle 14:00 Kril Allen <notifications@github.com>
ha scritto:
…
