### ISSUE TITLE
How to use mqttjs in nuxt 3

### ISSUE THREAD

**Issue by mrkimmy** [mqttjs/MQTT.js#1680]
I'm newbie NUXT. I tried to use mqttjs in nuxt 3.6.5

Below are steps for my testing

1. I created nuxt 3 from command
```npx nuxi init nuxt-mqtt-test```

2. Install mqttjs
```npm install mqtt```

3. Import mqtt to vue page
```
<script setup lang="ts">
      import * as mqtt from 'mqtt';
      if(process.client){
         const client = mqtt.connect("ws://broker.emqx.io:8083/mqtt");
        console.log(client);
      }
</script>
```

4. I got error ```global is not defined```
![image](https://github.com/mqttjs/MQTT.js/assets/14201370/a2d4b20a-5bbf-4cb6-908c-b8e46959bf89)

5. Then I found this issue: [https://github.com/emqx/MQTT-Client-Examples/issues/81](url) and follow Betty's answer.
    

5.1 Add ```shims-mqtt.d.ts```

![image](https://github.com/mqttjs/MQTT.js/assets/14201370/27f6503c-7421-4a9e-a243-f3698fab9ea5)

5.2. Change import in vue page to
```
<script setup lang="ts">
      import * as mqtt from  'mqtt/dist/mqtt.min';
      if(process.client){
         const client = mqtt.connect("ws://broker.emqx.io:8083/mqtt");
        console.log(client);
      }
</script>
```

5.3. The got error
![image](https://github.com/mqttjs/MQTT.js/assets/14201370/bbeadb45-aef1-4c3e-ba62-78d9f6f4d54d)

My package.json is
![image](https://github.com/mqttjs/MQTT.js/assets/14201370/d8b9a09c-be3a-4e6e-8ab7-2ea5e9c1366f)

Please advice.

**Comment by vagreargnatry** [comment]
Currently you can add `"./dist/*": "./dist/*.js"` to your mqtt's node_modules/package.json.

Related: https://github.com/mqttjs/MQTT.js/pull/1677

**Comment by mrkimmy** [comment]
> Currently you can add `"./dist/*": "./dist/*.js"` to your mqtt's node_modules/package.json.
> 
> Related: #1677

Thank you for kindly help. This fixed my problem. Version mqtt:5.0.4 is working properly. 👍
