### ISSUE TITLE
WSS connection issue with Chromium Browser

### ISSUE THREAD

**Issue by bjun626** [mqttjs/MQTT.js#1684]
Hi. I'm having an issue connecting to my MQTT server via wss using Chrome and Edge browser.

Below is the error message thrown from `client = mqtt.connect(connectUrl, mqttOp)`

```
_device_-ff12579c.js:1 WebSocket connection to 'wss://mqtt.[mydomain.com]:8084/ws' failed: 
(anonymous) @ _device_-ff12579c.js:1
(anonymous) @ _device_-ff12579c.js:1
(anonymous) @ _device_-ff12579c.js:1
connect @ _device_-ff12579c.js:1
_reconnect @ _device_-ff12579c.js:1
(anonymous) @ _device_-ff12579c.js:1
```
The issue is similar to #1470, the error is thrown by `let socket = new WebSocket(url, [websocketSubProtocol])`. I got this issue using Chrome, and Edge browser. But the connection is successful using Firefox and IOS Safari. 

I'm currently using version 5.0.4 with vue3 vite. I've tried `import * as mqtt from "mqtt"` with all the dependencies installed with a similar error. Downgrading the version doesn't help. Below is my MQTT init code.

Chrome Version: `Version 116.0.5845.111`
Edge Version: `Version 116.0.1938.62`

```ts
import * as mqtt from "mqtt/dist/mqtt.min"
// import * as mqtt from "mqtt"

let client = null

const mqttInit = (data) => {
  if (client) return client
  const connectUrl = `wss://mqtt.[mydomain.com]:8084/ws`
  const mqttOp = {
    connectTimeout: 30 * 1000,
    keepalive: 60,
    rejectUnauthorized: true,
  }
  mqttOp.username = data.username
  mqttOp.password = data.mqttPassword
  client = mqtt.connect(connectUrl, mqttOp) // create a client
  return client
}
```

Did I miss something in my settings specific to Chromium browser?

**Comment by robertsLando** [comment]
@bjun626 Sorry but that error doesn't help so much, could you dig into this a bit more?

**Comment by bjun626** [comment]
# Using Chromium Browser

So from what I can see, the `mqtt.connect` is only called once. But there seems to be a background task to trying to connect to the MQTT server by creating the `let socket = new WebSocket(url, [websocketSubProtocol])`.

![image](https://github.com/mqttjs/MQTT.js/assets/34598848/bdfcf8b9-5f3a-4355-adda-c3baf780cd94)

From the Network logs, it seems that the connection is all listed as pending, so there might be no reply from the MQTT server. Also, the Request URL is correct but the `Request Headers` is showing `Provisional headers are shown`

![image](https://github.com/mqttjs/MQTT.js/assets/34598848/261007b6-9c2b-4b70-8f3a-52aaa517cea4)
![image](https://github.com/mqttjs/MQTT.js/assets/34598848/253ffc51-e3fc-41fd-943d-088a7dcfbe2e)

# Using Firefox Browser

When using Firefox browser the connection is successful,

![image](https://github.com/mqttjs/MQTT.js/assets/34598848/f0033bb3-b37b-4025-ac8f-870f4f9020c1)
![image](https://github.com/mqttjs/MQTT.js/assets/34598848/18d196b7-e5bd-4865-9d3f-e20e3f55d205)

What I can suspect at the moment is my settings might be wrong which lead to the wrong setup for the `let socket = new WebSocket(url, [websocketSubProtocol])` function. But it is weird that Firefox is fine.

**Comment by robertsLando** [comment]
Do you have access to your broker logs? Maybe that can tell more about the error. What we see here is just a connection failed that doesn't tell so much about the origin of the error. Also your settings are not wrong otherwise it wouldn't connect even in firefox

**Comment by robertsLando** [comment]
Sorry but I have no clue so, really weird

**Comment by bjun626** [comment]
Cheers, thanks for the feedback. I'll try to investigate the `let socket = new WebSocket(url, [websocketSubProtocol])` function

**Comment by CyrusNG** [comment]
> Found the source of the issues. It is EMQX's Listeners' `, and it has to be marked off for MQTTJS to work. Even though `SSL Failed If No Peer Cert` is marked `false` it will still cause the WSS connection error.
> 
> <img alt="image" width="420" src="https://private-user-images.githubusercontent.com/34598848/265749058-669378c1-f4dd-4bb4-a6a7-0c14eb77c116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI3ODQ0NDIsIm5iZiI6MTc0Mjc4NDE0MiwicGF0aCI6Ii8zNDU5ODg0OC8yNjU3NDkwNTgtNjY5Mzc4YzEtZjRkZC00YmI0LWE2YTctMGMxNGViNzdjMTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI0VDAyNDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OTRlOTMyNzUyYzNlMTE4MTAzM2Y5OGFiYzZiNTg5Njk2NjU1YmM1N2NkNjYxNTliNjUyZGNjZTJmOGUxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HLMN6yBzbcFvFegj5saYt856FxJRtqiPUKOV0IXm3xc">

So, I have the similar issue, and how to set mqttjs as  `TLS Verify Client` off?
