### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by quanbui1997** [mqttjs/MQTT.js#1689]
i have a Reactjs project and get the isssue process is not defined when compile. Is there any solution? Please help me
dependencies
![image](https://github.com/mqttjs/MQTT.js/assets/125259954/b32ed32a-5d7b-4ca4-a3a5-df7288edc1f9)
craco.config.js
![image](https://github.com/mqttjs/MQTT.js/assets/125259954/5c783d92-173b-438b-9f9b-74260b2d1c33)
error
![image](https://github.com/mqttjs/MQTT.js/assets/125259954/b646e26f-93ed-4ada-a0ab-61a2c68ae809)

**Comment by robertsLando** [comment]
If you have an `index.html` entrypoint you may want to try adding process manually there like this comment suggest (replace Buffer with process): 

https://github.com/mqttjs/MQTT.js/issues/1639#issuecomment-1662533847

**Comment by quanbui1997** [comment]
> If you have an `index.html` entrypoint you may want to try adding process manually there like this comment suggest (replace Buffer with process):
> 
> [#1639 (comment)](https://github.com/mqttjs/MQTT.js/issues/1639#issuecomment-1662533847)

please show me how to replace Buffer with process

**Comment by robertsLando** [comment]
@quanbui1997 are you using:

```
import * as mqtt from 'mqtt/dist/mqtt'
```

?

**Comment by kandahk** [comment]
It worked for me using this` 'mqtt/dist/mqtt'`

**Comment by quanbui1997** [comment]
> @quanbui1997 are you using:
> 
> ```
> import * as mqtt from 'mqtt/dist/mqtt'
> ```
> 
> ?

tks for help, it worked

**Comment by robertsLando** [comment]
FYI starting from 5.2.1 you can now import mqtt using:

`import mqtt from 'mqtt'`
