### ISSUE TITLE
Authentication using JWT on EMQX broker

### ISSUE THREAD

**Issue by vetinary** [mqttjs/MQTT.js#1690]
I have EMQX installed on my server. It has two Authentication mechanisms enabled: Built-in Database and JWT. 

There is no problem using MQTT.js to Authenticate users added with Built-in Database: they have username and password, and everything works fine.
The problem is I can't figure out how to use MQTT.js with JWT. I have already tried everything — no success. I've tried to to set my generated token as a username, as a password, both as username and password… Tried to add "token=", tried everything I found on the Internet, and nothing helped to make it work.

There is only a small section In the documentation, covering usage of tokens, but it covers transform transformWsUrl and there is some 'signed_cloud_url' involved.

Does anyone has a working example of setting up MQTT.js with EMQX JWT Auth? 🙏🤯

**Comment by robertsLando** [comment]
I think JWT only works when using websockets? Maybe you have to set an header in the websocket request

**Comment by vetinary** [comment]
My bad, I didn't mention that. I'm using websockets. I'm trying to implement client JWT authorization in browser, which connects to emqx using WS (Nginx is used as a proxy for MQTT).

**Comment by robertsLando** [comment]
If it supports MQTT 5 you could set `properties` object in options when creating the mqtt client. There you can add some properties to connect packet sent to the broker like `authenticationMethod` and `authenticationData` for example. 

See source: https://github.com/mqttjs/MQTT.js/blob/main/src/lib/client.ts#L818

**Comment by vetinary** [comment]
EMQX supports MQTT 5.
Could you please provide an example of using it? I examined documentation yesterday and saw this parameter in this section https://github.com/mqttjs/MQTT.js#client however there is no list of values, which can be used as `authenticationMethod`, that's why I don't know how to use it. Will JWT do as a value?

**Comment by robertsLando** [comment]
If you are using typescript it will show you available properties

**Comment by vetinary** [comment]
No, there is no typescript in my project, just simple javascript. Ok, I'll try to find it out looking through the source code of the library.

**Comment by robertsLando** [comment]
https://github.com/mqttjs/mqtt-packet/blob/master/types/index.d.ts#L65

**Comment by vetinary** [comment]
Well, after almost two hours of experiments it turned out that EMQX Dashboard doesn't apply the changes "on the fly" and the only think I had to do make it work is to restart EMQX 🤦‍♂ 
Now everything works fine.

Thank you for your time and help.
