### ISSUE TITLE
client.on('message') - can I clear the handler, so I won't get duplicate messages?

### ISSUE THREAD

**Issue by wernermorgenstern** [mqttjs/MQTT.js#1693]
I have noticed (and I have some a previous issue reported, which is closed), is that when I call client.on('message', handler Function) a few times, that it will process the same message multiple times.

Is there a way, when I want to unsubscribe from the topic, and resubscribe, that I can clear the message handler, and add it again, so that way I won't process the same message multiple times?

or do I need to call client.end(), and then set the client to undefined?

**Comment by robertsLando** [comment]
the way to do this is to simply use `off` or `removeListener` methods to remove the previous listener: https://nodejs.dev/en/api/v20/events/#emitterremovelistenereventname-listener
