### ISSUE TITLE
Errors with Next.js

### ISSUE THREAD

**Issue by Baruchware** [mqttjs/MQTT.js#1698]
Hello, I have to setup a simple example using MQTT protocol.

I already tested it with desktop/native clients, and it works as expected.
but whenever I try to use this library in a Next.js project, seems there is no way to make it work.

One error I keep getting is the following: TypeError: mqtt_dist_mqtt__WEBPACK_IMPORTED_MODULE_2___default() is undefined

I tried importing like this: 
`import mqtt from 'mqtt'`
and 
`import mqtt from 'mqtt/dist/mqtt`

nothing changes..

I ve tried following this:
https://github.com/vercel/next.js/discussions/16904
and
https://community.hivemq.com/t/websocket-connection-failed-solution/1964

but still nothing change..

could you please help me understand what is going on?

**Comment by robertsLando** [comment]
Tried to follow this: https://github.com/mqttjs/MQTT.js#webpack ?

**Comment by Baruchware** [comment]
you are right!
Thank you a lot for this link w clarification!

Have a good day ser 👍 🚀

**Comment by robertsLando** [comment]
FYI starting from 5.2.1 you can now import mqtt using:

`import mqtt from 'mqtt'`

**Comment by Baruchware** [comment]
Thank you for letting me know that!
🚀 ☮️ ✌️
