### ISSUE TITLE
Enquiry about QoS 0 when reconnecting 

### ISSUE THREAD

**Issue by fattomhk** [mqttjs/MQTT.js#1706]
While the message id by default with QoS = 0 is 0.
And if we put the connection to airplane mode and reconnect it again, the following deliver method will be called. 

<img width="450" alt="image" src="https://github.com/mqttjs/MQTT.js/assets/1083049/a79398e3-670b-42b1-ad8a-76d7bd70b4aa">

https://github.com/mqttjs/MQTT.js/blob/e3c06430ccd9e98ae5c2c007152ff6fc90938f40/src/lib/client.ts#L618C11-L618C11

I am wondering should the queued packets send when when re-connect with QoS = 0? 

If it is by design, any suggested way to not deliver the queued message to MQTT broker?

**Comment by robertsLando** [comment]
> If it is by design, any suggested way to not deliver the queued message to MQTT broker?

Just use QoS > 0?

**Comment by fattomhk** [comment]
thanks for your reply. 
However, our use case should not buffer the messages as the message need to be sent timely. 
If the message delivered over a minute, it won't be useful anymore. 

you may refer to this [link's](http://www.steves-internet-guide.com/mqtt-client-message-queue-delivery/#:~:text=of%20the%20consequences.-,Problems,-with%20Buffering%20Messages) example.
