### ISSUE TITLE
The exception 'ws does not work in the browser' if I try connecting from a worker thread

### ISSUE THREAD

**Issue by a1leks** [mqttjs/MQTT.js#1709]
### The Issue

I use MQTT 5.1.0 in a browser inside a [worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) thread, but I can't connect and I get an exception: **ws does not work in the browser**

<img width="720" alt="Screenshot 2023-10-06 at 13 16 12" src="https://github.com/mqttjs/MQTT.js/assets/15309083/ae5bdaf1-63b2-4103-a14d-b694bf660fbc">

As I see this code can be the root reason of issue:
https://github.com/mqttjs/MQTT.js/blob/5006aea67eaea6905768d44add60234e49ac607b/src/lib/is-browser.ts#L1-L2

I have `isBrowser` `false` because I don't have the `window` object inside a worker. It leads to executing `streamBuilder` and then I get mentioned exception in `createWebSocket`
https://github.com/mqttjs/MQTT.js/blob/5006aea67eaea6905768d44add60234e49ac607b/src/lib/connect/ws.ts#L141 
however I expect executing `browserStreamBuilder`
https://github.com/mqttjs/MQTT.js/blob/5006aea67eaea6905768d44add60234e49ac607b/src/lib/connect/ws.ts#L158

In case I fix the browser checking, everything works fine for me, and the connection is successful.

### The proposal/question

Could you consider improving the 'is-browser' checking or giving me an advice on how to properly make MQTT connecting from a browser worker thread? I appreciate your answer.

**Comment by expcapitaldev** [comment]
do not see any info about Web worker and MQTT, is it supported ?

**Comment by robertsLando** [comment]
`import * as mqtt from 'mqtt/dist/mqtt'`

**Comment by a1leks** [comment]
I import exactly like you wrote. It works fine from main JS thread but **it didn't work from web worker js thread**. I've read the doc. Your advise unfortunately didn't help.

Have you ever tested this lib inside worker? Could you clarify mqtt.js 5.x.x is compatible with WebWorkers in browser (or not)? Thanks for answer!

**Comment by robertsLando** [comment]
@a1leks any hints about the error thrown?

**Comment by robertsLando** [comment]
what you could try is to manually create your websocket by using the `createWebsocket` option

**Comment by a1leks** [comment]
Thanks! I've tried. However in this case I have an error _ws_1.default.createWebSocketStream is not a function_:

<img width="700" alt="Screenshot 2023-10-09 at 18 05 38" src="https://github.com/mqttjs/MQTT.js/assets/15309083/8a5cbf2a-5ae0-43b4-b6c0-403d89786c3b">

It looks like code from https://github.com/websockets/ws which doesn't work in browser.

This is the root issue I guess. Could you please have a look 
```
const isBrowser = typeof window !== 'undefined' && typeof window.document !== 'undefined';
```
It doesn't look compatible with web workers in browser.

**Comment by robertsLando** [comment]
Could you test this? https://github.com/mqttjs/MQTT.js/pull/1711

**Comment by a1leks** [comment]
The fix works good for me. Connection is successful from a web worker.

**Comment by robertsLando** [comment]
Perfect, will merge and release tomorrow a new patch

**Comment by a1leks** [comment]
Thanks!

**Comment by robertsLando** [comment]
FYI starting from 5.2.1 you can now import mqtt using:

`import mqtt from 'mqtt'`
