### ISSUE TITLE
Do not remove nodejs support in minor versions please

### ISSUE THREAD

**Issue by Apollon77** [mqttjs/MQTT.js#1710]
Hi, it seems that you removed support for Node.js 16.x in 5.1.0 (https://github.com/mqttjs/MQTT.js/commit/069605bd5da346ee0f0edeb8b79a092e31ed48f8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L95) ... this makes a lot issues when dependenciesare used as normalyl with carets.

If this was wanted a reverting 5.1.x and a new major version yowould be great for this. :-)

**Comment by robertsLando** [comment]
@Apollon77 I'm sorry for the incovenience with that, I totally forgot that line when merging the PR. Giving that that change is only needed for tests, would it be ok for you If I only fix the engines in package.json? Everything should work as expexted with node 16 too it's just that it's not compatibile with tests anymore (and also reached EOL)

**Comment by Apollon77** [comment]
sure, a patch release that fixes this is absolutely fine. Thank you for your fast reaction and support!

**Comment by robertsLando** [comment]
Patch is coming 🙏🏼

**Comment by Apollon77** [comment]
Thank you very much!
