### ISSUE TITLE
I am connected to the server and have been pending processing

### ISSUE THREAD

**Issue by bbhxwl** [mqttjs/MQTT.js#1713]
There is no problem with connecting to mqtt in my Vue project, while nuxt uses mqtt to connect. The time column of the development tool always shows pending processing

why？    version  "^4.3.7"

**Comment by robertsLando** [comment]
first of all you are not using the latest version. Then the pending is normal because it's a websocket...

**Comment by bbhxwl** [comment]
> first of all you are not using the latest version. Then the pending is normal because it's a websocket...

I already know, isn't this a bug? Because I entered the password as a number type instead of a string type, strange problems may arise.

**Comment by robertsLando** [comment]
All websockets are shown as pending, them are open connections, the connection didn't ended so there is no reason to show a time there...
