### ISSUE TITLE
Type Definitions in Browser Version 5.2.1 Need Update or Separate Types File - Incompatible with Included NPM Types

### ISSUE THREAD

**Issue by davidhmays** [mqttjs/MQTT.js#1719]
When the _browser_ version of MQTT.js is imported, the types included in the project aren't currently usable in v5.2.1.
See the error below when importing with Vite.

In older versions of MQTT.js, a separate types file had been available for the browser, but it appears to have gone away now that types are included in the main project. Unfortunately the main project's type exports don't seem to match the browser typings or package.json exports,  npm install @types/mqtt shows a message saying something like "you don't need this, types are now included", and without a separate types file I can't seem to get type definitions working for the browser.

Using Vite:
`import * as mqtt from 'mqtt/dist/mqtt.min`

Result:
> There are types at '*****/node_modules/mqtt/build/mqtt.d.ts', but this result could not be resolved when respecting package.json "exports". The 'mqtt' library may need to **update its package.json** or **typings**.

Could the types / package.json be updated to allow types for the browser version?
Or did I miss a simple way to point to the correct browser based types? Is a browser types file available?
Types are so helpful when learning a new library, helping to sure you fill out the required connection objects correctly.

Thanks!

**Comment by robertsLando** [comment]
@davidhmays Try to use   `import * as mqtt from 'mqtt/dist/mqtt`

**Comment by robertsLando** [comment]
Starting from 5.2.1 you can now import mqtt using:

`import mqtt from 'mqtt'`
