### ISSUE TITLE
odd behavior when subscribing to topics with wildcards

### ISSUE THREAD

**Issue by rjbordon** [mqttjs/MQTT.js#172]
Hi there,

I've having some issues when subscribing to topics with wildcards. If I subscribe my client to "devices/+/activation" a message published to "devices/qwerty/metadata" if being processed by my client, which is in fact an error.

I'm using mosquitto as MQTT broker. This implementation supports wildcards for topics, and when I try this functionality with the mosquitto built-in client it works as expected. (just in case: http://mosquitto.org/man/mosquitto-8.html)

Does MQTT.js support this functionality? or I missing something else?

Thx in advance.

**Comment by VikramTiwari** [comment]
@mcollina Not exactly the same behaviour, but unable to publish/subscribe on the wildcard topics.

listening to `mqtt sub -t 'hello/vikram/hi' -h 'test.mosquitto.org' -v`
publishing to `mqtt pub -t 'hello/+/hi' -h 'test.mosquitto.org' -m 'from MQTT.js' `

getting no data on the subscriber side.
PS: Using node v4.1.0

**Comment by mcollina** [comment]
You need to:

mqtt sub -t 'hello/+/hi' -h 'test.mosquitto.org' -v
mqtt pub -t 'hello/vikram/hi' -h 'test.mosquitto.org' -m 'from MQTT.js'

**Comment by VikramTiwari** [comment]
Does this means I can subscribe on wildcard topics but can not publish to wildcard topics?

**Comment by RangerMauve** [comment]
@VikramTiwari Yes. MQTT doesn't allow you to publish to topics with wildcards in them AFAIK.

You must publish to topics that match the wildcards.

**Comment by anhldbk** [comment]
@mcollina This issue still persists. Here is the demo code:

```js
// test.js

var mqtt    = require('mqtt');

var client  = mqtt.connect('mqtt://test.mosquitto.org');
client.on('connect', function () {
  console.log('Connected')
  client.subscribe('#/:event/status') // <- using # will cause the problem below
});

client.on('offline', function () {
  console.log('Offline')
});
```

The output will be:
```text
$ node test.js
Connected
Offline
Connected
Offline
Connected
Offline
Connected
Offline
Connected
Offline
Connected
Offline
Connected
Offline
Connected
Offline
Connected
...
```

**Comment by RangerMauve** [comment]
@anhldbk What makes you say that this is related to the wildcards? Is there an error you're seeing that would suggest that? Because it just looks like your socket is disconnecting and reconnecting for no particular reason.

**Comment by anhldbk** [comment]
@RangerMauve There are many reasons:

1. If I subscribe to another mailboxes like `+/:event/status`, `data`..., it works well.
2. My network connection is stable. Actually, I tried to run the program above with a local MQTT broker before using `test.mosquitto.org`

**Comment by RangerMauve** [comment]
Are you logging any errors on the client side or on the broker itself?

**Comment by anhldbk** [comment]
@RangerMauve There's no error logged on the client side.

```js
client.on('error', function (error) {
  console.log('Error: ' + error) // <-- Nothing is printed out
});
```

**Comment by sandro-k** [comment]
@anhldbk the `#` has to be at the end like `foo/bar/#`. If you want to subscribe to everything just use `#`

`#/:event/status` === `#` because everything that is after the `#` is irrelevant. See http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices

**Comment by anhldbk** [comment]
@sandro-k Thank you for your explanation! 

@mcollina Is it a good idea for `mqtt.js` to validate topics before sending the subscriptions to brokers?

**Comment by anhldbk** [comment]
@mcollina I'm working on it.

**Comment by NancyZY** [comment]
@mcollina,  @sandro-k ,  why I cannot accpt the message ? 
sub topic : 'floor/+'
pub topic : 'floor/1'

**Comment by sandro-k** [comment]
@NancyZY sub to `floor/+` and pub to `floor/1` is valid. As already mentioned the MQTT-Spec is saying what is possible and what not. A good explanation can be found at http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices

**Comment by NancyZY** [comment]
@sandro-k ,yeah, I got it. I want to ask for another aspect: What is the limit of subscribe ? In other word, How many topics sub-client  can accept  at most? and How to solve it ? Does it have a method to test the limit?

**Comment by sandro-k** [comment]
42 - no just joking. As many as your System can handle CPU/RAM wise.

**Comment by NancyZY** [comment]
Ooh, I knew it , thank you! It is a few number. How can I deal with the situation? I want to deal with the cloud  client which can sync status, then notify the mobile phone, it subscribe the topic like "floor/+" , but the number of publish topic is thousands. What can I do to run normally？

**Comment by sandro-k** [comment]
It is a scalability issue you are facing. Split up hierarchy to support multiple processes and threads so that each process is doing a portion a the topics.

**Comment by NancyZY** [comment]
Hi, the whole process that subscribing  and publishing topic is right, BUT,  sometimes it happened wrong , the console hints **[Errno 54] Connection reset by peer**,  what is it? How can I solve it
