### ISSUE TITLE
Missing TypeScript Types in browser version

### ISSUE THREAD

**Issue by kolarski** [mqttjs/MQTT.js#1729]
Using: `import * as mqtt from "mqtt/dist/mqtt";`

I can correctly import the library and connect to a websocket.
But I'm missing all TypeScript types and getting error/warning: `Could not find a declaration file for module 'mqtt/dist/mqtt'`

Using: `import mqtt from "mqtt"` I get all types but it does not work in a browser env. 

Is there a way to bundle the browser version with the typescript declaration files so that the library can be used in TypeScript React projects ? Or is there some workaround to get the types applied to `mqtt/dist/mqtt` ?

Maybe using [tsify](https://www.npmjs.com/package/tsify)  can be solution to build browser version with declaration files ?

**Comment by robertsLando** [comment]
> But I'm missing all TypeScript types and getting error/warning: Could not find a declaration file for module 'mqtt/dist/mqtt'

Where do you get this error? Could you better define your environment? Are you using vue + ts + vite for example? What I don't understand is, when I import mqtt like that types are correctly identified by ide (vscode) because them are picked up by: https://github.com/mqttjs/MQTT.js/blob/main/package.json#L44. I dunno what tsify does more then this 🤔

**Comment by kolarski** [comment]
Thanks for your quick response!

I'm trying to narrow down the issue.
Indeed it looks it is something in my environment. (It is mostly new TypeScript / React / Vite project)

The error is caused by using `strict: true` in `tsconfig.json` using `strict: false` it is just a warning and I can compile the project.

I have a workaround at the moment: 

Defining a type file `mqtt.min.d.ts`
With contents: 
```
declare module "mqtt/dist/mqtt.min" {
    export * from "mqtt";
}
```

Seems to recognize all types and work correctly. 

I'll try to figure out exactly what is causing the issue if someone else encounters the issue.
Feel free to close the issue!

**Comment by robertsLando** [comment]
Could you give a try using [this](https://github.com/mqttjs/MQTT.js/pull/1732) PR? Maybe the only thing missing here are sorucemaps

**Comment by kolarski** [comment]
@robertsLando Thanks! I can confirm that the new version works great for me. 
All the types are detected correctly in React without any changes!

**Comment by robertsLando** [comment]
Perfect, thanks for your feedback. Are you using `import mqtt from 'mqtt'` so?

**Comment by kolarski** [comment]
@robertsLando Yes, reworked my code and works the same using `import mqtt from 'mqtt'`
