### ISSUE TITLE
Browserified MQTT.js defaults to connecting to localhost instead of server URL

### ISSUE THREAD

**Issue by dstolpmann** [mqttjs/MQTT.js#1730]
I am using the MQTT.js version from https://unpkg.com in the browser and experience the following issue.

In old versions (<=4.1.0), MQTT.js used to connect to the host that served the website and also used the same port if `connect()` was called without an URL. I do not know if it also selected wss over ws if the page was served via HTTPS, as I never used TLS.

Starting with 4.2.1 (4.2.0 does not work in the browser) and also in the current 5.1.4 release, calling `connect()` without an URL always connects to `ws://localhost/`.

This change in behavior was probably introduced in #1108.

I worked around this issue by using the following command:

```js
mqtt.connect((location.protocol == "https:" ? "wss" : "ws") + "://" + location.hostname + ":" + location.port)
```

**Comment by robertsLando** [comment]
@BrandonSmith would you like to submit a pr to fix this issue? you could use the `is-browser` const to detect the environment and based on that use `localhost` or the other default url

**Comment by haihuynhDF** [comment]
I also meet this issue when trying to connect MQTT from `ReactJS`

It connects to `localhost` instead of the host which I config in the option

But it works when I connect from `NodeJS`

This is my source code
```js
const opt: mqtt.IClientOptions = {
  host,
  protocol: "mqtt",
  clientId,
  clean: true,
  key,
  cert,
  ca,
  reconnectPeriod: 0,
};

const client: MqttClient = mqtt.connect(opt);

client.on('connect', () => {
  console.log('client connected');
  client.publish(
    `topic`,
    "abc",
  );
})
```

**Comment by robertsLando** [comment]
You should not provide an `host` in options in order to have it connecting to document url https://github.com/mqttjs/MQTT.js/blob/6591404b38c73550157e22f3e57683a634bb919c/src/lib/connect/ws.ts#L78
