### ISSUE TITLE
`will` `payload` typed as `Buffer` incompatible with browser code

### ISSUE THREAD

**Issue by Boudewijn26** [mqttjs/MQTT.js#1735]
The [`will#payload`](https://github.com/mqttjs/mqtt-packet/blob/master/types/index.d.ts#L52) property requires a `Buffer` to be passed. Though I find it does support `string`s. Since `Buffer`s are only a thing in Node.JS this means any browser code using the will option need to cast their string to Buffer

```typescript
const clientId = "my-client"
const client = await mqtt.connectAsync(url, {
  username,
  password,
  clientId,
  will: {
    topic: `health/${clientId}`,
    payload: 'disconnected' as unknown as Buffer, // cast because browsers don't have Buffer
    qos: 1,
    retain: true
  }
})
```

**Comment by robertsLando** [comment]
Would you like to submit a PR to fix this issue?

**Comment by Boudewijn26** [comment]
I wouldn't mind: https://github.com/mqttjs/mqtt-packet/pull/147

**Comment by Boudewijn26** [comment]
Bump

While https://github.com/mqttjs/mqtt-packet/pull/147 has been merged, it hasn't been released and thus this issue is still relevant

**Comment by robertsLando** [comment]
I tried to bump @mcollina multiple time in that PR hope he will see this now

**Comment by AlexMath23** [comment]
@robertsLando you mean the 5.10.3 release ? because there are still Buffer types in that version

**Comment by robertsLando** [comment]
I bumped mqtt packet here https://github.com/mqttjs/MQTT.js/commit/b7c8c3270955d6154c44f7e79e2a3104baac6a42

So types should be good starting from 5.10.2

**Comment by AlexMath23** [comment]
> I bumped mqtt packet here [b7c8c32](https://github.com/mqttjs/MQTT.js/commit/b7c8c3270955d6154c44f7e79e2a3104baac6a42)
> 
> So types should be good starting from 5.10.2
It seems like mqtt-packet 9.0.1 hasn't ditched the Buffer types yet https://github.com/mqttjs/mqtt-packet/blob/master/types/index.d.ts#L52
![image](https://github.com/user-attachments/assets/f6dd9a03-a38e-4698-b171-e5c4afab732c)

**Comment by robertsLando** [comment]
@AlexMath23 from your screenshot you can see that `payload` is typed as `Buffer | string` so it seems to be good.

**Comment by AlexMath23** [comment]
@robertsLando  is the same screenshot you see properties that are still Buffer only (correlationData, password, etc ...) , there you just run into the same incompatibility problem. Do you recommend asserting Uint8Array's as the Buffer type, or importing some 3rd party 'browserify' like library to get Buffer functionality ? or are you guys planning on adding Buffer alternatives in the future for the other properties

**Comment by robertsLando** [comment]
The best would be to drop buffer type everywhere in favour of Uint8Array but that requires lot of work in both mqtt-packet and mqtt side
