### ISSUE TITLE
Connection failure in react application

### ISSUE THREAD

**Issue by MuhammadHARIS46** [mqttjs/MQTT.js#1737]
useEffect(() => {

    const client = mqtt.connect('mqtt://tag4track.com:1883', {
      username,
      password,
    });

    client.on('connect', () => {
      console.log('Connected to MQTT broker');
      client.subscribe(topic);
    });

    client.on('message', (subscribedTopic, message) => {
      console.log(`Received message on topic ${subscribedTopic}: ${message.toString()}`);
    });

    client.on('error', (error) => {
      try {
        console.error('MQTT Error:', error);
      } catch (err) {
        console.error('Error in error handler:', err);
      }
    });
    
    console.log("hello")

    

    // Cleanup the MQTT client when the component unmounts
    return () => {
      client.end();
    };
  }, []); this is the relevant code and that is WebSocket connection to 'ws://tag4track.com:1883/' failed:  the error i am facing. i am not using websocket anywhere in my application. There is no network security and firewall issue and these config work all fine when i use it in mqtt explorer. If there is anybody who can help or guide me.

**Comment by robertsLando** [comment]
When you use mqttjs on browser only websocket protocol is supported (this because browsers themself don't support any anther protocol).

Tipically 1883 is the tcp address of a broker, not the ws. You should enable ws in your broker, check docs of your broker

**Comment by MuhammadHARIS46** [comment]
> When you use mqttjs on browser only websocket protocol is supported (this because browsers themself don't support any anther protocol).
> 
> Tipically 1883 is the tcp address of a broker, not the ws. You should enable ws in your broker, check docs of your broker

i have been provided the mqtt config by my client so probably he has the access to broker so i shall ask him to do this right?

**Comment by robertsLando** [comment]
Yeah, ask him to give you websocket port

**Comment by MuhammadHARIS46** [comment]
> Yeah, ask him to give you websocket port
this is view of mqtt explorer it works fine on this config.
![Capture](https://github.com/mqttjs/MQTT.js/assets/75878226/6751a595-ae07-4f2d-a707-87bbd50cafd5)
![WhatsApp Image 2023-11-12 at 1 00 46 AM](https://github.com/mqttjs/MQTT.js/assets/75878226/a68621f4-f090-444a-a3de-8c17fc1d51c7)
and look he shows me the ports and protocols enabled but i still get the error. Can you help me ? I am like integrating mqtt in my react application.

**Comment by MuhammadHARIS46** [comment]
> Yeah, ask him to give you websocket port

and he also has given me his EMQX username and password. i dont know why and the client is difficult to understand

**Comment by robertsLando** [comment]
@MuhammadHARIS46 again, mqtt:// uses TCP and IT IS NOT AVAILABLE ON BROWSERS! It will be converted to ws:// on browser but if your broker doesn't support websockets it will not connect! This is also specified on docs [here](https://github.com/mqttjs/MQTT.js#via-cdn) and again it's not a MQTTjs limitation but there is no way to make this on browsers.

When connecting from a BROWSER you can ONLY use WEBSOCKETS. Mqtt explorer is an APPLICATION (built using electronjs) and it can use all protocols as it uses nodejs.

**Comment by MuhammadHARIS46** [comment]
> @MuhammadHARIS46 again, mqtt:// uses TCP and IT IS NOT AVAILABLE ON BROWSERS! It will be converted to ws:// on browser but if your broker doesn't support websockets it will not connect! This is also specified on docs [here](https://github.com/mqttjs/MQTT.js#via-cdn) and again it's not a MQTTjs limitation but there is just no way to make this on browsers.
> 
> When connecting from a BROWSER you can ONLY use WEBSOCKETS. Mqtt explorer is an APPLICATION (built using electronjs) and it can use all protocols as it uses nodejs.

yeah i got you brother but look at the image above that i show you ws is enabled.

**Comment by MuhammadHARIS46** [comment]
> @MuhammadHARIS46 again, mqtt:// uses TCP and IT IS NOT AVAILABLE ON BROWSERS! It will be converted to ws:// on browser but if your broker doesn't support websockets it will not connect! This is also specified on docs [here](https://github.com/mqttjs/MQTT.js#via-cdn) and again it's not a MQTTjs limitation but there is just no way to make this on browsers.
> 
> When connecting from a BROWSER you can ONLY use WEBSOCKETS. Mqtt explorer is an APPLICATION (built using electronjs) and it can use all protocols as it uses nodejs.

yeah i got you. i made the connection  
![image](https://github.com/mqttjs/MQTT.js/assets/75878226/fd54dfe9-87ff-4b43-912f-0eb0a99fd2da)
![image](https://github.com/mqttjs/MQTT.js/assets/75878226/358339ce-2cb0-4b20-9829-aebf06cf5c01)
i can see the topics being subscribed on the EMQX dashboard. when i used mqtt explorer added the topics and connect i was receiving data there. but here in my react app i can't see this       console.log(`Received message on topic ${topic}: ${message.toString()}`);
on my console. Any insights for this would be really helpful

**Comment by robertsLando** [comment]
it depends if the messages published to those topics are retained them will received on subscribe but otherwise them will be received only when sent

**Comment by MuhammadHARIS46** [comment]
> it depends if the messages published to those topics are retained them will received on subscribe but otherwise them will be received only when sent

![image](https://github.com/mqttjs/MQTT.js/assets/75878226/5b168870-8721-4880-bb70-4a10fc264087)
is there anything i can do right now?

**Comment by robertsLando** [comment]
just set the retained flag on publish....

**Comment by MuhammadHARIS46** [comment]
> just set the retained flag on publish....

![image](https://github.com/mqttjs/MQTT.js/assets/75878226/f8b4ffb0-a6c7-4cc3-8931-507a794e3285)
first i receive error and i am good subscribed 
![image](https://github.com/mqttjs/MQTT.js/assets/75878226/ca86053d-e3e6-48c6-93e5-011ad48a5445)

**Comment by MuhammadHARIS46** [comment]
> just set the retained flag on publish....

![image](https://github.com/mqttjs/MQTT.js/assets/75878226/e2a63066-2560-4990-83a2-3f2e5917e91d)
what is this? 
![image](https://github.com/mqttjs/MQTT.js/assets/75878226/1d12a813-bc61-4d96-90df-1f8490dae509)
it is coming from here!

**Comment by tyas-susanto** [comment]
> > @MuhammadHARIS46 again, mqtt:// uses TCP and IT IS NOT AVAILABLE ON BROWSERS! It will be converted to ws:// on browser but if your broker doesn't support websockets it will not connect! This is also specified on docs [here](https://github.com/mqttjs/MQTT.js#via-cdn) and again it's not a MQTTjs limitation but there is just no way to make this on browsers.
> > When connecting from a BROWSER you can ONLY use WEBSOCKETS. Mqtt explorer is an APPLICATION (built using electronjs) and it can use all protocols as it uses nodejs.
> 
> yeah i got you. i made the connection ![image](https://private-user-images.githubusercontent.com/75878226/282471186-fd54dfe9-87ff-4b43-912f-0eb0a99fd2da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTMxMTgsIm5iZiI6MTcxNTU5MjgxOCwicGF0aCI6Ii83NTg3ODIyNi8yODI0NzExODYtZmQ1NGRmZTktODdmZi00YjQzLTkxMmYtMGViMGE5OWZkMmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA5MzMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZjQ5MWU2YzUyMGY3NGJmOGI1YTZmMGVkZGIzNzNiN2JmMDExNzdlNmVhOTFhNWRlZjg1NDczMDM2MjkzMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CYmq-kkhCOJwA6RSXTbd0QNhMTQkkl7dS5pCqTX9jqY) ![image](https://private-user-images.githubusercontent.com/75878226/282471480-358339ce-2cb0-4b20-9829-aebf06cf5c01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTMxMTgsIm5iZiI6MTcxNTU5MjgxOCwicGF0aCI6Ii83NTg3ODIyNi8yODI0NzE0ODAtMzU4MzM5Y2UtMmNiMC00YjIwLTk4MjktYWViZjA2Y2Y1YzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA5MzMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5N2YxZDAxNmYwNWMxOTY4OTc2N2NlZmJiNTgzNjljZTU4Y2YxMDgwYWJlZTYxMGVlYmJiYTAwZDU3YTE0NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yAEcepVfMiXgPbzF2fyMzELk1ItM9HO28jxLaTF7fU) i can see the topics being subscribed on the EMQX dashboard. when i used mqtt explorer added the topics and connect i was receiving data there. but here in my react app i can't see this console.log(`Received message on topic ${topic}: ${message.toString()}`); on my console. Any insights for this would be really helpful

how it possible? i also have same problem, i can't connect to mqtt with react
