### ISSUE TITLE
I can no longer use the same import code on node and browser since upgrading to `5.2.1`.

### ISSUE THREAD

**Issue by epatey** [mqttjs/MQTT.js#1738]
Thank you for the great project.

When using `5.1.4`, I was able to use the following `import` syntax in a utility module that was executed both on the server and browser.

```typescript
import { MqttClient, connect } from "mqtt"
```
After upgrading to `5.2.1`, the only way I can make it work is to have two different modules with different `import` syntax:
```typescript
// server
import * as mqtt from "mqtt"
...
mqtt.connect(...)
```
and
```typescript
// browser
import mqtt, { MqttClient } from "mqtt"
...
mqtt.connect(...)
```
Am I doing this wrong?

**Comment by epatey** [comment]
As an additional hint, when I do the the following on the client:
```typescript
import { MqttClient, connect } from "mqtt"
```
`Next.js` hot reloading warns me `Attempted import error: 'connect' is not exported from 'mqtt' (imported as 'connect').`

**Comment by robertsLando** [comment]
Try to set moduleResolution to `node16`

```json
{
  "compilerOptions": {
    "moduleResolution": "node16"
  }
}
```

**Comment by robertsLando** [comment]
@epatey Try with 5.2.2 and let me know. Anyway that import on nodejs should have never worked as there was no default export at all..

**Comment by epatey** [comment]
I'm all set now. Thank you.

**Comment by goran-markovic85** [comment]
This error on my side is still there:  Attempted import error: 'connect' is not exported from 'mqtt' (imported as 'connect'). I'm using 5.2.2 and nextjs 13.4.19

**Comment by robertsLando** [comment]
@goran-markovic85 how are you importing mqtt ?

**Comment by robertsLando** [comment]
it should work, dunno why it's failing...

Did you also tried with `import mqtt from 'mqtt'`? does that work?

**Comment by goran-markovic85** [comment]
I try like this `import {connect, MqttClient} from 'mqtt'`

**Comment by robertsLando** [comment]
Ok use this instead: `import mqtt from 'mqtt'`

**Comment by goran-markovic85** [comment]
if try like that I get  `TypeError: mqtt.connect is not a function`
```
    const mqttClient = mqtt.connect(brokerUrl, {
      username: mqttUsername,
      password: .mqttPassword,
      protocolVersion: 3,
      keepalive: 0,
    })
```

**Comment by robertsLando** [comment]
You must be doing something wrong as it works in all my setups, there is also a vite example in this repo
