### ISSUE TITLE
Multiple subscriptions to the same topic & retained messages

### ISSUE THREAD

**Issue by HelloItsKyle** [mqttjs/MQTT.js#1739]
I have a case where I'd like to subscribe to the same topic multiple times from the same client. The problem I'm facing is that the retained message is only returned to the first subscription and never again.

```
const client = mqtt.connect("url", {
    username: "username",
    password: "password",
});

client.on("connect", () => {
    client.subscribe("topic/1"); // immediately triggers .on("message") with the retained message
});

// subscribe to the same topic 10 seconds later
setTimeout(() => {
    client.subscribe("topic/1"); // does not trigger .on("message") with the retained message
}, 10000)

client.on("message", (topic, message) => {
    console.log(message.toString());
});
```
I've tried a few `options` in the [subscribe function](https://github.com/mqttjs/MQTT.js#mqttclientsubscribetopictopic-arraytopic-object-options-callback), like different `qos` and the `rh` values, but the MQTT broker sees this as a single subscription and the retained message is only sent on the first subscribe call.

Any help would be appreciated, thanks!

**Comment by robertsLando** [comment]
This is how protocol works, a second subscription to the same topic will not receive the retained message again...
