### ISSUE TITLE
TS2304: Cannot find name 'WebSocket'.

### ISSUE THREAD

**Issue by JimmyBjorklund** [mqttjs/MQTT.js#1746]
node_modules/mqtt/build/lib/shared.d.ts:10:14 - error TS2304: Cannot find name 'WebSocket'.

This line seams to be missing 
import type { WebSocket } from 'ws';

This issue was introduced in 5.3.0, its not present in 5.2.2

**Comment by Koenkk** [comment]
Having exactly the same issue ([link](https://github.com/Koenkk/zigbee2mqtt/pull/19896)).

`"skipLibCheck": true` suppresses the issue but not acceptable because it [reduce the type-system accuracy](https://www.typescriptlang.org/tsconfig#skipLibCheck)

**Comment by robertsLando** [comment]
@Koenkk Do you guys have a suggestion about how I could explicitly make it to return window.Websocket type instead `ws` Websocket?

**Comment by robertsLando** [comment]
5.3.1 is coming, sorry for the inconvenience...
