### ISSUE TITLE
v5  Cannot be used in uniapp, app-plus environments

### ISSUE THREAD

**Issue by codeDevStory** [mqttjs/MQTT.js#1750]
as shown in the title

node 16  or 20
vue 2.6
mqtt 5.3.1

**Comment by robertsLando** [comment]
What's the error you see? Is it on compilation time or runtime? What bundle are you using?

**Comment by codeDevStory** [comment]
> What's the error you see? Is it on compilation time or runtime? What bundle are you using?


mqqt 5.3.1
Introduced like this import mqtt from 'mqtt'
With uniapp, running to app-plus android
I get the following error


![image](https://github.com/mqttjs/MQTT.js/assets/82701276/80c5839e-0745-4637-b543-52703373d8a6)


If I introduce it like this
const mqtt = require("mqtt")

![image](https://github.com/mqttjs/MQTT.js/assets/82701276/a89d9208-6fb1-4362-8daf-42411a7dc295)


uniapp official website https://uniapp.dcloud.net.cn/

**Comment by robertsLando** [comment]
language is not present in source code so sincerly I have no clue what that error means

**Comment by codeDevStory** [comment]
> language is not present in source code so sincerly I have no clue what that error means

Inside the packaged code is Navigator.language

**Comment by codeDevStory** [comment]
> language is not present in source code so sincerly I have no clue what that error means

![image](https://github.com/mqttjs/MQTT.js/assets/82701276/6f8a9a58-e2a9-4fac-b911-c69e71d6641a)

**Comment by robertsLando** [comment]
Feel free to submit a PR to fix your issue

**Comment by robertsLando** [comment]
Try with v 5.3.6
