### ISSUE TITLE
[Feature/Question]: Exposing _resubscribeTopics

### ISSUE THREAD

**Issue by olso-nordsec** [mqttjs/MQTT.js#1762]
Hi,

When `resubscribe=true`, mqtt instance tracks resubscribe topics internally (hidden behind private field)

It would be helpful, if mqtt instance exposed a method e.g. `getResubscribeTopics()`.

Wdyt?

**Comment by robertsLando** [comment]
I would instead create a getter (without the _ prefix). Would you mind to create a PR?
