### ISSUE TITLE
v5.3.3 throws error building project in ember 4.4

### ISSUE THREAD

**Issue by raj-oeeai** [mqttjs/MQTT.js#1766]
Hi,
I need some help with this Issue.
I am trying to upgrade my ember project from 3.28 to 4.4. 
When I am using 'ember-auto-import' v2.7.1 and 'mqtt' v5.3.3 the project isn't building and throws this error:

 >ERROR in ../tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/app.cjs 24:68-83
 >Module not found: Error: Can't resolve 'mqtt' in '/tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack' 
>resolve 'mqtt' in '/tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack'
>   Parsed request is a module
>   No description file found in /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack or above
>   resolve as module
>     looking for modules in /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules
>       single file module
>         No description file found in /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules or above
>         no extension
>          /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt is not a file
>         .js
>           /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt.js doesn't exist
>          .ts
>          /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt.ts doesn't exist
>         .json
>           /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt.json doesn't exist
>       existing directory /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt
>         using description file: /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt/package.json (relative path: .)
>           using exports field: ./dist/index.js
>             using description file: /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt/package.json (relative path: ./dist/index.js)
>               no extension
>                 /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt/dist/index.js doesn't exist
>               .js
>                 /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt/dist/index.js.js doesn't exist
>               .ts
>                 /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt/dist/index.js.ts doesn't exist
>               .json
>                 /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt/dist/index.js.json doesn't exist
>               as directory
>                 /tmp/broccoli-1kzczpcG70Ypb/cache-532-webpack_bundler_ember_auto_import_webpack/node_modules/mqtt/dist/index.js doesn't exist
>     /tmp/broccoli-1kzczpcG70Ypb/node_modules doesn't exist or is not a directory
>     /tmp/node_modules doesn't exist or is not a directory
>     /node_modules doesn't exist or is not a directory
 
> - building... [ember-auto-import-webpack]
> Build Error (WebpackBundler)
 
> webpack returned errors to ember-auto-import

I was using 'async-mqtt' v2.6.3 with 'ember-auto-import' v1.12.2 before switching to 'mqtt' v5.3.3 with 'ember-auto-import' v2.7.1 .
When I use 'mqtt' v5.2.1 the project builds but throws an error that 'mqtt.connect' is not a function.

**Comment by robertsLando** [comment]
how are you importing mqtt?

**Comment by raj-oeeai** [comment]
> how are you importing mqtt?

I tried to import with  ' import mqtt from "mqtt"; ' & ' import mqtt* from "mqtt"; '
And i tried to import the connect component with ' import { connect } from "mqtt"; '

**Comment by raj-oeeai** [comment]
@robertsLando do you have any idea, why it wont work?

I've also came across the 'precompiled-mqtt' package, but there is no support for async methods since it is based on MQTTjs v4. 
I'm wondering if there's a recommended method or workaround to incorporate 'precompiled-mqtt' into an async environment.

**Comment by raj-oeeai** [comment]
@robertsLando 
 
I encountered a response to this issue in the 'ember-auto-import' repository (https://github.com/embroider-build/ember-auto-import/issues/608#issuecomment-1883208304). Although the project now builds successfully, I'm facing an error when attempting to connect:
```TypeError: (0 , _mqtt.connectAsync) is not a function ```

**Comment by raj-oeeai** [comment]
I found a solution for this issue, the folllowing steps helped me:
1.  ```import * as mqttjs from "mqtt/dist/mqtt.esm"; ```
2. ```const client = await mqttjs.default.connectAsync(mqttHost, mqttOptions, false);```
3. ```const subscribed = await client.subscribeAsync(notificationTopic, { qos: 2 });```

**Comment by raj-oeeai** [comment]
I found a solution for this issue, the folllowing steps helped me:
1.  ```import * as mqttjs from "mqtt/dist/mqtt.esm"; ```
2. ```const client = await mqttjs.default.connectAsync(mqttHost, mqttOptions, false);```
3. ```const subscribed = await client.subscribeAsync(notificationTopic, { qos: 2 });```
