### ISSUE TITLE
MQTT.js Client sends a seemingly invalid Connect Packet

### ISSUE THREAD

**Issue by cyates559** [mqttjs/MQTT.js#1767]
I wrote my own websocket/MQTT server and I've tested it with a few different Websocket client implementations (including my web browser) and **my server is successful at decoding various websocket frames from various client implementations**

However, I am failing to read frames sent over by the MQTT.js client.  The handshake completes, but after the handshake the MQTT.js  client sends over a Frame that starts off with the following two bytes:
```
10000010
10000001
```

This tells me the length of the payload for this Frame is one byte (and there is not a continuation frame)... but one byte is not long enough for an MQTT Packet...  **I'm definitely doing something wrong here or missing something, and would appreciate any help.** I just can't figure out why MQTT.js doesn't work with my server but other clients do work correctly.

Here is an example handshake:
```
GET / HTTP/1.1
Host: localhost:53535
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Accept-Language: en-US,en
Upgrade: websocket
Origin: http://localhost:3000
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Key: DmSqWpH26yEAhdjFZ0EQSw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: mqtt
===== RESPONSE ===============
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: CLvx1naUBQnLZd4OYzxz8irOB/o=
Sec-WebSocket-Protocol: mqtt
Sec-WebSocket-Version: 13
```

Here's a screenshot from my browser's devtools:
<img width="649" alt="image" src="https://github.com/mqttjs/MQTT.js/assets/4196674/6c156c13-6f43-45e8-a887-bb002f871cb9">

**Comment by robertsLando** [comment]
I suggest you to enable debug of mqttjs on browser in order to see a more verbose logs on console:

https://www.npmjs.com/package/debug#browser-support

`localStorage.debug = 'mqttjs*'`

All packets sent from mqttjs are handled by [mqtt-packet](https://github.com/mqttjs/mqtt-packet) and that frames should come from it

**Comment by cyates559** [comment]
Hello All,

Many Thanks for the tips on debugging, I think they helped a bit.

I've figured out that the connect packets (as well as other MQTT packets probably) are being split into multiple websocket frames, they just aren't using the continuation opcode... this all seems mostly fine, I just wasn't expecting this and I've corrected my code to properly account for this... it all works!

Feel free to close the issue, thanks for the help again!

**Comment by phancongchinh** [comment]
@cyates559 Hi, i am facing the same issue that mqtt has sent the connect packet in multiple frames. Could you please clarify what did you do to correct the code? Thanks in advance!

**Comment by cyates559** [comment]
Hi, sorry, coming in late: I didn't get an email for your question @phancongchinh 

I think what you probably need to do is ignore the boundaries of websocket frames and just continue reading more frames.  There will be more than one frame for your connack packet generally and it will not use the continuation opcode.  

my server code (which is not MQTT, I lied, it's really similar though) is here https://github.com/cyates559/mote-broker
