### ISSUE TITLE
Reconnect code not working with createSecureClient

### ISSUE THREAD

**Issue by wolfeidau** [mqttjs/MQTT.js#177]
Been digging into an issue we observed around reconnection. The MQTT client would only reconnect once then stop trying.

Managed to narrow this down to something to do with `createSecureClient` as same code works perfectly with createClient.

So the issue shows up if the server is down for more than one reconnect try or in cases where the server isn't available when the first connect attempt occurs.

Digging into it further now.

**Comment by mcollina** [comment]
This should be fixed in 1.0.0.
