### ISSUE TITLE
It seems that the latest version cannot support WeChat applet and Alipay applet

### ISSUE THREAD

**Issue by onsuper** [mqttjs/MQTT.js#1772]
It seems that the latest version cannot support WeChat applet and Alipay applet

**Comment by robertsLando** [comment]
Add some logs or else describing the error you get

**Comment by onsuper** [comment]
Alipay applet ,Use Last available version : v4.1.0
![image](https://github.com/mqttjs/MQTT.js/assets/44600130/bfea557e-ce76-496b-b8ec-d9a663f010b4)

**Comment by robertsLando** [comment]
Latest available version is 5.3.4

**Comment by onsuper** [comment]
Latest available version is 5.3.4

![image](https://github.com/mqttjs/MQTT.js/assets/44600130/f428a3f8-e064-41db-a9de-896866b3033d)

**Comment by robertsLando** [comment]
I'm sorry but I don't use WeChat and I also don't have a way to test this. I suggest you to open a PR to fix that issue

**Comment by robertsLando** [comment]
Try with 5.3.6
