### ISSUE TITLE
How can I catch the error shown in the screenshot below by using a listener function?

### ISSUE THREAD

**Issue by Shimmers688** [mqttjs/MQTT.js#1774]
I want to catch the errors shown in the screenshot below by using a listener function. But the error callback in mqtt.js and the onerror callback in wsOptions did not catch it. is there anything wrong in the code below?

![image](https://github.com/mqttjs/MQTT.js/assets/88917934/ef7245e8-9dc6-4531-94bd-3f262cd23e49)

here is the code:
```js
const serverIP = '192.168.1.8'
let mqtt_url = `ws://${serverIP}:1884/mqtt`
let mqtt_options = {
  clean: true, 
  connectTimeout: 30 * 1000,
  reconnectPeriod: 1000, 
  wsOptions: {
    onerror: (error) => {
      // After running the code, the console did not print the following message.
      console.log('webSocket connection failed: ', error)
    }
  }
}

const client = mqtt.connect(mqtt_url, mqtt_options)

client.on('connect', () => {
  console.log('connecting to mqtt server successfully')
})

client.on('error', (error) => {
   // After running the code, the console did not print the following message.
   console.log('connecting to mqtt server failed: ', error)
})
```

**Comment by robertsLando** [comment]
wsOptions are only working in node env, in browser we use the global [Websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). Unfortunately browsers don't allow to catch some websocket errors for security reason so this isn't something that we can handle. The only errors you can catch are with client.on('error') and maybe client.stream.on('error').

More details [here](https://github.com/mqttjs/MQTT.js/pull/1732#issuecomment-1804331355)

**Comment by Shimmers688** [comment]
@robertsLando Thanks a lot. For H5 Page, with client.stream.on('error'), I can catch the error. But in Wechat MiniProgram, it still don't work.
![image](https://github.com/mqttjs/MQTT.js/assets/88917934/de619de1-428a-4174-84ff-991ebf109a63)

**Comment by robertsLando** [comment]
WeChat mini uses a different approach, see https://github.com/mqttjs/MQTT.js/blob/main/src/lib/connect/wx.ts#L107

I suggest to do the necessary debug yourself, I cannot help you more then this as I don't use WeChat and also we don't have a plan to keep it maintained

**Comment by Shimmers688** [comment]
ok, thank you again for your helpful reply!

**Comment by robertsLando** [comment]
Feel free to submit a PR in case you find a fix

**Comment by Shimmers688** [comment]
Including stream.emit('error') within the socketTask.onError() listener, then I can catch the error with client.stream.on('error')." 
```js
https://github.com/mqttjs/MQTT.js/blob/c8b6695eec6b541b83f4090ba2cdbbad4ae8f712/src/lib/connect/wx.ts#L85
socketTask.onError((error) => {
    stream.emit('error', new Error('wx.connectSocket: ' + res.errMsg)) // add this line
    const err = new Error(error.errMsg)
    stream.destroy(err)
})
```
![image](https://github.com/mqttjs/MQTT.js/assets/88917934/0b4ec308-455c-4800-a7f4-de058a058f75)
