### ISSUE TITLE
Readme description of createWebsocket does not work in CommonJS

### ISSUE THREAD

**Issue by jsiegenthaler** [mqttjs/MQTT.js#1783]
I have tried to use the createWebsocket example in CommonJS

  const createWebsocket = createWebsocket(url, websocketSubProtocols, options) => {
    const subProtocols = [
      websocketSubProtocols[0],
      'myCustomSubprotocolOrOAuthToken',
    ]
    return new WebSocket(url, subProtocols)
  };

    const connection = await mqtt.connectAsync(<wss url>, {
      ...,
      createWebsocket: createWebsocket,
    });

Using VS Code, the snippet shows that it contains errors. Can you review please?

**Comment by jsiegenthaler** [comment]
I think the first part might need to be:

  const createWebsocket = createWebsocket((url, websocketSubProtocols, options) => {
  const subProtocols = [
  websocketSubProtocols[0],
  'myCustomSubprotocolOrOAuthToken',
  ]
  return new WebSocket(url, subProtocols)
  )};

**Comment by robertsLando** [comment]
That is not how you define a function named `createWebsocket` to pass as argument to the `connect` options

```js
const createWebsocket =  (url, websocketSubProtocols, options) => {
const subProtocols = [
websocketSubProtocols[0],
'myCustomSubprotocolOrOAuthToken',
]
return new WebSocket(url, subProtocols)
};

or:

function createWebsocket(url, websocketSubProtocols, options) {
.....
return new WebSocket(url, subProtocols)
}
 ```


This are Javascript foundamentals, I suggest you to follow an online course

**Comment by jsiegenthaler** [comment]
Hi @robertsLando 
Thanks for your feedback.

This is what is written in the [Readme.](https://github.com/mqttjs/MQTT.js#about-reconnection)
![image](https://github.com/mqttjs/MQTT.js/assets/59387202/3bf678ce-14cf-4cb8-bfc1-3aa0e89b01c0)

Can you please review the example code shown in the Readme. 
It appears to be incorrect.
