### ISSUE TITLE
Update Documentation: Docu out of sync

### ISSUE THREAD

**Issue by hanneslueke** [mqttjs/MQTT.js#1788]
**Is your feature request related to a problem? Please describe.**
While using the latest version i was surprised to see that publishAsync returns something i do not know and don't if i should care.
![image](https://github.com/mqttjs/MQTT.js/assets/152261405/a271c88b-f954-4a01-97a5-17534a29d2f2)

same is true for subscribeAsync but less "severe". instead of the type "granted[]" the type "ISubscriptionGrant[]" is used in the actual code
![image](https://github.com/mqttjs/MQTT.js/assets/152261405/e06a9c47-6eb6-4803-9cb7-7b2164098896)
i

**Describe the solution you'd like**
Either change the code or update the documentation with a little bit of context regarding the returned object.

**Comment by robertsLando** [comment]
Could you submit a PR to fix the docs?
