### ISSUE TITLE
[Bug]: WeChat mini `globalThis` is not defined in browser bundle

### ISSUE THREAD

**Issue by Diven-xinhai** [mqttjs/MQTT.js#1797]
### MQTTjs Version

5.3.6

### Broker

mqtt

### Environment

NodeJS

### Description

The latest version 5.3.6 reported an error in the wechat mini program, the error message is as follows:
TypeError: Cannot read property 'AbortController' of undefined

### Minimal Reproduction

![image](https://github.com/mqttjs/MQTT.js/assets/54425515/474a5662-0e05-49d5-acb7-b2203c85073e)
![image](https://github.com/mqttjs/MQTT.js/assets/54425515/a361258f-7fac-4dc1-a11c-45255624825d)

### Debug logs

.

**Comment by Diven-xinhai** [comment]
![image](https://github.com/mqttjs/MQTT.js/assets/54425515/671e4452-f2d4-430d-810e-45d48d539dab)

**Comment by robertsLando** [comment]
Could you try to add this to the mqttjs bundle?

```
  globalThis = globalThis || {};

```

**Comment by Diven-xinhai** [comment]
> Could you try to add this to the mqttjs bundle?
> 
> ```
>   globalThis = globalThis || {};
> ```

Sorry, I don't quite understand what you mean. Could you please specify where or in which file I should add?

**Comment by robertsLando** [comment]
@Diven-xinhai `node_modules/mqtt/dist/mqtt.esm.js`

**Comment by Diven-xinhai** [comment]
> @Diven-xinhai `node_modules/mqtt/dist/mqtt.esm.js`
> 
> Alternatively you could also try to add that in a script tag in your index.html file

I tried to add globalThis = globalThis || {} in index.html or mqtt.esm.js; But it didn't work. It's the same error

**Comment by robertsLando** [comment]
The problem is that for some reason when you are running this in wechat mini `globalThis` is not defined (it should be in all browsers BTW) so you should try fixing it within your bundle someway because I don't have a way to test this out

**Comment by timzaak** [comment]
MQTTjs Version
5.3.6

```TypeError: Cannot set property 'AbortSignal' of undefined```

Another issue about this is https://github.com/NervJS/taro/issues/15580

**Comment by robertsLando** [comment]
@timzaak I don't use wechat and I also have no way to test this so please feel free to open a PR to fix this issue.

**Comment by timzaak** [comment]
> @timzaak I don't use wechat and I also have no way to test this so please feel free to open a PR to fix this issue.

@robertsLando  I solved this by `import 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'` before import mqtt

but can not find where use `new Blob()`,  Wechat miniprogram do not support Blob, it should be replaced by ArrayBuffer.


![image](https://github.com/mqttjs/MQTT.js/assets/6149407/5194b999-0d1a-41a0-935e-e6174e47854c)

**Comment by robertsLando** [comment]
@timzaak You can disable using worker timer with `timerVariant` option

**Comment by timzaak** [comment]
> @timzaak You can disable using worker timer with `timerVariant` option

@robertsLando That works. Thanks

**Comment by shushenghong** [comment]
引入了`import "abortcontroller-polyfill/dist/abortcontroller-polyfill-only";` 还是报错

`TypeError: Cannot destructure property 'AbortController' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.`

**Comment by timzaak** [comment]
在项目最开始初始化的地方引入。 app.ts or main.ts

**Comment by shushenghong** [comment]
你用哪个版本的mqtt.js，我这试了还不行，引入了 `SyntaxError: Unexpected token ; onabort; `打包会报错， `SyntaxError: Unexpected token ; onabort; `

**Comment by timzaak** [comment]
"mqtt": "5.7.3"

**Comment by robertsLando** [comment]
Starting from next MQTTjs version you will need another polifilly in order to make it work with WeChat. See [docs](https://github.com/mqttjs/MQTT.js#wechat-mini-program)

**Comment by robertsLando** [comment]
@hoIIer see new docs: https://github.com/mqttjs/MQTT.js#wechat-mini-program
