### ISSUE TITLE
[Bug]: Only last message is send when Connecting with multiple retain Topics

### ISSUE THREAD

**Issue by kellergoech** [mqttjs/MQTT.js#1814]
### MQTTjs Version

5.3.6

### Broker

Mosquitto

### Environment

NodeJS

### Description

When using MQTT.js in react i get the problem that when connecting to multiple topics which are set retain, I only get the message from the last subcribed retain topic. Afterwards the connection works fine, when I create multiple instaces it also works fine from the beginning.
Maybe the problem could also be in the wrapper but it is only mapping the variables to MQTT.js:

```
this.client.on('connect', function (){

            for (var i = 0; i < topics.length; i++) {
                self.client.subscribe(topics[i]);
            }

            self.props.setProps({
                state: {
                    connected: true,
                    reconnecting : false
                }
            })
            
        })
```

### Minimal Reproduction

I am using a react wrapper around the MQTT.js to be able to use it in Plotly Dash.
[https://github.com/kellergoech/dash-mqtt](url)

I am using followin code to test it in Python with a local Mosquitto docker instance:

```
import dash_mqtt
import dash
from dash.dependencies import Input, Output, State
from dash import html
from dash import dcc

TEST_SERVER = 'localhost'
TEST_SERVER_PORT = 9001
TEST_SERVER_PATH = 'mqtt'
MESSAGE_OUT_TOPIC = 'testtopic'
MESSAGE_IN_TOPIC1 = 'testtopic1'
MESSAGE_IN_TOPIC2 = 'testtopic2'

app = dash.Dash(__name__)

app.layout = html.Div([
    dash_mqtt.DashMqtt(
        id='mqtt',
        options={"username": "admin", "password": "password"},
        broker_url=TEST_SERVER,
        broker_port = TEST_SERVER_PORT,
        broker_path = TEST_SERVER_PATH,
        topics=[MESSAGE_IN_TOPIC1, MESSAGE_IN_TOPIC2]
    ),
    html.H1('MQTT echo'),
    html.P('MQTT echo server to ' + TEST_SERVER + ' on port ' + str(TEST_SERVER_PORT)),
    dcc.Input(
        id='message_to_send',
        placeholder='message to send',
        debounce = True),
    html.Button('Send',id='send'),
    html.Div(id='return_message')
])


@app.callback(
        Output('mqtt', 'message'),
        Input('send', 'n_clicks'),
        State('message_to_send', 'value')
    )
def display_output(n_clicks, message_payload):
    if n_clicks and n_clicks>0:
        return {
            'topic': MESSAGE_OUT_TOPIC,
            'payload' : message_payload,
            'retain' : "True",
            'qos' : 1
        }
    return dash.no_update


@app.callback(
    Output('return_message', 'children'),
    Input('mqtt', 'incoming')
)
def display_incoming_message(incoming_message):
    if incoming_message:
        return incoming_message['payload']
    else:
        return dash.no_update


if __name__ == '__main__':
    app.run_server(debug=True)
```

### Debug logs

There are no NodeJS logs because the Wrappe is compiled for Python Dash.

**Comment by robertsLando** [comment]
@kellergoech I have multiple clients subscribing to multiple topics and receiving all the retained messages. Your code snippet is incomplete as the `message` event part is missing, also I suggest to add a callback to subscriptions to see if them succeed. 

Also you are using it on React so the environment is browser not Nodejs. I suggest you to try creating a base script that firstly publish 2 retain messages in 2 random topics and then it subscribes to those topics, you will see you can receive both messages then

**Comment by kellergoech** [comment]
Hello robertsLando,

Thanks for the answer, I was also thinking that i am missing something in my Code but I am unsre what it is, here the snippet where I get the messages:

```
 this.client.on('message', function (topic, payload, packet){

            let my_payload = payload;
            if (Buffer.isBuffer(payload)){
                my_payload = payload.toString();
            }
            self.props.setProps({
                incoming:{
                    topic: topic,
                    payload: my_payload,
                    packet: packet
                }
            })
        })
```
