### ISSUE TITLE
[Bug]: Issues With Chrome and WSS

### ISSUE THREAD

**Issue by juancirino23** [mqttjs/MQTT.js#1815]
### MQTTjs Version

frrom cdn

### Broker

private

### Environment

Browser

### Description

Hi Iam having an issue that just poped up. Iam using the cdn version and all was working well and out of no where I started having issues.
Basically when I try to establish a conection to my mqtt broker via wss on chrome i get  conection failed. But if I go into incognito mode it connects perfectly.
Could some one help me out?

### Minimal Reproduction

-

### Debug logs

-

**Comment by robertsLando** [comment]
I need some more details about your error in order to help you debug this

**Comment by juancirino23** [comment]
Hi sure, what info could I provide? 
the certificates are provided by a valid ca auth

**Comment by robertsLando** [comment]
@juancirino23 For exmaple I need mqttjs version and some logs output. In order to see logs go to verbose channel on chrome or set `log: console.log.bind(console)` in mqttjs connect options

**Comment by juancirino23** [comment]
ok
![image](https://github.com/mqttjs/MQTT.js/assets/93710242/c1d1bd19-2380-4324-a35f-8739f73feaa3)

Regarding mqttjs version Iam using CDN from  https://unpkg.com/mqtt/dist/mqtt.min.js I dont know what version is uploaded there.

**Comment by robertsLando** [comment]
@juancirino23 Could you expand the error you get on console? It should tell you the real reason why the connection has been aborted

**Comment by juancirino23** [comment]
![image](https://github.com/mqttjs/MQTT.js/assets/93710242/8f3528a7-9432-404e-8e92-3b9070ed07aa)
it doesnt really say anything

**Comment by robertsLando** [comment]
try to go to error tab to see if you can get more informations about the error, usually the error is not exposed on js side but it is on dev console

**Comment by juancirino23** [comment]
same thing
![image](https://github.com/mqttjs/MQTT.js/assets/93710242/022f1527-6db4-476f-819d-ee2be2b236a3)

**Comment by juancirino23** [comment]
The most interesting thing is if I go into incognito mode in conects fine

**Comment by robertsLando** [comment]
@juancirino23 Yeah I remember you  told me that, did you tried to clear cookies and else? Maybe try with firefox or another browser to see if it works there? I think this is something very specific to your browser

**Comment by juancirino23** [comment]
I have
firefox it works fine
brave it works fine
Edge doesnt work
Opera doesnt work
I have clear cookies cache
I have tried on multiple computer that have never connected to the system and none can connect.

**Comment by robertsLando** [comment]
I wish to be able to help you further but I rn foeed to know more details about the error, If the connecction doesn't even arrive to your broker it means it's the browser that is blocking it for some reason... I'm using mqttjs on browser with wss in many projects without issues

**Comment by juancirino23** [comment]
Question, is there a way to say like dont verify peer.
Iam asking this because for example in MQTTX program iam conenct via wss but if I turn off SSL secure.
I think the problem can be along this lines.
Could you guide me a bit

**Comment by juancirino23** [comment]
OK, I think I solved it. The issue is not a SSL or library from what Iam seeing something changed in chrome in regards to cookie size and length and that is causing the issue with the handshake. Iam runnig Laravel 8 framwork maybe in newer versions its solved.
Thanks for the help.

**Comment by robertsLando** [comment]
🙌🏻

**Comment by xiduzo** [comment]
I am facing the same issue right now. The client can connect fine to some `wss` endpoints but not to mine hosted in docker, I guess this has to do something with the broker configuration? I opened https://stackoverflow.com/questions/78162170/mqtt-over-tls-using-mqtt-js and from what I can see from the logging it seems to be related to https://stackoverflow.com/a/19305172/4655177

**Comment by juancirino23** [comment]
from what Iam seeing in your example your not passing in the connect the right way
here is my example

const broker="37.97.203.138"
const port=8084
const client_id=jojo_Math.random().toString(36).substring(7)
const username="YOUR USER NAME"
const password="YOUR PASSWORD"
const proto="wss"
var client = mqtt.connect({
        hostname: broker,
        port: port,
        clientId: clientId,
        username: username,
        password: password,
        protocol: proto,
        keepalive:10,
    });
    if your certificates are selfsigned you need to load it into your browser other wise it wont work. With this config I was able to connect to every wss mqtt I have
    The issue I was having is something regarding laravel + chrome with cookie size.

**Comment by xiduzo** [comment]
I can connect using MQTTX

![image](https://github.com/mqttjs/MQTT.js/assets/4045216/f95e8d83-2f77-4669-a90e-1938cfee1524)

And on the broker, I see the logging appear

```
1710449309: New client connected from <my_home_ip>:49823 as mqttx_b4c2e777 (p5, c1, k60, u'username').
1710449309: No will message specified.
1710449309: Sending CONNACK to mqttx_b4c2e777 (0, 0)
```

I can even pub/sub

![image](https://github.com/mqttjs/MQTT.js/assets/4045216/58e98e9e-ab25-42a7-b105-794add4a41a5)

**Comment by juancirino23** [comment]
I dont know the username and password your using but the code snipet I sent you, should be able to connect just fine.

**Comment by xiduzo** [comment]
the username and password are 🥁🥁🥁 username : password (yeah yeah not secure but I'll ditch them once the issue is resolved 😅)

I am serving from localhost but connecting to `wss://public:public@public.cloud.shiftr.io` works just fine. Also when serving the example from GitHub-pages (https) the issue still remains

**Comment by juancirino23** [comment]
Wierd your not getting an error of cross-origin  Iam never able to connect from a localhost to wss does anything reach docker from your page? did you try a tcpdump to see what reaching you. Also if you do from your localhost to your broker http localhost and your broker on ws does that connect? Also

**Comment by juancirino23** [comment]
Your getting packets. Did you try with firefox or brave?

**Comment by xiduzo** [comment]
Still unable to connect on firefox but I get a slightly different error. In chrome I get the `CloseEvent` with code `1006` while in Firefox the code is `1015`

![image](https://github.com/mqttjs/MQTT.js/assets/4045216/9285d566-ccf9-4baa-aa65-102caf2c3684)

**Comment by xiduzo** [comment]
```python
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, reason_code, properties):
    print(f"Connected with result code {reason_code}")
    client.subscribe("$SYS/#")

def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))

mqttc = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)

mqttc.tls_set(tls_version=mqtt.ssl.PROTOCOL_TLSv1_2, cert_reqs=mqtt.ssl.CERT_NONE)

mqttc.tls_insecure_set(True)
mqttc.username_pw_set("username", password="password")

mqttc.on_connect = on_connect
mqttc.on_message = on_message

mqttc.connect("37.97.203.138", 8883, 60)

mqttc.loop_forever()
```

This python script can connect properly to `mqtts`. It seems like the only issue is to connect to `wss` for some reason...

**Comment by xiduzo** [comment]
According to https://stackoverflow.com/a/78165535/4655177 `When using MQTT over WebSockets in the browser, the browser handles ALL the TLS work.` which means we can **not** `rejectUnauthorized` in the browser.

I was using a self-signed certificate and moving over to [letsencrypt](https://letsencrypt.org/) all works fine and dandy now!

I used https://medium.com/himinds/mqtt-broker-with-secure-websocket-using-traefik-docker-compose-and-lets-encrypt-2b8e32207555 to set-up the docker containers and routing `wss` via `traefik`.

Thanks for all other help @juancirino23 ❤️
