### ISSUE TITLE
[Bug]: nodejs 20.11.1 (from debian 12)  + mqtt 5.4.0 allways get connack timeout in connection

### ISSUE THREAD

**Issue by alfredopons** [mqttjs/MQTT.js#1822]
### MQTTjs Version

5.4.0

### Broker

MyQttHub

### Environment

NodeJS

### Description

nodejs 20.11.1 (from debian 12)  + mqtt 5.4,0 allways get connack timeout in connection.
If you use mqtt 5.3.6 works perfect. If you upgrade to 5.4.0, then not work

### Minimal Reproduction

Upgrade you mqtt to 5.4.0 & runs over nodejs 20.11

### Debug logs

  mqttjs connecting to an MQTT broker... +0ms
  mqttjs:client MqttClient :: version: undefined +0ms
  mqttjs:client MqttClient :: environment node +1ms
  mqttjs:client MqttClient :: options.protocol mqtts +0ms
  mqttjs:client MqttClient :: options.protocolVersion 4 +0ms
  mqttjs:client MqttClient :: options.username api_kioskera +0ms
  mqttjs:client MqttClient :: options.keepalive 60 +0ms
  mqttjs:client MqttClient :: options.reconnectPeriod 1000 +0ms
  mqttjs:client MqttClient :: options.rejectUnauthorized true +0ms
  mqttjs:client MqttClient :: options.properties.topicAliasMaximum undefined +0ms
  mqttjs:client MqttClient :: clientId API_KIOSKERA +1ms
  mqttjs:client MqttClient :: setting up stream +0ms
  mqttjs:client connect :: calling method to clear reconnect +2ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client connect :: using streamBuilder provided to client to create stream +0ms
  mqttjs calling streambuilder for mqtts +6ms
  mqttjs:tls port 8883 host node02.myqtthub.com rejectUnauthorized %b true +0ms
  mqttjs:client connect :: pipe stream to writable stream +48ms
  mqttjs:client connect: sending packet `connect` +2ms
  mqttjs:client _writePacket :: packet: {
  mqttjs:client   cmd: 'connect',
  mqttjs:client   protocolId: 'MQTT',
  mqttjs:client   protocolVersion: 4,
  mqttjs:client   clean: true,
  mqttjs:client   clientId: 'API_KIOSKERA',
  mqttjs:client   keepalive: 60,
  mqttjs:client   username: 'user_demo',
  mqttjs:client   password: 'pass_demo',
  mqttjs:client   properties: undefined
  mqttjs:client } +0ms
  mqttjs:client _writePacket :: emitting `packetsend` +3ms
  mqttjs:client _writePacket :: writing to stream +0ms
  mqttjs:client _writePacket :: writeToStream result true +37ms
  mqttjs:client !!connectTimeout hit!! Calling _cleanUp with force `true` +4s
  mqttjs:client _cleanUp :: forced? true +0ms
  mqttjs:client _cleanUp :: (API_KIOSKERA) :: destroying stream +1ms
  mqttjs:client _cleanUp :: client not disconnecting/reconnecting. Clearing and resetting reconnect. +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client _setupReconnect :: emit `offline` state +0ms
  mqttjs:client _setupReconnect :: set `reconnecting` to `true` +0ms
  mqttjs:client _setupReconnect :: setting reconnectTimer for 1000 ms +0ms
  mqttjs:client (API_KIOSKERA)stream :: on close +1ms
  mqttjs:client _flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function +0ms
  mqttjs:client stream: emit close to MqttClient +0ms
  mqttjs:client close :: connected set to `false` +0ms
  mqttjs:client close :: clearing connackTimer +0ms
  mqttjs:client close :: clearing ping timer +0ms
  mqttjs:client close :: calling _setupReconnect +0ms
  mqttjs:client _setupReconnect :: doing nothing... +0ms
  mqttjs:client reconnectTimer :: reconnect triggered! +1s
  mqttjs:client _reconnect: emitting reconnect to client +1ms
  mqttjs:client _reconnect: calling connect +0ms
  mqttjs:client connect :: calling method to clear reconnect +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client connect :: using streamBuilder provided to client to create stream +0ms
  mqttjs calling streambuilder for mqtts +5s
  mqttjs:tls port 8883 host node02.myqtthub.com rejectUnauthorized %b true +5s
  mqttjs:client connect :: pipe stream to writable stream +1ms
  mqttjs:client connect: sending packet `connect` +0ms
  mqttjs:client _writePacket :: packet: {
  mqttjs:client   cmd: 'connect',
  mqttjs:client   protocolId: 'MQTT',
  mqttjs:client   protocolVersion: 4,
  mqttjs:client   clean: true,
  mqttjs:client   clientId: 'API_KIOSKERA',
  mqttjs:client   keepalive: 60,
  mqttjs:client   username: 'user_demo',
  mqttjs:client   password: 'pass_demo',
  mqttjs:client   properties: undefined
  mqttjs:client } +0ms
  mqttjs:client _writePacket :: emitting `packetsend` +0ms
  mqttjs:client _writePacket :: writing to stream +1ms
  mqttjs:client _writePacket :: writeToStream result true +0ms

**Comment by robertsLando** [comment]
@alfredopons What are the options you pass to create the client?

**Comment by alfredopons** [comment]
Hi @robertsLando ,

`const tlsOptions = {
  rejectUnauthorized: true
};

// Connection options
const options = {
  connectTimeout: 4000,
  // USe TLS
  ...tlsOptions,
  host: host,
  port: 8883,
  username: username,
  password: password,
  clientId: deviceId
};`

**Comment by alfredopons** [comment]
Hi, I try to put 10 seconds. 

But the problem is not the timeout, the problem is that with version 5.5.0 it does not connect. With 10 seconds, the problem is still the same.

With the 5.3.5 library it works fine, the client connects to the mqtt broker instantly.

**Comment by robertsLando** [comment]
There is nothing on your logs that tells me what's going on there, I just see that the connect packet is sent and the connect doesn't arrive so the connack timeout triggers, closes the client and restarts the client. 

Could you provide me a script to reproduce the issue?
