### ISSUE TITLE
[Bug]: on reconnect after regaining internet, will loop forever disconnecting after reconnecting

### ISSUE THREAD

**Issue by mikelpr** [mqttjs/MQTT.js#1825]
### MQTTjs Version

5.4.0

### Broker

aws-iot

### Environment

NodeJS

### Description

whenever internet access is lost and then recovered, mqttjs loops reconnecting and immediately disconnecting (emits `offline`, then `close`) after `connect` is fired. does this forever.

this does not happen on aws-crt (which I'm trying to move away from, for other reasons)

### Minimal Reproduction

1. connect to the mqtt broker
2. disconnect internet
3. wait for ENETUNREACH
4. reconnect internet

### Debug logs

```
{"type":"connection","isConnected":true,"event":"reconnect"}
{"type":"connection","isConnected":true,"event":"connect","packet":{"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":false,"returnCode":0}}
{"type":"connection","isConnected":false,"event":"offline"}
{"type":"connection","isConnected":false,"event":"close"}
```

(`type: "connection"` and `isConnected` are for my internal use)

**Comment by robertsLando** [comment]
@mikelpr Just to know, is this a regression? Does it used to work in some previous version?

**Comment by mikelpr** [comment]
@robertsLando it didn't work on async-mqtt@2.6.2 either which used mqtt@^4.1.0, that's why we originally moved to aws-crt but it's giving us nightmares in different departments and we'd like to move back to mqttjs since it works on browsers

**Comment by mikelpr** [comment]
Also, I noticed that handling reconnection myself after getting a keepalive timeout error works

**Comment by robertsLando** [comment]
@mikelpr Could you provide me a simple reproduction script? Does this happens only with aws-iot broker or also with others?
