### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by MaximoLiberata** [mqttjs/MQTT.js#1837]
# Error: Cannot create URL for blob!

**located**: src/lib/client.ts
 **method**: _setupPingTimer
  **class**: PingTimer
   **init**: getTimer(variant) = getTimer('auto')

## Description:

The error is caused for the library `worker-timers` when the class `PingTimer` call `getTimer('auto')` method. This method `getTimer` doesn't recognize it's executed in ReactNative (RN), it know it's executed in a browser, but RN implements its own timers as: `setTimeOut`, `setInterval`, etc., when is called the method `workerTimer` instead `nativeTimer` the library `worker-timers` that implement `Blob` to store data or whatever it does, throw the next error: **[Error: cannot create URL for blob!]**, `Blob` it isn't supported by RN.

## Fix:

To support ReactNative (RN) it's necessary install 2 package additionals to RN projects:

- [buffer](https://www.npmjs.com/package/buffer)
- [url](https://www.npmjs.com/package/url)

Also include the next code at beginning of the program:

`
process.nextTick = (callback) => {
	setTimeout(callback, 0)
}
`

## Conclusion

I have the commit of the fix of this bug, please @robertsLando allow me create a PR and show you my solution.

I will attach my mqtt client connection and the files I changed in this package to fix the bug:

[mqtt_client_example.txt](https://github.com/mqttjs/MQTT.js/files/14898370/mqtt_client_example.txt)
[is-browser.txt](https://github.com/mqttjs/MQTT.js/files/14898380/is-browser.txt)
[get-timer.txt](https://github.com/mqttjs/MQTT.js/files/14898379/get-timer.txt)
[shared.txt](https://github.com/mqttjs/MQTT.js/files/14898381/shared.txt)
[BufferedDuplex.txt](https://github.com/mqttjs/MQTT.js/files/14898382/BufferedDuplex.txt)

**Comment by robertsLando** [comment]
Feel free to open the PR, anyway this could be fixed easily by using `timerVariant: 'native'` in connect options

**Comment by MaximoLiberata** [comment]
I think so, also I made the changes in that way because if isn't imported `Buffer` library, later I need to put `Buffer` library in the global scope in RN projects, something like this:

`Object.assign(global, { Buffer: require('buffer').Buffer });`
 
This is the PR #1840

**Comment by MaximoLiberata** [comment]
This issue was fixed in (#1840)[https://github.com/mqttjs/MQTT.js/pull/1840]
