### ISSUE TITLE
[Bug]: Websocket is not defined

### ISSUE THREAD

**Issue by allan-d-g** [mqttjs/MQTT.js#1844]
### MQTTjs Version

5.5.2

### Broker

mosquitto

### Environment

NodeJS

### Description

Getting following error:

socket = new WebSocket(url, [websocketSubProtocol])
		^
ReferenceError: WebSocket is not defined
    at createBrowserWebSocket (/../node_modules/mqtt/src/lib/connect/ws.ts:135:3)

### Minimal Reproduction

Install latest version in nodejs (typescript) project.
Connecting with followig code:
const client = connect("mqtt://test.mosquitto.org");

### Debug logs

/home/allan/git/ci-backend/node_modules/mqtt/src/lib/connect/ws.ts:135
		socket = new WebSocket(url, [websocketSubProtocol])
		^

ReferenceError: WebSocket is not defined
    at createBrowserWebSocket (/home/allan/git/ci-backend/node_modules/mqtt/src/lib/connect/ws.ts:135:3)
    at Object.browserStreamBuilder (/home/allan/git/ci-backend/node_modules/mqtt/src/lib/connect/ws.ts:171:17)
    at MqttClient.wrapper (/home/allan/git/ci-backend/node_modules/mqtt/src/lib/connect/index.ts:171:34)
    at MqttClient.connect (/home/allan/git/ci-backend/node_modules/mqtt/src/lib/client.ts:733:22)
    at MqttClient (/home/allan/git/ci-backend/node_modules/mqtt/src/lib/client.ts:677:9)
    at connect (/home/allan/git/ci-backend/node_modules/mqtt/src/lib/connect/index.ts:173:17)
    at MessageBroker.init (/home/allan/git/ci-backend/src/business_layer/services/utils/message-broker.util.ts:16:21)
    at Setup.setupRepositories (/home/allan/git/ci-backend/src/business_layer/index.ts:47:27)

**Comment by robertsLando** [comment]
Based on the error it seems that you are using mqttjs on nodejs but it tried to load the browser code to init the websocket. Could you show me how you are initing the client please and also attach debug logs by adding `DEBUG=mqttjs*` env var?

**Comment by allan-d-g** [comment]
Yes I'm using mqtt on nodejs.

My code:
``
import { connect } from "mqtt";

const client = connect("mqtt://test.mosquitto.org");

client.on("connect", () => {
        console.log("connected");
     });
``
Debug log:
mqttjs connecting to an MQTT broker... +0ms
  mqttjs:client MqttClient :: version: 2.0.0 +0ms
  mqttjs:client MqttClient :: environment browser +1ms
  mqttjs:client MqttClient :: options.protocol ws +0ms
  mqttjs:client MqttClient :: options.protocolVersion 4 +0ms
  mqttjs:client MqttClient :: options.username undefined +0ms
  mqttjs:client MqttClient :: options.keepalive 60 +0ms
  mqttjs:client MqttClient :: options.reconnectPeriod 1000 +0ms
  mqttjs:client MqttClient :: options.rejectUnauthorized undefined +0ms
  mqttjs:client MqttClient :: options.properties.topicAliasMaximum undefined +0ms
  mqttjs:client MqttClient :: clientId mqttjs_02ecbf9c +0ms
  mqttjs:client MqttClient :: setting up stream +0ms
  mqttjs:client connect :: calling method to clear reconnect +1ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client connect :: using streamBuilder provided to client to create stream +0ms
  mqttjs calling streambuilder for ws +3ms
  mqttjs:ws browserStreamBuilder +0ms

Your right, from the debug log it shows that it is loading the browser code.
Is there any way to tell it that it shouldn't? I tried to look through the documentation but couldn't find it.

**Comment by robertsLando** [comment]
> mqttjs:client MqttClient :: version: 2.0.0 

I don't think that's correct...

**Comment by allan-d-g** [comment]
Regarding the version. 
As I can see, it, this line in the mqtt library:

`public static VERSION = process.env.npm_package_version`

takes the version field of my projects package.json file.

{
  "name": "my-project",
  "version": "2.0.0",
  "description": "my-project version 2",
  "main": "server.ts",
...

If I change my version number, the value in the debug log changes with it.

**Comment by robertsLando** [comment]
Yeah I just pushed a fix for that on master. What triggers me is:

> mqttjs:client MqttClient :: environment browser +1ms

This should be NodeJS and I tried to run it on my side and it's detecting it correctly (also tests would fail in that case).

**Comment by robertsLando** [comment]
Could you put a debbuger in the is-browser.ts file to check what is actually making mqtt detecting your app as a browser? Are you patching globals someway?

**Comment by allan-d-g** [comment]
Thanks @robertsLando for pointing me in the right direction.
I have a leaflet library that is patching globals, to be able to generate leaflet map in nodejs.
If I disable this library, mqtt is working fine, and evironment is detected as nodejs.
