### ISSUE TITLE
Expose connection errors to clients

### ISSUE THREAD

**Issue by curtispd** [mqttjs/MQTT.js#185]
I'm using mqtt#createSecureClient to create a client, and I would like to log connection errors when it fails to connect to the MQTT server. There doesn't appear to be a clean way to do this because the client is eating connection errors in MqttClient.prototype._setupStream:

  // Suppress connection errors
  this.stream.on('error', nop);

Would it be wrong to re-emit errors to the client? I'm able to add an error handler to the client's stream directly, but this is awkward because it creates a new stream on re-connect after a failure, so I have to listen for this and keep adding the handler on the new streams as they are created.

**Comment by arturi** [comment]
Hey! Since the API changed from ```createClient``` to ```client```, trying to catch the error:

```
var mqtt = require('mqtt');
var mqttClient = mqtt.connect({
  host: 'localhost',
  port: 1883,
  username: config.mqttCredentials.username,
  password: config.mqttCredentials.password
});
mqttClient.on('error', function(err) {
  console.log(err);
});
```

Error event is not emitted, it throws:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/var/koti-new/node_modules/mqtt/lib/client.js:665:9)
    at MqttClient._handlePacket (/var/koti-new/node_modules/mqtt/lib/client.js:273:12)
    at process (/var/koti-new/node_modules/mqtt/lib/client.js:196:12)
    at Writable.writable._write (/var/koti-new/node_modules/mqtt/lib/client.js:206:5)
    at doWrite (/var/koti-new/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/var/koti-new/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/var/koti-new/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
```

What should I do? Thanks.

**Comment by mcollina** [comment]
That code should work, see https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L670-L671.

**Comment by arturi** [comment]
Thanks! Tried again now and it works:

```
var mqtt = require('mqtt');
var mqttClient = mqtt.connect('mqtts://example.com', {
  username: '123',
  password: '123',
  rejectUnauthorized: false
});
mqttClient.on('error', function(err) {
  console.log(err);
});
mqttClient.on('connect', function() {
  console.log('I am connected!');
});
```

Don’t know why it was’t able to catch it before. But with the cli it throws an error (which is fine, I guess, but I expected a simple error message):

```mqtt pub -t '/something' -h 'example.com' -C 'mqtts' -u '123' -P '123' -m 'something' --insecure```

**Comment by chris-kruining** [comment]
I seem to have the same problem, And I'm not sure how to fix it.
```js
let client = mqtt.connect('mqtts://mqtt.domain.tld:1885', {
    reconnectPeriod: 5000,
    will: {
        topic: 'game-over',
        payload: sessionId,
        qos: 2,
        retain: true,
    }
});

client.stream.on('error', () => client.end());

client.on('connect', () => {
    client.subscribe(sessionId, {
        qos: 2,
    });
});
```
When for example the broker is down I get an error in the console, which I of course want to catch and write logic to handle such exceptions. However the error event on the client is not triggered at all, the error event on the stream is only triggered once and it doesn't prevent the error being written to the console at all. So to prevent an overloaded console with the some error I now simply cancel the connection to the server. Is there a way for me to catch such errors, because like I said, I would like to have some logic to handle these situations :D

**Comment by samuelcotterell** [comment]
Any updates here??? I am getting the same issue where connection errors are not being caught by 
client.on("error") handler

**Comment by jakkso** [comment]
@chris-kruining Did you ever figure it out?

I'm also having an issue catching some errors.  I'm using a version for the following:

`client.on('error', (err) => {
  // Handle errors here
})
`

This approach  catches an connection refused: not authorized error, but not, for example, the following error:

 `WebSocket connection to ... failed: Error in connection establishment: net::ERR_INTERNET_DISCONNECTED
WebSocketStream @ stream.js:61
createWebSocket @ ws.js:55
buildBuilderBrowser @ ws.js:83
wrapper @ index.js:144
push../node_modules/mqtt/lib/client.js.MqttClient._setupStream @ client.js:271
push../node_modules/mqtt/lib/client.js.MqttClient._reconnect @ client.js:735
(anonymous) @ client.js:752`

How should I go about catching this type of error?

**Comment by chris-kruining** [comment]
@jakkso No not really, we kind of 'solved' it by making sure the up-time of the broker is okay...

I still use the same error event code (which for as far as I know doesn't work) :: `client.stream.on('error', e => client.end());`
