### ISSUE TITLE
[Bug]: MQTT connection getting offline while running in React Native.

### ISSUE THREAD

**Issue by Shahanshah-TA** [mqttjs/MQTT.js#1857]
### MQTTjs Version

5.5.5

### Broker

mosquitto

### Environment

React Native

### Description

I am trying to implement this in React Native. But its getting `offline` status only and then it get `close` and start `reconnect`.
I have also install `url` and `buffer` as dependencies.
My `package.json` dependencies
```
   "buffer": "^6.0.3",
    "mqtt": "^5.5.5",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "url": "^0.11.3"
```

### Minimal Reproduction

```
  const client = mqtt.connect({
      port: 1883,
      host: 'test.mosquitto.org',
      protocol: 'mqtt',
      clientId: 'mqttjs_12dsjfbsdkj',
      clean: true,
      keepalive: 120,
      reconnectPeriod: 5000,
    });
    client.on('connect', () => {
      console.log('connected with mqtt');
    });
    client.on('error', () => {
      console.log('error with mqtt');
    });
    client.on('reconnect', () => {
      console.log('reconnect with mqtt');
    });
    client.on('offline', () => {
      console.log('offline with mqtt');
    });
    client.on('close', () => {
      console.log('close with mqtt');
    });
    client.on('disconnect', () => {
      console.log('disconnect with mqtt');
    });

    client.on('message', (topic, message) => {
      console.log('message with mqtt');
      // client.end();
    });
```

### Debug logs

 Log from `console.log`
 LOG  offline with mqtt
 LOG  close with mqtt
 LOG  reconnect with mqtt
 LOG  close with mqtt
 LOG  reconnect with mqtt

**Comment by robertsLando** [comment]
Cannot reproduce

**Comment by Shahanshah-TA** [comment]
Hi @robertsLando 
Thank you for your reply.
Hope you are doing great.
I tried the repo mentioned in documentation with Expo https://github.com/MaximoLiberata/react-native-mqtt.js-example
Apart from that I am adding my sample public repo with Bare React Native with which I am not able get the `connected` status https://github.com/Shahanshah8791/MQTT 
Please have a look, its bit necessary for me, maybe I am missing something, I tried multiple things.
Thank you

**Comment by Shahanshah-TA** [comment]
@MaximoLiberata please help me with this.

**Comment by abdelhameedhamdy** [comment]
@Shahanshah-TA Make sure that your broker connection is good, or try using different port over websocket, you have different port options in mosquito server, give a try with e.g. 8081.

**Comment by abdelhameedhamdy** [comment]
@Shahanshah-TA As per your example, you might forget to pass the broker url to the connect function.

It should be like this,
```
const client = connect(url, mqttOptions);
```

**Comment by MaximoLiberata** [comment]
I got those connection logs when the connection wasn't established with the correct form, the broker closed my client connection, because some policy or the parameters that I sent.

**Comment by MaximoLiberata** [comment]
I modified [React Native Example](https://github.com/MaximoLiberata/react-native-mqtt.js-example) to fix these errors, try with the last commit and config your environment variables with the follow:

EXPO_PUBLIC_TZ = "UTC"
EXPO_PUBLIC_MQTT_HOST = "test.mosquitto.org"
EXPO_PUBLIC_MQTT_PORT = 8080
EXPO_PUBLIC_MQTT_PORT_SSL = 8081
EXPO_PUBLIC_MQTT_SSL = true
EXPO_PUBLIC_MQTT_VERSION  = 4
EXPO_PUBLIC_MQTT_QOS = 0
EXPO_PUBLIC_MQTT_USERNAME = ""
EXPO_PUBLIC_MQTT_PASSWORD = ""
EXPO_PUBLIC_MQTT_TOPICS = "#"

**Comment by Shahanshah-TA** [comment]
Hi @MaximoLiberata Thank you for response and time.
I tried the latest code and its working fine for me now.
While I was trying to run the code for first time there were some missing dependencies in `package.json` (maybe I am not that much familiar with expo but I think `@react-navigation/native` requires this two packages).
`react-native-screens react-native-safe-area-context` 
And I face this one also https://github.com/software-mansion/react-native-reanimated/issues/4538 , so added few packages as dev dependencies from [here](https://github.com/software-mansion/react-native-reanimated/blob/2426f32095af417f1cfc1789479c3d2ee7c72e18/package.json#L86-L95).
Again thank you for response guys.
