### ISSUE TITLE
Exposing reconnection attempts and errors

### ISSUE THREAD

**Issue by jeloou** [mqttjs/MQTT.js#186]
Hey guys, 

I see an issue (#108) mentioning the option `reconnectAttempts`, but it seems missing now. Also, no event is triggered when the client is trying to reconnect or when it fails. I just added those features to my [fork] (https://github.com/jeloou/MQTT.js/commit/c82d6b3728dcd9b06750f25cbcedd3764a13738e), maybe it can be merged, but couldn't find any contribution rules.

What do you think?

**Comment by mcollina** [comment]
Everything is exposed and documented in 1.0.0.
