### ISSUE TITLE
send PingREQ

### ISSUE THREAD

**Issue by BenAhrdt** [mqttjs/MQTT.js#1863]
Hi. Actual we have an issue with keepalive.
If i set it to more than 0 the client closes and reconnect every 5 oder 10 minutes.

Have i to send an pingreq manually?
If yes => How can i send it?
Is ther something link client.pingReq();????

**Comment by robertsLando** [comment]
@BenAhrdt What mqttjs version are you using?

**Comment by BenAhrdt** [comment]
The Last Version i Check it worked  was 5.3.6
Actual i cant Check this. Im Not at Home

**Comment by BenAhrdt** [comment]
But is the PingREQ Send automaticaly?

**Comment by robertsLando** [comment]
> But is the PingREQ Send automaticaly?

Yeah it is

**Comment by BenAhrdt** [comment]
And how i configure the keepalive?

**Comment by robertsLando** [comment]
@BenAhrdt Use 5.6.0 you don't have to configure anything, you can just choose a keepalive in options but it is 60 seconds by default if not specified and it's automatically handled by MQTTjs

**Comment by BenAhrdt** [comment]
@robertsLando it looks good
