### ISSUE TITLE
[Bug]: My React app can not connect wss in https

### ISSUE THREAD

**Issue by nidea1** [mqttjs/MQTT.js#1869]
### MQTTjs Version

5.6.0

### Broker

mosquitto

### Environment

Browser

### Description

I am trying to connect to the MQTT Broker using MQTT.js in my React application, but I am getting an error with the WSS protocol.

First, my mosquitto.conf file:
```bash
# mosquitto.conf

pid_file /run/mosquitto/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

allow_anonymous false
password_file /etc/mosquitto/passwd

listener 3940
protocol mqtt

listener 39393
protocol websockets

listener 3941
protocol mqtt
cafile /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/broker.crt
keyfile /etc/mosquitto/certs/broker.key

listener 3942
protocol websockets
cafile /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/broker.crt
keyfile /etc/mosquitto/certs/broker.key
```

And the code block in my React application:

```javascript
// some.jsx

useEffect(() => {
        let reconnectAttempts = 0;
        try {
            if (user && !client) {
                const host = "ws://my.domain.io:39393"
                // const host = "wss://my.domain.io:3942
                const options = {
                    keepalive: 60,
                    clientId: `${user.username}_${user.id}_${user.tenant}_${Date.now()}`,
                    username: "username",
                    password: "password",
                    clean: true,
                    rejectUnauthorized: false
                };
                const mqttClient = mqtt.connect(host, options);
                setClient(mqttClient);
                console.log("client: ", mqttClient);

                mqttClient.on("connect", () => {
                    console.log("Connected to MQTT broker");
                    setIsConnected(true);
                    setIsReconnecting(false);
                    setIsDisconnected(false);
                    reconnectAttempts = 0;
                });
                
                mqttClient.on("disconnect", () => {
                    console.log("Disconnected to MQTT broker");
                    setIsConnected(false);
                    setIsDisconnected(true);
                });
                
                mqttClient.on("close", (err) => {
                    console.log("Closed connection to MQTT broker", err);
                });

                mqttClient.on("reconnect", () => {
                    reconnectAttempts++;
                    setIsReconnecting(true);

                    if (reconnectAttempts > 5) {
                        mqttClient.end();
                        console.log("Reconnect attempts exceeded. Closing connection to MQTT broker");
                        setIsConnected(false);
                        setIsDisconnected(true);
                        return;
                    }
                    console.log("Reconnecting to MQTT broker", reconnectAttempts);
                });
                
                mqttClient.on("error", (err) => {
                    console.log("Error from MQTT broker", err); 
                });
            }   
        } catch (error) {
            console.error("Error connecting to MQTT broker", error);
        }

        return () => {
            if (client) {
                console.log("MQTT Hook cleanup")
                client.end();
                setClient(null);
            }
        }
    }, [user, client]);
```

I can connect to the host `mqtts://my.domain.io:3941` on my local device, but I cannot connect to the host `wss://my.domain.io:3942` in the production environment because I need to connect via HTTPS. Additionally, I can connect to `wss://my.domain.io:3942` and perform pub/sub operations without any issues using Python, MQTT Box, and MQTT Explorer.

SS from MQTT Box:
[![enter image description here](https://i.sstatic.net/xDskIXiI.png)](https://i.sstatic.net/xDskIXiI.png)

```python
# some.py
    def connect(self):
        self.client.on_message = self.on_message
        self.client.on_connect = self.on_connect
        self.client.on_disconnect = self.on_disconnect
        
        self.client.tls_set(cert_reqs=ssl.CERT_NONE)
        
        self.client.username_pw_set(self.username, self.password)
        
        self.client.connect(self.broker, self.port, keepalive=10)
        self.client.loop_start()
```

### Minimal Reproduction

So I want connect React to MQTT over WSS in my production server.

### Debug logs

My Mosquitto logs are as follows. My backend application running in the local environment can connect to the port 3941 without a certificate, while my React application can only connect to the port 39393 without a certificate.

[![enter image description here][1]][1]

When my React application in the production environment tries to connect to port 39393, my console shows:

[![enter image description here][2]][2]

When it tries to connect to port 3942, my console shows:

[![enter image description here][3]][3]

Lastly, even though my React application is set to either port 39393 or 3942 in the production environment, no data appears in my Mosquitto logs.

  [1]: https://i.sstatic.net/lQrwEHs9.png
  [2]: https://i.sstatic.net/823uqFRT.png
  [3]: https://i.sstatic.net/thiDB5yf.png

**Comment by robertsLando** [comment]
This is not a problem with MQTTjs, connecting to wss from http is not allowed by the browser

**Comment by nidea1** [comment]
> This is not a problem with MQTTjs, connecting to wss from http is not allowed by the browser

I know already, my react app in https and I gave 2 ss from my production console. First ss when I tried 39393 'ws' protocol getting erros and second ss when I tried 3942 my 'wss' protocol getting errors.

But when I running with 'npm start' on my local dev environment React can connect to 39393 'ws' protocol. So here SS from localhost:3000 console in my pc:

![39393 local](https://github.com/mqttjs/MQTT.js/assets/117437620/22eaf64b-7e68-410a-9bb6-162d2cc3eb0e)

Lastly I can connect to all protocols (3940, 39393, 3941, 3942) with MQTT Box, MQTT Explorer and Python.

**Comment by robertsLando** [comment]
What makes you think this is an MQTTjs related problem? IMO this is something related to your setup

**Comment by nidea1** [comment]
I had an issue where I couldn't connect to a secure MQTT broker at wss://dash.meetlarry.io:3942 over HTTPS while on a React Linux server. The steps I followed to solve this issue are as follows:

 1. First, I modified the Nginx configuration files to include the MQTT
    configuration, as the React server already had configurations for
    the certificates:
    ```nginx
    # React App Server
    server {
        server_name my.domain.io;
    
        root /var/www/html/app/build;
        index index.html;

        listen 443 ssl;
        ssl_certificate /etc/letsencrypt/live/my.domain.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/my.domain.io/privkey.pem;
    
        location / {
            try_files $uri /index.html;
        }

        location /mqtt {
            proxy_pass http://localhost:39393;  # Mosquitto WebSocket port
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }

    # Redirect HTTP to HTTPS for React App
    server {
        listen 80;
        server_name my.domain.io;
        return 301 https://$host$request_uri;
    }
    ```

 2. Then, I updated the code within React as follows:
    ```javascript
    const options = {
        host: "my.domain.io", // current server name with certificate
        port: 443, // port listened by nginx
        path: '/mqtt', // location assigned in nginx
        protocol: 'wss', // protocol
        keepalive: 60,
        clientId: `${user.username}_${user.id}_${user.tenant}_${Date.now()}`,
        username: "username",
        password: "password",
        rejectUnauthorized: false
    };
    const mqttClient = mqtt.connect(options);
    setClient(mqttClient);
    ```

 3. Next, I updated the MQTT configurations on the DRF side:
    ```python
    class MQTTClient:
        def __init__(self, broker, port, username, password):
            self.broker = broker
            self.port = port
            self.username = username
            self.password = password
        
            client_id = f"larry_hotline-{random.randint(0, 1000)}"
            self.client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id, transport="websockets")

        def connect(self):
            self.client.on_message = self.on_message
            self.client.on_connect = self.on_connect
            self.client.on_disconnect = self.on_disconnect
        
            self.client.tls_set(cert_reqs=ssl.CERT_NONE)
        
            self.client.username_pw_set(self.username, self.password)
        
            self.client.connect(self.broker, self.port, keepalive=10)
            self.client.loop_start()
    ```

 4. I ran my Django application on the 3942 WebSocket port to ensure messages are transmitted, and this solved the strange issue.



The reason I resorted to this solution is that I tried to certificate the IP address of my MQTT broker and connect by entering this IP address instead of the domain name through MQTT.js, but both attempts failed. I would have preferred to create a specific certificate for the MQTT broker and connect with MQTT.js directly. If anyone has managed to connect in this way before, I would be very happy if they could explain this method to me as well :)

**Comment by robertsLando** [comment]
@nidea1 Yeah but them are not connecting from the browser and that's a different thing, try to write a nodejs script and use the same parameters to connect to the broker, I suspect that will work

**Comment by nidea1** [comment]
> @nidea1 Yeah but them are not connecting from the browser and that's a different thing, try to write a nodejs script and use the same parameters to connect to the broker, I suspect that will work

Yes, you were right. When I wrote a nodejs script, I managed to connect without any issues, but I still don't understand why the browser doesn't work using the same method. If you could inform me about this or share a document or article that I can read, I would greatly appreciate it. Thank you <3

**Comment by robertsLando** [comment]
From ChatGPT:

you cannot directly connect to a WebSocket server using wss:// (WebSocket Secure) from a web page served over http:// (non-secure HTTP). This restriction is due to the security policies enforced by modern web browsers. Here’s why:

1. Mixed Content Policy: Browsers enforce a security policy called "mixed content" to protect users from certain types of attacks. This policy prevents secure (HTTPS) and non-secure (HTTP) content from being mixed. If you try to connect to a wss:// endpoint from a page served over http://, the browser will block the request because it involves sending potentially sensitive information over an insecure connection.

2. Security Risks: Allowing secure WebSocket connections (wss://) from insecure HTTP pages would undermine the security guarantees provided by the wss:// protocol. Sensitive data transmitted over the secure WebSocket could be intercepted or tampered with if the initial page load was not secure.

**Comment by nidea1** [comment]
> From ChatGPT:
> 
> you cannot directly connect to a WebSocket server using wss:// (WebSocket Secure) from a web page served over http:// (non-secure HTTP). This restriction is due to the security policies enforced by modern web browsers. Here’s why:
> 
> 1. Mixed Content Policy: Browsers enforce a security policy called "mixed content" to protect users from certain types of attacks. This policy prevents secure (HTTPS) and non-secure (HTTP) content from being mixed. If you try to connect to a wss:// endpoint from a page served over http://, the browser will block the request because it involves sending potentially sensitive information over an insecure connection.
> 2. Security Risks: Allowing secure WebSocket connections (wss://) from insecure HTTP pages would undermine the security guarantees provided by the wss:// protocol. Sensitive data transmitted over the secure WebSocket could be intercepted or tampered with if the initial page load was not secure.

Already my problem was cannot connect wss from page served over https :)

**Comment by robertsLando** [comment]
I think that the same problem may apply if the domain is different

**Comment by nidea1** [comment]
> I think that the same problem may apply if the domain is different

Domain names were already the same

**Comment by robertsLando** [comment]
No clue so I'm sorry but my feel is there is something wrong with your proxy configuration maybe or your backend is using something like "helmet" package in nodejs that blocks the connection

**Comment by nidea1** [comment]
> No clue so I'm sorry but my feel is there is something wrong with your proxy configuration maybe or your backend is using something like "helmet" package in nodejs that blocks the connection

May be, thanks for everything
