### ISSUE TITLE
[Bug]: reconnect subscribe issues

### ISSUE THREAD

**Issue by brandonstubbs** [mqttjs/MQTT.js#1882]
### MQTTjs Version

5.7.0

### Broker

mosquitto

### Environment

Browser

### Description

When calling reconnect on a client that has `resubscribe` set to true it causes an error.

### Minimal Reproduction

```js
const client = mqtt.connect(`wss://test.mosquitto.org:8081`, {
  protocolVersion: 5,
  clientId: "reconnect-issue",
  manualConnect: true,
  log: console.log.bind(console),
});

client.on("connect", () => {
  client.subscribe("reconnect-issue", { qos: 1 }, (err, granted) => {
    console.log("subscribed", err, granted);
  });
});

client.on("error", (err) => console.error("error", err));

client.connect();

setTimeout(() => {
  client.reconnect();
}, 10 * 1000);
```

### Debug logs

```
mqtt.esm.js:2 _resubscribe
mqtt.esm.js:2 _resubscribe: protocolVersion 5
subscribed Error: client disconnecting
    at t._checkDisconnecting (mqtt.esm.js:2:241073)
    at t.subscribe (mqtt.esm.js:2:235595)
    at t.<anonymous> (main.js:42:10)
    at Y.emit (mqtt.esm.js:2:27491)
    at t._onConnect (mqtt.esm.js:2:247915)
    at Rv (mqtt.esm.js:2:215998)
    at Mv (mqtt.esm.js:2:217411)
    at s (mqtt.esm.js:2:232120)
    at r._write (mqtt.esm.js:2:232392)
    at D_ (mqtt.esm.js:2:82265) undefined
```

The client has `disconnecting` still set to true

**Comment by robertsLando** [comment]
@brandonstubbs But is the client disconnected when you call reconnect? Want  to submit a PR to fix the issue?

**Comment by brandonstubbs** [comment]
@robertsLando the client is connected and reconnect is called. I know this is a bit of a weird case, but this is a client that is connected to AWS IoT Core. There is no way to disconnect a client to make it connect again (from IoT core), so these clients reconnect when they receive a particular message.

**Comment by brandonstubbs** [comment]
@robertsLando after doing some further tests, it seems the PR would need more work as stores and some other things are closed.

Looking at the tests, it seems that `reconnect` is designed to be used after `end` has been called. This approach works fine for me. I am closing the issues as `reconnect` **after** `end` works.

Thanks for your time.
