### ISSUE TITLE
Poor performance when publishing

### ISSUE THREAD

**Issue by RickBullotta** [mqttjs/MQTT.js#1899]
### MQTTjs Version

5.8.0

### Broker

HiveMQ 4

### Environment

NodeJS

### Description

When publishing approximately 5000 topics (each a small JSON payload with the retain flag set), I'm only seeing throughput of about 72 messages per second.  That seems extremely low.  Oddly enough, when connected to a cloud instance of HiveMQ versus a local instance, the throughput is excellent. I suspect some type of handshaking or network buffer flushing is causing this regression.

### Minimal Reproduction

Publish 5000 messages quickly.  Monitor HiveMQ's inbound/outbound message rates.

### Debug logs

Not applicable.

**Comment by robertsLando** [comment]
@RickBullotta Could you tell me if this is a regression and if yes point me to the version that introduced this?

**Comment by RickBullotta** [comment]
It turns out that it was a regression/flow control issue in the broker.  Closing issue.
