### ISSUE TITLE
[Bug]: Unable to preform a wss connection to a self hosted broker

### ISSUE THREAD

**Issue by hsmptg** [mqttjs/MQTT.js#1908]
### MQTTjs Version

5.8.0

### Broker

emqx and/or mosquitto

### Environment

Browser

### Description

When I use ws:// from inside a React app I can connect to a self hosted broker but if I use wss:// with self signed certificates I can not connect.
You could say that the problem is in my self hosted broker then, but if I preform the wss connection from a MQTT client (MQTTX for instance) I can connect to that broker!
Note that I used a self hosted mosquitto and emqx broker with the same result.
Strangely, if in my React app I use a public broker (like the wss://broker.emqx.io:8084/mqtt) it works again which makes me think that can be something related with the certificates. But if is this the case, why the MQTTX can establish connection?

### Minimal Reproduction

To reproduce the problem I had to give the access to my self hosted broker, that I do not mind to do it but not in this GitHub public place.

### Debug logs

Since I am using mqttjs from a browser I do not know what to write here.
In the console of Firefox I get the message: "Firefox can’t establish a connection to the server at wss://xxxxx.xxx:yyyy/mqtt"

**Comment by hsmptg** [comment]
Just to add some more information on this.
When I make a wss connection to my emqx self hosted broker I get a log message saying:
"2024-07-21T19:33:26.466398+00:00 [notice] TLS server: In state wait_finished received CLIENT ALERT: Fatal - Unknown CA"
Which makes me once again think the the problem is the use of "self signed certificates".
Does mqtt.js allows the use of "self signed certificates"?

**Comment by robertsLando** [comment]
Just override the mqttjs `log` option

**Comment by hsmptg** [comment]
> override the mqttjs `log` option

I do not know exactly what to do mean and how/where to check those logs.
In your readme Debug Logs section I see something to use this: `$env:DEBUG='mqttjs*'`
Can you give me more information on how to proceed?

Many Thanks

**Comment by robertsLando** [comment]
Check `log` option: https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options

**Comment by hsmptg** [comment]
Thanks for your help but I am afraid not doing what you probably want.

Here is a portion of my code:
```
  const connectToBroker = () => {
    const url = "wss://XXXXX.XX:YYYY/mqtt";
    const options = {
      keepalive: 30,
      clientId: "mqttjs_" + Math.random().toString(16).substr(2, 8),
      clean: true,
      reconnectPeriod: 1000,
      connectTimeout: 30 * 1000,
      username: "decel",
      password: "decel2023",
      protocol: "wss",
      ca: CERTIFICATES.ca,
      cert: CERTIFICATES.cert,
      key: CERTIFICATES.key,
    };
    const mqttClient = mqtt.connect(url, options);
    mqttClient.log = (err) => {
      console.log(err);
    };
```
As you can see in the end I tried to use the log option (probably not in the right way) and I got the follwing Firefox console messages:
```
Firefox can’t establish a connection to the server at wss://XXXXX.XX:YYYY/mqtt. mqtt.esm.js:5:15115

streamErrorHandler :: error App.jsx:309:14
noop :: App.jsx:309:14
(%s)stream :: on close App.jsx:309:14
_flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function App.jsx:309:14
stream: emit close to MqttClient App.jsx:309:14
close :: connected set to `false` App.jsx:309:14
close :: clearing connackTimer App.jsx:309:14
close :: calling _setupReconnect App.jsx:309:14
_setupReconnect :: emit `offline` state App.jsx:309:14
_setupReconnect :: set `reconnecting` to `true` App.jsx:309:14
_setupReconnect :: setting reconnectTimer for %d ms App.jsx:309:14
reconnectTimer :: reconnect triggered! App.jsx:309:14
_reconnect: emitting reconnect to client App.jsx:309:14
_reconnect: calling connect App.jsx:309:14
connect :: calling method to clear reconnect App.jsx:309:14
_clearReconnect : clearing reconnect timer App.jsx:309:14
connect :: using streamBuilder provided to client to create stream App.jsx:309:14
connect :: pipe stream to writable stream App.jsx:309:14
connect: sending packet `connect` App.jsx:309:14
_writePacket :: packet: %O App.jsx:309:14
_writePacket :: emitting `packetsend` App.jsx:309:14
_writePacket :: writing to stream App.jsx:309:14
_writePacket :: writeToStream result %s App.jsx:309:14
```
I tried to find an example using this log option in your repository without success.
Speaking about examples in the wss example at GitHub you use a proxy, something that I do not use. There is any other example using mqtt.js with wss?

**Comment by hsmptg** [comment]
Dear Daniel

Sorry to insist but in my pursue of trying to have a successful connection from within a frontend app (using React in my case) I am trying first to find a similar web mqtt client to do that test. The only one I found was [MQTTX web app](https://mqttx.app/web-client) but unlike [MQTTX desktop app](https://mqttx.app/) I can not specify the self signed certificates.

Did someone used successfully the mqtt.js to make a wss connection to a mqtt broker **from within a web page**?
Note that from within an desktop app I have multiple examples of success!

Once again I can give you the access to my mqtt broker to see if you have success in making a wss connection **from within a web page**.

Thanks once again for your help.

**Comment by robertsLando** [comment]
@hsmptg did you try to set `rejectUnauthorized` option to `false`?

**Comment by hsmptg** [comment]
> @hsmptg did you try to set `rejectUnauthorized` option to `false`?

Yes I did but the result is the same!

I think that the problem is somehow related with the use of certificates with mqtt.js.
Because if I use the wss://broker.emqx.io:8084/mqtt broker (where I do not need to provide certificates) it works ok!
You could say that then I should fix my self signed certificates. But in that case, why they work OK if I use them in a MQTTX desktop app?

Sorry to insist but I can give you privately (please sent me an email) my mqtt broker access data (host, port, certificates, etc.) and you can check by yourself why it works OK using a MQTTX client but not using mqtt.js!

Thanks once again for your effort in helping me on this.

**Comment by robertsLando** [comment]
I would like to see if there is some other error on console that could explain the issue as I don't see anything on your console that explains why the connection fails

**Comment by hsmptg** [comment]
Yes, that's my suspicion too but what can I do in order to fix the problem then?
That is, how can I create certificates that could work on the browser?
wss was created exactly to allow a secure connection from a browser, right?
And why the connection to the public emqx broker works, and not to my private broker, even when with the desktop app all works OK?

**Comment by robertsLando** [comment]
because desktop app isn't running on a browser environment. As said if you run mqttjs with nodejs you will see it works. You don't need to specify certificates on wss protocol as them will not be passed to the websocket constructor anyway.  You should use nginx to make the broker running on same port of your backend service
