### ISSUE TITLE
Consider improving/correcting unsubscribe()-related type signatures

### ISSUE THREAD

**Issue by bretambrose** [mqttjs/MQTT.js#1920]
**Is your feature request related to a problem? Please describe.**
The type signatures for unsubscribe are problematically re-using IClientSubscribeOptions: https://github.com/mqttjs/MQTT.js/blob/v5.9.1/src/lib/client.ts#L1300-L1318

None of the fields in IClientSubscribeOptions (including the required qos) are relevant to an Unsubscribe call.  The implementation just uses the options for its mqtt5 properties in the base type interface (which are technically equivalent since Subscribe and Unsubscribe only support user properties).

This leads to somewhat absurd situations like having to include a qos value (because it's required in IClientSubscribeOptions) in order to pass user properties to an Unsubscribe attempt.  

**Describe the solution you'd like**
Add IClientUnsubscribeProperties:

```
export interface IClientUnsubscribeProperties {
	/*
	 *  MQTT 5.0 properies object of unsubscribe
	 * */
	properties?: IUnsubscribePacket['properties']
}
```

and switch the unsubscribe implementation signatures to the new type.

**Describe alternatives you've considered**
Technically I can pass a nonsense-qos value and achieve the same result.  I can also just @ts-ignore the lack of qos.  Both solutions are not very desirable.

**Additional context**
N/A

**Comment by robertsLando** [comment]
Closed by #1921
