### ISSUE TITLE
[Bug]: MQTT WS connection not able to handle Blob Data while running in React Native Windows

### ISSUE THREAD

**Issue by IamJignesh** [mqttjs/MQTT.js#1928]
### MQTTjs Version

5.9.1

### Broker

mosquitto

### Environment

Browser

### Description

I am trying to implement this React Native example for windows UWP app https://github.com/MaximoLiberata/react-native-mqtt.js-example

The client's keeps disconnecting as it not able to handle the Blob data type when using WS connection:

Error's from the app:
![image](https://github.com/user-attachments/assets/46486dbe-65b2-4e1b-bdeb-db7df83dcd41)

![image](https://github.com/user-attachments/assets/0727dc85-2401-4139-9e00-2c09bca4228f)

**On debugging it further, I figured out that handling the Blob type in the onMessage in the ws.js resolved my issue**

![image](https://github.com/user-attachments/assets/a5e39fcb-741e-4e59-bc38-cbbbd6ab12fe)

After updating the ws.js I am able to connect to the broker and receive the message
![image](https://github.com/user-attachments/assets/9d6f33cd-a0af-4204-ae2f-f3ba82b08f29)

No errors on the console
![image](https://github.com/user-attachments/assets/df699c66-5ec9-4e15-bf87-3ac04a25bd2b)

### Minimal Reproduction

My Current setup is:

React Native Windows UWP App (I have attached the source code)
  - To build and run the code:
    -  Setup the development environment as per this docs here https://microsoft.github.io/react-native-windows/docs/rnw-dependencies
    - Extract the provided source code and navigate to the directory [MQTT-React-Native.zip](https://github.com/user-attachments/files/16684195/MQTT-React-Native.zip)
    - Run yarn install
    - Run npx install-windows-test-app
    - Run yarn windows
    - If you get an error regarding PowerShell scripts not digitally signed then launching the app is a two step process
      - Run yarn windows --arch x64 --release --logging --no-launch --no-deploy
      - Open the Windows project windows/espb.sln in the visual studio
      - Select the Debug configuration and the x64 platform from the combo box controls to the left of the Run button and underneath the Team and Tools menu item.
      - Make sure the Metro bundler is running when the app is launched (yarn [start)]([MQTT-React-Native.zip](https://github.com/user-attachments/files/16684156/MQTT-React-Native.zip))
      
I am also using a self-hosted Mosquitto broker which can be setup using:
https://cedalo.com/blog/mosquitto-docker-configuration-ultimate-guide/

I have tried running this solution against some of the available hosted brokers like https://www.emqx.com/en/mqtt/public-mqtt5-broker but they are not reliable that why I opted for a self hosted one.

### Debug logs

Console Error's:
![image](https://github.com/user-attachments/assets/d52db9ff-d7a7-4786-92ae-816cda7ca820)

**Comment by robertsLando** [comment]
@IamJignesh Could you submit a PR to fix the issue so please?

**Comment by IamJignesh** [comment]
Issue fixed in this PR https://github.com/mqttjs/MQTT.js/pull/1930
