### ISSUE TITLE
[Bug]: Changing from protocolVersion 4 to 5 causes duplicate messages when subscribing to both specific and wildcard topics

### ISSUE THREAD

**Issue by marinkovicmilos** [mqttjs/MQTT.js#1944]
### MQTTjs Version

5.10.1

### Broker

mosquitto

### Environment

NodeJS

### Description

Subscribing to both a specific topic (e.g., topic/test/foo) and a wildcard topic (e.g., topic/test/+), the application receives duplicate messages for the same published message. This issue occurs specifically when using protocol version 5. The behavior with **protocol version 4 works as expected**, with only one message being received. 
The switch to protocol version 5 was necessary to utilize the rap property, which is crucial for determining whether a message was retained.

### Minimal Reproduction

This is the code:
```javascript
const mqtt = require('mqtt');

start = () => {
    try {
        console.info('Start');

        const mqttClient = mqtt.connect({
            host: '192.168.1.111', // Replace with your Mosquitto broker IP
            port: 1883,
            // protocolVersion: 4,
            protocolVersion: 5, // Set to protocol version 5
            clientId: 'test-mqtt-123',
        });

        mqttClient.on('connect', () => {
            console.info('Client connected');
        });

        const topics = [
            'topic/test/foo',
            'topic/test/+',
        ];

        const options = {
            qos: 2,
            rap: true,
        };

        mqttClient.subscribe(topics, options, (error, data) => {
            if (error) {
                console.error('subscribing error: ', error);
            } else {
                console.log('subscribed: ', JSON.stringify(data));
            }
        });

        mqttClient.on('message', (topic, message, packet) => {
            console.info(`Received on topic: ${topic}, is retained: ${packet.retain}, message: ${message}`);
        });
    } catch (error) {
        console.error('Error: ', error.message);
    }
};

start();
```

1. Run code
2. Publish a message (e.g., Hello mqtt) on the topic topic/test/foo using an MQTT client.

**Expected behavior**: The message should be received once for the exact topic match (topic/test/foo) or the wildcard match (topic/test/+), but not both.

**Actual behavior**: The message is received twice, even though the message was published only once.

### Debug logs

Logs when the protocol version is set to 5, the message is received twice:
```bash
Start
Client connected
subscribed:  [{"topic":"topic/test/foo","qos":2,"nl":false,"rap":true,"rh":0},{"topic":"topic/test/+","qos":2,"nl":false,"rap":true,"rh":0}]
Received on topic: topic/test/foo, is retained: false, message: Hello mqtt
Received on topic: topic/test/foo, is retained: false, message: Hello mqtt
```

When the protocol version is set to 4, the message is only received once as expected:
```bash
Start
Client connected
subscribed:  [{"topic":"topic/test/foo","qos":2},{"topic":"topic/test/+","qos":2}]
Received on topic: topic/test/foo, is retained: false, message: Hello mqtt
```

**Comment by robertsLando** [comment]
@marinkovicmilos Would you like to submit a PR to fix the issue? Could it be it's the broker sending the message twice for some reason? Could you test with another broker?

**Comment by bretambrose** [comment]
FWIW, the specs for both 311 and 5 explicitly permit brokers to send multiple copies of a message if it matches multiple active subscriptions:

"When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.4-2]. In addition, the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case."

So even if there is a behavioral regression, it's probably best not to rely on an assumption of singular messages.

**Comment by robertsLando** [comment]
@bretambrose thanks for the reference 🙏🏼 

ok so this seems not an issue with MQTTjs
