### ISSUE TITLE
[Bug]: MQTT is not connecting to broker while using SSL 

### ISSUE THREAD

**Issue by Rakshith-Bhagya-Ram** [mqttjs/MQTT.js#1945]
### MQTTjs Version

^5.10.1

### Broker

 mosquitto

### Environment

Browser

### Description

i can connect to broker in node and MQTT Exporer, but unable to connect using react.js its throwing error **MQTT client is offline**

### Minimal Reproduction

1. install the library
2. integrated in my react.js project
3. and run the webapp

**this is how i integrated in my project**

              import React, { useEffect } from 'react';
              import mqtt from 'mqtt';
              import { mqttAddress } from '../../constants/urlConstants';
              
              
              const Mqtt = () => {
                  useEffect(() => {
                      const options = {
                          clientId: 'clientId',
                          username: 'mqtt',
                          password: 'mqtt',
                          keepalive: 32000,
                          rejectUnauthorized: false,
                          protocol: 'mqtts',  //SSL
                          reconnectPeriod: 1000,
                          connectTimeout: 30000
                      };
              
                      const client = mqtt.connect(mqttAddress, options);
              
              
                      client.on('connect', () => {
                          console.log('Connected to MQTT broker');
                      });
              
                      client.on('reconnect', () => {
                          console.log('Reconnecting to MQTT broker...');
                      });
              
                      client.on('offline', () => {
                          console.log('MQTT client is offline');
                      });
              
                      client.on('error', (err) => {
                          console.error('Connection error: ', err);
                      });
              
                      client.on('message', (topic, message) => {
                          console.log(`Received message: ${message.toString()} on topic: ${topic}`);
                      });
              
                      client.subscribe('your/topic', (err) => {
                          if (err) {
                              console.error('Subscription error: ', err);
                          } else {
                              console.log('Subscribed to topic');
                          }
                      });
              
                      client.publish('your/topic', 'Hello MQTT', (err) => {
                          if (err) {
                              console.error('Publish error: ', err);
                          } else {
                              console.log('Message published');
                          }
                      });
              
              
                      return () => {
                          client.end();
                      };
                  }, []);
               
                  return (
                      <div>
                          <h1>MQTT with React</h1>
                      </div>
                  );
              };
              
              export default Mqtt;

### Debug logs

![image](https://github.com/user-attachments/assets/59065ff9-eef1-4b75-b914-2b9915420124)

**Comment by robertsLando** [comment]
Please read docs: https://github.com/mqttjs/MQTT.js#browser
