### ISSUE TITLE
Transmitting binary data

### ISSUE THREAD

**Issue by simoneb** [mqttjs/MQTT.js#199]
Hi,

somewhat related to  #109 and #123, there doesn't seem to be a good way to publish binary data and receive it in the same format. 
The default `utf8` encoding is somewhat misleading because I publish a `Buffer` and get a string at the other end. I see the suggestion is to use `binary` encoding, but the [docs](http://nodejs.org/api/buffer.html#buffer_buffer) say it's deprecated and should not be used.

Workarounds are straightforward but I think the API would benefit from avoiding implicit encodings when binary data is published.

Ideas?

**Comment by mcollina** [comment]
This is fixed in 1.0.0 (or before).
