### ISSUE TITLE
Replace mosquitto?

### ISSUE THREAD

**Issue by hirecom** [mqttjs/MQTT.js#207]
Hi, can I use MQTT.js broadcast.js as a replacement for mosquitto?  It's nice to work with MQTT.js but the readme says you should use mosquitto but can use the broadcast example as well.

**Comment by joltup** [comment]
Would redis work better than rabbitmq for scaling horizontally? Why is would that be the case?

**Comment by mcollina** [comment]
It depends on your scale. Redis usually offers lower latencies if you have to distribute less than 1 million messages per second. RabbitMQ can offer super-high availability. Unfortunately, there is no easy recipe for scaling :(.

**Comment by joltup** [comment]
What about mongodb?

**Comment by RangerMauve** [comment]
MongoDB doesn't really facilitate passing messages between processes. It's used to store data.

**Comment by RangerMauve** [comment]
Redis is a lot easier to set up in my opinion. Though you can get more customization with rabbitmq in the long run.

**Comment by mcollina** [comment]
@RangerMauve it is not true, you can use [Capped Collections](http://docs.mongodb.org/manual/core/capped-collections/) and a [Tailable Cursor](http://docs.mongodb.org/manual/tutorial/create-tailable-cursor/) to exchange messages between processes in MongoDB. Mosca uses those to exchange messages between instances, so @joltup mongodb support in Mosca is a quick-win solution that does scale upon a certain point. I would recommend Redis anyway.

**Comment by RangerMauve** [comment]
@mcollina Oh, I didn't know you could do that with MongoDB! Definitely going to have to look into it some more.
