### ISSUE TITLE
warn on connect to a non ws enabled MQTT sever

### ISSUE THREAD

**Issue by gorhgorh** [mqttjs/MQTT.js#244]
when used as a browserify module mqtt.js uses a websocket connection and need a broker set up accordingly, if the server is not set up to accept ws but is at the right adress  /port mqtt.js does not warn you.
took me a bit of time before realising that, a simple warning could be handy

**Comment by mcollina** [comment]
It would be _very_ helpful if you send a PR do address that use case. You can just throw/emit an error in that case, a warning is not enough I think.

**Comment by gorhgorh** [comment]
Sure, do you have any leads on where that connection is happening ? and yes I agree it should error

**Comment by mcollina** [comment]
It really depends where we can catch this behavior. I am attaching the most probable places:

https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/ws.js
https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L148-L203

Regarding the latter, I think we might have a CONNACK timeout, i.e. if we do not receive a CONNACK in 5 seconds, we might just trigger the restart event.

Also, we currently swallow all connection errors to handle automatic reconnect in https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L183 but we might want to re-emit them as a `'connectionError'` event, and document that in the README.

What do you think?

**Comment by gorhgorh** [comment]
we may use a pure feature detection in the buildBuilderBrowser function (so we could also test if the browser is ws ready) 
I'll make a reduced test case tonight and see if that work

**Comment by mcollina** [comment]
Cool! If it works prepare a PR :D.

**Comment by mcollina** [comment]
Closing for now.

@gorhgorh feel free to send that PR in case!

**Comment by gorhgorh** [comment]
Sorry I totally forgot about this thing ... will try to have a look at it soon !
