### ISSUE TITLE
Websockets in browser should use default ports for http and https

### ISSUE THREAD

**Issue by RangerMauve** [mqttjs/MQTT.js#245]
I noticed that when the port isn't specified in the URL being passed to the [`buildBuilderBrowser`](https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/ws.js#L27) function, it's defaulting to using whatever port the current page is being loaded with. Wouldn't it be more intuitive to use whatever the default port for `ws` and `wss` be? (I'm assuming that would be the same as `http` and `https`, so 80 and 443)

**Comment by mcollina** [comment]
Let me make an example: I have a page running on localhost:3000. I want
just to run mqtt.connect(), and I have my mqtt connection. However, if I
want to connect from there to test.mosca.io, I want it to be on port 80. If
this is not happening now, can you please send a PR? Thanks a million!!
Il giorno mar 3 feb 2015 alle 20:17 RangerMauve <notifications@github.com>
ha scritto:

**Comment by RangerMauve** [comment]
Yeah, in your example, it would connect to test.mosca.io:3000. I'll take up the challenge.
