### ISSUE TITLE
Replace 'createClient' by 'connect' 

### ISSUE THREAD

**Issue by sguilly** [mqttjs/MQTT.js#247]
Hi,

I use currently the version '0.3.13' with the method 'createClient' and everything work fine.
 
var clientMqtt = mqtt.createClient(1883, '200.200.200.200', {
    clean: false,
    encoding: 'utf8',
    clientId: 'guest',
    username: 'guest',
    password: 'guest'
});

I try to use the lastest version but 'createClient' is now deprecated.

So i refactor my code with 'connect' method. The program start without error but i never receive the 'connect' event and don't receive any message

var clientMqtt = mqtt.connect(
    {
        port: 1883,
        host: '200.200.200.200',
        clean: false,
        encoding: 'utf8',
        clientId: 'guest',
        username: 'guest',
        password: 'guest'
    });

Someone could explain the new way to connect to the broker with username and password ?

Thanks

**Comment by mcollina** [comment]
First thing: `createClient` is still there but deprecated. Does it still work for you?

`encoding` is not needed anymore.

Which broker are you using? And which version?

This versions passes the parameters for MQTT 3.1.1, which your broker might not understand. Try passing:
https://github.com/mqttjs/MQTT.js/blob/1090fa6ce841790af2f51e72c4cd64f5fbd2d1c4/lib/client.js#L14-L15.

**Comment by sguilly** [comment]
With version > 1.0.x, both method "createClient" and "connect" don't succes to etablish the connection with my broker RabbitMQ 3.2.4, Erlang R16B03.

Everything work fine with 0.3.13.

**Comment by mcollina** [comment]
Have you tried passing the 'old' `protocolId` and `protocolVersion`:
https://github.com/mqttjs/MQTT.js/blob/1090fa6ce841790af2f51e72c4cd64f5fbd2d1c4/lib/client.js#L14-L15?

Does it work without credentials?

**Comment by sguilly** [comment]
The connection success with your additionnal parameters:

protocolId: 'MQIsdp',
protocolVersion: 3,

I use now :

var options = {
    port: 1883,
    host: '200.200.200.200',
    clientId: 'guest',
    username: 'guest',
    password: 'guest',
    keepalive: 60,
    reconnectPeriod: 1000,
    protocolId: 'MQIsdp',
    protocolVersion: 3,
    clean: true,
    encoding: 'utf8'
};

var clientMqtt = mqtt.connect(options);

Thanks for your help.

**Comment by mcollina** [comment]
I have updated the README, so other people will find the solution in the docs.
