### ISSUE TITLE
Apparent hang during install

### ISSUE THREAD

**Issue by mark-bom** [mqttjs/MQTT.js#248]
Hi,

while tying to install mqtt.js, the process stalls (have left it 5 minutes or more) at the following point.  Any advice would be appreciated.

Mark

root@raspberrypi:/home/pi# npm install -g mqtt url request

> ws@0.6.5 install /usr/lib/node_modules/mqtt/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\

**Comment by mcollina** [comment]
If it is the first time you install a binary addon, then it might take some time to download the node.js headers. You should look into /usr/lib/node_modules/mqtt/node_modules/ws/builderror.log and see if the build is stopped somehow. So, ensure your pi is connected to the outside internet, and let it go for a while.

We might even put ws and websocket-stream as optional dependencies. Anybody has other opinions on this?

**Comment by mark-bom** [comment]
Thanks; success!  Yes, it was the first install.  Not sure how long it took, but I left it going over night.

**Comment by mcollina** [comment]
Nice! :)
