### ISSUE TITLE
error in examples 

### ISSUE THREAD

**Issue by itavy** [mqttjs/MQTT.js#249]
hi,

1.in the file "/examples/tls client/mqttclient.js" the options for key and certificate are "keyPath" and "certPath" but in the file "/lib/connect/tls.js" when you build the secure socket, the tls constructor will look for "key" and "cert" keys to locate the files.

as is stated in the example:
var KEY = __dirname + '/tls-key.pem';
var CERT = __dirname + '/tls-cert.pem';
var TRUSTED_CA_LIST = [__dirname + '/crt.ca.cg.pem'];

but you pass them directly to tls constructor, and it will throw error since tls constructor expects a buffer and not a string, it should be 

var KEY = fs.readFileSync(__dirname + '/tls-key.pem');
var CERT = fs.readFileSync(__dirname + '/tls-cert.pem');
var TRUSTED_CA_LIST = [fs.readFileSync(__dirname + '/crt.ca.cg.pem')];

2.in the mqtt constructor, if you provide the key and cert options it will not build a secure client unless you specify one of the secure protocols.

Best regards,
Octavian

**Comment by mcollina** [comment]
I am a little low on bandwidth to maintain everything, you or anybody else would like to submit a fix for those? Maybe also we can add some form of testing for them, so we know when they break?
