### ISSUE TITLE
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

### ISSUE THREAD

**Issue by hongtoushizi** [mqttjs/MQTT.js#259]
hi ,i am using  "examples/server/orig.js" as my mqtt server.
so:
pm2 start org.js  
but ,i get some error;

As follows:
1:    error:push/1470c08a3a381a5
      { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
2:    error:push/42684e669a2151e7
      { [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }
3:    error:push/441a07081199cc43
    { [Error: read EHOSTUNREACH] code: 'EHOSTUNREACH', errno: 'EHOSTUNREACH', syscall: 'read' }

how can i fix them ???thanks

**Comment by mcollina** [comment]
I have no idea what is wrong with pm2, which I do not use.

`node orig.js` works fine for me, I have never seen those error. Please, try running it without PM2.

**Comment by itavy** [comment]
hi,

it is because of the 3rd parameter
on orig.js you have ().listen(process.argv[2] || 1883)

change to .listen(process.argv[3] || 1883) and it should work :)


Regards,
itavy

**Comment by hongtoushizi** [comment]
This error does not happen often, is running after a period of time reported online on the problem? 

I does not use pm2 now ,but still zhe problem。

**Comment by mcollina** [comment]
Closing as v2 will remove the server counterpart.
