### ISSUE TITLE
how to use redis?

### ISSUE THREAD

**Issue by hongtoushizi** [mqttjs/MQTT.js#260]
hi,, To ask, how to work in the following two lines?
    client.p = redis.createClient(null, null, {
          no_ready_check: true
   });
    client.s = redis.createClient(null, null, { 
        no_ready_check: true
    });

In addition, redis in mqtt played what role in the in the end? Concrete realization of those parts of it?

**Comment by mcollina** [comment]
Redis plays no role in MQTT.js.

**Comment by hongtoushizi** [comment]
in file node_modules/mqtt/examples/server , the redis.js : 
      client.p = redis.createClient(null, null, {
            no_ready_check: true
      });
      client.s = redis.createClient(null, null, {  
            no_ready_check: true
     });

These codes mean? What role started?  
In particular, i can not understand  how redis to work?  what role redis start it?

**Comment by RangerMauve** [comment]
That example uses Redis as a means to pass messages between other brokers.

Basically, you can create a server using the boilerplate that MQTT.js provides you, but that on its own is very limited.

The example you're talking about adds a feature that lets you run several instances of your server and synchronize messages between them.

So if you have a client publishing to server `A`, a client connected to server `B` can also receive that message.

Redis is being used for its [pub/sub feature](http://redis.io/topics/pubsub)

**Comment by hongtoushizi** [comment]
Oh, thank you for such a detailed explanation.。I  understand now.  very thanks....
