### ISSUE TITLE
Unable to connect using TLS

### ISSUE THREAD

**Issue by jornbeyers** [mqttjs/MQTT.js#264]
When trying to use TLS security options I get the following error on my MQTT broker (Mosquitto):

  1427756032: Socket error on client <unknown>, disconnecting.
  1427756033: New connection from 146.175.138.141 on port 8883.
  1427756033: OpenSSL Error: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version
                        number

I looked for help on stackoverflow.com, ralight (writer of mosquitto) told me that my node.js code is not using the TLS options. How is this possible? Here is the stackoverflow conversation: http://stackoverflow.com/questions/29358189/mosquitto-security-error-openssl-error-routinesssl3-get-recordwrong-version

This is my code:

var mqtt=require('mqtt')
var mongodbClient=require('mongodb').MongoClient;
var deviceRoot="demo/device/"
var mqtthost = '146.175.138.141';
var KEY = '/etc/keys/client.key';
var CERT = '/etc/keys/client.crt';
var CAfile = '/etc/keys/ca.crt';

var options = {
    host: mqtthost,
    port: 8883,
    protocolId: 'MQIsdp',
    ca: CAfile,
    keyPath: KEY,
    certPath: CERT,
    secureProtocol: 'TLSv1_method',
    protocolId: 'MQIsdp',
    protocolVersion: 3
};

var collection,client;

mongodbClient.connect("mongodb://localhost:27017/exampleDb", function(err,db){
 if(err){return console.dir(err);}

 collection=db.collection("test_mqtt");

 client=mqtt.connect(options);

 client.subscribe("#");
 client.publish(deviceRoot, '21');

 client.on('message', function(topic,payload){
  str = payload.toString();
  console.log(str);
  var key=topic.replace(deviceRoot,'');

  collection.update(
   { _id:key },
   { $push: { events: { event: { value:str, when:new Date() } } } },
   { upsert:true }
)})})

**Comment by itavy** [comment]
you have

**Comment by jornbeyers** [comment]
I'm very sorry, I thought that I looked at all the issues. Probably jumped over #249 ...
This configuration setting works for me. 

For further readers, add the following:

"var fs = require('fs');

**Comment by itavy** [comment]
hi,

if it is ok, can i close the issue ?

**Comment by jornbeyers** [comment]
Yes ofcourse, thank you for your help

**Comment by itavy** [comment]
duplicate of https://github.com/mqttjs/MQTT.js/issues/249

**Comment by OmarySudi** [comment]
I had this problem and I fixed it adding these fields in options variable

  ca: "./certs/ca-cert.pem",
  key: "./certs/client-key.pem",
  cert: "./certs/client-cert.pem",

NOTE: I had the folder called certs in my project root folder which contains those certificates and key files.

**Comment by banjobyster** [comment]
> protocolVersion: 3

Hello @OmarySudi ,

I also have my certificates inside certs folder. I used this [https://gist.github.com/guinp1n/8037766092c980164c5929c7e86bc29e](url) code to create the certificates.

I am using hivemq community broker server 
`<tls-tcp-listener>
    <port>1883</port>
    <bind-address>0.0.0.0</bind-address>
    <proxy-protocol>true</proxy-protocol>
    <tls>
        <keystore>
            <path>../certs/broker-keystore.jks</path>
            <password>changeme</password>
            <private-key-password>changeme</private-key-password>
        </keystore>
        <client-authentication-mode>REQUIRED</client-authentication-mode>
        <truststore>
            <path>../certs/client-truststore.jks</path>
            <password>changeme</password>
        </truststore>
    </tls>
</tls-tcp-listener>`

I am getting error: _ DEBUG - SSL message transmission failed for client with IP UNKNOWN: not an SSL/TLS record: 103700044d51545404c200......_

Can you please guide me how to solve this problem?

mqtt.js looks like this,
`var options = {
    port: 1883,
    host: 'localhost',
    username: "******",
    password: "******",
    keyPath: fs.readFileSync('../certs/client-key.pem'),
    certPath: fs.readFileSync('../certs/client-cert.pem'),
    rejectUnauthorized : true,
    // The CA list will be used to determine if server is authorized
    ca: [fs.readFileSync('../certs/server.pem')]
};`

I added other options such as protocol and others, but keep getting different errors.

**Comment by xtianus79** [comment]
@banjobyster  you need to set rejectUnauthorized to false. this is a self signed cert so unless you setup a way to mTLS you want this to be false.
