### ISSUE TITLE
Unable to publish a number message by command line

### ISSUE THREAD

**Issue by yangpu** [mqttjs/MQTT.js#265]
* to subscribe a simple topic on command line:
```
mqtt sub test/#
```

* to publish a simple message:
```
mqtt pub test/text hello
```

and the sub command line can print hello as expected, however nothing is printed when publish a single number as message:
```
mqtt pub test/number 123
```

what's wrong with my test cases?

**Comment by mcollina** [comment]
That there is bug. See https://github.com/mqttjs/MQTT.js/pull/266, as it should fix it.
