### ISSUE TITLE
username and password support

### ISSUE THREAD

**Issue by lucastan** [mqttjs/MQTT.js#267]
Could you please add username and password support (see mosquitto broker)

**Comment by mcollina** [comment]
username and password are supported. what problem are you seeing?

**Comment by lucastan** [comment]
oh it is not in README. Thanks I will try

**Comment by mcollina** [comment]
All the mqtt-related connect options are listed here: https://github.com/mqttjs/mqtt-packet#connect.

If you want to send a PR to update the documentation, it would be awesome!
