### ISSUE TITLE
mqtts help

### ISSUE THREAD

**Issue by JoelDapello** [mqttjs/MQTT.js#271]
Hello, I'm trying to get mqtts to work from a node app.  when I try a simple test with something like

``` javascript
var mqtt = require('mqtt')
, client  = mqtt.connect('mqtts://test.mosquitto.org');
``` 
I get 
```
Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

Meanwhile using similar code to attempt mqtts connection to my own server running an instance of Mosca configured to use a secure port on 8883 throws a different error:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

is this a valid url to pass? can I get some clues on how to trouble shoot this? Anything is appreciated. Thank you!

**Comment by mcollina** [comment]
`test.mosquitto.org` uses a [self-signed certificate](http://en.wikipedia.org/wiki/Self-signed_certificate), which means __it is not secure__, and it should be used only for testing (and you know what are you doing). In that case, you should pass `{ rejectUnauthorized: false }` to `mqtt.connect(url, opts)` as documented in https://nodejs.org/api/tls.html#tls_tls_connect_options_callback.

**Comment by JoelDapello** [comment]
What about in the case of my own Mosca server, using a signed cert and throwing the error
```
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

**Comment by mcollina** [comment]
It seems there are still some problems with the certificate chain. How are you starting Mosca?
MQTT.js and Mosca accept the same options of https://nodejs.org/api/tls.html (which it uses internally). I suggest trying to connect using that certificate using just TLS to a simple TLS sever on the other side.

**Comment by JoelDapello** [comment]
I start Mosca like this:
``` javascript
var mosca = require('mosca');

var SECURE_KEY = __dirname + '/mosca.key';
var SECURE_CERT = __dirname + '/mosca.crt';

var ascoltatore = {
  //using ascoltatore
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var settings = {
  port: 8883,
  logger: {
    name: "secure",
    level: 40
  },
  secure : {
    keyPath: SECURE_KEY,
    certPath: SECURE_CERT
  },
  backend: ascoltatore,
  https: {
    port: 8443, 
    bundle: true,
    static: './'
  }
};

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running');
}

var server = new mosca.Server(settings);
server.on('ready', setup);

server.on('clientConnected', function(client) {
  console.log('client connected', client.id);
});

// fired when a message is received
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});
```

**Comment by mcollina** [comment]
It seems correct. Does that work with a self-signed certificate, passing `rejectUnauthorized` to the client? Which CA emitted your certificate? If it's self-signed, please _recreate it_, as you might have made an error.

**Comment by JoelDapello** [comment]
using openssl s_client gives `Verify return code: 21 (unable to verify the first certificate)`;
meanwhile, passing `{ rejectUnauthorized: false }` to the client allows connection with the current cert. The cert is from comodo.

Additionally, using mqtt.js v0.3.1 in a node app and mqttws31.js from a browser both connect without throwing errors.

**Comment by mcollina** [comment]
MQTT.js v0.3.1 has rejectUnauthorized set to false by default. I have no
idea about mqttws31.js. I think Comodo CA certificate is not trusted by
node by default.
Il giorno mer 22 apr 2015 alle 08:54 Joel Dapello <notifications@github.com>
ha scritto:

**Comment by JoelDapello** [comment]
ahh. ok. I'll just pass `{ rejectUnauthorized: false }` until I get a better cert I guess?

Thanks for the help

**Comment by itavy** [comment]
hi,

i had same issue when i was testing with mosquitto, and one aproach was to pass the ca file to constructer in options parameter

{
.....
```javascript
ca: [ fs.readFileSync('ca.crt') ]
```
.....
}

**Comment by JoelDapello** [comment]
Thank you, I'll give that a shot.

**Comment by lonaking** [comment]
how to solve this problem, I suffered it yet
