### ISSUE TITLE
Websockets with TLS issues.

### ISSUE THREAD

**Issue by mkarliner** [mqttjs/MQTT.js#275]
I'm trying to use the browserfied version of mqtt.js with CloudMQTT, which only support Websockets with TLS. I'm trying a url which looks like

  wss://xxx.cloudmqtt.com:portnumber

but the failures I"m getting are like

WebSocket connection to 'ws://xxx.cloudmqtt.com:portnumber/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

which implies that the library is reverting back to plain websockets. Is this true?
Or what else might I be doing wrong?

Also, it would be really nice to be able to catch the connection exception, which seems not possible at the moment, so it only shows on the JS console.

MIke

**Comment by mcollina** [comment]
It looks like you are hitting a bug. Would you mind sending a PR that address this issue?

**Comment by mkarliner** [comment]
Not quite sure how to do that.
Could you point me at some instructions?

Mike

**Comment by mcollina** [comment]
You clone this repo, browserify it again, verify the bug is there, put some console log, browserify it again, and so on :D.

**Comment by mcollina** [comment]
The instructions for browserify it are https://github.com/mqttjs/MQTT.js#browserify.

**Comment by mkarliner** [comment]
Have gone to all the trouble of fixing the bug, I found you already did it on Feb 12th. My browserifed version was out of date. Doh!.

**Comment by mcollina** [comment]
Ouch! :D I thought I had already fixed it, but I thought it was a regression on a very specific situation :(.
