### ISSUE TITLE
Allow for command line defaults

### ISSUE THREAD

**Issue by djensen47** [mqttjs/MQTT.js#277]
It would be great if I didn't have to put in the host, username, and password every time I want to use the command line tool. What about putting a default configuration in a .mqttrc file in the user home directory?

**Comment by djensen47** [comment]
I can help implement this but I won't be able to look at it until later this month.

**Comment by mcollina** [comment]
dont't worry and take your time :)
Il giorno dom 3 mag 2015 alle 04:57 Dave Jensen <notifications@github.com>
ha scritto:

**Comment by mcollina** [comment]
@djensen47 feel free to send a PR whenever you want on this :). Closing for now.

**Comment by djensen47** [comment]
Sorry, probably won't happen. No longer working on Road Rules so no longer using MQTT. 😞
