### ISSUE TITLE
Passing ws:// URL results in Unknown protocol - ws:

### ISSUE THREAD

**Issue by raruston** [mqttjs/MQTT.js#279]
I've encountered an odd problem when passing in a ws:// URL where it detects the protocol as 'ws:', rather than 'ws'. I wasn't sure whether to raise here or not because a simple test case seems to work as expected - the problem is only happening for me inside the node-red environment.

Given that, my first thought was that I has done something wrong, so I added some debug code which extracts the protocol using xtend in the same way mqttjsjs does and dumps it to the console. The code is as follows:
```javascript
    this.log("URL=" + node.brokerurl+"=");
    var opts = node.options;
    opts = xtend(url.parse(node.brokerurl, true), opts);
    opts.protocol = opts.protocol.replace(/\:$/, '');
    this.log("Detected Protocol=" + opts.protocol +"=");
    node.client = mqtt.connect(node.brokerurl ,node.options);'
```

This results in the following output:
7 May 14:13:21 - [info] [mqtt-broker:abaf269.f5450d8] URL=ws://test.mosquitto.org:8080=
7 May 14:13:21 - [info] [mqtt-broker:abaf269.f5450d8] Detected Protocol=ws=
7 May 14:13:21 - [error] [mqtt out:70b9b1df.8f465] Error: Unknown protocol - ws:

So it appears that right before the call to connect everything seems in order, and somewhere in connect it goes pear shaped. 

Both mqtt:// and mqtts:// work as expected, and ws://test.mosquitto.org:8080 works fine in a simple test case outside of node-red

Clearly the difference is the NR environment, but I'm struggling to see what could be causing the error in mqttjs when the input looks fine.

Any thoughts?

**Comment by mcollina** [comment]
maybe some of that logic creates a couple of conflicting options. can you print in full the two objects?

**Comment by jsingler** [comment]
I have the same issue when using mqtt.connect with ws-url: "ws://localhost:8000"

my console output from node:

debug: Trying to connect to: ws://localhost:8000
/Users/d039757/Documents/src/node/node_modules/mqtt/lib/mqtt.js:58
  throw new Error('Unknown protocol - ' + brokerUrl.protocol);
        ^
Error: Unknown protocol - ws:
    at Object.module.exports.connect (/Users/d039757/Documents/src/node/node_modules/mqtt/lib/mqtt.js:58:9)
    at Object.<anonymous> (/Users/d039757/Documents/src/node/ws-bridge/edge.js:35:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Best, Joerg

**Comment by mcollina** [comment]
This works for me:

```js
var mqtt    = require('./');
var client  = mqtt.connect('ws://test.mosca.io');

client.subscribe('presence');
client.publish('presence', 'Hello mqtt');

client.on('message', function (topic, message) {
  console.log(message.toString());
});

client.end();
```

**Comment by raruston** [comment]
I've not revisited this as it was decided not to support the ws protocol in the new NodeRed mqtt node, and I no longer need to solve it at this point (I might somewhere down the road though). I can re-iterate that outside of NodeRed, in a simple test app, it all worked fine. 

@jsingler - are you able to recreate this in a simple test app? Or is this part of some other application, that might have other dependencies, similar to NodeRed?
