### ISSUE TITLE
Anthentication PSK (pre shared key) with Mosquitto

### ISSUE THREAD

**Issue by flyingmouse** [mqttjs/MQTT.js#283]
I am trying to configure a Pre Shared Key encrypted connection between a mosquitto mqtt broker and an application written in Node.js which uses the MQTT client library. 

I can't seem to find any samples or documentation that talks about how you'd set this up. Is it possible to authenticate the client with PSK using this library?

Thanks for your help :-)

**Comment by mcollina** [comment]
I think so, given that the PSK stuff is just TLS. However I do not know the options for doing it in node.js https://nodejs.org/api/tls.html#tls_tls_connect_options_callback. You can pass any of those options through the `mqtt.connect()` method.

If you would like to document that in the examples folder and send a PR, that would be great!

**Comment by flyingmouse** [comment]
Unfortunately after googling I don't think TLS-PSK is implemented by Node.js, because it is recently introduced to Openssl and is not widely supported. There was a PR (https://github.com/joyent/node/pull/1162/files) serveral years ago but was not accepted.

**Comment by mcollina** [comment]
TLS-PSK is not available in Node.js, when that will be added it would be supported in piggyback.
