### ISSUE TITLE
Secure MQTT client

### ISSUE THREAD

**Issue by mitos14** [mqttjs/MQTT.js#284]
hi,
I have been trying to create a secure mqtt client and I am not able to. I looked all over and I could not find one example of this MQTT library with TLS. My code is not working and I am sure that I am doing something wrong. For example, I am not specifying a cert or a key store because I have no idea where to  do so. Here is what I have and I am hoping someone can alter my code and show me all the parameters that I am missing. 
One thing to note, my code works just fine till I add TLS support.
I am using node.js version v0.10.5 on linux (and I also tried on mac osx)
My broker is not available for others to connect to it, so that is why I have dummy connection info in my code.
```
var mqtt = require('mqtt');
var clientId = "myclientid";
var port = 8883; //TLS port
var username = "myusername";
var password = new Buffer("mypassword");
var mqttBroker = "mqtts://mybroker.com";
var publishTopic = "mytopic/fmt/json";

var mqttClient  = mqtt.connect(mqttBroker, {clientId: clientId, port: port, username: username, password: password});
mqttClient.publish(publishTopic, new Buffer(JSON.stringify("myjsonmessage")), {qos:0, retain: false});

```
One last point. I have connected to the same broker previously using python library over TLS. I had to specify a certificate (maybe also a keystore). So I know the broker accepts TLS, I just do not know how to do it using this node.js module.
Thank you

**Comment by mcollina** [comment]
I strongly recommend you to update your node installation to 0.10.38 (or 0.12).

You need to pass a `ca` option containing an array with the CA certificate in it (as a buffer) see  https://github.com/mqttjs/MQTT.js/blob/97d3f158f11c3be6bb58b74376964c3571e162ef/test/secure_client.js#L97.

**Comment by mitos14** [comment]
Thank you for the sample.
One thing confused me. In my original posting I mentioned that I have nodejs v0.10.5 you are telling me to upgrade to a downgraded version (0.10.38)? is 0.10.38 newer than 0.10.5 ?
thank you

**Comment by mcollina** [comment]
Node.js is versioned using a pattern MAJOR.MINOR.PATCH, and in 0.10.38 and 0.10.5 the patch versions are 38 and 5, respectively. And 38 > 5, so it s far more recent.
