### ISSUE TITLE
Can I know what message is being passed in subscriber?

### ISSUE THREAD

**Issue by PritamUpadhyay** [mqttjs/MQTT.js#291]
Hello, I am new to mqtt and I am learning it. As far as i read and implemented, I got the idea of pub/sub via mqtt. 
From the examples, I have made two different files one for server and one for client. I want to know How can I get (print for logging purpose) the message at server side in subscriber event?

**Server.js**

 var mqtt = require('mqtt')
  , util = require('util');
  new mqtt.Server(function (client) {
    var self = this;

    if (!self.clients) self.clients = {};

    client.on('connect', function (packet) {
        //console.log(client);
        client.connack({ returnCode: 0 });
        client.id = packet.clientId;
        console.log("CONNECT(%s): %j", client.id, packet);
        self.clients[client.id] = client;
    });

    client.on('publish', function (packet) {
        console.log("PUBLISH(%s): %j", client.id, packet);
        for (var k in self.clients) {
            self.clients[k].publish({ topic: packet.topic, payload: packet.payload });
        }
    });

    client.on('subscribe', function (packet) {
        console.log("SUBSCRIBE(%s): %j", client.id, packet);       
        var granted = [];
        for (var i = 0; i < packet.subscriptions.length; i++) {
            granted.push(packet.subscriptions[i].qos);
        }
        client.suback({ granted: granted, messageId: packet.messageId });        
    });

    client.on('pingreq', function (packet) {
        console.log('PINGREQ(%s)', client.id);
        client.pingresp();
    });

    client.on('disconnect', function (packet) {
        client.stream.end();
    });

    client.on('close', function (err) {
        delete self.clients[client.id];
    });

    client.on('error', function (err) {
         console.log('error!', err);

        if (!self.clients[client.id]) return;

        client.stream.end();
        console.dir(err);
    });
}).listen(process.argv[2] || 1883);

**Client.js**

   var mqtt = require('mqtt')
        , host = 'localhost'
        , client = mqtt.connect();
    
    client.subscribe('test', function () {
        client.on('message', function (topic, message, packet) {
            console.log("Received '" + message + "' on '" + topic + "'");
        })
    });
    
    client.publish('test', 'Pritam Upadhyay');
    client.end();

**Comment by w3hacker** [comment]
client.subscribe('hello', { qos: 1 });

client.publish('hello', 'hello world');

**Comment by PritamUpadhyay** [comment]
@w3hacker : I want to catch message at server side and not client side. what you are suggesting is for client side.

**Comment by w3hacker** [comment]
```
client.on('publish', function (packet) {
    console.log(packet.payload); // that's it
    console.log("PUBLISH(%s): %j", client.id, packet);
    for (var k in self.clients) {
        self.clients[k].publish({ topic: packet.topic, payload: packet.payload });
    }
});
```

**Comment by PritamUpadhyay** [comment]
@w3hacker : By this way I will get published messages . I want to log messages while subscribing. I need subscribed messages which will be sent back to client.

**Comment by mcollina** [comment]
You can use the `'authorizeForward'` method in `Mosca`: https://github.com/mcollina/mosca/blob/master/lib/server.js#L395-L407

**Comment by PritamUpadhyay** [comment]
Hello,


Will it serve my purpose? I mean, What i really want to do is: I want to create a node.JS based mqtt server which will further communicate with RabbitMQ and from client side, client will connect to this node.JS based mqtt server. 




Sorry if I am bothering you.

 

Thanks & Regards,

Pritam Upadhyay.






Sent from Windows Mail





From: Matteo Collina
Sent: ‎Tuesday‎, ‎June‎ ‎2‎, ‎2015 ‎9‎:‎27‎ ‎PM
To: mqttjs/MQTT.js
Cc: pritam_upadhyay@hotmail.com





You can use the 'authorizeForward' method in Mosca: https://github.com/mcollina/mosca/blob/master/lib/server.js#L395-L407
