### ISSUE TITLE
client getting messages on all topics even not subscribed to

### ISSUE THREAD

**Issue by leothlon** [mqttjs/MQTT.js#293]
Hi.
i'm setting up a client that connects to my mosquitto broker, but i keep getting all messages on all topics.
i subscribed to "test/mqtt" and i still get messages on topic "not/subscribed/to"

i have even tried to unsubscribe to "#" and "/#" and i still get the messages..
i also get messages without having a single topic subscribed...

**Comment by w3hacker** [comment]
Delete mosquitto db file and restart it. mosquitto will store subscriptions if you connect with a clientid and set clean session flag to false.
