### ISSUE TITLE
How do i send received messages to rest api

### ISSUE THREAD

**Issue by infigon** [mqttjs/MQTT.js#297]
i have successfully implemented publish rest api, and tested with mosca and mosquitto

i am now building a rest api to subscribe and get messages

my question is how do i implement subscribe and send messages on rest api everytime data is published. like the console app.

is it possible ?

i am trying this

```
app.post('/mqtt/fetch/:topic',function(req,res){

		var topic = req.params.topic;

		var client = mqtt.connect('mqtt://localhost');

		client.subscribe(topic,function(err,granted){
			if(err){
				 return res.json({msg:"Failed to subscribe",err:err});
			}else{
				return res.json({msg:"Successfully subscribed",topic:granted.topic,qos:granted.qos});
			}
		})

		client.on("message", function(topic, payload) {
		  return console.log({topic:topic,payload:payload.toString()});
		  // return res.json({topic:topic,payload:payload.toString()}); throws headers already sent error
		  // client.end();
		});

	});
```

I am basically trying to build a web chat system . any suggestions ? thanks in advance

**Comment by RangerMauve** [comment]
REST APIs aren't good for push notifications. It'd be better to just have your MQTT client be client-side and have a custom broker with validation logic.

**Comment by RangerMauve** [comment]
Alternately you might want to look into [Server Sent Events](https://developer.mozilla.org/en-US/docs/Server-sent_events/Using_server-sent_events)

**Comment by infigon** [comment]
Thanks.. @RangerMauve  i will look into server sent events and Browserify for implementing mqtt client at browser
