### ISSUE TITLE
Which local ip to use?

### ISSUE THREAD

**Issue by behrad** [mqttjs/MQTT.js#298]
if my client has many ip addresses/interfaces, how can I tell mqttjs which source ip address to use for connecting to broker?

**Comment by mcollina** [comment]
Do you mind sending a PR to update https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/tcp.js#L16 to use this variant: https://nodejs.org/api/net.html#net_net_createconnection_options_connectionlistener

So you can pass the relevant parameters `localAddress` and `localPort`.

However, it seems that the same does not apply to TLS connections: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback. However, it might just be a doc issue, so please verify.

**Comment by behrad** [comment]
thank you, testing...

**Comment by mcollina** [comment]
Closing.
