### ISSUE TITLE
Bundled/ minified version of MQTT.js

### ISSUE THREAD

**Issue by sandro-k** [mqttjs/MQTT.js#300]
The Polymer [mqtt-elements](https://github.com/mqttjs/mqtt-elements) need to provide MQTT.js as a Browserify version. Usually custom elements are installed with `bower install REPO\PROJECT`, which works with MQTT.js but it will download all files contained within the repository. A better solution would be to put the Browserify version into a folder like `dist` and exclude all files not needed for web application inside a `bower.json` file. That would allow web application depending on `mqtt-elements` to transitively download the bundled version of MQTT.js

**Comment by sandro-k** [comment]
As an alternative [mqtt-elements](https://github.com/mqttjs/mqtt-elements) could provide the bundled version.

**Comment by RangerMauve** [comment]
I personally think that distributing the bundle with mqtt-elements would be a better alternative if you're planning on integrating them with bower anyways.

**Comment by sandro-k** [comment]
I agree and will bundle everything with the mqtt-elements

**Comment by mcollina** [comment]
:+1:!
