### ISSUE TITLE
browserify in WebWorkers

### ISSUE THREAD

**Issue by qm3ster** [mqttjs/MQTT.js#302]
Browserified version fails inside a Web Worker due to undefined document object.
Simply replacing
```javascript
    var url, 
          parsed = _URL.parse(document.URL);
```
with
```javascript
    var url, parsed;
    if (typeof(document) !== 'undefined') {
        parsed = _URL.parse(document.URL);
    }
```
fixes everything.
No further checks are really necessary, since it is known that the current URL can not be discovered from inside a worker. Of course this stems from evaluating **parse** even if it's unneeded, but the fix is more than sufficient.

**Comment by mcollina** [comment]
Can you please send a PR for that? Also a unit test in https://github.com/mqttjs/MQTT.js/blob/master/test/browser/test.js might be good.

**Comment by qm3ster** [comment]
.

**Comment by mcollina** [comment]
Fixed in https://github.com/mqttjs/MQTT.js/pull/303.
