### ISSUE TITLE
User name and password for MQTT connection

### ISSUE THREAD

**Issue by jingzhaoou** [mqttjs/MQTT.js#304]
My MQTT server requires user name and password for connection. For example, 
```
mosquitto_sub -t '#' -u 'username' -P 'password'
```
I am unable to see any username/password in the examples and the source code. Wonder if anyone can give me some help. 

Thanks,
Jingzhao

**Comment by mcollina** [comment]
You can pass `username` and `password` to `mqtt.connect`, as they are part of the CONNECT packet. I will leave this open, and it is probably worth to add them to the README.

Would you like to send a PR?

**Comment by jingzhaoou** [comment]
I tested the following options.
```js
    client = mqtt.connect({
        host: 'www.example.com',
        port: 1883,
        username: 'username',
        password: 'password'
    });
```
Things work properly.

**Comment by jingzhaoou** [comment]
Already submitted a PR.

**Comment by mcollina** [comment]
Thanks!
