### ISSUE TITLE
One-off request

### ISSUE THREAD

**Issue by farski** [mqttjs/MQTT.js#308]
Is it possible to make a one-off request to an end point (i.e. without needing to subscribe)?

**Comment by mcollina** [comment]
Yes of course, just don't do it.
Il giorno sab 11 lug 2015 alle 15:53 Chris Kalafarski <
notifications@github.com> ha scritto:

**Comment by farski** [comment]
@mcollina Why not? What's the alternative for getting data when using something AWS Lambda where it doesn't make sense to subscribe?

**Comment by mcollina** [comment]
Oh I thought you wanted to do it for a publish.

For a subscribe, you need to use retain messages when publishing, and those
will be sent to you when subscribing. So aftet the first messages, you just
disconnect.
Il giorno sab 11 lug 2015 alle 21:52 Chris Kalafarski <
notifications@github.com> ha scritto:

**Comment by tvanier** [comment]
Thanks for the amazing MQTT.js! I am prototyping a mqtt-based presence service, where clients publish online/offline retained messages, and `will: { payload: "offline", retain: true }`, subscribers are notified no problem. The prototype includes predictive user search, supporting one-off requests as @farski suggested would be great to presence-enable search results. I thought about a `fetch` API:

`client.fetch(topic/topic array/topic object, [callback])`
would retrieve  (possibly non-existent) retained messages under `topic`. `callback` would be in the form `callback(err, messages)`, where `messages` would be a single message, an array or object, depending on the `topic` argument. If `callback` is not provided, fetched messages would be returned through the existing `'message'` event.

Does MQTT include a "fetch" command? Or this would have to be a subscribe+unsubscribe?

**Comment by mcollina** [comment]
Sorry for not replying earlier. I hope you solved your issue.
I'll reopen if needed.
