### ISSUE TITLE
Subscribe everytime refresh page

### ISSUE THREAD

**Issue by arthurtalkgoal** [mqttjs/MQTT.js#312]
Hi,

I wanna subscribe a topic forever so I put it in my roUte, without closing it

'''
mqtt    = require('mqtt');
var client  = mqtt.connect('mqtt://test.mosquitto.org');

client.on('connect', function () {
  client.subscribe('presence');
  client.publish('presence', 'Hello mqtt');
});

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString());
  // client.end();
});

'''

However, it comes out it subscribe multiple times when user refresh the page.

What is the best way and place to keep subscription?

Thanks

**Comment by mcollina** [comment]
You should use it gobally, or better not use it at all in a web app server (it does not scale). If you need to do something for every published message, just use [mosca](http://npm.im/mosca) and put the behavior in there.

Read: http://www.nearform.com/nodecrunch/internet-of-things-how-to-build-it-faster/.
