### ISSUE TITLE
Mosca/MQTT.js downgrading my QoS request.

### ISSUE THREAD

**Issue by cefn** [mqttjs/MQTT.js#313]
QoS granted is less than requested for an unknown reason.

I'm initiating a subscription deliberately with QoS 2 like this...

    uplink.subscribe("#", {qos:2}, function(err, granted){
        that.emitter.emit("subscribe", [err,granted]);
    });

...but the granted array then evaluates as...

    [{"topic":"#","qos":1}]

What could be happening which would cause Mosca or my MQTT.js client to downgrade my QoS request. I can't seem to find any indication of this as expected behaviour and it could be problematic to receive multiple notifications after failure for some reason.

The client is initiated as...

    uplink = mqtt.connect(mqttWsAddr);

...where mqttWsAddr is the websockets URL of the Mosca server launched with the following options...

```
        var moscaOpts = {
            backend: {},
            logger: {},
            stats: true,
            port:null,
            persistence: {
                factory: persistence.Memory
            },
            http:{
                port:conf.mqttWsPort,
                static:false,
                bundle:false
            },
            onlyHttp:true
        };
```

**Comment by mcollina** [comment]
Mosca only supports QoS 1, it's stated in the README.
