### ISSUE TITLE
support mozTCPSocket

### ISSUE THREAD

**Issue by rednaks** [mqttjs/MQTT.js#314]
It's not a standard yet, but that would be nice to support mozTCPSocket, which is supported by FirefoxOS.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mozTCPSocket

**Comment by mcollina** [comment]
If it has minor impact, I would consider a PR that supports that.

Any other opinions?
Il giorno sab 22 ago 2015 alle 11:46 Alexandre BM <notifications@github.com>
ha scritto:

**Comment by RangerMauve** [comment]
If the code to enable it isn't very long then I think it'd be a very good idea. Maybe make it so it supports the unprefixed version just in case it becomes standardized. If it takes a lot of code, then I would suggest just having a stream wrapper and using that as a separate library so that there isn't needless bloat.

**Comment by itavy** [comment]
Hi,

I think if we can refactor the transport and separate it fron the protocol
we will be able to support more in the future. My ideea is to make a
factory for transports and each type has its own module. Atm i am not able
to look and make a PR but in about 2 weeks i will be able to look and see
how it can be separated

**Comment by mcollina** [comment]
I'm all in in for more modularity.

Alexandre, is there a module that wraps TCPSocket in a Node stream? I think
that would be the first step.
I'm also new to that standard, does it support SSL?

Il giorno sab 22 ago 2015 alle 18:12 itavy <notifications@github.com> ha
scritto:

> Hi,
>
> I think if we can refactor the transport and separate it fron the protocol
> we will be able to support more in the future. My ideea is to make a
> factory for transports and each type has its own module. Atm i am not able
> to look and make a PR but in about 2 weeks i will be able to look and see
> how it can be separated

**Comment by rednaks** [comment]
I agree with @RangerMauve .

@mcollina I'm not a NodeJS guy I'm only working on the browser side. but yes, it does support SSL. it's raw sockets for the web.
you can find the description of the `TCPSocket` interface here : https://developer.mozilla.org/en-US/docs/Web/API/TCPSocket

**Comment by mcollina** [comment]
MQTT.js requires a node duplex stream. I think it would not be too hard to
do that, the functionality is similar. A similar wrapper is
http://npm.im/websocket-stream.
Il giorno sab 22 ago 2015 alle 22:58 Alexandre BM <notifications@github.com>
ha scritto:

**Comment by mcollina** [comment]
Closing, feel free to reopen if needed.
