### ISSUE TITLE
How to Sub for Clean / Persistent Sessions 

### ISSUE THREAD

**Issue by mnbao1975** [mqttjs/MQTT.js#316]
Hello mcollina,

I would like the mosca broker to keep messages (including QoS 1 or 2) for offline subscribers. But I cannot find any instructions on the MQTT.js.

On the broker side, I use mongod for backend and persistence settings.
var moscaSettings = {
  port: 1883,
  backend: ascoltatore,
  persistence: {
    factory: mosca.persistence.Mongo,
    url: 'mongodb://my.host.com:27017/mqtt',
  }
};

On the publisher side, I send out message each sec with "qos: 2":
client.on('connect', function () {
	setInterval(function(){
		var msg = {
			pid: process.pid,
			timestamp: Date.now()
		};
		client.publish("mqtt/demo", JSON.stringify(msg), {qos: 2});		
	}, 1000);
});

On the subscriber side, I just print out the message:
client.on('connect', function () {
	client.subscribe({'mqtt/demo': 2}, function(err, granted){
		console.log(granted);
	});
});

client.on('message', function (topic, message) {
	// message is Buffer	
	var msg = JSON.parse(message.toString());
	console.log(msg.pid + ': ' + new Date(msg.timestamp));
});
 
But, when I stop and run again the subscriber, the messages had sent while it was offline are lost. So, how can the subscriber get those offline messages back when it reconnect to the broker?

Many thanks,
Bao

**Comment by mnbao1975** [comment]
Hi mcollina,

I know where I can do that.

var options = {
	clientId: 'mqttjs_' + 'persistence', //unique Id for persistence
	clean: false
}

var client  = mqtt.connect('mqtt://localhost:1883', options);

Thanks,
Bao

**Comment by mcollina** [comment]
Perfect!
