### ISSUE TITLE
CLI --key & --cert Fails

### ISSUE THREAD

**Issue by philmaker1** [mqttjs/MQTT.js#317]
This following lines of code in the project appear to be referencing a value which does not yet exist.

https://github.com/mqttjs/MQTT.js/blob/master/bin/pub.js#L52
https://github.com/mqttjs/MQTT.js/blob/master/bin/pub.js#L56
https://github.com/mqttjs/MQTT.js/blob/master/bin/sub.js#L52
https://github.com/mqttjs/MQTT.js/blob/master/bin/sub.js#L56

Philip

**Comment by mcollina** [comment]
Hi @philmaker1! Would you mind sending a PR to fix them?

Thanks!

**Comment by mcollina** [comment]
Fixed long ago.
