### ISSUE TITLE
mqtt.js compile error after updating node 4.0

### ISSUE THREAD

**Issue by yangpu** [mqttjs/MQTT.js#318]
windows 10, 64 bits, compile error after updating node 4.0:

error C2988: unrecognizable template declaration/definition 

looks like v8.h header file has been changed dramatically in version 4.5.

**Comment by mcollina** [comment]
The library should install fine, all binaries should be optional. Also, I
believe this to be specific to the ws module.
Il giorno dom 13 set 2015 alle 11:47 yangpu <notifications@github.com> ha
scritto:

**Comment by mcollina** [comment]
This should be fixed.
