### ISSUE TITLE
Server rotation bug

### ISSUE THREAD

**Issue by piotrmach** [mqttjs/MQTT.js#320]
If I try to connect, providing multiple servers like this:

      var  mqtt_urls = [
                { host:'firstmqq.server', port:1883 },
                { host:'someother.mqtt.server', port:1883 } 
      ];
      var  mqtt_auth = 'mypass:mylogin';

and then:

      mqtt.connect( { servers: mqtt_urls, auth: mqtt_auth } );

It won't work.

*Adding:*

           opts.host = opts.servers[client._reconnectCount].host;
           opts.port = opts.servers[client._reconnectCount].port;
           +opts.hostname = opts.host;

to /lib/connect/index.js  **fixes it** (but it was hard to find) Can you merge or fix it other way?

**Comment by mcollina** [comment]
Can you please send a PR? If you could add a test, we will be sure not break it again.

**Comment by piotrmach** [comment]
PR ready, dont'have time for a test now, maybe another day. 
I don't think it's a best possible fix anyway, it just mixes host with hostname somewhere and reconnect to the same host all the time, istead of rotating

**Comment by piotrmach** [comment]
Test done. Works for me..

**Comment by mcollina** [comment]
Fixed by #321.
