### ISSUE TITLE
Future of mqtt-stack and mqtt-spec.

### ISSUE THREAD

**Issue by 256dpi** [mqttjs/MQTT.js#322]
Hi all collaborators and contributors

I recently began switching the code base of shiftr.io away from node.js to golang. In the process, other golang contributors and I created the [gomqtt](https://github.com/gomqtt) organization that will provide libraries and tools for the go world.

In that sense I am no longer capable of actively contributing to this project and finishing the [mqtt-stack](https://github.com/mqttjs/mqtt-stack) and [mqtt-spec](https://github.com/mqttjs/mqtt-spec) projects which I started a while ago in this organization. Therefore, I would like to hand over the responsibility of these projects. You can freely decide if you want to continue these tools or let them rest in commits (pieces).

For the future, all the best!

@mcollina Thanks for the collaboration, and please decide as you see fit!

**Comment by mcollina** [comment]
I'm willing to take over mqtt-spec, while I will probably neglect mqtt-server. Any volunteers for mqtt-server?

**Comment by kokeksibir** [comment]
I would like to take over mqtt-server. Is there a documented road map or design, or at least a clear vision in your mind, how may I help?

**Comment by 256dpi** [comment]
The idea of mqtt-stack was basically to provide an "express" like way for building MQTT brokers.
As with express, the developer and can build his app out of middlewares that integrate in the stack and together provide the functionality of a broker. That way, one can easily use standard middlewares, while implementing a custom backend or authentication mechanism. The code is documented and there is also an [example](https://github.com/mqttjs/mqtt-stack/blob/master/example.js) which should give you an idea.

**Comment by mcollina** [comment]
@kokeksibir I've added you to the mqtt-server group in github, you have commit access now. Let me know your npm handle so that I can add you there as an owner.

**Comment by 256dpi** [comment]
Cool to see that the projects will be continued! Please ask me if you need more detailed information about the projects.

**Comment by kokeksibir** [comment]
@mcollina thank you very much, my npm account is also kokeksibir.

**Comment by mcollina** [comment]
Done :)
