### ISSUE TITLE
Full path leaked into browserified mqtt.js.

### ISSUE THREAD

**Issue by bentinata** [mqttjs/MQTT.js#323]
Mostly it's `insert-module-globals` package.

**Comment by mcollina** [comment]
Nice one. Which path? Would you mind sending a PR to fix it?
Il giorno dom 27 set 2015 alle 12:45 Benget Immanuel Nata <
notifications@github.com> ha scritto:

**Comment by mcollina** [comment]
Probably fixed, feel free to reopen in case.
