### ISSUE TITLE
Expecting an error event if connect timeout.

### ISSUE THREAD

**Issue by vilic** [mqttjs/MQTT.js#325]
#287 

And when would we expect an error event? Is there a brief categories?

**Comment by mcollina** [comment]
The reality is the exact opposite. You won't get an error event, but it will automatically try again. You would get an 'offline' event, followed by a 'reconnect' event.
What do you mean by "brief categories"?

**Comment by vilic** [comment]
I see, thanks.

It's not clear when an error event would be emitted, and this could be confusing. It would be great if we can have a brief categories of possible error events.
