### ISSUE TITLE
Strong network load since MQTTjs, how to debug ?

### ISSUE THREAD

**Issue by vallettea** [mqttjs/MQTT.js#332]
Hello,

We've moved our sensor infrastructure from a basic tcp socket to mqtt.
Since then the network load has been multiplied by about 30.
The mqtt logic may surely add some overhead but not that much.
We change the heartbeat to 60 seconds but still.

We are looking into what can cause this abnormal consumption. Do you have any techniques to monitor the network load ?
We are about to log every single message on the mosca broker part but it might not be enough ?

Thanks

**Comment by mcollina** [comment]
Are we talking about sensor -> broker load, or something else?

I suggest you to use wireshark to check what data is flowing through. Maybe you did a wrong subscription on the device end, and too much data is coming down.

**Comment by vallettea** [comment]
We are monitoring what we pay to the M2M provider.
I'll look to wireshark. thanks

**Comment by mcollina** [comment]
BTW, the heartbeat should be in the order of minutes, not seconds. Good values are 15 min/30 min/1 hour, depending on your connection.

**Comment by vallettea** [comment]
It was in fact related to the heartbeat which was too short.
