### ISSUE TITLE
Problems with authentication

### ISSUE THREAD

**Issue by ajsharp** [mqttjs/MQTT.js#336]
I'm using the latest stable version of MQTT.js (1.4.3) and latest stable of mosca (0.32.1). I'm trying to authenticate with the mosca server using the browserify'd version of mqtt.js. I'm connecting over websockets.

The documentation says, in order to authenticate use the `username` and `password` keys in the `options` hash. However, I found that on the server, the username / password only gets passed on to the `authenticate` function if i specify it in the `auth` key in the form of "username:password". Is this a known issue / websockets thing, or a bug? Thanks.

**Comment by mcollina** [comment]
I think this is a bug. Maybe you can send a PR with a couple of unit tests for it!

Browser tests lives in https://github.com/mqttjs/MQTT.js/tree/master/test/browser
Run `npm run browser-test` to run them.

**Comment by sandro-k** [comment]
I am using MQTT.js in <mqtt-elements> and the `username` and `password` options work for me, can you please try http://mqttjs.github.io/mqtt-elements . Just click on the asterisk and add your `username` and `password`

**Comment by ajsharp** [comment]
@sandro-k Are you using it over websockets? Also what versions are you using of each? Are you using mosca on the backend?

**Comment by sandro-k** [comment]
Yes I am making the connection over WebSockets in the browser. Just checked - [mqtt-elements](https://github.com/mqttjs/mqtt-elements/) uses MQTT.js (1.3) I am going to upgrade and check if it is still working. You can test your own backend over at http://mqttjs.github.io/mqtt-elements it is a live Web dome that runs in the browser

**Comment by ajsharp** [comment]
FWIW, I did a trace as to where the auth stuff ends up, and it's in this function: https://gist.github.com/ajsharp/4178e69d3b545ec0a437#file-mqtt-js-L1162.

**Comment by sandro-k** [comment]
Maybe I am missing something hear but... 

```
var options = {username: "FOO", password: "BAR"}
mqtt.connect("ws://HOST:PORT", options);
```

Then on https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/index.js#L32

opts will have 

```
opts.username 
=> FOO

opt.password
=> BAR
```

**Comment by ajsharp** [comment]
On current master -- https://github.com/mqttjs/MQTT.js/blob/2c282409dcf6962aaac7cde3ce0abe1a119135a7/lib/connect/index.js#L66 -- the `connect` function calls `parseAuthOptions`, which only looks at the `auth` key, and sets the username and password by splitting `auth` on the the `:` character.

**Comment by sandro-k** [comment]
Yes it will do that.. there is no point in 

```
opts.username = opts.username
opts.password = opts.password
```

As long as

```
opts.auth
=> null
```
the `username` and `password` will not be overwritten.

**Comment by ajsharp** [comment]
:( The problem is I was passing in values like this:

```js
mqtt.connect("ws://HOST:PORT", {
  options: {
    username: 'name',
    passwore: 'pass'
  }
});
```

Basically I misread the documentation on the homepage. Apologies for the confusion.

**Comment by sandro-k** [comment]
You are welcome.. happy mqtting :)

**Comment by sandro-k** [comment]
@ajsharp If you like yo update/ add something to the documentation PR are always welcome :+1:
