### ISSUE TITLE
TLS examples do not seem to work

### ISSUE THREAD

**Issue by jmeas** [mqttjs/MQTT.js#339]
**Type:** Documentation error

**Node/npm versions**:
- Node 4.2.1 + npm 2.14.7
- Node 0.12 + npm 2.13.2

**Description of error:** The clients never connect in neither the "tls server" nor "tls client" examples. This is unrelated to the problem described in #249 , which I fixed locally then PR'd in #338 

**Expected behavior:** The callbacks specified for the connect event would be called in each of the examples. It is not called in either example.

**Comment by mcollina** [comment]
Would you like to send a PR to address this one as well?

**Comment by jmeas** [comment]
I definitely would! The only problem is that I wasn't able to figure out the problem...

I made an example using the configuration for my specific app, and I was able to get it working. So I'm not sure what the problem is. If I take another look and figure it out, I'll PR the fix.

**Comment by mcollina** [comment]
I think it should pass `key` and `cert` vs `keyPath` and `certPath`.

**Comment by jmeas** [comment]
Ah! Okay, cool. I'll take a look and PR it up today.

**Comment by ryankurte** [comment]
The secure-client example appears to be broken because the arguments `keyPath: KEY,
  certPath: CERT` should in fact be `ca: CA, key: KEY, cert: CERT` to match the node TLS options.
Once changed this works against a mosquito setup with TLS and client authentication.

**Comment by dmeznaric** [comment]
You can specify which protocol should be used by passing brokerUrl parameter on connect. 

this configuration works fine for me:
```
var KEY = fs.readFileSync(__dirname + '\\mqttServer_key.pem');
var CERT = fs.readFileSync(__dirname + '\\mqttServer_b64.cer');
var TRUSTED_CA_LIST = fs.readFileSync(__dirname + '\\CA_b64.cer');

var PORT = 8883;
var HOST = 'mqttServer';

var options = {
  port: PORT,
  host: HOST,
  keyPath: KEY,
  certPath: CERT,
  rejectUnauthorized : true,
  //The CA list will be used to determine if server is authorized
  ca: TRUSTED_CA_LIST,
  will: {
    topic: 'node/status',
    payload: new Buffer('offline')
  }
};

var client  = mqtt.connect('mqtts://mqttServer', options);
```

**Comment by jameswhite** [comment]
`var client = mqtt.connect('mqtts://' + HOST, options);`

**Comment by dashracer** [comment]
How can I generate certificate for mqtt client?

**Comment by jameswhite** [comment]
@dashracer: https://github.com/mokjpn/hubot-mqtt/blob/master/doc/easy-rsa

The client and server must both agree on a CA. There's an included [mosquitto.conf](https://github.com/mokjpn/hubot-mqtt/blob/master/etc/mosquitto/mosquitto.conf) one can use for testing. the hubot-mqtt uses MQTT.js.

**Comment by mcollina** [comment]
I think all of this is fixed.
