### ISSUE TITLE
memory leak in MQTT.js?

### ISSUE THREAD

**Issue by liujian883** [mqttjs/MQTT.js#342]
hi,
I am new for node.js and MQTT.
I use the code lines below to receive message:
rev.js

```
var mqtt    = require('mqtt');
var client  = mqtt.connect('mqtt://192.168.0.76:8000');

client.on('connect', function () {
    client.subscribe('other');
    client.publish('other', 'Hello mqtt');
});

client.on('message', function (topic, message) {
});
```

and code lines below to publish message:
pub.js:
```
var mqtt = require('mqtt');
var client = mqtt.connect('mqtt://192.168.0.76:8000');
setInterval(function (){
    client.publish('other', 'Hello mqtt 1');
}, 1);
```
I use pm2 to start the rev.js,and find that the memory of the rev.js process grow up quickly(almost to 30 MB) .then I stop the pub.js, after a while, the memory of the rev.js process doesn`t decrease.

is there any memory leak in node.js or MQTT.js module???

and I also make a test about the node.js buffer.
buffer.js:
```
setInterval(function(){
    var loop = 10000;
    var buf1_ary = [];
    while(loop--){
        buf1_ary.push(new Buffer(4096));
    }
    buf1_ary = null;
},1000);
```
I use pm2 to start this buffer.js. and i find that ,the memory will grow up very quickly(at least several hundred MB )

node.js version is 0.10.36.

so I am afraid of the memory of  node.js now.
THANKS!!!

// edited by sandro.k to properly display code examples

**Comment by mcollina** [comment]
v0.10 is known to have a bad garbage collector. You should probably switch to node v4.
However, the default behavior of node v0.10 is to eat up all your memory before collecting anything (I'm oversimplifying).
