### ISSUE TITLE
reconnectPeriod does not work when >= 30,000

### ISSUE THREAD

**Issue by 4rzael** [mqttjs/MQTT.js#346]
When reconnectPeriod is set to a value >= 30,000, the reconnection does not work.

###### Note: In fact, it looks like the threshold is a little bit under 30K, between 29,900 and 29,950

With a wireshark scan, we can see that the SYN packet from the client (192.168.20.35 in the picture below) is not re-sent as it should.

#### Here's a (not working) example with reconnectPeriod set to 30,000: 

![mqttbug](https://cloud.githubusercontent.com/assets/9220115/11143546/29d5be94-89f6-11e5-9467-d6f96c742273.png)

I waited for a few minutes, but this is the only packet sent...

#### Here's a (working) example with reconnectPeriod set to 1,000 (default value):

![mqttworks](https://cloud.githubusercontent.com/assets/9220115/11143609/b3959802-89f6-11e5-8622-2bc47dea5400.png)

We can see here that the SYN packet is sent every seconds, as it should.

**Comment by mcollina** [comment]
So, it seems there is some problem at the networking level. Not sure we can handle this case in JS land. Are you running this in a controlled environment? Which version of node are you using?

I'd really welcome a PR to address this problem, but I have little clue on where that could be.

**Comment by 4rzael** [comment]
I'm using node v0.10.40.

In this test case, the client is an odroid C1 (a raspberry pi clone) directly connected to my computer (I run wireshark on the computer) through an ethernet cable, so there shouldn't be any packet-loss or something like that..

**Comment by mcollina** [comment]
Do you experience the same problem when running the code on your computer?
Il giorno ven 13 nov 2015 alle 12:43 Agor Maxime <notifications@github.com>
ha scritto:

**Comment by 4rzael** [comment]
Yes, my client does not reconnect.

On my computer, I tried with a very simple client:

```js
'use strict';

var mqtt = require('mqtt');
var PRIVATE = require('./PRIVATE.json');


// mqtt client
var client;

client = mqtt.connect('mqtt://127.0.0.1:1883',
    {
        username: 'ninja',
        password: PRIVATE.connectInfo.password,
        clientId: 'ninja',
        keepalive: 0,
        clean: false,
        reconnectPeriod: 30000
    });

client.on('connect', function(){
    console.log('connected to the server.');
});

client.on('message', function(topic, message) {
    console.log("data received : " + message.toString());
});
```

With this code, that does nothing but trying to connect to mqtt, the client code exit after 30 seconds when it's not connected.

So it looks like there is no `setInterval`/`setTimeout` running (I suppose that MQTT.js uses one of those in order to reconnect after a delay ?).

**Comment by 4rzael** [comment]
## Update:

The 29.9 seconds threeshold seems to be plateform dependant. For example, on a Raspberry Pi 2 under debian Jessie (node v0.10.40), even 29 seconds doesn't work.
