### ISSUE TITLE
mqtt.js 1.5.0 CLI get stuck

### ISSUE THREAD

**Issue by roccomuso** [mqttjs/MQTT.js#348]
This is just something I would like to point out.

Running this command, the mqtt.js CLI 'freezes' with no response:

     mqtt publish -h '192.168.1.12' -t 'anyone' -m 'hello world' -u 'megatron' -p 'ciao123'

Because mistakenly using the lower case -p instead of -P to specify the password (mqtt.js acts as 'ciao123' was the port number..).

I don't know if this is worth a 'fix', but can't be useful some kind of hint/error in this scenario?

**Comment by mcollina** [comment]
It is worth a fix.

We should:

1) emit an error if credentials are wrong, and catch it in the CLI
2) validate that the port is a number

Would you mind sending a PR?
Il giorno dom 15 nov 2015 alle 18:52 Rocco Musolino <
notifications@github.com> ha scritto:
