### ISSUE TITLE
Hot swapping mqtt broker

### ISSUE THREAD

**Issue by pedro93** [mqttjs/MQTT.js#350]
Hey guys, I am trying to develop a website where I have a form to connect to a default MQTT broker. I want to be able to hot swap the mqtt broker whenever requested by the user. Currently I am able to only change topic. Could anyone tell me what im doing wrong?

```javascript
       var message, host, port, topic;
        host = 'tum.smartcityhub.net';
        port = 9883;
        topic = 'iCatch';
        var messageCount = 0;
        var client = mqtt.connect({ host: host, port: port });
        $('.formDiv div input[name="host"]').val(host)
        $('.formDiv div input[name="port"]').val(port)
        $('.formDiv div input[name="topic"]').val(topic)
        client.subscribe(topic);

        client.on('message', function(topic, message) {
            messageCount++;
            message = '<div>Message ' + messageCount + ' ['+topic+']: ' + message + '</div>';
            $('.messages').append(message);
        });

        $('button').click(function(){
            client.unsubscribe(topic);
            host = $('.formDiv div input[name="host"]').val()
            port = $('.formDiv div input[name="port"]').val()
            topic = $('.formDiv div input[name="topic"]').val()
            client.end();
            client = mqtt.connect({ host: host, port: port });
            client.subscribe(topic);
        });
```

**Comment by sandro-k** [comment]
Hey, looking at you code it is hard to tell what is not working. But my guess is that you crate a new client in ` $('button').click(function()` and to not re-register the `client.on('message', function(topic, message) ` function to the client..

```

 $('button').click(function(){
            client.unsubscribe(topic);
            host = $('.formDiv div input[name="host"]').val()
            port = $('.formDiv div input[name="port"]').val()
            topic = $('.formDiv div input[name="topic"]').val()
            client.end();
            client = mqtt.connect({ host: host, port: port });

             client.on('message', function(topic, message) {
                messageCount++;
                message = '<div>Message ' + messageCount + ' ['+topic+']: ' + message + '</div>';
                $('.messages').append(message);
              });

            client.subscribe(topic);
        });

```

As a side note we have a wrapper for MQTT.js (mqtt-elements)[https://github.com/mqttjs/mqtt-elements] to use it in a Polymer project, maybe that is something you would like to look at :)

**Comment by pedro93** [comment]
Hey @sandro-k, thank you very much for your response. Your code does work, I will try to find a more eloquent and efficient way to write it. About mqtt-elements, it is very interesting but I think it wont allow me to dynamically change the MQTT broker I am speaking with, atleast without refresh the corresponding html (I don't know im supposing).  You may close this issue, and thanks again :)

**Comment by sandro-k** [comment]
@pedro93 Have a look at https://github.com/mqttjs/mqtt-elements/blob/master/demo/elements/demo-element.html#L248, I am calling `disconnect` and `connect` on the `<mqtt-connection>` element in between you are able to change the broker url. A live demo is online here http://mqttjs.github.io/mqtt-elements/. I am closing this issue here. You can open up one at `<mqtt-elements>` if you like to have more information.
