### ISSUE TITLE
Why does common messages are not considered as heartbeats ?

### ISSUE THREAD

**Issue by vallettea** [mqttjs/MQTT.js#353]
Heartbeats consume quite a lot of data, and i'm considering switching it off, with `keepalive: 0`.
However, I noticed I don't receive an `offline` events after this though I publish so data on various channels.
Why are these messages (at least the ones with qos 1 or 2) not considered as heartbeats ? It seems it could be easily implemented with the publish callback ?

**Comment by mcollina** [comment]
Yes! Would you like to send a PR?
