### ISSUE TITLE
URL with path??

### ISSUE THREAD

**Issue by mkarliner** [mqttjs/MQTT.js#356]
I'm trying to connect to a Jetty based mqtt broker which is mounted on a path of '/ws' over SSL.
I'm doing this with the browser version of mqtt.js
I've managed to connect with HiveMQ's websocket client http://www.hivemq.com/demos/websocket-client/, which is Paho based.
My question is, how do I achieve the equivalent of Paho's 'path' option?
http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html
If I include use wss://myhost/ws as my URL, mqtt.js tells me

_WebSocket connection to 'wss://myhost/' failed: Error during WebSocket handshake: Unexpected response code: 302_

Which sort of implies that the path part of the URL is not getting sent to the host.

**Comment by mcollina** [comment]
I think that should be supported. You should place some console log in https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/index.js and https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/ws.js, and possibly send a PR.

This is definitely not standard anyway, and I recommend deploying it to /mqtt (as the spec prescribes).

**Comment by mkarliner** [comment]
I've already been hacking my copy of index.js and ws.js to start tracking down where this is occurring, and I can confirm that the path is being dropped.  

I'm afraid that this is not my deploy, but the argument for supporting arbitrary paths is as follows. The broker to which I'm connecting (which is a homebrew), is sitting behind an nginx instance, and that requires the path to ascertain where to route to, as there is also regular http traffic going over it.
 
I didn't realise that the spec called for a standard path of /mqtt.

cheers

Mike

**Comment by mcollina** [comment]
@mkarliner would you mind sending a PR to fix this?

**Comment by mkarliner** [comment]
Certainly, when I find what is doing it :-) Any clues much appreciated.

**Comment by mcollina** [comment]
Not really, I should set something up and test this.
Il giorno mer 9 dic 2015 alle 11:14 Michael Karliner <
notifications@github.com> ha scritto:

**Comment by sandro-k** [comment]
@mkarliner can you try to use http://mqttjs.github.io/mqtt-elements/ to test your setup. The demo uses the browserify version of MQTT.js. At work I have a broker running at wss://HOST/api/ws/ and the connection works without any issues.

**Comment by mkarliner** [comment]
@sandro-k, I'm afraid I can't check with mqtt-elements against the target broker as it requires a specific clientID, and elements doesn't appear to support that.

@mcollina , I haven't been able to find the part of the spec that recommends the /mqtt path. I'd like to be able to show that to the person who has deployed the broker. Could you point me to the relevant section? Thanks.

**Comment by sandro-k** [comment]
@mkarliner I am going to change the demo to to make it possible to set a user defined client id. In the mean time you can open up a console in the browser and type 
```
document.querySelector("mqtt-connection")._generateClientId = function () {return "myClientId"}
```

and change "myClientId" to your ID before hitting connect.

**Comment by mkarliner** [comment]
@sandro-k  Excellent! It doesn't work in exactly the same way as my own client doesn't work :-)
That is, in your client I see the connection status go briefly green and then red again.

In the network section of Chrome, I can see an initial GET to the broker with a status
of '101 Switching protocols' followed by a response header of upgrade to websocket, after which
the 'offline' event is fired with no other information. I can also see that the response header on the upgrade has got Sec-WebSocket-Protocol:mqttv3.1. 
Now, I have tried 
{
  protocolId: 'MQIsdp',
  protocolVersion: 3
}

in the options in my client, to go down to mqtt 3.1, but it makes no difference.
BTW, this is after creating a new browser.js for my client, as it was pretty stale.

**Comment by knolleary** [comment]
Just to chip in, the 3.1.1 spec does not require a path of `/mqtt` - that was part of an earlier proposal, but it was decided that requiring a specific path would be far too restrictive - for example if you wanted to handle multiple websocket endpoints for different MQTT clients.

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718127

**Comment by mcollina** [comment]
@knolleary thanks for the clarification!

Anyway, we should solve this. @sandro-k have you got some bandwidth for solving this one?

**Comment by sandro-k** [comment]
Not in this week, back in the office in the new year.
Am 23.12.2015 2:52 nachm. schrieb "Matteo Collina" <notifications@github.com

**Comment by mkarliner** [comment]
@mcollina @sandro-k  @knolleary   
Sorry all. I should have posted the final resolution of this.
The original problem about the path was fixed when I refreshed 
my browserified version of the code. The bouncing connection was different.
Basically, the writer of the broker had implemented code that disconnected the client if it subscribed to 'invalid' topics. Invalid in this case meant that it didn't follow his particular naming conventions.
The result was that I saw the bouncing client connection.
So the conclusion is that I now have a working connection with this broker, and the library does not have a bug.

As a final note, this is what the broker's author said.

_Welcome to MQTT, the protocol with out any error codes.
Dropping connection on error is the lesser of many evils, we think its worse to say OK! when a device is trying to subscribe but actually some topics aren't allowed._

Is it true that there is no way in the standard for a broker to return an error code on subscription?

Mike

**Comment by mcollina** [comment]
> Dropping connection on error is the lesser of many evils, we think its worse to say OK! when a device is trying to subscribe but actually some topics aren't allowed.

That is not correct. A broker can return qos >= 128 to say it was not allowed. However, there is no error code for the PUBLISH command.
