### ISSUE TITLE
Mqtt connection is closed frequently because mqtt broker thinks the client is offline.

### ISSUE THREAD

**Issue by blbird** [mqttjs/MQTT.js#357]
I look over the recent changes that have rescheduling for ping request. 

I thinks this is the cause of my problem. 

According to below part of mqtt specification, PINGREQ seems not to be related to data from server. 

############################################
The PINGREQ Packet is sent from a Client to the Server. It can be used to:
Indicate to the Server that the Client is alive in the absence of any other Control Packets being sent from the Client to the Server.
Request that the Server responds to confirm that it is alive.
Exercise the network to indicate that the Network Connection is active.
############################################

Therefore, I think that the client must send ping request regardless the data from server. So, please reconsider this change.

Thanks.

**Comment by mcollina** [comment]
This is not really helpful. According to my understanding of the 3.1.1
spec, that is valid. However, that behavior might not be supported by old
brokers. Which broker are you using? On which version? Can you upload a
snipper?

This is the relevant part of the spec:

If the Keep Alive value is non-zero and the Server does not receive a
Control Packet from the Client within one and a half times the Keep Alive
time period, it MUST disconnect the Network Connection to the Client as if
the network had failed [MQTT-3.1.2-24].

Il giorno gio 10 dic 2015 alle 00:46 blbird <notifications@github.com> ha
scritto:

**Comment by blbird** [comment]
You're right. 
Server must disconnect to the Client as if the network had failed. So, my client is disconnected.

However, the current client implementation doen't send the PINGREQ when the client receive data from server. So, the broker disconnect client connection because the broker doesn't get PINGREQ data from client.

As the below client code, ping request interval is reset when the client receive data from server because of calling _shiftPingInterval().

MqttClient.prototype._handlePacket = function (packet, done) {
  switch (packet.cmd) {
    case 'publish':
      this._handlePublish(packet, done);
      break;
    case 'puback':
    case 'pubrec':
    case 'pubcomp':
    case 'suback':
    case 'unsuback':
      this._handleAck(packet);
      done();
      break;
    case 'pubrel':
      this._handlePubrel(packet, done);
      break;
    case 'connack':
      this._handleConnack(packet);
      done();
      break;
    case 'pingresp':
      this._handlePingresp(packet);
      done();
      break;
    default:
      // do nothing
      // maybe we should do an error handling
      // or just log it
      break;
  }
  // When a packet is received, reschedule the ping timer
  this._shiftPingInterval();
};

I'm using IBM IoT Foundation(https://internetofthings.ibmcloud.com) as MQTT Broker. However, I don't know which broker is used in IBM IoT Foundation.

Thanks.

**Comment by 4rzael** [comment]
Hum, yeah, that's true. I think I misunderstood the spec, sorry.

Here is another useful part of the spec:
> It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet [MQTT-3.1.2-23]

The current implementation can fail, for example, if the client receives a QoS 0 message. (so it does not answer with a Control Packet)

We should reschedule the ping timer only when sending Control Packets, instead of doing it when receiving Control Packets, as written in the MQTT spec.

**Comment by 4rzael** [comment]
@blbird I think #358 should fix it, but I can't test it right now, could you check if it fixes your bug ?

**Comment by blbird** [comment]
@4rzael It works well. Thanks. :-)
