### ISSUE TITLE
mqtt-packet module version

### ISSUE THREAD

**Issue by dmeznaric** [mqttjs/MQTT.js#363]
Is there any particular reason why "mqtt-packet" module major version 3.x.x is still used against the latest version 4.0.3? 

https://github.com/mqttjs/MQTT.js/blob/master/package.json
```
"dependencies": {
    "mqtt-packet": "^3.2.0",
    ...
  }
```

**Comment by mcollina** [comment]
mqtt-packet v4.x.x breaks compatibility with node 0.8, which this MAJOR version of MQTT.js still support.
The pull request #345 contains the next MAJOR version of MQTT.js, which breaks some backward compatibility, including v0.8 support. If you want to help, feel free to chip in.
