### ISSUE TITLE
Server authentication

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mqttjs/MQTT.js#365]
Using the server there is no way that I can see of authenticating a user, I added the following but when an incorrect username or password is sent I get an uncaught exception even if I wrap connect in a try catch. 

	  client.on('connect', function(packet) {
		//console.log(packet);
		self.clients[packet.clientId] = client;
		client.id = packet.clientId;
		console.log("CONNECT: client id: " + client.id);
		client.subscriptions = [];
		if(packet.username !== appData.mqttUser || packet.password.toString() !== appData.mqttPassword){
			client.connack({returnCode: 4});
			client.stream.end();	
			delete self.clients[client.id];
		}
		client.connack({returnCode: 0});
	  });

Please could you let me know what docs or code I can use to fix the above.

**Comment by mcollina** [comment]
The server will be removed in v2.
