### ISSUE TITLE
Prefetch on RabbitMQ breaks subscription

### ISSUE THREAD

**Issue by nfantone** [mqttjs/MQTT.js#367]
I'm using [RabbitMQ](www.rabbitmq.com) + MQTT plugin as my backend broker with `mqtt.js` and I'm having a hard time getting things to work for messages with QoS > 1.

Here's my scenario: two separate standalone scripts - one publishes random messages, the other subscribes to the topic and consumes them. Basic stuff.

### publisher.js
```javascript
var mqtt = require('mqtt');
var client = mqtt.connect('mqtt://rabbit.dev.enterprise.com.ar:1883', {
  username: 'some_user',
  password: 'some_secret'
});
client.on('connect', function() {
  setInterval(function() {
    var message = JSON.stringify({
      id: Math.random() * 100,
      from: 'Me',
      message: (Math.random().toString(36) + '00000000000000000').slice(2, 7 + 2)
    });
    client.publish('mqtt/test', message, {
      qos: 1
    }, function() {
      console.log('Message sent');
    });
    console.log('Published ', message, 'to mqtt/test');
  }, 2000);

});

process.once('SIGINT', function() {
  client.end(function() {
    console.log('Client ended connection to broker');
    process.exit();
  });
});
```

### subscriber.js

```javascript
var mqtt = require('mqtt');
var client = mqtt.connect('mqtt://rabbit.dev.enterprise.com.ar:1883', {
  clientId: 'my_client_id',
  username: 'some_user',
  password: 'some_secret',
  clean: false
});

client.on('connect', function(connack) {
  console.log(JSON.stringify(connack));
  client.subscribe('mqtt/test', { qos: 1 }, function(){
    console.log('Now waiting for incoming messages...');
    client.on('message', function(topic, message) {
      console.log(topic + ' : ' + message);
    });
    client.on('error', function(err) {
      console.log(err);
    });
  });
});
process.once('SIGINT', function() { console.log('Client ended connection to broker'); client.end(); } );
```

This doesn't seem to work fine. The subscriber's `'message'` event is fired only on _not_ prefetched messages. That is, if the publisher pushes `N` messages to the queue, the subscriber pulls `N` - `prefetch_count`.

> Prefetch value is 10 by default on RabbitMQ's MQTT plugin as explained here: https://www.rabbitmq.com/mqtt.html 

Let me show you an example of what I mean. This happens after configuring a prefetch of 1 in RabbitMQ (which is the mininum accepted value, as 0 means _no limit_)

```sh
// Publisher pushes four messages to the queue
nfantone@thinkpad-t430 ~/dev/js/tfo/tfo-ms-contact $ node publisher.js 
Published  {"id":6.593135418370366,"from":"Me","message":"o9rk08i"} to mqtt/test
Message sent
Published  {"id":74.2014494491741,"from":"Me","message":"iw0x0ug"} to mqtt/test
Message sent
Published  {"id":61.6890971083194,"from":"Me","message":"j6c4l36"} to mqtt/test
Message sent
Published  {"id":91.78856404032558,"from":"Me","message":"h08j2un"} to mqtt/test
Message sent
^CClient ended connection to broker

// Subscriber receives _all_ but the first message (which was prefetched)
nfantone@thinkpad-t430 ~/dev/js/tfo/tfo-ms-contact $ node subscriber.js
{"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":false,"returnCode":0}
Now waiting for incoming messages...
mqtt/test : {"id":74.2014494491741,"from":"Me","message":" iw0x0ug"}
mqtt/test : {"id":61.6890971083194,"from":"Me","message":"j6c4l36"}
mqtt/test : {"id":91.78856404032558,"from":"Me","message":"h08j2un"}
^CClient ended connection to broker
```

Needless to say, this happens for every value of prefetch count. So, am I missing something? Is `mqtt.js` not currenly usable with RabbitMQ? Maybe something I misconfigured?

**Comment by nfantone** [comment]
One thing that I should mentioned is that the messages that don't end up in the subscriber's `message' event are still consumed _and silently discarded_. So, no messages are left in the queue after the above process.

**Comment by alestarss** [comment]
+1

**Comment by mcollina** [comment]
I have no idea of what prefetch is for RabbitMQ.

QoS 1 works fine with other brokers, so I fear this is a Rabbit issue. Not
sure how to debug it either.
Does the python library work with a similar configuration?
Il giorno mer 30 dic 2015 alle 19:44 Nicolás Fantone <
notifications@github.com> ha scritto:

**Comment by nfantone** [comment]
> I have no idea of what prefetch is for RabbitMQ.
https://www.rabbitmq.com/consumer-prefetch.html

Basically, it defines the amount of unack messages to be fetched per connection/channel in a single round-trip to the broker.

> QoS 1 works fine with other brokers, so I fear this is a Rabbit issue. 

Could be. But I'm reluctant to think that, since RabbitMQ's MQTT support has been around longer than Mosca and almost the same time as Mosquitto.

> Does the python library work with a similar configuration?

Sorry, which python library would that be?

**Comment by mcollina** [comment]
The python client: https://eclipse.org/paho/clients/python/

Regarding AMQP prefetch: MQTT has no such feature. Also the meaning in the
MQTT context is weird: mqtt is push-based, not pull-based.

Anyway, It should be enabled and set to 10 by default at plugin level:
https://www.rabbitmq.com/mqtt.html

Maybe it's conflicting somehow with the global setting.
Il giorno mer 30 dic 2015 alle 22:01 Nicolás Fantone <
notifications@github.com> ha scritto:

**Comment by nfantone** [comment]
> Anyway, It should be enabled and set to 10 by default at plugin level:

We change that setting on purpose to showcase the error more easily in the example I described. With the default value, anything lower than 10 messages was lost during pulling.

> Maybe it's conflicting somehow with the global setting.

There is no _global setting_ for this. Prefetch is a QoC value per channel/connection. The plugin sets that value at 10 for every channel while on MQTT.

I could try the python client and see if it behaves the same. I'll get back to you, guys.

**Comment by mcollina** [comment]
Again, there is no pulling on MQTT. An MQTT client does not ask for
messages continuosly or when it is ready. There is no such mechanism. It
only sends a PUBACK to confirm it has received a message.

This problem might possibly be due to MQTT.js not sending a correct PUBACK
for RabbitMQ, or RabbitMQ not interpreting the PUBACK sent by MQTT.js
correctly.

Does the code above work with other brokers, right?

Or some sort of MQTT v3.1.1 compat that slipped through here.
Il giorno gio 31 dic 2015 alle 04:23 Nicolás Fantone <
notifications@github.com> ha scritto:

**Comment by nfantone** [comment]
> Again, there is no pulling on MQTT. An MQTT client does not ask for
messages continuosly or when it is ready. 

Yes, I'm aware of that. I was just calling it _pulling_ because it felt easier to understand and explain the situation. Issue appears when the subscriber _receives_ pushed messages from the broker. Didn't think it was really relevant.

> Does the code above work with other brokers, right?

Haven't tried since I'm stuck with RabbitMQ, sadly. I'll give it a go to both, the python client and a new broker next week.

Thanks for your replies, @mcollina.

**Comment by nfantone** [comment]
@mcollina Tried both of my scripts using `mqtt://test.mosquitto.org:1883` and they didn't work either. This time, I'm not receiving anything on the subscriber after publishing `qos: 1` messages while offline. But that may be because the Mosquitto test instance doesn't accept persistent messages?

**Comment by mcollina** [comment]
These works for me on a local mosquitto (you were missing a clientId):

```js
var mqtt = require('mqtt');
var client = mqtt.connect({
  clean: false,
  clientId: 'abcde'
});

client.on('connect', function(connack) {
  console.log(JSON.stringify(connack));
  client.subscribe('mqtt/test', { qos: 1 }, function(){
    console.log(arguments)
    console.log('Now waiting for incoming messages...');
  });
});

client.on('message', function(topic, message) {
  console.log(topic + ' : ' + message);
});

client.on('error', function(err) {
  console.log(err);
});

process.once('SIGINT', function() { console.log('Client ended connection to broker'); client.end(); } );
```

```js
var mqtt = require('mqtt');
var client = mqtt.connect();
client.on('connect', function() {
  setInterval(function() {
    var message = JSON.stringify({
      id: Math.random() * 100,
      from: 'Me',
      message: (Math.random().toString(36) + '00000000000000000').slice(2, 7 + 2)
    });
    client.publish('mqtt/test', message, {
      qos: 1
    }, function() {
      console.log('Message sent');
    });
    console.log('Published ', message, 'to mqtt/test');
  }, 2000);

});

process.once('SIGINT', function() {
  client.end(function() {
    console.log('Client ended connection to broker');
    process.exit();
  });
});
```

**Comment by nfantone** [comment]
@mcollina Your examples also work with `mqtt://test.mosquitto.org:1883`. The thing wasn't about a "missing a clientId" (I believe both my scripts and yours have a properly defined `clientId`), but the `'message'` and `'error'` callbacks being defined _inside_ the `client.subscribe` block.

If you do that, then you'll receive no messages at all. You can try it out. Is that actually expected?

**Comment by mcollina** [comment]
It can happen, because if sessionPresent is true, the messages might arrive right after CONNACK, as you don't need to do a subscription again.

**Comment by nfantone** [comment]
@mcollina Ok, I can confirm that. I've tested this with RabbitMQ and it's working wonderfully.

If I move the `'message'` event declaration outside the `client.subcribe` I see this output:

```
mqtt/test : {"id":73.66805006749928,"from":"Me","message":"iy277bi"}
Now waiting for incoming messages...
mqtt/test : {"id":95.23756187409163,"from":"Me","message":"8dm4nuy"}
mqtt/test : {"id":33.074697852134705,"from":"Me","message":"7al7ih7"}
mqtt/test : {"id":8.080576034262776,"from":"Me","message":"sm1u1rc"}
...
```

You can see that an incoming message is printed _before_ the `Now waiting for incoming messages...` legend appears.

Everything makes sense now. I'm closing this.

Thank you very much for your patience.

**Comment by mcollina** [comment]
No worries :dart:

**Comment by nfantone** [comment]
Also, for any other who encounters this issue using RabbitMQ, you may consider lowering the default prefetch count in MQTT plugin in order to limit the number of lost messages while struggling with this.

Grazie mille per tutti, anche un'altra volta.
