### ISSUE TITLE
New MQTT connection for each client

### ISSUE THREAD

**Issue by yyberi** [mqttjs/MQTT.js#371]
I'm trying to open new mqtt connection to mosquitto broker for each socket.io client like in code below. It actually works, but problem is that when the first connected client is disconnected all the later mqtt connections stop working. Is it not possible to have several mqtt connections from single node app? 

```js
io.on('connection', function (socket) {
	socket.mqttClient = {};

	console.log('socket.io client connected');
	socket.emit('connected', 'Welcome');

	socket.mqttClient = mqtt.connect('mqtt://localhost', {keepalive: 0, clean: true});

	socket.mqttClient.on('message', function (topic, message) {
	  console.log('Topic ' + topic + ' Message' + message.toString());
	  socket.emit('mqtt',{'topic': String(topic), 'payload':String(message)});
	});
	
	//MQTT connected
	socket.mqttClient.on('connect', function () {
		console.log('mqtt client connected');
	});

	//MQTT closed
	socket.mqttClient.on('close', function () {
		console.log('mqtt client closed');
	});
	
     //subscribe new topic
	socket.on('subscribe', function (data) {
		console.log('Subscribing to '+data.topic);
		socket.mqttClient.subscribe(data.topic);
	});

    //socket disconnect		
    socket.on('disconnect', function () {
    	console.log('disconnecting:', socket.id);
    	socket.mqttClient.end();
    	delete socket;
    });
});
```

**Comment by 4rzael** [comment]
Every mqtt client has a client_id.

If you want to have multiple clients connected at once, each one should have an unique client_id.

Your socket should have an unique identifier, you can use it as your client id, or you can create a random string for your client_id.

In order to use your client_id, change your connection line with this:

```js
socket.mqttClient = mqtt.connect('mqtt://localhost', {keepalive: 0, clean: true, clientId: YOUR_UNIQUE_ID});
```

Let me know if it fixes your problem.

**Comment by yyberi** [comment]
Thanks for you help. That put me to a right way. client_id was not the actual problem and it works now even without passing id at connect. 
Problem was mine stupid bug. socket.mqttClient.publish was destroyed off course with the socket disconnect. MQTT works very well with own connection in each socket.io client.

**Comment by jdestefanis** [comment]
Hey @yyberi do you have an example of how can I create a nodejs function to connect multiple clients to one single mqtt server? I'm passing the credentials from an arduino, the messages arrives to the topics by using an mqttbox tester, but how can I gather them from the node api I'm building? Thanks!

**Comment by andgatjens** [comment]
> Every mqtt client has a client_id.
> 
> If you want to have multiple clients connected at once, each one should have an unique client_id.
> 
> Your socket should have an unique identifier, you can use it as your client id, or you can create a random string for your client_id.
> 
> In order to use your client_id, change your connection line with this:
> 
> ```js
> socket.mqttClient = mqtt.connect('mqtt://localhost', {keepalive: 0, clean: true, clientId: YOUR_UNIQUE_ID});
> ```
> 
> Let me know if it fixes your problem.

Thanks! This also helped me in my project!
