### ISSUE TITLE
Messages lost during subscription

### ISSUE THREAD

**Issue by GavinDmello** [mqttjs/MQTT.js#373]
I'm pushing around 500 messages simultaneously with a qos of 1 and trying to receive the same messages,qos being the same. Most of messages are being dropped. Is this a library issue?

**Comment by RangerMauve** [comment]
Are you waiting for the callback from subscribe to be executed before publishing?

**Comment by GavinDmello** [comment]
No. I'm not waiting for the callback .

**Comment by sandro-k** [comment]
@GavinDmello could you pleas give some more information how your setup looks like? What OS, MQTT.js version, what MQTT-broker and your client code.
