### ISSUE TITLE
Mosca or MQTT.js to create a MQTT Chat Proxy Server?

### ISSUE THREAD

**Issue by alliv8** [mqttjs/MQTT.js#376]
I'm working on creating a clustered chat app using MQTT and Aerospike/Redis. The idea is to use Mosquitto as the underlying brokers connected via bridge mode and have public facing MQTT Proxy Servers responsible for the Auth, Security and logic.

Which would be the correct library to deploy? MQTT.js Server or Mosca?

**Comment by alliv8** [comment]
Sorry for that. Went through Mosca in detail and loved the abstraction with ascaltatore. I think we'll go ahead with Mosca keeping Mosquitto as the backend for Ascaltatore, and Aerospike as the persistence layer. We'll be writing a persistence wrapper for Aerospike as well.

**Comment by mcollina** [comment]
I'm splitting Mosca and Ascoltatori into multiple modules. Check out [Aedes](http://npm.im/aedes).

**Comment by alliv8** [comment]
Oh, we're just about to start using Mosca in production. We're looking at
overriding the client.js & server.js prototype functions to fit in our
custom logic. We have a requirement of modifying the payload at the proxy
server layer before sending it to mosquitto.

Please share your thoughts on this. Thanks

**Comment by mcollina** [comment]
Aedes already provides that: https://github.com/mcollina/aedes#instanceauthorizepublishclient-packet-doneerr

**Comment by alliv8** [comment]
But MQEmitter is backed by memory right? I'm looking to have Mosquitto as the backend

**Comment by mcollina** [comment]
@alliv8 you can use redis: https://gist.github.com/mcollina/a37f135136192d9c58a4. Other options coming soon.
