### ISSUE TITLE
Type Error when initializing a connection

### ISSUE THREAD

**Issue by RangerMauve** [mqttjs/MQTT.js#377]
One of my projects wasn't pinned properly and broke with, what I assume was, the 1.7.0 update. Specifically, I'm getting a TypeError when initializing a connection, I've got a browserify bundle of the code, so the most I can say is that it's within something called `WebSocketStream` and happens on the third-last line. Downgrading to 1.6.3 seems to work fine.

```javascript
 if (typeof target === 'object') {
    socket = target
  // otherwise make a new one
  } else {
    socket = new WS(target, protocols, options)
    socket.binaryType = 'arraybuffer'
  }
```

**Comment by ralphtheninja** [comment]
@RangerMauve Please post the error and the stack trace you get

**Comment by mcollina** [comment]
On which browser? I think we should setup SauceLabs to avoid these regressions.

I think this is https://github.com/maxogden/websocket-stream/issues/82. A fix is coming soon.

**Comment by RangerMauve** [comment]
@ralphtheninja Sadly the dev tools are kinda lacking and we didn't have time to go into this too much further after the downgrade fixed things. I'll see if I can get one later today.

@mcollina This was in mobile safari on an iPad running iOS 7.1.2, didn't check to see if it had issues on other platforms, though it looked to be fine in Chrome on Windows.

**Comment by mcollina** [comment]
Fixed.
