### ISSUE TITLE
Problem with url parsing in mqtt.connect

### ISSUE THREAD

**Issue by epignotti** [mqttjs/MQTT.js#378]
A mqtt client can not make a connection to a mqtt broker using the following type of url:
`mqtt://some-server.org:91883` (Note the non-standard port). However, the client  will connect correctly using the deprecated function `mqtt.crateClient(91883,"some-server.org");`

I have noticed that in lib/connect/index.js the line  `opts = xtend(url.parse(brokerUrl, true), opts);` associates the wrong value to the `host` property in `opts`. Using the example above,  this property appears as  `host = "mqtt://some-server.org:91883"` where it should be set to `host = "some-server.org"` for the connection to work.

**Comment by mcollina** [comment]
Sorry about not replying early. Feel free to reopen or send a PR if this is still an issue.
