### ISSUE TITLE
No way to get state of client (connected or not)

### ISSUE THREAD

**Issue by RickBullotta** [mqttjs/MQTT.js#379]
Right now, the implementation seems to require that the state of the connection be kept externally by monitoring all of the various events (connect, close, reconnect, error, etc.).  It would be extremely valuable to have a method on the mqtt client object to check the connection state.

**Comment by RickBullotta** [comment]
Actually, looking at the source, there appears to be a this.connected property, but overall I think it may be a documentation issue.  Also, it should be documented that the reconnect event does not imply a successful reconnect, only a reconnection attempt.

**Comment by mcollina** [comment]
Would you mind sending a PR against the README?
Il giorno mer 3 feb 2016 alle 00:50 Rick Bullotta <notifications@github.com>
ha scritto:
