### ISSUE TITLE
Client has exceeded timeout, disconnecting.

### ISSUE THREAD

**Issue by MichMich** [mqttjs/MQTT.js#381]
Ok, I'm starting to bang my head against the wall here. 

I'm running a Mosquitto (1.4.7) MQTT server on my CentOS Web Server. Using MQTT.js I created a small node script that connects to this server.

When I run this Node script on my web server, it connects, but every few 10-30 seconds, it disconnects and reconnects. The Mosquito log states the following:

     1455282675: Client mqttjs_057aaa0a has exceeded timeout, disconnecting.

The weird thing is, this only is the case when I run this node script on the same server as my Mosquitto server. If I run the script from an other machine (for example my Mac), it works fine and remains connected without any issue.

I already tried disabling the Firewall on my Web Server but without any succes.

Any idea what could cause this weird behavior? Where I should start looking?

Thanks in advance!

**Comment by MichMich** [comment]
I think I got a bit further: when I connect to the mosquitto test server, it has the same problems. 
So:
- running the node.js script on my mac = no problem, stable connection
- running the node.js script on my centos web server = disconnections, unstable connection.

I'll try to figure out what the issue is on the CentOs server. Any suggestion is welcome.

**Comment by MichMich** [comment]
I figured out I can solve this by occasionally publishing a message. Only subscribing causes the issue. It does feel like a workaround, though.

**Comment by mcollina** [comment]
How long is your keepalive? It should really be measured in minutes.

**Comment by MichMich** [comment]
I did not change the default config.

**Comment by mcollina** [comment]
Try increasing that.

**Comment by MichMich** [comment]
The default keepalive is 10 seconds. Would you suggest lowering it? To 5 seconds?

**Comment by mcollina** [comment]
Nope, increasing it to 60+.
Il giorno dom 14 feb 2016 alle 16:34 Michael Teeuw <notifications@github.com>
ha scritto:

**Comment by MichMich** [comment]
Ah, I see! I was under the assumption, the `keepalive` property was the number of seconds between every keep alive ping. I now understand it's the max number of seconds it can go without any contact.
Increasing the number did improve the connection a bit. But as you can guess, the error still occurs after 60+ seconds. - Is there a maximum number of seconds I can use?

**Comment by hakanernam** [comment]
Actually, the maximum amount of time without a contact(Control packet) without a forced server disconnect is 1.5 times that. [MQTT3.1.1 - 3.1.2.10 Keep Alive]. Max keep-alive value is 65535 seconds as the value is a 16-bit word. But I understand from the docs  MQTT.js client already should handle ping requests:

https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options

**Comment by mcollina** [comment]
Which version of Mosquitto do you have on your server, and which one do you have locally?
Maybe the two versions behave differently.

I think this is due to https://github.com/mqttjs/MQTT.js/pull/355 cc @4rzael .

**Comment by mcollina** [comment]
Can any other reproduce this problem? I fear it might be something in the server config.

**Comment by hakanernam** [comment]
He stated that he  connected to mosquito test server from separate machines, so I believe ping requests somehow do not go out when running the script on his web server as they should.

**Comment by MichMich** [comment]
Exactly. It's not based in the server I connect to, but based on the server I'm running my script on. It seems it doesn't keep the connection alive (pings).

**Comment by hakanernam** [comment]
I suspect a race condition or maybe a permission issue could be causing _setupPingTimer function not being called or the interval not being set. 

I would advise copying the repository to same directory as your script,  putting some log statements in that function and _checkPing to see if they are indeed called.

**Comment by MichMich** [comment]
Will do! I'll report back as soon as I find a cause or solution.

**Comment by MichMich** [comment]
Ok, I'm feeling pretty stupid now ...

I cloned the mqtt.js repo and added some logging to the suggested function. It turned the ping requests were send as required and on time. More importantly: the connection was now stable and did not disconnect. 

So then it occurred to me: with the newly pulled library, everything works fine. Am I just running an old version of MQTT.js on my web server? To test it, I typed the following magic command:

    npm update mqtt

And indeed ... The problem is solved. DOH!

So kids, always update your modules before you start wasting days of debugging ... *sigh*

**Comment by danki** [comment]
Have allmos same issue, how ever on Android side. Have been struggling with this past 2 months now and @MichMich solution above [(#issuecomment-183909042)](https://github.com/mqttjs/MQTT.js/issues/381#issuecomment-183909042) seems to solve that, at least regarding android. 
Connection has been up for 2 hours straight, so i see positive effect here :)
