### ISSUE TITLE
Client should not wait for PINGRESP for keeepalive time

### ISSUE THREAD

**Issue by hakanernam** [mqttjs/MQTT.js#383]
As it is, client waits for a period of keepalive time to check for ping response from server. This may result in server being down but client not knowing this for a very long time. Longest possible keep alive time is over 18 hours (65535/3600).

Spec states that: "If a Client does not receive a PINGRESP Packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server."

Reasonable period of time is actually quite short, definitely not minutes or hours.

**Comment by mcollina** [comment]
Would you mind to send a PR to address this issue?

**Comment by hakanernam** [comment]
I would be happy to try. My node skills are non existent, though. So a proper PR may take some time.

**Comment by mcollina** [comment]
Closing for now. Feel free to reopen and/or send a PR.
