### ISSUE TITLE
Re-subscribing to topics after disconnect and reconnect fails to receive further messages

### ISSUE THREAD

**Issue by danielgubler** [mqttjs/MQTT.js#384]
After losing a connection and reconnecting, I re-subscribe to topics but even after getting a successful subscribe callbacks, I no longer receive any further messages. I'm using wss (web sockets with ssl) and authentication and a mosquito broker. Mosquito is logging the the subscription requests as successful and also logging that it is continuing to send my client messages, but nothing is received on my client. Here is my client code:

```js
class MQTTClient {
  constructor() {
    this._connected = false
    this._registeredListeners = {}
  }

  subscribe(topics) {
    this._topics = topics
    if (this._connected) { this._subscribeTopics() }
  }

  connect() {
    console.log('connecting mqtt...')
    this.client = mqtt.connect('wss://www.some-url.com/mqtt', {
      username: 'omitted',
      password: 'omitted' })
    this._configureListeners()
  }

  _configureListeners() {
    this.client.on('connect', () => {
      this._connected = true
      console.log('mqtt:connected')
      if (this._topics) { this._subscribeTopics() }
    })

    this.client.on('error', (e) => {
      this._connected = false
      console.log(`mqtt:error:${e}`)
    })

    this.client.on('reconnect', () => {
      this._connected = false
      console.log(`mqtt:reconnecting...`)
    })

    this.client.on('close', () => {
      this._connected = false
      console.log(`mqtt:closed`)
    })

    this.client.on('offline', () => {
      this._connected = false
      console.log(`mqtt:offline`)
    })

    this.client.on('message', (topic, message) => {
      console.log(`topic:${topic}`)
      // some message handling...
    })
  }

  _subscribeTopics() {
    this._topics.forEach( topic => {
      console.log(`subscribing to: ${topic}`)
      this.client.subscribe(topic, { qos: 1 }, (err, granted) => {
        console.log(`finished subscribing to: ${topic}`)
        console.log(err)
        console.log(granted)
      })
    })
  }
}
```

In my console, I'm seeing:
```
mqtt:offline
mqtt:closed
mqtt:reconnecting...
mqtt:connected
subscribing to: some_topic
finished subscribing to: some_topic
null
[Object]
```
(where the Object at the end is the "granted" object given to the function on a successful subscription)

**Comment by mcollina** [comment]
Does the same code works outside a browser?

**Comment by loris** [comment]
Confirm same issue. It looks related to websocket (thus browser only).

**Comment by mcollina** [comment]
Websockets also work outside of the browser: it is browser specific then?

**Comment by mkarliner** [comment]
I  think I've just run into the same issue.

**Comment by mcollina** [comment]
Can you please provide an example that I can run easily (with instructions) to reproduce this?

**Comment by mayooran99** [comment]
Hey I'm having the same issue! are there any solutions to this yet? I'm running a node JS application. Not browser specific. And I'm not using secure websockets.

**Comment by mcollina** [comment]
@mayooran99 can you please upload a simple script using __only__ MQTT.js that can run on node v4, a mosquitto config and instructions to run all the above?

**Comment by lordkada** [comment]
+1
I'm experiencing the same (but within node.js it works as expected).

    client = mqtt.connect("wss://...omissis...")
    channel = "test_channel"

    client.on "connect", () ->
        console.log "Subscribing channel: #{channel}"
        client.subscribe channel

    client.on "message", (topic, payload) ->
        console.log "received message"
        console.log payload

    client.on "offline", () ->
        console.log "Offline..."

**Comment by mcollina** [comment]
I have hard trouble replicating this. Can anybody please upload an archive with everything needed to replicate? Include a README with all the instructions to replicate.

**Comment by mkarliner** [comment]
Apologies, Matteo, This issue went off my radar a while back. I'll try to get you a confirmed test case next week.

Mike
