### ISSUE TITLE
Authentication doesn't work in browser

### ISSUE THREAD

**Issue by yugandhar23** [mqttjs/MQTT.js#391]
I am trying to pass username and password in options. Its not working for browser.
Same config is working for node version

**Comment by mcollina** [comment]
We need more details, and possibly a full example. It was working for me as of yesterday.

**Comment by yugandhar23** [comment]
I am using following format.
mqtt.connect({servers : [{ host: host, port: port}],  username : username, password :pass})

Could you please share your example ?

**Comment by mcollina** [comment]
So, I am not using multiple servers. Can you please try:

1. just use one server, something like `{ host: host, port: port, username:username, password: password }`
2. specify the user-name password combination within each server object so `{ servers: [{ host: host, port: port, username:username, password: password }] }`

**Comment by yugandhar23** [comment]
None of them is working :(

**Comment by sandro-k** [comment]
Is your MQTT-broker at mqtt 3.1.1? I can definitely confirm that username and password authentication **works** with mosquitto.

**Comment by yugandhar23** [comment]
it supports all versions between 3.0.0 to 4.0.0

**Comment by sandro-k** [comment]
Is the authentication working with other clients?

**Comment by yugandhar23** [comment]
yeah.. its working for node client.
Could you please explain how authentications works here ?

**Comment by sandro-k** [comment]
Pleas post the code that creates the client and then connects.

**Comment by yugandhar23** [comment]
I am using mqtt.js as it is. After browserify
I am trying to connect using this format:
mqtt.connect({servers : [{ host: host, port: port}], username : username, password :pass})

**Comment by yugandhar23** [comment]
for 8883 port, I am getting this error..

**Comment by yugandhar23** [comment]
WebSocket connection to 'ws://host:8883/' failed: Connection closed before receiving a handshake response

**Comment by sandro-k** [comment]
Ok I just tested with my server and this works for me 

```
var host = "localhost/ws/";
  var port = 80;
  var username = "user";
  var pass = "pass";
  var client = mqtt.connect({servers : [{ host: host, port: port}], username : username, password :pass})

  client.on("connect", function(){
    console.log("connect", arguments);
  });

  client.on("error", function(){
    console.log("error", arguments);
  });
```

Are you connecting via `ws` or `wss`?

**Comment by yugandhar23** [comment]
ws

**Comment by sandro-k** [comment]
@yugandhar23 did you solve it?

**Comment by mcollina** [comment]
Closing as there was no more activity for a while.
