### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE SSL error

### ISSUE THREAD

**Issue by OrahKokos** [mqttjs/MQTT.js#395]
Hey, I posted a question on stackoverflow, but no answer. Could someone please point me in the right direction?

http://stackoverflow.com/questions/36444866/mqtt-client-unable-to-verify-leaf-signature

**Comment by mcollina** [comment]
I have never encountered the problem. What is your goal?

Have you looked into http://stackoverflow.com/questions/20747817/error-unable-to-verify-leaf-signature-phonegap-installation?

**Comment by OrahKokos** [comment]
The goal is to have a SSL/TLS connection with the mosca broker. Specific devices will be shipped with client certificates. Running the device ( C ) can connect to mosca using the self-signed cert which was generated on my machine. 

However some system parts are also communicating via MQTT, these parts of the system use the `mqtt` npm lib to create a connection. When passing the certs the client throws an error.
So there is no communication with the broker. 

Also I'm testing the system part on localhost, so there is no outgoing interference.
Any ideas ?

**Comment by mcollina** [comment]
I think the best way is try to do the same without mosca and mqtt, just with net.
Then we can address that issue.

**Comment by OrahKokos** [comment]
Ok, I'm trying a different approach. Is there a way to make mosca listen on multiple ports ( for system stuff port 1883, for devices 8883 SSL ). I see mosquitto has this, however i can't find anything in mosca.
Also, `allowNonSecure` option, does it have something to do with it?

Thanks for your time so far :)

**Comment by mcollina** [comment]
I'd suggest you follow the `tls` approach, and try to do the same thing cutting out the middlemen (mqtt.js and mosca). This is what you are looking for: https://github.com/mcollina/mosca/blob/master/examples/Server_Wtih_All%20Interfaces-Settings.js

**Comment by OrahKokos** [comment]
Nice, that is exactly what I'm looking for. Thanks for the support man!
