### ISSUE TITLE
maxFirstConnects to avoid reconnection loop

### ISSUE THREAD

**Issue by mcollina** [mqttjs/MQTT.js#396]
In some cases, we might be stuck in a reconnection loop were we do not expose the internal error to the user. `maxFirstConnect`  loop should avoid that, so that after X (10) failed attempt to connect for the first time, we give up. Suggested by @jimbojw in https://github.com/mqttjs/MQTT.js/issues/257#issuecomment-208841761

**Comment by 5aurabh** [comment]
@mcollina I just ran into this issue and am hoping to contribute. Just to get some clarity, should ```maxFirstConnect ``` be enforced only for the first successful connection or should it be reinforced every time after a successful connection?

Example:
Consider for  ```maxFirstConnect : 0```, what would be the desired behaviour if a client is able to successfully connect initially but later on loses connection and tries to reconnect?

**Comment by jianfenkezhan** [comment]
So, how to fix it?

**Comment by jimbojw** [comment]
> what would be the desired behaviour if a client is able to successfully connect initially but later on loses connection and tries to reconnect?

@5aurabh In that case, the current behavior (retry indefinitely) would be fine. The proposed `maxFirstConnect` setting would only apply to the initial connection. Once a connection has been made, later reconnection attempts would proceed as normal.

**Comment by YoDaMa** [comment]
This could be fixed for `ECONNREFUSED` via #1053

**Comment by YoDaMa** [comment]
while not explicitly handled, this has been released with #1053 to deal with typical TLS level errors. So we will close this feature request issue.
