### ISSUE TITLE
How to turn off outgoing message cache?

### ISSUE THREAD

**Issue by Densaugeo** [mqttjs/MQTT.js#397]
I have an MQTT client using mqtt.js, and publishing messages to a broker. If the broker goes offline, the client saves its messages up and sends them all at once when the server reconnects, creating a flood of traffic. Is there a way to turn off this caching? I don't need to preserve old messages, only saving the most recent is fine.

Also, I have qos set to zero. My understanding is that this means messages should be 'fire and forget', with no caching.

**Comment by mcollina** [comment]
So, caching is the wrong term, as we are not caching anything. The correct term is 'offline queue', or 'send queue'. Can you please reframe your issue? 

Disabling the queue is currently not possible.

I agree with you that we should address this is a bug that will need fixing in a next major release #345 (or after that one). The whole queue system needs to be highly refactored to address various issues. I currently have no bandwidth to do so.

**Comment by Densaugeo** [comment]
I can't speak to refactoring the whole system, but after looking at Client.js a bit, it shouldn't be hard to add an option for 'sendQueue' or something like that, and check it in MqttClient.prototype._sendPacket() before adding a packet to the queue. I can send a PR for this in a bit.

I haven't contributed to this project before, is there anywhere I would need to update tests and documentation other than Readme.md and test/client.js?

**Comment by mcollina** [comment]
> I can't speak to refactoring the whole system, but after looking at Client.js a bit, it shouldn't be hard to add an option for 'sendQueue' or something like that, and check it in MqttClient.prototype._sendPacket() before adding a packet to the queue. I can send a PR for this in a bit.

That can solve your issue, but that option will break a lot of the behavior of MQTT.js. The whole point is that you need to check if it's a publish QoS 0 and then discard that. All the other stuff would need to be queued anyway.

> I haven't contributed to this project before, is there anywhere I would need to update tests and documentation other than Readme.md and test/client.js?

@Densaugeo no.

**Comment by Densaugeo** [comment]
Would it be reasonable to only queue outgoing packets if they have QoS > 0? I think this would be correct behavior according to the MQTT spec, but would also mean a change of behavior (since QoS 0 packets are currently being queued). Is that why you mention v2?

For the meantime, I propose an option to enable this behavior (while still queuing QoS 1 and 2 packets regardless).

**Comment by mcollina** [comment]
Yes to all questions, good work!

**Comment by 4rzael** [comment]
Hum, looks like this issue can be closed, as it's been fixed in #399 ?
@mcollina

**Comment by mcollina** [comment]
Yes, I think so.
