### ISSUE TITLE
client not working when the broker is Mosquitto

### ISSUE THREAD

**Issue by wormcc** [mqttjs/MQTT.js#400]
Help! When i use Mosquitto as a broker, the client can not connect with it, but with mosca it does well, but my python client does well with both of them.

**Comment by mcollina** [comment]
I think you are using an old version of Mosquitto.

From the README:

> If you are connecting to a broker that supports only MQTT 3.1 (not 3.1.1 compliant), you should pass these additional options:
```
{
  protocolId: 'MQIsdp',
  protocolVersion: 3
}
```
This is confirmed on RabbitMQ 3.2.4, and on Mosquitto < 1.3. Mosquitto version 1.3 and 1.4 works fine without those.

**Comment by wormcc** [comment]
thx!
