### ISSUE TITLE
Can not install on raspberry pi

### ISSUE THREAD

**Issue by panagorn** [mqttjs/MQTT.js#401]
I cant intsll mqtt on raspberry pi

pi@raspberrypi:~/Desktop/mqtt $ npm install mqtt --save
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mqtt" "--sace"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install mqtt as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/mqtt/npm-debug.log

**Comment by mcollina** [comment]
You created a module call mqtt, and then you want to install mqtt inside it. You can't, that is forbidden by NPM. Rename your module to something else.
