### ISSUE TITLE
Streaming from stdin broken in mqtt CLI? 

### ISSUE THREAD

**Issue by megastef** [mqttjs/MQTT.js#402]
When I use ```mqtt pub -t 'hello' -h localhost --stdin``` then no messages are processed until stdin is closed (e.g. STRG+D). I would expect that each line is a message.
So I could not use mqtt CLI to stream data via unix pipe.

**Comment by mcollina** [comment]
> When I use mqtt pub -t 'hello' -h localhost --stdin then no messages are processed until stdin is closed (e.g. STRG+D). I would expect that each line is a message.

Is that written anywhere? The help is pretty clear: https://github.com/mqttjs/MQTT.js/blob/master/doc/publish.txt#L12.

However your expected behavior is an important use case, would you like to send a PR? It should be straightforward using http://npm.im/split2 and http://npm.im/through2.

**Comment by megastef** [comment]
+1 OK, I just wanted to check if I did miss something in the documentation. I could provide a PR, it might take a week to find the time to work on it.

**Comment by mcollina** [comment]
Thanks @megastef! Just do not disrupt the current behavior, something like `--stdin --multiline` or equivalent.

**Comment by mcollina** [comment]
Merged
