### ISSUE TITLE
Can I simply pipe a Readable stream to a MqttClient?

### ISSUE THREAD

**Issue by sprijk** [mqttjs/MQTT.js#404]
I have a high rate of source messages. When the connection's transmission speed is insufficient:
- how will MQTT.js handle back-pressure?
- or, can I just pipe to the MqttClient instance? 

Thanks

**Comment by mcollina** [comment]
you can `publish(topic, payload, cb)` and `cb` will be called when the message is written to the socket (QoS 0) or when it receive the ack.

**Comment by sprijk** [comment]
Ah super, thanks!

**Comment by 4rzael** [comment]
IIRC, there is no stream API to a MqttClient

I don't really see how there could be one, as MQTT is a protocol made for sending/receiving messages. Not really a continuous stream of data.

Anyway, you can still implement a wrapper that cuts your stream down into multiple messages before calling the publish method, as described above. (even though you can't assume evrything is sent in order)

**Comment by mcollina** [comment]
@4rzael great response!
