### ISSUE TITLE
Propose 'publish' event for MqttClient

### ISSUE THREAD

**Issue by Densaugeo** [mqttjs/MQTT.js#407]
I've got a client that sometimes needs to log everything it publishes. Perhaps adding a 'publish' event to the client would be useful?

**Existing method 1**
So far, I can add a log statement after every publish:
~~~
mqtt_connection.publish('/some/topic', 'a message');
logger.debug('Sent to MQTT:', { topic: '/some/topic', message: 'a message' });
...
~~~
but that is verbose, and I may miss a log statement.

**Existing method 2** (doesn't actually work this way)
There's a handy callback option:
~~~
var logger_cb = function(err, result) {
  logger.debug('Sent to MQTT:', result);
};
mqtt_connection.publish('/some/topic', 'a message', logger_cb);
~~~
but the callback only gets error arguments, no information about successful publishes is sent to the callback! So, with that approach, I would need a different callback for each publish, which looks basically the same as the first option.

**Existing method 3**
Or, I could make a custom .publishAndLog method:
~~~
mqtt.MqttClient.prototype.publishAndLog = function(topic, message, opts, callback) {
  this.publish(topic, message, opts, callback);
  
  logger.debug('Sent to MQTT:', { topic: topic, message: message });
}
mqtt_connection.publishAndLog('/some/topic', 'a message');
...
~~~
which works rather well, but I would prefer to use the standard .publish() method to avoid confusion.

**This would be nicer**
I would like to add a publish event to the client, so that I could use something like this:
~~~
mqtt_connection.on('publish', function(topic, message, packet) {
  logger.debug('Sent to MQTT:', { topic: topic, message: message });
});
mqtt_connection.publish('/some/topic', 'a message');
...
~~~
Passing the internal packet object to a callback on success could also be helpful, to allow something like the `logger_cb` case above.

Before I get started on it, are there any comments/suggestions for the new event? I am thinking of making it fire when the cb would normally be called on success, and giving it the same arguments as the 'message' event.

**Comment by mcollina** [comment]
I'm 👍 on firing the event, go ahead.
