### ISSUE TITLE
Unable to connect to Mosquitto broker

### ISSUE THREAD

**Issue by uzarubin** [mqttjs/MQTT.js#409]
Hey everyone! 

I have mqtt running via mosquitto broker on my raspberry pi. I have multiple nodemcus running lua that connect just fine, along with a dedicated client running on my computer, but I am unable to connect with mqtt.js. 

Here is what I have tried: 

    mqtt.connect('mqtt://192.168.1.21:1883', {clientId:'garage_node', username: 'foo', password: 'bar'})
    mqtt.connect({hostname:'192.168.1.21', port: '1883', clientId:'garage_node', username: 'foo', password: 'bar'})
    mqtt.connect({hostname:'192.168.1.21', port: '1883', clientId:'garage_node', auth: 'foo:bar''})

my `mosquitto.conf` file:
   
    pid_file /var/run/mosquitto.pid

    persistence true
    persistence_location /var/lib/mosquitto/
    persistence_file mosquitto.db
    listener 1883

    log_dest topic
    log_type error
    log_type warning
    log_type notice
    log_type information

    connection_messages true
    log_timestamp true

    include_dir /etc/mosquitto/conf.d

I have tried adding `protocol websockets` but that didn't work either. 
I am using mqtt version 1.10 and mosquitto 1.4.8. Any thoughts would be greatly appreciated

**Comment by mcollina** [comment]
Have you tried with a stock configuration, without authentication?

Are you trying connecting from a browser?

**Comment by uzarubin** [comment]
@mcollina I'll turn off auth and try again. Also, I am connecting through the browser. I noticed there was an issue with it switching from `mqtt` to `ws`, but does it still work?

**Comment by mcollina** [comment]
no known issue in this library. You need to setup websocket in mosquitto, use 'ws' in the url and connect to the right port.

**Comment by uzarubin** [comment]
@mcollina I figured out the problem. I installed mosquitto without websocket support. Once I fixed that, I am not connecting.
