### ISSUE TITLE
Connecting through TLS throws exception

### ISSUE THREAD

**Issue by mayooran99** [mqttjs/MQTT.js#412]
I wrote the following code to connect to the mosquitto broker. 

``` js
var mqtt = require('mqtt');
var fs = require('fs');
var KEY = fs.readFileSync('C:/OpenSSL-Win32/bin/clii.key');
var CERT = fs.readFileSync('C:/OpenSSL-Win32/bin/clii.crt');
var TRUSTED_CA_LIST = [fs.readFileSync('C:/OpenSSL-Win32/bin/ca1.crt')];
 
var PORT = 1883;
var HOST = 'localhost';
 
var options = {
  port: PORT,
  host: HOST,
  protocol: 'mqtts',
  keyPath: KEY,
  certPath: CERT,
  rejectUnauthorized : false, 
  //The CA list will be used to determine if server is authorized
  ca: TRUSTED_CA_LIST,
  secureProtocol: 'TLSv1_method',
  protocolId: 'MQIsdp',
  protocolVersion: 3
};
 
var client = mqtt.connect(options);
 
client.subscribe('messages');
client.publish('messages', 'Current time is: ' + new Date());
client.on('message', function(topic, message) {
  console.log(message);
});
 
client.on('connect', function(){
    console.log('Connected');
});
```

But its throwing the following exception.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)
```

Is this TLS connectivity tested and verified? Has anyone tested this? I can't find any documentation on this as well!

**Comment by mcollina** [comment]
Re: documentation. We need help, please contribute some guide and/or example regarding TLS.

You need to use `key`  and `cert` if you pass in buffers. `keyPath` and `certPath` are only for file paths (and they should not be used).

**Comment by mayooran99** [comment]
thanks a lot mate! its working now! I'll write a detailed blog on this and share it here for new users! :)

**Comment by mcollina** [comment]
@mayooran99 would you mind contributing an example for https://github.com/mqttjs/MQTT.js/tree/master/examples on how to setup mosquitto as well for LTS, etc..?

I see everybody struggling with this stuff.

Also, improving the README on that regard my be helpful.

**Comment by mayooran99** [comment]
sure mate! I'll do it within the next two weeks!
