### ISSUE TITLE
About un-publishable topics

### ISSUE THREAD

**Issue by anhldbk** [mqttjs/MQTT.js#413]
I'm using MQTT.js to publish messages to an `unauthorized topic` with function
```text
mqtt.Client#publish(topic, message, [options], [callback])
```

Is there any way for me to know the `publish operation` is not success?

**Comment by mcollina** [comment]
The client will disconnect. It's a known weakness of MQTT.

**Comment by anhldbk** [comment]
@mcollina If the client disconnect, so there's an event fired? I expected to have event `reconnect`, `close`, `offline` or `error` to be fired. But none of them showing up.

**Comment by mcollina** [comment]
It should be `'offline'`.

**Comment by anhldbk** [comment]
@mcollina actually no such event fired

**Comment by mcollina** [comment]
Which broker are you using? This behavior is governed by the broker, not really by the client.

**Comment by anhldbk** [comment]
@mcollina Ah, I see. I'm using `emqtt`. Thank you anyway!
