### ISSUE TITLE
Unexpected identifier error in browserifying mqtt

### ISSUE THREAD

**Issue by mayooran99** [mqttjs/MQTT.js#417]
I need to use the mqtt client from the browser and I followed the following steps as mentioned in the doc.

![capture](https://cloud.githubusercontent.com/assets/6868898/15809346/b465b390-2bac-11e6-9ea8-a2c8ba348f72.PNG)

And then created a html page as specified in the doc.

![capture](https://cloud.githubusercontent.com/assets/6868898/15809349/cae9c778-2bac-11e6-8056-975b53980656.PNG)

When I ran the commands, the browserMqtt.js got created successfully. But when I run the HTML I am getting the following error.

![capture](https://cloud.githubusercontent.com/assets/6868898/15809152/932bb530-2ba7-11e6-8d29-f8496785e29f.PNG)

Is there something wrong with the library?

**Comment by sandro-k** [comment]
@mayooran99 could you pleas expand the error given in the Console. Just copy-paste the stacktrace and the version of Chrome you are using.

**Comment by mcollina** [comment]
There is something wrong with the browserify version you are using:
I got this line:

```js
  if(length === -1 || end > this._list.length ||Â end > this.packet.length)
```

**Comment by mcollina** [comment]
I checked this here, and I get the same output, not sure what's up to.

@sandro-k can you have a look?

**Comment by sandro-k** [comment]
@mayooran99 and @mcollina I can confirm that this is a bug in https://github.com/mqttjs/mqtt-packet/blob/master/parser.js#L355 and https://github.com/mqttjs/mqtt-packet/blob/master/parser.js#L370. Somehow a `char 160` ended up after `if(length === -1 || end > this._list.length ||`

I will create a PR

**Comment by sandro-k** [comment]
@mayooran99 thanks for reporting this.

**Comment by sandro-k** [comment]
I can confirm when forcing `"mqtt-packet": "^3.4.7"` I can now bundle and use mqtt.js in the browser without any issue.

**Comment by mcollina** [comment]
I don't think there is a need to do a release, as we depend on mqtt-packet with the `^`.
If anyone faces this issue, just zap your node_modules folder and reinstall.
