### ISSUE TITLE
About connecting back

### ISSUE THREAD

**Issue by anhldbk** [mqttjs/MQTT.js#418]
So we know: If an MQTT client is successfully connected to its server, it then must subscribe to specific topics.

My question is: if there's something wrong, the client loses the connection. Does it have to re-subscribe the topics?

**Comment by mcollina** [comment]
if the client connects with `clean: false`, and specifies a unique `clientId`, the subscriptions are restored by the broker.

**Comment by anhldbk** [comment]
@mcollina Is option `clean: false` is necessary? In my experiment, I just need the unique `clientId`.

**Comment by mcollina** [comment]
It's part of the MQTT protocol

**Comment by anhldbk** [comment]
@mcollina Thank you so much!
