### ISSUE TITLE
Creating a wss connection over browser

### ISSUE THREAD

**Issue by mayooran99** [mqttjs/MQTT.js#421]
I couldn't find any examples on establishing a wss connection over the browser using browserify with both client and server side authentications. Is this possible? if so, how will the certificates be provided and through which protocol should the connection be established. Can you provide some example on it?

**Comment by mcollina** [comment]
You can't use client side certificates in the browser from a JS API. Maybe you can install a client side certificate through some other mean (but I do know nothing about it).
