### ISSUE TITLE
Can mqtt.js connect to the ActiveMQ ?

### ISSUE THREAD

**Issue by Xiao-Yaran** [mqttjs/MQTT.js#423]
System : windows7
mqtt.js:v1.11.0
----------------------------------
Masters,I use mosquitto as a broker,and  the mqtt client  can connect  it and works well.
But when I use ActiveMQ as a broker, mqtt client can't connect  it.
----------------------------------
My code:

//.............mqtt通信
var mqtt = require('mqtt');
var settings = {
    keepalive: 5,
    reconnectPeriod: 5 * 1000,  //自动重连时间，单位ms
    connectTimeout: 10 * 1000,   //连接超时时间
    protocolId: 'MQTT',
    protocolVersion: 4,
    clientId: 'client-czzd',
    clean: false  
}
var client = mqtt.createClient(1883, '192.168.1.38', settings);

**Comment by ralphtheninja** [comment]
Maybe the wrong `protocolVersion`?

**Comment by Xiao-Yaran** [comment]
@ralphtheninja   Your approach is correct.!! 
setting:
  protocolId: 'MQIsdp',
  protocolVersion: 3
It works! Thank you very much
