### ISSUE TITLE
Fail to connect tls mosquito broker.

### ISSUE THREAD

**Issue by sanket-mindstix** [mqttjs/MQTT.js#424]
Hi, 

I am using TLS MQTT client broker, but when I try to connect my broker using client it is failing to connect it, following error message gets written into MQTT broker log file.

 **OpenSSL Error: error:140890C7:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:peer did not return a certificate**

**Comment by sandro-k** [comment]
Can you please post the code you are using to connect to the MQTT-Broker.

**Comment by sanket-mindstix** [comment]
Please find code I'm using for mqtt client. I have set mosquito broker running locally. I am able to subscribe and publish the topics to the same mqtt broker using command line mqtt client. So I thing broker is working fine and one more thing I am using self signed certificates for broker and client.

When I try connect broker using nodejs mqtt client following log gets written into my log file,
**1466151342: New connection from 127.0.0.1 on port 1883.
1466151342: OpenSSL Error: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
1466151342: Socket error on client <unknown>, disconnecting.**

`
var mqtt = require('mqtt');
var fs = require('fs');
var KEY = fs.readFileSync(__dirname + '/client2.key');
var CERT = fs.readFileSync(__dirname + '/client2.crt');
var TRUSTED_CA_LIST = fs.readFileSync(__dirname + '/ca.crt');

var PORT = 1883;
var HOST = 'localhost';

var options = {
    port: PORT,
    host: HOST,
    keyPath: KEY,
    certPath: CERT,
    rejectUnauthorized : false,
    //The CA list will be used to determine if server is authorized
    ca: TRUSTED_CA_LIST
};

var client = mqtt.connect(options);

client.subscribe('messages');
client.publish('messages', 'Current time is: ' + new Date());
client.on('message', function(topic, message) {
    console.log(message);
});

client.on('connect', function(){
    console.log('Connected');
});
`

Thanks

**Comment by sandro-k** [comment]
Is the broker configured to accept SSL on port 1883 or is that the default no SSL bare TCP Port? If you connect without SSL, which port are you using?

**Comment by sanket-mindstix** [comment]
Yes, my broker is SSL enabled, I am successfully able to connect the broker using command line client,
following commands I am using for subscribing and pushing the topic using the same broker. 

**$mosquitto_sub -t test -v --cafile ca.crt --cert client2.crt --key client2.key
$mosquitto_pub -t test -m "HELLO Sanket" --cafile ca.crt --cert client2.crt --key client2.key**

**Comment by mcollina** [comment]
Closing, see #457.

**Comment by kSuccess** [comment]
hi @sanket-mindstix can you show me your mosquitto.conf file ,because i have same trouble with integrating TLS into Mosquito's broker

**Comment by RamcharanTeja** [comment]
hi @sanket-mindstix  can you share the reference link to configure TLS into Mosquitto broker, I tried but getting "Problem Setting TLS Options" Error

I follwed this link https://mosquitto.org/man/mosquitto-tls-7.html and created only server side keys
