### ISSUE TITLE
Try to connect to a server after browserify

### ISSUE THREAD

**Issue by DesarrolloSinapse** [mqttjs/MQTT.js#427]
Hi, 
I included this library to a new Ionic project, and after generate the bundle.js file without problems.

When I try to connect to a server, is there any way to do it without using websockets or is the only way to connect?.

I have done some tests usign tcp, http and mqtt protocols with the server's URL and I get the following error:

"WebSocket Error: Incorrect HTTP response. Status code 302"

**Comment by RangerMauve** [comment]
HTTP isn't a valid protocol for MQTT. If you're in the browser you can only really use websockets. If you really want TCP you'd need to wrap over some sort of ionic specific plugin for TCP which you could pass into MQTT.js as a stream.
