### ISSUE TITLE
Is it possible to do wild card subscriptions through this library?

### ISSUE THREAD

**Issue by mayooran99** [mqttjs/MQTT.js#432]
Is it possible to subscribe to topics having wildcard characters such as + and *  as they are possible in MQTT? Like if I 've subscribed to mqtt.subsribe('topic/+/something") will I receive a message on the "topic topic/okay/something"? Because this has not been mentioned in the documentation.

**Comment by mcollina** [comment]
Yes they are supported. Would you mind sending a pull request against the README to clarify?

**Comment by sandro-k** [comment]
@mayooran99 just as a side note MQTT only allows `+` - Single Level and `#` - Multi Level wildcards, both are supported by MQTT.js
