### ISSUE TITLE
event `message` called multiple times if multiple subscribe is done

### ISSUE THREAD

**Issue by rudylacrete** [mqttjs/MQTT.js#433]
Hello guys,

First of all thank you for all the great job you are doing on this library.
My company faced an issue while using your code because we didn't take care so much about subscribing only once to a given topic (a basic plain one, no wildcards). And in the case you do that, the event message is triggered as many times as the number of subscribe you did previously as soon as a publish is done for this particular topic. I think this behaviour is not relevant and I would like to hear from you about it. Is this related to the MQTT protocol itself or to your code logic?

Thanks again,
Kind regards.

**Comment by mcollina** [comment]
It seems an MQTT feature. Can you upload an example?

**Comment by RangerMauve** [comment]
I've found this happens with Mosquitto. My solution was to abstract my MQTT interactions and keep track of subscriptions so that I wouldn't subscribe to something I was already subscribed to. Also, for automatically re-subscribing on reconnecting.

**Comment by 4rzael** [comment]
This is strange.

Looking at the [MQTT specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf), section 3.8.4-3 (line 967), I quote :

> If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted [MQTT-3.8.4-3].

If I understand correctly theses lines, you **should not** receive multiple packets when subscribing more than once to a topic.

I cannot try this right now, but it is strange.

A good way to verify if it's Mosquitto that sends them multiple time or our client that emit too much events would be to log the event `packetreceive` (look if multiple `message` events are emitted for one `packetreceive`), or to directly look at the packets using a tool such as wireshark.

**Comment by rudylacrete** [comment]
We understand the same thing. However I was not able to reproduce the bug on my machine. I only got that on our cloud so still don't know if it comes from a mystake on my side.
That's a great idea to inspect directly the network packets to find out if it comes from the broker itself.  I'll continue to check that and keep you informed.
Thanks again guys.

**Comment by mcollina** [comment]
@rudylacrete can we close this?

**Comment by rudylacrete** [comment]
Sure I'll do it.
