### ISSUE TITLE
Receiving uint8array data through on message callback

### ISSUE THREAD

**Issue by mayooran99** [mqttjs/MQTT.js#434]
At times I am getting messages being published in the format of uint 8 array. I am writing the code in type script. Therefore below is how I used the message receiving callback.

`  this.client.on('message', (topic: string, message: string) => {
        this.onMessageArrived(topic, message, messageReceivedCallBack);
      });`

Is this scenario of receiving various data types handled inside? If I'm writing this code in Typescript, should I handle the data type conversion myself?

**Comment by mcollina** [comment]
I have no clue, as I'm not a TypeScript user.

cc @PekkaPLeppanen.

**Comment by PekkaPLeppanen** [comment]
This [example](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mqtt/mqtt-tests.ts) should explain the TypeScript part. 

```
client.on('message', (topic: string, message: Buffer) => {
    // message is Buffer
    console.log(message.toString());
    client.end();
});
```

The message is a NodeJS Buffer which implements the Uint8Array. https://nodejs.org/api/buffer.html

The data type conversion is left for the callback function. In the example the conversion is made from Buffer to String.
