### ISSUE TITLE
About MQTT over SSL connections

### ISSUE THREAD

**Issue by anhldbk** [mqttjs/MQTT.js#437]
I've got an MQTTs server with self-signed certificate. My below code doesn't work at all.

```js
var mqtt    = require('mqtt');

var options = {
  username: 'ping',
  password: '123456',
  host: '127.0.0.1',
  port: 8883,
  rejectUnauthorized: false
}
var client  = mqtt.connect(options);
client.on('connect', function () {
  console.log('Connected')
  client.subscribe(':event/status') // <- using # will cause the problem below
});

client.on('offline', function () {
  console.log('Offline')
});

```

Would you please tell me: How can I connect to an  MQTT server supporting `MQTT over SSL`?

**Comment by mcollina** [comment]
You need to specify a protocol, in your case `'mqtts'`.

Feel free to send a PR to the README to explain this a bit more :P.

**Comment by anhldbk** [comment]
@mcollina lol, you've made my day:

```js
var mqtt    = require('mqtt');

var options = {
  username: 'ping',
  password: '123456',
  rejectUnauthorized: false
}
var client  = mqtt.connect('mqtts://127.0.0.1:8883/',options);
client.on('connect', function () {
  console.log('Connected')
  client.subscribe(':event/status')
});

client.on('offline', function () {
  console.log('Offline')
});
```

**Comment by anhldbk** [comment]
@mcollina 

Would you pls let me know: why do we need parameter `url` for `mqtt.connect([url], options)` ? 

`The URL can be on the following protocols: 'mqtt', 'mqtts', 'tcp', 'tls', 'ws', 'wss'. `

Any use case for  protocols: 'mqtt', 'mqtts', 'tcp', 'tls', 'ws', 'wss' ?

Is that good to have `url` in `options`?

**Comment by mcollina** [comment]
You can pass `protocol: 'mqtts'` in the options.

It might also be good to have `url`  in options too.

**Comment by anhldbk** [comment]
@mcollina What's the role of `protocolId` in the options? Should we replace it by `protocol`?

**Comment by mcollina** [comment]
`protocolId` is the name of the MQTT protocol itself, `'MQIsdp'` for MQTT v3.1 or `'MQTT'` for MQTT v3.1.1. Also this should be set as `protocolVersion`, `3` or `4` respectively.

**Comment by sudhamab** [comment]
@mcollina as per the [README](https://github.com/mqttjs/MQTT.js), it's not recommended to use the `rejectUnauthorized: false`
in a prod environment ( which is what we want to do) to avoid the Man in the middle attack. 

We would like to communicate with the MQTT broker which sits on another machine on port 8883. 

I looked at [the example](https://github.com/mqttjs/MQTT.js/blob/master/examples/tls%20client/mqttclient.js) as well but not sure how the  'tls-key.pem', 'tls-cert.pem' apply for our case and if it will only suffice to pass 
the 'crt.ca.cg.pem'? 

And if the lattes is the case, then how do we generate the crt.ca.cg.pem file? 

Can we use [this](https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt) ? 

Would be grateful if you can advise us
