### ISSUE TITLE
How to set up to ensure that the MQTT client will have received the message

### ISSUE THREAD

**Issue by jonahzheng** [mqttjs/MQTT.js#440]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718100
I use the Mosca as MQTT server. how set “Quality of Service levels and protocol flows” is “At least once delivery”

**Comment by anhldbk** [comment]
@jonahzheng You mean: in addition to `qos = 2`, there will be an active client receives  such message?

**Comment by jonahzheng** [comment]
@anhldbk yes.
I found that mqttjs has qos.

mqtt.Client#subscribe(topic/topic array/topic object, [options], [callback])
Subscribe to a topic or topics
    options is the options to subscribe with, including:
        qos qos subscription level, default 0
