### ISSUE TITLE
Cannot work with React Native

### ISSUE THREAD

**Issue by pewh** [mqttjs/MQTT.js#442]
Hi,
Can you guide us how to use this library on React Native? I'm trying to use MQTT.js on React Native but didn't work because it requires 'net' native nodejs module. I'm also trying to compile mqtt.js with webpack and browserify. Unfortunately, these show same errors too.

**Comment by anhldbk** [comment]
It works well on Android. I already built a React Native app with `mqtt.js`.

**Comment by pewh** [comment]
Hmm, it strange, because react native shouldn't support native nodejs module like 'net' and 'fs' https://github.com/mqttjs/MQTT.js/blob/master/mqtt.js#L12-L15.

So this code below throw error:
```
var mqtt    = require('mqtt');
var client  = mqtt.connect('mqtt://test.mosquitto.org');
...

I'm wondering how you can bypass this limitation. Or maybe I should edit some code to make it work?

**Comment by RangerMauve** [comment]
React Native [supports websockets](https://facebook.github.io/react-native/docs/network.html#websocket-support) which should seamlessly work with mqtt.js

**Comment by pewh** [comment]
Although react native support websocket, but it doesn't support native nodejs modules which are dependency from mqttjs (like 'net' dan 'fs'). So I think the issue is not on websocket itself.
CMIIW :)

**Comment by mcollina** [comment]
Maybe it's a webpack issue then, the browser build should not load those.

**Comment by RangerMauve** [comment]
Are you trying to use a TCP MQTT connection in React-Native? Because it should only work with WebSockets. And as @mcollina said, your build should be respecting the "browser" field in `package.json` for this to work properly.

**Comment by pewh** [comment]
Hi @RangerMauve , I use MQTT on WebSockets. The good news is: I can rid the error message. I do ```webpack mqtt.js ./client.js --output-library mqtt```

and I'm trying to load this module by `const mqtt = require('mqtt/client')`. But I get undefined function when doing `mqtt.client(...)`. I inspect it via debugger and mqtt object is just empty object. I cannot get `mqtt.connect`.
I also have trying to use ```webpack mqtt.js ./client.js --output-library mqtt --output-librarytarget commonjs``` or ```webpack mqtt.js ./client.js --output-library mqtt --output-librarytarget commonjs2```, but still get empty object.

**Comment by pewh** [comment]
Finally, I fix it by `webpack mqtt.js ./client.js --output-library mqtt --output-library-target commonjs2` instead of `webpack mqtt.js ./client.js --output-library mqtt --output-librarytarget commonjs2`

Sorry for my stupid typo :smile:

**Comment by willin** [comment]
how about nativescript? 

a bit like react-native

**Comment by jinyuting** [comment]
@pewh so is that done? Does the client.js work for you? i met the same problem, the lib does not work with ReactNative....

**Comment by AlfredoPastor** [comment]
@pewh I join the questions of @jinyuting. 

I have managed to compile but when I initilize it, I have the following error: "mqtt.connect is not a function"

Regards.

**Comment by taoqf** [comment]
<https://www.npmjs.com/package/@taoqf/react-native-mqtt> works fine, and issues are welcome, If anyone is seeking for the solution.
