### ISSUE TITLE
FF 48 - Client will not connect

### ISSUE THREAD

**Issue by WilliamHolmes** [mqttjs/MQTT.js#445]
Works on: Chrome 52, FF 47

MQTT: v 1.13.0
BROKER: Apache Apollo 1.7.1

The  HTTP GET doesn't seem to get upgraded to WebSocket.

FireFox 48 (Not Working)
![image](https://cloud.githubusercontent.com/assets/5538260/17403377/549bc108-5a4f-11e6-97f4-52fafd584c49.png)

FireFox 47 (Working)
![image](https://cloud.githubusercontent.com/assets/5538260/17405004/c8361130-5a55-11e6-8f59-e17ca0c4435e.png)

After calling MQTT.connect( ....  the client.offline event it fired after a period of time.

The exact same code worked on FireFox 47, so I'm not 100% sure this is solely related to MQTT.js

**Comment by orlandodemauro** [comment]
issue related to https://github.com/feross/buffer/issues/120, it is fixed in buffer 4.9.0.

here the tree

 webpack@1.12.14
- node-libs-browser@0.5.3
`-- buffer@3.6.0

 webpack@1.13.1
- node-libs-browser@0.5.3
`-- buffer@3.6.0

webpack@2.1.0-beta.20
- node-libs-browser@1.0.0
`-- buffer@4.9.0

**Comment by WilliamHolmes** [comment]
FF48 - We're using Webpack 1.12.14

We'll update and verify.

Thanks.

**Comment by mcollina** [comment]
Any updates on this?

**Comment by orlandodemauro** [comment]
@mcollina the issue is when mqtt is used whit webpack 1.x.. I created a PR in webpack but it haven't been merged yet.

**Comment by orlandodemauro** [comment]
@mcollina @WilliamHolmes issue fixed, new node-libs-browser package delivered ( v0.6.0). it will be automatically picked by webpack 1.x. this issue can be closed. thanks
