### ISSUE TITLE
TLS conection

### ISSUE THREAD

**Issue by JuanRamino** [mqttjs/MQTT.js#447]
Hi,

I'm trying to connect to a TLS broker with no results.
Usually I connect with mosquitto_sub:
```
mosquitto_sub -h 1.1.1.1 -p 8883 -q 2 -t "#" --cafile /myPath/myCert.crt --tls-version tlsv1.2 -u user -P  password -v --insecure
```
But when I run this code
```
var mqtt = require('mqtt');
var fs = require('fs');

var CERT = fs.readFileSync('/myPath/myCert.crt');

var options = {
  host: '1.1.1.1',
  port: '8883',
  username: 'user',
  password: new Buffer('password'),
  certPath: CERT,
  rejectUnauthorized : false,
  debug: true
};

var client  = mqtt.connect(options);

client.on('connect', function(){
  console.log('Connected');
});
client.on('error', function(error) {
  console.log(error);
});
```
I get no output, no errors, nothing...
What's wrong in my options?

Thanks

**Comment by mcollina** [comment]
you should use `cert`  in place of `certPath`. Not sure _why_ it is not emitting a proper error.

Anyone that wants to dig into this and send a PR?

**Comment by JuanRamino** [comment]
Thanks Matteo,

I tried your solution but the result is the same.
How can I debug it?

**Comment by mcollina** [comment]
If `cert`  is the file of the certification authority, you should use the `ca` option: https://github.com/mqttjs/MQTT.js/blob/master/test/secure_client.js#L94-L99

**Comment by JuanRamino** [comment]
Now it works!

I use this options:
```
var options = {
  host: '1.1.1.1',
  port: '8883',
  username: 'user',
  password: new Buffer('password'),
  ca: CERT,
  protocol: 'mqtts',
  rejectUnauthorized : false,
  debug: true
};
```

Grazie Matteo, great job
