### ISSUE TITLE
client.end() sometimes returns `true`

### ISSUE THREAD

**Issue by brandly** [mqttjs/MQTT.js#453]
[Here's the line of code.](https://github.com/mqttjs/MQTT.js/blob/1fdc85dbda2270aca21c29009e6fd0f91258d0bc/lib/client.js#L437)

The comment above the method specifies `@returns {MqttClient} this - for chaining`, but doesn't this occasional `Boolean` prevent you from safely chaining?

**Comment by mcollina** [comment]
can you send a PR that fixes it? Maybe with unit tests.
