### ISSUE TITLE
About MQTT last wills

### ISSUE THREAD

**Issue by anhldbk** [mqttjs/MQTT.js#456]
@mcollina Is there any API (or spec) for updating last wills?

**Comment by mcollina** [comment]
No there is not.

**Comment by sandro-k** [comment]
@anhldbk disconnect and connect :)

**Comment by sclausen** [comment]
@anhldbk 
An addition to the answer from @mcollina: Details about the will flag are in the [mqtt spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf) in "3.1.2.5 Will Flag"
