### ISSUE TITLE
Question about TLS clients

### ISSUE THREAD

**Issue by anhldbk** [mqttjs/MQTT.js#457]
I'm reading the example code of [TLS clients](https://github.com/mqttjs/MQTT.js/blob/master/examples/tls%20client/mqttclient.js).

Would you please tell me: what are options `keyPath`, `certPath`, `ca` for?  Is the code implementing client-side-certicated clients? 

Actually, my use case is: I have a server with a self-signed certicate. Let's assume that I have a way to securely transfer the public key to clients. How can I let `mqtt.js` to accept the key?

**Comment by ralphtheninja** [comment]
The public key is public, so it doesn't need to be transferred securely. Just FYI :)

**Comment by anhldbk** [comment]
@ralphtheninja Man in-the-middle attack can fake public keys. Just FYI :3

**Comment by mcollina** [comment]
@anhldk would you mind adding a little guide with Mosquitto or Mosca on how to setup all of this? It's probably the most asked question, and it seem we need some more how-tos in the area.


1. the *Path version should not be use and are deprecated
2. it all just works as the tls module from core

**Comment by anhldbk** [comment]
@mcollina Currently I have no idea about TLS-configured clients. Would you mind explaining it a little bit?

**Comment by mcollina** [comment]
Which part of https://nodejs.org/dist/latest-v4.x/docs/api/tls.html#tls_tls_ssl are not clear? You can pass the same options in the same places.

**Comment by ralphtheninja** [comment]
> @ralphtheninja Man in-the-middle attacks can fake self-signed public keys. Just FYI :3

I stand corrected! :)

**Comment by anhldbk** [comment]
@mcollina Ok! I read the TLS documentation. Let's me see what I can help.

**Comment by anhldbk** [comment]
@mcollina Should the tutorial be in a separated file or in `README.md`? I think it's better to get the tutorial placed in `examples/tls server`.

**Comment by mcollina** [comment]
@anhldbk That's good. Also, add a link on the README for that to the tutorial "if you have TLS errors, go here".
