### ISSUE TITLE
util.inherits deprecated

### ISSUE THREAD

**Issue by wuhkuh** [mqttjs/MQTT.js#458]
Good afternoon,

after looking in the source files in 'server.js' I found the following lines:
```
util.inherits(MqttServer, net.Server);
util.inherits(MqttSecureServer, tls.Server);
```

A lookup on the node.js documentation got me this:

> Note: usage of util.inherits() is discouraged. Please use the ES6 class and extends keywords to get language level inheritance support. Also note that the two styles are semantically incompatible.

Are there plans to update this code to the latest standards?

**Comment by mcollina** [comment]
MQTT.js v2 will remove the support for Server ans SecureServer, as they are misleading.
