### ISSUE TITLE
A poor connection can cause a single packet to be sent many time on reconnect. Multiple duplicated subscriptions will kill the AWS IoT connection and will not recover.

### ISSUE THREAD

**Issue by miotabbott** [mqttjs/MQTT.js#460]
In certain situations a packet from the client `outgoingStore` can rewrite the `outgoing` callback for the packet to reference the `outgoingStore` flushing code (an anonymous function in `storeDeliver`) recursively on each unack'd packet.

AWS IoT does not tolerate many duplicate ack'd subscription messages and will kill the connection when this happens.

Unit test and fix in the works.

**Comment by mcollina** [comment]
Thanks, a PR is highly welcomed!

**Comment by miotabbott** [comment]
As a fun bonus, the unit test exhibits issue #450

**Comment by pguerin-miovision** [comment]
@mcollina Any idea of the typical turn around time to accept and publish a pull request like this once it's ready?  Trying to sort out some short term options if we think it could be a while before this makes its way through. Thanks in advance for any feedback!

**Comment by mcollina** [comment]
@pguerin-miovision roughly days or at most a week, as you can see from past prs. We all do this in our free time: if you want you can help.

**Comment by miotabbott** [comment]
Patch for master up #468.
Build bot for #467 passed with build 779.

**Comment by YoDaMa** [comment]
closing this issue because looks like #468 and #470 respond to this.
