### ISSUE TITLE
Cannot work with nativescript

### ISSUE THREAD

**Issue by willin** [mqttjs/MQTT.js#462]
#442

how about nativescript?

a bit like react-native

``` js
var ws = null

    if (typeof WebSocket !== 'undefined') {
      ws = WebSocket
    } else if (typeof MozWebSocket !== 'undefined') {
      ws = MozWebSocket
    } else {
      ws = window.WebSocket || window.MozWebSocket
    }

    module.exports = ws
```

there is no `window` in native.

**Comment by mcollina** [comment]
I do not know what nativescript is, but I'm happy to accept a pull request that solves the issue.

**Comment by RangerMauve** [comment]
This seems to be something that should be addressed in the ws module. https://github.com/websockets/ws

**Comment by taoqf** [comment]
@willin Have you solved this Issue? @RangerMauve @mcollina , it seems this is nothing todo with the ws module, I think it is webpack thing. webpackt changes the code ws and i don't know why and how can i fix this.

**Comment by RangerMauve** [comment]
Hi, I haven't progressed on this on my side because I got sidetracked. You should try to browserify the MQTT.js bundle and import that instead of the module and see if that works.
