### ISSUE TITLE
Need example to use mqtt.Client(streamBuilder, options)

### ISSUE THREAD

**Issue by kranthisai** [mqttjs/MQTT.js#463]
Hi, 
    I am trying to use socks5 proxy to connect to mqtt broker. can anybody post a sample script on using 

mqtt.Client(streamBuilder, options). especially streambuilder,

**Comment by mcollina** [comment]
I have __never__ used socks5 with MQTT, so there are no examples.
However, it would be great to have one? Do you mind sending a PR?

I would suggest you to look at https://github.com/mscdex/socksv5.

**Comment by kranthisai** [comment]
We were able to use socks5 with Mqtt. Thanks for your link. I already tried that before, but couldn't succeed before, but now working fine. Tested on both IBM and AWS MQTT brokers. I will try for PR, never done it before..

**Comment by BrandonSmith** [comment]
@kranthisai You mentioned that you were able to use SOCKS5 with MQTT. Was this with MQTT.js or another library? What details or examples can you share if it was with MQTT.js?

**Comment by kranthisai** [comment]
Yes MQTT.js

Example: 

'use strict';

var mqtt = require('mqtt');
var socks = require('socksv5');
var fs = require('fs');

var client1 = socks.connect({
    host: 'a3q7q4g3xqxnrz.iot.us-east-1.amazonaws.com',
    port: 8883,
    proxyHost: 'proxy-us.intel.com',
    proxyPort: 1080,
    auths: [ socks.auth.None() ]
},function(socket) {

    var mqttClient = mqtt.connect({
	socket: socket,
        port: 8883,
        host: '',
        protocol: process.env.MQTT_PROTOCOL ||'mqtts',
        clientId: ''
        key: ''
        cert:''
        ca: ''

    });
    mqttClient.on('connect', function(){
        console.log('mqtt connection successful');
        mqttClient.subscribe('peopleCount');
        
    });
    mqttClient.on('message', function (topic, message) {

        console.log(topic);
        console.log(message.toString());
        
    });
  mqttClient.on('reconnect', function(){
  console.log("%s MQTT client reconnecting", now());
});

mqttClient.on('close',function(){
  console.log("%s MQTT client disconnected", now());
});

mqttClient.on('offline', function(){
  console.log("%s MQTT client went offline", now());
});

mqttClient.on('error', function(err){
  console.log('%s MQTT client error: %s', now(), err);
});
function now() {
  return new Date().toISOString();
}
});

**Comment by lygstate** [comment]
How to do reconnect with stream?

**Comment by StephanGerbeth** [comment]
i'm also interested in reconnecting a stream. :)
