### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by zzzbatmand** [mqttjs/MQTT.js#464]
When i try to run the default example code i get this error:

```
/home/skypeBot/basicbot/node_modules/mqtt/lib/connect/index.js:63
    opts.protocol = opts.protocol.replace(/:$/, '')
                                 ^

TypeError: Cannot read property 'replace' of null
    at Object.connect (/home/skypeBot/basicbot/node_modules/mqtt/lib/connect/index.js:63:34)
    at Object.<anonymous> (/home/skypeBot/basicbot/mqtt.js:2:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

**Comment by zzzbatmand** [comment]
Found the problem. I forgot the "mqtt://" in the connection.

Btw, it also seems to have some problems connecting to an ip address instead of a url.

**Comment by mcollina** [comment]
I think we should catch those situations and emit a proper error! Would you like to send a PR?

**Comment by zzzbatmand** [comment]
I am not that good at git, but all it needs is "mqtt://" in the `var client  = mqtt.connect('muqtt://custom.url')` function, before the url or else the /lib/connect/index.js file would complain about replacing in null (witch would be the "mqtt://" that it got parsed by `opts = xtend(url.parse(brokerUrl, true), opts)` at line 60)

So if you could see if the input started with "mutt://" to make sure it was set, else print an error to the user and then just returning to the main program.

Otherwise, you could see if "opts.protocol" was empty then handle an error from there.


Also, it works with an ip address, it just seems to have glitched first time i tried, but it works now.

**Comment by mcollina** [comment]
Contributing a pull request is an easy way to learn git, and get familiar with node.js tooling.
I have no time to tackle this, so feel free (you or anyone else), to send a pull request.

**Comment by ralphtheninja** [comment]
@mcollina I'm on this. But how should we handle this? If a string is passed in e.g. `test.mosquitto.org` instead of `mqtt://test.mosquitto.org` should we default the protocol to `mqtt`?

**Comment by RangerMauve** [comment]
@ralphtheninja If you choose to have a default protocol, make sure to take into account whether you're in the browser, as well.

**Comment by mcollina** [comment]
I think we should just throw if the protocol is missing, but with a more meaningful error
