### ISSUE TITLE
Message.toString() comparison 

### ISSUE THREAD

**Issue by tchinou1** [mqttjs/MQTT.js#475]
Hi guys ! I'm trying to compare the message.toString() in a IF statement, and I don't understand why it is not working.

In my code, the console.log output "test" but the if statement returned false (it doesn't run).

Can anybody telling my the message converted to a string can't be compared ?

Thanks
```js
client.on('message', function (topic, message) {
  console.log(message.toString());

  if(message.toString() == "test") {
	  console.log("it worked");
  }
});
```

**Comment by ralphtheninja** [comment]
@tchinou1 If the comparison is false then the string doesn't equal "test" :) Do you have a newline or something in your message?

**Comment by tchinou1** [comment]
I think I did, I added .trim() and now it's working !

Thanks :)

**Comment by ralphtheninja** [comment]
Cool. Please close issue! Or maybe @mcollina can do that :)
