### ISSUE TITLE
node.js: wss protocol default to port 80 instead of 443

### ISSUE THREAD

**Issue by kintel** [mqttjs/MQTT.js#477]
The node.js (non-browser) connection builder defaults to port 80 for wss connections, while the browser-equivalent sets the port to 443.
See https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/ws.js#L19

Since mqttjs swallows connection errors, this may cause hard-to-debug connection issues.

Should we add similar code here for defaulting the port to 443 for wss connections?

**Comment by mcollina** [comment]
Yes we should. Would you like to contribute a PR?

**Comment by kintel** [comment]
sure, I'll look into it.
