### ISSUE TITLE
rollup, es6 support?

### ISSUE THREAD

**Issue by aedart** [mqttjs/MQTT.js#479]
At the moment, it is very difficult to get the mqtt module to work with rollup. Therefore, I am wondering when you are going to release this package as es6?

**Comment by mcollina** [comment]
As far as I understand, this questions revolves around ES6 modules, and not other ES6 features. If this is not the case, please explain.

MQTT.js will be based on ES6 modules when it could run on top of any supported version of Node without a transpilation step. Currently this number is zero, so it will probably take a few lts cycles to get there.

Anyway, I am very happy of accepting any PRs that would make the integration with rollup easy, as long as it keeps running with no transpilation step on all supported versions of Node.

It would be good to see if we can work a reference on how to achieve this. Maybe rollup supports some metadata.

**Comment by aedart** [comment]
I wish that I had a good solution, but at the moment, I'm not even able to run a single connect test, because of [commonjs'](https://github.com/rollup/rollup-plugin-commonjs) failure to resolve nested dependencies. I have no idea why, and therefore "fishing" for help anywhere I can...

See https://github.com/rollup/rollup-plugin-commonjs/issues/134 for further info.

Anyways, ty for your reply.

**Comment by mcollina** [comment]
closing this now. Feel free to open issues if it turns out it's MQTT.js fault.

**Comment by lesquirrel23** [comment]
I use polymer - based on the current pwa starter kit - and want to integrate mqttjs. As far as i understand (sry, newby in js) with polymer in the default way i'm only able to integrate es6 modules.

Is there any plan to support es6 module import or is the answer above still valid? 
Thanks.

**Comment by Crisfole** [comment]
Bump. This is definitely problematic. Even with `rollup-plugin-commonjs` installed we can't import the thing. Building with rollup and including es6 _and_ common js distributions is the way to go these days.

**Comment by idbartosz** [comment]
I've tried with _rollup-plugin-node-builtins_ and _rollup-plugin-node-globals_ and it's imported but probably due to circular dependencies the `connect` function throws:

**[Rollup 2.17.0] compile warning:**
```
(!) Circular dependencies
node_modules/readable-stream/lib/_stream_readable.js -> node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_readable.js
node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_writable.js -> node_modules/readable-stream/lib/_stream_duplex.js
node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_writable.js -> /Users/bartoszk/Projects/mqtt-dashboard/node_modules/readable-stream/lib/_stream_duplex.js?commonjs-proxy -> node_modules/readable-stream/lib/_stream_duplex.js
...and 3 more
```

**[Chrome 83.0.4103.106] calling `mqtt.client`**
```
_stream_duplex.js:77 Uncaught (in promise) TypeError: this.once is not a function
    at BufferList$1.Duplex$1 (_stream_duplex.js:77)
    at new BufferList$1 (bl.js:33)
    at BufferList$1 (bl.js:8)
    at Parser._resetState (parser.js:31)
    at new Parser (parser.js:22)
    at Object.Parser [as parser] (parser.js:11)
    at MqttClient._setupStream (client.js:289)
    at new MqttClient (client.js:276)
    at Function.connect$1 [as connect] (index.js:154)
```

So in the end to use it in _Rollup_ we have to compile it with _Webpack_ or import via script tag and then in `rollup.config` set it up as `external: ["mqtt"]` and `globals: { mqtt: "mqtt" }`. This way everything works but I'd prefer to have it compiled during my build instead of external dependency 😉

**Comment by kcdipesh** [comment]
Did anyone manage to successfully import using rollup or es6 import syntax?

**Comment by chartinger** [comment]
Ended up with the same workaround as @idbartosz - include the compiled file in script and declare the global var in typescript. Failed miserably trying to get it imported with rollbarjs (and therefor vite)

**Comment by psi-4ward** [comment]
seems mqttjs targets only node and not the browser
