### ISSUE TITLE
WebSocket Message Type

### ISSUE THREAD

**Issue by 256dpi** [mqttjs/MQTT.js#480]
Hi @mcollina 

Is the shift to the TextMessage type in 2.0 away from the BinaryMessage type intended?

AFAIK there is no written standard that the BinaryMessage has to be used, yet I have the feeling that would more match the MQTT protocol as the serialized packets are a binary stream.

**Comment by mcollina** [comment]
Can you please rephrase it?

If I understand it correctly, that issue should be solved, and it should be moving binary data only now.

**Comment by 256dpi** [comment]
I just created a browser lib from MQTT.js 2.0.1 using browserify and my broker rejected the connection as the messages are sent using the TextMessage WebSocket message type. My latest build from 1.4.0 still uses the BinaryMessage.

**Comment by mcollina** [comment]
Are you on https://github.com/maxogden/websocket-stream v3.3.0?
In the browser or on node?

**Comment by mcollina** [comment]
It might be a bug there, I have probably fixed it for Node, but not for the browser: https://github.com/maxogden/websocket-stream/blob/master/stream.js#L63-L83.

**Comment by 256dpi** [comment]
Yes npm installed v3.3.0.

I was testing with Safari and a recent Chrome.

**Comment by mcollina** [comment]
See my last comment. I'm stuck for the next couple of days, would you like to send a PR to websocket-stream?

**Comment by 256dpi** [comment]
I'll first make a fix for shiftr.io and look into it if I have time. ;)

**Comment by sjmf** [comment]
I've just noticed something I suspect may be related to this issue in one of my own projects (reference from commit a2d68b9): fixing the MQTT.js version at 1.14.1 made my code work again :)

My symptoms were that the broker (ActiveMQ) would close the connection immediately with a `java.io.IOException`, but I'm not sure how to check the message type being sent to tell you for sure if it's related to this issue. Leaving a comment just so you don't puzzle about the above reference :)
