### ISSUE TITLE
Enhancement: Include browser version

### ISSUE THREAD

**Issue by TotallyInformation** [mqttjs/MQTT.js#492]
Hi, I use this library a lot but more often in the browser than in node itself.

It is a pain to have to manually create the browser version. 

If you were to use browserify/webpack to create **`./dist/mqtt.js`** when you create a new version, not only would it be ready to use in the browser, it would also be picked up automatically by **`https://unpkg.com`** so anyone could use it directly in any web page without needing to know anything about Node, browserify/webpack, etc.

Minimal effort for maximum gain!

You might also consider adding the appropriate browser build script to the package.json for user convenience.

**Comment by mcollina** [comment]
@TotallyInformation that would be an handy feature, yes!

**Comment by mcollina** [comment]
@TotallyInformation I've just done a release. Please test (v2.1.0 still does not show up on unpkg, it might take a while)

**Comment by mcollina** [comment]
Here it is: https://unpkg.com/mqtt@2.1.1/dist/mqtt.min.js.

**Comment by mcollina** [comment]
Let me know if it works as expected.

**Comment by TotallyInformation** [comment]
Wow! Thanks, great service 👍 

I'll give it a go ASAP though I'm sure it will be fine. For reference, you can just do https://unpkg.com/mqtt/dist/mqtt.min.js to always get the latest version, it automatically redirects.

**Comment by andyfenelon** [comment]
Im getting this error
following this example http://mitsuruog.github.io/what-mqtt/

> WebSocket connection to 'ws://test.mosquitto.org:8080/mqtt' failed: Connection closed before receiving a handshake response

```
    <script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>

    <script>
    var client = mqtt.connect('ws://test.mosquitto.org:8080/mqtt');

    client.subscribe('mitsuruog')

    client.on('connect', function () {
      alert('connected')
    })
    client.on("message", function(topic, payload) {
      alert([topic, payload].join(": "));
      client.end();
    });
    </script>
```

**Comment by mcollina** [comment]
@andyfenelon that is a duplicate of #482, and addressed in https://github.com/maxogden/websocket-stream/pull/100. You can rebuild the bundle with some custom code in `websocket-stream` and test.

**Comment by andyfenelon** [comment]
ok thanks.

**Comment by mcollina** [comment]
V2.1.2 released.
