### ISSUE TITLE
Mosquitto web socket connection fails

### ISSUE THREAD

**Issue by i8beef** [mqttjs/MQTT.js#494]
I'm having some trouble connecting to a Mosquitto (1.4.10, was on 1,4,4 with same issue, upgraded hoping it was a problem there, no change) over web sockets. I can confirm I can connect to it via web sockets using (http://www.hivemq.com/demos/websocket-client/), so I don't think it's my setup...

Using https://unpkg.com/mqtt@2.1.1/dist/mqtt.min.js

On attempt to connect I'm getting "mqtt.min.js:7 WebSocket connection to 'ws://x.x.x.x:9001' failed: Connection closed before receiving a handshake response".

Code below:

    var client = mqtt.connect("ws://x.x.x.x:9001", {
        username: "username",
        password: "pass"
    });

    client.on("connect", function() {
        client.subscribe("alarm/motion/kitchen");
    });

**Comment by mcollina** [comment]
Should be fixed in 2.1.2. Please check and revert.

**Comment by i8beef** [comment]
Nope, still getting the same thing.

**Comment by i8beef** [comment]
2.1.3 fixed this. Thanks!
