### ISSUE TITLE
message event is emmited infinitely

### ISSUE THREAD

**Issue by brianjang** [mqttjs/MQTT.js#495]
Hi. could you review my problem that is related "message" event?

from my test code : 
[code here] https://github.com/brianjang/mqtt_test/tree/master/core/protocols

- mqtt_sub.js // has the current issue code part

- mqtt_pub.js // just only 1-time publish

- mqtt_test.js //this is for Redis, but it shows the same problem as mqtt_sub.js

**MY PROBLEM :** 
if i add client.publish() into client.on("message") event,
then mqtt.js call infinitely client.on("message") event

var mqtt = require("mqtt");
var client = mqtt.connect("mqtt://localhost:1885"); //this mosquitto broker
`client.on("message", function(topic, message, packet)` {
  console.log("mqtt_sub event message ===========================".bold.red);
  console.log(topic);
  console.log(message.toString());
  console.log(packet);

 ` client.publish("test", "hello mqtt");`
});

var sub_topic = {"test/#": 0};
client.subscribe(sub_topic,function (err, granted) {
  console.log("mqtt_sub callback =============".blue);

  if (err) {
    console.log("mqtt_sub callback =============".red);
    console.log(err);
  }

  console.log(granted);

});

here is my log message : 
`
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74^C

`

**Comment by mcollina** [comment]
This happens because you are effectively creating an infinite loop, as the subscription `test/#` matches `test`.

This is how MQTT works.

**Comment by brianjang** [comment]
Hi.

i modified topic from "test/#" to "test"
- topic in mqtt_sub.js 
- and topic in mqtt_pub.js
(and all part is the same)
`var topic = "test";`
client.publish(topic, "published by mqtt broker", option, function (err) {
  console.log("mqtt_pub callback ===============".blue);
  if (err) {
    console.log("mqtt_pub callback error ===============".red);
    console.log(err);
  }
});

but the result show the same problem.

this is log message
`
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt
Packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 16,
  topic: 'test',
  payload: <Buffer 68 65 6c 6c 6f 20 6d 71 74 74> }
mqtt_sub event packetsend ======================
publish
mqtt_sub event packetreceive =====================
publish
mqtt_sub event message ===========================
test
hello mqtt

`

**Comment by mcollina** [comment]
As I said test/# includes test.

**Comment by brianjang** [comment]
I got it.
Thank you for your answer.

I have been using MQTT.js v1.x, and today i try to migrate MQTT.js v2.1.2.
i didn't use external mqtt broker, i only used MQTT.js/lib/server.js and mqtt-connect.
- mqtt-connect emit event 'publish', 'subscribe' : i worked this event to develop private push server.
my stupid question is started :) cause i was confusing event driven(in mqtt-connect) and just function call (in mqtt.js v2.x)

please tell me if i can help :)

**Comment by mcollina** [comment]
It's still not clear what you want to achieve. You can still use http://npm.im/mqtt-connection if you prefer.

**Comment by brianjang** [comment]
the needed function in my side is round-robin function :+1: 
https://www.rabbitmq.com/tutorials/tutorial-two-javascript.html
- specially "Round-robin dispatching"

is there any method to apply "Round-robin dispatching"? (in MQTT.js)
- or do i need a kind of scheduling algorithm by myself?

Thank you.

**Comment by mcollina** [comment]
MQTT does not support that. If you need a subscriber on the "cloud" side of things, add it as a plugin inside the broker.
