### ISSUE TITLE
npm run browser-build failed

### ISSUE THREAD

**Issue by xiaochutian** [mqttjs/MQTT.js#499]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "browser-build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! mqtt@2.1.3 browser-build: `rm -rf dist/; mkdir dist/; browserify mqtt.j
s -s mqtt > dist/mqtt.js; uglifyjs --screw-ie8 < dist/mqtt.js > dist/mqtt.min.js
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mqtt@2.1.3 browser-build script 'rm -rf dist/; mkdir dist
/; browserify mqtt.js -s mqtt > dist/mqtt.js; uglifyjs --screw-ie8 < dist/mqtt.j
s > dist/mqtt.min.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mqtt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist/; mkdir dist/; browserify mqtt.js -s mqtt > dist/mqtt.j
s; uglifyjs --screw-ie8 < dist/mqtt.js > dist/mqtt.min.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mqtt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mqtt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\XiaoChutian\node_modules\mqtt\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "."
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! mqtt@2.1.3 prepublish: `npm run browser-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mqtt@2.1.3 prepublish script 'npm run browser-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mqtt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run browser-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mqtt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mqtt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\XiaoChutian\node_modules\mqtt\npm-debug.log

**Comment by mcollina** [comment]
I'm sorry but that npm script has been written for Linux and Mac in mind. I do not have much Windows time to solve this. Would you like to send a PR?

**Comment by arvindpdmn** [comment]
I have the same problem. I made this change for Windows but it's more of a hack:

    "browser-build": "rmdir dist /S /Q || mkdir dist && browserify mqtt.js -s mqtt > dist/mqtt.js && uglifyjs --screw-ie8 < dist/mqtt.js > dist/mqtt.min.js",

Not sure how to write it such that it works across platforms. `rmdir` can fail if the folder does not exist in the first place. Hence used `||` condition. A better way would be to check if folder exists. Also, `uglify-js` must be installed globally but not sure how to capture this dependency because `npm install .` installs stuff locally.

**Comment by RangerMauve** [comment]
An easy solution would be to use the [rimraf](https://www.npmjs.com/package/rimraf) and [mkdirp](https://www.npmjs.com/package/mkdirp) modules as dev dependencies.
