### ISSUE TITLE
how do i know the reason why MQTT client go offline

### ISSUE THREAD

**Issue by helxsz** [mqttjs/MQTT.js#500]
I can see the event 'offine' ,but how do i know the reason why MQTT client go offline ?

**Comment by 4rzael** [comment]
If I recall correctly, you can't.

Why do you want to do that ?

**Comment by mcollina** [comment]
One thing we do not put a distinction on our side is if the connection closes or if we receive a DISCONNECT packet. That's the only difference we can do.
I'm happy to get a PR on that.

Closing this for now.

**Comment by helxsz** [comment]
Hi, primarily it is for a debug reason.
