### ISSUE TITLE
certain messages lost when sending en masse. 

### ISSUE THREAD

**Issue by gitawego** [mqttjs/MQTT.js#501]
in my application, I have a lot of database to be synchronized to a device (more than 500 records).
my code is similar to this:
```js
data.forEach(function(d){
 client.publish(topic,d,{ qos: 2 });
});
``` 
with this code, the messages are randomly partially lost. the target device doesn't receive all the data in most of time. 

but if the messages are sent one by one after publish callback, it works:

```js
// suppose we have mutex here:
data.forEach(function(d){
 mutex.lock(()=>{
 client.publish(topic,d,{ qos: 2 },(err)=>{
   mutex.unlock();
 });
});
});
```

do you have any idea about this issue ? 

we use mqtt.js in nodejs, not in browser. the broker is mosquitto. both client and broker are tested in local machine.

thanks in advance.

**Comment by mcollina** [comment]
You are trying to send all the messages in parallel: the broker is probably telling you that you cannot do that.

Try sending them one after another, using something like http://npm.im/async.

**Comment by gitawego** [comment]
thanks for your reply. that's what I'm doing using mutex now. 
it would be more convenient if mqtt.js could integrate a queue system though.

**Comment by mcollina** [comment]
You can use http://npm.im/fastq

**Comment by gitawego** [comment]
thanks, gonna check this out.
