### ISSUE TITLE
Server side client

### ISSUE THREAD

**Issue by kani-rifluxyss** [mqttjs/MQTT.js#502]
We need to have a client running on server and receiving all messages coming to broker, will subscribe using # wildcard, will it hit any kind of limit other than OS limits? I have a php based script running in a look and doing that for us (currently less than 5 users). I am thinking of switching to this node based app to replace that script.

Looking for some advise. Thanks in advance.

**Comment by 4rzael** [comment]
I, personnally, never encountered any problems with a client running on the server.

I only did it with a small number (<100) of clients simultaneously connected to the broker, though, but I don't see why it should cause problems at scale.

**Comment by kani-rifluxyss** [comment]
ok thanks,
