### ISSUE TITLE
How do I subscribe to all topics?

### ISSUE THREAD

**Issue by leontastic** [mqttjs/MQTT.js#504]
I tried subscribing to all topics by subscribing to the `#` wildcard:
```javascript
mqttClient.subscribe('#')
```

I'm unable to receive any messages from the broker with this subscription. Subscribing to any other topic (including a wildcard or not) seems to work for me. Can someone explain why subscribing to wildcard `#` doesn't work?

**Comment by leontastic** [comment]
It seems that subscribing to `+/#` achieves the result I'm looking for.

Still not sure why a subscription to `#` fails to receive messages completely.

**Comment by jdiamond** [comment]
Does the topic start with a `$`? You don't receive notifications for those topics when subscribing to `#`.

**Comment by leontastic** [comment]
Nope. I'm not interested in `$SYS` topics. My test consists of sending 'Hello World!' on these channels:

- `test`
- `test/test1`
- `test/test1/test2`

Subscribing to `#` doesn't seem to subscribe to anything at all. If I push retained messages to any topics in the broker, subscribing to `+/#` will get all of those retained messages on connection/reconnection, while a subscription to `#` remains silent.

**Comment by RangerMauve** [comment]
What broker are you using? It might be related to that since this library doesn't do anything special to subscription topics.

**Comment by leontastic** [comment]
I'm using [EMQTT](https://github.com/emqtt/emqttd).

I see a PR in this repository implementing topic validation: https://github.com/mqttjs/MQTT.js/pull/438.

Is it possible that MQTT.js contains validation logic which would block a subscription to `#`? A quick cursory review of that PR seems to contain logic specific to the `#` wildcard.

Here's the full diff: https://github.com/mqttjs/MQTT.js/pull/438/files

**Comment by RangerMauve** [comment]
@leontastic Are you getting an error in the callback passed to `.subscribe`?

**Comment by leontastic** [comment]
No, no errors.

I just tried connecting to another broker (public HiveMQ test broker `mqtt://broker.hivemq.com:1833`) and it seems that a subscription to `#` works there. Probably means this is an issue with EMQTT, not MQTT.js, so I'll close this issue for now and investigate on the other end.

Thanks @jdiamond @RangerMauve for the responses!

**Comment by RangerMauve** [comment]
If possible, link back here if you find a solution so that others can follow your steps if they face this issue.

**Comment by Tobbe** [comment]
Super old topic, but for anyone else coming here, you have to explicitly enable this in EMQX Cloud if that's what you're using
![image](https://github.com/mqttjs/MQTT.js/assets/30793/8e0d0ab6-cfed-4432-bb3d-a1b6fb748554)

And if you host EMQX yourself there's a default rule you have to remove or override that also blocks subscribing to the `#` wildcard topic
https://github.com/emqx/emqx/issues/3052
