### ISSUE TITLE
Integration tests on Github Actions for all OSS brokers

### ISSUE THREAD

**Issue by mcollina** [mqttjs/MQTT.js#505]
It would be awesome to receive a contribution to do some integration testing against the major OSS brokers.

Something using Travis ENV support, or similar. It might even be a separate repo, feel free to discuss!

**Comment by ralphtheninja** [comment]
@mcollina Do we have any integration tests implemented?

**Comment by mcollina** [comment]
zero. But I think we should.

**Comment by sandro-k** [comment]
I am on board.. Lets start with something simple like Mosca and expand from there.

**Comment by mcollina** [comment]
I have no time to coordinate this :(. I would suggest we should start with Mosquitto and Mosca. Please go ahead and do it, I will be happy to review.

**Comment by 4rzael** [comment]
I completely agree on this. I don't have time to help right now, but I'll be happy to do so when possible.

**Comment by sandro-k** [comment]
I am trying to free some time next week.

**Comment by anhldbk** [comment]
Would you guys elaborate more on how we take integration tests? I think we should make a to-do list now. For example:

- [ ] Listing all OSS Brokers
- [ ] Specify what to test ...

**Comment by sandro-k** [comment]
Thanks @anhldbk for getting this started again.

# Brokers
* Mosquitto
* Mosca

# What to test
* Connect 
  * SSL/TLS
* Subscribe
  * QOS 0,1,2
  * Retained 
* Publish
  * Retained
* LWT

# Platform 
* Node.js
* Browser

**Comment by anhldbk** [comment]
Currently, I am using [emq broker](http://emqtt.io/) and find it great. It's written in Erlang (suitable for production environments). 

About `What to test`, should we have tests for  `MQTT Over WebSocket`?

**Comment by mcollina** [comment]
@anhldbk I think so, yes.

**Comment by mcollina** [comment]
It would be awesome to have integration tests also via SauceLabs.

**Comment by anhldbk** [comment]
The integration test results should be organized into a report with:

1. Information about brokers
2. For each broker, we should have describe the running environment. It must be reproducible. (Docker may be a great relief)
3. Associated test scripts
4. Finally, a summary

@sandro-k , @mcollina is that ok?

**Comment by mcollina** [comment]
@anhldbk yes! Go ahead and make it docker-based.

Bonus points (but keep it separate): websockets in browsers.

**Comment by YoDaMa** [comment]
changed the name since this is still a relevant ask but we're using Github Actions now.
