### ISSUE TITLE
https website how to use mqtt via wss

### ISSUE THREAD

**Issue by xiaoDC** [mqttjs/MQTT.js#507]
our website change http to https, so the browser reminds us to connect mqtt server via wss. I run the wss example, it does work.But when i use in the browser, it does not work!

**Comment by sandro-k** [comment]
Can you please post an example and what kind of error you are getting. Probably the MQTT-Server is not using the right SSL certificate!

**Comment by xiaoDC** [comment]
I am sorry. It is our mqtt-server error. We does not use the right SSL certificate! It does work!
