### ISSUE TITLE
Can't get code working. 

### ISSUE THREAD

**Issue by OczkoSX** [mqttjs/MQTT.js#508]
Hi. I can't get following code working: http://pastebin.com/705JAcWz
What can be wrong? It doesn't print anything, I need to terminate it by CTRL+C.

**Comment by mcollina** [comment]
the code seems right. Does it work if you connect to test.mosquitto.org instead? Are the credentials correct?
Browser or Node?

**Comment by OczkoSX** [comment]
I'll try later. Credentials are 100% fine, broker is Mosquitto on RPi. I'm using node. Does mqtt.connect return any errors? It doesn't print anything

**Comment by mcollina** [comment]
try publishing in the subscribe callback.
Il giorno sab 3 dic 2016 alle 06:44 OczkoSX <notifications@github.com> ha
scritto:

**Comment by OczkoSX** [comment]
Like that?:
client.subscribe('HAP/esp8266_1/#', function() {
  //publish
});

**Comment by mcollina** [comment]
yes

**Comment by OczkoSX** [comment]
Still nothing.

http://pastebin.com/7Yr69m7C

**Comment by OczkoSX** [comment]
I don't know how, but It suddenly started working. Thanks for your help
