### ISSUE TITLE
Connect on event

### ISSUE THREAD

**Issue by chimit** [mqttjs/MQTT.js#509]
Sorry for the stupid question, but how can I initiate a connection on another event? For example, on button push? I'm using MQTT.js in the browser.

**Comment by mcollina** [comment]
You can't. you create the connection when the button is clicked.

**Comment by chimit** [comment]
Sorry, @mcollina, maybe I'm not clear enough. I want to bind the connection to some event like this:
```
const client = mqtt.createClient({
    host: 'abc',
    port: 8883,
    protocol: 'mqtts',
    username: 'abc',
    password: 'abc',
});

$('#connect').click(function() {
    client.connect();
```
Is it still impossible?

**Comment by mcollina** [comment]
Using the current API, yes.

I'm happy to discuss a semver-major contribution on this, if you are willing to help.
