### ISSUE TITLE
finding the slowdown

### ISSUE THREAD

**Issue by ajoslin103** [mqttjs/MQTT.js#513]
I'm running on a mac, I'm using the mosquitto as installed by homebrew I've got a publisher written in python and a subscriber in chrome using mqtt.js and another subscriber as the MQTT.fx program.

The python job is publishing a [roughly] 2K message (stringified json) 
For comparison: the same python job as a cgi script returning the same data

cgi script: the data is returned in [roughly] 1 second
onMessage in MQTT.fx gets the data in [roughly] 1 second
onMessage in the web browser gets the data in [roughly] 10 seconds

Why is it so slow in the browser?  Can anyone suggest anything to help me figure this out?  I _really_ want to use MQTT but I can't justify the overhead 

(note: when the message is 196 chars the time is only [roughly] 2 seconds -- so it seems related to message size...)

My mosquitto conf is:
```
listener 8000 127.0.0.1
port 1883
protocol mqtt
protocol websockets
```

My mqtt.js wrapper is 
```js
import {LogManager} from 'aurelia-framework';
const Console = LogManager.getLogger('Approach');
const ThenDebug = (r) => { Console.debug(r); return r; }
Console.setLevel('error');

// ajoslin, dec 2016
// this class bottlenecks the mqtt access for this webapp
// we also keep a list of subscribers and the regEx's used to recognize them
//	so that we can distribute messages that come in only to those that want them

import mqtt from 'mqtt';

import {singleton} from 'aurelia-framework';

@singleton()
export class MQTTClient {

	singleLevelWildcard = '+';
	multipleLevelWildcard = '#';

	subscriptions = [];

	constructor() {
		this.mqttBroker = 'ws://127.0.0.1:8000';
		this.mqttClient = mqtt.connect(this.mqttBroker);
		this.mqttClient.on('connect', this.onConnected());
	}

	publish(topic, message, options, pcb) {
		this.mqttClient.publish(topic, message, options, pcb);
	}

	subscribe(topic, options, mcb, scb) {
		this.mqttClient.subscribe(topic, this.onSubscribed(mcb, scb));
	}

	unsubscribe(topic, ucb) {
		this.mqttClient.unsubscribe(topic, this.onUnsubscribed(ucb));
	}


	requestReply(topicRequest, topicReply, payload) {
		const rr_qos = 0;
		return new Promise((resolve, reject) => {
			this.subscribe(topicReply,{ qos: rr_qos }, (payload) => {
				this.unsubscribe(topicReply, (err) => {
					if (err) {
						reject({ msg: 'unsubscribe error, '+err, payload: payload });
					}
				});
				resolve(payload);
			}, (err) => {
				if (err) {
					reject({ msg: 'subscribe error, '+err, payload: payload });
				}
			});
			this.publish(topicRequest, payload, { qos: rr_qos });
		});
	}


	onUnsubscribed(cb) {
		const that = this;
		return function (error) {
			if (typeof cb == 'function') { cb(error); }
		}
	}

	onSubscribed(mcb, scb) {
		const that = this;
		return function (error, granted) {
			granted.forEach((sub)=>{
				let subRegStr = sub.topic.replace(that.singleLevelWildcard,'[^/]*').replace(that.multipleLevelWildcard,'.*');
				that.subscriptions.push({ regEx: new RegExp(subRegStr), cb: mcb });
			});
			scb();
		}
	}

	onConnected() {
		const that = this;
		let mqttClient = this.mqttClient;
		let onMessageCB = this.onMessage();
		return function(packet) {
			mqttClient.on('message', onMessageCB);
		}
	}

	onMessage() {
		const that = this;
		return function (topic, payloadBuff) {
			that.subscriptions.forEach((sub)=>{
				if (sub.regEx.test(topic)) {
					sub.cb(payloadBuff);
				}
			});
		}
	}
}
```

**Comment by mcollina** [comment]
There should be no slowdowns on Node. Can you please check and verify?

I feel this MQTT.fx delivering receiving data over websocket or over TCP/TLS?

What is this CGI script you are mentioning?

**Comment by ajoslin103** [comment]
There is only one 'remote' script, with two wrappers -- one for MQTT and the other for CGI 

The MQTT.fx is connecting via TCP - it doesn't have an option for websockets

If you can describe how I might help to debug this issue I would be very glad to do so !!

**Comment by mcollina** [comment]
Can you try connecting with the MQTT.js client above to port 1883 without websockets from Node.js? I fear it might be websockets.

**Comment by ajoslin103** [comment]
ok, it's instant when via mqtt://localhost

where should I go next ?

**Comment by mcollina** [comment]
I fear it's the websocket layer in Mosquitto or in this library, or a combination of the two. Are you using websockets from a Browser or Node?

Please try using https://eclipse.org/paho/clients/js/. It has a different way of dealing with Websockets, and we might be able to track down what is the problem.

The problem is sending the payload or receiving the payload?

**Comment by ajoslin103** [comment]
the slowdown is only for receiving the payload, sending the payload is fast as it should be -- I increased the payload size which has no effect on the overall speed, and I can see the publisher receive the request right away.

I tried with the HiveMQ javascript client, and it was slow to receive as well (sending was ok, based on timings)

the paho client has the same results -- fast transmit of the request, slow receipt of the results.

**Comment by mcollina** [comment]
have you tried any other broker?

**Comment by ajoslin103** [comment]
good idea!  I'll try on the target environments (FC20 & C7) and I'll look for other clients for the mac.

will advise (in 14hrs or so, I can't work on this tonight)

thanks!

-- can you confirm slowdown on receiving (vs sending) messages with the browser?

**Comment by ajoslin103** [comment]
I could not get the eval copy of the MQHive broker to connect to the MQTT.fx or to the websocket, but I can't use a paid product anyway

The EMQ broker connected (using a Docker image) to the MQTT.fx and the Paho client, but not to the mqtt-client that underlies your library.

The results were good!  the request and response are very fast!

So that points to the mosquitto broker as the slowdown, at least on the mac...

I'll get some brokers running on the target platforms today & report back here

**Comment by ajoslin103** [comment]
mosquitto & emq on centos -- fast for request & receive
mosquitto on FC20(32bit)  -- fast for request & receive

ok! so it seems definite !  the mosquitto broker on mac! 

thanks for your excellent work on your library & helping me to find out the problem !!

**Comment by ajoslin103** [comment]
furthermore, the slowdown is only when the browser & broker & publisher are on the same mac 

when the broker is on another mac, the slowdown disappears

**Comment by ajoslin103** [comment]
OH ^$%#@&* !!!

After testing _all_ over the place on multiple different OS's and combinations...

Upgrading my local broker to the latest version solved the problem...

Sigh...
