### ISSUE TITLE
4-Byte CONNACK message is divided into 2 packages to deliver

### ISSUE THREAD

**Issue by houluy** [mqttjs/MQTT.js#514]
I'm using MQTT.js to server as an MQTT server, but my client receives two packages of CONNACK message. In MQTT protocol, CONNACK message is only 4-Byte long. I don't know what's wrong with my MQTT server. It will consume massive of throughput if 4 Bytes are seperated into two TCP packages.
Any help for this? Thanks!
![image](https://cloud.githubusercontent.com/assets/11565649/20995114/bc3d4a96-bd2f-11e6-94b3-01b70f2f6969.png)

**Comment by mcollina** [comment]
Is this websocket or plain TCP?
Probably we should wrap the connect packet into a cork/uncork.

**Comment by houluy** [comment]
We've found the problem. We use connack() in mqtt-packet to respond the MQTT connecting client. The source code is shown below:
![a](https://cloud.githubusercontent.com/assets/11565649/21006995/3594e3fe-bd76-11e6-91c1-78f377ce8d19.jpg)

The two statements "stream.write" has an interval to run, which causes the first byte '0x20' is seperated into different TCP packages from other bytes. This can be fixed by encapsulating a whole CONNACK package and 'stream.write' it once for all. 

Do I have a correct understand about this?

**Comment by mcollina** [comment]
Yes.


In order to do that you should wrap the write in a cork() and uncork() pair. Schedule the uncork() using nextTick for max perf.

**Comment by houluy** [comment]
Thanks a lot for your help!

by the way, I've studied your paper 'Introducing the QEST broker' and gained a lot of new ideas and insights about IoT, MQTT and redis, sir. :)
