### ISSUE TITLE
Unable to connect to hivemq broker on amazonaws server using client MQTT.js

### ISSUE THREAD

**Issue by prateekthakurgithub** [mqttjs/MQTT.js#516]
Hi,

I am trying to connect hivemq broker using mqtt.js but unable to do that.
```js
var PORT=8883;
var HOST = 'ec2-xx-xxx-xx-xxx.ap-south-1.compute.amazonaws.com';
var fs = require('fs');
var dirPath = "/home/shiksha/meteor/HomenCloudN/private/";
var KEY = fs.readFileSync(dirPath+'mqtt-client-key-2.pem');
var CERT = fs.readFileSync(dirPath+ 'mqtt-client-cert-2.pem');
var TRUSTED_CA_LIST = [fs.readFileSync(dirPath+'hivemq-server-cert.pem')];
var options = {
         host:HOST,
         port:PORT,
         protocol:'mqtts',
         protocolId:'MQlsdp',
         ca: TRUSTED_CA_LIST,
         key: KEY,
         cert: CERT,
         secureProtocol: 'TLSv1_method',
         protocolVersion:3,
         passphrase: '*****',
         username: "*****",
         password: "******",
         rejectUnauthorized : false,
         //keepalive: 1000,
         //   checkServerIdentity: function (host, cert) {
        //     return undefined;
        //  },
         qos: 1
       };
```

It does not even throws back any error.  It just keeps trying to reconnect.
I am able to connect on port `1883` without TLS.
Generated the self signed certificates using the following link : [http://www.hivemq.com/docs/hivemq/latest/](http://www.hivemq.com/docs/hivemq/latest/)

I am able to connect publish and subscribe using mosquitto client.

**Comment by mcollina** [comment]
I don't know what is the problem. Probably a debug session would show the underlining error, as it is usually a TLS error. I'd be very happy in a PR that improves the debuggability of those situations.

**Comment by prateekthakurgithub** [comment]
Thanks for help mcollina. Here is the new configuration that worked
var options = {
         //host:HOST,
         port:PORT,
         protocol:'mqtts',
       //  protocolId:'MQlsdp',
         //clientId: 'bgtestnodejs',
         ca: TRUSTED_CA_LIST,
         key: KEY,
         cert: CERT,
         secureProtocol: 'TLSv1_method',
         protocolVersion:3,
         passphrase: 'Shiksha@123',
         username: "hivemq-Shiksha",
         password: "Shiksha123",
         
         //rejectUnauthorized : false,
         //keepalive: 1000,
          //  checkServerIdentity: function (HOST, CERT) {
            // return undefined;
          //},
         qos: 1
       };

As far my understanding is concerned the protocolId field should not be mentioned for hivemq 3.2 version. Also mosquitto was already using port 8883 which was blocking other requests to pass through. Let me know if any other improvements can be done.

**Comment by mcollina** [comment]
Seems good!
