### ISSUE TITLE
how Create client in V2

### ISSUE THREAD

**Issue by oussamaABID** [mqttjs/MQTT.js#517]
hello 
if i want create array of clients 
like this : 
`var tab= [];
var client1 = mqtt.createClient(...);
var client2 = mqtt.createClient(...);
tab.push(client1);
tab.push(client2);`

how do that in V2
`client1 = mqtt.connect(..); client2=mqtt.connect(..);`

with V2 it's static client2=>client1 ?

**Comment by mcollina** [comment]
No it's not static. It will return a new client.
