### ISSUE TITLE
Mqtt packets

### ISSUE THREAD

**Issue by shailendra12345** [mqttjs/MQTT.js#523]
Hi,

I have installed mqtt@2.2.1 using NPM. On successful server return a CONNCK packet like. 
{
 cmd: 'connack',
  retain: false,
  qos: 0,
  dup: false,
  length: 2,
  topic: null,
  payload: null,
  sessionPresent: false,
  returnCode: 0 
}

After i am publishing the messages to broker and getting PUBACK.
{ cmd: 'publish',
  topic: 'latlong',
  payload: 'my message7',
  qos: 1,
  retain: true,
  messageId: 41950 
}

So my question is why cmd is 'publish' rather than 'puback'.

thanks

**Comment by seymar** [comment]
Its the response from the broker because you use Quality of Service level 1 (which is default).
Just read the documentation on MQTT:
http://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels

**Comment by mcollina** [comment]
Thanks @seymar!
