### ISSUE TITLE
Cannot read property 'granted' of undefined

### ISSUE THREAD

**Issue by medric** [mqttjs/MQTT.js#529]
We get this error when trying to subscribe to a topic. This seems to come from ```MqttClient.prototype.subscribe``` in the mqtt js client source. Here is the stack trace we get
```
at outgoing.(anonymous function) (http://localhost:3000/assets/bundle.js:47058:28)
    at MqttClient._handleAck (http://localhost:3000/assets/bundle.js:47471:8)
    at MqttClient._handlePacket (http://localhost:3000/assets/bundle.js:46882:13)
    at process (http://localhost:3000/assets/bundle.js:46831:13)
    at Writable.writable._write (http://localhost:3000/assets/bundle.js:46841:6)
    at doWrite (http://localhost:3000/assets/bundle.js:58646:65)
    at writeOrBuffer (http://localhost:3000/assets/bundle.js:58635:6)
    at Writable.write (http://localhost:3000/assets/bundle.js:58573:12)
    at Duplexify.ondata (http://localhost:3000/assets/bundle.js:53622:21)
    at Duplexify.EventEmitter.emit (http://localhost:3000/assets/bundle.js:48188:18)
outgoing.(anonymous function) @ client.js:469
MqttClient._handleAck @ client.js:882
MqttClient._handlePacket @ client.js:293
process @ client.js:242
writable._write @ client.js:252
doWrite @ _stream_writable.js:347
writeOrBuffer @ _stream_writable.js:336
Writable.write @ _stream_writable.js:274
ondata @ _stream_readable.js:546
EventEmitter.emit @ events.js:81
readableAddChunk @ _stream_readable.js:217
Readable.push @ _stream_readable.js:176
Duplexify._forward @ index.js:163
onreadable @ index.js:127
EventEmitter.emit @ events.js:78
emitReadable_ @ _stream_readable.js:434
emitReadable @ _stream_readable.js:428
readableAddChunk @ _stream_readable.js:224
Readable.push @ _stream_readable.js:176
Transform.push @ _stream_transform.js:123
onmessage @ stream.js:119 
```
if that may help.
Here is the wrapper we use to handle subscriptions 
```
joinTopic(topic: string | string[], qos: number) {
        this.client.subscribe(topic, {qos}, (err: any, granted: any) => {
            if (!err) {
                this.addTopic(topic);
                this.dispatch({type: JOIN_TOPIC, data: {topic}});
            }
        });
    }
```
The connection to the server seems to work though. We're only dealing with subscription error here. Mosquitto version used is 3.1.1.

Does anyone know what could go wrong ? 

Thank you for your help .

**Comment by snailterror** [comment]
same problem for me

**Comment by mcollina** [comment]
Would you mind to upload a full example to reproduce the issue?

**Comment by medric** [comment]
We have been looking this error up and it appears that this is related to https://github.com/mqttjs/mqtt-packet/issues/14. The MQTT protocol level 4 handles a new QoS level : 128 (failed) which seems not to be handled by mqtt-packet 
https://github.com/mqttjs/mqtt-packet/blob/master/constants.js.

**Comment by mcollina** [comment]
@medric would you like to send a PR to solve the problem?

I think https://github.com/mqttjs/mqtt-packet/issues/14 is fixed, but maybe we need to regenerate the bundle here. Are you using the precompiled bundle?

**Comment by medric** [comment]
I think I spotted the problem. The parser works fine to me. The problem seems to come from mqtt client though. The thing here is that we receive an 'unsuback' packet. In that case the callback is called with a null parameter, making the exception occurred 
```
case 'unsuback':
      delete this.outgoing[mid]
      cb(null)
      break
```

The callback does 
```
this.outgoing[packet.messageId] = function (err, packet) {
    if (!err) {
      subs.forEach(function (sub) {
        that._subscribedTopics[sub.topic] = sub.qos
      })

      var granted = packet.granted
      for (var i = 0; i < granted.length; i += 1) {
        subs[i].qos = granted[i]
      }
    }

    callback(err, subs)
  }
```
There is no packet here, if if I am not mistaken. So should we modify the test case as we got no payload here ?

**Comment by mcollina** [comment]
@medric would you like to send a PR? That seems the callback for SUBSCRIBE and SUBACK, not UNSUBSCRIBE and UNSUBACK
