### ISSUE TITLE
Connect with series data

### ISSUE THREAD

**Issue by aignacio** [mqttjs/MQTT.js#531]
Hello all,

Firstly, great job for this package! I've implemented a client that needs first read the MAC Address to create the args (client_id, username, password...) for the options passed in .connect(#,options) method and for some reason the cb structure of MAC read is called after the mqtt.connect(.. method, generating 'undefined' options in the args of mqtt connection... =/  Does someone has a problem similar or knows a way to create a mechanism for this? @mcollina 

obs.: I already tried to use .async

**Comment by mcollina** [comment]
@aignacio can you upload an example of what you are trying to do?

**Comment by aignacio** [comment]
@mcollina sure! Above is part of my code and how I connect to MQTT server...

```
var unique = require('getmac');
var mqtt     = require('mqtt');
var md5     = require('md5');
let  mac;
let  mqtt_server = '127.0.0.1';

unique.getMac(function(err,mac_addr){
  if (err)
    throw err
  mac = mac_addr;
  // The problem is this attribution that runs after mqtt.connect...
});

mqttClient = mqtt.connect('mqtt://'+mqtt_server,{
 clientId :  mac
 ,username : 'test_'+mac
 ,password : md5(**mac**).slice(25,31)
 ,port : 3881
});
...
```

**Comment by mcollina** [comment]
@aignacio you need to call `mqtt.connect()` within the callback of `unique.getMac()`.

**Comment by aignacio** [comment]
Oh ok, I tried this but when I start the script, the event emitters 
´´´
mqttClient.on('connect', function()...
mqttClient.on('message', function(topic, message)...
´´´

just don't work, when the client connects =/

**Comment by mcollina** [comment]
@aignacio all the logic has to happen _after_ you initialize `mqttClient`. I recommend you to do some of the nodeschool workshoppers to familiarize yourself with Node.js https://nodeschool.io/.

**Comment by aignacio** [comment]
Sure, thanks. I understand to call the event emitters _after_ the init of mqttClient (calling in the cb works since the first time) but I was searching for the correct way to do this because my MQTT logic is big and all will be inside the cb or calling external functions.... =/

**Comment by mcollina** [comment]
@aignacio you should move all that logic into its own file, and call that from the callback.

**Comment by aignacio** [comment]
Thanks
