### ISSUE TITLE
changing options after client initialization

### ISSUE THREAD

**Issue by cordovapolymer** [mqttjs/MQTT.js#533]
Is it possible to change options after client initialization?
For example I'd like to change clientId on reconnect.

**Comment by yohei1126** [comment]
@mcollina probably not?

**Comment by RangerMauve** [comment]
It'd be easier to just create a new client instance, tbh.
However you could hack around that by modifying [client.options](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L70) at runtime, though this is unsupported so don't complain if something you hack on top of it breaks. 😛

**Comment by cordovapolymer** [comment]
@RangerMauve is it possible without modifying client.js?

**Comment by RangerMauve** [comment]
@cordovapolymer You can try to modify the `options` property directly on an instance of an mqtt client.

```javascript
var client = mqtt.connect(something);
client.options.something = "something else";
```

**Comment by cordovapolymer** [comment]
@RangerMauve , unfortunately it is not working this way.

**Comment by burritoIand** [comment]
@cordovapolymer yes this is possible with `client.options.transformWsUrl`, see https://github.com/mqttjs/MQTT.js/issues/1083

**Comment by YoDaMa** [comment]
`transformWsUrl` provides functionality for changing the URL or other options in websockets. For non-websockets, like @cordovapolymer said the solution would be to modify the `client.options` directly.
