### ISSUE TITLE
Add TypeScript definitions for the api

### ISSUE THREAD

**Issue by sublimator** [mqttjs/MQTT.js#536]
Actually, there exists a `@types/mqtt` (which happens to be inconsistent with this latest version) but of course it would be ideal to have it in this repo (which is considered the best practice I believe).

**Comment by mcollina** [comment]
Disclaimer: I am not a typescript user, and there is no one in the maintainers.
If you want to join and help, you are welcome!

In https://github.com/mqttjs/MQTT.js/pull/386 it was discussed this matter. I'm happy to embed the type definition here, if you want to help maintaining that.

cc @PekkaPLeppanen

**Comment by sublimator** [comment]
Yeah, keen! we at @flomio are going full TypeScript.

**Comment by sublimator** [comment]
k, once we got the other one sorted to your satisfaction, I'll get onto it :)

**Comment by ogis-onishi** [comment]
I am using mqtt.js with TypeScript. I can contribute if you need my help.

**Comment by sublimator** [comment]
Awesome :) There's a @types/mqtt package we can work with it's author with
:)

Just to find the time ...

**Comment by PekkaPLeppanen** [comment]
I wrote the type definitions for the MQTT API v1. I was hoping that one day I'll write another definitions for v2 API also. Because a lot of time has passed and nothing happened from my part, I must say it would be great if someone else could do the new type definitions.
I am no longer using MQTT, because I changed to another company to a completely different type of project.

Anyway, to write the type definitions, you should take the API documentation and write the definitions from there. The missing parts can be found from the source. And make PR for the documentation, if there is something missing.

Also notice that the two versions of the type definitions can co-exist, if the API v1 is still maintained actively. If it's not maintained, one should rewrite the existing file.

**Comment by sublimator** [comment]
I've been playing with async/await in TypeScript 2.1 and it's lovely. It would be nice to Promise-able the API while we're at it.

**Comment by ogis-onishi** [comment]
And DefinitelyTypes repo must be updated as well.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mqtt

**Comment by ogis-onishi** [comment]
I installed mqtt 2.5.0 by "npm install mqtt", but type definition files are not provided.

**Comment by mcollina** [comment]
this should be done now in 2.5.1

**Comment by yohei1126** [comment]
@sublimator 
I got the error "error TS2307: Cannot find module 'mqtt'." when compile.  How can I resolve the module?

**Comment by sublimator** [comment]
Can you verify that you have the typings in your node_modules/mqtt ? Are you using @mcollina's latest npm push of mqtt?  What version of typescript?

**Comment by ogis-onishi** [comment]
* I have "\node_modules\mqtt\types".
* I am using the follwoing modules.

```
    "mqtt": "^2.5.2",
    "typescript": "^2.2.2",
```

**Comment by sublimator** [comment]
Interesting, as it "works for me" here. 

`import { connect, MqttClient } from 'mqtt'`

Is all I'm using.

**Comment by ogis-onishi** [comment]
My tsconfig.json is as follows.

```
{
  "compilerOptions": {
    "lib": ["dom", "es2015.promise", "es2015.collection", "es5", "es6"],
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "types": [
        "mocha"
    ],
    "outDir": "./dist"
  },
  "exclude": [
      "node_modules"
  ],
  "include": [
     "src/**/*.ts",
     "test/**/*.ts"
  ]
}
```

The result of trace resolution is like this. The tsc compiler is trying to search the module in node_modules/@types/mqtt.d.ts. But not in node_modules/mqtt/types/index.d.ts.
Maybe this is an related to module resolution setting in tsconfig.json.

```
$ $(npm bin)/tsc -p . --traceResolution
======== Resolving module 'mqtt' from 'D:/work/xx.ts'. ========
Module resolution kind is not specified, using 'Classic'.
....
File 'D:/work/iotc_msgpub_js/node_modules/@types/mqtt.d.ts' does not exist.
...
```

**Comment by sublimator** [comment]
I'm using moduleResolution: "node"

Try that?

**Comment by sublimator** [comment]
I'm relatively new to TypeScript btw

**Comment by sublimator** [comment]
I'm using it with an angular 4 app, that was scaffolded by the angular cli,
which creates a tsconfig file with `compilerOptions.moduleResolution`, set
to `node`

**Comment by ogis-onishi** [comment]
Thanks. I fixed it with the "moduleResolution: Node" in the "compilerOptions".

```
{
  "compilerOptions": {
    "moduleResolution": "Node"
  }
}
```

**Comment by sublimator** [comment]
We should update the TypeScript section of the README I guess

**Comment by mcollina** [comment]
PR?

**Comment by sublimator** [comment]
Done. We might wanna add some CI tests that use all the `strict` tsconfig settings. I'll try and get around to that at some point.
