### ISSUE TITLE
Simple example dont work with EMQTT broker

### ISSUE THREAD

**Issue by StarpTech** [mqttjs/MQTT.js#540]
#### Environment

- OS: Windows
- Erlang/OTP: R18/7.3
- EMQ: 2.0.7

#### Description

```js
const mqtt = require('mqtt')
const client = mqtt.connect('mqtt://localhost:1883');

client.on('connect', function () {
    console.log('Connected')
    client.subscribe('presence')
    client.publish('presence', 'Hello mqtt')
})
client.on('message', function (topic, message) {
    // message is Buffer
    console.log(message.toString())
    client.end()
})
```

I get only the log `'Connected'` but when I publish in a seperate process I receive the message. I did anything wrong? Thanks!

In the EMQTT dashboard the messages are marked as `dropped`.

**Comment by StarpTech** [comment]
I tried it with https://github.com/mcollina/mosca
```
mosca -v | pino
```
 and it works. I leave this open. Perhaps anyone knows the reason.

**Comment by mcollina** [comment]
the main reason is that the behavior is non-deterministic. Your publish is
executed before your subscribe is acked in emqtt.
Il giorno dom 12 feb 2017 alle 20:41 Dustin <notifications@github.com> ha
scritto:

**Comment by StarpTech** [comment]
That was also my thought. You're right when I move the publish in the callback of the subscription it works and to avoid this beginner problem I would recommend to update the examples. Thank you.
