### ISSUE TITLE
Unable to resolve module events from ....

### ISSUE THREAD

**Issue by gyurobenjamin** [mqttjs/MQTT.js#541]
I got this error with react-native. Any idea?

<img width="376" alt="screen shot 2017-02-12 at 15 03 26" src="https://cloud.githubusercontent.com/assets/3200573/22863263/a6a69668-f134-11e6-812e-e531d464f36e.png">

**Comment by cagodoy** [comment]
+1

**Comment by cagodoy** [comment]
see #442 and #443

**Comment by gyurobenjamin** [comment]
I've tried to install all missing modules manually like event, path, url. But unfortunately the fs module is not working on react-native.

**Comment by mcollina** [comment]
@gyurobenjamin you need to bundle it, and treat it like it is a web browser. React Native is not Node.

Would someone take some time to prepare a guide for React Native to be contributed to this repo? I think it would help everybody.

**Comment by gyurobenjamin** [comment]
@mcollina That would be awesome! Thanks!

**Comment by xiongxiong** [comment]
+1

**Comment by zmGitHub** [comment]
anybody solved?

**Comment by zmGitHub** [comment]
anybody?

**Comment by nickzarate** [comment]
+1

**Comment by gyurobenjamin** [comment]
Go to the module library:
- npm install
- webpack mqtt.js ./browserMqtt.js --output-library mqtt
And than you can import the browserMqtt.js from your React.

**Comment by taoqf** [comment]
https://www.npmjs.com/package/@taoqf/react-native-mqtt
