### ISSUE TITLE
Retain messages are duplicated on connection

### ISSUE THREAD

**Issue by jeromevalentin** [mqttjs/MQTT.js#545]
In case of subscriptions to topics: A and +, if a message has been published previously into the broker under the 'A' topic, when connecting we receive two times the retained message (one per subscription)

When publishing a new message with retain: true/false, we receive only one notification for both subscriptions.

Consider the script below
```es6
import mqtt from 'mqtt'

let pub = process.argv[2] !== undefined
let retain = process.argv[2] === 'true' || false

console.log('RETAIN', retain)

let client = mqtt.connect('tcp://127.0.0.1:1883', {
  keepalive: 10,
  reschedulePings: true,
  protocolId: 'MQTT',
  protocolVersion: 4,
  clean: true,
  reconnectPeriod: 1000,
  connectTimeout: 30000,
  resubscribeOnReconnect: true
})
client.on('message', (topic, message, packet) => {
  console.log('message received on topic', topic, 'RETAIN:', packet.retain)
})

client.subscribe('+')
client.subscribe('A')

if (pub) client.publish('A', 'foo', { qos: 2, retain: retain })

setTimeout(() => {
  console.log('DONE')
  client.end()
}, 2000)
```
Using it with 'false' parameter produces:
```
jvalentin@jvalentin:~/mqtt$ node test/mqtt false
RETAIN false
message received on topic A RETAIN: false
DONE
```
Using it with 'true' parameter produces:
```
jvalentin@jvalentin:~/mqtt$ node test/mqtt true
RETAIN true
message received on topic A RETAIN: false
DONE
```
Finally launching it without parameter (no publication):
```
jvalentin@jvalentin:~/mqtt$ node test/mqtt
RETAIN false
message received on topic A RETAIN: true
message received on topic A RETAIN: true
DONE
```
I'm using:
```
jvalentin@jvalentin:~/mqtt$ npm list | grep mqtt
├─┬ mqtt@2.4.0
│ ├─┬ mqtt-packet@5.2.1
```
and mosquitto in version 1.4.8.

I'm not sure this bug is due to MQTT.js (very cool library), or to mosquitto. But this is definately not the behavior I was expecting!

Thanks in advance for you help,
Regards
Jérôme

NOTE: even by dumping the packet, the **'dup' flag is always false**!

**Comment by mcollina** [comment]
All of that is broker based, and it's how MQTT works. There is very little we can do about it in this library.

**Comment by RangerMauve** [comment]
This might just be a problem with using qos 1, if you use it to subscribe to a topic the broker guarantees that you'll receive it "at least once". That means you can have duplicates. You should use qos 2 which has a guarantee of receiving it only once.

**Comment by jeromevalentin** [comment]
@RangerMauve The qos doesn't change anything on that problem, I've got exactly the same behavior by changing it to 2!
@mcollina Does that behavior is required in MQTT specifications? I agree considering the received information (in the packet) it is complicated to perform filtering, that's why I'm asking if it is not a mosquitto's issue. 

From my side I'm trying to track all topics on which I received a RETAIN message, and ignoring repetition... but it might be integrated in mqtt.js directly...

**Comment by mcollina** [comment]
> @mcollina Does that behavior is required in MQTT specifications?

@jeromevalentin I think so, yes.
