### ISSUE TITLE
Unable to connect to RabbitMQ broker using MQTT.js

### ISSUE THREAD

**Issue by shanmohod** [mqttjs/MQTT.js#548]
I am using MQTT.js to connect with Rabbitmq broker... Problem Statement:
1> Connect.on is not getting execute (Not emitting connect event): Any scenario when it should get execute?
2> Connection is not getting established, Am I using correct syntax for tcp host, username, password, and vhost?

```js
var mqtt = require('mqtt');

var client  = mqtt.connect("tcp://hostname.com:1883",
{username: 'username', password: 'pass', Vhost:'t@cup', protocolId: 'MQIsdp', protocolVersion: 3});

client.subscribe('messages');
client.publish('messages', 'Current time is: ' + new Date());
client.on('message', function (topic, message) {
 console.log(message);
});

client.on('connect', function () {
  console.log("Connected");
});

client.on('error', function(){
console.log("error occurred");
});
`````

**Comment by sublimator** [comment]
I can't recall a `vhost` option. But I could be wrong. You need to
subscribe to topics before you will receive any `on('message', ...` events

**Comment by shan888** [comment]
@sublimator: still no success, I am not getting any events.. I guess their is some issue with how I'm connecting (mqtt.connect)

**Comment by sublimator** [comment]
I'm not sure :) I'd try connecting from the same box, without any vhost
complications. Your tcp:// url seemed ok.

require the node 'url' module and use the parse function on the string and
look at the result to assure yourself of its well formedness.

Are you sure you want that version of mqtt? 3.1 vs the default 3.1.1?

I have no experience with the broker you are using. New to mqtt and have
been using it only with the aws IoT broker

**Comment by sublimator** [comment]
I'm assuming "hostname.com" is some kind of redaction :)

**Comment by shan888** [comment]
Yes, different hostname I'm using here :) . I also tried connecting without providing mqtt version but then had a thought that it might be an issue.
Let's wait.. someone may help

**Comment by sublimator** [comment]
Could try having some fun with wireshark haha

**Comment by shan888** [comment]
@mcollina Can you help?

**Comment by shan888** [comment]
@dmeznaric

**Comment by mcollina** [comment]
@shan888 not at the moment. A generic suggestion is to publish during the subscribe callback.

**Comment by xiongyihui** [comment]
I have similar issue, but I use mqtt over websocket with rabbitmq.
To use mqtt.js with rabbitmq-web-mqtt, we have to specify `path` to `/ws` in the options.

```
var mqtt = require('mqtt');
var options = {
    path: '/ws',
    username: 'user',
    password: 'password'
    }

var client  = mqtt.connect("ws://{hostname}:15675", options);
```

putting `/ws` in the URL will not work!
```
var mqtt = require('mqtt');
var options = {
    username: 'user',
    password: 'password'
    }

var client  = mqtt.connect("ws://{hostname}:15675/ws", options);    // not work!
```

**Comment by TamimiGitHub** [comment]
Relates to #753

**Comment by alexlawrence** [comment]
@xiongyihui thanks for providing the solution! This saved me from spending countless hours investigating. I think it would be worth to have this documented somewhere.
