### ISSUE TITLE
resubscribe on reconnect fails when disconnect happens before suback

### ISSUE THREAD

**Issue by gerad** [mqttjs/MQTT.js#555]
I can submit a fix for this, but I want to be sure it's a legitimate issue before creating a pr.

1. **client** issues a subscribe to `topic1`
2. **server** issues a suback for `topic1`
3. **client** gets suback for `topic1`
4. **client** issues a subscribe to `topic2`
5. **server/client** connection is severed
6. **client** reconnects

**result**: client resubscribes to `topic1` but not `topic2`
**expected**: client resubscribes to `topic1` and `topic2`

This is because the topic is only added to the subscribed topic list after the suback: https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L465-L467

**Comment by mcollina** [comment]
fantastic, yes, go ahead with a PR.

**Comment by gerad** [comment]
@mcollina #556
