### ISSUE TITLE
Update readable-stream in order to support react-native

### ISSUE THREAD

**Issue by RangerMauve** [mqttjs/MQTT.js#557]
Currently I'm unable to use mqtt.js out of the box with react-native as it requires an updated version of readable-stream. (namely 2.2.3)

Are there any pitfalls to watch out for the upgrade? Would a PR be welcome for this?

**Comment by mcollina** [comment]
This depends on the latest one. Are you using the pre-made build during on-publish?
IMHO I should npm update and republish bumping the minor if that's the case.

**Comment by RangerMauve** [comment]
Oh jeeze. It appears I had an outdated version of MQTT.js installed. What an obvious mistake on my part. 😭 

I'll update it and close this once I see it working

**Comment by RangerMauve** [comment]
I somehow messed up my project entirely while updating, but this should be fine.
