### ISSUE TITLE
TypeScript implementation?

### ISSUE THREAD

**Issue by sublimator** [mqttjs/MQTT.js#559]
What are peoples thoughts/feelings about converting the lib/ implementation to TypeScript? (I did exactly this while in the process of creating headers/declarations for #547 The results are here: https://github.com/sublimator/MQTT.js/tree/typescript)

I'm not super invested, though it occurs to me it may be easier to maintain one TypeScript codebase rather than JS + TypeScript headers. I figured I'd bring it up now before the branch gets too stale. 

@mcollina ? 
@adamvr ? 
@radekg ?

**Comment by mcollina** [comment]
I'm definitely -1 on the idea. I'm ok in supporting TypeScript, not in using it directly.

**Comment by dkfiresky** [comment]
It's easier to support Javascript only, because TypeScript is just a superset of it.

**Comment by sublimator** [comment]
Ok, was just floating the idea :) Feel free to close the issue. I'm on
mobile or I'd do it myself.
