### ISSUE TITLE
QoS with multiple subscribers

### ISSUE THREAD

**Issue by woutrbe** [mqttjs/MQTT.js#560]
I'm only asking here because the documentation regarding the quality of service seems to be fairly poor.

As far as I understand, when I set `qos` to 2, I should only receive a packet once, ever.

However, in the following code, I'm able to receive the same packet twice
```
// Worker 1
_mqtt_client.subscribe('foo', { qos: 2 });
_mqtt_client.handleMessage = function(packet, success_cb, failure_cb) {
    setTimeout(function() {
        success_cb();
    }, 500);
})

// Worker 2
_mqtt_client.subscribe('foo', { qos: 2 });
_mqtt_client.handleMessage = function(packet, success_cb, failure_cb) {
    setTimeout(function() {
        success_cb();
    }, 500);
})

// Worker 3
_mqtt_client.publish('foo', 'test packet');
```

Do I need to acknowledge that a message has been receive? If so, how do I do this in the above scenario?

There's also some documentation regarding the qos on the `publish` method, but as soon as I change it there, I'm unable to receive any message in my subscribers.

Am I missing something obvious here, according to the documentation, this should be working.

**Comment by jdiamond** [comment]
Are those workers running in the same process--sharing the same `_mqtt_client` instance--or in separate processes?

**Comment by woutrbe** [comment]
@jdiamond They're running in different processes, so they have their own MQTT instance, I can also see them in the rabbitmq interface, they both have their own queue.

**Comment by jdiamond** [comment]
This sounds normal to me. All clients subscribed to a topic receive a copy of messages published to that topic. The broker really has no idea which clients are related and form some sort of worker pool and that only one should get a copy.

The QoS is a separate agreement between each individual client and the broker. Setting it to 2 tells the broker not to send any duplicates to that client. Other clients will still receive their own copies and will have their own QoS levels set.

FYI: The MQTT plugin for RabbitMQ doesn't even support QoS level 2 so you would need to be prepared to handle duplicates even if you only had one worker.

If you only want one worker to receive each message, MQTT is the wrong protocol. Use AMQP and consume from a queue.

**Comment by woutrbe** [comment]
That's fair enough and makes total sense. Just as feedback, I think the documentation on that could be improved a little bit, to me it was fairly confusing.

Since I can't switch to AMQP (MQTT is fairly deep implemented, this is just a small part of it)

I guess in my case I'll need to implemented duplicates myself somehow. Not sure how I can do that with different processes, but that shouldn't be part of this issue.

**Comment by jdiamond** [comment]
IMO, the easiest way is to make the publisher put a unique ID in the message and then use that as a unique key in your database.

**Comment by woutrbe** [comment]
Actually every message has a unique id already, but if those subscribers receive it at the same time (or within a few seconds), there's no way of knowing if it's already been processed or not.

So one of my solutions was to use a persistent store to check if it's been processed recently.

**Comment by jdiamond** [comment]
I think multiple subscribers receiving the same message within a few seconds will be very common (like all the time). MQTT is not designed to prevent that.

Could you use AMQP for just this part? The rest of your system can continue to use MQTT where it makes sense. That's how I do it at work.

**Comment by woutrbe** [comment]
Normally it shouldn't be a problem to switch this part to AMQP. I'll just have to have two clients open at the same time, but that's not an issue.

Let me try that first actually, I don't really want to introduce another store.

I'll close this issue for now, since it's not an issue with the library.

**Comment by woutrbe** [comment]
Just to update, I did switch that functionality to AMQP and it works great with no duplicates anymore.

**Comment by patrykwegrzyn** [comment]
Sorry for necro bumping but someone may find this useful.
EMQ Broker has [Shared Subscription](https://emqttd-docs.readthedocs.io/en/latest/advanced.html#shared-subscription) Feature.

Can be achchived as simple as subscribing to `"$queue/topic/#`

### Sample 

```javascript
const mqtt = require("mqtt");
const dotenv = require("dotenv");
const config = dotenv.config();

//return
if (config.error) {
  throw config.error;
}

const client1 = mqtt.connect(process.env.MQTT_BROKER);
const client2 = mqtt.connect(process.env.MQTT_BROKER);

client1.on("connect", () => {
  client1.subscribe(["$queue/device/#"], err => {
    client1.on("message", (topic, message) => {
      message = JSON.stringify(JSON.parse(message.toString()), null, 2);
      console.log("client1", topic, message);
    });
  });
});

client2.on("connect", () => {
  client2.subscribe(["$queue/device/#"], err => {
    client2.on("message", (topic, message) => {
      message = JSON.stringify(JSON.parse(message.toString()), null, 2);
      console.log("client2", topic, message);
    });
  });
});


```

### Results

```json
client1 device/qdsa {
  "type": "temperature",
  "value": 2.03,
  "timestamp": 1547992155,
  "battery": "88",
  "messageId": 16
}
client1 device/P1sK {
  "type": "current",
  "value": 8.72,
  "timestamp": 1547992155,
  "battery": "45",
  "messageId": 17
}
client1 device/46C5 {
  "type": "open",
  "value": 0,
  "timestamp": 1547992155,
  "battery": "66",
  "messageId": 18
}
client2 device/qdsa {
  "type": "temperature",
  "value": 1.39,
  "timestamp": 1547992156,
  "battery": "88",
  "messageId": 19
}
client2 device/P1sK {
  "type": "current",
  "value": 14.42,
  "timestamp": 1547992156,
  "battery": "45",
  "messageId": 20
}
client2 device/46C5 {
  "type": "open",
  "value": 0,
  "timestamp": 1547992156,
  "battery": "66",
  "messageId": 21
}
```
