### ISSUE TITLE
Change reconnect logic to exponential backoff with random delay

### ISSUE THREAD

**Issue by sclausen** [mqttjs/MQTT.js#561]
If a client loses the connection, the reconnect starts immediately. If your broker died and you restart it, all clients try to connect at the same time and may cause problems with traffic, or authorization logic and maybe kill it again. So in my opinion the reconnect should be changed to an exponential backoff with jitter, explained in [this article](https://www.awsarchitectureblog.com/2015/03/backoff.html).

What do you think about this idea?

**Comment by mcollina** [comment]
Would you mind to send a PR?
I think we should also cap the max timeout.

**Comment by sclausen** [comment]
Okay, I'll dig into the code and prepare something.

**Comment by leesenlen** [comment]
Has been finished?  It's a good job @sclausen

**Comment by sclausen** [comment]
Yes, that's what I've got so far. Any thoughts about the code?

**Comment by leesenlen** [comment]
I thought mcollina is right; You shoud define a strategy with object;
With this object, you can define retry_strategy with params such as  `delay_time`, `max_attempts`, `delay_random_range` etc...

It's would be a  strategy which support `random delay` or the other `custom-supported-strategy`;

And also you can define actions of the object(like mcollina said); 
It would be helpful to control the reconnection process;

Err.. btw, it would be a lot of works

**Comment by shivamydv** [comment]
Has this issue been resolved yet?
