### ISSUE TITLE
For browser,maximum socket buffer size before throttling

### ISSUE THREAD

**Issue by uvshah** [mqttjs/MQTT.js#568]
Hello,

I am using browserify MQTT.js for websocket. 
From single socket client, I am sending 1K messages(32KB size) at a time. 
After few messages, my client gets disconnected.
Now I tried with increasing browser buffer size from
var bufferSize = options.browserBufferSize || 1024 * 512  // 512KB    To
var bufferSize = options.browserBufferSize || 1024 * 1024 * 1024   //1 GB

In that case it works fine.
1) What should be maximum browser socket buffer size?
2) Is it right way to resolve my issue?

Regards,
Urmik

**Comment by mcollina** [comment]
I think sending 1k messages and process them as a single unit is not what MQTT is built for.
Where are you setting this `browserBufferSize` option?

**Comment by Urmik** [comment]
Thanks for reply.
I am just trying to do loadtesting from MQTT.js browserify client to Mosca server.
I am setting "browserBufferSize" option in client side browserify MQTT.JS. (function Name - WebSocketStream);

**Comment by mcollina** [comment]
why is it disconnected? Either the browser or the broker are emitting some logs?

**Comment by cordovapolymer** [comment]
@Urmik, I tryed heavy loading mqtt.js with mosca and it works fine. Can you publish your code or test it with this https://github.com/mcollina/aedes/files/793556/Archive.zip
