### ISSUE TITLE
TypeScript Client.end declaration wrong

### ISSUE THREAD

**Issue by sublimator** [mqttjs/MQTT.js#571]

**Comment by yohei1126** [comment]
The callback for end should be function.
https://github.com/mqttjs/MQTT.js/blob/v2.5.1/types/lib/client.d.ts#L151

```
  public end (force?: boolean, cb?: boolean): this
```

**Comment by ogis-onishi** [comment]
Is this fixed by #585?

**Comment by sublimator** [comment]
I believe so

**Comment by yohei1126** [comment]
I think the callback for the end function should be explicitly defined as follows. It is much easier for library users to understand.

```
export declare type CloseCallback = () => any
public end (force?: boolean, cb?: CloseCallback): this
```

**Comment by yohei1126** [comment]
I sent pull request for this. #587

**Comment by sublimator** [comment]
Probably void is more appropriate than any as a return type ?

**Comment by ogis-onishi** [comment]
It is already void.

**Comment by sublimator** [comment]
Soz, thought I saw it as 'any' ... never mind :)
