### ISSUE TITLE
QOS2 message sent on every reconnect with mosca

### ISSUE THREAD

**Issue by cordovapolymer** [mqttjs/MQTT.js#572]
When a message is sent as QOS2 in offline and a broker does not support QOS2 it gets delivered every reconnection again and again. Lowering mqtt.js connection to qos1 fixes issue.
The may be that a message is stored in outgoing store but once there's no connection it's QOS is not changed to broker provided level.

You can easily reproduce this by trying this on any example. 
I'm using latest MQTT.js and mosca.
The issue doesn't occur with aedes because it supports QOS2.

**Comment by mcollina** [comment]
@cordovapolymer there is not much we can't do here. You should use QoS 2 only if you know your broker supports it, as there is no way in the MQTT protocol to know.

Maybe we should discuss removing a failed "message" from the delivery queue if it fails more than X times.

**Comment by cordovapolymer** [comment]
Well, I have based on your [comment here](https://github.com/mcollina/mosca/issues/611) in my decision to keep a client running in QOS2. Thanks for pointing that there's no way for client to know about broker supported QOS level, I have digged into the protocol specs and found that the QOS downgrade only happens for subscribers not for publishers.

Removing a failed message will violate the MQTT protocol, it should just be clearly stated for Mosca and perhaps MQTT.js users as well, that they must avoid connecting with QOS2 to Mosca broker.

**Comment by mcollina** [comment]
You can achieve most of what QoS 2 provides with QoS 1. QoS 2 is really expensive for the client and the broker.

I'm closing this, feel free to reopen.

**Comment by cordovapolymer** [comment]
@mcollina I agree about QOS1.

It took me almost an hour to find why the message arrives twice in mentioned conditions, I think it would be good for other users to know about this from the manual.

**Comment by mcollina** [comment]
Feel free to send a PR to the docs!
