### ISSUE TITLE
Type inconsistency on packet between JS and TypeScript

### ISSUE THREAD

**Issue by ogis-onishi** [mqttjs/MQTT.js#574]
Event 'message' on connect function is defined as follows. Type of packet.messageId  is number. 
```
function (topic, message, packet) {}
```

But it is defined as string in the type definition file for TypeScript

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mqtt/index.d.ts#L14

```
    interface Packet {
        messageId: string;
        [key: string]: any;
    }
```

Should we correct the type definition file?

**Comment by ogis-onishi** [comment]
@PekkaPLeppanen Please check this issue.

**Comment by PekkaPLeppanen** [comment]
> Should we correct the type definition file?

I checked the docs and yes, you are correct: string => number.

Can you please make the PR?

**Comment by yohei1126** [comment]
Sent pq.

**Comment by sublimator** [comment]
See also: #575

**Comment by ogis-onishi** [comment]
merged
