### ISSUE TITLE
websocket efficiency

### ISSUE THREAD

**Issue by micbuh** [mqttjs/MQTT.js#576]
Hi,

sorry for posting here. Most likely I just don't get it, yet.
I would like to subscribe to several MQTT topics from the browser (web socket).
Initially I tried the Paho lib against Mosquitto, but wasn't satisfied with the performance.
Therefore, I gave MQTT.js a try. Performance wise the same issue. I also tried another broker, but no change.
Looking at packet level, I can see, that there is one packet per topic, where a normal MQTT TCP connection delivers several topics in a single packet.

Is this an websocket limitation? Or the implementation of client or broker?
Can this be improved?

Thanks, Michael

**Comment by mcollina** [comment]
@micbuh it can be improved. Specifically, we need to implement `_writev` in https://github.com/maxogden/websocket-stream. Or maybe add support for uws.

Which broker did you try? Have a look at https://github.com/mcollina/aedes.

**Comment by micbuh** [comment]
@mcollina , thanks for your quick response. I would be glad to see this issue tagged as feature request.

So far I am runningMosquitto. I had a quick look at aedes. Looks quite promising and I will definitely give it a try. Although, authorization is mandatory for my current project.

**Comment by mcollina** [comment]
@micbuh Aedes API allows you to embed custom authorization logic: https://github.com/mcollina/aedes#api.

**Comment by lpinca** [comment]
Sorry for jumping in the discussion but you can greatly improve performance by disabling permessage-deflate. It basically kills `ws` performance and uses a huge amount of memory.

If I'm not wrong you can forward configuration options to `websocket-stream` and then in turn to `ws`.

**Comment by lpinca** [comment]
@micbuh using https://github.com/websockets/bufferutil also helps a lot.

**Comment by mcollina** [comment]
this should improve once it's merged and MQTT.js updated: https://github.com/maxogden/websocket-stream/pull/112.

**Comment by micbuh** [comment]
@mcollina , I saw that `_writev` was implemented, meanwhile. Thanks a lot for that! I browserified a fresh copy MQTT.js and gave it another try (against mosquitto). Unfortunately, I couldn't see any performance increase. Somewhere in the code I saw, that `objectMode` should be turned off. So, I tried that as well. 

Basically, I am currently not sure, what to expect and if all necessary chances are done. I would appreciate some explaining words.

**Comment by lpinca** [comment]
@micbuh did you try disabling permessage-deflate?

```js
const options = {
  wsOptions: { perMessageDeflate: false },
  ...
}
```

**Comment by ranma42** [comment]
@mcollina in my environment the `_writev` change reduced the fragments quite a lot (before I was seeing one fragment per packet field), but the packets are apparently still sent as 2 fragments, one for the first byte and the other one for the remaining data.
I believe this might be caused by a bad interaction with `duplexify`, which does not know about `_writev` and upon uncorking does a `_write`.

**Comment by mcollina** [comment]
I will have little time to dedicate to this in the coming month, but I will try to have a look. What did you use to debug this situation? I'd need to replicate.

**Comment by ranma42** [comment]
I am sniffing the network traffic with Wireshark. I can provide you with a pcap dump of the session if that is useful.
