### ISSUE TITLE
Publishing to a topic with slashes does not work

### ISSUE THREAD

**Issue by vanesp** [mqttjs/MQTT.js#577]
When I publish to a simple topic ('el'), it works. 

`client.publish('el', rf);`

When I publish to a topic with sub-topics, nothing gets published.

`client.publish('el/rf', rf);`

I am monitoring what is happening with

`mosquitto_sub -d -t el`

Also, when I try with command line tools, 

`mqtt pub -t 'el/ff' -h 'rpiv2.local' -m 'from MQTT.js'`

the message does not appear in mosquitto_sub.

**Comment by RangerMauve** [comment]
@vanesp In your `mosquitto_sub` command, you're only subscribing on the `el` topic, if you have slashes after `el` then it won't be matched by that pattern. If you want all topics starting with `el`, subscribe on `el/#`

i.e. `mosquitto_sub -d -t el/#`

**Comment by RangerMauve** [comment]
Alternately you may want to subscribe on `#` so you can see _all_ events

**Comment by vanesp** [comment]
Thanks @RangerMauve... my mistake...

It's all working correctly now. Sorry for wasting your time.

**Comment by RangerMauve** [comment]
No worries! Happens to everyone. :P
