### ISSUE TITLE
QUESTION: Identify the client that published a message

### ISSUE THREAD

**Issue by aogriffiths** [mqttjs/MQTT.js#578]
Hi 

This is probably a general mqqt question but I'm using mqtt.js and want to be able to log which clients are publishing a message. For example, client A subscripes to a topic and client B and C publich to that topic. Can my code in client As tell whether client B or C published it? 

Specifically, with the code below in client A, can I tell if it was client B or C which published the message...

`client.on('message', function (topic, message, packet) {
// ...HERE?
}`

Thanks
Adam

**Comment by mcollina** [comment]
no it can't. You can add that information into the topic or the payload.
