### ISSUE TITLE
Webpack 2 - Bundling Error

### ISSUE THREAD

**Issue by maecky** [mqttjs/MQTT.js#583]
How can I include mqtt in my webpack2 config for bundling?

I tried the following to get it to compile:

```
/**
 * Base webpack config used across other specific configs
 */

import path from 'path';
import webpack from 'webpack';
import { dependencies as externals } from './app/package.json';

export default {
  module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          cacheDirectory: true
        }
      }
    }]
  },

  output: {
    path: path.join(__dirname, 'app'),
    filename: 'bundle.js',
    // https://github.com/webpack/webpack/issues/1114
    libraryTarget: 'commonjs2',

  },

  /**
   * Determine the array of extensions that should be used to resolve modules.
   */
  resolve: {
    extensions: ['.js', '.jsx', '.json'],
    modules: [
      path.join(__dirname, 'app'),
      'node_modules',
    ],
  },

  plugins: [
    new webpack.NamedModulesPlugin(),
  ],

  externals: [Object.keys(externals || {}),
    'mqtt'
  ]
};

```

But I am getting the following error:

```
Uncaught Error: Cannot find module 'mqtt'
    at Module._resolveFilename (module.js:470)
    at Function.Module._resolveFilename (D:\Projects\ReactJS\electron_new - Copy\release\win-unpacked\resources\electron.asar\common\reset-s…:35)
    at Function.Module._load (module.js:418)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at Object.0 (isEventSupported.js:17)
    at g (es6.string.from-code-point.js:4)
    at Object../app/middlewares/mqtt.js (es6.string.from-code-point.js:4)
    at g (es6.string.from-code-point.js:4)
    at Object../app/store/configureStore.production.js (es6.string.from-code-point.js:4)
```

I am trying to get this to work since days and I cannot find any ressources on the net, explaining how I can achieve this.

Any help is greatly appreciated.

**Comment by mcollina** [comment]
I do not know. I think mqtt should just load like any other module, so it should not be in the `externals`. Can you send a PR with an example of using webpack2 + react with mqtt? I think everybody would benefit by that. I will help fixing the example.

**Comment by maecky** [comment]
Thank you for your answer.

I uploaded a "working" example here: https://github.com/maecky/electron-react-redux-mqtt

If you run it with: `npm run dev` everything is working fine.
But if you build it: `npm run package-win` the described error shows up. I modified the electron app in such way, that you can see the debugger in a production build.

**Comment by datnordstrom** [comment]
This is still an issue when trying to install from https://github.com/aws/aws-iot-device-sdk-js

**Comment by OmgImAlexis** [comment]
Closing as we're now on webpack v4 so this is well out of date.
