### ISSUE TITLE
Typescript definition on DefinitelyTyped should be deleted

### ISSUE THREAD

**Issue by ogis-onishi** [mqttjs/MQTT.js#586]
The definition on DefinitelyTyped is no longer maintained, I think this shuould be deleted to avoid confusion.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mqtt
https://www.npmjs.com/package/@types/mqtt

**Comment by ogis-onishi** [comment]
@PekkaPLeppanen please let me know what do you think about this. 
Or you may want to keep it and add some explanation to use [type definition](https://github.com/mqttjs/MQTT.js/tree/master/types) on this repo.
https://www.npmjs.com/package/@types/mqtt

**Comment by PekkaPLeppanen** [comment]
It's already removed. 

See https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5b092631c92ea29f86cbc907ddb536a015921ce6

I suggest to close this issue.

**Comment by ogis-onishi** [comment]
Thanks.
