### ISSUE TITLE
mqtt version 2.5.1 throws error when compiling through webpack2. mqtt v2.4.0 is OK

### ISSUE THREAD

**Issue by luimucar** [mqttjs/MQTT.js#588]
I am using mqtt in package.json   "mqtt": "^2.4.0", recently reinstalled everything and the library updated to version 2.5.1. Then webpack started to fail compilation. Going back to mqtt 2.4.0 solves the issue. What I have to do to use 2.5.1? Here are the logs when failing:

ERROR in [at-loader] node_modules\mqtt\types\lib\client.d.ts:1:1
    Cannot find type definition file for 'node'.

ERROR in [at-loader] node_modules\mqtt\types\lib\types.d.ts:1:1
    Cannot find type definition file for 'node'.

ERROR in [at-loader] src\app\services\mqtt\mqtt.service.ts:8:10
    Module '"C:/Users/XXXXXXX/projects/XXXXX/XXXXXX/node_modules/mqtt/types/index"' has no exported member 'ClientOptions'.

**Comment by mcollina** [comment]
can you send an example project that demonstrate this failure?

cc @sublimator

**Comment by sublimator** [comment]
Hi, you seem to be missing the `@types/node`package. I believe we need to update the types index.d.ts to export more members than it currently is. I think I missed that because I was using a custom index, and importing the module via `import * as mqtt from 'mqtt/ts` so I could navigate to the source directly rather than the `.d.ts` files.  

Will fix exports with #592

**Comment by sublimator** [comment]
No, actually, it seems the index is exporting everything:
```typescript
export * from './lib/client'
export * from './lib/connect'
export * from './lib/store'
export * from './lib/types'
export * from './lib/client-options'
import { MqttClient } from './lib/client'
export { MqttClient as Client }
```

**Comment by sublimator** [comment]
The correct name for the options type is actually `IClientOptions` rather than `ClientOptions`. Be sure to `npm install @types/node --save-dev` in your project.
