### ISSUE TITLE
Max drain listeners..

### ISSUE THREAD

**Issue by gilesbradshaw** [mqttjs/MQTT.js#589]
My client does =lots of oublishes when it first starts up whuch leads to me getting the 
"Possible EventEmitter memory leak detected. 1001 drain listeners added. Use emitter.setMaxListeners() to increase limit"  error

I wonder if this is not really a problem - this could be made configurable (happy to do a PR if you think it would)

ie in lib/client.js...
````
var defaultConnectOptions = {
  keepalive: 60,
  reschedulePings: true,
  maxDrainListeners: 1001,
  protocolId: 'MQTT',
  protocolVersion: 4,
  reconnectPeriod: 1000,
  connectTimeout: 30 * 1000,
  clean: true
}

````

and later...

````
// many drain listeners are needed for qos 1 callbacks if the connection is intermittent
  this.stream.setMaxListeners(this.options.maxDrainListeners)


````

**Comment by mcollina** [comment]
Doing a lot of QoS 1 publishes in parallel it's not really a good idea. If you can stagger them, or use something like http://npm.im/fastq to only send a few.

Anyway, send the PR :).
