### ISSUE TITLE
Improve TypeScript: testing on CI, plus exports

### ISSUE THREAD

**Issue by sublimator** [mqttjs/MQTT.js#592]
* Add some compile tests using a tsconfig with all the strict settings
* Make sure we are exporting the options type etc
* Add on/once overloads for all emitted events

**Comment by sublimator** [comment]
@yohei1126  

Do you want to help me with this? Anything else need improvement? When I get a block of time I will look into it. Thanks

**Comment by sublimator** [comment]
Exports seem fine, though we could do it more explicitly rather than using wildcard exports: https://github.com/mqttjs/MQTT.js/blob/master/types/index.d.ts

**Comment by sublimator** [comment]
TODO: Add on/once overloads for all emitted events

**Comment by andy-ms** [comment]
Hi, despite #582 having been merged, the `types` folder still doesn't show up in NPM package.

**Comment by yohei1126** [comment]
@sublimator can you check it?

**Comment by OmgImAlexis** [comment]
If this is still an issue please comment and I'll reopen this.
