### ISSUE TITLE
The example doesn't work

### ISSUE THREAD

**Issue by asCii88** [mqttjs/MQTT.js#595]
```
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://test.mosquitto.org')

client.on('connect', function () {
  client.subscribe('presence')
  client.publish('presence', 'Hello mqtt')
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})
```

The example code doesn't work neither in Ubuntu 16.02, nor in Windows 10.

It just sits there and doesn't publish anything.

**Comment by sublimator** [comment]
Try another public broker.

**Comment by sublimator** [comment]
broker.mqttdashboard.com

**Comment by asCii88** [comment]
It works. Should replace the broker from the example.
Also, I had to specify { protocolId: 'MQIsdp', protocolVersion: 3} to connect to mosquitto version 1.0.4-0ppa1
