### ISSUE TITLE
MQTT version 2.6.0 Error on '.connect()'

### ISSUE THREAD

**Issue by flodonsky** [mqttjs/MQTT.js#597]
I'm building with webpack, as I have been for a while now. When I build the new version of MQTT that got pushed, what looks like last night. I now get this error:
`TypeError: this.once is not a function`

When I run the stack trace it back it stops me at: `client.connect(`

 Rolling back to `v2.5.2` It resolves my issue, but now I have a high-risk production situation and any resolution right now may break my live portal.
It's SUPER unfortunate to have breaking changes in a non-full version.... makes me force my version to stick at `2.5.2` instead of `^2.5.2`

Any information needed to understand further...? please ask questions.

**Comment by yohei1126** [comment]
The same issue as this? https://github.com/mqttjs/MQTT.js/issues/596

**Comment by yohei1126** [comment]
I have the same issue.

**Comment by flodonsky** [comment]
FIXED
