### ISSUE TITLE
return code missing on connection error (connack event)

### ISSUE THREAD

**Issue by rahulbhanushali** [mqttjs/MQTT.js#598]
The error event emitted in `_handleConnack`  method passes the error object with a message (which is mapped to the return codes for connack) as the parameter for the event listener.

Passing return codes along with the message will allow for adding custom logic based on return codes.

Reference: https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L760
`    this.emit('error', new Error('Connection refused: ' + errors[rc]))
`

We can choose to simply update the method to pass an object containing the return code and the string or pass a custom error object.

**Comment by mcollina** [comment]
I think a custom error object is ok. Or just attaching a property to it.

Would you mind assembling a PR?

**Comment by rahulbhanushali** [comment]
I have attached a property to the error object and created a PR.

**Comment by OmgImAlexis** [comment]
Closing as PR is merged.
