### ISSUE TITLE
Create a secure connection

### ISSUE THREAD

**Issue by clem91** [mqttjs/MQTT.js#601]
Hi,

I searched into the doc a way to connect to my brocker (mosquitto) without having to inform the client with any keys or certificates. I have a working secure connection with Let's encrypt certificates and what i want is making a secure connection with the client asking for server side certificates. Is it possible with mqtt.js? The doc is quite confusing with the SSL part.

**Comment by RangerMauve** [comment]
@clem91 If you're using trusted certificates on your server, all you need to do is use `mqtts` as the protocol in your connections.

e.g.

```javascript
var client = mqtt.connect("mqtts://localhost:420");
```

**Comment by clem91** [comment]
It works like a charm! 
The only problem I faced is when I precise my port 8083 ( wich is the default one) it's not working.

```
var client = mqtt.connect("mqtts://url:8083"); //doesn't work
var client = mqtt.connect("mqtts://url");   // work
```

It's not a real problem just an information for next people with same issue.

Thank you @RangerMauve

**Comment by RangerMauve** [comment]
@clem91 You might have a configuration error, because the default port for TLS in MQTT is 8883 according to [the connection code](https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/tls.js#L6)

**Comment by clem91** [comment]
You are right. My configuration was correct I was just misthinking and mixing ports. This debug afternoun liquified my brain =S.

**Comment by RangerMauve** [comment]
Cool, glad you're sorted out! Hope this library proves useful for whatever you're doing!
