### ISSUE TITLE
reconnect documentation

### ISSUE THREAD

**Issue by ozomer** [mqttjs/MQTT.js#602]
It is not clear from the documentation what the reconnectPeriod option covers and what it does not.
If the first connection attempt does not succeed, will there be a reconnection attempt?
If the first connection attempt succeeds and then fail, will there be a reconnection attempt?
What are the other events that would happen in each scenario, regarding 'error', 'close', 'offline' and 'connect' events? In what order?
Is it required to re-subscribe in each 'connect' event? 
Will a "publish" attempt during a reconnection return an error immediately or be queued? Will a "publish" attempt before the first connection succeed?
Will the "reconnect" event happen for the first connection attempt?

Please add some example scenarios. Thanks!

**Comment by mcollina** [comment]
@ozomer the best way to do write this doc is to look at the code, and fill in the documentation.
I'll be happy to review.

**Comment by ozomer** [comment]
Well, I just thought it would be nice to have a state-machine diagram by the developers themselves.

**Comment by mcollina** [comment]
@ozomer this is done by volunteers, so you (or anybody else) can be one! :)

**Comment by burritoIand** [comment]
@ozomer were you able to clarify any of the reconnection logic? It's definitely lacking and gives me some slight pause in using this, but the wss service I'm using is based on mqtt so...
