### ISSUE TITLE
Nodejs mqtt module connect problem

### ISSUE THREAD

**Issue by Irfanbsse2060** [mqttjs/MQTT.js#604]
I am using mqtt module in nodejs to connect with mosquitto broker running in my another pc locally.
Broker is running on Ip 192.168.0.4 and port 1883. 
Here is my code

var mqtt = require('mqtt')
var client  = mqtt.connect( 'mqtt://192.168.0.4:1883');

client.on('connect', function () {
    client.subscribe('presence')
    client.publish('presence', 'Hello mqtt')
})

client.on('message', function (topic, message) {
    // message is Buffer
    console.log(message.toString())
    client.end()
})
.
I am unable to connect with the broker.I think probelm is in mqtt.connect with method. am i intializing connect method correctly ?plz help me out . Thanks

**Comment by mcollina** [comment]
Is the connect event firing?

**Comment by Irfanbsse2060** [comment]
yes

**Comment by Irfanbsse2060** [comment]
![mqttconnect](https://cloud.githubusercontent.com/assets/25392177/25591784/77ab5b68-2ecf-11e7-87ae-ad3e92aa2d8a.PNG)
as you can see in pic, connected is false

**Comment by mcollina** [comment]
So, it's connecting.
You must do the publish in the subscribe callback.

**Comment by mcollina** [comment]
Also, don't call client.end(), it will close the client.

**Comment by Irfanbsse2060** [comment]
am i correctly giving the path in connect method ?

**Comment by Vignesh-Sakkarai** [comment]
@Irfanbsse2060  did u find the soln for this issue, i too facing the same problem. 
Am using tcp protocol "tcp://localhost:1883" as a broker url. 
its connected fine in backend, not the frontend? . Anyone help on this.
