### ISSUE TITLE
Still not able to connect

### ISSUE THREAD

**Issue by Irfanbsse2060** [mqttjs/MQTT.js#605]
I am using mqtt module in nodejs to connect with mosquitto broker running in my another pc locally.
Broker is running on Ip 192.168.0.4 and port 1883. 
Here is my code

var mqtt = require('mqtt')
var client  = mqtt.connect( 'mqtt://192.168.0.4:1883');

client.on('connect', function () {
    client.subscribe('presence')
    client.publish('presence', 'Hello mqtt')
})

client.on('message', function (topic, message) {
    // message is Buffer
    console.log(message.toString())
    
})

connect event doesnt fire. i am unable to connect.

**Comment by mcollina** [comment]
Can you connect from the same host that is running mosquitto? Do you or the other PC have any firewall installed? Can you see port 1883 on that ip as open? (use nmap)

the client.publish should be in the subscribe callback.

**Comment by Irfanbsse2060** [comment]
it works well in same host. bt why its not working on the computer?   i have tried on nodemcu. it works well. do  i need to forward port?

**Comment by mcollina** [comment]
What's the other computer version of Node.js, npm and operating system?

**Comment by Irfanbsse2060** [comment]
window 8  and node version v6.9.4

**Comment by mcollina** [comment]
Maybe it's an issue with Windows 8, can you try disabling all the firewall that are in place?

**Comment by Irfanbsse2060** [comment]
Thanks mcollina.
