### ISSUE TITLE
Inverted clean session behavior?

### ISSUE THREAD

**Issue by sclausen** [mqttjs/MQTT.js#608]
In your readme you state, that

> From v2.0.0, subscriptions are restored upon reconnection if `clean`: `true`

The specification states in [3.1.2.4 Clean Session](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref362965194), that
> If CleanSession is set to 0, the Server MUST resume communications with the Client based on state from the current Session. […] If CleanSession is set to 1, the Client and Server MUST discard any previous Session and start a new one

If I'm not wrong, this behavior is the opposite behavior of [MQTT-3.1.2-6] stated in [3.1.2.4 Clean Session](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref362965194).

**Comment by mcollina** [comment]
Maybe it's not clear in the README. If `clean: true`, MQTT.js will take care of resubscribing in case the connection goes down. If `clean: false`, the broker will do it for you.

**Comment by sclausen** [comment]
@mcollina The thing is, the MQTT specification statesm, that if the clean flag is present, the server AND the client MUST delete the session and therefor the subscriptions. So this behavior is against the specification.

**Comment by mcollina** [comment]
Yes. It recreate a new session, and it does new subscriptions. From an API and user perspective, it makes sense, because otherwise everybody had to redo all their subscriptions on reconnect if the network went down.

**Comment by sclausen** [comment]
Okay, I get it :+1:
