### ISSUE TITLE
If a packet is published with QOS 2 to Mosca, client does not close

### ISSUE THREAD

**Issue by btsimonh** [mqttjs/MQTT.js#611]
hi,

the attached javascript illustrates this issue.
tested with mqtt.js 2.2.1 and 2.7.1, mosca 2.3.0
If a packet is published with QOS 2 to mosca, then the client does not close correctly?
The issues seems to be that the outgoing message queue never fires 'outgoingEmpty', so finish() is never called in client.end.

Mosca does not claim QOS 2 support, and this is reported to not be an issue with another broker.

This code is an extract from the Node-Red mqtt node.
Should node-red implement a timeout strategy, calling client.end(true) if the connection does not close in a specific time, or is this a bug which should be resolved in mqtt.js?

[testmqtt.txt](https://github.com/mqttjs/MQTT.js/files/995383/testmqtt.txt)

**Comment by mcollina** [comment]
Mosca does not support QoS 2. It's clearly stated in the readme.

**Comment by btsimonh** [comment]
Although true, shouldn't mqtt.js be more graceful about it?
Or should we have a timeout mechanism around the close; at the moment, because 
client.once('close', function() {
                    done();
                });
never calls done(), it breaks NR.
Your advice is appreciated :)
If someone does end up with QOS 2 set, are other 'bad things' going on under the hood which could be a long term issue (e.g. growing outgoing queue)?

**Comment by mcollina** [comment]
I'm not exactly sure how to handle that case, and I have little time atm. Would you like to attempt a more graceful degradation if QoS 2 is not supported?

**Comment by btsimonh** [comment]
I'll see what I can do; no promises :).

**Comment by knolleary** [comment]
What does mosca do if it receives a qos2 publish?

I'd expect it to kill the connection rather than ignore it.

**Comment by mcollina** [comment]
@knolleary subscriptions are degraded, but publishes are ignored, to avoid continuous killing of connections. Maybe we should revise that, as it seems not having the desired effect.

**Comment by btsimonh** [comment]
no return msg is received, so the client just has a bunch in it's queue.  I can't see any message timeout code in mqtt, am I just missing it?  I'm not familiar enough with the MQTT std to know if a timeout on messages on a connected connection is appropriate...

**Comment by mcollina** [comment]
I think we should have a timeout here, and some way to notify the user of the situation. How long has the server to reply, before considering the message as not sent?

What are other clients doing in this specific situation?

**Comment by btsimonh** [comment]
Happy to close this;  @mcollina - thanks again for Mosca; we're still using it in production (will migrate when we have time) after 5 years with no issues (except the one I noted a day or two ago in Aedes since I could not raise an issue against the mosca archive! - and that issue - inflight packets - was caused by my own stupid system design, not by the technology :).  Hopefully my issue will inform others to avoid similar problems),
br,
Simon
