### ISSUE TITLE
Unhandled error event on connection lost with TLS

### ISSUE THREAD

**Issue by eiabea** [mqttjs/MQTT.js#614]
Hey,

i am getting an stack trace when my [mqtt broker](https://github.com/emqtt/emqttd) goes down while connected via mqtts.

This only happens, when the insecure flag is set to false

ascoltatori version: 4.1.0

Behavior:

1. Broker up and running
2. mqtt client connected
3. Broker goes down
4. clients tries to reconnect and dies with following message

```
Mon, 22 May 2017 12:45:57 GMT ascoltatori:mqtt error in the client
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 172.16.3.165:8884
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
```

If i set insecure to true the client reconnects as soon as broker is up again

**Comment by mcollina** [comment]
Have you tried just using MQTT.js? Does it causes the same error?

**Comment by eiabea** [comment]
No, because i checked the code in [mqtt_ascoltatore](https://github.com/mcollina/ascoltatori/blob/master/lib/mqtt_ascoltatore.js#L60) and found out, that ascoltatori does pass all the options directly to mqtt

**Comment by mcollina** [comment]
This is very hard to debug. Would you mind either to send a PR, or to send a PR with a failing test?

**Comment by eiabea** [comment]
it is indeed very hard to debug in an automated test. I can not really think of a good solution to start a tls enabled broker with a valid chain and domain in an unit test :(
Maybe we could do some kind of live debugging with our companies broker and a small script connecting to it and i kill the broker right after the script connects manually?
I know it is a strange solution, but i couldn't find a better approach

**Comment by mcollina** [comment]
@eiabea you can use a self-signed certificate as long as you pass the signing CA to the `ca` arguments.

**Comment by eiabea** [comment]
i will try to write a unit test for it, or at least debug it and report back

**Comment by eiabea** [comment]
I am currently trying to debug this issue and found out that it is not necessary to stop the mqtt broker, i even get the same stacktrace when i try to connect without a broker available on the domain. When i set the `rejectUnauthorized` flag to `false` the client waits for a connection.
I guess this has something to do with the TLS handshake?

**Comment by alorle** [comment]
@mcollina , any update on this issue??

**Comment by ArondeParon** [comment]
I experience the same issue and can reproduce this by simply starting a `mosquitto` server on localhost and connectingt to `mqtts://localhost`. 

The client will not automatically reconnect.

**Comment by ghormann** [comment]
I have also reproduced this issue recently using TLS 1.2.   Once the connection is established, just restart the mosquito server.  Instead of disconnecting and reconnecting the exception is thrown.

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.0.212:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at TLSSocket.handleTLSerrors (/home/ghormann/Documents/src/vote/server/node_modules/mqtt/lib/connect/tls.js:26:18)
    at TLSSocket.emit (events.js:203:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by rssk** [comment]
We're also running into this issue, I did a little digging and here's what seems to be going on.

Both `tls.js` and `tcp.js` socket connections emit an error event when they cannot connect to the broker initially, however `tcp.js` isn't listening for the event and so never does anything with it, while the `tls` connection method seems to incorrectly handle it and emits an uncaught error inside a callback that can't be handled by the end user.

@mcollina What sort of expected behavior should be expected here? Should the `mqtt.connect` function throw on a refused initial connection, exponential timeout, be silent etc?
HTH :-)

**Comment by YoDaMa** [comment]
@rssk with newly added error handling in the client layer, such connection errors like `ECONNREFUSED` will now be thrown regardless of using `tls.js` or `tcp.js`. However @solymosi 's PR to remove the thrown error handling seems ill-advised, since then if you pass in a bad cert there is no notification to the user that something bad has occurred, it is just trapped in a reconnect loop...

**Comment by solymosi** [comment]
@YoDaMa I would be fine with whatever solution that prevents an error from being thrown upon a network-related disconnect event 👍

**Comment by YoDaMa** [comment]
> @YoDaMa I would be fine with whatever solution that prevents an error from being thrown upon a network-related disconnect event 👍

we'll make a release soon so you can see what has changed, but network-related connection errors like `ECONNREFUSED` **would** be thrown now.

**Comment by rssk** [comment]
@YoDaMa As long as those thrown errors are now catchable that is all fine with me.

**Comment by xamarindevelopervietnam** [comment]
guys, generate certificate file from private key and use a self-signed certificate resolve issue for me. Bellow is 2 commands to generate key, cert and ca file:
$ openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 10000 -nodes
$ openssl req -new -key key.pem -out ca.csr
