### ISSUE TITLE
IClientSubscribeOptions's qos is defined as optional but required by code

### ISSUE THREAD

**Issue by masterclock** [mqttjs/MQTT.js#615]
https://github.com/mqttjs/MQTT.js/blob/master/types/lib/client-options.d.ts#L117
defines:
```
export interface IClientSubscribeOptions {
  /**
   * the QoS
   */
  qos?: QoS
}
```
but according to the js code, `qos` is required, otherwise, the client will not function properly.

**Comment by yohei1126** [comment]
As far as I know, qos is optional. 
https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L413

**Comment by masterclock** [comment]
```js
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://test.mosquitto.org')

client.on('connect', function () {
  console.log('connect')
  client.subscribe('presence', {}) // passing a empty options object
  client.publish('presence', 'Hello mqtt')
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})
client.on('offline', function () {
  console.log('offline')
})
```
but running the above modified example code doesn't pass as expected, mqtt keeps connect and disconnect loop

**Comment by 4rzael** [comment]
From [this line](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L439), I suppose it won't work if you give the `subscribe` function an empty object, but it will if you don't pass it an object at all.

Could you try replacing `client.subscribe('presence', {})` with `client.subscribe('presence')` and tell us if it works properly, please ? (I don't have access to a testing environment right now)

NB: If it is the case, it may be great to change the way the default qos attribution is done.

**Comment by masterclock** [comment]
calling `client.subscribe('presence')` works as expected, I've noticed [this line](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L439) too, and makes me thought that `qos` is not optional.
note: `opts` itself is optional
