### ISSUE TITLE
Subscribing to wildcard topic is not working from browser whereas it works from nodejs

### ISSUE THREAD

**Issue by vairabagni** [mqttjs/MQTT.js#622]
I have different topics like: log/gw1, log/gw2 and so on.
I want to subscribe on 'log/#' from browser.
It is not receiving any logs where as from nodejs (TCP port) it is able to receive logs.

Is it really supported ?

**Comment by mcollina** [comment]
Yes it is, so maybe it's something in the browser.

**Comment by RangerMauve** [comment]
This library passes subscriptions as is to the broker without doing any additional processing on them, it's up to the broker to support wildcards. Would you mind posting a code sample so we can debug what's wrong?

**Comment by vairabagni** [comment]
`/* eslint-disable no-console */
import { connect } from 'mqtt';

function invert(obj) {
  const keys = Object.keys(obj);
  const newObj = {};

  keys.forEach((key) => {
    newObj[obj[key]] = key;
  });

  return newObj;
}

class MQTTRedux {
  constructor(config) {
    this.config = config;
    this.topicActionMap = {};
    this.isConnected = false;
  }

  setServerUrl(url) {
    this.config.url = url;
  }

  setCredential(username, password) {
    this.config.opt.username = username;
    this.config.opt.password = password;
  }

  connect(actions, store) {
    // const actionNames = Object.keys(actions);
    // this.topicActionMap = invert(actions);
    // console.log('topicActionMap', this.topicActionMap);
    this.isConnected = true;
    this.mqtt = connect(this.config.url, this.config.opt);
    this.mqtt.on('connect', () => {
      store.dispatch({
        type: 'MQTT_CONNECT',
        message: 'Connected to MQTT broker',
      });
      console.log('[MQTT] connected');
      if(actions) {
        this.subscribe(actions);
      }
      // actionNames.forEach((action) => {
      //   this.mqtt.subscribe(actions[action], { qos: 0 });
      // });
    });

    this.mqtt.on('disconnect', () => {
      this.isConnected = false;
      store.dispatch({
        type: 'MQTT_DISCONNECT',
        message: 'Disconnected from MQTT broker',
      });
      console.log('[MQTT] disconnected');
    });

    this.mqtt.on('message', (topic, payload) => {
      if (this.topicActionMap[topic]) {
        store.dispatch({
          type: this.topicActionMap[topic],
          payload,
          topic,
        });
        //console.log('[MQTT] message received');
      }
    });

    this.mqtt.on('error', (err) => {
      store.dispatch({
        type: 'MQTT_ERROR',
        error: err,
      });
      console.log('[MQTT] error');
    });
  }

  disconnect(store) {
    this.mqtt.end(true); // Force disconnect
    this.isConnected = false;
    store.dispatch({
      type: 'MQTT_DISCONNECT',
      message: 'Disconnected from MQTT broker',
    });
    console.log('[MQTT] disconnected');
  }

  subscribe(actionMap) {
    const actionNames = Object.keys(actionMap);
    actionNames.forEach((action) => {
      this.mqtt.subscribe(actionMap[action], { qos: 0 }, function(err, granted) {
        console.log("Subscribed: ", err, granted);
      });
      this.topicActionMap[actionMap[action]] = action;
    });
  }

  unsubscribe(actions) {
    const actionMap = invert(this.topicActionMap);

    if (Array.isArray(actions)) {
      let topic;
      actions.forEach((action) => {
        topic = actionMap[action];
        this.mqtt.unsubscribe(topic);
        delete this.topicActionMap[topic];
      });
    } else {
      this.mqtt.unsubscribe(actionMap[actions]);
      delete this.topicActionMap[actionMap[actions]];
    }
  }

  createMiddleware() {
    const mqttClient = this.mqtt;
    return (store) => (next) => (action) => {
      if (action.mqtt) {
        const mqtt = action.mqtt;
        let payload;

        if (mqtt.topic && typeof mqtt.payload !== 'function') {
          payload = typeof mqtt.payload === 'string'
              ? mqtt.payload
              : JSON.stringify(mqtt.payload);
        } else if (mqtt.topic && typeof mqtt.payload === 'function') {
          payload = mqtt.payload.call(null, store.getState());
        }
        mqttClient.publish(mqtt.topic, payload, { qos: 0 });
        const modifiedAction = {
          ...action,
          mqtt: {
            payload,
            topic: mqtt.topic,
          },
        };
        return next(modifiedAction);
      }
      return next(action);
    };
  }
}

export function createClient(config) {
  return new MQTTRedux(config);
}
`

And from code I call subscribe as below:
subscribe({
'LOG_RECEIVED': 'log/#'
})

**Comment by vairabagni** [comment]
// MQTT Client Config
const mqttConfig = {
  url: 'mqtt://localhost:8008/',
  opt: {
    clientId: `litegrid-webclient-${Date.now()}`,
    username: '',
    password: '',
  },
};
const mqttRedux = createClient(mqttConfig);
mqttBroker.connect(null, this.context.store);

**Comment by RangerMauve** [comment]
The problem is here: `this.topicActionMap[actionMap[action]] = action;`

What you're doing is making `topicActionMap` look like

```javascript
{
"log/#": "LOG_RECEIVED"
}
```

When you get MQTT events coming in from the broker, you'll get `log/gw1` and `log/gw2`, neither of which equal `log/#`, so when you use `topicActionMap["log/gw1"]` you will get `undefined`.

You should use a library for matching MQTT patterns like [mqtt-pattern](https://www.npmjs.com/package/mqtt-pattern)

**Comment by vairabagni** [comment]
Thanks a lot. This really unblocked me. Thank you very much.

**Comment by RangerMauve** [comment]
Glad I could help! 😄
