### ISSUE TITLE
The error handler is not invoked when authentication fails.

### ISSUE THREAD

**Issue by arminbaljic** [mqttjs/MQTT.js#623]
Hi. I am having an issue to set up error handling when a client connection to broker fails (because of wrong username/password). It looks like "error" handler is not invoked in this case. "MQTT.js" is used in "angular" application with "mosquitto" broker and auth plugin. Client code snippet:
```js
/* Configuration */
const options: IClientOptions = {
    clientId: Mqtt2Service.clientId,
    keepalive: 10,
    reconnectPeriod: 30000,
    connectTimeout: 10000,
    username: '<some_user>',
    password: '<some_token>'
};

/* Create client */
this.client = connect('ws://localhost:9883/mqtt', options);

/* Bind handlers */
this.client.on('error', this.handleOnError);
this.client.on('connect', this.handleOnConnect);
this.client.on('close', this.handleOnClose);
this.client.on('reconnect', this.handleOnReconnect);
this.client.on('message', this.handleOnMessage);
```
If the connection fails only "close" handler is invoked. No error will be shown and reconnect loop will start.

> [6:13:06][MQTT] Connection closed.
> [6:13:38][MQTT] Reconnecting.
> [6:13:40][MQTT] Connection closed.
> [6:14:11][MQTT] Reconnecting.
> [6:14:13][MQTT] Connection closed.

Please notice when username/password is correct everything functions as expected. Am I doing something wrong?

**Comment by mvayngrib** [comment]
i'm experiencing a similar issue with aws-iot-device-sdk (which uses this mqtt client underneath). When authentication fails, there's no feedback to my code other than the 'close' event.

**Comment by mcollina** [comment]
Would somebody try a PR for this?

**Comment by yohei1126** [comment]
will do if it is not urgent.

**Comment by mvayngrib** [comment]
@mcollina I see the library explicitly suppresses errors from the websocket stream: https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L262 Before any PRs, it would be good to know the reason for that decision, because this is one of those purposely suppressed errors

**Comment by mcollina** [comment]
line 262 is completely superflous and can be removed. All errors are intercepted by https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L266

**Comment by mvayngrib** [comment]
@mcollina you're right. And it seems it's aws-iot-device-sdk that's ignoring the error re-emitted on 'close', at least Node-side. Will check browser-side

**Comment by OmgImAlexis** [comment]
Can someone confirm this is still an issue or if it was fixed up/downstream?

**Comment by deftomat** [comment]
Still an issue. We see 403 in browser's console but error event is not emitted.

**Comment by elmontoya7** [comment]
Any solution found?
