### ISSUE TITLE
Using MQTT with NativeScript

### ISSUE THREAD

**Issue by pierreclr** [mqttjs/MQTT.js#625]
Hi there,

I'm actually trying to use mqtt.js library inside a NativeScript project but got the following error : 
`app/tns_modules/mqtt/mqtt.js:1:19: JS ERROR SyntaxError: Invalid character: '#'` 

Is MQTT.js compatible with NativeScript or only with browser and node env ? In this case does someone can give me directives (polyfills) to make it compatible ?

**Comment by RangerMauve** [comment]
Seems to be related to NativeScript not supporting the [browser](https://github.com/mqttjs/MQTT.js/blob/master/package.json#L55) attribute in the package.json.

Change your code to use `require("mqtt/lib/connect")` instead

**Comment by RangerMauve** [comment]
There's a good change that NativeScript won't support this library, though since we require either a Node.js or a Browser environment.

**Comment by pierreclr** [comment]
Thank you @RangerMauve for your answers. I will certainly choose a lighter implementation to achieve my goal ! Maybe starting with this library https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/mqttws31.js

**Comment by VeeTeeDev** [comment]
@pierreclr 

Did you make any progress on this matter ?
