### ISSUE TITLE
how to reconnect when mqtt server restart?

### ISSUE THREAD

**Issue by ashishvaghasiya** [mqttjs/MQTT.js#630]
After restarting mqtt server client not getting the message. how to handle this.

**Comment by mcollina** [comment]
what do you mean? Can you write down steps to reproduce?

**Comment by ashishvaghasiya** [comment]
@mcollina

1. connecting mqtt_server and subscribe some topic.
2. after some issue mqtt_server down/ restart
3. after that client was not reconnecting or not getting subscribe topic message.

how to handle this case? can you give me the solution?

**Comment by mcollina** [comment]
Is the client not reconnecting or not receiving messages on the subscriptions? Who is the sender?

**Comment by ashishvaghasiya** [comment]
Node js Server is sender

**Comment by mcollina** [comment]
Can you upload a full example that demonstrate your problem?

**Comment by ashishvaghasiya** [comment]
thanks @mcollina 

getting solutions how to reconnect server after server restart.

**Comment by ievgennaida** [comment]
> thanks @mcollina
> 
> getting solutions how to reconnect server after server restart.

So how to have you fixed this?

**Comment by Sujay-shetty** [comment]
@ashishvaghasiya I'm also facing same issue like when mqtt server restart occurs automatic connection is working fine but not able to receive messages.
Could you please provide information on how you solved this issue.

**Comment by ievgennaida** [comment]
> @ashishvaghasiya I'm also facing same issue like when mqtt server restart occurs automatic connection is working fine but not able to receive messages.

I have this issue when QOS 2 sent before the connection lost. 
Workaround is to use QOS 1.
