### ISSUE TITLE
How to add awsIotUrlSigner lib in the browser ?

### ISSUE THREAD

**Issue by minhlong** [mqttjs/MQTT.js#632]
I add "mqtt.min.js" in to html file and connect to AWS like as below:

```
var client = mqtt.connect(host, {
            clientID: 'Brow1',
            transformWsUrl: function (url, options, client) {
                var tmpURL = awsIotUrlSigner(url)
                console.log(tmpURL)
                return tmpURL;
            }
        })
```

But the console say: Uncaught ReferenceError: awsIotUrlSigner is not defined

Thanks and Best Regards

**Comment by sublimator** [comment]
awsIotUrlsigner is just mock code, that must be provided by the user

**Comment by minhlong** [comment]
I got it,

Thanks so much for your information
