### ISSUE TITLE
WebSocket connection to 'ws://test.mosquitto.org/' failed: Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by theunreal** [mqttjs/MQTT.js#633]
I'm simply trying to use mqtt.js to connect to the test mosquitto server using the browser:

```
var client  = mqtt.connect('mqtt://test.mosquitto.org')

		client.on('connect', function () {
		  client.subscribe('presence')
		  client.publish('presence', 'Hello mqtt')
		})
```

When I launch my app (Angular  - client side) I get the following error:

`mqtt.min.js:6 WebSocket connection to 'ws://test.mosquitto.org/' failed: Error during WebSocket handshake: Unexpected response code: 200`

I also tried:
`var client  = mqtt.connect('mqtt://broker.mqttdashboard.com');`

resulted in error 301

`WebSocket connection to 'ws://broker.mqttdashboard.com/' failed: Error during WebSocket handshake: Unexpected response code: 301`

Is there anything I'm missing here?

**Comment by mcollina** [comment]
See https://github.com/mqttjs/MQTT.js/issues/628#issuecomment-305417900
