### ISSUE TITLE
Reconnect does not happen when broker’s port is blocked and released

### ISSUE THREAD

**Issue by i-gk** [mqttjs/MQTT.js#636]
Hi All,

I noticed that when the broker’s port (1883) is blocked and then released the reconnect from client does not happen. 

```
mqttOptions = {
		"clientId":"myclientid",
		"protocolId":"MQTT",
		"protocolVersion":4,
		"keepalive":60000,
		"clean": false,
		"reconnectPeriod":"10000",
		"will": {
				"topic":"v1/items/client/101/ev/Will",
				"payload":"client terminated",
				"qos":2,
				"retain": true
				}
		};
```
can recreate this by enable/disable a firewall rule to block inbound connections on broker’s host.

**Comment by mcollina** [comment]
Would you mind to work on a fix?

**Comment by i-gk** [comment]
I got my configs wrong. keepalive is seconds not mili-seconds. once that is corrected it was all good.
