### ISSUE TITLE
client.end() Not an issue

### ISSUE THREAD

**Issue by stherrienaspnet** [mqttjs/MQTT.js#640]
I'm using typescript, as soon I call client.connect(), I'm adding some EventListener on most of your events and then I add a subscription. When closing connection do i need to remove subscription and remove even listener first before calling client.end() for a clean disconnection or client.end() will take care of this perfectly?
 
Thanks a million time for your amazing contribution!

**Comment by mcollina** [comment]
No you can call end safely, you will be disconnected. If you are connecting with clean: false, the subscription will be restored when the same client reconnects.
