### ISSUE TITLE
BrowserMQTT.js with secure client?

### ISSUE THREAD

**Issue by BenjaminHaldin** [mqttjs/MQTT.js#642]
I have already set up a mosquitto broker with secure websocket listener. But on the client side, when i connect, it will show username and password in the source code... Any way to hide this?

**Comment by mcollina** [comment]
You need either:

a. to fetch those credentials dynamically via XHR
b. to use a custom auth logic in Mosquitto, so that you can validate the credentials using a cookie or something similar
c. sign the connection URL for that user: https://github.com/mqttjs/MQTT.js#signed-websocket-urls
