### ISSUE TITLE
Missing messages

### ISSUE THREAD

**Issue by pmehtaaustin** [mqttjs/MQTT.js#644]
When polling a specific topic for about 15 min, I got ~ 300 messages through nodejs code and over 1300 messages for the same topic using MQTTFx client.  I am using mqtt package with the following connect params:

```mqttconfig.prod = {
    url: 'mqtt://serverIPAddress',
    port: 8883,
    keepalive: 30,
    clientId: 'ls_mqtt_client_'+Date.now(),
};
```
The server is Erlang MQTT broker, vers. 2.2.

Any tips on how to not lose messages?

**Comment by jdiamond** [comment]
Polling?

Are you sure your client didn't disconnect/reconnect during that period? MQTT.js does that automatically.

You're using a dynamic `clientId` and not setting `clean: false` so the broker definitely isn't saving messages for you while you're offline.

Of course, the publisher needs to publish with `qos: 1` and your client needs to subscribe to their topics with `qos: 1` for that to work.

If I was confident my client was not disconnecting, I would expect to receive all the messages even without the above, but I can't rely on that. Clients _always_ disconnect. When I care about not losing messages, I do all of the above.

To see if you're reconnecting, handle the `connect` event and log something. If you're not disconnecting and still losing messages, you'll probably have to share more code.

**Comment by alexduh** [comment]
Hello, I have a similar problem when using mqtt.js. I verified that the client was disconnecting/reconnecting frequently, but when I added the option ```clean: false```  my client isn't receiving any messages, whereas before it would receive about half. What might be going wrong?

**Comment by peeyushsrj** [comment]
Same issue. It's published from server to broker (qos=2) while on client side subscription (q=2) it's loosing messages.
