### ISSUE TITLE
Support for TLS CRL?

### ISSUE THREAD

**Issue by edgracilla** [mqttjs/MQTT.js#646]
Our app requires cert revocation list, any plan to support this one?

**Comment by jdiamond** [comment]
MQTT.js is a client library. It would be up to your broker to support checking a CRL. Assuming it does, you would set the `cert` and `key` options when connecting to it just like with any TLS connection, and the server would check your cert against its CRL. So as far as I'm aware, MQTT.js already supports everything it can to enable this. Hope this helps.
