### ISSUE TITLE
Only receiving message from last subscription after reconnecting with same session

### ISSUE THREAD

**Issue by peppesilletti** [mqttjs/MQTT.js#647]
Hi, I am experiencing a problem when using the session concerning subscriptions. When I reconnect I only receive the message of the last subscription (qos: 2). Is this an expected behavior  or is it a bug? I'm posting the test that can show this problem (sorry about the pyramid :) ):

```coffee
mqtt = require 'mqtt'

client1 = mqtt.connect 'mqtt://localhost:1883', { clientId: 'testing', clean: false }

client1.on 'connect', (connack) ->
  console.log 'connack.sessionPresent:', connack.sessionPresent

  client1.subscribe 'test1', { qos: 2 }, (error, granted) ->
    return console.error if error
    console.log 'subscribed test1!', granted

    client1.subscribe 'test2', { qos: 2 }, (error, granted) ->
      return console.error if error
      console.log 'subscribed test2!', granted

      client1.subscribe 'test3', { qos: 2 }, (error, granted) ->
        return console.error if error
        console.log 'subscribed test3!', granted

        client1.publish 'test1', 'value1', { qos: 2, retain: true }, ->
          client1.publish 'test2', 'value2', { qos: 2, retain: true }, ->
            client1.publish 'test3', 'value3', { qos: 2, retain: true }, ->

              client1.end ->
                client2 = mqtt.connect 'mqtt://localhost:1883', { clientId: 'testing', clean: false }

                client2.once 'connect', (connack) ->
                  console.log 'connack.sessionPresent:', connack.sessionPresent

                client2.on 'message', (topic, message) ->
                  console.log topic.toString(), message.toString()

```

Output: 
```
connack.sessionPresent: false
subscribed test1! [ { topic: 'test1', qos: 2 } ]
subscribed test2! [ { topic: 'test2', qos: 2 } ]
subscribed test3! [ { topic: 'test3', qos: 2 } ]
connack.sessionPresent: true
test3 value3
```

**Comment by mcollina** [comment]
The behavior is correct. You are receiving only `test3` because you have received the rest with the first connection. I recommend you to add a `' message'` listener also to `client1` to see those messages.

**Comment by peppesilletti** [comment]
Hi @mcollina, thank you for the fast answer. Maybe I am misunderstanding how the persistent sessions work. I was expecting the session to preserve the subscription to all the topic it was subscribed before disconnecting and since I'm retaining the messages, to receive them back. (I've been reading this article: [http://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages](url)).

Am I misunderstanding?

**Comment by mcollina** [comment]
I thought you were referring to the QoS 2 part and for the offline subscription.

@peppesilletti which broker are you using? Can you please verify with mosquitto?

**Comment by peppesilletti** [comment]
@mcollina I am using mosquitto for my development and I have the same behavior with the emqtt broker.

**Comment by mcollina** [comment]
can you please provide a script in pure javascript so I can reproduce?

**Comment by mcollina** [comment]
Does removing QoS: 2 fixes the issue?

**Comment by peppesilletti** [comment]
I've tried with QoS 1 and the problem persists. Anyway, sure I'm going to write a pure javascript script for you!

**Comment by peppesilletti** [comment]
Here it is the pure JS script:

```javascript
var mqtt = require('mqtt')

var client1 = mqtt.connect('mqtt://localhost:7654', { clientId: 'testing', clean: false })

client1.on('connect', function (connack) {
  console.log('connack.sessionPresent:', connack.sessionPresent)

  client1.subscribe('test1', { qos: 2 }, function (error, granted) {
    if (error) {
      return console.error
    }
    console.log('subscribed test1!', granted)

    client1.subscribe('test2', { qos: 2 }, function (error, granted) {
      if (error) {
        return console.error
      }
      console.log('subscribed test2!', granted)

      client1.subscribe('test3', { qos: 2 }, function (error, granted) {
        if (error) {
          return console.error
        }
        console.log('subscribed test3!', granted)

        client1.publish('test1', 'value1', { qos: 2, retain: true }, function() {
          client1.publish('test2', 'value2', { qos: 2, retain: true }, function() {
            client1.publish('test3', 'value3', { qos: 2, retain: true }, function() {

              client1.end(function () {
                var client2 = mqtt.connect('mqtt://localhost:7654', { clientId: 'testing', clean: false })

                client2.once('connect', function (connack) {
                  console.log('connack.sessionPresent:', connack.sessionPresent)
                })

                client2.on('message', function (topic, message) {
                  console.log(topic.toString(), message.toString())
                })
              })
            })
          })
        })
      })
    })
  })
})

```

**Comment by mcollina** [comment]
The behavior is correct, mosquitto is not sending the retained messages after a restored session, but only for new subscribes.

@behrad this proves that the behavior in aedes is wrong, and you are right. We should not send the retained messages when restoring a session.

**Comment by peppesilletti** [comment]
I see, I tried to send an offline to client2 while it's offline and it receives the messages when it's back online. So as you say it only regards retained messages. I am curios to understand why this behavior takes place, if the subscriptions are part of the session and the client is interested in those kind of messages, why not getting them?

**Comment by mcollina** [comment]
retained messages are sent only in case of new subscriptions. If a client restores the session, it is not a new subscription after all.

**Comment by peppesilletti** [comment]
That makes sense! Thank you for your time and helpful explanations! :)
