### ISSUE TITLE
Store.del() requires a callback

### ISSUE THREAD

**Issue by peppesilletti** [mqttjs/MQTT.js#648]
Hi, I come accross a problem using the library mqtt.js after the fix  [https://github.com/peppesilletti/MQTT.js/commit/735ed2d7b2b49c72d9ab5e62c3f8748172c925c3](url)
The del of the store method requires a cb to return the packet:
```javascript
/**
 * deletes a packet from the store.
 */
Store.prototype.del = function (packet, cb) {
  packet = this._inflights[packet.messageId]
  if (packet) {
    delete this._inflights[packet.messageId]
    cb(null, packet)
  } else if (cb) {
    cb(new Error('missing packet'))
  }

  return this
}
```
Should the fix be changed to pass a callback or should the del method check if the callback is provided?

**Comment by mcollina** [comment]
Definitely passing a callback is mandatory. Can you please send a PR?

**Comment by peppesilletti** [comment]
Sure! : )
