### ISSUE TITLE
typescript: reconnect succeed, subscribe failed but subscribe call back is ok.

### ISSUE THREAD

**Issue by sudotamm** [mqttjs/MQTT.js#649]
I import @type/mqtt in my code, and try to use like this: 

```
var options: ClientOptions = {
            keepalive : this.config.keepalive,
            reconnectPeriod: 10000,
            clientId : 'clientid_' + Math.floor(Math.random()*65535),
            username: this.config.user,
            password: this.config.pass
}
var url = scheme + '://' + this.config.host + ':' + this.config.port;
// Create the client and listen for its connection
this.client = connect(url, options);

this.client.addListener('connect', this.on_connect);

public on_connect = () => {
       this.client.subscribe(this.config.subscribe, {qos: 2}, (err, granted)=>{
            console.log(err)
            console.log(JSON.stringify(granted)) //topic will response even if subscribe failed
            this.state.next( TransportState.SUBSCRIBED ); //subscribe failed sometimes, so fetch will no response from time to time
        });
}
```

**console.log as below:** 
```
===Ryan: mqtt connection CONNECTED.===
mqtt: begain subscribe topic: /UMR/appointments/test/status
mqtt: subscribe call back.
mqtt: subscribe error value: null
mqtt: subscribe granted value: {"topic":"/UMR/appointments/test/status","qos":2} 
===Ryan: mqtt connection SUBSCRIBED.===
mqtt: fetch: {"mail":"test"} 
```

If network is broken, mqtt will auto reconnect succeed, then I resubscribe topics in **on_connect** function, I found that subscribe failed sometimes, but ClientSubscribeCallback object always response err = null, and then my fetch command will never receive response.

Any help will be very appreciated, Thanks.

**Comment by mcollina** [comment]
Can you reproduce the same error without TypeScript? Also, che you include a full example?

**Comment by sudotamm** [comment]
I used @types/mqtt which contains type definitions for MQTT.

I know client subscribe key like 'connect', 'reconnect', 'message', 'offline', 'error'. Can I add listener for subscribe call back? 
Such as: 
`
this.client.addListener('subscribe', subscribeCallback);
`

**Comment by sudotamm** [comment]
PR [Add a flag to control re-subscribe functionality. #665]  seems can fix this issue, I will close this issue and update to version 2.12.0
