### ISSUE TITLE
Support for mqtt v5 specification

### ISSUE THREAD

**Issue by jeffdare** [mqttjs/MQTT.js#651]
What is the plan for support of MQTT v5 specification for this node?

**Comment by mcollina** [comment]
Would you like to contribute? i have no time right now.

**Comment by muka** [comment]
Hi
is there someone working on that or would like to work on the implementation?

A *growing* list of features for the v5 support (help is welcome to make it more precise)

- [ ] Properties as header variables
- [ ] Error reason code and message
- [ ] Flow control for QoS 1/2
- [ ] Request / Response pattern
- [ ] Shared Subscriptions
- [ ] Session management
- [ ] Publication expiry interval
- [ ] Improved AUTH support 
- [ ] Last Will and Testament
- [ ] keep alive timeout in CONNACK
- [ ] CONNECT with empty user field
- [ ] Provide client-id in CONNACK
- [ ] Maximum QoS from CONNACK and reason code on disconnect
- [ ] Use topic aliases over full topic in messages

A few resources to crunch:

- [Specification](http://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html)
- [New features explained](https://dzone.com/articles/mqtt-v5-what-is-on-the-way)

See also this issue for reference https://github.com/mcollina/aedes/issues/194

Thanks

**Comment by RangerMauve** [comment]
I think the first step will be to modify [mqtt-packet](https://github.com/mqttjs/mqtt-packet) to be able to support the new message types.

**Comment by muka** [comment]
Thanks for the reference, will look into it

**Comment by manifest** [comment]
Are there any progress on this one? There are currently a bunch of brokers that have already implemented v5 support.

**Comment by scarry1992** [comment]
@manifest, already in master, on npm coming soon.

**Comment by manifest** [comment]
I see. Thanks!

**Comment by thomasnordquist** [comment]
close?

**Comment by mcollina** [comment]
yes!
