### ISSUE TITLE
travis error?

### ISSUE THREAD

**Issue by taoqf** [mqttjs/MQTT.js#654]
https://travis-ci.org/mqttjs/MQTT.js/jobs/257626265
```sh
> mqtt@2.9.3 typescript-compile-execute /home/travis/build/mqttjs/MQTT.js
> node test/typescript/*.js
connect("broker.mqttdashboard.com")
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
Anyone could finger me out what's wrong with my commit, or some thing with travis?

**Comment by mcollina** [comment]
@sublimator can you please refactor https://github.com/mqttjs/MQTT.js/blob/master/test/typescript/broker-connect-subscribe-and-publish.ts#L3 so that it spins up a local server like the other JS tests?
