### ISSUE TITLE
Does mqttjs have a max payload size ?

### ISSUE THREAD

**Issue by gleroi** [mqttjs/MQTT.js#655]
Hello,

i am using mqttjs 2.9.3 in a browser (chrome). It seems that when mqttjs receive a frame bigger than 28k, it fails.

Sometimes mqttjs closes the connection, sometimes the underlying websocket seems to receive nothing.

I've other clients subcribed to the same topic, and they receive the message without any problems.

Is there any max size/configuration i should be aware of ?

Thank you.

**Comment by mcollina** [comment]
@gleroi can you reproduce it by connecting via websocket from Node.js? What are you using as a broker?

**Comment by gleroi** [comment]
The broker is mosquitto 1.4.10 (with support for websocket)
I'll try to reproduce it with nodejs.

**Comment by gleroi** [comment]
After more testing the error occurs only when sending qos 0 message.
With qos 1 it works

**Comment by marciopamplona** [comment]
In my case I'm connecting to AWS IoT core and messages > 65Kb seems to fill the buffer and close the WebSocket socket.

![image](https://user-images.githubusercontent.com/4551753/192623633-c2933015-1ae4-4fdc-8ba5-fe2dc506f97f.png)

**Comment by marciopamplona** [comment]
bump

**Comment by marciopamplona** [comment]
I catch the close event reason:
![image](https://user-images.githubusercontent.com/4551753/192644923-c18548ea-3d99-42dd-9374-f6d627c0e83a.png)
