### ISSUE TITLE
Event offline is not emitted

### ISSUE THREAD

**Issue by ffamar** [mqttjs/MQTT.js#661]
Hi,
in Linux after unpluggin the lan cable, the 'offline' event is not emitted.
In Windows, using the same configuration there are no problems.

I have just installed the last avaiable version 2.11.0.

Thanks!
Fabio.

**Comment by mcollina** [comment]
Have you tried waiting for a while? Maybe the socket gets closed/notified after a while. This is very platform dependent.

Which version of Node.js are you using? If it is a bug, it's likely to be part of Node.js itself.

**Comment by ffamar** [comment]
Hi Matteo, 
I waiting for a 20 minute and my node version is 6.9.5.
When I unplug the cable the message "ethernet eth0: Link is Down" appear immediately in console.

Thanks!

**Comment by mcollina** [comment]
Who prints "ethernet eth0: Link is Down"? What's your code?

**Comment by ffamar** [comment]
No no, it's a Kernel Message.

**Comment by mcollina** [comment]
have you got a keepalive setup?

**Comment by ffamar** [comment]
Probably I found the cause of the problem, the tcp socket from my target to broker remain in ESTABLISHED status.I tried to change tcp_keepalive_time from 7200 to 10 without results.

Now I must find a solution.

**Comment by RangerMauve** [comment]
@ffamar Does your broker support keepalive messages? I had this issue in the past in a custom broker that wasn't properly setting up listeners to kill the connection if the keepalive failed.

**Comment by ffamar** [comment]
I set
tcp_retries1=1 
tcp_retries2=1 
tcp_keepidle=3
tcp_keepintvl=3
tcp_keepcnt=3
and the problem solved.

Now event 'offline' is emitted and tcp socket is closed approximately after 30 seconds.
I need to study the correlation between the tcp_xxxx parameters and the status of the socket tcp in depth.

@RangerMauve  my broker is't custom, it is RabbitMQ, I think it support keepalive.

Thanks for support.
