### ISSUE TITLE
How to disable re-subscribe functionality

### ISSUE THREAD

**Issue by redboltz** [mqttjs/MQTT.js#664]
I was using MQTT.js 2.7.2 for a long time. Recently I updated it to 2.11.0.
Then I got some suspicious behavior. Some subscribe packet does't seems to send to the broker.

I started debugging, then I found the property of MqttClient `_resubscribeTopics` caused the behavior.

I tried to find the document about re-subscribe functionality, but I didn't found it, so far.
Does the documentation exists?

I read the code and guess that it is the functionality that the MqttClient remains which topics are subscribed. And when the client is disconnected, then connect again, remained topics automatically subscribe just after connack packet is received.
I'm not 100% sure I understand correctly.

I think that it is useful functionality. But not all users need it. So I want to disable the functionality. How can I do?

I tried to update client.js temporarily.

https://github.com/mqttjs/MQTT.js/blob/v2.11.0/lib/client.js#L446

```JavaScript
  if (Array.isArray(obj)) {
    obj.forEach(function (topic) {
      delete that._resubscribeTopics[topic] // I added
      if (that._resubscribeTopics[topic] < opts.qos ||
          !that._resubscribeTopics.hasOwnProperty(topic) ||
          resubscribe
        ) {
        subs.push({
          topic: topic,
          qos: opts.qos
        })
      }
    })
  } else {
    Object
      .keys(obj)
      .forEach(function (k) {
        delete that._resubscribeTopics[k] // I added
        if (that._resubscribeTopics[k] < obj[k] ||
            !that._resubscribeTopics.hasOwnProperty(k) ||
            resubscribe
          ) {
          subs.push({
            topic: k,
            qos: obj[k]
          })
        }
      })
  }
```

I added the two lines I commented `// I added`, then my code becomes to work as I expected.

I found one case that _resubscribeTopics should be deleted even if the re-subscribe functionality is enabled.

That is when MqttClient received a suback packet and its payload bit7 is 1,
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718071

that means subscribe is failed. 
In this case _resubscribeTopics should be deleted.
It seems that the key of _resubscribeTopics is topic, but in suback error receiving case, need to specify by messageId.

**Comment by mcollina** [comment]
Would you mind sending a PR to address the problem you have found? I'm also ok in having a flag disable the automatic resubscribe behavior.

**Comment by redboltz** [comment]
@mcollina , I just sent the PR. #665

**Comment by sudotamm** [comment]
I aslo got this problem. I used version 2.9.3.
When mqtt connection reconnected succeed. And then I resubscribe topics manully, sometimes it can subscribe succeed, sometimes it can't work, it's very weird.
