### ISSUE TITLE
strange network error handling

### ISSUE THREAD

**Issue by krukid** [mqttjs/MQTT.js#666]
When I try to connect to an unreachable endpoint (e.g. `wss://not.reachable.com:8083/mqtt`) with `connectTimeout = 30000 (default)` and `keepalive = 60 (default)`, something strange starts to happen:

1. after 30 seconds a `close` event gets emitted with an undocumented first argument that is a `premature close` error;
2. connection stays open for a full minute and then terminates with a console message:
    > WebSocket connection to 'wss://not.reachable.com:8083/mqtt' failed: Error during WebSocket handshake: Unexpected response code: 504

    (504 = Gateway Timeout)
3. no `error` events are fired at any time

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a PR with a proposed fix?

How would you expect this library to behave?

**Comment by unirey** [comment]
Yes, I was just about to open a similar issue: 

I had `403 Forbidden`: it doesn't emit `error` event, but it emits `close` which I find a little bit weird.

Where am I supposed to handle errors? Both in `close` and `error`? Different errors emit different events? This is definitely something we need to discuss.

**Comment by mcollina** [comment]
Would you like to make a proposal and send a PR to implement it?

**Comment by unirey** [comment]
I think we should first discuss & reach to consensus what should emit what (when it comes to errors).

**Comment by mcollina** [comment]
@unirey There are several open (or closed) issues on errors to things we might want to change.
I'm very open to discuss the current situation and what to improve, but someone else should take the lead on this.

**Comment by japita-se** [comment]
same happen if the routing table changes
