### ISSUE TITLE
Question about systemjs integration.

### ISSUE THREAD

**Issue by stherrienaspnet** [mqttjs/MQTT.js#668]
Hello, thanks 1000 times for your libraries! I'm trying to integrate mqtt.js into angular 4 tour of hero demo application without any success. I used mqtt.js server side into another project with sucess. But now this project is using system.js, is there is something I'm missing
Here is the sample application source.
https://github.com/angular/angular

**Comment by RangerMauve** [comment]
Could you please specify what issues you're having with the integration? Are you getting build errors? If so could you please post a stack trace. Also, knowing the version of MQTT.js and SystemJS that you're using would help us debug.

**Comment by stherrienaspnet** [comment]
"mqtt": "^2.11.0",
"systemjs": "0.19.39",

Here is a screen capture of the issue.
![image](https://user-images.githubusercontent.com/6126961/29275230-690d1f5a-80d8-11e7-9aaf-e0cb3352b643.png)

The complete source code can be found here
[https://github.com/stherrienaspnet/pi-robot](https://github.com/stherrienaspnet/pi-robot)

Thanks for your help :)

**Comment by RangerMauve** [comment]
Are there any logs visible from your build server?

**Comment by stherrienaspnet** [comment]
Hello RangerMauve,
into my gpio.service.ts i have ana import as the following
import * as mqtt from 'mqtt';
and as soon i use mqtt into my code i got the issue when running the application
like here 
![image](https://user-images.githubusercontent.com/6126961/29277161-deae1858-80de-11e7-8c9c-ab9b7e8d27a5.png)

Here is my systemjs.config.js file content

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      'app': 'app',

      // angular bundles
      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/router/upgrade': 'npm:@angular/router/bundles/router-upgrade.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
      '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
       'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'

    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js',
        meta: {
          './*.js': {
            loader: 'systemjs-angular-loader.js'
          }
        }
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
  });
})(this);
 I don't know what is the proper way to include mqtt here?

**Comment by RangerMauve** [comment]
Adding `'mqtt': 'npm:mqtt` to your map and see if that helps.

Is the process you're running to build the bundle outputting any errors or warnings?

**Comment by stherrienaspnet** [comment]
i tried but nothing changed, i do not have a trace showing me the issue.  I even replace try with require.

**Comment by RangerMauve** [comment]
Not sure what I can do without additional logs. If you could try to find a way to get logs from systemJS on why it's unable to import `mqtt` even with the changes to the config, that would help me get you to the next step. Maybe look up a guide for using systemjs with npm modules

**Comment by RangerMauve** [comment]
If anything you could try following [this guide](https://github.com/mqttjs/MQTT.js#browserify) to build the mqtt.js library into a single bundle that you can import in your app

**Comment by stherrienaspnet** [comment]
Thanks you very much for your help!
