### ISSUE TITLE
Angular 4 WebSocket error

### ISSUE THREAD

**Issue by stherrienaspnet** [mqttjs/MQTT.js#669]
Hello mqtt specialist, I'm really sorry, I love so much your library and i cannot let it go... I'm not able to etablish the minimal connection to the mosquitto test broker. Here is a sample of the message seen
WebSocket connection to 'ws://test.mosquitto.org/' failed: Error during WebSocket handshake: Unexpected response code: 200.

![image](https://user-images.githubusercontent.com/6126961/29301993-4eda9560-814e-11e7-925b-be7bd576ce65.png)

 The connect event is never fired, but the close it fired so many time...

Here is the linkto my tiny application, cannot believe I cannot make it work... You will probably see something i cannot see :) 

[https://github.com/stherrienaspnet/PI-ROBOT](https://github.com/stherrienaspnet/PI-ROBOT)

**Comment by sandro-k** [comment]
There is no MQTT WS service at ws://test.mosquitto.org/ . Please try ws://mosquitto.org:8080/

**Comment by stherrienaspnet** [comment]
Thanks you verry much!
