### ISSUE TITLE
How can I disconnect the connection?

### ISSUE THREAD

**Issue by AlirezaMoseni** [mqttjs/MQTT.js#670]
hi
How can I disconnect the connection?
Is this module have disconnect  method ? i cant find it :((

**Comment by mcollina** [comment]
it's .end().

**Comment by MartinMuzatko** [comment]
You should add this to the documentation @mcollina.

**Comment by mcollina** [comment]
@MartinMuzatko would you mind to send a PR? thanks!

**Comment by MartinMuzatko** [comment]
Oh! it looks like it already exists. 
https://github.com/mqttjs/MQTT.js#mqttclientendforce-cb
My bad! I didn't find it in the first place.
Everything should be alright.
