### ISSUE TITLE
can you put the BrowserMqtt.js on cdn directly?

### ISSUE THREAD

**Issue by saintthor** [mqttjs/MQTT.js#674]
i am not familiar with npm. it dosn't work friendly.

**Comment by mcollina** [comment]
It is already. As indicated in the README: https://unpkg.com/mqtt@2.12.0/dist/mqtt.min.js

**Comment by saintthor** [comment]
<script src="https://unpkg.com/mqtt@2.12.0/dist/mqtt.min.js"></script>
<script>
  var client = mqtt.connect('mqtt://test.mosquitto.org'); 
</script>
error in chrome:  WebSocket connection to 'ws://test.mosquitto.org/' failed: Error during WebSocket handshake: Unexpected response code: 200

also failed in firefox.

**Comment by mcollina** [comment]
MQTT over WebSockets in http://test.mosquitto.org/, as it's written in the website is on port 8080.

**Comment by saintthor** [comment]
thank you. it works.
