### ISSUE TITLE
Too many duplicate `subscribe` requests after reconnect

### ISSUE THREAD

**Issue by leecoder** [mqttjs/MQTT.js#675]
Hi~

Sometimes, I have too many duplicate `subscribe` requests after reconnect.

I think it is because of the following queuing.
https://github.com/mqttjs/MQTT.js/blob/b1463afe6dcbe833005c8d333be4f0ad79338a45/lib/client.js#L713

Why not just return an error?
Or what about checking `clean session`?

**Comment by mcollina** [comment]
@leecoder can you upload a snippet to reproduce? Or send a pull request with the change you would like to make?

**Comment by leecoder** [comment]
I've sent a PR. pls check it. Thnx~
