### ISSUE TITLE
What is the purpose of using stores?

### ISSUE THREAD

**Issue by abcd-ca** [mqttjs/MQTT.js#676]
Hi,

I'm new to MQTT but I do have a working prototype already. This library was very easy to get started with, thanks! I don't understand what the purpose of a store is – I gather it's for storing incoming/outgoing messages but why would one want to do that. I'm also not clear how messages would automatically get published if the connection were intermittent and reconnect happened. I've seen it work but not sure if it would eventually time out or where the messaged are stored without a store – just in memory? Would the store add the advantage of a persistent storage mechanism for queued messages, useful for flakey connections? 

Also, I want to publish with QoS 1; should I manage when to set `dup:true` on my own or does the mqtt library provide this somehow? I can manage the receiving end of the duplicates

Thanks!

**Comment by mcollina** [comment]
You should study up how MQTT QoS works, check out http://www.hivemq.com/mqtt-essentials/.

You can use https://github.com/mcollina/mqtt-level-store to persist on disk.

**Comment by abcd-ca** [comment]
I did read the hivemq articles, they're awesome. I read those before checking out your library. I still have some outstanding questions because I find some ambiguity remains with regards to roles and responsibilities:

> The sender will store the message until it gets an acknowledgement in form of a PUBACK command message from the receiver.

My question here, is whose responsibility is the storage? Will the mqtt library do it for me? Do I have to do it manually or is that where mqtt-level-store comes into play? 

> The association of PUBLISH and PUBACK is done by comparing the packet identifier in each packet. If the PUBACK isn’t received in a reasonable amount of time the sender will resend the PUBLISH message. If a receiver gets a message with QoS 1, it can process it immediately, for example sending it to all subscribing clients in case of a broker and then replying with the PUBACK.
The duplicate (DUP) flag, which is set in the case a PUBLISH is redelivered, is only for internal purposes and won’t be processed by broker or client in the case of QoS 1. The receiver will send a PUBACK regardless of the DUP flag.

If the DUP flag is "only for internal purposes" then why is it exposed in the [mqtt publish options](https://github.com/mqttjs/MQTT.js#publish) API? I know what it does, I'm just not clear if it's something I have to manage setting or if the client library will do this for me.

Thank you for providing clarification. I'm excited to clarify these things so I can head out into the mountains with a flaky connection to test out QoS 1 :)

**Comment by jdiamond** [comment]
Storage is the responsibility of the [Store](https://github.com/mqttjs/MQTT.js#mqttstore) objects you pass in to `mqtt.connect()`. The default implementation stores messages in memory which is not persistent. If you want persistence, you can use an alternate `Store` implementation, but you have to pass it in as the `incomingStore` and `outgoingStore` options when you connect.

I'm not actually sure what sets `dup` when re-publishing a packet. In all the years I've used MQTT, I've never checked `dup` to see if a message was re-published because I try very hard to write my subscribers so that they're idempotent. If your system should not process duplicate messages and checking for duplicates is expensive, you can choose to only do it when `dup` is true, avoiding the unnecessary check when it's false. I've never needed that, but it might be useful for you.

**Comment by abcd-ca** [comment]
Thank you, I was able to get the persistent store working and I see what it's for. I'll have a think about `dup` in my case. I did some field tests and the results were as expected when I went in and out of cell range – messages queued up and flushed out once I re-entered an area with coverage. 

One thing I am still curious about – what would you recommend for a flow where the initial connection can't be established because my device is powered up out of range? Would I just have to do my own queuing and check once we're online then try to make the initial connection once the (portable) device enters a zone with 3g coverage (I'm using a 3g module for data access)?. Or, maybe I can somehow add messages to the store prior to making the initial connection. It's really nice how once you have a connection, the connectivity can come and go and session can stop and resume respectively. I need to figure out a way to do this with the initial connection. Might need to roll my own by polling some `AT` commands to check for network connectivity prior to making the initial connection.

**Comment by jdiamond** [comment]
You don't have to wait until you establish a connection before you start publishing. MQTT.js queues up all messages you publish in your outgoing store until it actually connects and then it flushes publishes them for you.

You got the persistent store working, so it may already behave the way you want. 😄

**Comment by abcd-ca** [comment]
Oh, you're right, nice! Thank you. 

For messages that are set to QoS 1 and retain: true, do you know what event causes the broker to discard messages? Would it be after all subscribers have received the retained messages? If a subscriber never reconnects, I wonder what the maximum retention time is for a message by the broker? I'll have to read the spec again but maybe it depends on the broker implementation.

**Comment by jdiamond** [comment]
QoS 1 and retained messages aren't really related the way your question seems to imply.

QoS 1 subscriptions: The subscriber is saying "I want the broker to save all messages published to these topics while I'm offline". The publishers do NOT have to set retain: true. Not sure what the spec says about TTL, but I know Mosquitto and RabbitMQ have options for controlling this.

Retained messages: A publisher is saying "I want clients to immediately receive this message as soon as they subscribe without having to wait for me to republish it". There's an implied limit of 1 retained message per topic.

IME, I mostly publish and subscribe with QoS 1, but very rarely use retained messages.

**Comment by abcd-ca** [comment]
Hi @jdiamond I've spent some time meditating on this and I think I now get how it all works. If you have time to review a "missed messages, catch-up" problem and proposed solution I [outlined here](https://stackoverflow.com/questions/46229861/mqtt-catch-up-missed-messages-looking-for-feedback-on-design-assumptions), I'd be interested in your feedback. To sum it up though, I figure I'll have `QoS:1, retain:true` for all stateful messages (i.e. voltage, temperature) and for historically/contextually  relevant messages (i.e. chat messages in a conversation over time) I'll use `QoS: 1, retain: false`. If a subscriber disconnects and misses some chat messages, they can publish a message that requests a catch-up, causing the other client to re-publish everything that was missed (filtered by an exclusion list of message ids in the catch-up message) .
