### ISSUE TITLE
MqttJs Publish on QOS2 is entering to callback function without error even if no client recieved the message

### ISSUE THREAD

**Issue by arihantdaga** [mqttjs/MQTT.js#681]
I am using following code on my nodeJs Server from where i am publishing message to a topic.

```
let promise = new Promise((resolve, reject) => {
    MQTTclient.publish(topic, message, { qos: 2 }, (err) => {
        if (err) {
            return reject(err);
        } else {
            return resolve("success");
        }
    });
});

```
On the other end, a client is subscribed to the topic with QOS 2. 
I expect this code to work in a way such that the promise is resolved only if the client who has subscribed to the topic recieves this message. 
But this promise is fulfilled even if my device is offline(Means no body recieved this message). 
I am using EMQTTd Broker. (http://emqtt.io) And it supports QOS 2. 
Am i doing something wrong ? or understanding something wrong about qos ?

**Comment by mcollina** [comment]
This is not how it behaves. The publisher and the subscriber are fully decoupled. The callback is fired when the messages ownership has been transfered from the client to broker.
