### ISSUE TITLE
ReschedulePings can cause a dropped connection to never be realized

### ISSUE THREAD

**Issue by duncanfinney** [mqttjs/MQTT.js#682]
Hi Guys,

I was noticing that when `reschedulePings` is set to `true` the sending of the ping packet and also the _check_ for a timed out connection is being rescheduled. 

I am pretty sure that only the _sending_ of the next ping should be rescheduled when a control packet goes out. There still needs to be a check each keepalive period to see if you've received a ping or not.

Example to reproduce:
```javascript
const mqtt = require('mqtt');
const client = mqtt.connect({ 
   keepalive: 10
   reschedulePings: true
    ... 
});

client.on('connect', () => {
    console.log('pull the WAN from your router right now, wait 30 seconds, plug it back in');
    setInterval(() => client.publish('foo', 'bar'), 1000);
});
```

Your client will never realize that they're disconnected.

I think that #630 may be fixed by fixing this as well.

**Comment by OmgImAlexis** [comment]
@mcollina what's the go with this as the PR associated is closed.

**Comment by mcollina** [comment]
In doubt, close ;). Those are extremely hold.
