### ISSUE TITLE
object in payload 

### ISSUE THREAD

**Issue by alnikitich** [mqttjs/MQTT.js#685]
when i set payload = object (not string or buffer) and qos = 2
i have many reconnections to server when client send this packet.
After each try it disconnected withot errors
And i cant remove this message from outgoing stream because i havent any errors
This mesage stuck

**Comment by mcollina** [comment]
You can't send objects. Something in the client is erroring and you get a disconnection as a result. You should use JSON.stringify to convert your object to a string before sending.
