### ISSUE TITLE
qos2 payload

### ISSUE THREAD

**Issue by entcor** [mqttjs/MQTT.js#686]
Hello 
When i receive message with qos1 a get on payload uft8array like this: [2, 3, 4, 5, 6....],
but when i receive message with qos2 a get object on payload like this: {0:2, 1:3, 2:4, 3:5, 5:6....}
and i cant apply toString() to this object

Thank you!

**Comment by mcollina** [comment]
Can you please upload a script to reproduce the problem?

**Comment by alnikitich** [comment]
its not work only with nedb on client:

server code:
```
const aedes = require('aedes')();
const http = require('http');
const wss = require('websocket-stream');

var port = 1883;

const server = http.createServer();
const ws = wss.createServer({server: server}, aedes.handle)
server.listen(1884);
```

client code
```
<html>
<header>
	<script src="./browserMqtt.js"></script>
	<script src="./nedb.js"></script>
	<script src="./mqtt-nedb-store.js"></script>
	<script>

		var client = mqtt.connect("ws://127.0.0.1:1884",{
			clean: false,
			clientId: 'console_client',

		  	incomingStore: Manager().incoming,
		  	outgoingStore: Manager().outgoing
		});		


		client.on('connect', function () {
			console.log ("connected")

			client.subscribe('testQueue',{qos: 2});
			
			setInterval(function(){
				client.publish("testQueue","hello",{qos: 2});
			},4000);
		});

		client.on('message', function (topic, message) {
			console.log(message);
		});


</script>

</header>
<body></body>
</html>
```

i think it`s my error. when i`ve removed first {qos:2} in subscribe all work fine.
and when i change second {qos:2} to {qos:1} all work fine too

**Comment by mcollina** [comment]
You should probably open an issue against the nedb store.

**Comment by alnikitich** [comment]
i thinek it`s not depens on nedb directly.
What difference between mqtt.subscribe({qos:2}) and mqtt.publish({qos:2}) ?
and why i have difference result if i use it together ?
