### ISSUE TITLE
DUP flag not set when redelivering messages

### ISSUE THREAD

**Issue by iurly** [mqttjs/MQTT.js#692]
It looks like the MQTT client might re-transmit the same message (with the exact same messageId) without setting the DUP flag. In my case, the MQTT server I'm connecting to then treats this as an error and forces a disconnect. Then upon reconnection the same thing happens again (two messages with the exact same messageId sent in a row) leading to instability.

I had a look at the code:
https://github.com/mqttjs/MQTT.js/blob/8c34d13497bab2b315792ba406ae1e8d171c602f/lib/client.js
and I could not find any place where the dup flag is set.

Isn't that a bug?

**Comment by mcollina** [comment]
It seems weird that the same message is transmitted twice when reconnecting. Can you write an example that reproduces the problem?


Related to dup.. yes it’s probably a bug. Would you mind sending a PR?

**Comment by iurly** [comment]
Unfortunately I can't reproduce the issue at will. I got a report mentioning this problem occurring a few thousand times during a timespan of about 8 hours, then everything normal for a couple days, then again, then everything normal,and it's now been a week. Out of 8 similar setups, only one exposed this behavior.
I could write a patch but I'm not familiar at a with the code and I have no way to test it, so...

**Comment by amitmangalvedkar** [comment]
@mcollina : I am also getting this strange behaviour. This happens very intermittently. I am investigating if there is any particular trend when this happens, so that it can be reproduced at will.
