### ISSUE TITLE
in browser,can not use ssl&tcp?

### ISSUE THREAD

**Issue by coloz** [mqttjs/MQTT.js#698]
found /lib/connect/index.js:
`
if (process.title !== 'browser') {
  protocols.mqtt = require('./tcp')
  protocols.tcp = require('./tcp')
  protocols.ssl = require('./tls')
  protocols.tls = require('./tls')
  protocols.mqtts = require('./tls')
} else {
  protocols.wx = require('./wx')
  protocols.wxs = require('./wx')
}
`

**Comment by RangerMauve** [comment]
Browsers cannot make TCP connections. You must use websockets if you want to use MQTT from a browser.
