### ISSUE TITLE
MQTTS connection error on nodejs >= 8.6.0

### ISSUE THREAD

**Issue by redboltz** [mqttjs/MQTT.js#699]
After updating nodejs from 8.5.0 to 8.6.0, MQTTS connection becomes failure.

The reason is the commit https://github.com/nodejs/node/commit/ee157e5a7f
See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.6.0

Here is the document.
https://nodejs.org/api/tls.html#tls_tls_connect_options_callback

"path <string> Creates unix socket connection to path. If this option is specified, host and port are ignored."

I analyzed the problem. And 
https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/index.js#L60 adds `path` member.

And the variable `opt` that contains `path` member passed to https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/tls.js#L11

Hence host and port are ignored.

**Comment by redboltz** [comment]
I realized that I passed `mqtts://hostname:1234/`. If I remove the last `/`, the connection is successfully finished. However, I think that ignoring path might be convenient. Because existing working code don't need to be changed.

So I post the PR #700.

**Comment by bengl** [comment]
Perhaps MQTT should be in https://github.com/nodejs/citgm ?

**Comment by mcollina** [comment]
@bengl I think so, too. However our tests are network heavy and they tend to bet too flaky to be in CITGM.
