### ISSUE TITLE
Missing messages on AWS reconnection 

### ISSUE THREAD

**Issue by alex-borkun** [mqttjs/MQTT.js#701]
AWS EC2 instance `sts:AssumeRole`'s  `sessionToken` expires in ~6 hours and there is `expiry window` 15 seconds before to refresh token.
I refresh the token, but MQTT.js client still has expired token in url.
Then I get the following chain of events: `offline -> close -> reconnect -> transformWsUrl -> connect`.
And as the result I lose couple of messages.
QOS 1 on AWS has a chance to produce duplicate messages, QOS 2 is not supported.

Please expose the API to forcibly reset url.
Something like `client.setUrl(url: string)`.

**Comment by mcollina** [comment]
Can you send a PR?

**Comment by Surecom** [comment]
@mqtt-owner-team fix the issue please

**Comment by mcollina** [comment]
Unfortunately these are all volunteers, so we'll fix this when/if we have time.

**Comment by alex-borkun** [comment]
Guys, it won't help.
The update of `url` will require reconnection anyway.
Please close it as won't fix.
Thank you!
