### ISSUE TITLE
Routing Changes Stops Connection

### ISSUE THREAD

**Issue by japita-se** [mqttjs/MQTT.js#702]
We have a raspberry with 3 interfaces: wifi,eth0,ppp0.
It happens sistematically that when we activate a new interface (for example wifi), the routing table change (e.g. the default gateway) and the mqtt.js cannot publish anything anymore.
It sound like that the "old connection" on the previous interface goes "naturally" towards a timeout.
If we restart the application, everything works as usual.
Is it possible to handle these kind of situations?
It depends on the keepalive timer?

**Comment by mcollina** [comment]
I don't know, I've never tested this situation. It _should_ converge itself over time, error the old socked, and reconnect. If this is not working, something is broken. If you identify what the problem is, I'm very happy to land a PR.

**Comment by japita-se** [comment]
It seems related to the keepalive and timeout values. But I have to investigate...
Thks
