### ISSUE TITLE
Publish stops working after sending empty string as message

### ISSUE THREAD

**Issue by the1laz** [mqttjs/MQTT.js#705]
I'm using MQTT.js in the browser and I've had issues after sending messages like this: publish('topic','') 

The client then stops sending messages for a while, although it seems to receive them still. 

I've not had this issue with other clients, I've only used Mosquitto as the broker. I've edited my script to check for empty strings and replace them with '{}' as a workaround.

**Comment by mcollina** [comment]
Is it providing any error? It should work.
Can you please provide an example? or maybe a PR with a proper fix if you can figure it out?

**Comment by the1laz** [comment]
It's silent on the MQTTjs end. Mosquitto is getting the occasional "socket error on client", but it's not at the same time as a message being published.

I tried in both Chrome and Firefox on two different computers and got the same thing. I used the Firefox websocket monitor plugin to confirm that MQTTjs is sending something down the websocket every time, however Mosqitto does not receive any packets after the first publish. MQTTjs keeps receiving packets fro Mosquitto though. It seems that an empty string message is crashing all communications for MQTTjs->Mosquitto, but Mosquitto->MQTTjs keeps working fine.

client.publish('topic','') is an example. It only seems to happen with messages that are an empty string, regardless of topic. Because it seems to be outputting something to the websocket every time, but Mosquitto isn't receiving anything, I'd guess that something about the packet that MQTTjs is sending causes some issue with Mosquitto receiving, but I don't know much about the nuts and bolts of websockets or MQTT to speculate or investigate any further. I posted this here rather than to Mosquitto because I've sent messages with empty strings from other clients through Mosquitto before (Node-RED, MyMQTT) without issue.

**Comment by mcollina** [comment]
As I said, can you please produce an example to reproduce this bug? thanks.

**Comment by the1laz** [comment]
There's not much to reproduce. It's in a react app, I initialise with:
```
client = mqtt.connect(this.state.host+":"+this.state.port);
```
Then I have a couple of text fields for topic/message and a button to send when you click on it:
```
<Form.Field control={Button} onClick={this.mqttPublish}>{this.state.sendlabel}</Form.Field>
...
mqttPublish() {
  client.publish(this.state.topic,this.state.message,{qos:1},(err) =>{
    if(err) console.log(err)
  });
}
```
When this.state.message === '', the first click of the button will result in the broker getting the message, nothing happens on subsequent clicks. 
When thist.state.message !== '', the broker gets a message on every click.

**Comment by mcollina** [comment]
Unfortunately, I will not set up a react application to check this. Let me ask again: can you provide a failing test case for Node.js or the browser?

**Comment by the1laz** [comment]
Already gave you an example. Here's a test case:

```
npm install mqtt
```

index.html:
```
<html>
<head>

</head>
<body>
<script src="node_modules/mqtt/dist/mqtt.min.js"></script>
<script>
var client = mqtt.connect('ws://192.168.1.21:9001')

setInterval(function(){
  client.publish('test','')
  console.log('published')
},2000)
</script>
</body>
</html>
```

```
http-server .
```

Results in a single 'test' message arriving on another client subscribed to '#'. A couple of minutes later, another 'test' message. If you add a message:
````
setInterval(function(){
  client.publish('test','why???')
  console.log('published')
},2000)
```
The other client receives a message every 2 seconds.

**Comment by mcollina** [comment]
Which version of mosquitto are you using? I cannot reproduce this issue with 1.4.14.

**Comment by the1laz** [comment]
1.4.10 
I'll try a newer version.

**Comment by the1laz** [comment]
Seems to work for me on mosquitto 1.4.14, maybe a prior issue with their websocket implementation. Thanks for the help.
