### ISSUE TITLE
Using MQTT with keystore and certificates in browser javascript

### ISSUE THREAD

**Issue by deepanigi** [mqttjs/MQTT.js#709]
Hi all.

I am trying to use this example in pure JavaScript web application 
I have the following files ready.

- key.pem
- cert.pem
- ca.cg.pem

When i use the following code 

[Github source code link ](https://github.com/mqttjs/MQTT.js/tree/master/examples/tls%20client)

I am getting error and my js application cannot understand require

> var mqtt = require('mqtt')
> var fs = require('fs')
> var path = require('path')

How can i use this MQTT.js in JavaScript application to support security files as listed above

**Comment by mcollina** [comment]
That is not possible, the websocket API in the browsers does not allow you to specify those.
