### ISSUE TITLE
Handling subscription failure 

### ISSUE THREAD

**Issue by yemkay** [mqttjs/MQTT.js#714]
My broker is a commercial version of EMQ. We enabled Authorization in EMQ, so clients can subscribe to only assigned topics. To test negative case, I use this module to subscribe to a topic, not granted to client, but still get a success callback as below:

```
err = null
granted = [ { topic: '/topicName/json',   qos: 1} ]
```
In broker log, I could see the request is being denied. Other MQTT clients are able to handle this error. When testing Publish negative cases, the callback never gets called.

Broker is compatible with MQTT 3.1.1. My connection settings are,

`
 {
				username: username,
				password: password,
				keepalive: 60,
				clean: true,
				reconnectPeriod: 1000 * 30,
				clientId: username
			};
`

**Comment by abser** [comment]
Yes. I also see the same issue. Any insights from the MQTT.js team?

**Comment by Leen15** [comment]
I have the same issue. somebody have any workaround?

**Comment by chainhead** [comment]
For `mosquitto` broker **ONLY**

As per this [link](https://github.com/eclipse/mosquitto/issues/803#issuecomment-386110952), ACL with `mosquitto` may not prevent subscription; but, message delivery is certainly restricted.
