### ISSUE TITLE
can not connect to test.mosquitto.org any longer

### ISSUE THREAD

**Issue by saintthor** [mqttjs/MQTT.js#715]
i tried another mqtt server which i can connect by python.
code:
var client = mqtt.connect( { host: '112.xx.xx.xxx', port: 1883, username: 'localserver', password: 'mypasswd', protocolId: 'MQIsdp', protocolVersion: 3 } );
chrome tell me:
mqtt.min.js:1 WebSocket connection to 'ws://112.xxx.xx.xxx:1883/' failed: Connection closed before receiving a handshake response
WebSocketStream @ mqtt.min.js:1

how can i fix it?

or, is there other mqtt servers for testing?

**Comment by mcollina** [comment]
8081 is encrypted. 8080 is not encrypted.

**Comment by Tsumiqt** [comment]
Having the same issue. I want to connect to 'ws://test.mosquitto.org:8080/' or 'wss://test.mosquitto.org:8081/' but i immediately getting the offline event. Connecting to localhost via ws (even with reverse proxy nginx) is working fine.

**Comment by saintthor** [comment]
mqtt.min.js:1 WebSocket connection to 'ws://test.mosquitto.org:8080/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

8080 has never worked. while 8081 had worked 1 week ago.
and, you may see the Connected client count at http://test.mosquitto.org/ , the count is down to nearly 0 these days. there may be something wrong.

**Comment by jdiamond** [comment]
I just tested and both 8080 and 8081 are broken on test.mosquitto.org.  When I use the same code to connect to my private broker (using wss: in my URL), it works as expected.

**Comment by Tsumiqt** [comment]
Yep. Same here. Server seems to be down. Own Broker works as expected.

**Comment by saintthor** [comment]
hello,  jdiamond,
i have a mqtt server. i can set a tcp connection with it and run mqtt protocol on the connection with python.
params are issued in the first post. do you know how to connect it with mqttjs?

**Comment by jdiamond** [comment]
Based on your first post, I think you're trying to use MQTT.js in a browser app? That means you must use MQTT over WebSockets.

Are you sure your broker supports WebSockets? Not all do. Seeing you put the port as 1883 in your first post makes me think you're confusing your broker's support for plain MQTT with support for MQTT over WebSockets.

What broker are you using? Can you share your working Python code so we can see if it's really using MQTT over WebSockets?

**Comment by saintthor** [comment]
thank you.
i am afraid there is no websocket.

**Comment by jdiamond** [comment]
Glad you figured out the issue. Hope it's easy to add WebSocket support to your broker or replace it.
