### ISSUE TITLE
publish callback function not working in koa

### ISSUE THREAD

**Issue by Micrap** [mqttjs/MQTT.js#721]
When i use koa+mqtt to build a push service, i found a problem , client publish callback function not working,this is my example code 
```js
const mqtt = require('mqtt');
const client = mqtt.connect('mqtt://test.mosquitto.org:1883');
const Koa = require('koa');
const app = new Koa();

app.use(async function (ctx) {
    // ctx.body = "welcome";    
    client.publish('xx/test/callback', 'test callback', { qos:1 }, function (err, result) {
        ctx.body = err || result;
    })
})
app.listen(4000, function(){
    console.log("listening on 4000")
})
```
later, i view mqtt source code, found the message will put in a store queue, koa will not wait callback execute,so koa response not found,any solution could solve it?

**Comment by RangerMauve** [comment]
Try using [async-mqtt](https://github.com/mqttjs/async-mqtt) and `await`ing the promise returned from client.publish

**Comment by Micrap** [comment]
@RangerMauve Thanks for your reply, it has worked well.
