### ISSUE TITLE
Reconnect on publishing blank message in browser

### ISSUE THREAD

**Issue by edog1973** [mqttjs/MQTT.js#723]
I'm working on a browser client that connects to a broker via websockets.  Unfortunatly I'm seeing an issue where publishing a blank (zero length string) message causes the client to reconnect.  I'm only seeing this when bundling using browserify and running in browser.  Running the same code using node works fine. 

Note: the short keepalive causes the reconnect to manifest quicker.  Same issue with default keepalive, you just have to wait longer to see it.
 
```javascript
var mqtt = require("mqtt");

var options = {"keepalive":1}
var url = "ws://ohab1:1884"
var mqttClient = mqtt.connect(url, options);

mqttClient.on("connect", function(){
    console.log("MQTT is connected to %s", url);
    var topic = "test/topic";
    var msg = ""; //Change to "foo" removes issue
    mqttClient.publish(topic,msg);
});

mqttClient.on("reconnect", function(){
    console.log("MQTT is reconnecting")
});

mqttClient.on("offline", function(){
    console.log("MQTT is offline")
});

```
Result:
```
MQTT is connected to ws://ohab1:1884
MQTT is offline
MQTT is reconnecting
MQTT is connected to ws://ohab1:1884
MQTT is offline
MQTT is reconnecting
.
.
.
```

**Comment by mcollina** [comment]
Which broker are you using? Where you able to track down why this is happening?

**Comment by edog1973** [comment]
I'm connecting to a mosquitto install.  No, I have not been able to track down the root cause.

**Comment by RangerMauve** [comment]
@edog1973 Are you sure your broker is up / supports websockets?

**Comment by edog1973** [comment]
Yes, the broker works with web sockets.  I'm successfully using mqtt.js in an browser app that receives data from the broker.  It took me quite a while to find the issue as all the code looked good.  I ended up pulling almost everything from the app to come up with the example posted.  And the exact same code works fine when run though node.  It's only when compiled with browserify and running in the browser that I see the issue.

**Comment by edog1973** [comment]
I finally got around to debugging this further today and was able to come up with a resolution.  The issue crops up whenever publishing a message with an undefined or zero length string messages (also only when running in a browser).  I followed the code down through the mqtt module and into the writeToStream.js file of the mqtt-packet module.  At the end of the publish method the payload is written to the stream unconditionally.  Adding a check that only writes the payload to the stream if it's a non zero length resolves the issue.

```
diff --git a/writeToStream.js b/writeToStream.js
index 72167ef..ba5db10 100644
--- a/writeToStream.js
+++ b/writeToStream.js
@@ -285,7 +285,10 @@ function publish (opts, stream) {
   if (qos > 0) writeNumber(stream, id)
 
   // Payload
-  return stream.write(payload)
+  if (byteLength(payload) > 0)
+    return stream.write(payload)
+  else
+    return true
 }
 
 /* Puback, pubrec, pubrel and pubcomp */
``` 

FYI: I opened the issue here so am posting my findings here.  Please let me know if it would be better to post the comments on the mqtt-packet issues.

**Comment by mcollina** [comment]
I think the bug is in websocket-stream. Can you send a PR there?

**Comment by edog1973** [comment]
OK, I guess I was in a little over my head trying to figure this one out.  I'll leave it to those who know the systems better than I.

**Comment by mcollina** [comment]
@edog1973 you actually are correct! But this should be handled in WebsocketStream, more or less not writing down the buffer into the actual websocket in:

https://github.com/maxogden/websocket-stream/blob/master/stream.js#L104-L121

It is just a matter of moving that code over there!
