### ISSUE TITLE
Can't figure out how to get JSON to save in the database.

### ISSUE THREAD

**Issue by developerX** [mqttjs/MQTT.js#727]
Hey I was hoping to find out how to get the mqtt response to parse in JSON.

I have tried many different variations of this:
```js
client.on('message', function (topic, message) {
  var json = JSON.parse(message); // This errors out
});
```
The error I am getting is this:
`SyntaxError: Unexpected token I in JSON at position 0`

Tried this as well
```js
client.on('message', function (topic, message) {
  var json = JSON.parse(JSON.stringify(message)); // Doesnt fail
  console.log(json.id) //undefined
});
```

when I try to do : `message.toString()` it does look like it renders a the json object I sent from the client.

All I would like to do is convert the Buffer object coming from the message event to json object I can use to configure the save into the persistence layer. Or any other suggestions of getting this information into a database im all ears.

**Comment by RangerMauve** [comment]
What does your message look like?

**Comment by developerX** [comment]
so what I get back from the message is `{ "serial": SERIALNUMBER, "status": STATUS  }`. I did a work around by passing in the information as a string separated by commas, then used `str.split()` and that worked just fine.

I validated the message coming back using a MQTT GUI and it picked up the JSON just fine.

**Comment by TechnicalSoup** [comment]
@developerX did you end up solving this?

When I pass JSON around using MQTT I usually parse the message in a try catch block, something like this:
```javascript
client.on('message', (topic, message) => {
  try {
    let incoming_object = JSON.parse(message.toString());
  } catch (e) {
    console.log('Error parsing JSON message');
  }
}
```

**Comment by ZeroSoulEater** [comment]
I don't know why this does work but I did the folling:

`client.on('message', function (topic, message) {
    let m = JSON.parse(JSON.parse(message));}`

**Comment by daithinh2401** [comment]
@developerX Hi, I'm having the same issue. Did you figure out the solution ?

**Comment by developerX** [comment]
@daithinh2401 It has been a while since I worked on this particular project. From reading the comments above I was able to pass in a string separated by commas and just used an `str.split()` to get the values I needed. I hope that helps!
