### ISSUE TITLE
weapp bug

### ISSUE THREAD

**Issue by charlesluo2014** [mqttjs/MQTT.js#729]
wss://api.xxx.com:80 不在以下 socket 合法域名列表中，请参考文档：https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-request.html

because of the mqtt lib add the port to the url,but wechat not allow the port in the url

**Comment by 4rzael** [comment]
You may want to use the protocol `wx` (weapp websocket) or `wxs` (secured weapp websocket) instead of `wss`
