### ISSUE TITLE
MQTT Store doesn't return an error to the publish function if the Store fails to insert packets in the queue

### ISSUE THREAD

**Issue by v-divya110** [mqttjs/MQTT.js#731]
I was trying to use the MQTT level store for a persistent store for all QoS 1, 2 and retained messages. I realised that the callback is undefined in case of the QoS being 2. In this case, the API _sendPacket does not have anything to callback to and the error remains within the scope of this function. 
Here is the code snippet for publish and the switch case for the qos is what I mentioned about.
```js
MqttClient.prototype.publish = function (topic, message, opts, callback) {
  var packet

  // .publish(topic, payload, cb);
  if (typeof opts === 'function') {
    callback = opts
    opts = null
  }

  // default opts
  var defaultOpts = {qos: 0, retain: false, dup: false}
  opts = xtend(defaultOpts, opts)

  if (this._checkDisconnecting(callback)) {
    return this
  }

  packet = {
    cmd: 'publish',
    topic: topic,
    payload: message,
    qos: opts.qos,
    retain: opts.retain,
    messageId: this._nextId(),
    dup: opts.dup
  }

  switch (opts.qos) {
    case 1:
    case 2:

      // Add to callbacks
      this.outgoing[packet.messageId] = callback || nop
      this._sendPacket(packet)
      break
    default:
      this._sendPacket(packet, callback)
      break
  }

  return this
}
MqttClient.prototype._sendPacket = function (packet, cb) {
  console.log(cb);
  if (!this.connected) {
    if (((packet.qos || 0) === 0 && this.queueQoSZero) || packet.cmd !== 'publish') {
      this.queue.push({ packet: packet, cb: cb })
    } else if (packet.qos > 0) {
      this.outgoingStore.put(packet, function (err) {
        if (err) {
          return cb && cb(err)
        }
      })
    } else if (cb) {
      cb(new Error('No connection to broker'))
    }
    return
  }
```

I wonder why this is done. Why couldn't we send the callback in all the cases to _sendPacket? Isn't publish supposed to fail if the Store manager cannot put the messages in the store ? 

I made a minor work around in the _sendPacket API for receiving the errors in the publish API. I set the callback before returning it.

```js
MqttClient.prototype._sendPacket = function (packet, cb) {
  console.log(cb);
  if (!this.connected) {
    if (((packet.qos || 0) === 0 && this.queueQoSZero) || packet.cmd !== 'publish') {
      this.queue.push({ packet: packet, cb: cb })
    } else if (packet.qos > 0) {
      var that = this;
      this.outgoingStore.put(packet, function (err) {
        if (err) {
          cb = that.outgoing[packet.messageId];
          return cb && cb(err)
        }
      })
    } else if (cb) {
      cb(new Error('No connection to broker'))
    }

    return
  }
```

**Comment by mcollina** [comment]
Good spot, would you mind sending a PR with a unit test?

**Comment by v-divya110** [comment]
I don't think I would be able to simulate a unit test because the error only arises when an external store is used. For instance, mqtt-level-store. In your case there is a Store which never returns an error in Store.put() so I'm not sure how to go about the unit test.

**Comment by mcollina** [comment]
You can create a `new mqtt.Store()` and override the `put` method in there.

**Comment by v-divya110** [comment]
So I can use mqtt-level-store in the test case here?

**Comment by mcollina** [comment]
no. Just:

```js
const store = new mqtt.Store()
store.put = function (packet, cb) {
  process.nextTick(cb, new Error('kaboom'))
}
```

**Comment by v-divya110** [comment]
okay! Thanks :+1:

**Comment by v-divya110** [comment]
I have added the test case and submitted a new pull request for this issue

**Comment by Maxattax97** [comment]
For reference the PR is #732. I have also ran into this issue so I'm hoping this is pulled soon to clean it up.
