### ISSUE TITLE
Empty password got rejected connection without even try to authenticate with the server

### ISSUE THREAD

**Issue by michaeljota** [mqttjs/MQTT.js#739]
Some server configuration allows to set an user without password, however if you try to connect to such server with MQTT.js the connection throws as rejected, but the request never leaves the client. 

```console
Error: Connection refused: Bad username or password
    at MqttClient._handleConnack ()
    at MqttClient._handlePacket ()
    at process ()
    at Writable.writable._write ()
    at doWrite ()
    at writeOrBuffer ()
    at Writable.write ()
    at Duplexify.ondata ()
    at Duplexify.EventEmitter.emit ()
    at addChunk ()
```

Options:
```js
        clientId: 'MAD' + parseInt(Math.random() * 100, 10),
        username: 'legitUsername',
```

**Comment by mcollina** [comment]
Have you been able to debug why this is happening? Can you send a PR to fix it?

**Comment by michaeljota** [comment]
I will try to debug, and see if I can fix it. :).

**Comment by michaeljota** [comment]
Hi! I tried to debug, but I don't why this is happening. I'm sorry.

**Comment by RangerMauve** [comment]
How do you know for sure that the request doesn't leave the client?

**Comment by michaeljota** [comment]
I have a interceptor in the server and it does not get through.

**Comment by kasvith** [comment]
happens to me also
