### ISSUE TITLE
Inconsistency with semicolons in Typescript declaration files

### ISSUE THREAD

**Issue by TechnicalSoup** [mqttjs/MQTT.js#740]
I've noticed that the general coding style for this project is to omit optional semicolons, however I've noticed that some of the Typescript declaration files have semicolons in a few locations.

An example of this from the types.d.ts file is shown below
```javascript
 will?: {
    topic: string;
    payload: Buffer;
    qos?: QoS;
    retain?: boolean;
  }
```

In the majority of Typescript declaration files I've looked at the semicolons are not omitted (seems to be less prevalent in Typescript code in general). I'm happy to create a PR to correct this to keep it consistent across the file, and project in general but thought I'd raise an issue first to see if there was a preference to steer the declaration files to include semicolons.

**Comment by mcollina** [comment]
Go ahead and propose a change that make sense. We follow standard in the rest of the codebase.

Is there a linter to catch these issues?

**Comment by 4rzael** [comment]
I haven't tried, but [tslint](https://palantir.github.io/tslint/) can probably be used for that, with the [semicolon](https://palantir.github.io/tslint/rules/semicolon/) rule

**Comment by TechnicalSoup** [comment]
Yep - I've used tslint in the past and it has a semicolon rule that can applied as `always` where semicolons must be used and `never` where they must only be used when necessary.

I'm happy to propose changes to the declaration files, and even create a tslint.json file with some rules in it if you are looking to enforce a coding style for Typescript aspects of the project. There is a github repo that attempts to mirror the javascript coding standard in a tslint [here](https://github.com/blakeembrey/tslint-config-standard)

My personal preference for Typescript code is to include the semicolons as it seems to be more common when browsing through example code and other repos, however as the rest of this project omits them in the javascript code that may seems a little odd. 


If @mcollina has a preference I'm happy to head in that direction.

**Comment by sublimator** [comment]
I'd say it is actually less common to have semicolons in TypeScript code,
though that might just be my preference speaking :) The fact that I don't
even know clearly speaks to the invisibility/redundancy of them. Given the
REQUIRED compilation step, it's pretty safe to omit semicolons in code, as
the compiler will pick up the few rare cases when they are actually
required ( wrapping expressions in parentheses )

I'd vote for consistently none :)

**Comment by mcollina** [comment]
I abstain: I’m very unfamiliar with Typescript.

**Comment by sublimator** [comment]
I don't really care either way :)

**Comment by TechnicalSoup** [comment]
Thanks for the input @sublimator. 

As the rest of the code base omits semicolons it probably makes more sense to have them omitted from these declaration files too.

I'll get a PR going to address this.

**Comment by TechnicalSoup** [comment]
Appears there is already TSLint rules setup to catch these, however from a bit of digging the linter's approach to interfaces seems to be inconsistent.

I've created a PR to remove the semicolons that I spotted earlier, and testing the change at my end to make sure the TS declarations behaved as expected (VSCode 1.19.1 and TS 2.6.2). All looked good.
