### ISSUE TITLE
Does the client emit a `connect` event? If so, where?

### ISSUE THREAD

**Issue by RickCarlino** [mqttjs/MQTT.js#743]
I am debugging a very application specific bug relating to re-connection attempts and would like to use the `connect` event for debugging.

The [documentation](https://github.com/mqttjs/MQTT.js#event-connect) states that the event is

 > Emitted on successful (re)connection

however, I can't seem to get my `connect` event handler to fire in a browser while debugging a websocket connection.

My questions are:

1. Does the `connect` event fire for WebSocket client connections?
2. If it does, where in the source is the handler triggered?

I spent some time looking through the source but was unable to find any client-side code that emits a `connect` event. The only events that appear to trigger are `reconnect`, `close`, `offline`, `message`, `packetsend`, `packetreceive`.

Thanks for all the great work on this library! We really appreciate it.

**Comment by RangerMauve** [comment]
Inside `_setupStream` we listen on various events and send [a connect packet](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L286) down the socket.

After the connection is verified, we [receive a connack packet](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L869) and emit the `connect` event on the client.

Could you show a minimal code sample of the `connect` not being emitted? Make sure to listen on the `error` event so you can catch any errors happening during connection.

**Comment by RickCarlino** [comment]
@RangerMauve Thanks! I was able to verify that the issue is indeed on my end.

**Comment by RangerMauve** [comment]
Glad I could help! :D
