### ISSUE TITLE
changing will message after connection

### ISSUE THREAD

**Issue by cordovapolymer** [mqttjs/MQTT.js#750]
Hi,
Is it possible to change the will message after the connection?
I want to have a login token inside of the will message, to handle "client offline" logic.

**Comment by mcollina** [comment]
no it is not possible.

**Comment by cordovapolymer** [comment]
I see, will message can be only set in [connect payload](docs.oasis-open.org/mqtt/mqtt/v5.0/csprd01/mqtt-v5.0-csprd01.html#_Toc489530091)
