### ISSUE TITLE
Bug in receiving retain

### ISSUE THREAD

**Issue by igor-d-deus** [mqttjs/MQTT.js#752]
It's strange but this library has some bugs in receiving retain with some words in topic or other reason.
I'm trying to subscribe to topic like 'gateway/+/out/structure/+/devices/+/status' and I'm not receiving anything. When I subscribe from console mosquito client - all messages. When with nodejs mqtt lib - nothing!

**Comment by mcollina** [comment]
Can you provide a script and instructions to reproduce?

**Comment by igor-d-deus** [comment]
Can't reproduce it anywhere except production server. But after updating to latest release and switching QoS of subscription to 0 it began work. May be it's not a bug or it was fixed somehow. But I tested 250 000 topics with retain at local server and none of msg was lost.

**Comment by igor-d-deus** [comment]
I'll close this issue because it impossible to reproduce.
