### ISSUE TITLE
Call to 'connect' just hangs

### ISSUE THREAD

**Issue by BorisBrock** [mqttjs/MQTT.js#753]
I'm trying to get the following example code to work:

```js
var mqtt = require('mqtt')
var client  = mqtt.connect('tcp://192.168.178.32:1883')

client.on('connect', function () {
  client.publish('presence', 'Hello mqtt')
})
```

This should connect to an up-to-date Mosquitto server running on my Raspberry Pi. But all that happens is that the code hangs. No errors, no nothing. The server itself is fully functional. I tested that with an Android app.

What could cause this behavior?

**Comment by mcollina** [comment]
does that need a username/password combination?
can the raspberrypi connect to `192.168.178.32`?

**Comment by VanKurt** [comment]
Hi,
192.168.178.32 is the address of the Raspberry running the MQTT Server (Mosquitto). My Android App can connect to the Raspberry Pi at this address just fine and publish/subscribe topics. So on that end everything seems fine.

Also the MQTT Server requires no username/password (since it is only running in my home network).

**Comment by mcollina** [comment]
I have no idea. You are probably better off checking with wireshark or node inspector what's going on.
If you find what the problem is, feel free to send a PR.

**Comment by cdupont** [comment]
I have the same problem. connect hangs until timeout.
I have a Mosquito server running, it displays:
```
1554374308: New connection from 127.0.0.1 on port 6883.
1554374308: New client connected from 127.0.0.1 as mqttjs_53c8c6e7 (c1, k60).
```
But nothing more. It seems that mqtt.js doesn't receive the CONN ACK.

**Comment by Mrc0113** [comment]
I also ran into this problem. The problem seems to be including `tcp://` in the URL. If I removed that I was able to connect successfully.

**Comment by Mrc0113** [comment]
@mcollina - this feels like it should be a quick fix, but not being a node developer I don't see where to quickly address this. Any chance you can take a quick stab at it when you have a few minutes? This was almost a deal breaker to using this library over the weekend with a few different dev teams at a hackathon when I randomly came across the solution of removing `tcp://`
