### ISSUE TITLE
Subscribing to retained topic with wildcard

### ISSUE THREAD

**Issue by teemupiiroinenwirepas** [mqttjs/MQTT.js#755]
Hello

Is there something special while subscribing to retained topic with wild card? I'm publishing data into topic with QoS1 and retained flag set on. If I subscribe to the topic before I publish the data, I get the message, but if I subscribe later, I don't get the message. Everything works just fine if I subscribe to the exact topic name.

I have tried with "#" and "+" wildcards, but the results is the same.

```js
subscribe("topic/25e78987-bb72-4781-9a82-0093fa93f3d3");  // Works
subscribe("topic/+");  // Does not work
subscribe("topic/#");  // Does not work
```

Br,
Teemu

**Comment by mcollina** [comment]
Which broker are you using?
You should be getting the messages - it's likely a broker config issue.

**Comment by teemupiiroinenwirepas** [comment]
Yes, you are correct. This seems to be an issue with RabbitMQ and MQTT plugin.

https://github.com/rabbitmq/rabbitmq-mqtt/issues/154

Thanks
