### ISSUE TITLE
How to unbind event handlers, for example: on ("message", callback)

### ISSUE THREAD

**Issue by caflulu** [mqttjs/MQTT.js#756]

**Comment by mcollina** [comment]
Check out the node.js docs, the mqtt instance is an event emitter.

**Comment by caflulu** [comment]
I agree with you somehow, probably,  I had somthing wrong with my question. My actually question is that when I want to use the same topic in other pages, the callback of this page in the handler,Which I want to detroy it. So I can do other things in the other pages. So in some way how to unbind the old event handler.

**Comment by mcollina** [comment]
Your question is definitely not clear.

**Comment by addedjacky** [comment]
How can i unbind event handlers, like off('message') .

**Comment by johnnytolengo** [comment]
interesting issue.. seems "unbind" to not exists.
will be fine if when you call the event it returns the pointer to it like:
var myevent = client.on('message', callback..);
and later unbind the listener with some:
myevent.off()
With this funcionality we will be able to recall the 'message' event without returning multiple times the same callback.
Any idea how to do it?

**Comment by alecdwm** [comment]
As per the [EventEmitter](https://nodejs.org/api/events.html#events_emitter_off_eventname_listener) api:

```javascript
const callback = (topic, message) => console.log(topic, message)

// add handler
client.on('message', callback)

// remove handler
client.off('message', callback)
```

**Comment by fspegni** [comment]
It seems that the client object does not respect the EventEmitter api:

`client.on('message', callback)` works fine, but `client.off(...)` raises an error saying that `client.off` is undefined. Why is that?

**Comment by robertsLando** [comment]
https://nodejs.dev/en/learn/the-nodejs-event-emitter/
