### ISSUE TITLE
After the net is broken, it is reconnected, but there is no data.

### ISSUE THREAD

**Issue by RelaxLiu** [mqttjs/MQTT.js#757]
After the net is broken, it is reconnected, but there is no data.

publish-subscribe

Subscribe to success

Data reception success

Off the net

Link offline

Reopen the network

After that, the link has been successful. Close, offlin, connection is successful, close, offline has been circulating, neither resubscribe nor cancel subscription.

Want to ask what you need to set up to continue the data transfer

Mqttjs JavaScript used
![image](https://user-images.githubusercontent.com/16301089/35606462-4cf8996a-068a-11e8-9e37-ee637005755e.png)

**Comment by mcollina** [comment]
Unfortunately, this might be an issue with your broker. If you want to send a PR, I’m very happy to review.

**Comment by RelaxLiu** [comment]
@mcollina Thank you for your reply
I want to know what is the reconnection mechanism of mqtt. At the beginning, I have already created a subscription and broken network. Do I need to cancel the previous subscription when I want to connect to the Internet, or do I have other ways to deal with it?
