### ISSUE TITLE
client.on('message', callback) keeps appending data when inside a function.

### ISSUE THREAD

**Issue by ayushsharma82** [mqttjs/MQTT.js#760]
So I have an Express app , What i really wanted to do was Publish a message and then Retrieve a reply in that same function.I go to http://localhost/mqtt , it publishes a message to broker and receives the reply from other client , but on repeated attempts, message keeps getting Appended.   So here is example the code for better understanding:

```
app.get('/mqtt', function(req, res){
	client.subscribe('test/in',{qos: 2});
 	client.publish('test/out', 'Hello from frontend!',{qos: 2});
 	
 	client.on('message', function (topic, message) {
		// message is Buffer
		console.log(message.toString());
		client.unsubscribe('test/in');
	});
	 
	res.end("MQTT Sent! ");
  });
```

The Output would be : 
For 1st Time : Hello from Backend!
For 2nd Time : Hello from Backend! Hello from Backend!
and so on... it keeps appending data from the first received message. how can i clear this buffer?

What could be causing this?

**Comment by ayushsharma82** [comment]
UPDATE: On further Studying the Issue, I Got to know that it is Duplicating the message rather than Appending. Example: if i use the function 5 times, then the recent Message gets duplicated 5 times.

**Comment by erichonkanen** [comment]
I may be encountering the same problem, @ayushsharma82 did you have any more insight into this?

**Comment by ayushsharma82** [comment]
@erichonkanen  The Library was never intended to be wrapped inside a function. The Solution was to create a array of pending tasks and then listen for 'on' event outside function and execute queue as the messages come.
