### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by reejinbouk** [mqttjs/MQTT.js#762]
Hi,
Can't find connect method for typescript with ISecureClientOptions.
How can I use typescript to connect with SSL cert?
Thank you.

**Comment by mcollina** [comment]
Probably we have a bug in our typings. Would you like to send a PR?

**Comment by reejinbouk** [comment]
I'm trying to connect using node.js as in https://github.com/mqttjs/MQTT.js/tree/master/examples/tls%20client
I've used certificates for my site, but get this error:

`Error: Unknown protocol for secure connection: "ssl"!`

**Comment by RangerMauve** [comment]
@reejinbouk Try the `mqtts` protocol instead in your URL

**Comment by mbrandau** [comment]
Looks like this can be closed too @mcollina
