### ISSUE TITLE
Call message callbacks upon disconnection / no more reconnections

### ISSUE THREAD

**Issue by periclesroalves** [mqttjs/MQTT.js#765]
I noticed that current message callbacks (`MqttClient.outgoing`) are not called with an error when connection suddenly drops. I guess this is expected as the library may reconnect automatically and the ack for those messages can still come back after reconnection, right?

However, these callbacks are not called with an error even when reconnection attempts are exhausted (in this case, to reconnect again the user would have to explicitly call `MqttClient.reconnect()`, effectively reinstantiating the stores). Would this be an accepted/desired behavior to have these callbacks called when reconnections will no longer be attempted by the library?

If not, can we at least call them with an error when the user calls `MqttClient.end()`, as this effectively triggers a cleanup and closes the store?

**Comment by mcollina** [comment]
Oh, good spot, would you or @pierreca be able to help with a PR? Thansks!

**Comment by pierreca** [comment]
@anthonyvercolano is going to take a look at this, thanks!

**Comment by anthonyvercolano** [comment]
Looking at this problem a bit.  My thinking is that code such as the following should probably be inserted after line 725 in client.js (at the beginning of  _cleanup).

  if (this.outgoing) {
    this.outgoing.forEach((cb) => {
      cb(new Error('Connection closed'))
    })
  }

I'm not trying to make this a pull request.  Just hoping to hear an opinion as to whether I need to be doing a lot more work to maintain the other various structures holding information related to packets such as the various stores

**Comment by pierreca** [comment]
The proposed fix for this is in #787
