### ISSUE TITLE
'end' event

### ISSUE THREAD

**Issue by gautaz** [mqttjs/MQTT.js#767]
Hello,

I was wondering if you (the maintainers) would consider adding an `end` event?

The use case would be multiple parts of some code using the same MQTT connection. Once the connection is asked to `end()` and it actually ends (with or without an error), this event would tell all listeners that the connection has effectively ended and is no longer usable.  The `end` event could be emitted just after the `end()` callback is called.

It is currently difficult to rely on the `close` event which is emitted directly by the underlying communication stream. The `close` event can be emitted multiple times and AFAIK listeners have to check the `disconnecting` attribute in order to tell if the connection is really ending.
It is even more difficult if the connection was never successful, in this particular case, no `close` event  will be emitted after an `end()` call.

I am interested by any proposal on this particular subject and I can send a PR if there is an agreement on how to handle this :-).

**Comment by mcollina** [comment]
Definitely, would you like to send a PR with a proposal?

**Comment by gautaz** [comment]
I am close to send the PR but since I have added additional test cases, I was able to reproduce a bug on my last PR (#763).

Do you want me to fix this in the same PR or do you want me to put this on a separate issue?

**Comment by mcollina** [comment]
Send another PR!

**Comment by gautaz** [comment]
Sorry for the delay, the bug is fixed by #770 and the `end` event is added by #771.

**Comment by gautaz** [comment]
Hello, this issue went completely off my radar.
As the PR were merged, I guess I can close this now, sorry for the delay.
