### ISSUE TITLE
Large Payload issue. offline->close->reconnect infinite loop

### ISSUE THREAD

**Issue by enVolt** [mqttjs/MQTT.js#768]
In case the message payload is very large (> 64 kb), Publish method, doesn't return the callback with a failure. 

I'm getting `offline`, `close` & `reconnect` event in order as an inifinite loop. 

Here is the code snippet -

```js
let config = {host, port, username, password};
let client = mqtt.connect(config);

client.on("connect", () => {
    logger.info("[mqtt] Connected");
});

let events = ["reconnect", "close", "offline"];

events.forEach((event) => {
    client.on(event, () => logger.info("[mqtt] Event", event));
});

client.on("error", (error) => {
    logger.error("[mqtt] Error Event", error);
});

let publishOptions = {
    qos: 1,
    retain: true
};

client.publish(channel, aVeryLargeBody, publishOptions, (err) => {
    if (err) { logger.error(err, "[mqtt] [publish] Error Occurred"); }
    logger.info("Published");
});
```

The scenario can be replicated for any value of `aVeryLargeBody`, where size is greater than 64 KB.

**Comment by mcollina** [comment]
which broker are you using?

Can you send a PR to fix this bug?

**Comment by enVolt** [comment]
Broken is emqttd. 

For now, I've put a check on the size of the message which is being published. I might have missed the point, that it could be a broker specific thing. 

As far as I'm able to understand the code, reconnect loop is being handled at client.js#L208, and publish method will not get to know that. I guess the expected behaviour here is that in case the client gets a disconnect (or broken), it will eventually connect and the message will be published.

**Comment by mcollina** [comment]
Can you please check with Mosquitto, too?

**Comment by enVolt** [comment]
It's part of emqtt default config ([source](http://emqtt.io/docs/v2/config.html#maximum-packet-size))

**Comment by mitsos1os** [comment]
@enVolt Unfortunately this is not the case for us. We are using **mosca** broker for  our MQTT service and the thing is that the payloads **are sent when a normal connectivity exists**, but whenever a **lower quality connection is available, not even partial data arrive of the bigger payload** *(I am checking this by attaching a data listener on the raw underlying TCP socket of the MQTT client server side)*
