### ISSUE TITLE
Controlling inflight message count?

### ISSUE THREAD

**Issue by Eric24** [mqttjs/MQTT.js#773]
Is it possible for the client to control the inbound inflight message count (i.e. what RabbitMQ's MQTT plugin calls prefetch-count or what mosquito calls max_inflight_messages)? Of course, this only applies to QoS 1 or 2.

**Comment by mcollina** [comment]
This would be a very nice feature, would you like to send a PR?

**Comment by Eric24** [comment]
@mcollina : Maybe, but I'm not exactly sure where to start. It's my understanding that the broker will keep sending messages until its internal prefetch/inflight count is reached. How can the client "control" this? There does not appear to be any standardized way to override the server's setting on this during connect or subscribe. If the server can't be overridden, how can the client throttle messages?

**Comment by mcollina** [comment]
That is indeed not possible. Closing.
