### ISSUE TITLE
Unable to establish connection with MQTT Client

### ISSUE THREAD

**Issue by RameshRM** [mqttjs/MQTT.js#774]
`TypeError: nextTick is not a function`

Stack Trace : 

mqtt/lib/client.js:37:2
mqtt/lib/client.js:286:3
mqtt/lib/client.js:227

FYI, This is used along with `aws iot` aws-iot-device-sdk/device/index.js:639

Suddenly hit with this issue right b4 launch preparation, can someone look @ this earliest

Thx

**Comment by mcollina** [comment]
Are you using yarn or package-lock, or webpack? Can you please update your dependencies?
This should not be happening and it is a package manager/bundling issue.

**Comment by RameshRM** [comment]
i am using plain simple `npm i`

**Comment by RameshRM** [comment]
there is a package-lock.json, should i remove the lock and do `npm install ` ?

**Comment by mcollina** [comment]
remove it, remove node_modules, and reinstall.

**Comment by RameshRM** [comment]
no luck, same error

**Comment by RameshRM** [comment]
I am running my code under `setImmeidiate(tryEstablishClient());`

**Comment by mcollina** [comment]
I would recommend you to open this issue against aws-iot-device-sdk. AWS has the resource to track down this problem and help you, while this is a community maintained project.
This is not a bug in this library.

**Comment by coloz** [comment]
it,s same error,TypeError: nextTick is not a function
i use `npm update` to update mqtt,then get the error

**Comment by RameshRM** [comment]
It is the release of `mqtt-packet^5.5.0` causing this issue. I have downgraded to `5.4.0` and that works,

@mcollina Can you check ?

**Comment by RameshRM** [comment]
@mcollina Pls let me know , what would be causing this i can check and see if i can send a `pr`

**Comment by mcollina** [comment]
it’s a bug between webpack and yarn, they are caching too much. There is
nothing that is not working here, and I have yet to see a full way to
reproduce.
The “problem” originates from readable-stream. I’ve update mqtt-packet to
help.
Il giorno mer 7 mar 2018 alle 07:01 Ramesh Mahadevan <
notifications@github.com> ha scritto:

**Comment by aravind08** [comment]
test
