### ISSUE TITLE
Servers option does not allow different protocol than brokerURL.

### ISSUE THREAD

**Issue by wcatron** [mqttjs/MQTT.js#775]
When connecting using the servers option the protocol can't be set. Need to add it as an option to the `IClientOptions` interface so that this works:
```
var client = connect(null, {
    username: 'Username',
    password: accessToken,
    reconnectPeriod: 1000 * 5,
    servers:[{
        host: getMQTTBrokerHostname(),
        port: 8883,
        protocol: 'wss'
    },{
        host: getMQTTBrokerHostname(),
        port: 1884,
        protocol: 'ws'
    }]
})
```

`opts.protocol = opts.servers[client._reconnectCount].protocol` Should just need to add this to line 129 of the `lib/connect/index.js` file. I can create a pull request if this proposal seems reasonable. My goal for this functionality is to use a secure server but fall back to insecure if need be.

**Comment by mcollina** [comment]
You have investigated the issue quite well the issue. Would you like to send a PR?
