### ISSUE TITLE
Incoming message throttling (Qos 1)

### ISSUE THREAD

**Issue by Eric24** [mqttjs/MQTT.js#776]
I have a client that appears to be receiving messages much faster than I would expect. I'm basing my expectation on my understanding of this code:
```
      // emit the message event
      this.emit('message', topic, message, packet)
      this.handleMessage(packet, function (err) {
        if (err) {
          return done && done(err)
        }
        // send 'puback' if the above 'handleMessage' method executed
        // successfully.
        that._sendPacket({cmd: 'puback', messageId: mid}, done)
      })
```

I'm not overriding handleMessage--I'm just using the event listener. It's my understanding that each event listener (although I have only one listening for the 'message' event) is called synchronously, so that 'puback' is not sent until the listener completes. If so, then I would expect no more than 10 (per the server's "prefetch" configuration) messages to be offered at a time, essentially being "throttled" by the speed at which my listener completes. But instead, I'm seeing 50+ messages per second, causing the browser to become unresponsive at 100% CPU usage.

1. Is my understanding of the message/puback flow correct?
2. Would it be "better" in some way to override handleMessage rather than use the event listener?
3. Any thoughts on what I'm observing?
4. Any thoughts on how I might troubleshoot this?

**Comment by mcollina** [comment]
If you want throttling you will have to override `handleMessage`.

**Comment by Eric24** [comment]
@mcollina - Just so I'm sure I understand, does that mean that all messages are immediately puback'ed, independent of my event listener? If so, is there an example somewhere of using handleMessage in this way? None of my searching turned up anything helpful.

**Comment by mcollina** [comment]
@Eric24 they are puback'ed after all the synchronous event listeners are executed. If you want to delay or wait for some async operation to finish, you need to specificy `handleMessage`  and call the passed callback when you are done.

**Comment by Eric24** [comment]
OK. Based on that, I don't think I need to do anything here. There are no async operations in my on-message listener, so the existing puback sequence seems like it will do the job.
