### ISSUE TITLE
Chrome connect mqtt server err

### ISSUE THREAD

**Issue by shaocongcong** [mqttjs/MQTT.js#777]
when i use chrome anerror has occured on this page.
"WebSocket connection to 'ws://localhost:9800/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received"
mac safari is ok! why?

**Comment by mcollina** [comment]
I think you are connecting from a https page.

**Comment by shaocongcong** [comment]
Thanks for your quick response.  I use http connect server!

**Comment by shaocongcong** [comment]
All the problems have been solved

The idea is to send 'mqtt' as default subprotocol and 'mqttv3.1'if in the mqtt.connect options for MQTT 3.1 are passed:

{
  protocolId: 'MQIsdp',
  protocolVersion: 3
}
