### ISSUE TITLE
What happens to messages published on a channel when there are no subscribers?  Even with QoS 1 and 2.  Is it stored somewhere until there is a new client connected?

### ISSUE THREAD

**Issue by harishydav** [mqttjs/MQTT.js#778]

**Comment by dushyantbangal** [comment]
The messages are stored only if you have the the `retain:true` flag.
Your publisher does not directly send the messages to the subscribers.

Publisher communicates with the broker. So the publisher doesn't really know how many subscribers exist.

**Comment by abcd-ca** [comment]
further, `qos` is about confirmation that messages are received by broker from client or by subscriber from broker. `retain` is about whether or not broker keeps the message

**Comment by KrishnaPG** [comment]
If you want the data to be stored till a client consumes it, use `unclean` sessions with `QoS > 0`. On the client set `clean:false` option while connecting.
