### ISSUE TITLE
MQTT 5 Support

### ISSUE THREAD

**Issue by Domvel** [mqttjs/MQTT.js#780]
Does this library already support the mqtt version 5?
I'm confused about the protocolVersion of 4 in the sources.
Does version 4 ever exists? I thought they jumped to 5 because of an issue to have a integer version in header. Is version 4 == 3.x ?

**Comment by mcollina** [comment]
4 is 3.1.1.

As stated in https://github.com/mqttjs/MQTT.js/issues/651, I have no time to contribute this. I'd be very supported if anybody wanted to work on it.
