### ISSUE TITLE
On internet disconnect client loops: transformWsUrl -> close -> reconnect

### ISSUE THREAD

**Issue by aalibasic** [mqttjs/MQTT.js#781]
I am have an issue where after disconnecting from the internet for several minutes, then reconnecting mqtt gets stuck in a "close" then "reconnect" loop. The transformWsUrl method keeps getting hit and a new signed url assigned.

This only happens when:
1. Resubscribe: true
2. I have several subscriptions

I am using aws with a signed url.

Does anyone have any suggestion on how I can debug what is happening?

**Comment by RangerMauve** [comment]
Just to confirm, when you reconnect to the internet, you keep looping?
What's your reconnect interval?

**Comment by aalibasic** [comment]
@RangerMauve - yes when i reconnect to the internet the mqtt client keeps hitting the transformWsUrl -> then closing -> then reconnecting.

AWS show these logs:
`2018-02-28 20:00:43.111 TRACEID:1PRINCIPALID:A [ERROR] EVENT:MQTTClient Subscribe TOPICNAME:/this/testing/bro MESSAGE:Subscribe Status: CLIENT_ERROR`

**Comment by RangerMauve** [comment]
Does your MQTT server have more information in it's logs? It looks like you're connecting successfully, but the broker is throwing an error when subscribing. Maybe the broker can give more information on why the subscribes are a "client error"

**Comment by aalibasic** [comment]
@RangerMauve I filed a ticket with aws as this seems to only happen when using aws iot as a broker. Using an aws ec2 instance with mosquito works fine.

Have you guys tested the scenario where:
1. Using aws iot
2. Subscribe to several topics
3. Ensure resubscribe is enabled
4. You disconnect from the internet until the transformWsUrl function gets called
5. From transformWsUrl function return a new signed url for aws iot
6. Reconnect the internet connection
7. Loop begins

**Comment by RangerMauve** [comment]
What does your code look like? Do you have error listeners everywhere?
Sadly when a broker has an error they send a pretty opaque status code and break the connection. "CLIENT_ERROR" is the best we can do because that's all the server can provide us with.
I think MQTT v5 is working towards improving that, but I don't think there's much out there that supports v5 yet.

**Comment by aalibasic** [comment]
@RangerMauve - it does not hit the error call back it just seems to cycle : close, reconnect, close ....

**Comment by RangerMauve** [comment]
I think I get what you want.
When we setup a new stream, we don't relay the "error" events to the MQTT client, we just relay the "close" event.

I think a PR that changes [this line](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L277) to instead pass the "error" event on to the client would be welcome.

That way you can get actual errors for when this happens to help diagnose problems.

**Comment by aalibasic** [comment]
That would be awesome!

**Comment by aalibasic** [comment]
Turns out my issue was with aws iot. They only allow 8 subscriptions in a batch.

**Comment by RangerMauve** [comment]
Glad you figured it out, I'll keep that in mind next time somebody has issues with subscriptions. :P

Would you mind if I closed this issue for now?

**Comment by aalibasic** [comment]
Works for me, thanks for the help!

**Comment by hoIIer** [comment]
Hello @aalibasic, I'm getting this exact same behavior where after a certain idle timeout (e.g. browser tab lost focus), the client starts trying to reconnect indefinitely. On the AWS side all I see is `CLIENT_ERROR`.

How were you able to resolve this?

**Comment by hoIIer** [comment]
https://repost.aws/questions/QU_Gid6CMHRay7iv-Php3XfQ
