### ISSUE TITLE
refactoring for extendable class in the future

### ISSUE THREAD

**Issue by dkebler** [mqttjs/MQTT.js#783]
I want to build an extended es6 class but because of the way that you defined `Client`  with it taking an **already connected** socket `streamBuilder` instead of having a connect method(function) I can't extend it in a normal ES6 way.   I ended up doing merge with `this` after the call to connect.  As a result I can't  extend any of the methods in a normal way using `super.` either and ended up writing function that does both .  For example I can't extend subscribe without having to save a copy first unless I want to use another method name which  kinda defeats the purpose of an extended class.

Anyway maybe you all should consider a extendible structure with a `connect` method instead of a `StreamBuilder` argument when you make the jump to the next breaking major version or offer a complete refactor in an es6 class version.  IMHO ES6 class sugar is easier to read and work with.

I have a working solution inelegant as it is so this is really just a comment/suggestion at this time.
Thx for this mqtt project. It of course saved me a lot of time even as it is.

```javascript
import { connect } from 'async-mqtt'
import merge from 'lodash.merge'
import btc from 'better-try-catch'
import isArray from 'lodash.isarray'
import logger from '@uci/logger'

let log = {}


export default class Client {
  constructor (opts={}) {
    this.id = opts.id || opts.name || 'mqtt:'+ new Date().getTime()
    this.url = opts.url
    // subscription topics can be string of commna delimited or array of strings see object see mqtt.js docs
    this.topics = isArray(opts.topics) ? opts.topic : (opts.topics.split(',') || ['default'])
    this.opts = opts.connect || {}  // see options for new mqtt.Client
    // self bindings
    this.connect = this.connect.bind(this)
  }

  async connect () {

    return new Promise( (resolve,reject) => {

      // connect returns connected mqtt client instance so merge it to class
      // console.log(this)
      let mqtt = connect(this.url,this.opts)
      this._extend(mqtt,'subscribe,unsubscribe')
      this._log()
      this._listen()

      this.on('reconnect', () => {
        log.info('mqtt client reconnected to broker' )
        this.subscribe(this.topics)
      })

      this.once('connect', () => {
        this.subscribe(this.topics)
        log.info('mqtt client connected to broker' )
        resolve(`mqtt client connected to broker at ${this._client.options.host}`)
      })

      this.on('error', err => {
        log.fatal({err:err},'connection error to broker' )
        console.log('connection error',err.code)
        reject(err)
      })

    }) //end promise

  }

  async subscribe(topic,options={}) {
    if (options.pub) {
      if (typeof topic==='string') topic = topic.split(',')
      this.topics=union(this.topics,topic)
    }
    this._subscribe(topic,options)
  }

  async unsubscribe(topic,options={}) {
    if (!options.pub) {
      if (typeof topic==='string') topic = topic.split(',')
      this.topics=xor(this.topics,topic)
    }
    this._unsubscribe(topic)
  }
.... more methods
}
```
the extender function I had to write

```javascript
  _extend (obj, funcs) {
    let temp = {}
    funcs = funcs.split(',')
    funcs.forEach(func => {
      temp[func] = this[func]
    })
    merge(this,obj)
    funcs.forEach(func => {
      this['_'+func]=this[func]
      this[func] = temp[func]
    })
  }
```

an example using the above
```javascript
import Client from '../src/client'

// let mqtt = new Client({id:'example-mqtt-client', url:'tcp://trantor:1883', topics:'test1'})
let mqtt = new Client({id:'example-mqtt-client', connect:{host:'localhost', port:1883}, topics:'test1'})

;
(async () => {

  await mqtt.connect()
  await mqtt.send({cmd:'test', status:'I\'m good'})
  await mqtt.subscribe('test2',{pub:true})
  await mqtt.send({cmd:'test', status:'I\'m good'})
  await mqtt.unsubscribe('test2')
  await mqtt.send({cmd:'test', status:'I\'m good'})


})().catch(err => {
  console.error('FATAL: UNABLE TO START SYSTEM!\n',err)
})
```

**Comment by mcollina** [comment]
All the code in this repository runs _without babel_ in modern browsers and all Node.js LTS versions. That's a target. I'm very 👎 on using async await and other features that are not widely supported in all LTS lines of Node.js and modern browsers.
Updating Node.js on a raspberry Pi is not super easy, especially on old hardware.

That being said, I would love to see `mqtt.publish()` and others potentially returning a promise if no callback is passed through. If you want to work on a PR, please file one.

Why would you need to extend and override the methods? This is a MQTT client, and you would like to make a specialized MQTT client, specialized for what? I'm failing to understand the use case of being able to extend the client.

> I have a working solution inelegant as it is so this is really just a comment/suggestion at this time.
Thx for this mqtt project. It of course saved me a lot of time even as it is.

Instead of proposing a complete API redesign, you might want to help sorting out some of those 83 open issues, if you want to give back.
