### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by alduxvm** [mqttjs/MQTT.js#785]
I'm using browserify with mqtt, I followed the instructions on the readme file in order to make it... 

But when connecting to my broker, I'm getting this error in the console:

`WebSocket connection to 'ws://localhost:8083/' failed: Error during WebSocket handshake: Unexpected response code: 404` 

I tested my broker with other applications using WS and it works... Also, testing mqtt.js without browserify it connects to my broker with no issues. The problem comes when doing the browserify, any idea?

**Comment by RangerMauve** [comment]
I haven't seen that before, actually.

Could you post a code snippet of how you're connecting?

**Comment by alduxvm** [comment]
of course... I'm using EMQ os broker, the code I use to connect is:

```
var mqtt = require('mqtt')
var client  = mqtt.connect({
  host: 'localhost',
  port: 8083,
  username: 'sim',
  password: 'sim',
  clientid: 'test12345'
});

client.on('connect', function () {
  client.subscribe('device/#')
});

client.on('message', function (topic, message) {
  console.log(message.toString())
```

**Comment by alduxvm** [comment]
If I try the connection on the console only (no browser), I can connect changing the port from `8083` to `1883`

**Comment by RangerMauve** [comment]
Please note that the browser version only supports the websocket version of MQTT, make sure your broker supports websockets and that you're using the correct port for websockets.

You also need to set the `protocol` to `ws`

**Comment by alduxvm** [comment]
yes, I make sure that my broker works with ws, I tried my broker using this client: http://www.hivemq.com/demos/websocket-client/ and the connection works.

I added the protocol option but still no luck...

**Comment by RangerMauve** [comment]
Which version of MQTT.js are you using?
You're sure that 8083 is the correct port to use?
The error message you posted implies that the webserver you're trying to connect to isn't listening on WS

**Comment by spydmobile** [comment]
What ever happend to this, I have the exact same issue I have EMQ Broker that works with everything except this lib via websockets, gives the same error as OP.

**Comment by RangerMauve** [comment]
I'm not sure. Are you able to inspect what URLs other libraries are using to connect to the broker? Maybe it's the trailing `/` that's causing a problem.

**Comment by spydmobile** [comment]
:( ok, what client js mqtt did you switch to?

**Comment by spydmobile** [comment]
ok, I just rewrote using Paho, and it worked, but I would rather work to get mqttjs working...

**Comment by spydmobile** [comment]
@RangerMauve yes quite likely. this lib has no problems connecting to EMQ from the node side, only the browser side.

**Comment by tartavull** [comment]
I'm having a similar problem where nodes code works correctly but the browser  version doesn't.
   mqtt.js:8236 WebSocket connection to 'wss://mqtt.googleapis.com:8883/' failed: Connection closed      before receiving a handshake response

**Comment by RangerMauve** [comment]
@tartavull Try the steps described [here](https://github.com/emqx/emqx/issues/1563#issuecomment-381076108)

**Comment by tartavull** [comment]
It seems that Google Cloud IoT doesn't support MQTT over websockets [1].
Thank you @RangerMauve 

[1] https://stackoverflow.com/questions/49418312/is-it-possible-to-connect-to-the-google-iotcore-mqtt-bridge-via-javascript#comment86909751_49932371

**Comment by JackGujt** [comment]
confirm you host name, somethime you can add the string 'mqtt' to the end of you host,eg: 'wxs://xxx.xxxxxxx.xxx/mqtt'
