### ISSUE TITLE
Is there any way to subscribe to particular messages like /house/livingroom/device1 AND /house/bedroom/device2 and process them with separate event handlers using the same client? 

### ISSUE THREAD

**Issue by zakzag** [mqttjs/MQTT.js#790]
What I mean is, that one client can be subscribed to multiple events, but there's only one message event handler: 
`client.on("message", () => {
    // do something
});`

but as much as I understand it responses to all the subscriptions done by method subscribe. 
What if I want to respond to different messages with different callback? Should I put ifs into message event handler??
Should I instantiate a separate client for each topic?
It does not make any sense and waste of memory. Is there any better solution?

**Comment by RangerMauve** [comment]
What you want is to add a router over top of your MQTT client.

I'd suggest using my [mqtt-emitter](https://github.com/RangerMauve/mqtt-emitter) library to wrap over your client.

Create an MQTT client instance and an MQTTEmitter instance.
Relay events from the MQTT client to the MQTTEmitter

```javascript
client.on("message", function(topic, data){
  emitter.emit(topic, data);
});
```

Then you'll want to listen on new listeners in the MQTTEmitter and subscribe on MQTT topics

```javascript
emitter.onadd = function (topic) {
  client.subscribe("topic");
}
emitter.onremove = function (topic) {
  client.unsubscribe("topic");
}
```

Next you'll be able to just add listeners on the emitter and it'll automatically subscribe and unsubscribe them on the MQTT client.

```
emitter.on("/house/livingroom/device1", function(payload) {
  console.log("Wow!");
});
emitter.on("/house/bedroom/device2", function(payload) {
  console.log("Cool!");
});
```

You can even do fancy things by using [mqtt-regex](https://github.com/RangerMauve/mqtt-regex) patterns.
