### ISSUE TITLE
Subscribe sometimes doesn't work

### ISSUE THREAD

**Issue by EnricoGiordano1992** [mqttjs/MQTT.js#792]
Hi, I have a problem with mqtt subscribe function. 
I'm using Ionic 2 and I've imported your library in this way:
`import * as mqtt from 'mqtt'`

my environment:

```
cli packages: (C:\work\blablabla\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.2
    Ionic Framework    : ionic-angular 3.2.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.10.0
    npm               : 5.7.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk

Misc:

    backend: pro
```

This is my code (it's in a singleton class in my code):

```javascript
...
         var self = this;
          self.client  = mqtt.connect(mqttServer,
          { clientId: 'blablabla-' + uuid,
            username: 'blablabla',
            password: 'blablabla',
            keepalive: 60,
            clean: true,
            reconnectPeriod: 15000,
            rejectUnauthorized: false
           })

           self.client.on('error', function (err) {
             console.log("Mqtt error", err)
           })
           self.client.on('close', function () {
             console.log("Mqtt close. Try to reconnect")
             self.client.reconnect()
           })
           self.client.on('connect', function (connack) {
             console.log("Mqtt connected",self.client.connected)
           })

...

 console.log("Try Sub to topic 00:14:2d:4d:bd:71/+/+/+/presenza/parameter_update");
            mqttClient.subscribe("00:14:2d:4d:bd:71/+/+/+/presenza/parameter_update", {qos: 1}, (err, granted)=>{
              if(err){
                console.error("error: ",err);
              }else {
                console.log("granted: ", granted);
              }
            });
```

I've noticed that sometimes I don't receive anything from mqtt, in particular, I've seen that this code sometimes doesn't print anything in subscribe callback. What's the problem with my code? Why sometimes subscribe callback doesn't work?
Thanks

**Comment by RangerMauve** [comment]
In your example, is `mqttClient.subscribe` the same as `self.client.subscribe`?
What version of MQTT.js are you using?
Are you making sure to wait for the connect to happen before trying to subscribe?

**Comment by RangerMauve** [comment]
Also, which broker are you using?

**Comment by EnricoGiordano1992** [comment]
Yes, mqttClient is the same as self.client.

I've added a check to my subscribe function, so my code now is:
```javascript
           self.client.on('error', function (err) {
             console.log("Mqtt error", err)
             self.is_connected = false;
           })
           self.client.on('close', function () {
             console.log("Mqtt close. Try to reconnect")
             self.is_connected = false;
             self.client.reconnect()
           })
           self.client.on('connect', function (connack) {
             self.is_connected = true;
             console.log("Mqtt connected",self.client.connected)
           })
...

    subscribeTo(mac: string, topic: string)
    {
      var self = this;

      //NOT CONNECTED?
      if(!self.is_connected){
        console.error("warning! mqtt not connected!!! retry...");
        self.client.reconnect()
        setTimeout(()=>{
          self.subscribeTo(mac, topics);
        }, 1000);
        return;
      } else {
        console.log("is connected, so np!");
      }

 console.log("Try Sub to topic ", mac+topic);
            mqttClient.subscribe(mac+topic, {qos: 1}, (err, granted)=>{
              if(err){
                console.error("error: ",err);
              }else {
                console.log("granted: ", granted);
              }
            });
```

now I see that sometimes I lost connection to my mqtt broker, in fact, I have this error:
```
WebSocket connection to 'ws://157.27.254.149:8085/mqtt' failed: Connection closed before receiving a handshake response
```

as you see, I try to reconnect with self.client.reconnect() function.

I'm using EMQTT broker.

**Comment by RangerMauve** [comment]
The client should be automatically reconnecting, manually invoking reconnect may be messing stuff up.
Is your broker giving you logs for why it's closing? Maybe that can give us a clue as to what's happening.
Are you sure your client is authorized to subscribe to those topics?

**Comment by EnricoGiordano1992** [comment]
Ok, I removed all "reconnect" in my code.

I have noticed that mqtt client stop to receive data when in server log appeared this string:

09:08:34.699 [error] WsClient(157.27.147.80:45719): Unexpected Info: {'EXIT',<0.16664.508>,{shutdown,conflict}}

What does it mean?

**Comment by RangerMauve** [comment]
I'm not sure to be honest. I think that's something you'll need to ask the authors of the broker.

**Comment by EnricoGiordano1992** [comment]
solved: I accidentally used the same client id for my devices, so did not work for that. Thanks for the support!

**Comment by RangerMauve** [comment]
Awesome, glad you figured it out! I'll try suggesting this earlier next time someone has a problem. :P

**Comment by semireg** [comment]
This is somewhat unrelated to the root cause (above), but I came here looking for answers to a similar issue I was having. Turns out, if you're using windows cmd.exe as a command-line, avoid using single quotes for arguments. Always use double-quotes... weird things happen with mosquitto_pub/sub when using single quoted arguments. :-)
