### ISSUE TITLE
Broker keeps sending retained message?

### ISSUE THREAD

**Issue by Diamundo** [mqttjs/MQTT.js#795]
Hi, I've written a (for now) tiny piece of MQTT code in Node.js, to receive topics and print them to the console. See below.

Problem: I receive the same retained message every 30m40s roughly.
I've added a QOS option of 2, which didn't help either, so now I'm thinking it's got something to do with:

- the client timing out and reconnecting every 30m40s, upon which the retained message is sent; or 
- the connection between my client and broker being destroyed every 30m40s (which would be outside the scope of both my client and the broker?)
- I'm actively querying the retained message?

Can anyone help me figure out the root of this problem?
_Note: the channels aren't actually one/# and two/#, these have been anonymized._

__EDIT:__
I've just added a retained message to channel "two", and at 30m40s since the last retained message was sent from "one", I received another retained message from "one", now also accompanied by the retained message from "two".

settings.js
```
var express= require('express');
var Setting = function() {
	this.mqtt = {},
	this.mqtt.BrokerURL	='mqtt://m2m.eclipse.org',
	this.mqtt.Topics 	= ['one/#', 'two/#'],
	this.mqtt.options	= { "qos" : 2 },
	
	this.now = () => {
		var cdate = new Date();
		return	(cdate.getFullYear()+"-"
			+(cdate.getMonth()<=8?"0":"")+(cdate.getMonth()+1)+"-"
			+(cdate.getDate()<=9?"0":"")+ cdate.getDate()+" "
			+(cdate.getHours()<=9?"0":"")+ cdate.getHours()+":"
			+(cdate.getMinutes()<=9?"0":"")+ cdate.getMinutes()+":"
			+(cdate.getSeconds()<=9?"0":"")+ cdate.getSeconds());
	}

	return this;
}
module.exports = Setting;
```

mqtt-client.js
```
var mqtt	= require('mqtt');
var setting	= require('../settings.js');

var settings = setting();
var client	= mqtt.connect( settings.mqtt.BrokerURL, settings.mqtt.options );

client.on('connect', () => {
	client.subscribe( settings.mqtt.Topics, settings.mqtt.options );
});
client.on('message', (topic, message) => {
	console.log(settings.now() + ' MQTT RECEIVE ' + topic + ' = ' + message.toString() );
	//temporarily print msg
});

```

**Comment by Diamundo** [comment]
Update: I've now switched to a different public broker (broker.hivemq.com) and done the same trick, albeit slightly different topics (but the same channels "one" and "two"), and at first glance the issue now seems to be fixed. Perhaps the issue was with the broker - though trough a [Windows Application MQtt.fx v1.6.0](http://mqttfx.jensd.de/) I'm also subbed to the old broker and that doesn't repeat the messages either as it did with my Node.js server.

**Comment by mcollina** [comment]
Awesome news!

**Comment by Diamundo** [comment]
I've given it some more thought, and I've come up with the following thought pattern:
- A client has a sort of timeout time set, with a default of 30 minutes. 
- After these 30 minutes, the client times out.
- Since I don't give any sort of identification, I'm anonymous
- Since I do reconnect, I'm another anonymous client and receive the retained messages
- The additional ~40 seconds come from the connecting, receiving published messages and other things. After that, 30 minutes of timeout start.

Solving this would be to:
- add some sort of identification.

In my case, I altered ```settings.js```:
```
this.mqtt.options	= { "qos" : 2, "clientId" : "myClientId" },
```

@mcollina does this sound reasonable?

**Comment by karlp** [comment]
do you actually have a 30 minute keepalive?  are you sure you're connection is actually still alive?  that's going to have been killed by most tcp cleanup I would have thought.
