### ISSUE TITLE
Question: Using with nodejs 4.3.1

### ISSUE THREAD

**Issue by suculent** [mqttjs/MQTT.js#796]
Hello,

we're doomed to use nodejs 4.3.1 (onion.io; 128MB RAM; 580MHz). Which version of MQTT.js would be running with that? Thanks

**Comment by mcollina** [comment]
I think the latest one should still run fine. Let us know!

**Comment by suculent** [comment]
It doesn’t due to the stream-completion  dependency. Even with disabled streaming env-var. 

Odesláno z iPhonu

22. 3. 2018 v 16:03, Matteo Collina <notifications@github.com>:

**Comment by mcollina** [comment]
our tests are currently passing on 4.3.2 (https://github.com/mqttjs/MQTT.js/blob/master/.travis.yml#L6). I expect it to work on 4.3.1 as well.

What are you executing and with what output?

**Comment by suculent** [comment]
https://github.com/nodejs/readable-stream/issues/326
