### ISSUE TITLE
unsubscribe topic is not working..

### ISSUE THREAD

**Issue by aaamitsingh** [mqttjs/MQTT.js#801]
I'm not getting any error but after unsubscribe also getting message from that topic. Here is my code
```js
client.unsubscribe('test/1234/status', function (err) {
      if(err){
        console.log(err);
      }else{
        console.log("unsubscribed");
      }
});
```

**Comment by mcollina** [comment]
Can you please upload a full example? Consider that this is likely your code or your broker problem.

**Comment by aaamitsingh** [comment]
Thanks for your quick reply @mcollina. Let me explain the case.
1. I have subscribed to a particular topic i.e 'test/1234/status' then published message from MqttBox and I have successfully received the message.

2. Then After sometime I have unsubscribed the topic 'test/1234/status' by below code but still I'm getting messages to that topic.
```
client.unsubscribe('test/1234/status', function (err) {
if(err){
console.log(err);
}else{
console.log("unsubscribed");
}
});
```
Can you please tell me what I'm doing wrong or there any other issue?

**Comment by mcollina** [comment]
As I said, can you please upload a __full example__?

**Comment by 4rzael** [comment]
The basic following code works:
```js
const mqtt = require('mqtt')
const client = mqtt.connect('mqtt://localhost:8001') // change the host
client.subscribe('/hello')
client.on('message', console.log)
setTimeout(() => {
  console.log('unsubscribing')
  client.unsubscribe('/hello')
}, 10000)
```

Please send us a full code, such as this one, that we can run directly (and if possible, which broker you are connected on), so we can understand your problem, and potentially find a bug.

**Comment by aaamitsingh** [comment]
Thanks, @4rzael @mcollina. I have found the issue the issue was in my code
