### ISSUE TITLE
Retrieving ClientID on message receipt

### ISSUE THREAD

**Issue by ASwingler** [mqttjs/MQTT.js#802]
I'd like to have the clientId available when I receive a message. I don't see that field in the packet. Is there another way to retrieve the clientId during a message receipt event?
- Andrew.

**Comment by RangerMauve** [comment]
Hi, are you talking about the client-side? The messages you're receiving are from the broker, not a client.

The MQTT protocol doesn't allow for a clientID within messages. If you need to tag messages with an origin, either put that in the topic string or as part of the message contents.

**Comment by ASwingler** [comment]
Thanks for the response RangerMauve. I was indeed talking about client-side messaging. I understand the messages are coming from the broker - I was hoping that the broker would be able to pass the clientId of the publisher when a subscriber receives a message.
You're right that I could include the information in the payload and indeed I already do. I was hoping to be able to validate the payload against the clientId. No matter - I'll figure out another way. Thanks again.

**Comment by ASwingler** [comment]
Some good ideas there. I do already have authentication (and TLS) and a unique portion of the Client ID is already included in the topic. 

I'll check out mqtt-emitter. Looks like an interesting project.
