### ISSUE TITLE
mqtt package on NPM include test, examples, documentation, etc.

### ISSUE THREAD

**Issue by yeiniel** [mqttjs/MQTT.js#803]
When a dependency is installed what i expect is the code that implement the feature and not example code or tests. May be i'm in the wrong in this one?

This affect mqtt package version 2.17.0 on NPM.

**Comment by mcollina** [comment]
In fact I expect the exact opposite, to have all code and examples. More often than not, I use those to get info about the module.

**Comment by yeiniel** [comment]
I'm sorry if i create this issue and forgive me if i'm not expressing my self correctly. English is not my mother tongue. But you distribute a package on NPM and NPM is intended to distribute code, not examples and certainly not howto to test your package. Additionally you have close this issue without discussion at all. You do not ask why this is a problem for me (a user). It's a shame you close this issue without discussion at all. Your are not acknowledging that shipping test code and examples is against common practice on the NPM ecosystem either. 

Have a good day

**Comment by mcollina** [comment]
Because it is not. Some of the most downloaded modules do include tests and examples. Some of the most downloaded modules do not include those.

You open this issue not saying why this is a problem for you, and you hint you could be wrong. It did not seems you wanted a discussion, but a generic question about this module and npm.

**Comment by yeiniel** [comment]
Again. Sorry for the communication issues. 

When i say "May be i'm in the wrong in this one?" i was just opening the possibility to discuss any opinions on the subject. So if you have a different opinion i appreciate you expose it as you did above. But may be you should wait for the opinions of other interested parties because i'm not the only user of this package.

Additionally i must say that this

> Your are not acknowledging that shipping test code and examples is against common practice on the NPM ecosystem either

is my mistake. I must have said 

> Your are not acknowledging that shipping test code and examples is against [best practice](https://www.npmjs.com/package/module-best-practices#npm-ignores) on the NPM ecosystem either

I'm very grateful of your job contributing to this project. Don;t get that wrong. I have a great appreciation for this work of yours and i use this package a lot. I know the stated problem[ is common to many other NPM packages](https://gist.github.com/greim/e8e1bd3b1ed08a7505ce). I'm just trying to contribute to this project i really appreciate by raising the issue. If some day i found a problem on this package no doubt i will report it and try to fix it myself to contribute to your work. I just not create a MR because i think the issue need to be discussed first with the community as a hole. This is one of the packages that is a strong candidate to install on embedded systems and distributing additional stuff do not help on that scope.

My brain is saying "just end the conversation" but i really think that the community need to have this debate.

Have a good day and keep the good work

**Comment by sublimator** [comment]
Matteo, you need break

**Comment by mcollina** [comment]
@sublimator I know.

**Comment by sublimator** [comment]
Take one. If it makes you feel better I broke my toe today kicking a door
between myself and a mother beating ... child ...

All this will wait
