### ISSUE TITLE
pass packet or packet.messageId to publish callback?

### ISSUE THREAD

**Issue by ptone** [mqttjs/MQTT.js#806]
I'm not sure how this could be done without a breaking API change.  But if I want to take some action where I want to mark a message in a system as published. I have no way of connecting the message published to the callback.

This would require changes to the publish method to return the messageId (which it has access to) and the callback to receive the message callback.

I could find no issues asking about this, perhaps it has been discussed in the past.

**Comment by mcollina** [comment]
why? The callback is always called for the message you have published.

**Comment by 4rzael** [comment]
This is not required. If you want this functionality, you could go with something like that:
```js
function sendMessage(client, topic, message, options) {
    client.publish(topic, message, options, (error) => {
        console.log(`the message is ${message}`)
        // do something to set the message as sent in your UI / DB / Anything
    })
}
```

This way, the function defined in the publish callback can have access to your message. (Note that you actually need to check the error parameter)
