### ISSUE TITLE
CLI not working in Windows 10

### ISSUE THREAD

**Issue by kasvith** [mqttjs/MQTT.js#807]
# Issue
I followed introductions on the readme how to use CLI version for MQTT pub/sub.
This works very nice in my MacOS and in windows Terminal seems keep freezing.

I used Mosca as the broker. There is not clientConnected message also when i try to publish to mosca.
I tried same with MQTT.fx client for windows which is a standalone application. It works fine with mosca

![image](https://user-images.githubusercontent.com/13379595/38764674-07cd90fe-3fd1-11e8-875c-625333cd7838.png)

# System Info
Windows 10 Education x64 1709 , Build 16299.248
Cmder for commandline

**Comment by mcollina** [comment]
This is very interesting! Would you like to send a PR for this?

**Comment by kasvith** [comment]
I will try to do it, but not sure as im new to mqtt :D

**Comment by VsterLong** [comment]
I also encountered this problem, CLI is not supported.

**Comment by VsterLong** [comment]
but can use in Powershell.

**Comment by gewoonwoutje** [comment]
Still an issue in 3.0.0
