### ISSUE TITLE
password is getting undefined and callback is not connected

### ISSUE THREAD

**Issue by AhmadRaza786** [mqttjs/MQTT.js#809]
```
var mqtt = require('mqtt')
var options = {
  username: 'abc',
  password: 'xyz',
}
var client  = mqtt.connect('mqtt:localhost:1883', options);
```
In Above code I am providing username and password in options to this mqtt client.

```
var mosca = require('mosca');
var ascoltatore = {
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var settings = {
  port: 1883,
  backend: ascoltatore
};
var server = new mosca.Server(settings);
server.on('ready', setup);

function setup() {
  server.authenticate = authenticate;
  console.log('Mosca server is up and running');
}

var authenticate = function(client, username, password, callback) {
  console.log(username, password);
  callback(true);
}
```
Here in server side in the `authenticate` function I am getting the username correctly but the password is undefined What I am missing here. Also I need to connect a callback at client side that is being called in `authenticate` function.

**Comment by RangerMauve** [comment]
It might be related to your MQTT URL being messed up. the protocol needs to have a `//` in it like `mqtt://`. Maybe that's related?

**Comment by AhmadRaza786** [comment]
@RangerMauve , I dont think so. because its working fine. just forget the password, Can u please tell me that how can i can connect my callback function with the authenticate ?

**Comment by RangerMauve** [comment]
Which callback are you taking about? Did you figure out what you needed?
