### ISSUE TITLE
Terribly slower in subscription mode when comparing with Paho PERFORMANCE

### ISSUE THREAD

**Issue by zlatinejc** [mqttjs/MQTT.js#815]
Ran some simple tests sending 100K QoS 2 records via IBM MessageSight v2 mqtt broker and was shocked by the results:

Paho needs little less than 2s, when MQTT.js needs 20s.

Am I missing something, did anyone have similar experience during testing of this lib ?

Thanks in advance.

**Comment by krittanon-w** [comment]
Pay attention to this issue.

**Comment by zlatinejc** [comment]
Still nothing ?
