### ISSUE TITLE
Suggestion for handling large backlog of non-essential messages?

### ISSUE THREAD

**Issue by abcd-ca** [mqttjs/MQTT.js#817]
Hello,

I've had a great experience with this library so far, thank you! I've got an app on a device that has had real-world experience now in (temporarily) flaky or non-existent network conditions. I have some essential messages (QoS1) that eventually get published as expected upon re-establishing network connectivity. My persistent client store queues all my messages up and sends them out as expected. 

However, I also have some hardware status type messages like temperature etc to provide insight into how the equipment is doing. I send this out every 30 seconds. In one case we found the device was not able to connect for around 5 hours so there were thousands of these messages in the backlog. By the time network connectivity was restored, it was quite a wait to get through all these queued non-essential messages to finally get to the queued essential messages. 

I considered sending the non-essentials as QoS 0 but I think my client would queue just as many messages while offline – it just wouldn't care if the broker receives them, right? So that wouldn't really help much, I think. I could send the messages less frequently, and I might do so anyway.

I'm wondering, might it be possible to somehow find the IDs of all messages of a certain topic like, `/foo/state/#` and opt to only queue the 10 most recent somehow? Can you recommend a strategy that the existing mqttjs API might support?

**Comment by RangerMauve** [comment]
There's no easy way to do what you want because the way the functionality works is it processes the packets one at a time from storage without really inspecting the packet types or topics.

You might be able to add some custom logic by modifying the library around [here](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L140).

**Comment by abcd-ca** [comment]
Thanks @RangerMauve I'll look into that. I'd also be happy not sending certain messages if I know I'm not connected – I don't think I currently have a good way of establishing that though.

This is what I've tried but it doesn't seem to reliably update once connected. Maybe it's got a long timeout or something. See anything bad with this approach.

```
this.client = connect(`mqtt://${process.env.MQTT_HOST}`, {
        username: process.env.MQTT_USER,
        password: process.env.MQTT_PASS,
        //   port: 1883,
        clean: false,

        // only need to set this when clean is set to false
        clientId: this.clientID,

        // Last Will send connected=false 
        will: {
          topic: `${this.stateTopicBase}/connected`,
          payload: BINARY_FALSE,
          qos: 1,
          retain: true
        },

        incomingStore: manager.incoming,
        outgoingStore: manager.outgoing
      })

      this.client.on('offline', () => {
        console.log('*** Messenger offline')
        this._commState = CommState.OFFLINE
      })
      this.client.on('reconnect', () => {
        console.log('*** Messenger reconnecting...')
        this._commState = CommState.RECONNECTING
      })
      this.client.on('error', err => console.log('*** Messenger error ', err))
      this.client.handleMessage = this.handleMessage.bind(this)

      this.client.on('close', () => this._commState = CommState.OFFLINE)

      this.client.on('connect', async () => {
        this._commState = CommState.CONNECTED
      })
```

**Comment by RangerMauve** [comment]
In your code are you checking for CommState.OFFLINE, or CommState.CONNECTED? AFAIK the `reconnect` event goes out right after the conenction closes, so I doubt you'd be in the `OFFLINE` state for long.

Other than that it all looks good to me. You may want to play around with the `reconnectPeriod` time if you're expecting your device to be offline for a long time.

**Comment by abcd-ca** [comment]
@RangerMauve I'm not really checking yet for CommState.OFFLINE or CommState.CONNECTED. I'm updating an LCD with the current state, whatever it is but I am interested in conditionally publishing non-essential messages when !CommState.CONNECTED. I didn't notice `reconnectPeriod`, I'll try it – I don't really understand from the limited docs there what it does – does it mean that's how long between retries? will it retry forever? My device could be offline for hours before a human moves it to a place that has a connection (we have a cellular connection)

**Comment by RangerMauve** [comment]
Checking for `this._commState!== CommState.CONNECTED` sounds like a good approach, I've used similar logic in some of my code.

Yeah, `reconnectPeriod` is the time between retries, it should save you some CPU cycles.

It should retry forever, if it doesn't raise an issue. :P

**Comment by abcd-ca** [comment]
Thanks!
