### ISSUE TITLE
Conflict with React application bundling with webpack

### ISSUE THREAD

**Issue by amerllica** [mqttjs/MQTT.js#820]
I'm working on a Universal `React` application that need  a client `MQTT`, I choose this library because of its crowded stars, but it cause to some weird errors:

    ERROR in ./node_modules/mqtt/mqtt.js
    Module parse failed: Unexpected character '#' (1:0)
    You may need an appropriate loader to handle this file type.
    | #!/usr/bin/env node
    | 'use strict'
    | 
     @ ./src/app/App.jsx 23:12-27
     @ ./src/server.jsx
    i ｢wdm｣: Failed to compile.

I cannot understand why `#!/usr/bin/env node` wrote in a `JavaScript` library! `JavaScript` can't settle `#` character and it cause to error,

For settle this issue I exclude some paths in my `webpack` configuration file and use `shebang-loader`, my last `babel-loader` configs in `webpack` was:

    {
        test: /\.(js|jsx)$/,
         exclude: /node_modules/,
        use: [
            {
                loader: 'babel-loader',
            }
        ]
    }

And for fixing I changed them to:

    {
        test: /\.(js|jsx)$/,
         exclude: /(node_modules\/)/,
        use: [
            {
                loader: 'babel-loader',
            },
            {
                loader: 'shebang-loader',
            }
        ]
    }

And it fixed, also some warning is showing in my bash console:

    WARNING in ./node_modules/ws/lib/BufferUtil.js
    Module not found: Error: Can't resolve 'bufferutil' in 'C:\Users\Amer\WebstormProjects\member\node_modules\ws\lib'
     @ ./node_modules/ws/lib/BufferUtil.js 35:19-40
     @ ./node_modules/ws/lib/Receiver.js
     @ ./node_modules/ws/index.js
     @ ./node_modules/websocket-stream/server.js
     @ ./node_modules/websocket-stream/index.js
     @ ./node_modules/mqtt/lib/connect/wx.js
     @ ./node_modules/mqtt/lib/connect/index.js
     @ ./node_modules/mqtt/mqtt.js
     @ ./src/app/index.jsx
     @ ./src/server.jsx

    WARNING in ./node_modules/ws/lib/Validation.js
    Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Users\Amer\WebstormProjects\member\node_modules\ws\lib'
     @ ./node_modules/ws/lib/Validation.js 12:20-45
     @ ./node_modules/ws/lib/Receiver.js
     @ ./node_modules/ws/index.js
     @ ./node_modules/websocket-stream/server.js
     @ ./node_modules/websocket-stream/index.js
     @ ./node_modules/mqtt/lib/connect/wx.js
     @ ./node_modules/mqtt/lib/connect/index.js
     @ ./node_modules/mqtt/mqtt.js
     @ ./src/app/index.jsx
     @ ./src/server.jsx
     i ｢wdm｣: Compiled with warnings.

It is so weird, why the contributors didn't add the dependencies?

**Comment by amerllica** [comment]
@RangerMauve , Thanks for you answer, but your works are a little complicated, what do you mean my build system has problem? My example platform is [**`HERE`**](https://github.com/digikala/universal-react-app-sample) Take a look and tell me what I'm wrong. Thanks

**Comment by RangerMauve** [comment]
The "build system" in your case is webpack. I'll need you to do a bit of reading up on webpack and babel before I can explain more. Sadly the thing you're trying to do is a bit complicated. (universal apps that use node.js modules in RN)

**Comment by amerllica** [comment]
Thanks @RangerMauve  for your answer but I'm intermediate in `React`, `Webpack` and `Babel`, Actually my projects works well with `MQTT` and I settled up everything but I wanna know why `mqtt.js` using `shebang` and why after using `shebang-loader` the console still show yellow warning.

If you are interested to see my project you can see [**`THIS ADDRESS`**](https://github.com/amerllica/react-server-render-example), after installing with `yarn install` just type `yarn dev` to run and see what I'm writing about universal react app.

If you wanna see my mqtt project, wait until sunday and then I'll post a link here to you.

**Comment by RangerMauve** [comment]
@amerllica The `mqtt.js` file is used in the CLI and isn't supposed to be loaded as part of the library. The shebang there is standard Linux/Node.js syntax that specifies what executable should be used to run the file.

Node.js command line applications specify this so that they can be set as "executable" in linux and can be run like a compiled program.

In Node.js, ashebang on the first line is ignored.

**Comment by amerllica** [comment]
@RangerMauve , Thanks a lot for your clear explanation. I got it. thanks.
