### ISSUE TITLE
publish looks for message even when stdin is being used

### ISSUE THREAD

**Issue by knishant** [mqttjs/MQTT.js#821]
cat /tmp/msgfile | mqtt publish -h localhost -p 1883  **--stdin** topicname

when I run this command, it fails at the following line 
```
at Command.start [as func] (mqtt/src/dist/client/node_modules/mqtt/bin/pub.js:121:50)
```
I have to pass a dummy message at the end of the command for this command to work.
Thankfully it send the message from stdin, instead of the dummy message.

Issue is that the command looks for a message after topic even if stdin is specified.
```
args.topic = (args.topic || args._.shift()).toString()
args.message = (args.message || args._.shift()).toString()
```
second line above should use args.stdin flag as well.

**Comment by OmgImAlexis** [comment]
If this is still an issue on the latest version please let me know and I'll reopen this.
