### ISSUE TITLE
MQTT Client Disconnecting if receive too many messages

### ISSUE THREAD

**Issue by arihantdaga** [mqttjs/MQTT.js#823]
I am using this library in a case where i have many retained messages from 1000s of clients. And my node app subscribe to those topics and hence receive too many messages at the time on connection. 
Problem i am facing with this library is, most of the time it is disconnecting from broker and again reconnecting and also subscribing to the topic which will make broker send the retained messages again to my app hence it again disconnects.. It enters into this loop and is never able to stabilize.. 

I used bombing.js from benchmarks folder and sent around 10,000 retained messages on topic - 
`test/${count++}/anything`  
and then in throughputCounter.js file i subscribed to the topic 
`test/+/anything` 

This is how my log look like - 

```
*** Messenger offline
received/s 5966.400000000001
*** Messenger reconnect
connected
received/s 0
*** Messenger offline
*** Messenger reconnect
connected
received/s 6215
*** Messenger offline
*** Messenger reconnect
connected
received/s 6796.400000000001
received/s 0
*** Messenger offline
*** Messenger reconnect
connected
received/s 6593.4
*** Messenger offline
*** Messenger reconnect
connected
received/s 7560
*** Messenger offline
received/s 7081.8
*** Messenger reconnect
connected
received/s 0
```

Can anyone suggest me what is happening here? Why client gets disconnected frequently and what i should do to prevent it?

**Comment by krittanon-w** [comment]
Pay attention to this issue.

**Comment by rodrigomvf** [comment]
I'm going through the same problem.
When the message volume is very large it is apparently experiencing memory leak

**Comment by Benzer1406** [comment]
Have the same issue, will probably have to change the library....
