### ISSUE TITLE
Unable to recieve large payloads over websocket connection

### ISSUE THREAD

**Issue by PTS93** [mqttjs/MQTT.js#824]
It seems like large payloads get eaten up somewhere. Whenever I publish a 9MB payload my mqtt.js websocket client never receives the message. On a different client connecting via TCP I get the message pretty much immediately.
What could be causing this?

**Comment by PTS93** [comment]
It seems it was broker related, I couldn't pinpoint the exact cause but messages were coming through after a while, though quite a bit slower than for non ws clients.

**Comment by RangerMauve** [comment]
Would you mind telling us which broker you were using so we know for next time?

**Comment by PTS93** [comment]
Mosquitto
