### ISSUE TITLE
How to know when all messages from store have been sent?

### ISSUE THREAD

**Issue by abcd-ca** [mqttjs/MQTT.js#825]
Hi, I have had good success with this library. I have a device that sometimes goes offline for long periods and upon reconnecting sends its mqtt messages that were queued in the mqtt-level-store. This works.

What I am missing is a way to know when it's safe to power-off my device. I want to be able to know if all mqtt messages have been sent from the store or if it's still busy sending. Is there a hook for this already that you can point me to? Otherwise, is there a particular place in the source code you can point me to to develop it myself?

Thanks!

**Comment by abcd-ca** [comment]
I've been digging into the source code observing `createStream`. Here's my hack test:

```
manager.outgoing.createStream().on('data', data => {
        // print first object to get sense of its structure
        if (this.streamCount === 0) console.log('*** stream data: ', data)

        this.streamCount++
      })

      setTimeout(() => {
        console.log('*** streamCount: ', this.streamCount)
      },5000)
```

I am finding that apparently my leveldb store emits the 'data' event 1762 times. That's a lot more than I expected unless it's keeping all data from all time. I had assumed that after a connection was established and all client-persisted messages had been published they'd be removed from the store. Do I need to be managing when to delete from the store? If so I'd love an example and that would also answer my original question. Thank you!

**Comment by jlawrencecfm** [comment]
I'm also wondering this - for our purposes it's to ensure data is always written in the correct order.  Currently if the device loses connection for some time and then reconnects, newer events can be written to mqtt before the old ones from leveldb have been sent.
