### ISSUE TITLE
transformWsUrl not called when options passed as first param

### ISSUE THREAD

**Issue by benswinburne** [mqttjs/MQTT.js#826]
The following code would suggest that I can just pass an object of options into the connect function.

```
/**
 * connect - connect to an MQTT broker.
 *
 * @param {String} [brokerUrl] - url of the broker, optional
 * @param {Object} opts - see MqttClient#constructor
 */
function connect (brokerUrl, opts) {
  if ((typeof brokerUrl === 'object') && !opts) {
    opts = brokerUrl
    brokerUrl = null
  }
...
```

However, when I run the following, the function isn't called. Note that the particular signing package doesn't require the original URL, hence me not wanting to put something in as the first parameter.

```
const signUrl = require('aws-device-gateway-signed-url')
const client = mqtt.connect({
  transformWsUrl: (url, options, client) => {

    console.log('signing a new url') // never seen
    return signUrl({
      regionName: process.env.AWS_REGION,
      endpoint: process.env.IOT_ENDPOINT,
      accessKey: process.env.AWS_KEY,
      secretKey: process.env.AWS_SECRET,
      expires: 3600
    })
  }
})
```

I've currently just resorted to the following which works, but obviously makes no sense from a readability point of view.

```
const client = mqtt.connect('ws://localhost', {
  transformWsUrl: (url, options, client) => {
    return signUrl({...})
  }
})
```

I have also used the following

```
// This works, but then doesn't get a new url for reconnection
const client = mqtt.connect(signUrl({...}))
```

I'm not sure if this is a bug or I'm trying to use the library in a way which it isn't intended. Any help would be much appreciated; if it's not a bug I'll head over to SO but it seems like this should work given the above excerpt.

Thanks

**Comment by mcollina** [comment]
I would recommend to ask the folks at AWS to help you out, or send a PR with the fix.

**Comment by benswinburne** [comment]
It's not related to AWS, I could just put a console long in my `transformWsUrl` and it never gets called. 

The actual signing of the URL and connecting to the server works fine. This library never runs my `transformWsUrl` function if an object is passed as the first parameter to `connect()`, but if it's the 2nd one, it's fine.

**Comment by mcollina** [comment]
This feature was contributed to better support AWS IoT. AWS IoT is a paid product, and while they are using this library, they are not helping with the maintenance of this library.

I'm happy to review a PR that fixes this bug.
