### ISSUE TITLE
I can't connect the server in vuejs 

### ISSUE THREAD

**Issue by sueblue** [mqttjs/MQTT.js#832]
I just use the simple ep:
```js
    var client = mqtt.connect("mqtt://test.mosquitto.org");

    client.on("connect", function() {
      client.subscribe("presence");
      client.publish("presence", "Hello mqtt");
    });

    client.on("message", function(topic, message) {
      // message is Buffer
      console.log(message.toString());
      client.end();
    });
```
this code writes in created() function in vue-cil project , but got a error:

`stream.js?b72e:64 WebSocket connection to 'ws://test.mosquitto.org/' failed: Error during WebSocket handshake: Unexpected response code: 200`

is   there  something wrong? 

Thanks in advance.

**Comment by anthrogan** [comment]
You need to supply a port with the connection url. "mqtt://test.mosquitto.org:1883"

**Comment by sueblue** [comment]
@anthrogan adding port 1883 is not useful .
got a error:
 `stream.js?b72e:64 WebSocket connection to 'ws://test.mosquitto.org:1883/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET`,

anyway,tks a lot.

**Comment by hanfengcan** [comment]
the same problem

**Comment by hanfengcan** [comment]
set broker protocol websockets

**Comment by Haider8** [comment]
@sueblue I am having this same error in vue.js. Were you able to resolve this?
Would love to hear the solution :)

**Comment by hanfengcan** [comment]
@Haider8 make sure your broke use the websockets protocol. not the tcp
