### ISSUE TITLE
nodejs to mosquitto raspberry pi  pub sub not work

### ISSUE THREAD

**Issue by Nasrogit** [mqttjs/MQTT.js#833]
Hi I am trying to sub and pub to mosquitto service runnin on raspberry pi but no thing happen on Rpi console 
here is my code 
```js
var mqtt = require('mqtt');
var client  = mqtt.connect('mqtt://192.168.10.97');
 
client.on('connect', function () {
  client.subscribe('presence');
  client.publish('presence', 'Hello mqtt');
});
 
client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString());
  client.end();
});
```

so my raspberry pi with ip 192.168.10.97

and when I test the commend from raspberry pi console it work secsussfully

`mosquitto_sub -d -t "iot" `

`mosquitto_pub -d -t "iot" -m "Hi, This is my msg..."`

so what is the problem ?

**Comment by TechnicalSoup** [comment]
I'd suggest that you create a callback function for the client.subscribe call so that the message published from your code isn't sent until you're subscribed to the topic... 

As the client.subscribe is asynchronous you may be publishing you message before the subscription is done.
