### ISSUE TITLE
Way to correlate subscription with incoming message

### ISSUE THREAD

**Issue by Eric24** [mqttjs/MQTT.js#840]
It would be very useful when subscribing to multiple topics on the same connection to have a way to correlate received messages to a particular subscription. Of course the topic does this, but only if it doesn't contain wildcards. If a subscription does contain wildcards, it's a lot of extra work to determine which subscription it "belongs" to. I assume that each subscription has some sort of internal data structure, so one idea would be to allow some sort of key or ID to be included in the subscribe() options, and then include the options object in the message receive event. Thoughts?

**Comment by RangerMauve** [comment]
The MQTT protocol expects you to have your own routing set up for topics.
I don't think it'd be a good idea to add non-standard features to the client.
The subscriptions don't exist as data structures on the client-side, it's made to be tracked by the broker and it'd be hard to make all brokers adopt your idea.

 I suggest using something like [mqtt-pattern](https://github.com/RangerMauve/mqtt-pattern) to do routing client-side which should make life a lot easier.
