### ISSUE TITLE
Web socket aren't connecting.

### ISSUE THREAD

**Issue by j3rin** [mqttjs/MQTT.js#844]
var host = 'ws://xxxxx.xxxxxx.xxx.xxx.ibmcloud.com:1883/mqtt'

var options = {
  userName: "xxxxxxxxxx",
  password: "xxxxxxxxxxx",
  clientId:'axxxxx:xxxxxx',
  rejectUnauthorized: false
}

var client = mqtt.connect(host, options)

client.on('error', function (err) {
  console.log(err)
  client.end()
})

client.on('connect', function () {
  console.log('client connected:' + clientId)
})
client.on('message', function (a) {
    console.log('lost connection!' + a)
  })
   

Trying to connect but none of the WebSocket connection is connecting. I Tried the mqtt://test.mosquitto.org and it works. Please help, thank you! 🥇 :)

**Comment by mcollina** [comment]
1883 is the MQTT port. If you want to connect via Websocket, you need to use a HTTP/Websocket port.
