### ISSUE TITLE
Browserify: how force TCP

### ISSUE THREAD

**Issue by lucaele** [mqttjs/MQTT.js#849]
After Browserify,
All connection with "tcp://..." or "mqtt://..." will change automatically in "ws://..."
but i need "tcp" only.

There is a config to force that?
Thanks

**Comment by mcollina** [comment]
Are you running your bundle in the browser, right? In the browser, there is no tcp socket.

**Comment by lucaele** [comment]
yes i'm running on browser.
So I think the same problem is on cordova mobile app, right?

**Comment by mcollina** [comment]
Yes


Il giorno dom 5 ago 2018 alle ore 12:13 lucaele <notifications@github.com>
ha scritto:

**Comment by mbrandau** [comment]
Since this is not a problem with MQTT.js, this issue can probably be closed. @mcollina
