### ISSUE TITLE
subscribed to multiple topics, but want get message by topic by mqtt client.on

### ISSUE THREAD

**Issue by akdj** [mqttjs/MQTT.js#853]
Hi, 

I write a function which subscribes to one topic and start a listener. 
```
subscribeRequest = (subTopic, callback) => {
  MqttCLient.subscribe(subTopic);
  MqttCLient.on('message', (topic, message) => {
      if(topic === subTopic ){
        callback(topic, message);
      }
    });
  };
```
However, the listener catches all messages from all topics.

And because I call this function several times, I get too many replicated messages.

How can I fix my function?

is there some option that I can set, for listening only one topic by the MqttCLient.on? 
Like: MqttCLient.on ('message', my_topic, callback)

**Comment by RangerMauve** [comment]
Hi, MQTT.js is made to handle connecting to MQTT brokers and subscribing.

If you want to "route" events to certain listeners, consider using something like this: https://github.com/RangerMauve/mqtt-emitter

**Comment by akdj** [comment]
Ok, thanks!
