### ISSUE TITLE
Support for additional HTTP headers in Websocket connection

### ISSUE THREAD

**Issue by rafaelubal** [mqttjs/MQTT.js#856]
Hi,

I'm trying to add additional authentication headers in the initial HTTP connection request, but using option `wsOptions` does not seem to add additional headers:
```js
client = mqtt.connect(url, {
  clientId: client_id,
  wsOptions: {
    headers: {
      'My-Header': 'my_value'
    }
  }
});
``` 
If there is currently a way to do this, it'd be great if the documentation explicitly stated it. If not, I'd greatly appreciate support for this feature. Thanks a lot!

Rafael

**Comment by mcollina** [comment]
I don't think that's currently supported. Would you like to send a PR?

**Comment by rafaelubal** [comment]
I took a quick look at the code, and it looks like a limitation of the underlying 'websocket-stream' library used to create the WebSocket connection. In fact, it appears to be a restriction of the native `WebSocket` class specification on the browser (https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). However, the Amazon IoT Device SDK finds a way to do this, I'm not sure how at the moment.

**Comment by phillipj** [comment]
I spent a day digging deep into getting an AWS IoT custom authorizer working, which *requires* custom Websockets HTTP headers. In short I stumbled upon this issue where AWS employee @AWSSteveHa confirms several times that it can't be done from browsers because of limitations in the underlying Websocket implementation: https://github.com/aws/aws-iot-device-sdk-js/issues/169

> However, the Amazon IoT Device SDK finds a way to do this, I'm not sure how at the moment.

Ohh! Any hints how to make that work? Would be really interesting digging into the "how" there..

**Comment by rrrhys** [comment]
To send the headers in the connect request, please try installing a modified websocket-stream library.
npm install --save git+https://github.com/rrrhys/websocket-stream.git

I've modified websocket-stream to pass through headers when supplied in the options (for a React Native project).

**Comment by gswly** [comment]
Hi, i'm interested in this feature and after some testing i can say that:
* additional headers DO WORK when the library is used in a server-side Node script, with the exact same code posted by @rafaelubal 
* additional headers DO NOT WORK when the library is used in the browser
* i have no data regarding React Native, but the solution proposed by @rrrhys seems to implement the feature for this specific platform
