### ISSUE TITLE
mqtt.js + mosquitto on rpi infinite loop

### ISSUE THREAD

**Issue by mix359** [mqttjs/MQTT.js#861]
Hi to all,
I'm trying to integrate the mqtt.js library in a project but I'm having some problems that completely stop me:

I've setup a mosquitto 1.5 server on a raspberry pi 2 (installed like described [here](https://www.ecosia.org/search?q=mosquitto&addon=firefox&addonversion=4.0.4)) and configured as follow:
```
pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log
listener 9001
protocol websockets
include_dir /etc/mosquitto/conf.d
```

I'm simply connecting to it and displaying a console message on connection:
```
const mqttClient = connect('mqtt://rdisplay1.local:9001');
mqttClient.on('connect', function () {
  console.log("connected");
});
```

In the moment I open the page with this code, an infinite loop is produced. Looking into the console I can see the message "connected" printed continuously. I've tried to step in using the debugger and I can see that the work function in the client.js is called again and again from the Writer stream, like if the buffer is not cleaned.
I've also tried to shutdown the mosquitto server after I've opened the page, and the problem continue, so to me it seam like a bug of this library that produces in some way an infinite loop when a connack is received.

I've tried connecting with the same code to the test.mosquitto.org server, and with a mosquitto server installed on my macbook, and it work without problem, so it seam something related to the version of mosquitto I have on the raspberry (1.5) and this library.
Other software I've tested work without problem with the raspberry server.

Can anyone help me figure out what's the problem?
Thanks to all
Cheers
Mix

**Comment by redboltz** [comment]
It seems that mosquitto protocol is websockets.

```
protocol websockets
```

But MQTT.js connection is TCP.

```js
const mqttClient = connect('mqtt://rdisplay1.local:9001');
```

Try

```js
const mqttClient = connect('ws://rdisplay1.local:9001');
```
