### ISSUE TITLE
Question about v2.18.7

### ISSUE THREAD

**Issue by redboltz** [mqttjs/MQTT.js#862]
It is just a question.

Now, npm mqtt is v2.18.7. But github release is still v2.18.6.

When new pull requests are merged, what is the next version?
v2.18.8 or overwrite v2.18.7 on npm?

If the next version is v2.18.8, it might reduce confusion if v2.18.7 is release in github. I know the difference between v2.18.6 and v2.18.7 are just test file fix. However, mqtt-level-store includes the fixed test file. It is a part of public interface for mqtt-level-store in a sense.

If the next version is v2.18.7 and overwrite npm release, I'm afraid that users might be confused that two different contents that have the same version.

**Comment by mcollina** [comment]
I just forgot to publish 2.18.7. I've just tagged it.
