### ISSUE TITLE
MQTT.js v3.0.0

### ISSUE THREAD

**Issue by mcollina** [mqttjs/MQTT.js#871]
Are there any other semver-major changes that we would like to include before I cut the release?

**Comment by scarry1992** [comment]
I have one more idea, but I will realese here after 3.0.0.

**Comment by mcollina** [comment]
go for it!

Il giorno mer 19 set 2018 alle 03:21 Masaaki Fujiwara <
notifications@github.com> ha scritto:

**Comment by scarry1992** [comment]
Added PR with fix. @mcollina, merge it before release 3.0.0. please.

**Comment by scarry1992** [comment]
@mcollina, hello. I have a question: why are you skipping error from writable stream for creating connect packet?
279  // Suppress connection errors
280  this.stream.on('error', nop)

**Comment by mcollina** [comment]
if the streams ends, we are not going to error the client (autoreconnect), but routing it to the close event in https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L283.

**Comment by scarry1992** [comment]
@mcollina, but we have no ability getting errors in process writing connect packet to stream. Maybe we need to think about it?

**Comment by mcollina** [comment]
What do you mean? Would you like to send a PR?

**Comment by scarry1992** [comment]
I don`t think about PR for now, but I can attach my usecase:
if we attach broken will-object to config, we have the error in mqtt-packet, but in MQTT.JS we have no catching thats errors.
I think you can resolve that issue faster, then me.
Anyway, if you have no time, I can resolve it later.

**Comment by mcollina** [comment]
no time atm :/.

Il giorno mer 24 ott 2018 alle ore 10:13 scarry1992 <
notifications@github.com> ha scritto:
