### ISSUE TITLE
How to subscribe from mqtt to AWS IOT Service

### ISSUE THREAD

**Issue by srinivasyl** [mqttjs/MQTT.js#874]
I've device publishing data to AWS iot using AWS iot sdk I want that data to subscribe to store it in my local system 

I had gone through the AWS IOT documentation and it uses  X.509 certificates for authentication which is an extra layer of security both for subscribing and publishing.

But mqtt of this repository uses Just an host name, sometime s username and password for authentication
can we use this mqtt for authenticating to AWS IOT with certificates  ??? 

If it can. how to achieve it?

**Comment by fArchitect** [comment]
Check your Thing policy it should contain appropriate rules for connection: 
```json
{
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:...:client/sdk-java",
        "arn:aws:iot:...:client/basicPubSub",
        "arn:aws:iot:...:client/sdk-nodejs-*"
      ]
    },
{
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:...:topic/sdk/test/java",
        "arn:aws:iot:...:topic/sdk/test/Python",
        "arn:aws:iot:...:topic/topic_1",
        "arn:aws:iot:...:topic/topic_2"
      ]
    }
```

In my case, client id must be in format "sdk-nodejs-*" and topics: "topic_1", "topic_2"...
Example:
```shell
$ mqtt publish --key priv.pem --cert cert.pem --ca AmazonRootCA1.pem -h <iot-rest>.iot.<region>.amazonaws.com -i sdk-nodejs-1 topic_1 '{"Hello":"World!"}'
```

**Comment by ackratos** [comment]
same question to me. Anyone could suggest?

**Comment by ollolollollooloo** [comment]
hi guys can i see your example connection to aws iot from mqtt.js?

**Comment by jeff2013** [comment]
If you're using x509 certificates you can ad them as key, cert and ca in the options for connect. It's not documented but it works :) 

``` 
const opt = {
        host: host,
        protocol: 'mqtt',
        keepalive: 30,
        clientId: ...,
        clean: true,
        key: x509Key.pem,
        cert: x509Cert.pem,
        ca: root_CA.pem
    }

    mqtt.connect(opt);
