### ISSUE TITLE
WebSocket connection closed before receiving a handshake, cookies related 

### ISSUE THREAD

**Issue by adicatur** [mqttjs/MQTT.js#878]
Hi there, 

I have an app which uses mixpanel inside it, my web app URL is **"abc.com"**, in other hands I have chat app which uses mqtt for the real-time, my chat app URL is "chat.abc.com" and the mqtt url is **"mqtt.abc.com"**, once I reload **"abc.com"**, I will have cookies mixpanel, then I get this issue, but when I remove cookies from **"abc.com"**, then I reload **"chat.abc.com"** 
I will not see this issue again 

<img width="945" alt="screen shot 2018-10-01 at 18 39 06" src="https://user-images.githubusercontent.com/10487211/46286528-ae58cc00-c5a9-11e8-9d0e-a09d94a7571e.png">

**Comment by 1215708470** [comment]
我也遇到了同样的问题，求帮忙看看是什么问题，问题出现在哪里，failed: Connection closed before receiving a handshake response
![837c393b6fa3693c2440803951d55c8](https://user-images.githubusercontent.com/35633250/49852509-4501fe80-fe1f-11e8-8b47-7e723d0de371.png)
![f36c94102cd5623979d02306e8a45d8](https://user-images.githubusercontent.com/35633250/49852514-4a5f4900-fe1f-11e8-9bca-acd18c613c06.png)
![e4cb04df5d86d4d7cf366162b14be13](https://user-images.githubusercontent.com/35633250/49852648-ad50e000-fe1f-11e8-9c7b-a6337d2b5740.png)

**Comment by housemeow** [comment]
If you use mosquitto as mqtt broker, you have to set below:
listener 9001
protocol websocket
in /etc/mosquitto/mosquitto.conf

**Comment by kursatarslan** [comment]
same issue. is there any solution? 
![image](https://user-images.githubusercontent.com/9142092/92306497-28fda380-ef98-11ea-81fa-5f5db800ffb1.png)

**Comment by ysfscream** [comment]
@kursatarslan Check your port is right Webscoket port.
