### ISSUE TITLE
MQTT connection over WSS is not working with Proxy

### ISSUE THREAD

**Issue by sudhamoorthi** [mqttjs/MQTT.js#879]
Hi

I used the below code snippet to connect ActiveMQ. The url is wss://51.24.207.209:443/activemqws/mqtt But it is not connecting to message broker(ActiveMQ). I tried in cooperate network as well as open network. I am using this in node js. Please do the needful to resolve this issue.

```js
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://test.mosquitto.org')

client.on('connect', function () {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})
```

**Comment by sudhamoorthi** [comment]
i tried with below code snippet and its working fine in open network but it is not working in corporate network. kindly support on this.

var options = {
    'username':'admin',
    'password':'admin',
    'retain': false,
    'protocol': 'wss',
    'rejectUnauthorized': false
  };
  var broker = "wss://51.24.207.209:443/activemqws/mqtt";

  var client = mqtt.connect(broker, options);

**Comment by andares** [comment]
I have same trouble. I use broker ```ws://dev.app.lianxue.com:8083/mqtt``` it's work, and use ```wss://dev.app.lianxue.com:8084/mqtt``` is not work, can not connect server.

but I test it in servlet is ok.

![default](https://user-images.githubusercontent.com/7556505/49328506-0bbec880-f5ad-11e8-8120-d347512e2360.png)

**Comment by kainonly** [comment]
@andares I also use the emqx wss protocol, I have encountered the same problem as you.

**Comment by kainonly** [comment]
### Using EMQX

test:ok , mqttjs:connect failed

```
EMQX_LISTENER__WSS__EXTERNAL__KEYFILE: /ssl/mqtt.key
EMQX_LISTENER__WSS__EXTERNAL__CERTFILE: /ssl/mqtt.crt
```
add `EMQX_LISTENER__WSS__EXTERNAL__CACERTFILE` 

test:ok , mqttjs:ok

```
EMQX_LISTENER__WSS__EXTERNAL__KEYFILE: /ssl/mqtt.key
EMQX_LISTENER__WSS__EXTERNAL__CERTFILE: /ssl/mqtt.crt
EMQX_LISTENER__WSS__EXTERNAL__CACERTFILE: /ssl/root_bundle.crt
```
