### ISSUE TITLE
MQTT Client exceeded timeout, disconnecting

### ISSUE THREAD

**Issue by senthil5053** [mqttjs/MQTT.js#883]
In my node.js application, every 5 days we see the below errors  in our MQTT broker:

```
Client mqttjs_a29812c8 has exceeded timeout, disconnecting.	
Socket error on client mqttjs_a29812c8, disconnecting.
```
As a result of this, node.js app becomes kind of unresponsive by repeated connection and disconnection of MQTT client. There are like more than 10 k client connections made to broker. 
All the configurations are default ones and we use express. Below is the code snippet:

```js
var client = mqtt.connect("mqtt://" + moscaHost + ":" + moscaPort);
app.get('/sse/events', function (req, res) {
    client.on('connect', function () {
        req.log.info('SSE MQTT client connected');        
        client.subscribe(topic, function (err) {
            if(err) req.log.error(`MQTT subscribe err: ${err}`);
            else req.log.info(`SSE MQTT client subscribed to topic: ${topic}`);
        });        
    });
    client.on('message', function (topic, messsage, pkt) {
        req.log.info('Received message', message);       
    });
   req.on("close", function () {
       client.end();
   }
});
```

Could someone help here ?

**Comment by senthil5053** [comment]
@mcollina Could you please help here

**Comment by mcollina** [comment]
Unfortunately I can’t help atm :/.

**Comment by malishahi** [comment]
@senthil5053 I think the problem is that the connection to mqtt is outside app.get.
var client = mqtt.connect("mqtt://" + moscaHost + ":" + moscaPort);
