### ISSUE TITLE
Duplicate messages received - 2.18.8

### ISSUE THREAD

**Issue by hoIIer** [mqttjs/MQTT.js#884]
I'm using the [aws sdk](https://github.com/aws/aws-iot-device-sdk-js/) and lately I've been noticing that I get multiple duplicate messages that don't match up to our IoT backend logs.

So far I am not able to find a cause of this in our own client code, and again we verified that on IoT side only a single event is emitted.

Where could I begin to debug this?

I also tried passing `subscribe(topic, { qos: 0/1/2 }`, 2 seems to make the connection go bad, 1 and 2 both have same occurrence of duplicate messages being received.

**Comment by sergey-lukin** [comment]
Same issue here. I get several duplicates of the same message.
As a workaround I store last message of each topic in a variable and before processing message I check if same message with same topic was already processed. In my case messages are always different because they contain datatime field.
```js
var lastMsgPerTopic = {};
mqttClient.on('message', function insertEvent(topic, encodedMessage, packet) {
    var message = encodedMessage.toString();
    if (!lastMsgPerTopic[topic] || lastMsgPerTopic[topic] != message) {
        lastMsgPerTopic[topic] = message;
        // processing a message
    }
});
```
