### ISSUE TITLE
come across a memory leak problem！

### ISSUE THREAD

**Issue by jaybill-lee** [mqttjs/MQTT.js#890]
The situation is that:
1. The range of client ports can be used in my linux OS is  [32775, 61000]. It means I can create about 28225 mqtt connections at most. 
2. I use the OS to be stress-test client,  when I create about 28225 mqtt connections, the library works ok. However,  when I try to create more connections, such as 50000, normally it can create about 28225 connections, and the rest 21775 connections cannot be create sucess.
3. But, when over 28225  connections, the memory grow gradually util 1.4G,  and the connections which create success now lost connect,  and the process crash!

My code like this:

```js
var mqtt = require('mqtt');
for(var i=0; i<50000; i++) {
   var client = mqtt.connect('mqtt://10.160.114.6:6888');
   client.on("connect", function(){
	console.log('connnect!');
   });
   client.on("close", function(){console.log('close...');});
};
```

**Comment by OmgImAlexis** [comment]
Is this still an issue in the latest version?
