### ISSUE TITLE
Subscription with topic object

### ISSUE THREAD

**Issue by chainhead** [mqttjs/MQTT.js#896]
When providing topic string and QoS as an object, subscription does not happen. Instead, a close-reconnect loop starts. Refer snippet below.

```js
const MQTT = require('mqtt')
const uuidv1 = require('uuid/v1')
//
var client = MQTT.connect('tcp://localhost:1883', { clientId: uuidv1() })
client.on('connect', () => {
    console.log('Connected.')
    client.subscribe({ 'topic/string': { 'qos': 2 } }, (err, granted) => {
        if (err) {
            console.log(err)
        } else {
            console.log(granted)
        }
    })
})
client.on('reconnect', () => {
    console.log('Reconnected.')
})
client.on('close', () => {
    console.log('Closed.')
})
```

Also, if multiple subscription topic and their QoS are to be passed (as array or object), shouldn't the `options` object also be an array? To which subscriptions will those `options` apply?

Things would have been much simpler if the input was an array similar to the `granted` output object with an `options` object that is an array 'mapped' to the `granted` array.

**Comment by scarry1992** [comment]
@chainhead,  Are you set up mqtt.js from npm? If yes, that form of subscribe method not relized npm yet. Old form is client.subscribe({ 'topic/string': 2 })

**Comment by chainhead** [comment]
@scarry1992 But, the [document](https://github.com/mqttjs/MQTT.js#mqttclientsubscribetopictopic-arraytopic-object-options-callback) seems to mention it? BTW, can I extend your example into an array of objects for multiple subscriptions - `[{ 'topic/string': 2 }]`?

**Comment by scarry1992** [comment]
If you need multiple subscriptions you can use object form as well: client.subscribe({“topic/item”: 1, “topic/items”: 2}). Or wrong I understand you?

**Comment by chainhead** [comment]
Ok, understood. What about the `options` object? Does it apply to all the topics to be subscribed?
