### ISSUE TITLE
failed: Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by 1215708470** [mqttjs/MQTT.js#900]
帮我看看是什么问题，
![837c393b6fa3693c2440803951d55c8](https://user-images.githubusercontent.com/35633250/49852785-0fa9e080-fe20-11e8-8dcb-fd3c958535db.png)
![f36c94102cd5623979d02306e8a45d8](https://user-images.githubusercontent.com/35633250/49852789-12a4d100-fe20-11e8-84ee-68d40deb71f8.png)
![7c4341e8275919341fba815dab230ed](https://user-images.githubusercontent.com/35633250/49852796-15072b00-fe20-11e8-8335-ded5d4cdd9a5.png)

**Comment by SyMind** [comment]
websocket 连接失败，服务器端问题。
