### ISSUE TITLE
client does not receive messages when multiple messages are sent by broker simultaneously

### ISSUE THREAD

**Issue by vish30** [mqttjs/MQTT.js#904]
I have a NodeJS client which subscribes to a Mosquito MQTT broker. The QoS is set to 1. But when broker sends multiple messages simultaneously on may topics (and to all these topics, the NodeJS client is subscribed), the client's code is not able to receive the messages. The message-listening code goes like this:
```js
public_client.on('message', function (topic, message) {
  console.log(message);
}
```
It does receive some messages but not all. To verify that this is a problem on the client side, I also subscribed to the messages from MQTT.fx and it was able to receive the messages successfully, even with QoS set to 0 in MQTT.fx.

**Comment by juansmolano** [comment]
Hi,
did you find any kind of work-around for this?  we are also experiencing the same issue, the client does not receive messages when multiple messages are sent by broker simultaneously.  we are already on production and we had to scale the backend in order to minimize de probability of occurrence.

**Comment by vish30** [comment]
Hi,

I avoided it by changing the restart policy of docker container to
'always'. So, the container restarts instantly after a failure and it works
for me.

Best,
*Vishesh G. Sanghvi*

**Comment by Vishalz003xd9h** [comment]
Any update on this bug ?

**Comment by Vishalz003xd9h** [comment]
@adamvr , @mcollina , @4rzael , @scarry1992 -  Any updates on this issue ?

**Comment by Vishal8523** [comment]
@juansmolano , What is the workaround this issue that you implemented ?

**Comment by Vishal8523** [comment]
@4rzael , Any updates on this issue ?

**Comment by Vishal8523** [comment]
@mcollina , Any updates ?

**Comment by Vishal8523** [comment]
@4rzael , Any updates on this issue ?

**Comment by siegmund-beckmann-gmbh** [comment]
We are experiencing the same problem with 2.8.18 since changing from a single mosquitto-Broker to a VerneMQ-Broker-Cluster.

Is there any way of throttling on the client side ?

**Comment by mmben** [comment]
We are experiencing the problem as well. In our case it occurs when we start up the application. We initially subscribe to many retained topics also containing wildcards (e.g. LevelA/+/LevelC/+ which is addressing around 300+ retained messages). That results in many received messages of which some are not received.

**Comment by ducanh2110** [comment]
any update?
