### ISSUE TITLE
Question: MQTT node.js is able to work with Node.JS Clustering? 

### ISSUE THREAD

**Issue by amirzandi** [mqttjs/MQTT.js#907]

**Comment by OmgImAlexis** [comment]
Yes.

Please close this issue.

**Comment by TheBeachMaster** [comment]
I have not had any success with this, in most cases the client gets kicked out the connection gets discarded by the broker. Are there docs for this...

Say for something like: 

```js
const cluster = require("cluster");
const numCPUs = require("os").cpus().length;
if (cluster.isMaster) {
  for (let index = 0; index < numCPUs; index++) {
    cluster.fork();
  }
// establish connection and reconnection
}
else {
// on message handlers here
}
```

Using the above leads to getting kicked out by the broker.

But putting `on-message` handlers on "master" works (but defeats the purpose of wanting to cluster the clients)
