### ISSUE TITLE
How use MQTT.js with weapp

### ISSUE THREAD

**Issue by guakeliao** [mqttjs/MQTT.js#908]
Sorry ! 
I copied dist/mqtt.js to my weapp's project then required it. like that

```js
var mqtt = require('../../MQTT/mqtt.js')
const client = mqtt.connect('wss://****:8884')
```

but it can not work . Console show the error:

 sdk uncaught third Error 
 WS is not a constructor 
 TypeError: WS is not a constructor

Would you please provide a simple working example of weapp? thinks

**Comment by RangerMauve** [comment]
Hi, I would suggest looking at some of the [existing issues](https://github.com/mqttjs/MQTT.js/issues?utf8=%E2%9C%93&q=weapp) related to weapp to see if there are any examples there.
