### ISSUE TITLE
Can't connect to Amazon MQ (mqtts protocol)

### ISSUE THREAD

**Issue by ffxsam** [mqttjs/MQTT.js#910]
I'm trying to use this library with Amazon MQ and not having much luck. I'm attempting to connect using this URL:

`mqtts://xxx.mq.us-east-1.amazonaws.com:8883` (user and password are in the options)

Which results in this error in the browser console:

```
WebSocket connection to 'wss://xxx.mq.us-east-1.amazonaws.com:8883/' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE
```

**Comment by RangerMauve** [comment]
Hi, are you sure that Amazon MQ supports websockets on that port?

**Comment by ffxsam** [comment]
Never mind, we figured it out. Didn't realize we have to use wss on the client side.. so we switched to Amazon MQ port 61619 (WSS).

**Comment by RangerMauve** [comment]
Glad you figured it out. 😀
