### ISSUE TITLE
No error is emitted on wrong IP

### ISSUE THREAD

**Issue by bicccio** [mqttjs/MQTT.js#911]
If the connection IP is wrong no event error is emitted, The client will try to reconnect forever.
I've looked inside the client code and there's no way to circumvent the problem (without changing it).

**Comment by lucacalcaterra** [comment]
Same issue for me even the mqtt server is offline...

**Comment by darahayes** [comment]
Hey there, I see this issue also. It happens whenever any part of the connection config is wrong (port, hostname, protocol, etc). It's a huge issue but I'm thinking of cases where maybe an application is deployed with an incorrect config and maybe I would want to produce some logs or exit the process in when this occurs.

@mcollina do you think it is a good idea for the client to be able to detect this case and emit an event? Or do you think it makes more sense to solve it at an application level?

For anyone experiencing this issue - you could implement some basic workaround like this.

```js
const TIMEOUT = 10

setTimeout(() => {
  if (!client.connected) {
    console.log(`client not connected after ${TIMEOUT} seconds`)
	// process.exit(1) if you wish
  }
}, TIMEOUT * 1000)
```

^^ You could even wrap this up in a function that returns a promise which would allow you to `await` to see if the connection was successful. But I'm not sure if this is a good thing to do.

**Comment by darahayes** [comment]
^^ Original comment said it's a huge issue. I meant to type it's not a huge issue 😄

**Comment by KrishnaPG** [comment]
Looks like there are events that might help:
````
const MQTT = require('mqtt');
const mqttClient = MQTT.connect("ws://test.mosquitto.org:8080");

mqttClient.on('connect', () => console.log("connected"));
mqttClient.on('reconnect', () => console.log("reconnecting"));
mqttClient.on('error', () => console.log("connect error"));
````
The `reconnecting` event may repeat and handling it may be of some help. However it would be better if this library improves this current design:
- the reason for reconnect is currently unavailable - it should be made know somehow what was the previous connect error
- the reconnect attempt count is not available - if this is the first reconnect attempt or 100th reconnect attempt?
- no upper limit options for the reconnects

A reconnection *after* a successful connect (and drop), is far different from a reconnection that never connected earlier. Both scenarios need separately logic and a well designed library allows that.
