### ISSUE TITLE
mqtt.Client#end([force], [options], [cb])

### ISSUE THREAD

**Issue by AuspeXeu** [mqttjs/MQTT.js#918]
Clients' end function does not accept options as documented. See line 609 in `client.js`.

**Comment by scarry1992** [comment]
That signature isn`t in npm yet. If you want new features of mqtt 5, you need to install mqttjs from master.

**Comment by AuspeXeu** [comment]
So which one is lacking behind? the `README.md` or the `client.js`?

**Comment by scarry1992** [comment]
Where from you install mqttjs? Or where you compare readme and client.js?

**Comment by AuspeXeu** [comment]
Well the files on the current master branch on GitHub do not comply with each other.

**Comment by scarry1992** [comment]
What do you mean don`t comply with each other? And what I must see in https://github.com/mqttjs/MQTT.js/blob/62641d6ec22e4e51b1cacd3f692965d44a09d03e/lib/client.js#L609

**Comment by AuspeXeu** [comment]
Ah, it seems like the file changed since I opened this issue and all is okay now.
