### ISSUE TITLE
Is there any parameter about client-Id, user and password?

### ISSUE THREAD

**Issue by MY201314MY** [mqttjs/MQTT.js#920]
Here is the part of code to connect the OneNET mqtt server in python:
import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish

hostname = '183.230.40.39'  
port = 6002  
clientid = '509109399'  
username = '179383'  
password = ''  
topic = 'raspberry ' 

But how can I use the JavaScript library to connect?I haven’t find any relevant parameter except client Id.

**Comment by nuhamind2** [comment]
[here](https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options)

**Comment by MY201314MY** [comment]
It’s the main page of the repository,Are you sure?

**Comment by nuhamind2** [comment]
There if field to set username and password on the Client constructor

**Comment by MY201314MY** [comment]
Thank you, I will see it clearly.

**Comment by nuhamind2** [comment]
This example also show how to set username and password
[https://github.com/mqttjs/MQTT.js/blob/master/examples/wss/client.js](https://github.com/mqttjs/MQTT.js/blob/master/examples/wss/client.js)
