### ISSUE TITLE
Weapp When I disconnect, the console prints an error

### ISSUE THREAD

**Issue by Likunone** [mqttjs/MQTT.js#921]
WeChat Mini Program
![image](https://user-images.githubusercontent.com/15193414/53617805-c2216080-3c23-11e9-8ec9-a0a0d4882063.png)
![image](https://user-images.githubusercontent.com/15193414/53617813-cbaac880-3c23-11e9-95ac-4457577ae322.png)

**Comment by Likunone** [comment]
WeChat Mini Program

**Comment by SyMind** [comment]
@Likunone You need point out version you use.

**Comment by Likunone** [comment]
@SyMind Thank you to solve
