### ISSUE TITLE
Participation in the Package Maintenence WG

### ISSUE THREAD

**Issue by Eomm** [mqttjs/MQTT.js#922]
Hi @mcollina, I wrote to you as our main reference for MQTT.js
We are continuing on the first steps of "how to help" the pilot packages joint in the Package Maintenance WG  https://github.com/nodejs/package-maintenance/issues/142

It would be awesome if you could reply to [this survey](https://github.com/nodejs/package-maintenance/blob/master/pilots/SURVEY.md) in order to start and find the best way to collaborate 👍 

Feel free to reply directly on this issue or open a PR in the https://github.com/nodejs/package-maintenance/ repository with the replies in the file `pilots/MQTTjs/SURVEY_ANSWER.md`.

Thank you very much

**Comment by mcollina** [comment]
Done in https://github.com/nodejs/package-maintenance/pull/175.
