### ISSUE TITLE
Small program debugging tools can be connected to the normal, the real machine is not

### ISSUE THREAD

**Issue by Likunone** [mqttjs/MQTT.js#923]
WeChat Mini Program Small program debugging tools can be connected to the normal, the real machine is not.
Is it an MQTT bug or a WeChat bug?

Version 2.18.8 of MQTT used

Development tool log
![mqtt.js](https://mmbiz.qlogo.cn/mmbiz_png/XxMFqWWH28SNVic2RR3pWRAWh3X4oMnia6RTicTKibTlw4zefFQcVOkp4x0IT99F35Qc6z0PJITzDuEWbKgmKP0v0Q/0?wx_fmt=png)
Real machine log
![mqtt.js](https://mmbiz.qlogo.cn/mmbiz_png/XxMFqWWH28SNVic2RR3pWRAWh3X4oMnia6S60KOMnTYG7rRkFicvzxQFSSf0dCIsK0t7ysKl0W2hhTKbicBo9ExEsA/0?wx_fmt=png)

**Comment by SyMind** [comment]
@Likunone This is the limitation of the webscoket interface provided by Wechat Mini Program. You can ask for help in the Wechat Mini Program Community.
https://developers.weixin.qq.com/

**Comment by xuhongv** [comment]
@Likunone 请问您解决了吗？

**Comment by SyMind** [comment]
@xuhongv 可能是端口问题，真机可能不可使用除了443 或 80 以外的端口。

**Comment by Likunone** [comment]
@SyMind I'm using port 443

**Comment by xuhongv** [comment]
@Likunone 以及解决并且再次封装，现在我已经开源出来作为一个工程了！可以在微信真机运行！https://github.com/xuhongv/WeChatEsp8266Lib
