### ISSUE TITLE
can't use {protocolVersion:5} when use connect function

### ISSUE THREAD

**Issue by WengangChen** [mqttjs/MQTT.js#927]
`
ret = mqtt.connect("192.168.21.129",{protocolVersion:4, protocol:'mqtt'});
`
can connect my server, but when I change into
`
ret = mqtt.connect("192.168.21.129",{protocolVersion:5, protocol:'mqtt'});
`
my server can not receive connect require.
server code is clone from emqx/emqx-rel in github.

**Comment by linjunjj** [comment]
@WengangChen  You can use protocalVersion:5, After all, MQTT5 is a relatively new protocol for MQTT3.1.

**Comment by DanielPeinhopf** [comment]
I also want to use MQTT 5 but i think the problem is the dependency to mqtt-packet 5.6.0 in the npm package "mqtt 2.18.8". This version doesnt support v5 and should be updated to the 6.1.2 which has support for v5.
