### ISSUE TITLE
Multiple mqtt connections will be lost in the weapp?

### ISSUE THREAD

**Issue by 849511441** [mqttjs/MQTT.js#928]
For example, I want to multi-instantiate a few mqtts in a small program, which says that WebSockets can be up to five. I have studied how many mqtts can be connected without sending heartbeat, but only one heartbeat can be disconnected. I would like to ask if there is any way to adapt to multiple mqtt connections to see if there is a God modifying the source code and so on.

**Comment by 849511441** [comment]
this.data.client = mqtt.connect(host1, this.data.options);
    this.data.client.on('connect', function(connack) {
      wx.showToast({
        title: 'success1'
      })
    })
		that.data.client2 = mqtt.connect(host2, that.data.options);
		that.data.client2.on('connect', function(connack) {
			wx.showToast({
				title: 'success12'
			})
		})

Only one mqtt instance is online?

**Comment by SyMind** [comment]
https://github.com/mqttjs/MQTT.js/issues/892

you can use the new implementation.

**Comment by 849511441** [comment]
What do you mean?

**Comment by SyMind** [comment]
In old version, use wx.connectSocket/wx.closesocket api to connect/close websocket. I have fixed it, but the mqtt.js not release.

https://developers.weixin.qq.com/miniprogram/en/dev/api/network-socket.html#wxclosesocket
