### ISSUE TITLE
连接的URL后面必须跟/mqtt是什么原因

### ISSUE THREAD

**Issue by zengyuanqiu** [mqttjs/MQTT.js#933]
文档里没解释url后面为什么要带上/mqtt
我连接时不带上/mqtt就连接不成功

**Comment by zengyuanqiu** [comment]
用mosca测试时不需要在后面加上/mqtt也能连接成功
但后台给的url地址不加/mqtt就连接不上
    例如后台给的地址是: iot.testurl.com:1883
    连接时要写成: mqtt.connect('ws://iot.testurl.com:1883/mqtt') 才能连接成功

**Comment by SyMind** [comment]
@zengyuanqiu 
区分环境或连接方式
