### ISSUE TITLE
how to update client's password?

### ISSUE THREAD

**Issue by chanelnumberfive** [mqttjs/MQTT.js#934]
i need to update the client's password with no disconnect, how?

**Comment by RangerMauve** [comment]
You should be able to update `client.options.password` and the next time it opens a socket it'll use the new password.

Does that help?

**Comment by chanelnumberfive** [comment]
> You should be able to update `client.options.password` and the next time it opens a socket it'll use the new password.
> 
> Does that help?

it work ,thank you very much!
