### ISSUE TITLE
[ help] How can I use it in the WeChat MINI  APP？

### ISSUE THREAD

**Issue by jiejieTop** [mqttjs/MQTT.js#935]
Hello, this framework is very good, I really want to use it, and also need it very much.but I can't use it directly on the WeChat MINI  APP. How can I use it in the WeChat MINI APP? What preparations do I need to make?

**Comment by jiejieTop** [comment]
When I added [MQTT.js folder] to my project, Show this error:
![image](https://user-images.githubusercontent.com/41819258/55298370-d5f8f600-545f-11e9-80a6-07b5c1a69e7f.png)

**Comment by SyMind** [comment]
@jiejieTop 
WeChat App can resolve Shebang correctly.

**Comment by SyMind** [comment]
@mcollina Is it necessary to add Shebang in mqtt.js?

**Comment by jiejieTop** [comment]
> @mcollina Is it necessary to add Shebang in mqtt.js?

Hello,my name is jiejie,Thank you for your reply, I have used another mqtt.js, but I also want to use this framework.

**Comment by isharrrry** [comment]
WTF Shebang
