### ISSUE TITLE
Not able to publish message via event listener function

### ISSUE THREAD

**Issue by Haider8** [mqttjs/MQTT.js#938]
I am using this module in my vue.js project. The client is successfully connected to the broker, made locally using mosquitto but i am unable to publish the publish.

This is the code
```
<b-button @click="buttonClicked()">Send Hi !</b-button>
```
This ```@click``` function is defined here:
```
<script>
import { client, MQTT_TOPIC } from '../mqtt'

export default {
  methods: {
    buttonClicked: function() {
      client.publish(MQTT_TOPIC, 'hi')
    }
  }
}
</script>
```
And this is my mqtt.js file:
```
const mqtt = require('mqtt')

const MQTT_TOPIC = 'test'
const MQTT_ADDR = 'tcp://localhost'
// const MQTT_PORT = 1883

const client = mqtt.connect(MQTT_ADDR, {
  clientId: 'bgtestnodejs',
  protocolId: 'MQIsdp',
  protocolVersion: 3,
  connectTimeout: 1000,
  debug: true
})

client.subscribe(MQTT_TOPIC)

export { client, MQTT_TOPIC }
```
Any help would be highly appreciated.
Thanks in advance :)

**Comment by Haider8** [comment]
@mcollina Can you please help me

**Comment by RangerMauve** [comment]
Hi, please don't tag collaborators directly. 😅

Could you give some more details about any errors you have in the JavaScript console and what your Mosquitto configuration looks like?

Are you able to publish to that topic using the Mosquitto CLI?

**Comment by RangerMauve** [comment]
Also, please note that you can't have multiple connections with the same ID

**Comment by Haider8** [comment]
I am able to publish message by mosquitto cli. Also the client id is
unique.

**Comment by RangerMauve** [comment]
What are you subscribed to to verify that it's being published?
Are there any errors in the mosquitto logs?

It looks like you're using `tcp` which doesn't work in the browser.

**Comment by Haider8** [comment]
I have setup one client locally. On this if I send message from my android
it gets printed there. But if I try to publish the message from my vue app
using mqtt.js nothing gets printed although it is connected to the broker.

What should I write in place of tcp then?

Thanks for listening replying to me 😀

**Comment by RangerMauve** [comment]
Ideally, you should be using WebSocket if you want to target browsers. Here's a [random guide](http://www.steves-internet-guide.com/mqtt-websockets/) which might help.

Is your Vue app running in a browser?

**Comment by Haider8** [comment]
Yes, it is running on a web browser.

**Comment by RangerMauve** [comment]
It's kinda weird that it's able to create a connection, then. 😅
But yeah, websockets are a must to get it working in browsers.

**Comment by Haider8** [comment]
Okay. Thank you very much.
I will try with web sockets and will let you know then.

**Comment by Haider8** [comment]
@RangerMauve Still not able to resolve this issue. 
I have the address to ```MQTT_ADDR = 'ws://127.0.0.1:1883'```. The error ```WebSocket connection to 'ws://127.0.0.1:1883/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET``` is shown on my google chrome console. 

And this is shown for the broker on my terminal:
```
1555394559: New connection from 127.0.0.1 on port 1883.
1555394559: Socket error on client <unknown>, disconnecting.
```

**Comment by RangerMauve** [comment]
Are you sure that's the port that the websocket server is running on?
