### ISSUE TITLE
server side received QoS 3

### ISSUE THREAD

**Issue by coyzeng** [mqttjs/MQTT.js#939]
mqtt.js connect to server, server side received QoS value is 3. Server implement used netty mqtt

**Comment by scarry1992** [comment]
Value 3 speaks about error on subscribe in mqtt 3.1.1

**Comment by CoyZeng** [comment]
> Value 3 speaks about error on subscribe in mqtt 3.1.1
Code sample like
<script src="https://unpkg.com/mqtt@2.18.8/dist/mqtt.min.js"></script>
 <script>
    var clientId = 'mqttjs_' + Math.random().toString(16).substr(2, 8)
    var client = mqtt.connect('mqtt://ducesoft.com:1883')
 </script>
Other mqtt client implements can connect and publish message, but mqtt.js payload server side validate failed. 
Browser console output **WebSocket connection to 'ws://ducesoft.com:1883/' failed: Connection closed before receiving a handshake response**
