### ISSUE TITLE
TypeError: WS is not a constructor when url use 'ws:' in WeChat Mini Program

### ISSUE THREAD

**Issue by aifeier** [mqttjs/MQTT.js#940]
when I use 'wxs' ,it is ok ,but use 'ws',it is wrong，
is it can't use 'ws'? 
but when I test ,I only have 'ws' 

ws://10.49.2.153:1883 is wrong  but wxs://10.49.2.153:1883 is ok

**Comment by xuhongv** [comment]
试下这个已经集成MQTT.js库的开源项目：https://github.com/xuhongv/WeChatMiniEsp8266
