### ISSUE TITLE
Handling of multiple subscribe and callbacks

### ISSUE THREAD

**Issue by jasonayre** [mqttjs/MQTT.js#941]
For awhile I thought this was due to my usage of rabbitmq mqtt/webmqtt implementation, but after looking at the code, it seems like it's a client issue, unless I am missing something. Easier to explain issue with use case first (which contains a wonky workaround I am applying):

``` javascript
    mqtt_client.subscribe(`match/actions/${id}`, { qos: 1, retain: false }, function() {
      mqtt_client.on('message', function(topic, message, packet) {
        if(topic === `match/actions/${id}`) {
          handleAction(message.toString());
        }
      })
    });

    mqtt_client.subscribe(`match/sync/${id}`, { qos: 1, retain: false }, function() {
      mqtt_client.on('message', function(topic, message, packet) {
        if(topic === `match/sync/${id}`) {
          handleSyncRequest(message.toString());
        }
      })
    });

    mqtt_client.subscribe(`match/inspect/${id}`, { qos: 1, retain: false }, function() {
      mqtt_client.on('message', function(topic, message, packet) {
        if(topic === `match/inspect/${id}`) {
          handleInspectRequest(message.toString());
        }
      })
    });
```

You can see the intent, as well as the wonky workaround I applied to get it to do what I expected it to above. - Basically, whenever any of the subscriptions are matched, every on.message will have it's callback invoked, which seems really surprising to me.

Am I missing something here or is that how it's supposed to be working?

If I'm not missing something, and the spec doesn't handle this or whatever, I think it could still be solved fairly simply by returning a subscription object rather than the client itself, which would wrap the on message event and route it to the correct callback by matching its topic, for example:

``` javascript
mqtt_client.subscribe(`match/inspect/${id}`, { qos: 1, retain: false }).on('message', function() {
 
});
```

or

``` javascript
let subscription = mqtt_client.subscribe(`match/inspect/${id}`, { qos: 1, retain: false})
subscription.on('message', function() {
});
```

**Comment by jschank** [comment]
I thought this was strange too. Having essentially a single conduit through which all messages go, and then the need to pluck out the ones you want.

**Comment by yamato225** [comment]
In paho-mqtt(Python), we can use `message_callback_add` method.
https://www.eclipse.org/paho/clients/python/docs/#callbacks

I want same function in MQTT.js.
