### ISSUE TITLE
为什么用 npm下载的库，不支持支付宝小程序连接？

### ISSUE THREAD

**Issue by xuhongv** [mqttjs/MQTT.js#944]
- 见到你们说明文档，使用 `npm install mqtt run` 得到的是 2.18.8 版本，但是我看了代码，压根不支持 alis 连接？怎么回事？

**Comment by SyMind** [comment]
@xuhongv 没有release

**Comment by 894827077** [comment]
现在不支持支付宝的mqtt 了吗  alis  我这边报错了
![image](https://user-images.githubusercontent.com/23007977/71614586-7cd51300-2be7-11ea-9031-4e75f1482186.png)

**Comment by SyMind** [comment]
import { connect } from 'mqtt';
const client  = connect('alis://test.mosquitto.org', { my } );

支付宝小程序需要将 my 变量最为 options 传入

**Comment by 894827077** [comment]
![V(PDKA8T57C@NCP}(1{Z1_3](https://user-images.githubusercontent.com/23007977/71638270-aac56080-2c96-11ea-89fd-26867fb27eba.png)
我mqtt地址是没有问题的 微信的可以跑通但是 支付宝的我用真机、模拟器调试都提示 这个错误

**Comment by 894827077** [comment]
![}Y8M50B~I1AGB9@ ZU67Z@T](https://user-images.githubusercontent.com/23007977/71638314-64bccc80-2c97-11ea-8b21-7dce8475f51a.png)
模块引入成功了

**Comment by 894827077** [comment]
我昨天问支付宝官方 说 不支持mqtt协议 不知道是不是跟这个有关系?

**Comment by SyMind** [comment]
@894827077 你照着我说的试一下再说啊

**Comment by 894827077** [comment]
第二个参数是必填的嘛

**Comment by 894827077** [comment]
还是提示 Cannot read property 'connectSocket' of undefined

**Comment by 894827077** [comment]
好像是我wss连接的问题

**Comment by 894827077** [comment]
https连接我配置好了  支付宝的还是连不上 方便给看下吗
下面是微信跟h5的成功的截图 支付宝 还是上面的那个 错误截图
![wx](https://user-images.githubusercontent.com/23007977/71640031-b37d5d00-2cbd-11ea-80d6-87373e816c9b.png)
![h5](https://user-images.githubusercontent.com/23007977/71640032-b415f380-2cbd-11ea-97a5-151adbde17c6.png)

**Comment by 894827077** [comment]
![wx](https://user-images.githubusercontent.com/23007977/71640041-cbed7780-2cbd-11ea-8b16-e34c1ebfcd5b.png)
![h5](https://user-images.githubusercontent.com/23007977/71640042-cbed7780-2cbd-11ea-81d1-efc1f76e1c6a.png)

**Comment by 894827077** [comment]
这个是支付宝的错误
![eacca346dfb309c2ae249dfa4514837](https://user-images.githubusercontent.com/23007977/71640081-782f5e00-2cbe-11ea-9490-64b58e06cd9f.png)

**Comment by xuhongv** [comment]
不要用虚拟机调试！用真机调试！支付宝有这个坑！！！

**Comment by 894827077** [comment]
> 不要用虚拟机调试！用真机调试！支付宝有这个坑！！！
> […](#)
> 在2020年1月1日，下午5：45，894827077 ***@***.***>标题：这个是支付宝的错误—您收到此消息是因为您修改了打开/关闭状态。直接回复此电子邮件，在GitHub上查看或取消订阅。
是真机调试的 感觉这个库有点问题 
我引入了你的 xmqtt.js  真机就可以跑通了   mqtt.js库真机就是跑不通

**Comment by 894827077** [comment]
是真机调试的 感觉这个库有点问题 
我引入了你的 xmqtt.js  真机就可以跑通了   mqtt.js的 库真机就是跑不通

**Comment by 894827077** [comment]
> 不要用虚拟机调试！用真机调试！支付宝有这个坑！！！
> […](#)
> 在 2020年1月1日，下午5:45，894827077 ***@***.***> 写道： ﻿ 这个是支付宝的错误 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

不过有个问题 接受/发布的数据怎么传给后台 在用http请求过去?
比如 对A主题发布了一个消息 前端收到后 在通过http接口请求吧数据给后台吗

**Comment by xuhongv** [comment]
这个是 websocket 知识了。已经补充

**Comment by 894827077** [comment]
已经补充？在哪呀 大佬

**Comment by xuhongv** [comment]
自行脑补！百度
