### ISSUE TITLE
WeChat mini program can't load Plugin when I imported mqtt.js

### ISSUE THREAD

**Issue by wugaoxue** [mqttjs/MQTT.js#947]

**Comment by wugaoxue** [comment]
when I load plugin in my WeChat mini program I get this problem:
![1557122759(1)](https://user-images.githubusercontent.com/46316669/57208786-2ab40180-7008-11e9-9730-bbf68e6b3d2a.png)
what should I do ?

**Comment by xuhongv** [comment]
- 试下这个已经集成MQTT.js库的开源项目：https://github.com/xuhongv/WeChatMiniEsp8266

**Comment by wangko27** [comment]
> * 试下这个已经集成MQTT.js库的开源项目：https://github.com/xuhongv/WeChatMiniEsp8266

你这个是不行的，真机调试就报错，不是域名不合法，而是js toString方法不存在

**Comment by xuhongv** [comment]
我在qq群里面有二十几个人真机调试都没报错，截图看看报错信息。

**Comment by isharrrry** [comment]
> * 试下这个已经集成MQTT.js库的开源项目：https://github.com/xuhongv/WeChatMiniEsp8266

client.connected 一直为true，掉线了也为true，怎么解决
