### ISSUE TITLE
Getting the value of the topic immediately after the subscription?

### ISSUE THREAD

**Issue by 9223000** [mqttjs/MQTT.js#955]
The event client.on('message') is called only after the publication in the topic. It is necessary immediately after the client subscribes to the topic, get the current values of the topic in the broker.
How can I get the value of the topic immediately after the subscription?

**Comment by 9223000** [comment]
The decisions are clear, this is governed by the MQTT itself and it is necessary that the publisher flag the message on Retain = true.

client.publish('topic', 'value', { qos: 0, retain: true })

In details:
https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/

I close the question :-)

**Comment by redboltz** [comment]
That is MQTT specification. If you want to receive immediately after subscription, you need to set RETAIN flag when you publish the message.

See

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901104

> When a new Non‑shared Subscription is made, the last retained message, if any, on each matching topic name is sent to the Client as directed by the Retain Handling Subscription Option.
