### ISSUE TITLE
Issue while reconnecting in react native

### ISSUE THREAD

**Issue by nageshjawanjal** [mqttjs/MQTT.js#957]
![reconnect issue](https://user-images.githubusercontent.com/46245074/58961346-8d92e700-87c6-11e9-9a25-89e7942bd9e9.png)
.
Hello. I'm using react-native-mqtt-client. I'm trying to reconnect the server but it's not connecting after I restart the wifi.

**Comment by gbalduzzi** [comment]
How did you manage to get react-native-mqtt-client working? I got error for missing nodejs dependecies
