### ISSUE TITLE
Version 3.0.0 cantnot used in wechat mini app on rela machine

### ISSUE THREAD

**Issue by fangsj** [mqttjs/MQTT.js#961]
Hi, 3.0.0 mqttjs cant run on real machine, but 2.x is OK

**Comment by xuhongv** [comment]
实现微信小程序连接mqtt服务器，可控制esp8266智能硬件等需求。 https://github.com/xuhongv/WeChatMiniEsp8266

**Comment by whisper-bye** [comment]
+1
