### ISSUE TITLE
3.0 not support client.subscribe({view_server: 1})

### ISSUE THREAD

**Issue by jaskle** [mqttjs/MQTT.js#965]
3.0 not support client.subscribe({view_server: 1})

**Comment by DotChris** [comment]
Apparently, `{'test1': {qos: 0}` is now the way to do this, a little over a year ago as apart of #827 

>* object which has topic names as object keys and as value the QoS, like {'test1': 0, 'test2': 1}.

became

>* object which has topic names as object keys and as value the options, like {'test1': {qos: 0}, 'test2': {qos: 2}}.

So this could be closed.
