### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ievgennaida** [mqttjs/MQTT.js#966]
Sometimes I have TypeError: Cannot read property 'length' of undefined
   "mqtt":  "3.0.0",

**granted is undefined.** 

- MQTT is configured to unsubscribe
- broker connection is unstable. Authorization is used.
- Heavy messages publishing: more that 60 msg per second 

>   this.outgoing[packet.messageId] = {
>     volatile: true,
>     cb: function (err, packet) {
>       if (!err) {
>         var granted = packet.granted
>         for (var i = 0; i < granted.length; i += 1) {
>           subs[i].qos = granted[i]
>         }
>       }
>       callback(err, subs)
>     }
>   }
> 

TypeError: Cannot read property 'length' of undefined
    at cb (\node_modules\mqtt\lib\client.js:629:37)
    at cb (\node_modules\mqtt\lib\client.js:1425:15)
    at Store.del (\node_modules\mqtt\lib\store.js:106:5)
    at MqttClient._handleAck (\node_modules\mqtt\lib\client.js:1218:26)
    at MqttClient._handlePacket (\node_modules\mqtt\lib\client.js:358:12)
    at work (\node_modules\mqtt\lib\client.js:283:12)
    at Writable.writable._write (\node_modules\mqtt\lib\client.js:294:5)
    at doWrite (\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Writable.write (\node_modules\readable-stream\lib\_stream_writable.js:334:11)

Windows 10.

**Comment by SebastianNarz** [comment]
I have the same error. Once a week my client application crashes. My client application is publishing round about 50 msg per second and also uses a store (nedb). Also running on Windows, but Server 2019. Broker is RabbitMQ. Did you find a way to solve it?

**Comment by ievgennaida** [comment]
In my case it happened on windows as well with the mosquito server. The issue was reproduced only once. the external store is not used, QoS1, QoS2 are used, sometimes service is offline

**Comment by SebaNar** [comment]
Have you implemented a workaround for that to keep the client application up? Would be nice to get a hint!

**Comment by ievgennaida** [comment]
Sorry, no, while I was not able to reproduce it for a second time.

**Comment by ievgennaida** [comment]
@SebaNar have you fixed your issue?

**Comment by ievgennaida** [comment]
> @SebaNar have you fixed your issue?

I don't remember details, but lib has a few bugs.  it's possible to fix and needs to be digged with error handling on the initial subscription

**Comment by SebaNar** [comment]
> > @SebaNar have you fixed your issue?
> 
> I don't remember details, but lib has a few bugs. it's possible to fix and needs to be digged with error handling on the initial subscription

No, was not able to reproduce with current versions.

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists
