### ISSUE TITLE
weapp's real device environment report ERROR: undefined function socketTask.onmessage callback

### ISSUE THREAD

**Issue by workzj** [mqttjs/MQTT.js#968]
I used mqtt.js in my weapp's project ,  in Simulator of PC is run well .
But in real device environment , it report the error :
gameThirdScriptError undefined;at socketTask.onmessage callback function undefined.

===================================

this is the callback function code :

  socketTask.onMessage(function (res) {
    var data = res.data

    if (data instanceof ArrayBuffer) data = Buffer.from(data)
    else data = Buffer.from(data, 'utf8')
    proxy.push(data)
  })

#### used browserify webpack build the mqtt.js lib 

why ?

**Comment by workzj** [comment]
what diffrent with Simulator and  real device environment ? why Simulator environment is running well ?

**Comment by workzj** [comment]
The problem is solved.

it's a weapp 's bug , the api setInterval(https://developers.weixin.qq.com/minigame/dev/api/base/timer/setInterval.html),last paramer can not pass null array. so , before using this api , check the parameter
：

change mqttjs source:

this._interval = setInterval(callback, interval, this._args);

to :

if(args.length === 0){

        this._interval = setInterval(callback, interval);

    }else{

        this._interval = setInterval(callback, interval, this._args);

    }

it's ok. (this bug only in wechat version 7.0 on android platform)

**Comment by Bravo123** [comment]
> The problem is solved.
> 
> it's a weapp 's bug , the api setInterval(https://developers.weixin.qq.com/minigame/dev/api/base/timer/setInterval.html),last paramer can not pass null array. so , before using this api , check the parameter
> ：
> 
> change mqttjs source:
> 
> this._interval = setInterval(callback, interval, this._args);
> 
> to :
> 
> if(args.length === 0){
> 
> ```
>     this._interval = setInterval(callback, interval);
> 
> }else{
> 
>     this._interval = setInterval(callback, interval, this._args);
> 
> }
> ```
> 
> it's ok. (this bug only in wechat version 7.0 on android platform)

I meet the same problem. 
I try to use your method, hope it can solve my problem at the same time
