### ISSUE TITLE
Amazon MQ connect ?????

### ISSUE THREAD

**Issue by dluisbrbr** [mqttjs/MQTT.js#970]
Hello

I'm trying to use package mqtt to access the Amazon MQ service, but to no avail.
`var mqtt = require('mqtt')

var options = {
   username: 'xxxxxxxx',
   password: 'xxxxxxxxxxx',
   clientId: 'mqttjs_' + Math.random().toString(16).substr(2, 8)
};

//var client  = mqtt.connect(options);

var client  = mqtt.connect( 'wss://b-xxxxxxxxxxxxxxxxxxxxxxxxxxxx.mq.us-west-2.amazonaws.com:61619', options);

client.on("error",function(error){
    console.log("Error :" + error);
    process.exit(1)
});

client.on("disconnect",function(error){
    console.log("You are Disconnected ....." + error);
    process.exit(1)
});

client.on("end",function(error){
    console.log("You are ended ....." + error);
    process.exit(1)
});

client.on("close",function(){
    console.log("You are closed .....");
    process.exit(1)
}); 
 
client.on('connect', function () {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})
 
client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})`

Could someone guide me how to proceed to make the connection?

If possible, sample code.

Tks

**Comment by evlach** [comment]
I had a similar issue with AWS before and I solved it by increasing the `connectTimeout` - depending also to which region you are trying to connect.
