### ISSUE TITLE
connect with mqtt 3.1.1

### ISSUE THREAD

**Issue by fanW96** [mqttjs/MQTT.js#974]
I wanna to  connect an server(ssl) with mqtt 3.1.1, so in the options, how to set the protocol, protocolId and protocolversion?

**Comment by freew01f** [comment]
the same with me
Ihava to change paho to connect mqtt 3.1.1

**Comment by viniciusbo** [comment]
Readme currently states: 

> Another breaking change is that MQTT.js now defaults to MQTT v3.1.1, so to support old brokers, please read the client options doc.

So it's there's no need for extra config. Btw, MQTT v3.1.1 is referred as protocol version 4.
