### ISSUE TITLE
why the example code not working??????

### ISSUE THREAD

**Issue by mxsmxm** [mqttjs/MQTT.js#977]
**this is the example code:**

var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://test.mosquitto.org')

client.on('connect', function () {
  client.subscribe('presence', function (err) {
    if (!err) {
      client.publish('presence', 'Hello mqtt')
    }
  })
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})

when i copy this and run with nodejs, it doesn't work ,who can tell me why,thanks.

here is my package.json dependcencies:
  "dependencies": {
    "mqtt": "^3.0.0"
  }

here is my node command to run this code(I use vscode):
node test.js

the terminal does not print anything!!!!
@ mcollina

**Comment by fonym** [comment]
Hi mxsmxm,

If you add the following code to the bottom of your test.js file it should give you some more answers.

    client.on('close', function () {
        console.log("Connection closed");
        client.end();
    });
