### ISSUE TITLE
Stored data is written simultaneously with live data

### ISSUE THREAD

**Issue by ghost** [mqttjs/MQTT.js#978]
If the client disconnects and then reconnects (or is restarted), live data and data that was stored while disconnected are both written to broker simultaneously.

My expectation is that stored data should be written first and once we've caught up, newer data will be transmitted.

This can cause problems for stream processing applications downstream - e.g. windowing.

**Comment by KrishnaPG** [comment]
Facing similar issue - old/saved messages are coming **after** new data. Ref. below screenshot - those at top are the latest received, but sent earlier (timestamps are from the sender). 

The final 'connected' message is somewhere in the between (sandwiched below the old data).

![image](https://user-images.githubusercontent.com/4610831/64084778-1ed51380-cd4c-11e9-80ce-8d628e723910.png)

**Comment by jlawrencecfm** [comment]
I'm trying to write a test case to reproduce it but am having some real trouble replicating in the testing framework
