### ISSUE TITLE
Cannot import in React Native

### ISSUE THREAD

**Issue by navata** [mqttjs/MQTT.js#979]
I have use this package in React Native, but It's miss some package dependencies url, events ...
`var mqtt = require("mqtt"); // error`
![Photo1566195740 5246081](https://user-images.githubusercontent.com/16706514/63243348-75d6e500-c284-11e9-8e89-9f9dcfcbbbeb.jpg)

But it's working well in children folder as below:
`var mqtt = require("mqtt/dist/mqtt");`

Who can help me to explain this issue?

**Comment by Lindsor** [comment]
Looks like you need to do a specific step to make it borwser compatible you cant just import it:
https://www.npmjs.com/package/mqtt#browserify

Have you tried this?

**Comment by aleluis777** [comment]
> I have use this package in React Native, but It's miss some package dependencies url, events ...
> `var mqtt = require("mqtt"); // error`
> ![Photo1566195740 5246081](https://user-images.githubusercontent.com/16706514/63243348-75d6e500-c284-11e9-8e89-9f9dcfcbbbeb.jpg)
> 
> But it's working well in children folder as below:
> `var mqtt = require("mqtt/dist/mqtt");`
> 
> Who can help me to explain this issue?


But connected, could you send messages? I try to import "mqtt / dist / mqtt" but it doesn't recognize anything. I cannot subscribe nor can I broadcast
