### ISSUE TITLE
Error event not firing after unsuccessful connection attempt

### ISSUE THREAD

**Issue by basickarl** [mqttjs/MQTT.js#984]
The mqtt library (version 2.18.8) doesn't seem to emit an error event when the library unsuccessful attempts to connect to an incorrect url:
```
    console.log('connecting to:', url);
    const mqttClient = mqtt.connect(url);

    mqttClient.on('error', function error(error: object): void {
        console.log(error);
    });

    mqttClient.on('connect', function connect(connack: object): void {
        console.log('connected to', url);
    });
```
Results in just:
```
connecting to: mqtt://localhost:8883
```
Using the `mqtt://test.mosquitto.org` url works though:
```
    console.log('connecting to:', 'mqtt://test.mosquitto.org');
    const mqttClient = mqtt.connect('mqtt://test.mosquitto.org');

    mqttClient.on('error', function error(error: object): void {
        console.log(error);
    });

    mqttClient.on('connect', function connect(connack: object): void {
        console.log('connected to', 'mqtt://test.mosquitto.org');
    });
```
Results in:
```
connecting to: mqtt://test.mosquitto.org
connected to mqtt://test.mosquitto.org
```

I read the documentation at it states on the error event (https://github.com/mqttjs/MQTT.js#event-error):
```
Emitted when the client cannot connect (i.e. connack rc != 0) or when a parsing error occurs.
```
It also should timeout after 30 seconds, which I've waited longer than.

Something I've misunderstood?

**Comment by atrovato** [comment]
Same for me.
I saw it tries to reconnect undefinitely.

**Comment by LordShadowen** [comment]
Same exact here

**Comment by YoDaMa** [comment]
yes @atrovato the client will try to reconnect indefinitely. Where is the documentation @basickarl that says it should timeout?

**Comment by YoDaMa** [comment]
When the `tls` layer receives a `connect ECONNREFUSED 127.0.0.1:8883` because of the bad hostname, the behavior of the client is to suppress the error. See [here.](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L300)

**Comment by basickarl** [comment]
@YoDaMa Hiya! 
As I read and interpret the documentation an event error should fire after an unsuccessful connection attempt as it says in the documentation:

> Event 'error'
> function (error) {}
> 
> Emitted when the client cannot connect (i.e. connack rc != 0) or when a parsing error occurs.

As you see it says `client cannot connect`.

That is what the documentation says. I read your post and it seems like an error event is not fired but suppressed? This means the documentation is inconsistent with what is happening hence the confusion from my side (and this issue).

I think what we as developers would like to know from this library is how to handle behavior such as incorrect hostname. I was expecting an error event because I'd like to handle this scenario (would like to give feedback to the person using the application that the hostname is incorrect). You mentioned a close event is emitted, would that be a suitable place to handle this? If so, how would we know the difference between a clean closing of the stream and a unsuccessful connection attempt?

**Comment by YoDaMa** [comment]
So when the client is not connected and the connection comes back refused presently, a `offline` event is emitted, with no information. So you can imagine like this: 
```
[connecting to bad port]--->[port says NO!] --->[stream receives error and emits 'close']--       
--->[client tries to reconnect]---->[during reconnect client emits 'offline']--->[client reconnects]---
-------->[connecting to bad port]...........
```
So if you really wanted to, you could listen on this offline emit and then throw an error. 
```js
//your-code.js

client.on('offline', function () { throw Error('oh no') }
```
The event error should fire if `connack rc != 0`, like you said, but we never get a `connack` to respond to since this is a socket error. So MQTT.js does not presently throw on the errors you are seeing.

I'm seeing if we can add better error handling specifically for `ECONNREFUSED` port errors in the PR #1051 .

**Comment by robertsLando** [comment]
Try to reproduce the issue with MQTT v5 and feel free to reopen in case the bug persists
