### ISSUE TITLE
Unable to connect to broker using TLS 

### ISSUE THREAD

**Issue by BradPrit09** [mqttjs/MQTT.js#995]
When trying to connect to broker (Mosquitto) using TLS it returns an error:

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('NaNError: write EPROTO 1208:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert
protocol version:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1536:SSL alert number 70\n')
    at MqttClient.emit (events.js:187:17)
    at TLSSocket.handleTLSerrors (F:\Data Bucket\node_modules\mqtt\lib\connect\tls.js:40:18)
    at TLSSocket.emit (events.js:203:15)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at TLSSocket.Socket._destroy (net.js:613:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)

I looked for help everywhere my I don't get it right.

My code:

```
var mongodb  = require('mongodb');
var mqtt     = require('mqtt');
var config   = require('./config');
var fs       =require('fs');



var KEY;
    try {
        KEY = fs.readFileSync("./cert/m2mqtt_srv.key");
        } 
        catch (error) {
           if (error.code==='ENOENT') {
               console.log("KEY File not Found !")
           }
           else{
               throw error;
           }
    }


var CERT ;
try {
    CERT = fs.readFileSync("./cert/m2mqtt_srv.crt");
    } 
    catch (error) {
       if (error.code==='ENOENT') {
           console.log("CERT File not Found !")
       }
       else{
           throw error;
       }
}
var CAFile;
try {
    CAFile = [fs.readFileSync('./cert/m2mqtt_ca.crt')];
    } 
    catch (error) {
       if (error.code==='ENOENT') {
           console.log("CA File not Found !")
       }
       else{
           throw error;
       }
}



var options={
    clientId: 'mqttjs_'+Math.random().toString(16).substr(2,8),
    host: config.mqtt.hostname,
    port: 8883,
    protocol: 'mqtts',   
    protocolId: 'MQTT',
    ca: CAFile,
    key: KEY,
    cert: CERT,
    secureProtocol: 'TLSv1_method',
    protocolId: 'MQTT',
    protocolVersion: 4,
    ciphers :'ALL'
    
};

// var mqttUri  = 'mqtt://' + config.mqtt.hostname + ':' + config.mqtt.port;

var client   = mqtt.connect(options);

client.on('connect', function () {
    client.subscribe(config.mqtt.namespace);
});

var mongoUri = 'mongodb://' + config.mongodb.hostname + ':' + config.mongodb.port + '/' + config.mongodb.database;
mongodb.MongoClient.connect(mongoUri, function(error, database) {
    if(error != null) {
        throw error;
    }

    var collection = database.collection(config.mongodb.collection);
    collection.createIndex( { "topic" : 1 } );

    client.on('message', function (topic, message) {
        var messageObject = {
            topic: topic,
            message: message.toString()
        };

        collection.insert(messageObject, function(error, result) {
            if(error != null) {
                console.log("ERROR: " + error);
            }
        });
    });
});


```

**Comment by jdiamond** [comment]
You told MQTT.js to use TLS v1, but the mosquitto docs say it only supports 1.1, 1.2, and 1.3.

**Comment by BradPrit09** [comment]
If I use secure Protocol 1.1 then also its' showing same error 

> You told MQTT.js to use TLS v1, but the mosquitto docs say it only supports 1.1, 1.2, and 1.3.

**Comment by jdiamond** [comment]
Why set `secureProtocol` at all? Node.js docs say not setting it should allow it to try from TLSv1 to TLSv1.2.

Do you have any mosquitto configuration that would change it from its defaults? Have you been able to connect to mosquitto with any other client successfully?

Use `openssl s_client -connect yourhost:8883` and you should see what protocol gets negotiated in the output.

**Comment by jdiamond** [comment]
I use MQTT.js to connect to brokers using TLS almost exclusively so it's hard to imagine this isn't a configuration error. Please reopen if you have more information.

**Comment by BradPrit09** [comment]
I got it connected. Thanks
